"""The curated trivia question bank — a large, diverse, multi-topic pool.

A single flat tuple of :class:`~kenning.twitch.economy.games.TriviaQuestion`
spanning many categories (science, space, history, geography, world capitals,
pop culture, movies & TV, music, sports, video games, literature, food & drink,
nature & animals, technology & computing, mythology, art, math/logic, and
general knowledge) — plus the original Valorant/gaming questions so the channel
keeps its on-theme rounds.

Each entry is ``TriviaQuestion(question, answer, accept=(...))`` where:
  * ``question`` is a clear, unambiguous one-line prompt,
  * ``answer`` is the concise canonical answer (the one Ultron announces), and
  * ``accept`` is a tuple of additional acceptable spellings/aliases.

Matching is case-insensitive + whitespace-stripped against the canonical answer
OR any alias (see :meth:`Trivia.check_answer`). Keep answers SHORT and aliases
natural (digits vs words, common abbreviations, alternate names) so a correct
chatter is not robbed by a spelling nitpick, while wrong answers still fail.

ANTICHEAT (BR-P1): pure data + stdlib typing only. No imports beyond the
sibling ``games`` dataclass.
"""
from __future__ import annotations

from kenning.twitch.economy.games import TriviaQuestion as _Q

__all__ = ["TRIVIA_QUESTIONS"]


# ---------------------------------------------------------------------------
# The bank. Grouped by category only for readability — at runtime it is one
# flat pool. Answers verified for correctness; aliases cover the natural ways a
# chatter would type the same answer (number words, abbreviations, alt names).
# ---------------------------------------------------------------------------
TRIVIA_QUESTIONS: tuple[_Q, ...] = (
    # --- Valorant / gaming (kept from the original pool) -------------------
    _Q("How many rounds does it take to win a standard Valorant match?", "13"),
    _Q("What is the name of Jett's ultimate ability?", "blade storm",
       accept=("bladestorm",)),
    _Q("Which Valorant agent can resurrect a fallen ally?", "sage"),
    _Q("What is the buy phase timer in Valorant, in seconds?", "30",
       accept=("thirty",)),
    _Q("What is the name of Omen's ultimate ability?", "from the shadows"),
    _Q("Which Valorant map is set in Morocco?", "pearl"),
    _Q("How many players are on each team in a Valorant match?", "5",
       accept=("five",)),
    _Q("What is the name of Reyna's heal ability?", "devour"),
    _Q("Which Valorant agent uses an owl drone to scout?", "sova"),
    _Q("How many seconds does the Spike take to detonate after being planted?",
       "45", accept=("forty-five", "forty five")),
    _Q("Which Valorant map was the first added after launch?", "icebox"),
    _Q("In Minecraft, which hostile mob explodes when it gets close to you?",
       "creeper"),
    _Q("What is the best-selling video game of all time?", "minecraft"),
    _Q("In Pac-Man, what does Pac-Man eat to turn the ghosts blue?",
       "power pellet", accept=("power pellets", "power-up", "energizer")),
    _Q("Which company created the game Fortnite?", "epic games",
       accept=("epic",)),
    _Q("In the Pokemon games, what type is super effective against Water?",
       "grass", accept=("electric",)),
    _Q("What is the name of the princess Mario usually rescues?", "peach",
       accept=("princess peach",)),
    _Q("Which video game features a silent protagonist named Gordon Freeman?",
       "half-life", accept=("half life", "halflife")),

    # --- Science ----------------------------------------------------------
    _Q("What is the chemical symbol for gold?", "au"),
    _Q("What gas do plants absorb from the atmosphere for photosynthesis?",
       "carbon dioxide", accept=("co2", "co-2")),
    _Q("How many bones are in the adult human body?", "206",
       accept=("two hundred six", "two hundred and six")),
    _Q("What is the most abundant gas in Earth's atmosphere?", "nitrogen"),
    _Q("What is the powerhouse of the cell?", "mitochondria",
       accept=("the mitochondria", "mitochondrion")),
    _Q("What is the chemical symbol for iron?", "fe"),
    _Q("What force keeps us anchored to the ground?", "gravity"),
    _Q("What is the hardest known natural material?", "diamond"),
    _Q("At what temperature in Celsius does water boil at sea level?", "100",
       accept=("one hundred",)),
    _Q("What is the pH of pure water?", "7", accept=("seven",)),
    _Q("Which metal in human blood binds and carries oxygen?", "iron"),
    _Q("What is the speed of light commonly rounded to, in km per second?",
       "300000", accept=("300,000", "three hundred thousand")),
    _Q("What scientist developed the theory of general relativity?",
       "einstein", accept=("albert einstein",)),
    _Q("What is H2O more commonly known as?", "water"),
    _Q("What part of the human body produces insulin?", "pancreas"),
    _Q("How many chambers does a human heart have?", "4", accept=("four",)),
    _Q("What is the lightest element on the periodic table?", "hydrogen"),
    _Q("What blood type is the universal donor?", "o negative",
       accept=("o-", "o neg", "type o negative")),

    # --- Space / astronomy ------------------------------------------------
    _Q("Which planet is known as the Red Planet?", "mars"),
    _Q("What is the closest planet to the Sun?", "mercury"),
    _Q("What is the largest planet in our solar system?", "jupiter"),
    _Q("What is the name of Earth's only natural satellite?", "the moon",
       accept=("moon", "luna")),
    _Q("Which galaxy is Earth located in?", "the milky way",
       accept=("milky way",)),
    _Q("Who was the first person to walk on the Moon?", "neil armstrong",
       accept=("armstrong",)),
    _Q("What is the name of the force that pulls everything toward a black "
       "hole's center?", "gravity"),
    _Q("How many planets are in our solar system?", "8", accept=("eight",)),
    _Q("What star is at the center of our solar system?", "the sun",
       accept=("sun", "sol")),
    _Q("Which planet has the most prominent ring system?", "saturn"),
    _Q("What is the name of the first artificial satellite launched into "
       "space?", "sputnik", accept=("sputnik 1", "sputnik-1")),
    _Q("What was the name of the telescope launched in 1990 that orbits "
       "Earth?", "hubble", accept=("hubble space telescope",)),

    # --- History ----------------------------------------------------------
    _Q("In what year did World War II end?", "1945"),
    _Q("Who was the first President of the United States?",
       "george washington", accept=("washington",)),
    _Q("Which ancient civilization built the pyramids of Giza?", "egyptians",
       accept=("ancient egyptians", "egypt", "ancient egypt")),
    _Q("What wall fell in 1989, reuniting a divided city?", "berlin wall",
       accept=("the berlin wall",)),
    _Q("Who painted the ceiling of the Sistine Chapel?", "michelangelo"),
    _Q("In what year did the Titanic sink?", "1912"),
    _Q("Which queen ruled the United Kingdom for over 70 years until 2022?",
       "elizabeth ii", accept=("queen elizabeth ii", "elizabeth the second",
                                "queen elizabeth")),
    _Q("What document, signed in 1776, declared American independence?",
       "declaration of independence",
       accept=("the declaration of independence",)),
    _Q("Who was the British Prime Minister during most of World War II?",
       "winston churchill", accept=("churchill",)),
    _Q("Which empire was ruled by Julius Caesar?", "roman empire",
       accept=("rome", "the roman empire", "roman")),
    _Q("What year did the first man land on the Moon?", "1969"),
    _Q("Which explorer is credited with reaching the Americas in 1492?",
       "christopher columbus", accept=("columbus",)),

    # --- Geography --------------------------------------------------------
    _Q("What is the largest country in the world by area?", "russia"),
    _Q("What is the longest river in the world?", "the nile",
       accept=("nile", "nile river")),
    _Q("Which is the largest ocean on Earth?", "pacific",
       accept=("pacific ocean", "the pacific ocean")),
    _Q("What is the smallest country in the world?", "vatican city",
       accept=("vatican", "the vatican")),
    _Q("On which continent is the Sahara Desert located?", "africa"),
    _Q("What is the tallest mountain on Earth above sea level?",
       "mount everest", accept=("everest",)),
    _Q("Which country has the most people in the world?", "india"),
    _Q("What is the largest desert in the world?", "antarctica",
       accept=("antarctic", "the antarctic")),
    _Q("Which US state is the largest by area?", "alaska"),
    _Q("What body of water separates England from France?",
       "english channel", accept=("the english channel", "the channel")),
    _Q("Which African country was never colonized by a European power?",
       "ethiopia"),
    _Q("What is the longest wall in the world, visible across China?",
       "great wall of china", accept=("the great wall of china",
                                       "great wall", "the great wall")),

    # --- World capitals ---------------------------------------------------
    _Q("What is the capital of France?", "paris"),
    _Q("What is the capital of Japan?", "tokyo"),
    _Q("What is the capital of Australia?", "canberra"),
    _Q("What is the capital of Canada?", "ottawa"),
    _Q("What is the capital of Egypt?", "cairo"),
    _Q("What is the capital of Brazil?", "brasilia", accept=("brasília",)),
    _Q("What is the capital of Italy?", "rome"),
    _Q("What is the capital of Russia?", "moscow"),
    _Q("What is the capital of South Korea?", "seoul"),
    _Q("What is the capital of Spain?", "madrid"),
    _Q("What is the capital of Germany?", "berlin"),
    _Q("What is the capital of Greece?", "athens"),

    # --- Pop culture / movies & TV ----------------------------------------
    _Q("Which superhero is known as the Caped Crusader?", "batman"),
    _Q("In the Harry Potter series, what is the name of Harry's pet owl?",
       "hedwig"),
    _Q("What is the highest-grossing film of all time (unadjusted)?",
       "avatar"),
    _Q("Which animated movie features a snowman named Olaf?", "frozen"),
    _Q("Who directed the movie Jaws and Jurassic Park?",
       "steven spielberg", accept=("spielberg",)),
    _Q("In Star Wars, who is Luke Skywalker's father?", "darth vader",
       accept=("vader", "anakin", "anakin skywalker")),
    _Q("What is the name of the coffee shop in the TV show Friends?",
       "central perk"),
    _Q("Which movie features the quote, 'I'll be back'?", "the terminator",
       accept=("terminator",)),
    _Q("In The Lion King, what is the name of Simba's father?", "mufasa"),
    _Q("What fictional metal is Wolverine's skeleton coated with?",
       "adamantium"),
    _Q("Which streaming show features a series of deadly children's games for "
       "money?", "squid game", accept=("the squid game",)),
    _Q("Who plays Iron Man in the Marvel Cinematic Universe?",
       "robert downey jr", accept=("robert downey jr.", "rdj",
                                    "robert downey junior")),

    # --- Music ------------------------------------------------------------
    _Q("Which British band released the album 'Abbey Road'?", "the beatles",
       accept=("beatles",)),
    _Q("Who is known as the 'King of Pop'?", "michael jackson"),
    _Q("How many strings does a standard guitar have?", "6", accept=("six",)),
    _Q("Which instrument has 88 keys?", "piano", accept=("the piano",)),
    _Q("Who sang the 1992 hit 'I Will Always Love You'?",
       "whitney houston"),
    _Q("What genre of music is Bob Marley most associated with?", "reggae"),
    _Q("Which artist released the album '1989' and the song 'Shake It Off'?",
       "taylor swift"),
    _Q("How many lines are in a traditional limerick?", "5", accept=("five",)),
    _Q("What is the best-selling music album of all time?", "thriller"),
    _Q("Which classical composer was deaf for much of his later life?",
       "beethoven", accept=("ludwig van beethoven",)),

    # --- Sports -----------------------------------------------------------
    _Q("How many players are on a soccer team on the field at one time?",
       "11", accept=("eleven",)),
    _Q("In which sport would you perform a slam dunk?", "basketball"),
    _Q("How many points is a touchdown worth in American football?", "6",
       accept=("six",)),
    _Q("Which country has won the most FIFA World Cups?", "brazil"),
    _Q("In tennis, what is the term for zero points?", "love"),
    _Q("How often are the Summer Olympic Games held, in years?", "4",
       accept=("four", "every four years")),
    _Q("What sport is played at Wimbledon?", "tennis"),
    _Q("How many holes are played in a standard round of golf?", "18",
       accept=("eighteen",)),
    _Q("In which sport is the term 'home run' used?", "baseball"),
    _Q("How many rings are on the Olympic flag?", "5", accept=("five",)),
    _Q("What is the maximum score possible in a single game of ten-pin "
       "bowling?", "300", accept=("three hundred",)),

    # --- Literature -------------------------------------------------------
    _Q("Who wrote the play 'Romeo and Juliet'?", "shakespeare",
       accept=("william shakespeare",)),
    _Q("In which novel would you meet a character named Sherlock Holmes?",
       "a study in scarlet", accept=("the adventures of sherlock holmes",
                                      "sherlock holmes")),
    _Q("Who wrote the dystopian novel '1984'?", "george orwell",
       accept=("orwell",)),
    _Q("What is the first book of the Christian Bible?", "genesis"),
    _Q("Who wrote 'Pride and Prejudice'?", "jane austen", accept=("austen",)),
    _Q("In Greek-inspired fiction, what boy never grows up in J. M. Barrie's "
       "tale?", "peter pan"),
    _Q("Who is the author of the Harry Potter book series?",
       "j.k. rowling", accept=("jk rowling", "j. k. rowling", "rowling",
                                "joanne rowling")),
    _Q("Which Roald Dahl book features a boy who wins a golden ticket?",
       "charlie and the chocolate factory"),
    _Q("Who wrote 'The Adventures of Tom Sawyer'?", "mark twain",
       accept=("twain", "samuel clemens")),

    # --- Food & drink -----------------------------------------------------
    _Q("What fruit is traditionally used to make wine?", "grapes",
       accept=("grape",)),
    _Q("What is the main ingredient in guacamole?", "avocado",
       accept=("avocados",)),
    _Q("Which spice is the most expensive in the world by weight?",
       "saffron"),
    _Q("What type of pasta is shaped like little bow ties?", "farfalle"),
    _Q("From which country did sushi originate?", "japan"),
    _Q("What is the main ingredient in traditional hummus?", "chickpeas",
       accept=("chickpea", "garbanzo beans", "garbanzo")),
    _Q("What beverage is made from roasted, ground coffee beans?", "coffee"),
    _Q("What is the most consumed beverage in the world after water?", "tea"),
    _Q("What nut is used to make marzipan?", "almonds", accept=("almond",)),
    _Q("What is the name of the Italian dish of thin-sliced raw beef?",
       "carpaccio"),

    # --- Nature & animals -------------------------------------------------
    _Q("What is the largest land animal on Earth?", "elephant",
       accept=("african elephant", "elephants")),
    _Q("What is the fastest land animal?", "cheetah"),
    _Q("How many legs does a spider have?", "8", accept=("eight",)),
    _Q("What is the largest mammal in the world?", "blue whale",
       accept=("the blue whale",)),
    _Q("What do bees collect from flowers to make honey?", "nectar"),
    _Q("Which bird is known for its ability to mimic human speech?", "parrot",
       accept=("parrots",)),
    _Q("What is a group of lions called?", "a pride", accept=("pride",)),
    _Q("What is the only mammal capable of true flight?", "bat",
       accept=("bats",)),
    _Q("What is the tallest animal in the world?", "giraffe"),
    _Q("How many hearts does an octopus have?", "3", accept=("three",)),
    _Q("What animal is known as man's best friend?", "dog", accept=("dogs",)),

    # --- Technology & computing -------------------------------------------
    _Q("What does CPU stand for?", "central processing unit"),
    _Q("Who co-founded Microsoft with Paul Allen?", "bill gates",
       accept=("gates", "william gates")),
    _Q("What does 'WWW' stand for?", "world wide web",
       accept=("the world wide web",)),
    _Q("What company makes the iPhone?", "apple"),
    _Q("In computing, how many bits are in a byte?", "8", accept=("eight",)),
    _Q("What does 'HTML' stand for?", "hypertext markup language"),
    _Q("What programming language shares its name with a type of snake?",
       "python"),
    _Q("Who is the founder and CEO of Tesla and SpaceX?", "elon musk",
       accept=("musk",)),
    _Q("What does 'RAM' stand for in computers?", "random access memory"),
    _Q("What search engine's name has become a verb for looking things up "
       "online?", "google"),
    _Q("What is the binary number system's base?", "2", accept=("two",)),

    # --- Mythology --------------------------------------------------------
    _Q("In Greek mythology, who is the king of the gods?", "zeus"),
    _Q("In Norse mythology, who wields the hammer Mjolnir?", "thor"),
    _Q("In Greek mythology, who is the god of the sea?", "poseidon"),
    _Q("What is the name of the winged horse in Greek mythology?", "pegasus"),
    _Q("In Greek mythology, who flew too close to the sun on wax wings?",
       "icarus"),
    _Q("In Egyptian mythology, who is the god of the underworld and the dead?",
       "anubis", accept=("osiris",)),
    _Q("What three-headed dog guards the underworld in Greek mythology?",
       "cerberus"),
    _Q("In Roman mythology, who is the counterpart of the Greek god Zeus?",
       "jupiter"),
    _Q("In Greek mythology, what creature had snakes for hair and turned "
       "people to stone?", "medusa"),

    # --- Art --------------------------------------------------------------
    _Q("Who painted the Mona Lisa?", "leonardo da vinci",
       accept=("da vinci", "leonardo",)),
    _Q("Which artist cut off part of his own ear?", "van gogh",
       accept=("vincent van gogh",)),
    _Q("What art movement is Pablo Picasso most associated with?", "cubism"),
    _Q("In which country is the Louvre museum located?", "france"),
    _Q("Which Dutch artist painted 'The Starry Night'?", "van gogh",
       accept=("vincent van gogh",)),
    _Q("What painting technique uses small dots of color?", "pointillism"),
    _Q("Who sculpted the statue of David in Florence?", "michelangelo"),

    # --- Math / logic -----------------------------------------------------
    _Q("What is 7 times 8?", "56", accept=("fifty-six", "fifty six")),
    _Q("How many sides does a hexagon have?", "6", accept=("six",)),
    _Q("What is the value of pi rounded to two decimal places?", "3.14"),
    _Q("What is the square root of 144?", "12", accept=("twelve",)),
    _Q("How many degrees are in a right angle?", "90", accept=("ninety",)),
    _Q("What is 15 percent of 200?", "30", accept=("thirty",)),
    _Q("How many sides does a triangle have?", "3", accept=("three",)),
    _Q("What is the next prime number after 7?", "11", accept=("eleven",)),
    _Q("How many degrees are in a full circle?", "360",
       accept=("three hundred sixty", "three hundred and sixty")),
    _Q("What do you call a number that can only be divided by 1 and itself?",
       "prime number", accept=("prime", "a prime number", "a prime")),

    # --- General knowledge ------------------------------------------------
    _Q("How many colors are in a rainbow?", "7", accept=("seven",)),
    _Q("What is the currency used in Japan?", "yen", accept=("japanese yen",)),
    _Q("How many days are there in a leap year?", "366",
       accept=("three hundred sixty-six", "three hundred and sixty six")),
    _Q("What is the tallest building in the world?", "burj khalifa",
       accept=("the burj khalifa",)),
    _Q("How many continents are there on Earth?", "7", accept=("seven",)),
    _Q("What is the freezing point of water in Fahrenheit?", "32",
       accept=("thirty-two", "thirty two")),
    _Q("How many minutes are in a full day?", "1440",
       accept=("1,440", "one thousand four hundred forty")),
    _Q("What color do you get when you mix blue and yellow?", "green"),
    _Q("How many letters are in the English alphabet?", "26",
       accept=("twenty-six", "twenty six")),
    _Q("What is the largest organ in the human body?", "skin",
       accept=("the skin",)),
    _Q("How many sides does a stop sign have?", "8", accept=("eight",)),
    _Q("What is the most spoken language in the world by native speakers?",
       "mandarin", accept=("mandarin chinese", "chinese")),
    _Q("How many zeros are in one million?", "6", accept=("six",)),
    _Q("What is the national animal of China?", "panda",
       accept=("giant panda", "the panda")),

    # === EXPANSION 2026-07-08 (doubles the bank; LRU rotation keeps a
    # question from repeating in a stream until the pool has cycled) =======
    _Q("In Valorant, what do attackers plant to win a round?", "spike"),
    _Q("What in-game currency buys weapons at the start of a Valorant round?",
       "credits", accept=("creds",)),
    _Q("Which Nintendo plumber wears green and is Mario's brother?", "luigi"),
    _Q("In The Legend of Zelda, what is the name of the green-clad hero?",
       "link"),
    _Q("In Among Us, what is the sabotaging player called?",
       "impostor", accept=("the impostor", "imposter")),
    _Q("Which company makes the PlayStation console?", "sony"),
    _Q("In Sonic the Hedgehog, what does Sonic collect as he runs?",
       "rings", accept=("gold rings",)),
    _Q("What is the best-selling home video game console of all time?",
       "playstation 2", accept=("ps2", "playstation two")),
    _Q("In Grand Theft Auto, what does 'GTA' stand for?", "grand theft auto"),
    _Q("Which handheld console did Nintendo launch in 1989?",
       "game boy", accept=("gameboy",)),
    _Q("In Tetris, what is the name of the straight four-block piece?",
       "i-piece", accept=("i piece", "the i-piece")),
    _Q("What blocky sandbox game features a default character named Steve?",
       "minecraft"),
    _Q("What is the chemical symbol for oxygen?", "o"),
    _Q("What is the chemical symbol for sodium?", "na"),
    _Q("What is the center of an atom called?",
       "nucleus", accept=("the nucleus",)),
    _Q("What is the process by which liquid water becomes vapor?",
       "evaporation"),
    _Q("What planet's day is longer than its year?", "venus"),
    _Q("What is the study of living organisms called?", "biology"),
    _Q("What subatomic particle carries a negative charge?",
       "electron", accept=("electrons",)),
    _Q("What is the freezing point of water in Celsius?",
       "0", accept=("zero",)),
    _Q("What organ pumps blood through the human body?",
       "heart", accept=("the heart",)),
    _Q("What is the largest bone in the human body?",
       "femur", accept=("the femur", "thigh bone")),
    _Q("Which vitamin does the human body produce from sunlight?",
       "vitamin d", accept=("d",)),
    _Q("What is the chemical symbol for potassium?", "k"),
    _Q("Which planet is famous for a great red spot storm?", "jupiter"),
    _Q("What is the name of the path a planet takes around the Sun?",
       "orbit", accept=("its orbit", "an orbit")),
    _Q("Which planet is tilted on its side and rotates that way?", "uranus"),
    _Q("What do you call a rock from space that burns up in the atmosphere?",
       "meteor", accept=("a meteor", "shooting star")),
    _Q("How long does light from the Sun take to reach Earth, in minutes?",
       "8", accept=("eight", "about 8", "roughly eight")),
    _Q("What is the second-largest planet in our solar system?", "saturn"),
    _Q("What is the name of NASA's rover that landed on Mars in 2021?",
       "perseverance"),
    _Q("What galaxy is our nearest large neighbor?",
       "andromeda", accept=("the andromeda galaxy",)),
    _Q("What is a group of stars forming a recognizable pattern called?",
       "constellation", accept=("a constellation",)),
    _Q("Which planet is nicknamed Earth's twin for its similar size?",
       "venus"),
    _Q("What was the first country to put a human in space?",
       "soviet union", accept=("ussr", "russia", "the soviet union")),
    _Q("In what year did the American Civil War begin?", "1861"),
    _Q("Who was the leader of Nazi Germany during World War II?",
       "adolf hitler", accept=("hitler",)),
    _Q("Which ship carried the Pilgrims to America in 1620?",
       "the mayflower", accept=("mayflower",)),
    _Q("Who was the ancient Macedonian king who conquered a vast empire?",
       "alexander the great", accept=("alexander",)),
    _Q("What year did the Berlin Wall come down?", "1989"),
    _Q("Who led India's nonviolent independence movement?",
       "gandhi", accept=("mahatma gandhi",)),
    _Q("Which war was fought between the North and South of the United States?",
       "the civil war", accept=("civil war", "american civil war")),
    _Q("Who was assassinated in Dallas, Texas in 1963?",
       "john f. kennedy", accept=("jfk", "kennedy", "john f kennedy")),
    _Q("What ancient wonder stood in the harbor of Alexandria?",
       "the lighthouse", accept=("lighthouse of alexandria", "pharos")),
    _Q("Which civilization built Machu Picchu?",
       "the inca", accept=("inca", "incas", "the incas")),
    _Q("Who was the first woman to win a Nobel Prize?",
       "marie curie", accept=("curie",)),
    _Q("In what year did the United States declare independence?", "1776"),
    _Q("What is the smallest continent by land area?", "australia"),
    _Q("Which country is both in Europe and Asia and spans the most time zones?",
       "russia"),
    _Q("What is the largest island in the world?", "greenland"),
    _Q("Which mountain range separates Europe from Asia?",
       "the ural mountains", accept=("urals", "ural mountains", "the urals")),
    _Q("What is the deepest ocean trench on Earth?",
       "the mariana trench", accept=("mariana trench", "marianas trench")),
    _Q("Which country is shaped like a boot?", "italy"),
    _Q("What is the largest lake in Africa?",
       "lake victoria", accept=("victoria",)),
    _Q("Through which country does the Amazon River mainly flow?", "brazil"),
    _Q("What is the capital city with the highest elevation in the world?",
       "la paz"),
    _Q("Which US state is known as the Sunshine State?", "florida"),
    _Q("What line of latitude divides Earth into the northern and southern halves?",
       "the equator", accept=("equator",)),
    _Q("Which desert covers much of northern Africa?",
       "the sahara", accept=("sahara", "sahara desert")),
    _Q("What is the capital of China?", "beijing"),
    _Q("What is the capital of India?", "new delhi", accept=("delhi",)),
    _Q("What is the capital of the United Kingdom?", "london"),
    _Q("What is the capital of Mexico?", "mexico city"),
    _Q("What is the capital of Argentina?", "buenos aires"),
    _Q("What is the capital of the United States?",
       "washington", accept=("washington dc", "washington, d.c.", "washington d.c.")),
    _Q("What is the capital of Turkey?", "ankara"),
    _Q("What is the capital of Portugal?", "lisbon"),
    _Q("What is the capital of the Netherlands?", "amsterdam"),
    _Q("What is the capital of Ireland?", "dublin"),
    _Q("What is the capital of Sweden?", "stockholm"),
    _Q("What is the capital of Thailand?", "bangkok"),
    _Q("Which wizard trains Harry Potter as headmaster of Hogwarts?",
       "dumbledore", accept=("albus dumbledore",)),
    _Q("In the show Breaking Bad, what is the main character's teacher profession?",
       "chemistry teacher", accept=("chemistry", "teacher")),
    _Q("Which movie features a shark terrorizing a beach town?", "jaws"),
    _Q("What is the name of the toy cowboy in Toy Story?", "woody"),
    _Q("Which Disney movie features a mermaid named Ariel?",
       "the little mermaid", accept=("little mermaid",)),
    _Q("Who directed the Lord of the Rings film trilogy?",
       "peter jackson", accept=("jackson",)),
    _Q("What is the fictional African nation in Black Panther?", "wakanda"),
    _Q("In The Matrix, what color pill does Neo take to learn the truth?",
       "red", accept=("the red pill", "red pill")),
    _Q("Which sitcom is set in a bar 'where everybody knows your name'?",
       "cheers"),
    _Q("What is the name of the hobbit who carries the ring to Mordor?",
       "frodo", accept=("frodo baggins",)),
    _Q("Which superhero swings between buildings on webs?",
       "spider-man", accept=("spiderman", "spider man")),
    _Q("What galaxy-spanning franchise features Jedi and the Force?",
       "star wars"),
    _Q("Which Swedish group sang 'Dancing Queen'?", "abba"),
    _Q("How many keys are white on a standard piano?",
       "52", accept=("fifty-two", "fifty two")),
    _Q("What brass instrument is largest and lowest in pitch?",
       "tuba", accept=("the tuba",)),
    _Q("Which artist is nicknamed the 'Queen of Pop'?", "madonna"),
    _Q("What band was fronted by Freddie Mercury?", "queen"),
    _Q("How many musicians are in a quartet?", "4", accept=("four",)),
    _Q("What Italian word means to play music loudly?", "forte"),
    _Q("Which rapper released the album 'The Marshall Mathers LP'?", "eminem"),
    _Q("What family of instruments includes the violin and cello?",
       "strings", accept=("the string family", "string", "string family")),
    _Q("Which four-member band came from Liverpool in the 1960s?",
       "the beatles"),
    _Q("What do you call the speed or pace of a piece of music?", "tempo"),
    _Q("Which pop star is known for the hit 'Bad Romance'?",
       "lady gaga", accept=("gaga",)),
    _Q("How many players are on a basketball team on the court at once?",
       "5", accept=("five",)),
    _Q("In which sport is the Stanley Cup awarded?",
       "ice hockey", accept=("hockey",)),
    _Q("How many bases are on a baseball diamond?", "4", accept=("four",)),
    _Q("What country hosts the Wimbledon tennis tournament?",
       "england", accept=("united kingdom", "uk", "great britain")),
    _Q("In boxing, how many minutes is a standard professional round?",
       "3", accept=("three",)),
    _Q("What piece of equipment do you hit a puck with in hockey?",
       "a stick", accept=("stick", "hockey stick")),
    _Q("How many players are on a cricket team?", "11", accept=("eleven",)),
    _Q("In golf, what is one stroke under par on a hole called?",
       "birdie", accept=("a birdie",)),
    _Q("Which sport uses terms like 'strike' and 'spare'?", "bowling"),
    _Q("How long is a marathon, rounded to the nearest mile?",
       "26", accept=("twenty-six", "twenty six", "26 miles")),
    _Q("In American football, how many points is a field goal worth?",
       "3", accept=("three",)),
    _Q("Who wrote 'The Old Man and the Sea'?",
       "ernest hemingway", accept=("hemingway",)),
    _Q("In which novel does a whale named Moby Dick appear?",
       "moby dick", accept=("moby-dick",)),
    _Q("Who wrote the horror novel 'Dracula'?",
       "bram stoker", accept=("stoker",)),
    _Q("What is the name of the boy wizard in J.K. Rowling's series?",
       "harry potter", accept=("harry",)),
    _Q("Who wrote 'The Great Gatsby'?",
       "f. scott fitzgerald", accept=("fitzgerald", "f scott fitzgerald")),
    _Q("Which Charles Dickens novel features Ebenezer Scrooge?",
       "a christmas carol"),
    _Q("Who created the detective Hercule Poirot?",
       "agatha christie", accept=("christie",)),
    _Q("What epic poem by Homer tells of the Greek siege of Troy?",
       "the iliad", accept=("iliad",)),
    _Q("Who wrote 'The Adventures of Huckleberry Finn'?",
       "mark twain", accept=("twain", "samuel clemens")),
    _Q("In which fantasy series would you find the land of Narnia?",
       "the chronicles of narnia", accept=("chronicles of narnia", "narnia")),
    _Q("Who wrote 'Frankenstein'?", "mary shelley", accept=("shelley",)),
    _Q("What Japanese dish consists of vinegared rice and raw fish?", "sushi"),
    _Q("What is the primary ingredient in bread?", "flour"),
    _Q("What vegetable is used to make traditional kimchi?",
       "cabbage", accept=("napa cabbage",)),
    _Q("What is the hottest part of a chili pepper measured by?",
       "the scoville scale", accept=("scoville", "scoville scale", "scoville units")),
    _Q("What Italian dish is a flat round base topped with cheese and sauce?",
       "pizza"),
    _Q("What fruit is dried to make a raisin?", "grape", accept=("grapes",)),
    _Q("What is the main ingredient in traditional French fries?",
       "potatoes", accept=("potato",)),
    _Q("What is the name for a young sheep's meat?", "lamb"),
    _Q("What plant do we get chocolate from?",
       "cacao", accept=("cocoa", "cacao tree", "cocoa bean")),
    _Q("What alcoholic drink is made by fermenting barley and hops?", "beer"),
    _Q("What breakfast food is made from beaten, cooked eggs?",
       "omelette", accept=("omelet", "scrambled eggs")),
    _Q("What is the largest species of shark?",
       "whale shark", accept=("the whale shark",)),
    _Q("What do you call a baby kangaroo?", "joey", accept=("a joey",)),
    _Q("What is the only bird that can fly backwards?",
       "hummingbird", accept=("the hummingbird", "hummingbirds")),
    _Q("What is a group of wolves called?", "a pack", accept=("pack",)),
    _Q("What is the largest species of penguin?",
       "emperor penguin", accept=("the emperor penguin",)),
    _Q("How many legs does an insect have?", "6", accept=("six",)),
    _Q("What is the fastest bird in the world in a dive?",
       "peregrine falcon", accept=("the peregrine falcon", "falcon")),
    _Q("What amphibian starts life as a tadpole?",
       "frog", accept=("frogs", "a frog")),
    _Q("What is the largest living species of lizard?",
       "komodo dragon", accept=("the komodo dragon",)),
    _Q("What color are a flamingo's feathers?", "pink"),
    _Q("What is a female horse called?", "mare", accept=("a mare",)),
    _Q("Which sea creature has eight arms and can change color?",
       "octopus", accept=("an octopus", "the octopus")),
    _Q("What does 'GPU' stand for in computing?", "graphics processing unit"),
    _Q("Who founded the company Amazon?", "jeff bezos", accept=("bezos",)),
    _Q("What does 'URL' stand for?", "uniform resource locator"),
    _Q("What social media platform is known for short videos and a 'For You' page?",
       "tiktok"),
    _Q("What does 'AI' stand for?", "artificial intelligence"),
    _Q("What company developed the Windows operating system?", "microsoft"),
    _Q("What does 'USB' stand for?", "universal serial bus"),
    _Q("What is the name of Apple's voice assistant?", "siri"),
    _Q("In email, what does the 'cc' field stand for?", "carbon copy"),
    _Q("What does 'Wi-Fi' commonly let devices connect to?",
       "the internet", accept=("internet", "a network", "the network")),
    _Q("What company owns and operates the search engine and Android?",
       "google"),
    _Q("What does 'PDF' stand for?", "portable document format"),
    _Q("In Greek mythology, who is the goddess of love and beauty?",
       "aphrodite"),
    _Q("In Norse mythology, who is the trickster god?", "loki"),
    _Q("In Greek mythology, who holds the sky or the heavens on his shoulders?",
       "atlas"),
    _Q("In Greek mythology, what hero completed twelve labors?",
       "hercules", accept=("heracles",)),
    _Q("Who is the Roman god of war?", "mars"),
    _Q("In Egyptian mythology, who is the sun god?", "ra", accept=("re",)),
    _Q("What half-man, half-bull creature lived in the Labyrinth?",
       "the minotaur", accept=("minotaur",)),
    _Q("In Greek mythology, who is the messenger of the gods with winged sandals?",
       "hermes"),
    _Q("In Norse mythology, what is the rainbow bridge to Asgard called?",
       "bifrost", accept=("the bifrost",)),
    _Q("In Greek mythology, who opened a box releasing all the world's evils?",
       "pandora"),
    _Q("What is the Greek underworld ruled by Hades also called?",
       "the underworld", accept=("underworld", "hades")),
    _Q("Who painted 'The Persistence of Memory' with melting clocks?",
       "salvador dali", accept=("dali",)),
    _Q("What nationality was the painter Frida Kahlo?", "mexican"),
    _Q("Which artist is famous for painting soup cans and pop art?",
       "andy warhol", accept=("warhol",)),
    _Q("What is the art of beautiful handwriting called?", "calligraphy"),
    _Q("Which Renaissance artist painted 'The Last Supper'?",
       "leonardo da vinci", accept=("da vinci", "leonardo")),
    _Q("What do you call a painting of a person, especially the face?",
       "portrait", accept=("a portrait",)),
    _Q("In which city is the famous ceiling of the Sistine Chapel?",
       "vatican city", accept=("rome", "the vatican", "vatican")),
    _Q("What primary colors can be mixed to make orange?",
       "red and yellow", accept=("red & yellow",)),
    _Q("What is a sculpture made of many small tiles called?",
       "mosaic", accept=("a mosaic",)),
    _Q("Which artist painted 'Girl with a Pearl Earring'?",
       "vermeer", accept=("johannes vermeer",)),
    _Q("What is 9 times 9?", "81", accept=("eighty-one", "eighty one")),
    _Q("How many sides does an octagon have?", "8", accept=("eight",)),
    _Q("What is 100 divided by 4?",
       "25", accept=("twenty-five", "twenty five")),
    _Q("What is the perimeter term for the distance around a circle?",
       "circumference", accept=("the circumference",)),
    _Q("What is 2 to the power of 10?",
       "1024", accept=("1,024", "one thousand twenty-four")),
    _Q("How many degrees are in the angles of a triangle added together?",
       "180", accept=("one hundred eighty", "one hundred and eighty")),
    _Q("What do you call a four-sided shape with all equal sides?",
       "square", accept=("a square",)),
    _Q("What is 12 times 12?",
       "144", accept=("one hundred forty-four", "one hundred and forty four")),
    _Q("What is the only even prime number?", "2", accept=("two",)),
    _Q("What is one half written as a decimal?", "0.5", accept=(".5", "0.50")),
    _Q("How many minutes are in two hours?",
       "120", accept=("one hundred twenty",)),
    _Q("How many seconds are in a minute?", "60", accept=("sixty",)),
    _Q("What is the currency of the United Kingdom?",
       "pound", accept=("pound sterling", "british pound", "gbp")),
    _Q("How many months have 31 days?", "7", accept=("seven",)),
    _Q("What color is a ripe banana?", "yellow"),
    _Q("How many hours are in a day?",
       "24", accept=("twenty-four", "twenty four")),
    _Q("How many chess pieces does each player start with?",
       "16", accept=("sixteen",)),
    _Q("What is the currency used across most of the European Union?",
       "euro", accept=("the euro",)),
    _Q("How many weeks are in a year?",
       "52", accept=("fifty-two", "fifty two")),
    _Q("What do bees make that people eat?", "honey"),
    _Q("How many strings are on a violin?", "4", accept=("four",)),
    _Q("What is the first month of the year?", "january"),
    _Q("How many wheels does a standard car have?", "4", accept=("four",)),
    _Q("What gas do humans need to breathe to survive?", "oxygen"),
    _Q("How many players are on the field for one baseball team on defense?",
       "9", accept=("nine",)),
)
