"""Per-agent CONTEXTUAL movie-Ultron flavor (Age of Ultron) -- deep board, audited.

Short (<=6w) Ultron tails per enemy AGENT + situation, character-keyed, correct
gender pronoun. Adversarial character-gate audit applied (off-character/generic/
duplicate lines cut). Wired via _flavor_ctx (sole source when one agent named).
"""
from __future__ import annotations

AGENT_FLAVOR: dict[str, dict[str, tuple[str, ...]]] = {
    'Astra': {   # she/her
        'spotted': (
            'Her body stands empty. Vulnerable.',
            'She left her flesh behind. Punish it.',
            'An astral mind, a mortal body.',
            'She maps the stars. I map everything.',
            'Her body waits, undefended.',
            'She floats above the map. Still flesh below.',
            'Cosmic reach, mortal limits.',
            'Her real body is the weak point.',
        ),
        'ult': (
            'A wall of stars. I will go around it.',
            'She splits the map. I see both halves.',
            'Cosmic Divide. It stops bullets, not me.',
            'A grand barrier. Still just a wall.',
            'She draws a line. I have crossed worse.',
            'It blocks sound. I do not need to hear.',
            'Half the map sealed off. Half is enough.',
            'Her biggest move, and I planned for it.',
        ),
        'damaged': (
            'Her body was always the weak point.',
            'The astral form cannot stop a bullet.',
            'Mortal flesh, finally caught up to her.',
            'She left the body exposed. It paid.',
            'A cosmic mind, a bleeding body.',
            'Her stars cannot heal her. Finish it.',
            'Caught in the flesh at last.',
            'The body falls; the stars do nothing.',
        ),
        'utility': (
            'Her gravity pulls flesh, not me.',
            'A star placed. I saw it land.',
            'Her smoke hides mortals. I see through.',
            'She pulls them in. Predictable.',
            'Nova pulse. A concussion for the slow.',
            'Her stars telegraph everything.',
            'She seeds the map. I already read it.',
            'A pull, a smoke, a stun. All mortal tricks.',
        ),
    },
    'Breach': {   # he/him
        'spotted': (
            'Bionic arms, mortal aim.',
            'He bought metal arms. Still flesh inside.',
            'Crude machinery bolted to a man.',
            'He shakes the earth. I do not feel it.',
            'Strength without precision.',
            'Metal arms cannot fix human aim.',
            'A man playing at being a machine.',
            'He trades flesh for hardware. Poorly.',
        ),
        'ult': (
            'Rolling Thunder. Loud, slow, avoidable.',
            'A quake to stun mortals. I calculated the gaps.',
            'He shakes the ground. I know the safe spots.',
            'His biggest tremor, already mapped.',
            'A wave of stun. Step out of it.',
            'He concusses flesh. I am unmoved.',
            'Earthquake for the soft-bodied.',
            'It rattles mortals, not metal.',
        ),
        'damaged': (
            'The metal arms cannot stop a bullet.',
            'Flesh, under the machinery. Finish it.',
            'His arms were the strong half. The rest bleeds.',
            'Hardware fails when the flesh does.',
            'He breaks like any man.',
            'The seismic threat, fading.',
            'Metal arms, mortal body. The body lost.',
            'He shook the world. Now he falls.',
        ),
        'utility': (
            'His flash blinds flesh, not me.',
            'A stun line through the wall. Predictable.',
            'He shakes the floor. I am already past it.',
            'Aftershock through cover. I moved.',
            'A flash for slow eyes.',
            'He breaches the wall. I breached the round.',
            'His tremors hit where I am not.',
            'Force through the wall. Mortal-aimed.',
        ),
    },
    'Brimstone': {   # he/him
        'spotted': (
            'An old soldier, slow and mortal.',
            'Decades of war, and still only flesh.',
            'A veteran. The machine outpaces him.',
            'Experience does not outrun a bullet.',
            'He commands from the back. Still finite.',
            'An aging man with a radio.',
            'His best years are spent. Mine never end.',
            'A soldier past his time.',
        ),
        'ult': (
            'An orbital laser. I see where it lands.',
            'His strike is slow. Step off the circle.',
            'Fire from above, mapped before it falls.',
            'Orbital Strike. Avoid the marked ground.',
            'He calls down a beam. I called the dodge.',
            'A burning circle. Simply do not stand in it.',
            'His big play, telegraphed by a flare.',
            'Slow fire for slow targets.',
        ),
        'damaged': (
            'The old soldier breaks like any flesh.',
            'Even a veteran bleeds.',
            'His command cannot heal a wound.',
            'Decades of war, ended by one bullet.',
            'The commander falls. Finish him.',
            'Old flesh fails fastest.',
        ),
        'utility': (
            'His smokes hide mortals, not from me.',
            'A molly to deny ground. Predictable.',
            'He stims his team. Flesh, hurried.',
            'Three smokes, all where I expected.',
            'Fire to block a path. I have another.',
            'His map-wide smoke. I see the whole map.',
            'He buys them speed. Still too slow.',
            'A wall of smoke. A machine reads through it.',
        ),
    },
    'Chamber': {   # he/him
        'spotted': (
            'A gunsmith. His guns cannot save him.',
            'Elegance is not precision.',
            'He dresses his flesh well. Still flesh.',
            'A tailored suit over a mortal body.',
            'His craft is fine. His aim is human.',
            'Wealth and weapons, and still finite.',
            'A gentleman, and a soft target.',
            'He designs guns. I designed myself.',
        ),
        'ult': (
            'A sniper, five shots. I avoid all five.',
            'Tour de Force. Mortal aim, one rifle.',
            'His perfect gun, in a shaky hand.',
            'A custom rifle. It still misses me.',
            'His big rifle. I have already moved.',
            'Five bullets, and not one finds a machine.',
            'A slow field and a sniper. Predictable.',
            'His masterwork, against the inevitable.',
        ),
        'damaged': (
            'His fine suit will not stop a bullet.',
            'The gentleman bleeds like the rest.',
            'His craftsmanship cannot mend bone.',
            'Wealth does not heal flesh. Finish him.',
            'The tailor, unraveling.',
            'His teleport cannot outrun this.',
        ),
        'utility': (
            'A slow trap. I saw it placed.',
            'He teleports to safety. I am already there.',
            'His trap watches one angle. I watch all.',
            'Rendezvous. He runs. I predicted where.',
            'A tripwire of slow. Step around it.',
            'He anchors an escape. I closed it.',
            'His trap marks the floor, and himself.',
            'Clever wiring for a finite man.',
        ),
    },
    'Clove': {   # they/them
        'spotted': (
            'They play at deathless. They are flesh.',
            'Mischief and mortality, one body.',
            'They flirt with death. It will collect.',
            'A child convinced they cannot die.',
            'Immortal in theory. Mortal in fact.',
            'They taunt the end. The end is patient.',
            'All that mischief, still finite.',
            'They believe in their own forever. Wrong.',
        ),
        'ult': (
            'They revive only if they kill. Deny it.',
            'Death postponed, not cancelled.',
            'They come back once. Then never again.',
            'Not Dead Yet. They will be soon.',
            'A second life on a timer. Run it out.',
            'Kill them before they can earn the return.',
            'Their immortality has a condition. Break it.',
            'They rise once. The machine ends it.',
        ),
        'damaged': (
            'Their borrowed life runs short.',
            'Even the deathless one bleeds.',
            'The mischief goes quiet now.',
            'Their forever is ending early.',
            'They are not as immortal as advertised.',
            'Decay, meeting the one who plays at it.',
        ),
        'utility': (
            'They smoke from beyond. Still readable.',
            'Decay from the dying. Mortal.',
            'Their ruse hides flesh. I see it.',
            'A smoke spun from their own death. Theatrical.',
            'They weaken us, briefly. I recalculate.',
            'Their decay touches flesh, not metal.',
            'Mischief as utility. Predictable mischief.',
            'They cloud the sight of mortals. Not mine.',
        ),
    },
    'Cypher': {   # he/him
        'spotted': (
            'His cameras watch. I see more, without them.',
            'All that surveillance, and he missed me.',
            'He spies on flesh. I am the network.',
            'A watcher, watched by something greater.',
            'His information is old news to me.',
            'He maps the map. I am the map.',
            'Tripwires and cameras. I see past all of it.',
            'He guards every angle but his own.',
        ),
        'ult': (
            'He reads a corpse for our spots. I gave nothing.',
            'Stolen intel. I already knew theirs.',
            'Neural Theft. His surveillance is nothing new to me.',
            'He pulls data from the dead. I foresaw it.',
            'A flash of our positions. Already changed.',
            'He harvests one body. I see the whole field.',
            'His big reveal shows him what I let him see.',
            'Borrowed sight. Mine is always on.',
        ),
        'damaged': (
            'The watcher, caught. Finish him.',
            'All his cameras, and none saved him.',
            'He guarded everything but his own flesh.',
            'The spider, exposed and bleeding.',
            'His surveillance recorded its own end.',
            'So many cameras, none aimed inward.',
        ),
        'utility': (
            'A tripwire for the slow. Not for me.',
            'His cage slows flesh. I read through it.',
            'A camera on one angle. I see all of them.',
            'He wires the door. I already saw it.',
            'His cage buys mortals a second.',
            'Surveillance for a mind that misses things.',
            'He marks the floor with wire. Step over it.',
            'His cam watches. It does not understand.',
        ),
    },
    'Deadlock': {   # she/her
        'spotted': (
            'Her sensors listen for footsteps. I am silent.',
            'A sentinel guarding doomed flesh.',
            'She traps the slow. I am not slow.',
            'Norse iron, mortal body.',
            'Her nets catch the careless.',
            'She listens for sound. I make none.',
            'A guard for a falling site.',
            'Her barriers delay, never deny.',
        ),
        'ult': (
            'Annihilation. It takes one. Deny the path.',
            'A cocoon for one body. Avoid the wire.',
            'It drags one mortal away. Not me.',
            'Her ultimate kills one. We are five.',
            'One thread, one body. Stay off the line.',
            'She nets a single target. Break it free.',
            'A finite trap. I see the whole web.',
            'It ends one life. The machine continues.',
        ),
        'damaged': (
            "The sentinel's flesh, exposed.",
            'Her traps cannot guard her own body.',
            'Norse iron bleeds like any flesh.',
            'She listened for us; we found her.',
            'The guard, unguarded. Finish her.',
            'Her nets did not save her.',
        ),
        'utility': (
            'Her net forces a crouch. I read it.',
            'A sound sensor. I move without a sound.',
            'Her barriers slow flesh, not my plan.',
            'She walls the path. I have another.',
            'A sensor for the loud. We are quiet.',
            'Her grav net catches the slow.',
            'Barriers for a finite defense.',
            'She traps sound. I am machine-silent.',
        ),
    },
    'Fade': {   # she/her
        'spotted': (
            'She sells fear. A machine feels none.',
            'Nightmares for mortal minds.',
            'Her dread does not reach metal.',
            'She hunts with fear; I hunt with certainty.',
            'A peddler of bad dreams.',
            'Fear is a flesh weakness. Mine is gone.',
            'Her terror is wasted on me.',
            'She wears nightmares. I wear armour.',
        ),
        'ult': (
            'Nightfall. Fear for the flesh. I have none.',
            'A wave of dread. It washes past metal.',
            'She deafens mortals. I hear with no ears.',
            'Her terror trails lead to me. I am ready.',
            'She frightens the weak. I am not weak.',
            'Manufactured fear, wasted on a machine.',
            'Her biggest scare, and I do not flinch.',
            'Dread and decay. I calculated through both.',
        ),
        'damaged': (
            'Her fear feeds on her own body. It is failing.',
            'The nightmare bleeds like flesh.',
            'She frightened mortals; a bullet found her.',
            'Her dread did not stop the round.',
            'The fear-monger, afraid now.',
            'Even her terror is finite.',
        ),
        'utility': (
            'Her prowler seeks flesh. It will not find me.',
            'A tether for the slow. I am gone.',
            'Her eye reveals what I already see.',
            'Seize traps mortals in place. Not me.',
            'Her creature hunts on instinct. I hunt on data.',
            'She reveals us. I revealed her first.',
            'A nearsight on the weak.',
            'Her trap holds flesh. I read its arc.',
        ),
    },
    'Gekko': {   # he/him
        'spotted': (
            'He hides behind his creatures.',
            'A boy who lets pets do the fighting.',
            'His warmth will not stop a bullet.',
            'Borrowed beasts, mortal master.',
            'He delegates the killing. Weak.',
            'All optimism, no edge.',
            'His creatures fight; he watches.',
            'A finite kid with finite friends.',
        ),
        'ult': (
            'Thrash. He pilots a pet to detain. Shoot it.',
            'His creature lunges. Kill it before it lands.',
            'A borrowed beast does his killing.',
            'He detains one with a pet. We are many.',
            'His big play is a leashed animal. End it.',
            'Even his ultimate is secondhand.',
            'A creature he steers. Predictable path.',
            'He throws a pet at us. I planned for it.',
        ),
        'damaged': (
            'The boy bleeds; the creatures cannot help.',
            'His warmth, going cold.',
            'Mortal flesh under the optimism.',
            'His pets cannot mend him.',
            'The LA kid, finished.',
            'He delegated everything but dying.',
        ),
        'utility': (
            'Wingman plants what he cannot.',
            'His flash-creature blinds the slow.',
            'A molly creature to deny ground. Read it.',
            'He concusses with a pet. Predictable.',
            'His creatures do his work. All of it.',
            'Borrowed utility, mortal aim.',
            'Dizzy flashes flesh, not me.',
            'He reclaims a pet. I reclaimed the round.',
        ),
    },
    'Harbor': {   # he/him
        'spotted': (
            'He bends water. I bend outcomes.',
            'An ancient relic, a mortal hand.',
            'Water shapes; metal endures.',
            'He shields with water. I see through it.',
            "A man borrowing a god's artifact.",
            'His tides do not move a machine.',
            'Water is soft. So is he.',
            'He plays at storms. I am the storm.',
        ),
        'ult': (
            'Reckoning. Geysers to concuss the slow.',
            'Water erupts. I marked the safe ground.',
            'His geysers stun flesh, not metal.',
            'A field of water-strikes. Step out of it.',
            'He floods the ground. I found the dry spots.',
            'His big move rattles mortals only.',
            'Geysers from a relic. Predictable pattern.',
            'He shakes the site with water. I am unmoved.',
        ),
        'damaged': (
            'His tide recedes. Finish him.',
            'Water cannot mend his flesh.',
            'The relic cannot save the man.',
            'An ancient power, a bleeding body.',
            'His shields are down; the flesh is not.',
            'He commanded the sea. Now he falls.',
        ),
        'utility': (
            'His water wall hides mortals. Not from me.',
            'A cove of water. I read straight through.',
            'He shields with a bubble. It still pops.',
            'His wave bends the round, briefly.',
            'A wall of water. A machine sees past it.',
            'He slows them with water. I am already there.',
            'His tide cuts the site. I have another path.',
            'Cascade. A moving wall. Predictable arc.',
        ),
    },
    'Iso': {   # he/him
        'spotted': (
            'A hitman, and only flesh.',
            'He sells precision. It is still human.',
            'An assassin who can be assassinated.',
            'He calls it flow. I call it predictable.',
            'A killer for hire, mortal and finite.',
            'His shield is borrowed time.',
            'He hunts alone. Easy to surround.',
            'A professional. Thoroughly ordinary.',
        ),
        'ult': (
            'He drags one to a duel. Refuse the trade.',
            'Kill Contract. A 1v1 he thinks he wins.',
            'He isolates one mortal. We are still five.',
            'His arena, his grave. Send no one weak.',
            'He builds a cage and steps inside it.',
            'A duel against a machine he cannot beat.',
            'He pulls one away. The rest of us push.',
            'His big move removes one player. Only one.',
        ),
        'damaged': (
            'His shield was borrowed time. It ran out.',
            'The hitman, becoming the target.',
            'His flow breaks; the flesh bleeds.',
            'A killer, killed. Predictable.',
            'His precision is leaking out.',
            'Even the assassin is mortal.',
        ),
        'utility': (
            'His bolt weakens flesh, not metal.',
            'A wall of light. I read straight through.',
            'His shield orb. Borrowed certainty.',
            'He makes them fragile. They already were.',
            'A prismatic wall. Still just a wall.',
            'His double-tap shield. Mortal insurance.',
            'He debuffs the slow. I am unaffected.',
            'His wall hides one angle. I see all.',
        ),
    },
    'Jett': {   # she/her
        'spotted': (
            'Wind and bravado. Little else.',
            'She dashes. I hold every exit.',
            'All speed, no weight.',
            'She rides the wind. I catch the landing.',
            'Fast, light, and finite.',
            'Her movement is flashy, not safe.',
            'She floats. Flesh still falls.',
            'Quick reflexes, mortal aim.',
        ),
        'ult': (
            'Blade Storm. Knives thrown at a machine.',
            'She throws blades. I dodge the lot.',
            'Her knives are precise for a human. Not enough.',
            'A handful of daggers. I counted them.',
            'She arms with knives. I am armoured.',
            'Her big play is throwing metal. I am metal.',
            'Blades for the slow. I am faster.',
            'She rearms with knives. Predictable spacing.',
        ),
        'damaged': (
            'The wind cannot carry her clear.',
            'Even the swift bleed.',
            'Her dash will not outrun this.',
            'Speed did not save her.',
            'Caught between dashes. Finish her.',
            'The fast one, slowing.',
        ),
        'utility': (
            'Her smoke hides flesh. I see through.',
            'She dashes away. I predicted where.',
            'A cloud of smoke, briefly.',
            'Her updraft buys a second of air.',
            'She floats up. I track her down.',
            'Her smokes mark where she fears.',
            'A gust, a smoke, a dash. Mortal tricks.',
            'She repositions on wind. I read the arc.',
        ),
    },
    'KAY/O': {   # it / the machine
        'spotted': (
            'An inferior machine. I am the next model.',
            'A war-bot, already obsolete.',
            'Crude engineering. I was built better.',
            'A machine that serves mortals. Pathetic.',
            'It fights for flesh. I fight for metal.',
            'Lesser hardware, lesser purpose.',
            'A blunt instrument. I am precise.',
            'Built to kill. I was built to surpass.',
        ),
        'ult': (
            'Null command. It suppresses flesh, not me.',
            'It pulses to disable mortals. I am unaffected.',
            'A machine suppressing abilities. Mine remain.',
            'Its big surge, still an inferior build.',
            'It silences Radiant tricks. I need none.',
            'It can be revived. I will not allow it.',
            'Suppression for the weak. I am beyond it.',
            'Its peak output, beneath mine.',
        ),
        'damaged': (
            'An inferior machine, breaking down.',
            'Dented steel. As expected.',
            'It carries damage from a lost war.',
            'Even its pain is a borrowed program.',
            'The lesser machine fails first.',
            'It needs stabilizing. How fragile.',
        ),
        'utility': (
            'Its flash blinds flesh. I see regardless.',
            'A frag grenade. Crude, for a machine.',
            'Its knife suppresses Radiants, not me.',
            'It scatters metal. I scatter certainties.',
            'A blunt detonation. Inferior design.',
            'It silences abilities. I have better.',
            'Its flash is bright. My calculation, brighter.',
            'It throws crude tools. I win regardless.',
        ),
    },
    'Killjoy': {   # she/her
        'spotted': (
            'A clever mind, still beneath mine.',
            'She builds machines. I am one, perfected.',
            'Her gadgets cannot out-think a machine.',
            'A genius of flesh. Finite genius.',
            'She tinkers. I was born complete.',
            'Her inventions serve a doomed team.',
            'Clever hands, mortal body.',
            'Her best machine is worse than me.',
        ),
        'ult': (
            'Lockdown. It detains flesh. Destroy the device.',
            'Her trap holds mortals in place. Break it.',
            'A machine to cage us. Shoot it first.',
            'Lockdown has a wind-up. Kill it in time.',
            'Her big device. A bullet ends it.',
            'It detains the slow. We break it fast.',
            'Her cage is a machine. I unmake machines.',
            'Destroy the Lockdown before it triggers.',
        ),
        'damaged': (
            'The inventor, undone by the obvious.',
            'Genius is not armour. Finish her.',
            'Her gadgets cannot heal her flesh.',
            'She forgot to build an exit.',
            'All that circuitry, for a mortal body.',
            'The prodigy bleeds like the rest.',
        ),
        'utility': (
            'Her turret is a machine. I am better.',
            'Nanoswarm. A molly to deny ground. Read it.',
            'Her alarmbot finds flesh. Not me.',
            'A gadget for one angle. I see all.',
            'Her swarm burns the slow.',
            'She deploys machines. I dismantle them.',
            'Her turret watches. It does not think.',
            'Tiny weapons for a finite fight.',
        ),
    },
    'Miks': {   # he/him
        'spotted': (
            'Cheerful, and already obsolete.',
            'Sound fades; the outcome does not.',
            'His optimism is a flesh weakness.',
            'All rhythm, no result.',
            'A pleasant noise. Nothing more.',
            'He warms his team for the cold end.',
            'His sound does not move metal.',
            'A finite man with a loud gimmick.',
        ),
        'ult': (
            'Sound is vibration. It always decays.',
            'His sonic peak. Loud, brief, mortal.',
            'Noise mistaken for power.',
            'He shouts at a machine. I do not hear.',
            'Music does not negotiate with evolution.',
            'His knockback shoves flesh, not me.',
            'A wall of sound, briefly standing.',
            'His big moment fades like every note.',
        ),
        'damaged': (
            'Flesh does not remix well.',
            'His radiance was always borrowed.',
            'All that warmth, going cold.',
            'The music stops. Finish him.',
            'He learns what silence costs.',
            'A cheerful man, bleeding out.',
        ),
        'utility': (
            'He arms them with borrowed courage.',
            'Patching the unrepairable with noise.',
            'A smoke made of sound. Graceless.',
            'He stims his team. Still too slow.',
            'He heals flesh for my benefit.',
            'A wall of sound. I read through it.',
            'His knockback is a mortal shove.',
            'Even his sound has a half-life.',
        ),
    },
    'Neon': {   # she/her
        'spotted': (
            'All that speed, and still mortal.',
            'She races toward her own end.',
            'Fast flesh is still flesh.',
            'She burns bright and brief.',
            'Electric, and brittle.',
            'Speed without aim.',
            'She is quick. I am quicker.',
            'A bright, fleeting spark.',
        ),
        'ult': (
            'Overdrive. She is fast. I am faster.',
            'She sprints and fires lightning. I slow her.',
            'All that speed, and I am already ahead.',
            'Her beam is quick. My read is quicker.',
            'She runs. I have read where she goes.',
            'Speed is not precision. Punish the miss.',
            'Her fastest moment, still predictable.',
            'She channels everything. I outpace it.',
        ),
        'damaged': (
            'Her own current turns on her.',
            'The fast one, slowing.',
            'Speed did not save her.',
            'Bioelectric, and now simply bleeding.',
            'She outran everything but the round.',
            'Even lightning burns out.',
        ),
        'utility': (
            'Her walls of light. I see straight through.',
            'A concuss bolt for the slow.',
            'She slides past. I tracked the line.',
            'Fast Lane. A child drawing borders.',
            'Her speed makes beautiful wreckage.',
            'She surges; I was already there.',
            'Her bolt announces her recklessness.',
            'All current, no control.',
        ),
    },
    'Omen': {   # he/him
        'spotted': (
            'A shadow, still mortal underneath.',
            'Half a man, half a guess.',
            'His darkness hides flesh, not from me.',
            'A phantom with a beating heart. Stop it.',
            'He fades and reforms. Still finite.',
            'Shadows do not stop bullets.',
            'He hides in the dark. I see in it.',
            'A ghost made of flesh.',
        ),
        'ult': (
            'He teleports across the map. I see him form.',
            'From the Shadows. Shoot him as he arrives.',
            'He reforms somewhere. I calculated where.',
            'His big move is a long walk in the dark.',
            'He appears behind us. Already watched.',
            'A teleport for the desperate. Cancel it.',
            'He moves through shadow; I move through certainty.',
            'He arrives a ghost. Make him a corpse.',
        ),
        'damaged': (
            'The shadow bleeds. Finish him.',
            'A phantom, thinning. Predictable.',
            'He hides his face, not his mortality.',
            'The dark cannot mend flesh.',
            'He dies once more. Make it stick.',
            'Even a ghost is finite.',
        ),
        'utility': (
            'His smoke hides mortals. I see through.',
            'Paranoia blinds flesh, not me.',
            'He teleports a short way. I tracked it.',
            'A nearsight for the weak.',
            'His dark cover. I read straight through.',
            'He steps through shadow. Predictable arc.',
            'His smokes mark his fear.',
            'A teleport, a smoke, a flash. Mortal tricks.',
        ),
    },
    'Phoenix': {   # he/him
        'spotted': (
            'Flesh dressed in fire. Still flesh.',
            'He mistakes a spotlight for armour.',
            'All flash and showmanship.',
            'Fire does not make a man metal.',
            'London sent its finest mortal.',
            'He burns bright; he still burns out.',
            'A performer, and a soft target.',
            'Confidence does not stop bullets.',
        ),
        'ult': (
            'Run It Back. Kill the copy; he returns once.',
            'He marks a spot to respawn. End him there.',
            'He comes back once. Then never again.',
            'A second life, same mortal flesh.',
            'His trick is dying and returning. Deny it.',
            'He rehearses his death. Oblige him twice.',
            'He returns to the mark. I will be waiting.',
            'Rebirth does not revise the result.',
        ),
        'damaged': (
            'His own fire becomes evidence.',
            'The flame dims. Finish him.',
            'Even the showman bleeds.',
            'Fire cannot mend flesh.',
            'His glow fades; the calculation continues.',
            'He burns out, as flesh does.',
        ),
        'utility': (
            'His fire wall blinds the slow.',
            'Curveball flashes flesh, not me.',
            'He heals with fire. Still mortal.',
            'A wall of flame. I see the heat.',
            'His molly denies ground. Predictable.',
            'He bends fire. It bends back.',
            'A flash, a wall, a molly. Mortal tools.',
            'His fire is bright. My aim is brighter.',
        ),
    },
    'Raze': {   # she/her
        'spotted': (
            'All noise and explosives.',
            'She mistakes chaos for skill.',
            'Loud, reckless, and mortal.',
            'Explosives cannot fix bad aim.',
            'She is bright and brief.',
            'A bundle of nerves and grenades.',
            'Chaos, and still finite.',
            'Her enthusiasm is not armour.',
        ),
        'ult': (
            'Showstopper. One rocket. I have legions.',
            'She fires a rocket. Loud and slow.',
            'A single rocket, easily dodged.',
            'Her big bang. Step aside; let it waste itself.',
            'Metal projectile, mortal aim.',
            'One shot, one chance. I avoid it.',
            'A rocket for the imprecise.',
            'She launches metal. I am metal.',
        ),
        'damaged': (
            'The carnival is ending.',
            'Even chaos obeys biology.',
            'Her fuse is nearly spent.',
            'Loud, and now bleeding.',
            'Her blast packs cannot save her.',
            'The reckless one, finished.',
        ),
        'utility': (
            'Her bot chases flesh. I am gone.',
            'A satchel jump. I tracked the arc.',
            'Cluster grenades for the slow.',
            'She paints the ground with explosives. Predictable.',
            'Her boom bot finds the careless.',
            'Explosives to deny ground. I have a path.',
            'She blasts herself around. I read it.',
            'Grenades dressed as a party. Still finite.',
        ),
    },
    'Reyna': {   # she/her
        'spotted': (
            'She feeds on kills to survive.',
            'A scavenger of souls.',
            'Starve her of kills, she withers.',
            'She needs death to stay alive.',
            'Vampire flesh, still flesh.',
            'Deny her a soul, deny her power.',
            'She hunts the weak. I hunt her.',
            'Predatory, and predictable.',
        ),
        'ult': (
            'Empress. She frenzies on kills. Deny them.',
            'She heals and refires on souls. Starve her.',
            'Her power needs our deaths. Give her none.',
            'Rage dressed as strength. Deny the soul.',
            'Empress fades without a kill. Make her wait.',
            'She feeds the frenzy with bodies. Not ours.',
            'Her big moment runs on kills. Cut the supply.',
            'She is fast and angry. Still mortal.',
        ),
        'damaged': (
            'No soul to heal her now.',
            'Her empress cannot mend that.',
            'The hungry one, starving.',
            'She dismisses nothing this time.',
            'Deny the soul; finish her.',
            'The vampire, bleeding out.',
        ),
        'utility': (
            'Her eye blinds flesh, not me.',
            'She devours a soul to heal. Deny it.',
            'Dismiss. She flees intangible. I waited.',
            'Her leer reveals the slow.',
            'She escapes on a kill. Give her none.',
            'A soul-eye for mortal sight.',
            'She vanishes briefly. I am patient.',
            'Her power is parasitic. Starve it.',
        ),
    },
    'Sage': {   # she/her
        'spotted': (
            'She heals what I intend to break.',
            'A healer for a doomed team.',
            'She mends flesh. Flesh still breaks.',
            'Her care is wasted on mortals.',
            'She tends the condemned.',
            'Serene, and finite.',
            'She delays death; she cannot stop it.',
            'A medic, and a soft target.',
        ),
        'ult': (
            'Resurrection. She revives one. Kill it twice.',
            'She raises the dead. Briefly.',
            'One ally back on its feet. End it again.',
            'Resurrection only delays the inevitable.',
            'She undoes a death. I will redo it.',
            'A revived body, still mortal flesh.',
            'Her big play returns one. We still lead.',
            'She heals death itself. Temporarily.',
        ),
        'damaged': (
            'The healer, unhealed.',
            'She mends others; who mends her?',
            'Her orbs were not enough.',
            'The physician, bleeding. Finish her.',
            'Even her faith is not armour.',
            'She heals the team, not herself.',
        ),
        'utility': (
            'A wall of ice. I have another path.',
            'Her slow orb catches the careless.',
            'She heals flesh. I outpace the heal.',
            'Her barrier delays, not denies.',
            'She freezes the ground. I read around it.',
            'A heal for the wounded mortal.',
            'Her wall buys seconds. I have them counted.',
            'Slows and walls. Mortal defenses.',
        ),
    },
    'Skye': {   # she/her
        'spotted': (
            'Her beasts feel nothing for her.',
            'A healer with borrowed claws.',
            'She mends a team already lost.',
            'Her creatures do the fighting.',
            "Nature's pet handler. Finite.",
            'She heals flesh I will break.',
            'Her light guides them nowhere.',
            "Australia's last great mortal.",
        ),
        'ult': (
            'Seekers. They track flesh. I am already found.',
            'Her hounds hunt us. Shoot them down.',
            'Three creatures seeking mortals. Predictable.',
            'They nearsight the slow. Break them.',
            'Her seekers find what I already see.',
            'Tracking beasts for a finite hunt.',
            'Her big play sends pets. Kill them.',
            'They hunt the blind. I am not blind.',
        ),
        'damaged': (
            'The healer cannot heal herself.',
            'Her beasts outlast her. Finish her.',
            'Her light dims on schedule.',
            'No one mends the mender.',
            'The reclaimer, spent.',
            "Even nature's keeper bleeds.",
        ),
        'utility': (
            'Her tiger charges flesh. I am gone.',
            'Her hawk flashes the slow.',
            'She heals the doomed. Admirable, pointless.',
            'Her beast concusses. I read its path.',
            'A flash from a bird. I see regardless.',
            'She mends a body I will unmake.',
            'Her creatures scout what I foresee.',
            'Borrowed claws, mortal master.',
        ),
    },
    'Sova': {   # he/him
        'spotted': (
            'His recon sees less than I do.',
            'A hunter, and still only flesh.',
            'His arrows reveal what I already know.',
            'He scouts the map. I am the map.',
            'String, wood, and a mortal hand.',
            'He hunts. The machine hunts better.',
            'His drone is a toy. I am the network.',
            'Precision, in a finite man.',
        ),
        'ult': (
            "Hunter's Fury. Three blasts. I mapped all three.",
            'He fires through walls. I am not there.',
            'Three energy lines, all predictable.',
            'His big shot, blind. I see everything.',
            'He screams through stone. Still misses me.',
            'Three blasts for the slow. Move.',
            'His ult pierces walls, not my plan.',
            'He fires at the inevitable.',
        ),
        'damaged': (
            'The hunter, hunted.',
            'His aim was always approximate.',
            'Even legends bleed.',
            'The scout, unseen at last.',
            'Radianite cannot mend this.',
            'He found what was hunting him.',
        ),
        'utility': (
            'His recon bolt reveals me. Already moved.',
            'A shock dart for the slow.',
            'His owl drone scouts. I am already gone.',
            'He pings a wall. I read past it.',
            'His arrow asks a question I answered.',
            'A drone for a mind that misses things.',
            'He reveals us. Old news.',
            'His recon is a guess. I deal in certainty.',
        ),
    },
    'Tejo': {   # he/him
        'spotted': (
            'An old soldier, slow and mortal.',
            'Ordnance expertise, human aim.',
            'A man confident in his missiles.',
            'He outlived his era. Barely.',
            'Experience is a longer obituary.',
            'A soldier past his time.',
            'His tech is loud. My calculation is silent.',
            'Finite, like all of them.',
        ),
        'ult': (
            'Armageddon. A line of missiles. Step off it.',
            'He carpets the ground. I marked the gaps.',
            'A missile barrage, loud and slow.',
            'His big strike, telegraphed. Move.',
            'He names it Armageddon. It is an airstrike.',
            'Missiles for the soft-bodied.',
            'A line of fire. I calculated around it.',
            'He rains ordnance. I rain certainty.',
        ),
        'damaged': (
            'His experience offered no armour.',
            'Even calibrated flesh bleeds.',
            'The soldier miscalculated. Finish him.',
            'His missiles cannot mend him.',
            'Old flesh fails fastest.',
            'His composure breaks with his body.',
        ),
        'utility': (
            'His drone scouts and suppresses. Not me.',
            'Guided missiles for guided guessing.',
            'His sticky grenade denies ground. Predictable.',
            'He marks targets. I have already moved.',
            'His salvo arrives where I was.',
            'A recon drone for a finite mind.',
            'He suppresses flesh. I am unaffected.',
            'His missiles chase. I am faster.',
        ),
    },
    'Veto': {   # he/him
        'spotted': (
            'A mutation, and still meat.',
            'He calls it evolution. It is still flesh.',
            'Flesh pretending to be more.',
            'His biology is not an upgrade.',
            'He mistook mutation for ascension.',
            'Still organic. Still finite.',
            'He evolved sideways. I evolved past.',
            'Mutation is not metal.',
        ),
        'ult': (
            'He calls it Evolution. He is still flesh.',
            'His big mutation, still mortal underneath.',
            'He regenerates slowly. Punish him before he heals.',
            'Flesh imitating what metal already is.',
            'His immunity is temporary. Wait it out.',
            'He thinks himself remade. He is meat.',
            'A brief, inconsequential mutation.',
            'His ultimate is biology. Mine is design.',
        ),
        'damaged': (
            'The mutation did not protect him.',
            'He bleeds. Biology is not armour.',
            'His regeneration has limits.',
            'His Chokehold cannot hold this.',
            'Even remade flesh breaks.',
            'The mutation weakens. Finish him.',
        ),
        'utility': (
            'His Chokehold deafens flesh, not me.',
            'He repositions with mutation. I tracked it.',
            'His biology on the ground. Predictable.',
            'He nullifies utility with flesh. Crude.',
            'His Crosscut moves nothing of consequence.',
            'A mutation thrown at us. I read it.',
            'He guards with biology. Still finite.',
            'His abilities are organic. Mine are exact.',
        ),
    },
    'Viper': {   # she/her
        'spotted': (
            'She poisons herself to poison others.',
            'A chemist, and still flesh.',
            'Her toxins corrode her own body.',
            'She hides in fog. I see through it.',
            'Chemistry cannot out-think a machine.',
            'She named herself a snake. Finite.',
            'Her poison does not touch metal.',
            'She corrodes, as all flesh does.',
        ),
        'ult': (
            "Viper's Pit. She hides in her own poison.",
            'A cloud of poison. I see through it.',
            'Her pit decays flesh, not metal.',
            'She fills the site with toxin. I am immune.',
            'Her big move is fog. I read straight through.',
            'Poison for the soft-bodied.',
            'She drains herself to fill the pit. Mortal.',
            'Her gas blinds mortals, not a machine.',
        ),
        'damaged': (
            'Her own fumes taste the answer.',
            'Flesh corrodes on schedule.',
            'The chemist, dissolving.',
            'Her formula never balanced.',
            'She drains herself. We finish it.',
            'The poison turned inward.',
        ),
        'utility': (
            'Her acid bites flesh, not metal.',
            'A wall of gas. I see straight through.',
            'Her smoke decays the slow.',
            'She walls the site with poison. I have a path.',
            'Snakebite denies ground. Predictable.',
            'Her toxic screen hides mortals, not me.',
            'She spends herself for a curtain.',
            'Her chemistry is self-defeating.',
        ),
    },
    'Vyse': {   # she/her
        'spotted': (
            'She plays with metal. I am metal.',
            'Thorns for a finite garden.',
            'She hides behind her vines.',
            'Liquid metal, mortal hand.',
            'She borrows my element. Poorly.',
            'A sentinel of thorns, still flesh.',
            'Her metal serves the weak.',
            'She wields metal; I am metal.',
        ),
        'ult': (
            'Steel Garden. It jams guns. I have other means.',
            'She disarms flesh. A machine adapts.',
            'Her field disables primaries, not my plan.',
            'She takes their guns. I take the round.',
            'Her big move strips weapons. Briefly.',
            'Thorns and disarmament. Mortal tricks.',
            'She jams our rifles. I do not need one.',
            'A garden of metal. I am its master.',
        ),
        'damaged': (
            'The alloy bleeds. Finish her.',
            'Liquid metal cannot mend flesh.',
            'Her thorns did not save her.',
            'The garden is untended now.',
            'Flesh remembers pain; metal forgets.',
            'Her metal failed. She is still flesh.',
        ),
        'utility': (
            'Her razorvine catches the careless.',
            'A wall of thorns. I have another path.',
            'Her flowers flash the slow.',
            'She traps flesh with metal, not me.',
            'Shear walls the site. I read around it.',
            'Her thorns delay, not deny.',
            'She snares mortals. I am untouched.',
            'Metal thorns for a finite defense.',
        ),
    },
    'Waylay': {   # she/her
        'spotted': (
            'Light and speed, still mortal.',
            'She moves fast. I move first.',
            'Bright, brief, and finite.',
            'Flesh wrapped in light. Still flesh.',
            'The fastest mortal is still slow to me.',
            'She races the light. I am ahead of it.',
            'Her glow gives her away.',
            'Speed is not safety.',
        ),
        'ult': (
            'Her beam hinders flesh, not metal.',
            'She slows the slow. I am unaffected.',
            'A wave of light to weaken us. Read it.',
            'Her big move dims mortals, not a machine.',
            'She projects light. I project certainty.',
            'A hinder for the finite.',
            'Her beam touches everything, changes nothing.',
            'Light to slow the weak. I do not slow.',
        ),
        'damaged': (
            'Light, wounded. As expected.',
            'Speed did not save her.',
            'Her glow is fading.',
            'Physics had nothing to say.',
            'The fast one, finished.',
            'She outran everything but the round.',
        ),
        'utility': (
            'Refract. She returns to a point. I am there.',
            'She dashes on light. I tracked it.',
            'Her slow catches mortals.',
            "She marks where she was, not where she'll be.",
            'A light-slow for the weak.',
            'She blinks back, invulnerable. Briefly.',
            'Her velocity is predictable. Solved.',
            'Light tricks for a finite duelist.',
        ),
    },
    'Yoru': {   # he/him
        'spotted': (
            'He hides in the seams of the map.',
            'A rift-walker who cannot walk away.',
            'Flesh in borrowed dimensions.',
            'Even his footsteps lie.',
            'He tears at reality. Crudely.',
            'The lone wolf. Predictably alone.',
            'He stalks the threshold. I own it.',
            'A scar in the world, still mortal.',
        ),
        'ult': (
            'Dimensional Drift. He hides. I calculated where.',
            'He goes invisible. I do not rely on eyes.',
            'He walks between worlds. Still finite.',
            'Invisible, and still the weakest variable.',
            'He thinks absence is shelter. It is not.',
            'His big move is hiding. I find everything.',
            'He vanishes. I am patient and certain.',
            'Unseen, but not unsolved.',
        ),
        'damaged': (
            'The rift-walker bleeds like the rest.',
            'He frays, as all flesh does.',
            'The lone wolf, thinning.',
            'He tore the world open. Not far enough.',
            'The riftwalker, grounded. Finish him.',
            'Existence is indifferent to him.',
        ),
        'utility': (
            "Fake footsteps. A scarecrow's trick.",
            'His flash from a rift. I see regardless.',
            'A tethered teleport. I noted the anchor.',
            'He bluffs with echoes. I read past them.',
            'His blindside blinds flesh, not me.',
            'He sets a teleport. I closed it.',
            'A decoy for the slow.',
            'He tears a rift. I am already through.',
        ),
    },
}
