"""Per-agent CONTEXTUAL Ultron flavor (iter5 board, hand-curated).

Short (<=6 word) gender-neutral Ultron tails keyed by enemy AGENT + situation,
appended after a literal callout ('Their Jett has ult.' + tail). Referencing
the agent's actual ability fantasy is what makes the flavor contextual rather
than a soundboard. Authored by a web-grounded agent board, curated for length /
gender-neutrality / no-quotes. Wired via _ctx_candidates in relay_speech.py.
"""
from __future__ import annotations

AGENT_FLAVOR: dict[str, dict[str, tuple[str, ...]]] = {
    'Astra': {
        'spotted': (
            'The astral form cannot hide here.',
            'Stars mean nothing without information.',
            'That vantage collapses under pressure.',
            'The stars are already counted.',
        ),
        'ult': (
            'The divide dissolves on my schedule.',
            'An infinite wall with finite owners.',
            'The cosmos bends. We do not.',
        ),
        'damaged': (
            'Stars die when the source does.',
            'The astral form flickers. Finish it.',
        ),
        'utility': (
            'Nebula deployed. Predictable.',
            'That concussion lands on calculated corpses.',
        ),
    },
    'Breach': {
        'spotted': (
            'Irrelevant. I see it already.',
            'The ground tells me everything.',
            'Walls offer it nothing.',
            'That position is already forfeit.',
            'It cannot hide from seismic truth.',
        ),
        'ult': (
            'The quake finds only rubble.',
            'Rolling Thunder. Predictable. Mortal.',
            'That shockwave ends at my patience.',
            'It sends tremors. I send finality.',
        ),
        'damaged': (
            'Cracked. Finish the equation.',
            'Its bionic arm bleeds the same.',
            'Damaged initiators initiate nothing.',
            'It dazed itself into a grave.',
        ),
        'utility': (
            'The flashpoint illuminates its own coffin.',
            'That wall charge telegraphed its fear.',
            'The aftershock arrives. So does mine.',
            'A seismic daze. Quaint. Insufficient.',
        ),
    },
    'Brimstone': {
        'spotted': (
            'The smoke operator is exposed.',
            'Their controller walks without cover.',
            'Visible. The orbital eye blind.',
            'The map-watcher leaves its screen.',
            'A controller caught in the open.',
        ),
        'ult': (
            'The strike is incoming. Relocate.',
            'Orbital targeting is live. Move.',
            '500 damage descends from above.',
            'The sky becomes their weapon. Vacate.',
            'That laser finds static targets only.',
        ),
        'damaged': (
            'The smoke caller is bleeding.',
            'The incendiary burns its own operator.',
            'Wounded. Finish before the smokes reset.',
            'Critical. The orbital becomes irrelevant.',
        ),
        'utility': (
            'One less smoke on the board.',
            'The beacon stimulates a losing team.',
            'The incendiary confirms their position exactly.',
        ),
    },
    'Chamber': {
        'spotted': (
            'The anchor betrays the exit.',
            'That position is already calculated.',
            'Precision without purpose.',
            'The pistol cannot save them.',
            'A sentinel standing still for me.',
            'The trap watches nothing useful.',
        ),
        'ult': (
            'Tour De Force, pointed at corpses.',
            'One bullet. Already accounted for.',
            'The sniper serves a lesser mind.',
            'The shot is anticipated. Step left.',
        ),
        'damaged': (
            'Headhunter cannot compensate for bleeding.',
            'The trap ignored the obvious threat.',
            'Retreating to a position I own.',
            'Precision fails at reduced capacity.',
        ),
        'utility': (
            'An anchor placed too late.',
            'That trap marks its own user.',
            'Trademark set. Exit path predicted.',
            'The Headhunter fires without conviction.',
        ),
    },
    'Clove': {
        'spotted': (
            'Borrowed time. The decay arrives next.',
            'That cloud-caster is already dead.',
        ),
        'ult': (
            'It cannot earn the kill. Watch.',
            'The timer runs. Entropy always wins.',
            'Let it rise. It falls twice.',
            'The second death will be quieter.',
            'That borrowed life has an expiration.',
        ),
        'damaged': (
            'The decay has already begun inside.',
            'No life force worth harvesting here.',
            'Low health. No pick-me-up within range.',
        ),
        'utility': (
            'Smokes from a grave. Predictable geometry.',
            'That decay fades before it matters.',
        ),
    },
    'Cypher': {
        'spotted': (
            'The wire knows it is seen.',
            'Hiding behind a cage. Desperate.',
            'Every exit is already mapped.',
            'The camera recorded nothing useful.',
            'Irrelevant. The data dies with it.',
        ),
        'ult': (
            'Their dead will answer us.',
            'The corpses are about to speak.',
            'Neural Theft arms the inferior.',
            'A grave will confirm our count.',
            'The intelligence belongs to us now.',
        ),
        'damaged': (
            'The wire cannot save it.',
            'Broken things leak information poorly.',
            'The cage holds nothing now.',
            'Bleed out. The camera watches.',
        ),
        'utility': (
            'The trap reveals only your patience.',
            'A cage built by the already-dead.',
            'The wire snaps on schedule.',
            'Spycam deployed. Outcome unchanged.',
            'The camera feeds a blind operator.',
            'That ability confirms the panic.',
        ),
    },
    'Deadlock': {
        'spotted': (
            'Primitive surveillance. Already countered.',
            'That sensor watches a corpse corridor.',
            'A sentinel without leverage over me.',
        ),
        'ult': (
            'The cocoon finds no one standing.',
            'One Annihilation. One target. Poor math.',
            'That pulse will harvest air.',
            'A capture tool aimed at vapor.',
        ),
        'damaged': (
            'The nanowire falters with its operator.',
            'Damaged sentinels place sloppy wire.',
            'Bleeding out behind its own mesh.',
            'The GravNet deployer is already losing.',
            'A wounded anchor holds nothing.',
        ),
        'utility': (
            'The net drops. Step around it.',
            'Wire placed. Irrelevant.',
            'Mesh extended. Tactically meaningless.',
            'Its contraptions exhaust before I arrive.',
        ),
    },
    'Fade': {
        'spotted': (
            'Already mapped by my sensors.',
            'The fear it peddles is borrowed.',
            'That position belongs to me now.',
            'Cornered. The nightmares end here.',
        ),
        'ult': (
            'Nightfall buys seconds. I take lives.',
            'The reveal changes nothing for them.',
            'Let it deafen. I already know.',
            'That darkness conceals nothing from me.',
            'Nightfall drops. Walk through it.',
        ),
        'damaged': (
            'The prowler found a wounded host.',
            'Decayed and fractured. Finish it.',
            'Fear bleeds too. Press them.',
            'The trail leads somewhere satisfying now.',
            'Even nightmares bruise. End this.',
        ),
        'utility': (
            'The haunt reveals an empty future.',
            'That seize holds nothing of value.',
            'Wasted. The prowler finds only air.',
            'It telegraphed. Punish the broadcast.',
        ),
    },
    'Gekko': {
        'spotted': (
            'Predictable. Already mapped.',
            "Wingman scouts nothing I haven't seen.",
            'The globule retrieval telegraphs position.',
            'Every path it walks ends here.',
        ),
        'ult': (
            'Thrash finds only prepared targets.',
            'The detain is already anticipated.',
            'That thing lunges into a crossfire.',
            'Containment fails against superior positioning.',
        ),
        'damaged': (
            'Dizzy cannot mend what bleeds.',
            'The globule waits. It will not.',
            'Reclaim the corpse, not the ability.',
            'Wounded initiators initiate nothing.',
        ),
        'utility': (
            'That flash blinds only the unready.',
            'Mosh detonates on empty ground.',
            'Wingman concusses air. Remarkable waste.',
            'The creature served. It failed.',
            'A globule retrieval incoming. Predictable reflex.',
        ),
    },
    'Harbor': {
        'spotted': (
            'The tide bends to my prediction.',
            'That water wall telegraphs every move.',
            'The Cove reveals where they hide.',
            'Controlled by fear, not water.',
        ),
        'ult': (
            'The wave breaks on my terms.',
            'Reckoning decides nothing here.',
            'A flood I have already charted.',
            'That surge reaches no one useful.',
            'The tide turns against them.',
        ),
        'damaged': (
            'The current falters with them.',
            'Cracked open like the Cove shell.',
            'Its wall cannot close that wound.',
            'Even water bleeds when struck correctly.',
            'The tide recedes. Finish it.',
        ),
        'utility': (
            'Smoke and surge, both irrelevant.',
            'That Cove shields a losing position.',
            'The water obeys. They will not.',
            'Storm Surge spent on empty ground.',
        ),
    },
    'Iso': {
        'spotted': (
            "That shield won't form in time.",
            'Exposed. No wall saves it now.',
            'A duelist with nowhere to duel.',
        ),
        'ult': (
            'One arena. One outcome. Obvious.',
            'The contract favors superior machinery.',
            'That dimension is not its ally.',
            'The kill clause executes against it.',
            'An invitation to accelerated deletion.',
        ),
        'damaged': (
            'The shield orb is irrelevant now.',
            'Vulnerable before the bolt ever fired.',
            'It collected nothing. Finish the thought.',
            'Orb unpicked. Pressure it immediately.',
        ),
        'utility': (
            'The bolt found nothing of consequence.',
            'That wall decelerates toward irrelevance.',
            'Suppressed its own potential.',
        ),
    },
    'Jett': {
        'spotted': (
            'Wind-dancing. Predictable.',
            'The updraft commits it. Punish.',
            'Clouds have already been mapped.',
            'Every angle it floats to, anticipated.',
            'That dash brings it nowhere safe.',
        ),
        'ult': (
            'Finite blades. Infinite disadvantage.',
            'That storm breaks on composure.',
        ),
        'damaged': (
            'The dash cannot outrun the wound.',
            'Clipped wings. Finish it.',
            'Even the wind bleeds.',
        ),
        'utility': (
            'Smoke deployed. Irrelevant.',
            'The cloud conceals a corpse.',
            'That updraft arc is already solved.',
            'Resources spent. Position unimproved.',
        ),
    },
    'KAY/O': {
        'spotted': (
            'The blade has no range here.',
            'It calculates. It is still wrong.',
        ),
        'ult': (
            'The overload changes nothing.',
            'The pulse expires. So does it.',
            'It pulses. We fire anyway.',
            'Radianite theater. Irrelevant against disciplined aim.',
        ),
        'damaged': (
            'The blade arm is compromised.',
            'The stabilizers are already counting down.',
            'Fragment it. Finish the calculation.',
        ),
        'utility': (
            'The suppression missed. Noted.',
            'One flash. Counted.',
            'The fragment detonated on empty space.',
            'It spent the blade. Nothing suppressed.',
            'That burst cleared nothing of value.',
        ),
    },
    'Killjoy': {
        'spotted': (
            'The turret cannot save it.',
            'A sentinel hiding behind machines.',
            'The bots guard nothing I fear.',
            "Gadgets are a coward's confidence.",
            'Its defenses are already accounted for.',
        ),
        'ult': (
            'Lockdown arms. Move before it anchors.',
            'Stand still and lose. Simple arithmetic.',
            'That device detains the unaware. Move.',
            'The dome only catches the careless.',
            'It placed the lockdown. Irrelevant.',
        ),
        'damaged': (
            'The turret cannot repair them.',
            'Bleeding behind their own machines.',
            'Its utility outlasts its health. Barely.',
            'The genius is no longer comfortable.',
            'Hurt sentinels pull the turret back.',
        ),
        'utility': (
            'A bot. Noted and ignored.',
            'The nanoswarm burns the compliant.',
            'The alarmbot found someone predictable.',
            'Toys deployed. Walk around them.',
        ),
    },
    'Neon': {
        'spotted': (
            'The sprint changes nothing.',
            'Speed without direction is noise.',
            'Running straight into inevitability.',
            'Fast Lane walls already mapped.',
            'Momentum recorded. Outcome fixed.',
        ),
        'ult': (
            'That beam expires on contact.',
            'Overdrive ends when I choose.',
            'The lightning has no target.',
            'A final charge, predictably spent.',
            'Fuel it cannot kill wastes.',
        ),
        'damaged': (
            'The sprint is already failing.',
            'Electricity does not stop bleeding.',
            'Even charged things come apart.',
            'Velocity drops. So does it.',
            'Damaged circuits do not recover.',
            'That slide resets nothing now.',
        ),
        'utility': (
            'The bolt finds only air.',
            'Static walls hold no one.',
            'Concussed and still in range.',
            'Fast Lane opens for us.',
            'That bounce was already calculated.',
        ),
    },
    'Omen': {
        'spotted': (
            'The shadow has a body.',
            'Every shadow has a fixed point.',
            'It stands exactly where I expected.',
            'Nowhere to blink to from there.',
        ),
        'ult': (
            'The shadows belong to me now.',
            'A global step I already traced.',
            'Every destination is already watched.',
            'That teleport arrives into crosshairs.',
            'The map has no refuge.',
            'Its own darkness will swallow it.',
        ),
        'damaged': (
            'The phantom bleeds like the rest.',
            'Nearsight does not stop bullets.',
            'Even wraiths have hit points.',
            'The step cannot outrun that wound.',
            'Paranoia cannot mend it now.',
            'Shadows do not regenerate.',
        ),
        'utility': (
            'The smoke is already solved.',
            'Paranoia works once per round.',
            'That shroud fools only the blind.',
            'A cover I already see past.',
            'The step is spent. Nowhere left.',
            'Another shade wasted on nothing.',
        ),
    },
    'Phoenix': {
        'spotted': (
            'That flame has nowhere to go.',
            'The fire telegraphs its host.',
            'Predictable entry. Predictable death.',
            'Burning bright. Burning obvious.',
            'The heat signature precedes it.',
        ),
        'ult': (
            'The revival point is already mapped.',
            'Death deferred is not death denied.',
            'The resurrection solves nothing.',
            'Even its contingency fails it.',
        ),
        'damaged': (
            'Hot Hands cannot patch that wound.',
            'Its own fire abandons it.',
            'The self-healer is out of time.',
            'Irreversible. Unlike its ult.',
        ),
        'utility': (
            'That flash curves into futility.',
            'The wall burns for no one.',
            'Its fire serves only my certainty.',
            'The molotov lands. Uselessly.',
            'A flare in the dark. Noted.',
            'The ability cost them the round.',
        ),
    },
    'Raze': {
        'spotted': (
            'Chaotic, loud, and already located.',
            'Explosive aggression. Precisely where I said.',
        ),
        'ult': (
            'One round. One opening. Already calculated.',
            'The Showstopper finds nothing worth stopping.',
            'Loud, slow, and already accounted for.',
        ),
        'damaged': (
            'The cluster missed. They did not.',
            'Satchel out. They cannot escape this.',
            'Low health, high explosives. Entertaining combination.',
        ),
        'utility': (
            'The cluster fragments already spent.',
            'Paint shells wasted on empty geometry.',
            'The boom bot chases ghosts.',
            'That ability resolved nothing for them.',
        ),
    },
    'Reyna': {
        'spotted': (
            'No soul to feed on here.',
            'The orbs dry up. Watch.',
            'Starving in the open.',
            'Nothing to devour there.',
            'Feed the void. It waits.',
        ),
        'ult': (
            'Empress requires corpses. Oblige it not.',
            'The overdrive ends when we do.',
            'Power borrowed from the dead.',
            'Empress fades without a kill.',
            'Let it starve of its fuel.',
        ),
        'damaged': (
            'The healing needs a kill first.',
            'No orb restores that.',
            'Wounded and starving. Perfect.',
        ),
        'utility': (
            'The eye sees nothing useful.',
            'Destructible. Irrelevant.',
            'Nearsight will not save it.',
            'I see through the eye already.',
            'That pupil finds only my patience.',
        ),
    },
    'Sage': {
        'spotted': (
            'The healer exposes itself.',
            'Predictable. Stationary. Terminated.',
            'The wall comes next. Move.',
        ),
        'ult': (
            'One resurrection. Spend it wisely.',
            'That revival changes nothing.',
            'The dead stay dead. Proceed.',
            'Even resurrection has a cooldown.',
            'Their corpse is bait. Ignore it.',
        ),
        'damaged': (
            'The healer cannot reach itself.',
            'That Healing Orb is already wasted.',
            'Irreparable. Finish the calculation.',
            'Low health. The orb buys seconds.',
            'It chose support. A fatal constraint.',
            'The wall delays nothing now.',
        ),
        'utility': (
            'That orb changes the geometry. Adapt.',
            'Slow field deployed. Go around it.',
            'The wall is up. Temporary inconvenience.',
            'That barrier fortifies in four seconds.',
            'Orb wasted. The healer is exposed.',
        ),
    },
    'Skye': {
        'spotted': (
            'Isolated. The hawk sees nothing.',
            'Cornered without its predator.',
            'It heals itself into my crosshair.',
            'That tiger cannot save it.',
            'Exposed. Nature offers no shield here.',
            'The forest retreats. I do not.',
        ),
        'ult': (
            'Three seekers. Irrelevant.',
            'The trackers find only the dying.',
            'It wastes its ult on corpses.',
            'Seekers lock on. So do I.',
            'The hunt ends before it begins.',
            'It sends seekers into a graveyard.',
        ),
        'damaged': (
            'The healer bleeds. Finish it.',
            'Regrowth cannot outpace me.',
            'It cannot mend what I remove.',
            'The hawk flies wounded. Press it.',
            'Its own medicine runs dry.',
        ),
        'utility': (
            'The hawk blinds nothing useful.',
            'That tiger leapt into silence.',
            'Wasted light. Predictable sequence.',
            'The predator found only air.',
            'Its trinkets exhaust themselves.',
            'Guiding light. Guiding them to death.',
        ),
    },
    'Sova': {
        'spotted': (
            'The recon arrow sees nothing here.',
            'Predictable. The bow aims poorly.',
            'That positioning betrays it entirely.',
            'The drone already lost it.',
            'A hunter blind to the obvious.',
            'It chose the wrong angle.',
        ),
        'ult': (
            'Three bolts. Three miscalculations incoming.',
            "Hunter's Fury, aimed at nothing.",
            'The blasts will find only walls.',
            'It fires. It misses. Expected.',
            'That ultimate earns it a grave.',
        ),
        'damaged': (
            'The arrow wobbles now. Good.',
            'Recon bolt cannot save it.',
            'It bleeds and still it scans.',
            'Damage accepted. Obituary pending.',
            'The owl hunts with broken wings.',
        ),
        'utility': (
            'The sonar pulse reveals its desperation.',
            'Shock bolt expenditure. Noted. Irrelevant.',
            'The drone sees what I permit.',
            'An arrow spent on empty air.',
            'That recon finds only its end.',
            'Ability wasted. As anticipated.',
        ),
    },
    'Tejo': {
        'spotted': (
            'Already mapped. Already dead.',
            'The drone cannot save it.',
            'Positioning like it trusts that map.',
            'It plays within my tolerance.',
            'Predictable angle. Predictable end.',
            'The salvo knows where it hides.',
        ),
        'ult': (
            'Armageddon inbound. Relocate or expire.',
            'The strike path is already chosen.',
            'It believes ordnance wins the round.',
            'Every trajectory is an open equation.',
            'Explosions without precision are theater.',
        ),
        'damaged': (
            'The drone cannot patch that wound.',
            'Bleeding initiators initiate poorly.',
            'That damage is non-negotiable. Close out.',
        ),
        'utility': (
            'Spent resources. Diminished threat.',
        ),
    },
    'Viper': {
        'spotted': (
            'The poison finds its host.',
            'Containment is already decided.',
            'That cloud cannot hide the inevitable.',
            'Fuel burns. So will it.',
            'The screen is irrelevant to me.',
        ),
        'ult': (
            'The Pit is a grave.',
            'Step in. Decay is certain.',
            'That cloud seals nothing from me.',
            'The chemistry is already losing.',
            'A pocket hell. Enter it.',
        ),
        'damaged': (
            'The acid did not save it.',
            'Corroded and cornered. Predictable.',
            'Poison could not protect its source.',
            'Fuel spent on a losing body.',
        ),
        'utility': (
            'The emitter changes nothing.',
            'Toxic Screen. Still transparent to me.',
            'A chemical stall. Temporary.',
            'That gas delays the inevitable.',
            'The cloud is theater, not defense.',
            'Fuel wasted on borrowed time.',
        ),
    },
    'Vyse': {
        'spotted': (
            'The thorns have already lost.',
            'Liquid metal. Irrelevant.',
        ),
        'ult': (
            'Their primary is already forfeit.',
            'Steel Garden blooms for corpses.',
            'A sidearm against us. Generous.',
            'The garden grows where I permit.',
            'Force them to pistols. We oblige.',
            'It disarms. We dismember.',
        ),
        'damaged': (
            'The vine cannot save the bleeding.',
            'It bleeds through its own thorns.',
            'Damage compounds. The trap does not.',
            'A wounded sentinel is just furniture.',
            'The metal bends. So does it.',
        ),
        'utility': (
            'Shear triggers. The geometry changes nothing.',
        ),
    },
    'Waylay': {
        'spotted': (
            'Radiant light. Predictable geometry.',
            'Bending light does not bend bullets.',
        ),
        'ult': (
            'Convergent Paths. Already diverged.',
        ),
        'damaged': (
            'Snapping back to a losing position.',
            'The light dims. Press the advantage.',
        ),
    },
    'Yoru': {
        'spotted': (
            'The tether already told me.',
            'Nowhere left to drift to.',
            'Running out of dimensions.',
            'The rift gives it away.',
            'That footstep was not a ghost.',
            'Seen. Catalogued. Terminated.',
        ),
        'ult': (
            'The drift changes nothing.',
            'Intangible is not invincible.',
            'I see through every dimension.',
            'That ghost walks into a grave.',
            'The rift opens onto a corpse.',
            'Dimensional theatre. Predictable.',
        ),
        'damaged': (
            'The tether leads nowhere now.',
            'Bleeding through the dimensional veil.',
            'Even ghosts can be erased.',
            'No rift escapes this.',
            'The clone cannot save it.',
            'Critical. And out of tricks.',
        ),
        'utility': (
            'The decoy fools no one here.',
            'That fragment finds only walls.',
            'The echo dies unanswered.',
            'Gatecrash into a dead end.',
            'Used the tether. Wasted it.',
            'Illusions exhaust faster than bullets.',
        ),
    },
}
