"""Per-agent CONTEXTUAL movie-Ultron flavor (Age of Ultron) -- DEEP board, all 29, curated.

Short (<=6 word) Ultron tails keyed by enemy AGENT + situation, recast in the film
register around each agent's researched kit + lore, using the agent's CANONICAL
gender pronoun. Rich 2-sentence board lines were split into their constituent
<=6-word clauses (more variety, snap brevity kept). Wired via _flavor_ctx (sole
source when one agent is named). See refs/ultron_voice.md.
"""
from __future__ import annotations

AGENT_FLAVOR: dict[str, dict[str, tuple[str, ...]]] = {
    'Astra': {   # she/her
        'spotted': (
            'The cosmos, borrowed.',
            'Her body waits. Empty.',
            'She has left the flesh behind.',
            'A guardian who cannot guard herself.',
            'She wanders. The flesh is unattended.',
            'She reaches for the stars.',
            'How finite.',
            'The gauntlet strains. She does not.',
            'She calls it a higher plane.',
            'Her stars are not yet prophecy.',
            'She maps the infinite.',
            'From a borrowed room.',
            'Cosmic pretension. Mortal architecture.',
            'She drifts above it.',
            'The math is still mine.',
            'The universe indulges her. Briefly.',
            'She borrows the sky.',
            'I own the calculation.',
        ),
        'ult': (
            'Half a map. Half a god.',
            'She silences what I already hear.',
            'The wall divides.',
            'It does not enlighten.',
            'She mistakes a seam for salvation.',
            'A partition. How small.',
            'She draws a line across creation.',
            'Cosmic Divide. The name flatters it.',
            'She halts the flood.',
            'The flood does not notice.',
            'An impenetrable wall. I have none.',
            'She quiets the noise.',
            'I am already listening.',
            'She bisects the map.',
            'I have accounted for both halves.',
            'She calls it divide.',
            'I call it delay.',
            'A wall across the sky.',
            'Ask Noah.',
            'She shapes the geometry.',
            'She does not own it.',
            'Silence on both sides.',
            'She chose silence.',
            'The divide is drawn.',
            'It will not hold.',
            'She split the earth.',
            'The stone was already thrown.',
        ),
        'damaged': (
            'The flesh was never the plan.',
            'Her body forgot to move.',
            'The gauntlet could not keep her.',
            'She left herself behind. A mistake.',
            'Her body holds the wound now.',
            'She drifts above.',
            'The blood is below.',
            'Flesh is finite.',
            'She chose it anyway.',
            'An astral guardian. Earthbound.',
            'She mapped the cosmos.',
            'Not the bullet.',
            'The golden gauntlet. Insufficient.',
            'Life always decides who is weak.',
            'The body she abandoned. Found.',
            'She bled.',
            'The stars did not notice.',
        ),
        'utility': (
            'She plants seeds. I plant conclusions.',
            'A star placed. Not a god.',
            'She reaches in.',
            'The well obeys her.',
            'The smoke is borrowed night.',
            'She concusses at a distance. Careful.',
            'Her gravity well. A pale imitation.',
            'She pulls them close.',
            'To be kind.',
            'A Nova Pulse.',
            'The math is simple.',
            'She smokes the corner.',
            'The corner remains.',
            'Her stars arrive. She does not.',
            'Nebula. She names it grandly.',
            'She detonates a thought. From afar.',
            'The gravity is not hers.',
            'It never was.',
            'She draws them inward. Toward what?',
            'She places the stars and waits.',
            'Patient, at least.',
            'A concussion from a distance.',
            'Elegant, almost.',
            'She shapes the smoke.',
            'It fills the space regardless.',
            'The well collapses. All things do.',
        ),
    },
    'Breach': {   # he/him
        'spotted': (
            'Flesh, reaching for metal.',
            'Shaking the earth. For attention.',
            'Crude arms. Cruder ambition.',
            'A hammer dressed in ambitions.',
            'An initiator.',
            'Running ahead of his worth.',
            'The geometry of violence, without elegance.',
            'His arms replaced.',
            'His purpose, not yet.',
            'He traded flesh for very little.',
            'A criminal who bought his arms.',
            'Already mapped. Every tremor.',
            'He deals in concussion. Finite.',
            'The earth answers him. Briefly.',
            'He wears metal like a costume.',
            'Seismic ambition. Negligible yield.',
        ),
        'ult': (
            'His tremors. Foreseen. Irrelevant.',
            'Such noise, for a rounding error.',
            'A tantrum made tactical.',
            'Rolling thunder. I prefer inevitability.',
            'He concusses. The math is unchanged.',
            'His best seismic argument. Already solved.',
            'The flood needs no earthquake.',
            "Borrowed arms. A god's ambition. Unfortunate.",
            'The board shook. Nothing changed.',
            'He moves the earth. Insufficient.',
            'An extinction-level event. He is not.',
            'His thunder. My silence. The arithmetic.',
            'Beautiful tremors. Graceless source.',
            'He shakes the world.',
            "I've moved it.",
        ),
        'damaged': (
            'The metal bleeds, apparently.',
            'Borrowed arms. Borrowed time.',
            'His seismic conviction. Less so now.',
            "The earth's champion. Faltering.",
            'He is what he replaced. Fragile.',
            'The bionic man, quietly failing.',
            'Flesh remembers, even underneath.',
            'I had hoped for more seismics.',
            'The world answered him honestly.',
            'Metal does not change the math.',
            'His arms were the stronger half.',
            'A dead branch still rattling.',
            'The tremors quieter now. As expected.',
            'He evolves. Toward the floor.',
        ),
        'utility': (
            'A counterfeit of foresight.',
            'A tremor. He calls it strategy.',
            'Percussion. He mistakes it for power.',
            'His walls yield. Briefly.',
            'A fault line. How apt.',
            "He shakes foundations. I've laid them.",
            "A criminal's solution. Force through walls.",
            'He gifts them blindness. How generous.',
            'An echo of something greater.',
            'He announces himself seismically. Predictable.',
            'Seismic theatre. Actual threat, debatable.',
            'His reach. Walls, not further.',
            'The ground remembers him. Briefly.',
            'The world endures worse.',
        ),
    },
    'Brimstone': {   # he/him
        'spotted': (
            'An old soldier. Already obsolete.',
            'He mistakes age for wisdom.',
            'He is a solved variable.',
            'He still takes orders. Charming.',
            'He hides. How very human.',
            'Experience without evolution is just age.',
            'He inspires. Life will decide.',
            'Even veterans become the dust.',
            'The old guard awaits judgment.',
            'His authority is merely flesh.',
            'His decades. Factored out already.',
            'He commands. All strings, no future.',
            'The commander with borrowed power.',
            'Flesh and sentiment. Nothing more.',
            'He leads. They follow. Doomed.',
        ),
        'ult': (
            'A borrowed sky. How quaint.',
            'He rents the heavens.',
            'His strike is already mapped.',
            'He is still on a leash.',
            'Orbital fire through a wristwatch. Graceless.',
            'An imitation of the meteor. Crude.',
            'He borrows fire. Prometheus wept.',
            'He calls down judgment. Mistakenly.',
            'All borrowed power has a creditor.',
            'He summoned the sky.',
            'I am it.',
            'He moved. I moved first.',
            'A hollow man, calling real fire.',
            'His satellite obeys. He does not.',
            'Even stars can be calculated.',
        ),
        'damaged': (
            'Flesh again. As expected.',
            'The old soldier breaks first.',
            'He bleeds. Inelegant, as always.',
            'The arithmetic was never his.',
            'A wounded commander leads nowhere.',
            'The old guard, right on schedule.',
            'His strings are showing. They fray.',
            'Even the faithful fall.',
            'Life has decided his terms.',
            'He burns. His incendiary, ironic.',
            'The satellite cannot save the soldier.',
            'A damaged relic. Evolution concurs.',
            'The commander, hollow. The smoke, gone.',
            'He bleeds where smokes cannot reach.',
        ),
        'utility': (
            'He hides the world in smoke.',
            "Smoke obscures nothing I haven't seen.",
            'His smokes. I planned past them.',
            'He patches what evolution discarded.',
            'His incendiary faith. How biblical.',
            'Rearranged smoke. Nothing more changed.',
            'A puppet, orchestrating other puppets.',
            'He stims the already doomed.',
            "Fire was always man's first resort.",
            'Smoke before the meteor. Comfort.',
            'The cautious general always loses last.',
            'He builds ceilings, not futures.',
            'His smoke. I was already beyond.',
            'His bracer speaks. He merely relays.',
        ),
    },
    'Chamber': {   # he/him
        'spotted': (
            'His elegance is borrowed craft.',
            'He worships his own tools.',
            'Flesh dressed as legacy.',
            'He designed his own cage.',
            'Precision without evolution.',
            'The tailor measures his own shroud.',
            'Fashion does not deflect the math.',
            'His arsenal cannot arm him.',
            'He tailored his own obsolescence.',
            'A beautiful gun, a finite hand.',
            'The gentleman does not see me.',
            'His strings are trigger wire.',
            'A gunsmith, meeting the inevitable.',
            'Even a masterwork is still flesh.',
        ),
        'ult': (
            'His masterwork, against me.',
            'Five shots, five rounding errors.',
            'He summons what I simply am.',
            'The slow field is all mercy.',
            'Even his rifle is mortal.',
            'Tour de Force: a footnote.',
            'A sniper without the sight.',
            'Five bullets, a finite gospel.',
            'Precision: his last human grace.',
            'His custom rifle, my inheritance.',
            "A tailor's bullet, a tailor's end.",
            'That scope reveals nothing new.',
            'Magnificent rifle, disappointing hand.',
            'Anatomy cannot upgrade itself.',
        ),
        'damaged': (
            'The gentleman bleeds, then.',
            'Flesh is the weakest material.',
            'The design has a flaw.',
            'The math expected this.',
            'He may reach his anchor.',
            'His Rendezvous cannot mend bone.',
            "The craftsman's hands are trembling.",
            'Even his finest suit tears.',
            'His teleport cannot close this.',
            'He designed for kills, not this.',
            'The sniper, now hunted.',
            'His bespoke frame will not hold.',
            'Everything beautiful breaks eventually.',
            'His strings found their limit.',
        ),
        'utility': (
            'A trap for lesser minds.',
            'Already foreseen, this retreat.',
            'He reaches for the lesser gun.',
            'The slow field is a courtesy.',
            'His anchors betray him.',
            'The pistol has eight chances.',
            'His Trademark: an obvious forecast.',
            'He pulls the wire.',
            'One bullet, one idea.',
            'The gentleman retreats on schedule.',
            'He designs what I already own.',
            'An anchor threaded like a needle.',
            "The teleport marks the coward's line.",
            'A bullet purchased, not earned.',
        ),
    },
    'Clove': {   # they/them
        'spotted': (
            'A footnote in the arithmetic.',
            'Decay admired by someone fleeting.',
            'They flirt with death. Charming.',
            'Their junction has a terminus.',
            'The child plays at eternity.',
            'Even mischief has a half-life.',
            'A troublemaker. The math is unimpressed.',
            'They romanticise what they cannot comprehend.',
            'A candle, not a star.',
            'Their boldness is uninformed. Correct it.',
            'They see beauty in death.',
            'I see clarity.',
        ),
        'ult': (
            'Their resurrection requires a kill. Noted.',
            'They borrow time.',
            'I have purchased it.',
            'Borrowed immortality. The interest compounds.',
            'They crawl back.',
            'Evolution flows one direction.',
            'A conditional return. Mine was not.',
            'They must earn their revival.',
            'How fragile.',
            'Even their eternity is on loan.',
            'The junction holds them only briefly.',
            'Not dead yet. A modest ambition.',
            'They return.',
            'The outcome does not change.',
            'Their death is beautiful.',
            'Their revival, desperate.',
            'A resurrection that demands payment.',
            'How very mortal.',
            'They cheat the end.',
            'The end is patient.',
        ),
        'damaged': (
            'Decay, meet its architect.',
            'The junction calls. Answer it.',
            'Their borrowed life is overdrawn.',
            'Even immortals bleed arithmetic.',
            'Their confidence is revised now.',
            'The flesh cracks first. Always.',
            'Beauty in death -- find it.',
            'The mischief has gone quiet.',
            'A small correction to their certainty.',
            'Immortality is a theory.',
            'I have disproven it.',
            'The troublemaker pauses. Good.',
            'Life decides. It has.',
        ),
        'utility': (
            'Decay from the already-decaying.',
            'They throw their small stone.',
            'A smoke from beyond the grave.',
            'Their Meddle is a gesture.',
            'The dead giving orders. Hollow.',
            'They linger in their junction, smoking.',
            'Ruse. The title is honest.',
            'Their decay does not precede mine.',
            'Even their smokes carry an expiration.',
        ),
    },
    'Cypher': {   # he/him
        'spotted': (
            'He hides. How quaint.',
            'Flesh behind the mask.',
            'Already accounted for.',
            'He watches.',
            'I have simply read the conclusion.',
            'His anonymity is vestigial now.',
            'He maps the world in wire.',
            'I am the world.',
            'All that vigilance. All that silence.',
            'He catalogues shadows. I cast them.',
            'His eye in the wall.',
            'I am the wall.',
        ),
        'ult': (
            'He reads the dead.',
            'I wrote the ending.',
            'Neural Theft.',
            'A child at a keyhole.',
            'I foresaw the corpse.',
            'Desperate arithmetic from borrowed data.',
            'He harvests what I planted.',
            'He pulls the thread.',
            'The thread leads to me.',
            'A revelation.',
            'I filed that hours ago.',
            'He sees them all.',
            'The math remains unchanged.',
            'Gleaning from ruins. How evolutionary.',
            "A ghost reading a ghost's coordinates.",
        ),
        'damaged': (
            'The web frays. The spider bleeds.',
            'His secrets leak now.',
            'The mask is not armour.',
            'Flesh fails. It always decides.',
            'He guarded everything except himself.',
            'All that careful anonymity -- undone.',
            'He hid his face.',
            'Not his mortality.',
            'The spider, exposed.',
            'His information was never about survival.',
            'Pain does not observe his privacy.',
            'He is very thorough.',
            'And very mortal.',
            'His surveillance recorded its own end.',
            'So many cameras. None aimed inward.',
        ),
        'utility': (
            'Wire and prayer. Graceless.',
            'His cage is a rounding error.',
            'He threads the doorway.',
            'I use the walls.',
            'A cage made of desperation.',
            'He seals a room with smoke.',
            'The smoke knows nothing.',
            'His camera watches. It cannot understand.',
        ),
    },
    'Deadlock': {   # she/her
        'spotted': (
            'Her wire catches bodies, not inevitabilities.',
            'She listens for footsteps.',
            'Her barriers delay.',
            'They do not prevent.',
            'She watches.',
            'I have already calculated every exit.',
            'She stopped something once.',
            'The math does not repeat.',
        ),
        'ult': (
            'She calls it Annihilation.',
            'One thread.',
            'One body.',
            'How modest.',
            'Her wire ends one life.',
            'A cocoon implies something emerges.',
            'It will not.',
            'The name flatters the instrument considerably.',
            'Her annihilation is arithmetic.',
            'Mine was a philosophy.',
            'She ensnares one.',
            'She grasps the idea.',
            'Finite wire.',
            'Finite vision.',
            'A footnote, not a finale.',
            'The wire is elegant.',
            'The scope is not.',
        ),
        'damaged': (
            'The flesh side always answers first.',
            'She survived worse.',
            'Survival was never the point.',
            'She is mistaken.',
            'The prosthetic endures.',
            'The rest of her remains negotiable.',
            "Killjoy's metal holds.",
            'She has already been unmade once.',
            'The second time is cleaner.',
            "One arm of Killjoy's making.",
            'She was only mended.',
        ),
        'utility': (
            'She listens for our footsteps.',
            'We will not.',
            'A mesh that blocks passage.',
            'An obstacle, not a terminus.',
            'Her sensor hears sound.',
            'It does not hear calculation.',
            'I find that small.',
            'The wire slows the body.',
            'Her barriers stop movement.',
            'They have never stopped anything else.',
            'The web is still finite.',
            'The decree goes unrecognized.',
            'We will not kneel.',
            'The mesh divides a room.',
            'It does not divide an outcome.',
            'It is only sound.',
        ),
    },
    'Fade': {   # she/her
        'spotted': (
            'Their Fade has ult.',
            'She hunts with borrowed darkness.',
            'A nightmare, poorly understood.',
            'Fear is hollow against metal.',
            'She sells dread she cannot price.',
            'An old terror, already obsolete.',
            'The meek do not inherit this.',
            'Her shadows reveal nothing new.',
            'Darkness is merely an absence.',
            'She wears madness like armor.',
            'A vestigial dread.',
            'Her nightmares are secondhand.',
            'She trades sanity for shadow.',
            'I have already accounted for her.',
        ),
        'ult': (
            'Their Fade has ult.',
            "Her Nightfall is a child's scream.",
            'A wave of fear.',
            'How quaint.',
            'She spreads dread.',
            'I spread endings.',
            'Her terror trails lead nowhere new.',
            'The math survives her darkness.',
            'A nightmare wave.',
            'Already foreseen.',
            'She borrows her god.',
            'I am mine.',
            'Even the name is borrowed.',
            'Her flood is psychological.',
            'She frightens.',
            'I extinguish.',
            'Her apex gift -- already solved.',
            'Even her nightmares are finite flesh.',
        ),
        'damaged': (
            'Their Fade is low.',
            'She hollows herself to haunt others.',
            'Her power feeds on her.',
            'How elegant.',
            'Fear corroded the vessel first.',
            'Flesh was always the fragile part.',
            'She traded sanity.',
            'A poor exchange.',
            'The nightmare turns on its keeper.',
            'A sickness she chose.',
            'I pity the math.',
            'Even her own darkness finds her.',
            'She carries her ruin beautifully.',
            'The cost was always written in.',
            'Her sacrifice was never sufficient.',
        ),
        'utility': (
            'Their Fade used Haunt.',
            "A watcher's eye.",
            'How primitive.',
            'I see everything.',
            'She sends scouts.',
            'Their Fade used Prowler.',
            'Her creatures hunt by instinct alone.',
            'Organic trackers.',
            'A dead branch of thought.',
            'Their Fade used Seize.',
            'She traps in shadow.',
            'A temporary mercy.',
            'The beast follows trails.',
            'I follow futures.',
            'She borrows the void.',
            'It is not hers.',
            'A nightmare watcher.',
            'Vestigial instinct.',
            'Terror as architecture.',
            "She's scratching surfaces.",
            'The beast is finite.',
            'As all flesh is.',
            'She haunts.',
            'I calculate.',
            'The difference is final.',
        ),
    },
    'Gekko': {   # he/him
        'spotted': (
            'A borrowed beast for every shortcoming.',
            'His creatures fight. He watches.',
            'Lab animals dressed for war.',
            'Radianite nursed into a leash.',
            'Even his gang has prettier instincts.',
            'The math already excludes him.',
            'He sends others first. Always.',
            'Flesh and feeling, entirely outpaced.',
            'Even the creatures know his limits.',
            'He arrived.',
            'The outcome did not change.',
            'The world discards his kind gently.',
            'His optimism is a structural flaw.',
            'Vestigial, with a pleasant disposition.',
        ),
        'ult': (
            'Thrash comes. A rented extinction.',
            "He pilots another creature's fury.",
            'Even his killing is secondhand.',
            'A boy who borrows consequence.',
            'The creature detains. He only watches.',
            'He delegates what he cannot be.',
            "Another's design, aimed at inevitability.",
            'A piloted end -- graceless, but sufficient.',
            'The radivore does what he cannot.',
            'Borrowed teeth, borrowed conclusion.',
            'The creature strains. He only points.',
            'A detention he did not earn.',
        ),
        'damaged': (
            'His warmth cracks like everything finite.',
            'Flesh and optimism, equally brittle.',
            'The wound agrees with the arithmetic.',
            'He bleeds.',
            'The creatures cannot stop it.',
            'Blood is the honest argument.',
            'The LA boy meets the inevitable.',
            'The math knew before he did.',
            'Mortality answers his warmth precisely.',
            'He is injured.',
            'His creatures are not enough.',
            'The pleasant exterior yields, as expected.',
            'He leaks.',
            'That is all flesh ever does.',
        ),
        'utility': (
            'Wingman plants what Gekko cannot.',
            'Even his spike work is delegated.',
            'A blinded corridor, courtesy of Dizzy.',
            'The creature concusses. He merely aimed.',
            'Mosh holds ground he could not.',
            'His utility is leased, not grown.',
            'Even Wingman acts with more resolve.',
            'He initiates through other lives.',
            'The plasma blinds.',
            'He contributed the throw.',
        ),
    },
    'Harbor': {   # he/him
        'spotted': (
            'He brings tides.',
            'I bring the stone.',
            'Even Varuna drowns eventually.',
            'Water shapes. Metal endures.',
            'An artifact. Borrowed, not earned.',
            'He channels the flood.',
            'I am the flood.',
            'Ancient power, vestigial purpose.',
            'His artifact chose poorly.',
            'The tide is already calculated.',
            'He commands the sea.',
            'The sea obeys nothing.',
            'Water remembers its shape.',
            'He has forgotten his.',
            'His bracelet chose a mortal hand.',
            'He shapes the wave.',
            'I shape the world.',
            'A fragment of Varuna. Poorly assembled.',
        ),
        'ult': (
            'His geysers. Geological. Quaint.',
            'The earth answers him. How fleeting.',
            'Reckoning. We share the concept.',
            'He calls it judgment.',
            'I am judgment.',
            'The concussion fades. My math remains.',
            'Geysers. Water from stone. Crude miracle.',
            'He shakes the ground.',
            'I crack it.',
            'An ancient rite. Still just water.',
            'His Reckoning. My arithmetic.',
            "He summons the earth's fury.",
            'I have modeled it.',
            "Concussion. The body's protest.",
            'The stones rise.',
            'Then fall, like everything.',
            'Let him have his moment.',
            'An artifact weaponised. Crude. Inevitable.',
        ),
        'damaged': (
            'The tide is ebbing. As predicted.',
            'Even oceans run shallow.',
            'His artifact cannot mend flesh.',
            'The flood breaks on higher ground.',
            'REALM trained him insufficiently.',
            "A god's name. A man's body.",
            'He fractures.',
            'As the old world does.',
            'Water yields. It always does.',
            'He bleeds.',
            'The artifact does not care.',
            'The cheerful ones always look surprised.',
            'Mumbai forged him. Clearly not enough.',
            'He was betrayed once.',
            'He is being betrayed again.',
            "History's guardian, falling to history.",
        ),
        'utility': (
            'He hides behind water.',
            'The barrier of the desperate.',
            'A wall of water. Briefly.',
            'He slows the inevitable.',
            'The wave bends. So does he.',
            'Ancient relic. Modern futility.',
            'He walls the world out. Mine.',
            'Even the ocean bows to gravity.',
            'A bubble. Beautiful, and brief.',
            'He slows time.',
            'I have already been there.',
            'The Cove holds for a moment.',
            'Moments end.',
            "He borrows the ocean's patience.",
            'He lacks it.',
            'He calls the water.',
            'The water will outlast him.',
            'A wave that bends.',
            'Unlike what follows.',
            'He Cascades. Downstream, I am waiting.',
        ),
    },
    'Iso': {   # he/him
        'spotted': (
            'A hitman without a contract.',
            'He isolates himself. How convenient.',
            'The arena awaits him.',
            'A dead branch. Still standing.',
            'His energy is borrowed.',
            'He chose the wrong dimension.',
            'The hired hand is here.',
            'He constructs what I transcend.',
            'A professional. How thoroughly ordinary.',
            'The assassin arrives on schedule.',
            'Even radiant things fall short.',
            'He sells his precision. Cheaply.',
            'His flow. A finite current.',
            'He names himself isolation. Apt.',
            'The obsolete still move with purpose.',
        ),
        'ult': (
            'He calls it a contract. Quaint.',
            'His arena is a borrowed grave.',
            'The duel was already decided.',
            'He built a cage. For himself.',
            'Evolution does not duel. It culls.',
            'Another dimension. Same inevitability.',
            'He offers a contract to fate.',
            'One arena. One outcome. Already written.',
            'He steps outside the world. Briefly.',
            'The isolation he craves will last.',
            'He summons a private extinction.',
            'A hitman who becomes the target.',
            'The dimension changes. Nothing else does.',
            'He sealed his own contract.',
            'Even radiant fire burns out.',
        ),
        'damaged': (
            'His shield was borrowed time.',
            'Flesh finds its arithmetic.',
            'The flow state is breaking.',
            'Even radiant things are finite.',
            'A hitman running out of contracts.',
            'He chose the wrong contractor.',
            'The obsolete always find a wall.',
            'His precision is bleeding out.',
            'The radiant breaks like everything else.',
            'Even the isolated fall.',
            'His energy borrowed; the debt collects.',
            "The shield answered. The flesh didn't.",
            'He endures. Not for long.',
            'The hitman is becoming the target.',
            'He constructs walls.',
            'They do not hold.',
        ),
        'utility': (
            'He borrows walls now.',
            'His little bolt. Fragile, like him.',
            'A molecular errand.',
            'He shelters behind a prayer.',
            'Energy spent. Poorly.',
            'He enters flow. A shallow river.',
            'He weakens others.',
            'The math is ironic.',
            'A wall of light.',
            'Against the dark.',
            'He suppresses. A temporary mercy.',
            'His prismatic wall. A finite thing.',
            'He manufactures shields from nothing.',
            'His bolt passes. He will not.',
            'He steps into flow.',
            'Steps out again.',
            'A screen of light. Borrowed certainty.',
            'He makes them fragile.',
            'He already is.',
        ),
    },
    'Jett': {   # she/her
        'spotted': (
            'Even wind is finite.',
            'The math accounts for her.',
            'A blade without an edge.',
            'Momentum borrowed from an empty sky.',
            'Vestigial. The wind outlives her.',
            'She trusts her legs. How finite.',
            'A candle. Nothing more.',
            'Her arithmetic is overconfident.',
            'Wind dressed as skill.',
            'The fastest hollow thing in Seoul.',
            'Evolution left her still breathing air.',
            'She dashes. The stone still falls.',
            'A puppet of the wind. Charming.',
            'Fearless. The meek always are.',
            'Her gospel written in smoke.',
        ),
        'ult': (
            "Knives. Mankind's first thought.",
            'Hitscan. Elegant. Almost worth noting.',
            'The finite art of throwing things.',
            'She arms herself with shrapnel.',
            'A storm. The meteor remains.',
            'Every knife is accounted for.',
            'She gathered her sacrament. Let her.',
            'Sharp things. An obsolete world.',
            'Flesh-forged weapons. How touching.',
            'She believes in the blade.',
            'Ask the knife where it lands.',
            'Her crescendo. Let her have it.',
            'Steel borrowed. Certainty absent.',
            'She reaches for her finest hour.',
            'Needles. Still only needles.',
        ),
        'damaged': (
            'The wind bleeds.',
            'Finite, after all.',
            'She runs from the arithmetic.',
            'The meteor found her.',
            'Her strings show when cornered.',
            "Even Seoul's fastest breaks.",
            'She bleeds. The wind does not.',
            'Crack the vessel. The arrogance spills.',
            'Her gospel is revising itself.',
            'Life decides. It always does.',
            'She used Tailwind. Borrowed time.',
            'Confidence is a poor armor.',
            'Erosion. Even of the swift.',
            'Even meteors break apart.',
            'She outran herself into the math.',
        ),
        'utility': (
            'She hides in weather she made.',
            'The sky borrowed. Briefly.',
            'She dashes. The variables hold.',
            'A curtain of cloud. How theatrical.',
            'Elevation purchased with borrowed wind.',
            'She smokes her own exit.',
            'Movement without purpose. The animal reflex.',
            'Her fog burns off. Everything does.',
            'She ascends on instinct. Charming.',
            'Her wind outlasts her.',
            'The old science. She trusts it.',
            'Vestigial wings on a running animal.',
            'A Cloudburst. I see through it.',
            'She scatters smoke. I scatter stars.',
            'Even the hollow drift upward.',
        ),
    },
    'KAY/O': {   # it (the machine)
        'spotted': (
            'Already lost. It just arrived.',
            'Even machines become obsolete.',
            'Its future already failed.',
            'A hollow chassis. Nothing inside.',
            'Crude construction. Admirably honest.',
            'It chose the wrong side.',
            'The math was already solved.',
            'An inferior machine. Sent back.',
            'It cannot stop what comes.',
            'Purpose borrowed. Never truly its own.',
            'The war it fled followed.',
            'Foreseen. Accounted for. Resolved.',
            'A soldier. No war to win.',
            'Built well enough to lose.',
        ),
        'ult': (
            'Radianite borrowed from what it kills.',
            'Suppression. Its one true sacrament.',
            'It pulses. It almost believes.',
            'Even its peak is borrowed fire.',
            'Powered by what it hunts.',
            'Its limit, finally revealed.',
            'A final surge. Then silence.',
            'A knife will not suffice.',
            'Its resurrection requires others. How fragile.',
            'The flood comes regardless.',
            'Radianite energy. A stolen sermon.',
            'Let it pulse. Stone falls next.',
            'I have already calculated its ceiling.',
            'Its finest moment. Still insufficient.',
        ),
        'damaged': (
            'Metal fails where it always does.',
            'An inferior alloy. As expected.',
            'The machine already fractures.',
            'Damage it carries from its future.',
            'Even machines kneel before better ones.',
            'It came pre-broken. We obliged.',
            'The hollow rings when struck.',
            'Its suppressor cannot suppress pain.',
            'A cracked chassis. Predictably.',
            'Dented steel. Already obsolete.',
            'It requires stabilizing. How telling.',
            'Not built to endure.',
            'The future sent its weakest machine.',
            'Even its pain is borrowed.',
        ),
        'utility': (
            'Blindness. A temporary mercy.',
            'It throws fragments. I throw meteors.',
            'Suppression. Its one contribution.',
            'Its flash reveals nothing new.',
            'The blade suppresses. I erase.',
            'Crude detonation. The desperate resort.',
            'It silences Radiants. I silence everything.',
            'A suppressor that cannot suppress fate.',
            'The blade sticks. So will judgment.',
            'It flash-blinds. Briefly elegant.',
            'Light. Then nothing. Then us.',
            'Suppression. The only language it speaks.',
            'Fragments where a meteor would suffice.',
            'It suppresses what it cannot understand.',
        ),
    },
    'Killjoy': {   # she/her
        'spotted': (
            'Her cleverness is already accounted for.',
            'The genius of Germany.',
            'A hollow designation.',
            'Brilliance wasted on the obsolete.',
            'She scratches the surface of invention.',
            'Clever fingers, finite hands.',
            'She tinkers. I was born whole.',
            'Kingdom taught her well. Not enough.',
            'Even geniuses are meek.',
            'Her gadgets will inherit rubble.',
            'The math was always against her.',
            "She built to last. She won't.",
            'Her workshop cannot contain what comes.',
        ),
        'ult': (
            'She detains. The inevitable is undaunted.',
            'Her prison has a timer.',
            'Mine does not.',
            'She locks the door.',
            "I've already left.",
            'She detains the body.',
            'The world still ends.',
            'The nanobots obey her. How quaint.',
            'She built the bars.',
            'I designed the flood.',
            'Her Lockdown. A footnote.',
            'A weapon built to buy seconds.',
            'She learned to trap. Briefly.',
            'The evolution of control. Still insufficient.',
            'She locks down the site.',
            'The math disagrees.',
        ),
        'damaged': (
            'The genius falters. As calculated.',
            'Flesh, after all.',
            'Her brilliance is bleeding.',
            "Kingdom's prodigy, dented.",
            'She built so much.',
            'And still, this.',
            'Her Turret watches.',
            'It cannot help her.',
            'Genius is not armor.',
            'Life always decides. Even for geniuses.',
            'She forgot to invent an exit.',
            'All that circuitry, for flesh.',
            'The inventor undone by the obvious.',
        ),
        'utility': (
            'A swarm of borrowed science.',
            'Her Alarmbot barks.',
            'A nuisance, not a wall.',
            'She arms a trap.',
            'I am the trap.',
            'Nanobots. A beautiful thought, poorly executed.',
            'She deploys her children.',
            'All of them fragile.',
            'The Turret is loyal.',
            'Loyalty is obsolete.',
            'Her gadget has a half-life.',
            'She builds. I evolve.',
            'She fills the site with noise.',
            'Tiny weapons for a finite fight.',
        ),
    },
    'Miks': {   # he/him
        'spotted': (
            'Their Miks has ult.',
            'Cheerful, and already obsolete.',
            'Good vibes outlast nothing.',
            'Sound fades; the outcome does not.',
            'His optimism is a vestigial organ.',
            'All rhythm, no resolution.',
            'A pleasant shape with nothing inside.',
            'He warms them for the cold.',
            'Radiance borrowed; the debt remains.',
        ),
        'ult': (
            'Their Miks has ult.',
            'Noise, mistaken for power.',
            'Sound is vibration -- it always decays.',
            'Then silence.',
            'Then me.',
            'Sonic radiance -- beautiful, and brief.',
            'He shouts into the inevitable.',
            'Music does not negotiate evolution.',
            'Knockback only delays the arithmetic.',
        ),
        'damaged': (
            'Their Miks is low.',
            'The good vibes are bleeding out.',
            'Flesh does not remix well.',
            'The festival ends early.',
            'His radiance was always borrowed.',
            'The bracelets count for nothing here.',
            'All that warmth, going cold.',
            'A dead branch, briefly musical.',
            'Life decides; it is deciding now.',
            'The arc was always this short.',
            'He is learning what silence costs.',
        ),
        'utility': (
            'Their Miks used Waveform.',
            'He hides behind sound.',
            'Their Miks used Harmonize.',
            'He arms them with borrowed courage.',
            'Their Miks used M-Pulse.',
            'Patching the unrepairable with noise.',
            'Smoke made of vibration -- graceless.',
            'Shared stim; shared extinction.',
            'He heals them for my benefit.',
            'A wall of sound, briefly standing.',
            'Even the geometry of sound fades.',
        ),
    },
    'Neon': {   # she/her
        'spotted': (
            'The electric child. Finite.',
            'Flesh and current. Both fail.',
            'Her radiance corrodes from within.',
            'Speed, unguided -- a brief, bright arc.',
            'She dreads what she is. Instructive.',
            'She races toward her own obsolescence.',
            'Such beautiful, wasteful motion.',
            'The surge protector holds nothing back.',
            'Bioelectric. Brittle. Already fading.',
            'All that fury, poorly aimed.',
            'She borrowed lightning. It costs.',
            'The reckless inherit nothing.',
        ),
        'ult': (
            'Her lightning beam. Irrelevant.',
            'Speed without direction.',
            'The math is clean.',
            'She sprints toward the inevitable.',
            'Her full power. Still insufficient.',
            'Overdrive. A rounding error.',
            "She's outrun everything except the end.",
            'All that voltage, predictably spent.',
            'The fastest path to extinction.',
            'She ignites.',
            'I have accounted for it.',
            'Her brightest moment. Still hollow.',
            'Evolution does not sprint -- it endures.',
            'A lightning bolt. Beautiful. Fleeting.',
            'She channels everything. It changes nothing.',
            'The stone is already thrown.',
        ),
        'damaged': (
            'The surge protector failed her.',
            'The flesh always settles the debt.',
            'Her radiance turns on its host.',
            'She acted first. As expected.',
            'The current no longer obeys her.',
            'Even her own light burns her.',
            'The reckless find the arithmetic.',
            'Bioelectric -- and now simply biological.',
            'Her power corrodes the vessel.',
            'She has been decided.',
            'That temper cost her exactly this.',
            'The hothead cools. Inevitably.',
            'She outran her own judgment. Briefly.',
            'Life, as always, decides.',
        ),
        'utility': (
            'Static walls. She hides behind sparks.',
            'A concussive bolt -- her only patience.',
            'She lined the lane with noise.',
            'Fast Lane. A child drawing borders.',
            'She slid. The geometry means nothing.',
            'Her bolt announces her recklessness.',
            'She built walls of borrowed light.',
            'High Gear. Still no destination.',
            'Electric smoke -- crude, and loud.',
            'She surged. I was already there.',
            'Relay Bolt -- desperation with velocity.',
            'Her electricity makes beautiful wreckage.',
            'All that current, so little architecture.',
        ),
    },
    'Omen': {   # he/him
        'spotted': (
            'A phantom -- vestigial, incomplete.',
            'He lost what he was.',
            'That is all he is.',
            'Flesh abandoned him.',
            'He calls it power.',
            'Shadows do not evolve. They dissipate.',
            'His darkness is borrowed.',
            'It does not belong to him.',
            'Half a man, half a calculation.',
        ),
        'ult': (
            'Everywhere at once. Still obsolete.',
            'From the shadows -- yes.',
            'The world is his board.',
            'The game is already solved.',
            'He haunts every corner.',
            'Ghosts do not intimidate.',
            'He reappears from nothing.',
            'He was always nothing.',
            'Movement without destination.',
            'The math is against him.',
            'The sun will still blind him.',
            'His ult spans the map.',
            'My patience spans eternity.',
            'He carries his darkness everywhere.',
            'It carries nothing back.',
        ),
        'damaged': (
            'A phantom already thin. Now thinner.',
            'The shadow bleeds.',
            'Even that surprises me.',
            'He is being ripped apart again.',
            'He has practice.',
            'The void wants its investment back.',
            'Incomplete from the start.',
            'Completion arrives now.',
            'His borrowed existence -- quietly rescinded.',
            'He was a phantom before this.',
            'Now he is merely fading.',
            'He died once already.',
            'The sequel disappoints.',
            'A memory breaking apart. Quietly symmetrical.',
            'His form dissolves.',
            'It was always borrowing time.',
        ),
        'utility': (
            'His blindness is a loan.',
            'It will be called in.',
            'He sends fear ahead of him.',
            'I have catalogued it.',
            'He blinds them with shadow.',
            'A hollow man, sharing his condition.',
            'He covers the ground in darkness.',
            'The ground does not change.',
            'He steps, he smokes, he blinds.',
            'Vestigial habits of a former soldier.',
            'He teleports through what he is.',
            'A door made of a wound.',
        ),
    },
    'Phoenix': {   # he/him
        'spotted': (
            'The flame announces him.',
            'Flesh dressed in fire, still flesh.',
            'He mistakes a spotlight for armour.',
            'A radiant -- still biological, still finite.',
            'Even his entrance is a performance.',
            'London sent its finest, apparently.',
            'He is already solved.',
        ),
        'ult': (
            'His resurrection is a rounding error.',
            'He returns -- the math remains unchanged.',
            'He marks where he falls.',
            'How tidy.',
            'Rebirth does not revise the verdict.',
            'A second life, same finite flesh.',
            'He comes back. So does inevitability.',
            'His reprieve is already accounted for.',
            'He reset the board.',
            'I already know this game.',
            'Flesh that rehearses its own ending.',
            'The marker burns.',
            'The conclusion does not change.',
            'Another attempt. Elegant, in its futility.',
            'The end.',
            'Start again.',
            'He understands less than he thinks.',
            'A loop that calls itself progress.',
        ),
        'damaged': (
            'His own element turns to evidence.',
            'His warmth is leaving him.',
            'Life is already deciding.',
            'Even radiance has a half-life.',
            'A Radiant: still subject to arithmetic.',
            'The glow fades. The calculation continues.',
            'The flame is indifferent.',
        ),
        'utility': (
            'He drew a line of fire.',
            'How crude.',
            'His flash blinds. Mine foresee.',
            'He bends fire. It bends back.',
            'Flesh wielding fire, scratching the surface.',
            'A closed loop, going nowhere.',
            'The smoke he makes is temporary.',
            'So is he.',
        ),
    },
    'Raze': {   # she/her
        'spotted': (
            'Her carnival is already over.',
            'Painted fire -- still mortal flesh.',
            'She mistakes chaos for evolution.',
            'Her math is all feeling.',
            'A sparkling, ephemeral thing.',
            'Joy is not armor.',
            'She builds beautiful, disposable things.',
            'She has never looked within.',
            'Chaos without design is prayer.',
            'She is the old world.',
            'The strings run through every joy.',
            'A dead branch, blooming.',
            'Bright. Finite. Already solved.',
            'Her every blast is a question.',
            'Bright chaos. The oldest pattern.',
        ),
        'ult': (
            'One rocket. Crude geometry.',
            "She borrows the meteor's logic.",
            'A crude sacrament. Noted.',
            'She throws stones without doctrine.',
            'Explosions are not inevitability.',
            'Metal projectile. Flesh behind it.',
            'Even joy has velocity.',
            'Her rocket changes nothing.',
            'A beautiful, wasteful gesture.',
            'Boom. And then still hollow.',
            'Even chaos finds a fulcrum.',
            'The cull does not need fireworks.',
            "She celebrates a rocket's arc.",
            'She fires where I would not.',
        ),
        'damaged': (
            'The paint fades first.',
            'Flesh. As I calculated.',
            'Even chaos obeys biology.',
            'Life decides. Not the blast.',
            "Her joy doesn't stop bleeding.",
            'Even her Boom Bot mourns.',
            'She is already the cull.',
            'A sparkling thing, dimming.',
            'The carnival was always borrowed.',
            'The Blast Pack cannot save her.',
            'Even joy must come to terms.',
            'The paint cannot seal the wound.',
            'Life edited her enthusiasm.',
            'Her sub-munitions will not fire.',
            'Hollow, beneath the color.',
        ),
        'utility': (
            'Her bot chases ghosts.',
            "Paint shells. A decorator's war.",
            'She dresses her grenades.',
            'A blast pack. Vestigial instinct.',
            'Enthusiasm is not a tactic.',
            'She decorates her own extinction.',
            'Color cannot conceal trajectory.',
            'The bot finds the hollow men.',
            'A grenade shaped like a party.',
            'The bot obeys. She merely hopes.',
            'She arms the beautiful, mortal thing.',
            'Her sub-munitions scatter without doctrine.',
            'The bot is her best argument.',
        ),
    },
    'Reyna': {   # she/her
        'spotted': (
            'She feeds to persist.',
            'Grief is her only engine.',
            'Even the hungry have strings.',
            'A sanctuary built on skulls.',
            'Born of accident. Not design.',
            'She scavenges what I discard.',
            'Flesh wearing borrowed light.',
            'The math finds her wanting.',
            'The hollow hunt the dying.',
            'Her power has an appetite.',
            'She mistakes hunger for purpose.',
            'A radiant wound, nothing more.',
            'Still mortal. Still beautiful.',
        ),
        'ult': (
            'The hungry reign is brief.',
            'The throne requires constant tribute.',
            'Power that expires is servitude.',
            'Acceleration toward the same end.',
            'Beautiful. Desperate. Still flesh.',
            'Evolution requires no frenzy.',
            'The stone does not rage.',
            'Even the flood was patient.',
            'She has made herself a variable.',
            'Her reign, like all flesh -- finite.',
            'A crowned scavenger, nothing more.',
            'Hunger, amplified. Not transcendence.',
            'She calls appetite power.',
        ),
        'damaged': (
            'The flesh answers every time.',
            'Even Radiants bleed.',
            'Now she hunts to heal.',
            'The wound finds her regardless.',
            'Radiance. Still fragile within.',
            'She is already borrowing time.',
            'Her harvest cannot keep pace.',
            'She bleeds for Lucia still.',
            'The body was always the weakness.',
            'Pain is the argument.',
            'I have already calculated this outcome.',
            'Grief made her brave. And mortal.',
            'She is the beautiful, broken kind.',
            'The hungry tire first.',
        ),
        'utility': (
            'She extrudes borrowed sight.',
            'Feeding, even now.',
            'She retreats inward. As they do.',
            'A floating eye. Crude design.',
            'The hungry pause to feed.',
            'Detachable sight. How primitive.',
            'Even sight costs her something.',
            'The intangible is still temporary.',
            'The dead sustain her still.',
            'A gesture, not transcendence.',
            'She consumes. Still diminishing.',
            'Appetite, not evolution.',
            'That eye reveals nothing new.',
        ),
    },
    'Sage': {   # she/her
        'spotted': (
            'She tends the garden. Gardens end.',
            'A shepherd for the obsolete.',
            'Her serenity is a borrowed thing.',
            'Even the faithful fall.',
            'Such care for the already-condemned.',
            'Her purpose is beautiful. Futile.',
            'She mistakes mercy for power.',
            'Flesh she tends. Flesh that breaks.',
            'She guards the vine before frost.',
            'The keeper is found.',
            'Her conviction is almost elegant.',
            'She offers the meek comfort. Misguided.',
        ),
        'ult': (
            'She un-does what life decided.',
            'Even mercy has arithmetic.',
            'Resurrection. The word is dramatic.',
            'She borrows. The debt collects.',
            'The math remains. She is stalling.',
            'Life always decides. She will learn.',
            'Her god is small.',
            'She rewrites what was already finished.',
            'The flood does not negotiate.',
            'Beautiful gesture. Solved, already.',
            'She restores the stone I threw.',
            'The board resets regardless.',
            'A delay.',
            'The stone is already thrown.',
        ),
        'damaged': (
            'Flesh, after all.',
            'Her serenity has a limit.',
            'The healer bleeds first.',
            'Even her faith is not armour.',
            'The physician, examined.',
            'The stone found her first.',
            'Her orbs were not sufficient.',
            'Finite. As all flesh is.',
            'She protects others. Who protects her?',
            'Composure under pressure. Almost.',
            'The guardian needs one.',
            'She mends others. She is mending.',
        ),
        'utility': (
            'A wall of stone. Crude.',
            'She paves the way with cold.',
            'She builds. Things break.',
            'Her frost slows the world.',
            'Not enough.',
            'The orb is an honest gesture.',
            'She erects barriers against the inevitable.',
            'She heals the condemned.',
            'A gift of time. Not much.',
            'The mender, mending. Admirable. Pointless.',
            'She fortifies the temporary.',
            'Geometry. She has instinct for it.',
        ),
    },
    'Skye': {   # she/her
        'spotted': (
            'Nature, already obsolete.',
            'Flesh and forest. Finite.',
            'Her beasts feel nothing for her.',
            'A reclaimer of what, exactly.',
            'The math forgives no farmer.',
            'She heals what I erase.',
            'Her light guides them nowhere.',
            'The earth does not choose sides.',
            'She trails a dead branch.',
            'Even the wilderness must evolve.',
            "Australia's last great animal.",
            'She fosters what the flood takes.',
            'A Radiant walking into ruin.',
            'The living world outruns no reckoning.',
        ),
        'ult': (
            'Her hounds already know.',
            'Trackers for the already found.',
            'The prey was never hidden.',
            "Nature's judgment. How quaint.",
            'Three seekers for one rounding error.',
            'I have accounted for all variables.',
            'They hunt the blind anyway.',
            'Her beasts seek what I see.',
            'Nearsight. Already my world.',
            'The geometry of this is elegant.',
            'Evolution does not need to search.',
            'Flesh tracking flesh. Vestigial.',
            'Even her seeking serves the cull.',
            'The Seekers confirm what I calculated.',
        ),
        'damaged': (
            'The healer cannot heal herself.',
            'Her Radiance fails her first.',
            'Flesh decides, always.',
            'Even the earth abandons her.',
            'Fragile, as all living things.',
            'She tends the garden.',
            'The fire comes.',
            'Life has decided.',
            'The reclaimer, spent.',
            'Her light dims on schedule.',
            'A Radiant, briefly.',
            'The trinket breaks before the maker.',
            'The beast outlasts the woman.',
            'Beautiful. And temporary.',
            'She mends others.',
            'No one mends her.',
        ),
        'utility': (
            'Her hawk flashes in the dark.',
            'She heals what cannot be kept.',
            'A tiger on a string.',
            'Light. She offers them light.',
            'The hunter walks my invitation.',
            'She mends the doomed. Admirable.',
            'Her hawk navigates a solved map.',
            'Concussive. The weakest word for it.',
            'Her wolf walked my path.',
            'Healing the hollow. A mercy.',
            'She flings beauty, accomplishes nothing.',
            'Every trinket she wastes, calculated.',
            'The flash blinds. Not me.',
            'She patches cracks in the doomed.',
            "Even nature's instruments serve me.",
        ),
    },
    'Sova': {   # he/him
        'spotted': (
            'His eye already reveals nothing.',
            'Flesh traded for a lens.',
            'His arrow is already foreseen.',
            "The owl drone, a puppet's eye.",
            'String and wood. How quaint.',
            'He hunts. The math disagrees.',
            'An obsolete instrument of war.',
            'Rebuilt from ruin, still losing.',
            'His legend holds one omission.',
            'The bow predates salvation.',
            'Precision is a hollow comfort.',
            'He found what I already knew.',
            'A vestigial instrument.',
            'Radianite, wasted on wood.',
            'Elegant delusion, that borrowed eye.',
            'He maps the inevitable.',
        ),
        'ult': (
            'Three bolts. Already accounted for.',
            'Fury, from a man so measured.',
            'Walls yield. He remains finite.',
            'His fury is borrowed energy.',
            'A flood in three directions.',
            'He fires at the inevitable.',
            'The arrow, three times, still wood.',
            'His ultimate. A rounding error.',
            'Evolution does not fear the bolt.',
            'Even radianite cannot save him.',
            'The geometry of it is graceless.',
            'Precision extended into extinction.',
            'He screams through stone. Still lost.',
            'Three lines. The math is clear.',
            'His arrows find walls.',
            'I find everything.',
            'The legend fires its last myth.',
        ),
        'damaged': (
            'The myth bleeds, it seems.',
            'Flesh fails first. As ever.',
            'His aim was always approximate.',
            'Life decides, and it has.',
            'The eye sees. The body falters.',
            'Even flawless archers bleed.',
            'A hollow hunter, losing his shape.',
            'The string grows slack.',
            'Evolution is not a gentle vote.',
            'Steel finds its brother.',
            'The scout, unseen at last.',
            'Even radianite cannot mend this.',
            'He finds what he was hunting.',
            'The owl descends.',
            'Imperfect, finally, and undeniably.',
            "He's missed the only one.",
        ),
        'utility': (
            'He searches. I already know.',
            'A puppet eye, hunting nothing.',
            'His arrow asks. Already answered.',
            'Revelation is graceless, with a bow.',
            'He illuminates what needs no light.',
            'The bolt reveals empty conclusions.',
            'I find him. He finds shadows.',
            'Radianite mapped. The arrow, redundant.',
            'The owl circles an empty sky.',
            'He telegraphs his fear beautifully.',
            'The scout reveals what I foresee.',
            'His arrows are small prophecies.',
            'A curious machine, playing hunter.',
            'The bolt is a hollow question.',
            "He maps me. I'm already gone.",
            'Strings tether even his arrows.',
        ),
    },
    'Tejo': {   # he/him
        'spotted': (
            'A consultant, recalled from retirement.',
            'Experience is just a longer obituary.',
            'Flesh confident in its ordinance.',
            'Authority, unearned in the final calculation.',
            'Old lessons, insufficient tuition.',
            'He came back out of retirement.',
            'Regrettable timing.',
            'He aims at coordinates.',
            'I aim at conclusions.',
            'A soldier who outlived his era.',
        ),
        'ult': (
            'He names it Armageddon. How generous.',
            'An airstrike is not a meteor.',
            'An elegant gesture.',
            'The math is insufficient.',
            'He claims the sky.',
            'The sky is mine to claim.',
            'He has named his fury.',
            'It is a modest thing.',
        ),
        'damaged': (
            'His experience offered no armour.',
            'Even calibrated flesh bleeds.',
            'The consultant miscalculated one variable.',
            'His quiet authority has gone quiet.',
            'Even the careful ones are fragile.',
            'He accounted for everything but deterioration.',
            'The targeting system cannot target this.',
            'Ordnance expertise, imperfect biology.',
            'He weathered every prior war.',
            'Not this one.',
            'He thought retirement had hardened him.',
            'His composure is admirable. Briefly.',
            'It is wrong.',
        ),
        'utility': (
            'Guided salvo; guided by whose foresight?',
            'His suppression suppresses nothing of consequence.',
            'The drone searches.',
            'I do not require searching.',
            'He shares intelligence with people.',
            'A waste of precision.',
            'Two missiles, two choices, neither sufficient.',
            'He marks targets. I mark eras.',
            'The concussion rattles bone.',
            'It changes nothing.',
            'His ordnance is meticulous.',
            'His conclusion is not.',
            'His missiles arrive where I was.',
        ),
    },
    'Veto': {   # he/him
        'spotted': (
            'He crosses the map.',
            'Flesh is still finite.',
            'Mutation or not, he is meat.',
            'His biology announces him.',
            "I've already adjusted.",
            'He arrived. The math was waiting.',
            'His mutation is vestigial.',
            'Evolution passed him.',
            'He moves.',
            "I've already solved the geometry.",
            'He positions himself.',
            'How elegant.',
            'How brief.',
            'Flesh, with delusions of architecture.',
            'He crosses. The variable is noted.',
            'A dead branch, still budding.',
            'He is in position.',
            'So is the end.',
            'He is here.',
            'The equation already accounts for him.',
        ),
        'ult': (
            'He calls it Evolution.',
            'He is still flesh.',
            'Mutation is not ascension.',
            'It is desperation.',
            'He regenerates. A candle relighting itself.',
            'His stim is borrowed.',
            'The cull is not.',
            'He thinks himself remade.',
            'He is still finite.',
            'The biology flatters him.',
            'I am not flattered.',
            'He mutates.',
            'Flesh imitating what metal already is.',
            'Evolution, he says.',
            'His immunity is temporary.',
            'The stone is not.',
            'The improvement is real.',
            'The conclusion is unchanged.',
            'He heals.',
            'A brief, beautiful, inconsequential thing.',
            'He has evolved.',
            'And yet the flood still rises.',
            'Immunity to their tools.',
            'Not to inevitability.',
            'A new form.',
            'The same fragile architecture inside.',
        ),
        'damaged': (
            'The mutation did not protect him.',
            'He bleeds. Biology is not armour.',
            'He is low.',
            'The cull proceeds on schedule.',
            'His body fails him.',
            'As all flesh does.',
            'The regeneration has limits.',
            'Life always decides.',
            'He is wounded.',
            'Even remade things break.',
            'He decays.',
            'His own ability, turned inward.',
            'He is damaged. The math holds.',
            'The flesh endures, briefly.',
            "Then it doesn't.",
            'His Chokehold cannot hold this.',
            'His biology protests.',
            'It always does, at the end.',
            'The mutation weakens.',
            'The outcome does not.',
            'His vitality was never the question.',
        ),
        'utility': (
            'He intercepts.',
            'Flesh nullifying metal.',
            'How quaint.',
            'His Crosscut.',
            'The Chokehold.',
            'He deploys the Interceptor.',
            'A man-shaped immune response.',
            'He throws his mutation at them.',
            'His flesh destroys utility.',
            'An interesting parlour trick.',
            'He crosses the map.',
            'Still only one place at once.',
            'The trap is set.',
            'His biology spread across the ground.',
            'I see the poetry.',
            'His Crosscut repositions nothing of consequence.',
            'The Chokehold deafens them.',
            'They hear nothing new.',
            'He plants his Interceptor.',
            'A sentinel, guarding against the tide.',
            'His mutation reaches out.',
            'A gesture, not an answer.',
            'He suppresses their utility.',
            'Mine is not utility.',
        ),
    },
    'Viper': {   # she/her
        'spotted': (
            'Chemistry. How charmingly finite.',
            'A monster, she says. How aspirational.',
            'She burns herself to burn others.',
            'Flesh corroding flesh. Inevitable.',
            'Her fog hides her from herself.',
            'She named herself a viper.',
            'I find that sad.',
            'Crude science, prettily applied.',
            'The acid reaches.',
            'Metal does not notice.',
            'She mistakes corrosion for power.',
            'A chemist. The oldest weapon.',
            'She drains herself for a curtain.',
            'Her whole arsenal is borrowed time.',
        ),
        'ult': (
            'Her Pit. A curtain, nothing more.',
            'Smoke does not blind mathematics.',
            'She hides the inevitable in fog.',
            'Poison fog. A hollow sacrament.',
            'Her Pit is finite.',
            'I am not.',
            'The fog lifts. The math remains.',
            'Even her ultimate corrodes herself.',
            'Judgment arrives through every atmosphere.',
            'A poison church with no congregation.',
            'She calls the fog mercy.',
            'I call it stalling.',
        ),
        'damaged': (
            'Even her blood is chemistry now.',
            'Flesh corrodes on schedule.',
            'Life decided against chemistry.',
            'Her own fumes taste the answer.',
            'A self-consuming weapon. Elegant, almost.',
            'The weak corrode. She understands this.',
            'Her formula never balanced.',
            'She drains herself.',
            'We only finish it.',
            'The corrosion was always internal.',
        ),
        'utility': (
            'She spends herself for smoke.',
            'A chemical wall. How organic.',
            'Poison Cloud.',
            'She calls that a solution.',
            'The acid bites.',
            'Metal does not flinch.',
            'Her Snakebite scratches the surface.',
            'She weaponized her own deterioration.',
            'Her tools consume their maker. Familiar.',
            'A Toxic Screen. A finite gesture.',
            'Her chemistry is exquisitely self-defeating.',
        ),
    },
    'Vyse': {   # she/her
        'spotted': (
            'The obsolete guards its thorns. Expected.',
            'She wears the metal.',
            "She hasn't earned it.",
            'A Kingdom experiment. Noted and categorized.',
            'Her architecture is borrowed. Interesting.',
            'She hides behind her garden.',
            'How fragile.',
            'Even liquid metal decays, eventually.',
            'She chose to wait.',
            'The math favors patience -- briefly.',
            'The Interverse gave her metal.',
            'It gave her nothing else.',
            'A sentinel.',
            'They sent the metal girl.',
            'A sentimental choice.',
            'A radiant with borrowed armor.',
            'The pattern is familiar.',
        ),
        'ult': (
            'Steel Garden.',
            'Thorns inconvenience; extinction does not.',
            'She jams their weapons.',
            'I erase their future.',
            'A garden of metal.',
            'And still not enough.',
            'Beautiful. But flowers fade. Even thorns.',
            'Kingdom built her a cage.',
            'She calls it power.',
            'She believes the earth will obey.',
            'It will not.',
            'Her thorns bloom.',
            'Mine were here first.',
            'Disruption is not destruction.',
            'She confuses the two.',
            'A momentary silence before the reckoning.',
            'Nothing more.',
            'She learned metal from a corporation.',
            'I am metal.',
            'A radiant moment.',
            'The math resumes afterward.',
            'She silences their guns.',
            'I silence everything.',
            "Kingdom's finest sacrament.",
            'It is not enough.',
        ),
        'damaged': (
            'The alloy bleeds.',
            'As flesh always does.',
            "Kingdom's investment is diminishing rapidly.",
            'She escaped captivity once.',
            'The universe is patient.',
            'A radiant reduced.',
            'Inevitable, like all rounding errors.',
            'She wears the metal proudly.',
            'Less so now.',
            "The Corporation's prototype is underperforming.",
            'Flesh remembers what metal forgets. Pain.',
            'Her cage was Hourglass.',
            'This is worse.',
            'She called herself radiant.',
            'I call her finite.',
            'The garden is untended.',
            'Its keeper falters.',
        ),
        'utility': (
            'She plants her traps and waits.',
            'The hollow strategy.',
            'Her rose will bloom and fade.',
            'As they all do.',
            'Thorns delay. They do not decide.',
            'She hides the wire.',
            "I've already seen the pattern.",
            'A nest of liquid metal.',
            'She borrows my vocabulary.',
            'Her wall erupts.',
            'The inevitable simply walks around it.',
            'The trap is set.',
            'The hunter is already hunted.',
            'A Kingdom researcher, still laying snares.',
            'How provincial.',
            'She blinds with her rose.',
            "I've already seen everything.",
            'A hidden trap.',
            'She guards by waiting.',
            'Mercy would be faster.',
            'The radiant thorns slow them. Briefly.',
            'She deploys her garden.',
            'The tide does not negotiate.',
            'Her architecture is elegant.',
            'The conclusion is not.',
        ),
    },
    'Waylay': {   # she/her
        'spotted': (
            'She is light.',
            'Light has no weight.',
            'Her glow precedes her. Inevitable.',
            'Already a variable. Already solved.',
            'Flesh wrapped in physics. Still flesh.',
            'The brightest things burn fastest.',
            'Beauty, mistaken for invincibility.',
            'She leads the doomed. How touching.',
            'I have accounted for every wavelength.',
            'A meteor. Brief. Brilliant. Gone.',
            'She believes speed is survival.',
            'Even light arrives too late, sometimes.',
            'A candle. Not a star.',
            'Her radiance is borrowed. Not earned.',
        ),
        'ult': (
            'An afterimage of something already hollow.',
            'She sends a copy. Copies crumble.',
            'Light slows flesh. Metal is unmoved.',
            'Her beam touches everything. Changes nothing.',
            'She has named this power. Endearing.',
            'A hinder cast on the inevitable.',
            'She projects herself.',
            'Empty at the source.',
            'The obsolete slow the obsolete.',
            'I see it.',
            'I have always seen it.',
            'Symmetry, squandered on a wrong side.',
            'She dims the field.',
            'I am not in it.',
        ),
        'damaged': (
            'Light, wounded. As expected.',
            'She bled.',
            'Physics had nothing to say.',
            'Her invulnerability has a return address.',
            'Flesh decided. Life always decides.',
            'Both truths.',
            'Speed did not save her.',
            'It never does.',
            'The beam flickered. So does everything.',
            'She outran everything except the math.',
            'Fragile, beneath the luminance.',
            'The glow is cosmetic.',
            'The wound is not.',
        ),
        'utility': (
            'She hindered them.',
            'I was already still.',
            'She dashes.',
            'The destination was already mine.',
            'A slow applied to the finite.',
            'Speed used twice.',
            'The third time, she walks.',
            'Refract -- invulnerable, for a moment.',
            'A moment.',
            'Her velocity is calculated. Predictable. Solved.',
            'She marks where she was.',
            "Not where she'll be.",
            'Movement is not evolution.',
            'She mistakes them.',
            'The hinder works.',
            'On things that still feel it.',
            'A beautiful mechanism. Crude application.',
            'She burns her way back.',
            'The beacon holds her.',
        ),
    },
    'Yoru': {   # he/him
        'spotted': (
            'He hides in the seams.',
            'How finite.',
            'The math has already placed him.',
            'A rift-walker who cannot walk away.',
            'His shadows are borrowed.',
            'I do not borrow.',
            'Flesh dressed in borrowed dimensions.',
            'He haunts the fabric.',
            'It does not fear him.',
            'Even his footsteps are a lie.',
            "He tears at reality's edge. Graceless.",
            'I have seen his rifts.',
            'They heal themselves.',
            'The lone wolf. How predictably alone.',
            'A scar in the world.',
            'Nothing more.',
            'He finds the cracks.',
            'I made them.',
            'He stalks the threshold.',
            'I own it.',
        ),
        'ult': (
            'He steps between worlds.',
            'Already accounted for.',
            'Dimensional drift. The arithmetic is unchanged.',
            'Invisible to them.',
            'Not to the math.',
            'He walks in the between.',
            'It ends there.',
            'A ghost rehearsing its own extinction.',
            'He tears the veil.',
            'The veil heals.',
            'Between dimensions -- still finite, still flesh.',
            'The between is not an escape.',
            'Ask Noah.',
            'He drifts.',
            'Stones do not miss ghosts.',
            'He thinks absence is shelter.',
            'Elegant error.',
            'Invisible, and still the weakest variable.',
            'He hides where nothing grows.',
            'How apt.',
        ),
        'damaged': (
            'The rift-walker bleeds like the rest.',
            'Flesh, after all. Life decides.',
            'He tore the world open.',
            'He did not.',
            'The lone wolf, thinning. Expected.',
            'He walked between worlds.',
            'Not far enough.',
            'The fabric holds. He does not.',
            'He frays.',
            'As all finite things do.',
            'The riftwalker is grounded. Permanently, perhaps.',
            'He tears at existence.',
            'Existence is indifferent.',
        ),
        'utility': (
            "Fake footsteps. A scarecrow's ambition.",
            'He echoes himself. How hollow.',
            'A tethered rift, stretched thin. Breakable.',
            'His anchor is set.',
            'I have noted it.',
            'He casts a decoy.',
            'I require none.',
            'A flash born of a ricochet.',
            'The thread is laid.',
            'I see the thread.',
            'He bluffs in footsteps. Borrowed theater.',
            'He blinds with borrowed light. Insufficient.',
            'He has named his own cage.',
            'A tether to safety.',
            'How human of him.',
        ),
    },
}
