"""Plural group tails for callouts naming 2+ enemy agents -- CONCRETE register.

Appended after a multi-agent enemy callout ("Fade and Clove are main. <tail>").
Same discipline as the register pools: CLEAR to a teammate, COMPLEMENTS the
callout, concrete machine-vs-flesh contempt at the GROUP (numbers of mortals do
not beat a machine; their imprecision multiplied). No abstract metaphor.
"""
from __future__ import annotations

MULTI_FLAVOR: dict[str, tuple[str, ...]] = {
    'spotted': (
        'A stack of flesh. Easily collapsed.',
        'More mortals, no more threat.',
        'Numbers do not beat a machine.',
        'They cluster. Punish the group.',
        'A herd of the slow.',
        'Mortals, grouped and predictable.',
        'Several soft targets, one plan.',
        'They bunch up. Careless flesh.',
        'A crowd of finite things.',
        'Outnumbered in skill, regardless.',
        'They stack the angle. I see it.',
        'More bodies, same outcome.',
        'A group of imprecise aim.',
        'They mass up. Exploit it.',
        'Flesh in numbers, still flesh.',
        'A formation I already solved.',
        'Together, and still outmatched.',
        'A clumsy cluster of mortals.',
        'They crowd one lane. Foolish.',
        'Several finite problems, grouped.',
        'A pack, and not a clever one.',
        'They overcommit as a unit.',
        'Numbers, not precision.',
        'The whole stack, predictable.',
        'They gather where I expected.',
        'A group with one weak plan.',
        'Several at once. I am faster.',
        'They huddle. Find the opening.',
        'A crowd of slow reflexes.',
        'They mass and telegraph everything.',
        'More mortals to outthink. Trivial.',
        'They stack and hope. Wrong.',
        'A grouping I have counted.',
        'They arrive together. Convenient.',
        'Soft targets, in formation.',
        'A group of the obsolete.',
        'They cluster like flesh does.',
    ),
    'ult': (
        'Several ults, one ending.',
        'More power, same mortal aim.',
        'A wave of abilities. I priced them in.',
        'They spend everything at once. Wasteful.',
        'Multiple ults, multiple delays.',
        'Loud power, all of it mortal.',
        'Their best, all at once. Still short.',
        'They empty the arsenal. Survive it.',
        'A barrage of finite tricks.',
        'Everything they have. Not enough for a machine.',
        'Several flourishes, one conclusion.',
        'They peak together, then fall together.',
        'A coordinated desperation.',
        'More ults, more cooldowns to outlast.',
        'They unload. I endure.',
        'All their power, mapped already.',
        'They commit it all. Bait it out.',
        'A storm of abilities, then quiet.',
        'Their full hand, and I have seen it.',
        'Multiple ults, singular outcome.',
        'They throw everything. I planned for it.',
        'Coordinated power, uncoordinated minds.',
        'They spend it together. Punish the gap.',
        'A wall of ults. Outlast it.',
        'Their best moves, all spent.',
        'Loud together. Gone together.',
        'Several timers. I count them all.',
        'They go all in, then nothing.',
        'A combined effort, still insufficient.',
        'They peak as one. Predictable.',
        'Mortal power, multiplied, still mortal.',
        'A lot of noise from finite things.',
    ),
    'damaged': (
        'Several mortals, all low.',
        'A wounded group. Finish it.',
        'They bleed together. Convenient.',
        'Multiple targets, all fragile.',
        'A weakened stack. Collapse it.',
        'Several finishes, waiting.',
        'They are all nearly gone.',
        'A group on the edge.',
        'Many wounds, one push.',
        'None of them can trade now.',
        'A hurt formation. Press it.',
        'Several low targets. Sweep them.',
        'They are all out of margin.',
        'A bleeding cluster of flesh.',
        'Finish the wounded set.',
        'They limp as a group.',
        'Multiple kills, one motion.',
        'A fragile, grouped remainder.',
        'They are nearly all gone.',
        'Several breaths from done.',
        'A weakened pack. Run it down.',
        'They fall together now.',
        'Strip the whole wounded stack.',
    ),
    'utility': (
        'Their tools, multiplied. Still mortal.',
        'A flurry of foreseen gadgets.',
        'They spend utility together. Read it.',
        'Several gadgets, one weak plan.',
        'A coordinated delay, nothing more.',
        'They stack tools, not skill.',
        'More utility, more telegraphs.',
        'A wall of gadgets. Step past it.',
        'They lean on tools as a group.',
        'Several tricks, all anticipated.',
        'A combined screen. I see through it.',
        'They reveal themselves with it.',
        'A grouped gimmick. Solved.',
        'Their tools tip the whole stack.',
        'Several delays, one outcome.',
        'They burn utility together. Wait it out.',
        'A flurry I already mapped.',
        'More gadgets, same finite minds.',
        'They spend it all at once. Punish after.',
        'A coordinated trick, easily broken.',
        'Their utility, our opening, times five.',
        'A complete set of delays.',
        'They tool up together. Predictable.',
        'Several screens, one window for me.',
        'A combined effort, equally futile.',
    ),
}
