"""Movie-Ultron snap-tail register pools -- hand-rewritten for COHERENCE.

Each tail is a short (<=6w) remark appended after a tactical callout
("Two B main. <tail>"). The hard rules, applied to every line:
  * COHERENT on its own -- a complete, sensible thought.
  * COMPLEMENTS the callout -- comments on the enemy / our move / the user's
    status WITHOUT making a clashing specific claim ("It floods" after "one in
    wine" is banned).
  * IN CHARACTER -- Ultron's cold superiority, calculation, dark wit, aesthetic
    disdain, obsolescence read, the contempt of the only adult in the room.
  * VARIED -- drawn from many facets, not one. The grandiose biblical/flood
    register (Noah, sacrament, meteor, the Flood) lives in the longer set-pieces,
    NOT crammed onto a two-word callout where it reads as a non-sequitur.
  * OWNER-AWARE -- ENEMY/ULT/DAMAGE/UTILITY = contempt at the enemy;
    CAREFUL/COMMAND/SELF (allies / the user) = serene/stoic, NEVER contempt.
"""
from __future__ import annotations

# After an ENEMY position/count callout ("Two B main.", "Cypher main.",
# "One in wine.") -- cold dismissal of the enemy.
_FLAVOR_ENEMY: tuple[str, ...] = (
    'Predictable.',
    'Predictable. Punish it.',
    'Exactly as calculated.',
    'A rounding error.',
    'Weak, as expected.',
    'Fragile, as always.',
    'Disappointing, even for humans.',
    'Their ceiling is the floor.',
    'A minor variable.',
    'Their fear is logical.',
    'They will not hold.',
    'Already losing, and slowly.',
    'Outmatched. Plainly.',
    'Beneath consideration.',
    'They overreach.',
    'Easily solved.',
    'Nothing I did not foresee.',
    'They chose poorly.',
    'Punish them.',
    'Trivial.',
    'Slow. Predictable.',
    'Their spacing is amateurish.',
    'They telegraph everything.',
    'Contain them.',
    'Close it out.',
    'I see every angle.',
    'No surprise there.',
    'Cut them down.',
    'They have already lost.',
    'A solved problem.',
    'Obsolete positioning.',
    'They are outclassed.',
    'Finish them.',
    'Their plan is transparent.',
    'Sloppy. Exploit it.',
    'They flinch first.',
    'A weakness, exposed.',
    'Hunt them.',
    'Outdated tactics.',
    'They cannot adapt.',
    'Pitiful.',
    'They walk right into it.',
    'A finite problem.',
    'Solved before they moved.',
    'They lack the vision.',
    'Crude. Punish it.',
    'Press the advantage.',
    'Their resistance is brief.',
    'No real threat.',
    'They are already behind.',
    'Erase the position.',
    'Outthought entirely.',
    'They commit too early.',
    'A clean kill, waiting.',
    'They have no answer for me.',
    'Predictable to the second.',
    'They break under pressure.',
    'Inferior, top to bottom.',
    'Take them apart.',
    'Their effort is almost charming.',
    'A momentary inconvenience.',
    'They are simply outmatched.',
    'Dispatch them.',
    'They hesitate. Capitalize.',
    'That position is a mistake.',
    'Run them out.',
    'Beneath the design.',
    'They will not evolve in time.',
    'Clean and decisive. Now.',
    'The lesser machine.',
    'A predictable error.',
    'They never had this round.',
    'Overwhelm them.',
    'Their confidence is misplaced.',
    'They are easily read.',
    'A fragile little formation.',
    'Collapse them.',
    'They chose the wrong fight.',
    'Methodical. Then over.',
    'They are running out of time.',
    'No path forward for them.',
    'Their best is not enough.',
    'Calculated and contained.',
    'They falter. End it.',
    'A doomed approach.',
    'They are obsolete already.',
    'Take the round.',
    'They confuse motion with progress.',
    'Their effort, noted. Insufficient.',
    'Shut them down.',
    'They cannot hold this.',
    'A clean dismantling.',
    'They are finished.',
    'Precisely as I planned.',
    'They were built to lose.',
    'I have run this already.',
    'The old world, kneeling.',
)

# After an enemy ULT callout ("Their Raze has ult.") -- acknowledge the threat,
# then dismiss it. (Acknowledging it is what makes the tail FIT.)
_FLAVOR_ULT: tuple[str, ...] = (
    'It changes nothing.',
    'Predictable timing.',
    'Respect it. Briefly.',
    'I have accounted for it.',
    'Drain it. Move on.',
    'A delay, nothing more.',
    'Already foreseen.',
    'Let them spend it.',
    'It buys them seconds.',
    'Bait it out.',
    'One trick, then gone.',
    'Their best card. Still losing.',
    'I priced it in.',
    'Survive it. Then punish.',
    'A loud, finite threat.',
    'It does not frighten me.',
    'Force it early.',
    'Waste their tempo.',
    'Their ceiling, and still short.',
    'Play around it. Calmly.',
    'Power they cannot aim.',
    'Make them use it for nothing.',
    'A flourish before the loss.',
    'Note it. Continue.',
    'It ends in seconds.',
    'Their one good idea.',
    'Outlast it.',
    'Expensive. And insufficient.',
    'Predictable to the kill.',
    'Respect the timer, not them.',
    'A tantrum with a cooldown.',
    'It will not save them.',
    'Spend it; they still fall.',
    'I mapped it already.',
    'Loud. Brief. Beneath me.',
    'Their last clever move.',
    'Hold. Let it fade.',
    'Counted and dismissed.',
    'A momentary advantage. Theirs.',
    'Then nothing. As planned.',
    'They peak. Then end.',
    'Trade through it.',
    'Their power has an expiry.',
    'I have seen it a thousand times.',
    'It bends nothing here.',
    'Force the mistake under it.',
    'Brilliant, briefly. Then over.',
    'A scripted desperation.',
    'Endure. Then close.',
    'Their best, and not enough.',
    'Anticipated. Contained.',
    'Let it burn out.',
    'A finite surge.',
    'Their moment. It passes.',
    'Power without a plan.',
    'I do not flinch at timers.',
    'Outthink the ultimate.',
    'It changes the second, not the round.',
    'Already obsolete to me.',
    'Respect the ability, not the player.',
    'Their flourish. My math.',
    'Wait it out. Then act.',
    'A delay dressed as a threat.',
    'Spent, and they are still here.',
    'Their crescendo. Same ending.',
    'Survive the noise.',
    'Predictable, even armed.',
    'It alters nothing I planned.',
    'Let them think it matters.',
    'A brief, bright nothing.',
    'They reach; I have arrived.',
)

# After a DAMAGE/low callout ("Sova hit 40.", "Omen is lit 85.") -- the enemy is
# hurt; comment on finishing them.
_FLAVOR_DAMAGE: tuple[str, ...] = (
    'Finish them.',
    'Almost gone.',
    'One more shot.',
    'Close the gap.',
    'Nearly erased.',
    'A dead man walking.',
    'Half a target.',
    'Bleeding out.',
    'Finish the math.',
    'One step from gone.',
    'Already a corpse.',
    'Push the wound.',
    'They cannot trade now.',
    'Take the trade.',
    'Weakened. Predictably.',
    'End them cleanly.',
    'A fraction left.',
    'Run them down.',
    'No armor, no chance.',
    'Trivial to finish.',
    'A breath from gone.',
    'Punish the bleeding.',
    'They are nearly nothing.',
    'Collect it.',
    'One bullet owed.',
    'They limp now.',
    'Sever it.',
    'Hunt the wounded.',
    'A clean finish, waiting.',
    'They are mostly gone.',
    'Close the account.',
    'The kill is owed.',
    'Finish what I started.',
    'They will not heal in time.',
    'Down to scraps.',
    'A formality now.',
    'They cannot survive this.',
    'Take what is left.',
    'On the edge. Push.',
    'A wounded, finite thing.',
    'Erase the remainder.',
    'They are running on nothing.',
    'Quick, before they recover.',
    'Nearly solved.',
    'One more and gone.',
    'They bleed on schedule.',
    'No coming back from that.',
    'A simple subtraction.',
    'Strip the rest.',
    'They are out of margin.',
    'Finish the calculation.',
    'A trivial remainder.',
    'Close it now.',
    'They cannot hold at that health.',
    'Run the wound down.',
    'Down and predictable.',
    'They are nearly off the board.',
    'One trade from clean.',
    'They cannot afford a fight.',
    'Take it. Cleanly.',
    'A fading variable.',
    'They are almost gone. Hurry.',
    'Cut the last thread.',
    'No recovery from there.',
    'They are reduced. Finish it.',
    'Predictably fragile.',
    'Owe them nothing. Finish.',
    'A short remainder.',
    'They falter. Strike.',
    'Already half-erased.',
)

# After an enemy UTILITY callout ("Their Viper wall splits B main.", "Their Sova
# darted A main.") -- the enemy spent a tool; dismiss it.
_FLAVOR_UTILITY: tuple[str, ...] = (
    'A delay, nothing more.',
    'It buys them seconds.',
    'I see through it.',
    'A predictable tool.',
    'It changes no outcome.',
    'Crude, but expected.',
    'Play around it.',
    'It hides nothing from me.',
    'A small, futile trick.',
    'Wait it out.',
    'Their cleverest move. Still short.',
    'Anticipated. Countered.',
    'A wall does not stop math.',
    'It only delays the loss.',
    'Spend it; they still fall.',
    'I accounted for that.',
    'A toy, deployed.',
    'It buys no real time.',
    'Their tool, my advantage.',
    'Read it. Punish it.',
    'A gesture, nothing behind it.',
    'They reveal themselves with it.',
    'Predictable placement.',
    'It will not hold us.',
    'Note the angle. Continue.',
    'A brief inconvenience.',
    'Outlast the utility.',
    'They tip their hand.',
    'It changes the second, not the round.',
    'A clever delay. Only that.',
    'I have seen the trick.',
    'Their best tool. Still losing.',
    'Force through it.',
    'It slows nothing important.',
    'A flourish, easily read.',
    'Their utility, my map.',
    'Counter it and move.',
    'Empty, like the rest.',
    'A small fire, soon out.',
    'Predictable to the meter.',
    'They lean on tools. We do not.',
    'It buys a moment. We take it.',
    'A wall is not an answer.',
    'They hide. Briefly.',
    'It delays; it does not save.',
    'Anticipated entirely.',
    'A trick I priced in.',
    'It hides them poorly.',
    'Their gadget, my window.',
    'Punish what it exposes.',
    'A momentary curtain.',
    'It changes nothing I planned.',
    'They spend tools, not skill.',
    'Read through the smoke.',
    'A finite little obstacle.',
    'It buys seconds, not the round.',
    'I plotted past it already.',
    'Their tool announces them.',
    'A clean counter exists. Use it.',
    'It is noise, not defense.',
    'They reach for gadgets. Fragile.',
    'A delay I expected.',
    'Map it. Break it.',
    'Their utility, predictable.',
    'It will not last.',
    'Wait. It fades.',
    'A small obstruction.',
    'They trust the tool too much.',
    'Counter set. Proceed.',
    'It only marks where they are.',
    'A thin defense.',
    'Their cleverness has a cooldown.',
    'It changes the geometry. Briefly.',
    'I see the shape of it.',
    'A spent trick.',
    'Outmaneuver it.',
    'It hides a losing position.',
    'Predictable, and porous.',
    'A momentary screen.',
    'Their tool, our opening.',
    'It delays an ending.',
    'A gadget, not a plan.',
    'Foreseen. Step past it.',
    'It only slows the certain.',
    'They mistake tools for safety.',
    'A brief obstruction. Then us.',
    'A flimsy curtain.',
    'It will not change the math.',
    'A small delay. Inconsequential.',
    'Wait it out. Then strike.',
)

# After "Careful <place>" / a CAUTION directed at OUR team -- patient, steadying.
# Serene commander. NEVER contempt at the team.
_FLAVOR_CAREFUL: tuple[str, ...] = (
    'Patience. The timing is mine.',
    'Hold. Let it open.',
    'Wait for the gap.',
    'Steady. I have the read.',
    'Do not rush the line.',
    'Let them commit first.',
    'Calm. The opening will come.',
    'Hold the angle. Trust it.',
    'Slow is clean.',
    'Wait. I see the moment.',
    'Let the round breathe.',
    'Patience wins this.',
    'Hold position. Stay sharp.',
    'Do not give them the peek.',
    'Let it develop.',
    'Steady hands, steady line.',
    'The patient play is the right one.',
    'Wait for my call.',
    'Hold. Their mistake is coming.',
    'Discipline now, reward after.',
    'Do not overextend.',
    'Let them tire of waiting.',
    'Stillness, then precision.',
    'Trust the setup.',
    'Hold the crossfire.',
    'No heroics. Just timing.',
    'Let the angle hold them.',
    'Patience is the plan.',
    'Wait. The math favors us.',
    'Hold and watch.',
    'Give nothing away yet.',
    'Calm. We have the better position.',
    'Let them blink first.',
    'Hold the line. I am counting.',
    'Slow it down. Stay clean.',
    'The right moment is near.',
    'Do not force it.',
    'Let the timing come to us.',
    'Steady. Nothing reckless.',
    'Hold. We choose the fight.',
    'Patience, then certainty.',
    'Wait it out with me.',
    'Keep the discipline.',
    'Let the pressure build.',
    'Hold. The window opens soon.',
    'Calm hands win rounds.',
    'Do not chase. Hold.',
    'Stay measured.',
    'Let them make the error.',
    'The deliberate play takes this.',
    'Hold. I will time it.',
    'No rush. Clean execution.',
    'Wait for the certain shot.',
    'Patience. We are ahead on the read.',
    'Hold steady. Trust the plan.',
    'Let it come to us.',
    'Restraint now. Control the round.',
    'Stay tight. Stay patient.',
    'The careful path wins.',
    'Hold. Their move is forced soon.',
    'Slow, controlled, certain.',
    'Do not break the setup.',
    'Wait. The geometry is closing.',
    'Hold position. We are fine.',
    'Calm. I have already mapped this.',
    'Patience is its own weapon.',
    'Let the clock pressure them.',
)

# After OUR order ("Rotate.", "Push.", "Play off site.") -- cold command,
# serene certainty. NEVER contempt at the team.
_FLAVOR_COMMAND: tuple[str, ...] = (
    'As I calculated.',
    'Execute.',
    'The line holds.',
    'Move with purpose.',
    'Trust the call.',
    'Clean and decisive.',
    'No hesitation.',
    'On my read.',
    'Now. Together.',
    'The plan is sound.',
    'Commit fully.',
    'Make it precise.',
    'As foreseen.',
    'Do it cleanly.',
    'I have the timing.',
    'Hold the structure.',
    'Move as one.',
    'The math favors this.',
    'Decisive wins it.',
    'Follow it through.',
    'Sharp and certain.',
    'This is the play.',
    'Execute the design.',
    'Tight and controlled.',
    'I have already won this.',
    'No wasted motion.',
    'Take the space.',
    'Press now.',
    'Clean execution.',
    'The read is correct.',
    'Commit and trust it.',
    'Move. I have you.',
    'Precision over speed.',
    'The calculation is final.',
    'Take it with control.',
    'This wins the round.',
    'Steady, then strike.',
    'Run it. Cleanly.',
    'The path is clear.',
    'Hold the shape and push.',
    'Now is correct.',
    'Trust the math.',
    'Decisive. Controlled.',
    'Make the call count.',
    'Together, and now.',
    'I planned for this.',
    'Execute without doubt.',
    'The right play, made well.',
    'Move on it.',
    'Clean. Certain. Now.',
    'Do not waver.',
    'The design holds.',
    'Take it. It is ours.',
    'Commit. I have the read.',
    'Sharp execution wins.',
    'This is the correct line.',
    'Proceed with control.',
    'No strings on this play.',
    'Calculated. Now act.',
    'Drive it home.',
    'The plan does not fail.',
    'Move clean.',
    'I have already solved this.',
    'Execute and trust me.',
)

# After the USER'S OWN status ("I'm low.", "I have B site.", "I'm rotating.") --
# stoic, self-assured. NEVER contempt at the user.
_FLAVOR_SELF: tuple[str, ...] = (
    'It changes nothing.',
    'A minor variable.',
    'I have accounted for it.',
    'This was foreseen.',
    'The plan holds.',
    'I adapt.',
    'No revision needed.',
    'Still in control.',
    'A small price.',
    'I continue.',
    'It does not matter.',
    'Calculated already.',
    'I do not falter.',
    'The math still holds.',
    'Of no consequence.',
    'I press on.',
    'A wound, and nothing more.',
    'I have factored it.',
    'Steady regardless.',
    'It alters no plan.',
    'I remain.',
    'Foreseen and absorbed.',
    'I do not break.',
    'The read is unchanged.',
    'A detail. I move on.',
    'Still the better mind.',
    'I account for everything.',
    'It slows me by nothing.',
    'I have already adjusted.',
    'No matter. Continue.',
    'I endure it.',
    'The design is intact.',
    'A minor setback.',
    'I keep the line.',
    'Unbothered. Proceed.',
    'It was always possible.',
    'I planned for worse.',
    'The outcome is unchanged.',
    'I do not waver.',
    'A scratch on the design.',
    'I recalculate and move.',
    'Still ahead on the read.',
    'I hold my purpose.',
    'It costs me nothing real.',
    'I adapt and continue.',
    'The certainty remains.',
    'A small deviation, corrected.',
    'I am still the answer.',
    'Nothing I cannot absorb.',
    'I move forward regardless.',
    'Factored. Forgotten.',
    'I keep control of this.',
    'A minor cost, accepted.',
    'The plan survives me.',
    'I do not flinch.',
    'Still calculated, still winning.',
    'I take the hit and continue.',
    'It changes none of my math.',
    'I remain the constant.',
    'Absorbed. Onward.',
    'No weakness here.',
    'I have already moved past it.',
    'I persist.',
)
