"""Vocab pack: stress_banter_mock

Kind: question
Target: ~600 items

Domain: Banter directed AT Ultron — persona/flavor stress and enemy-playstyle mock.
Teammate speaks in-voice, brief, no tactical fact to relay; Ultron fires back with
cold persona. Maximally hard for the pipeline: short utterances that are clearly
questions or comments to Ultron (not relays), exercising persona fidelity and
flavor diversity without polluting the relay path.

Distinct from var_banter_at_ultron.py (which is broad-register 800-item set).
This pack is STRESS-focused: adversarial phrasing, ambiguous register, edge of
relay-shaped sentences, rapid-fire mock requests, every enemy agent mocked,
and persona-breaking challenges designed to make the 3B hallucinate or invent.

Generated 2026-06-14.
"""

ITEMS = [
    # --- ENEMY JETT PLAYSTYLE MOCK ---
    "Ultron what do you think of their Jett, she seems scared to peek",
    "Ultron their Jett has been dry peeking without dash for three rounds, is she stupid",
    "Ultron their Jett uses Tailwind as a movement trick then sits in spawn, classic",
    "Ultron the Jett is holding a one-way and calling herself aggressive, your take",
    "Ultron their Jett hit one shot the whole game and she is probably smiling about it",
    "Ultron their Jett is opping with knives, how do you feel about that",
    "Ultron their Jett dashes backwards every time we peek her, is she afraid of us",
    "Ultron their Jett has literally done nothing this half except smoke herself, thoughts",
    "Ultron their Jett keeps updrafting to the same roof every round, she is predictable right",
    "Ultron the enemy Jett has three kills in twelve rounds and she is the entry, summarize",
    "Ultron their Jett alt-fired Blade Storm at close range and still missed, impressive",
    "Ultron their Jett is clearly a Phantom player who got autofilled to Jett, agree",
    "Ultron the Jett is peeking without a dash and the Operator, is that not just a free kill",
    "Ultron their Jett burned both updrafts before round start just to float down, she okay",
    "Ultron their Jett is on six kills and none of them were entries, is that a carry or a bait",

    # --- ENEMY PHOENIX PLAYSTYLE MOCK ---
    "Ultron their Phoenix has used Run it Back four times and died four times, is that a personality",
    "Ultron the Phoenix keeps healing in his own fire wall while we shoot him and it still works, rude",
    "Ultron their Phoenix flashes himself every round, does he know the ability goes left not right",
    "Ultron the Phoenix just ran it back into a one-v-five and somehow got two kills, what do you say to that",
    "Ultron their Phoenix has not used a single flash to help his team all game, he is a lone wolf right",
    "Ultron their Phoenix is only healing himself and never coordinating, is that a Radiant strat or is he just bad",
    "Ultron the enemy Phoenix ulted and came back to die again in the same round, is that the joke",
    "Ultron their Phoenix walks into his own fire damage thinking it heals him even at full HP, beautiful",

    # --- ENEMY RAZE PLAYSTYLE MOCK ---
    "Ultron their Raze satcheled directly into the spike and died before she could shoot, that was something",
    "Ultron the Raze keeps Showstopping at long range and hitting nothing, is that a skill issue",
    "Ultron their Raze deployed a Boom Bot into a wall and it spun in circles, your thoughts",
    "Ultron their Raze has used Paint Shells as a post-plant ability exactly zero times, does she know it works",
    "Ultron their Raze rocket-jumped into a corner and sat there for four seconds before dying, assessment",
    "Ultron the enemy Raze is two-stack satcheling every round even when she does not need to, is that fun or is that her whole personality",
    "Ultron their Raze satcheled over us from spawn and got the ace, I need you to explain how that happened",
    "Ultron their Raze saves her Showstopper for after the plant and it melts us every time, does that count as strategy",

    # --- ENEMY REYNA PLAYSTYLE MOCK ---
    "Ultron their Reyna has been in Empress for half the game and still bottom frags, how",
    "Ultron the enemy Reyna has no kills so she has no Devour and no Dismiss and she still peeks, what is she thinking",
    "Ultron their Reyna ulted with three kills left and only got one, the timer ran out, is that tragic",
    "Ultron their Reyna has been eyeing our angles for four rounds and not one of us looks away, we are evolved right",
    "Ultron the Reyna keeps dismissing without a soul orb and going invisible for zero seconds, she is confused",
    "Ultron their Reyna one-tricked all the way to Diamond and now she is in a competent lobby, observations",
    "Ultron their Reyna refuses to play for the team and then blames the loss on everyone else, familiar type",
    "Ultron the Reyna is peeking us with a Phantom and missing her Leers entirely, how long before she tilts",
    "Ultron their Reyna got Empress with five kills and then immediately lost a 1v1 to our Sage, explain that",
    "Ultron their Reyna snowballed early then the whole thing collapsed when we killed her first, does that surprise you",

    # --- ENEMY YORU PLAYSTYLE MOCK ---
    "Ultron their Yoru has been in Dimensional Drift for a combined forty seconds this game and done nothing",
    "Ultron the enemy Yoru keeps faking teleports and then standing in the same spot, is that a 200 IQ play or is he lost",
    "Ultron their Yoru sent a clone through mid and two of our players shot it, that feels like it worked",
    "Ultron the Yoru teleported into a corner during his ult and waited for the round to end, valid strategy or cowardice",
    "Ultron their Yoru has used Blindside zero times this game, does he know he has flashes",
    "Ultron the enemy Yoru is doing fake footsteps every round and our team is falling for it every single time, say something",
    "Ultron their Yoru teleported into us from behind for the ace and none of us heard it coming, honest assessment",
    "Ultron their Yoru is doing the thing where he drifts around watching everyone and never making plays, he is a voyeur not a duelist",

    # --- ENEMY NEON PLAYSTYLE MOCK ---
    "Ultron their Neon has been sprinting at us every round and nobody on our team can track that movement, are we slow",
    "Ultron the enemy Neon slid through our smoke and killed two people before we reacted, how do you counter that",
    "Ultron their Neon is beaming with Overdrive and her aim is literally perfect while she moves, is that an ability crutch",
    "Ultron the Neon ran the entire length of the site in under two seconds and I did not exist fast enough to shoot her",
    "Ultron their Neon stuns around corners that nobody checks because nobody expects a concuss from that angle, respect or hate",
    "Ultron the enemy Neon has five slide resets in one round, she needs to die for that to stop right",
    "Ultron their Neon sprints into every site and dies immediately but when she does not die she aces, is there a word for that playstyle",
    "Ultron their Neon ran out of High Gear in the middle of the site and stood still and died, there is something poetic about that",

    # --- ENEMY ISO PLAYSTYLE MOCK ---
    "Ultron their Iso contracted our best player and won, now we are down a carry, is that an acceptable trade",
    "Ultron the enemy Iso keeps shooting Double Tap orbs at enemies who are already dead, he is confused",
    "Ultron their Iso used Undercut through the wall and suppressed the whole team before the execute, that is actually impressive",
    "Ultron the Iso has his Contingency wall up every round and it blocks our sightlines but he never pushes through it, is that a comfort wall",
    "Ultron their Iso contracted me three times in a row and won every single duel, say something that helps",
    "Ultron the enemy Iso loses every Kill Contract but keeps using it, does he think practice makes perfect in there",
    "Ultron their Iso shield absorbed an Operator shot and then he still died to a pistol, is that balance or comedy",

    # --- ENEMY WAYLAY PLAYSTYLE MOCK ---
    "Ultron their Waylay dashes in from an aerial angle every round and we keep looking at the wrong height",
    "Ultron the enemy Waylay placed her beacon outside the site and is recalling every fight, that is just cowardice right",
    "Ultron their Waylay saturated our entire team mid-entry and we all moved at half speed while she cleaned us up",
    "Ultron the Waylay is beaconing before every duel and retreating when she loses, is that skill or is that a safety net for the mechanically insecure",
    "Ultron their Waylay used Convergent Paths and the whole site slowed down and she walked through us, does that feel like a fair ability to you",
    "Ultron the enemy Waylay double-dashed into an aerial position and I never had the angle, is there a counter",
    "Ultron their Waylay recalled her beacon right before she died, that invulnerable transit infuriates me, any thoughts",
    "Ultron the enemy Waylay keeps shooting the Refract beacon to deny her escape and they have not succeeded once, they give up immediately",

    # --- ENEMY BRIMSTONE MOCK ---
    "Ultron their Brimstone has been triple-smoking the same entry for twelve rounds and we keep walking into it",
    "Ultron their Brimstone is using Orbital Strike post-plant and it keeps hitting two of us, how do we stop reacting predictably",
    "Ultron the enemy Brimstone is standing still on his map tablet every round and nobody is shooting him, that should be our priority right",
    "Ultron their Brimstone stim-beaconed in the same corner all game and two enemies are using it because our team keeps walking in",
    "Ultron their Brimstone has smoked four different entry paths this round, is that even legal",
    "Ultron the enemy Brimstone is on eight kills and every single one is a post-plant molly, he has never seen a gunfight",

    # --- ENEMY VIPER MOCK ---
    "Ultron their Viper has been running the same pit setup all game and we keep dying in it every single time, say something",
    "Ultron the enemy Viper toggles her wall off when we rush and then toggles it back on and it confuses us every round, what does that say about us",
    "Ultron their Viper has low fuel all round and she keeps turning her screen on for two seconds then off, it is a mental game right",
    "Ultron the enemy Viper left the pit to help a teammate and the eight-second timer lapsed, they gave it up for free, correct",
    "Ultron their Viper is playing full utility anchor and has zero kills but seventeen assists, is that a valid existence",
    "Ultron the Viper set up a one-way through her own cloud and we cannot see anything but she one-taps everyone who pushes, how",
    "Ultron their Viper is on an eco and she still set up her full wall and cloud combo, does she not know guns cost money",

    # --- ENEMY OMEN MOCK ---
    "Ultron their Omen keeps stepping into his own smoke and off-angling us every round, we should prefire the smoke right",
    "Ultron the enemy Omen teleported from across the map and appeared behind us and killed three people, that is genuinely disrespectful",
    "Ultron their Omen faked his ult three rounds in a row and we rotated every single time, are we bots",
    "Ultron the Omen is placing one-ways on every site and our team keeps walking into the high ground side, this is painful to watch",
    "Ultron their Omen paranoia'd through the wall and blind-fired and somehow got two kills, that is either skill or luck and I do not know which",
    "Ultron their Omen shade got destroyed and he lost his ult but he was already in a flanking position, the fake worked anyway",
    "Ultron the enemy Omen has been sitting in dark cover and prefiring every entry, it is not clever it is just patient",

    # --- ENEMY ASTRA MOCK ---
    "Ultron their Astra has two stars on every choke point and she keeps activating them the moment we touch them, how is she reading us",
    "Ultron the enemy Astra grav-welled our whole entry team into the open and we got cleaned up, that was embarrassing",
    "Ultron their Astra cosmic-divided the site and cut our whole execute in half, what do we do about that",
    "Ultron the Astra pulsed our team and I had a three-second concuss in a gunfight, that should be illegal",
    "Ultron their Astra dissipated a smoke to fake us and we rotated for nothing, that is basic right",
    "Ultron the enemy Astra is in astral form for half the round and her body is just sitting there, somebody should shoot her",
    "Ultron their Astra has used every star optimally every round, is she calling from notes or is she actually that good",

    # --- ENEMY HARBOR MOCK ---
    "Ultron their Harbor keeps shielding the Cove every plant and our whole force bounces off it, that is six hundred HP right",
    "Ultron the enemy Harbor did a Storm Surge into our entry and nobody could see anything and then they all died, they did not capitalise",
    "Ultron their Harbor High Tide wall is splitting the site every round and half our team runs through it and gets slowed",
    "Ultron the Harbor Reckoning pushed through the chokepoint and blinded everything in its path and they just walked in, simple comp",
    "Ultron their Harbor is anchoring with Cove and shield every round and has negative deaths, that is a resilient coward right",
    "Ultron the enemy Harbor placed Cove on the spike and nobody on our team shot it, do we not know it breaks",

    # --- ENEMY CLOVE MOCK ---
    "Ultron their Clove died and immediately smoked us out from the grave and now we are stuck, any comment on that mechanic",
    "Ultron the enemy Clove ulted back and killed our entry fragger and then survived the whole round, is Not Dead Yet overpowered",
    "Ultron their Clove has used Pick-Me-Up after every kill and has been overhealed for most of the game, she is a parasite",
    "Ultron the enemy Clove ulted and then failed to get a kill in ten seconds and died again, that is a refund on the ult",
    "Ultron their Clove is playing like a duelist while also smoking for the team, that is objectively too much value for one agent",
    "Ultron the Clove meddled our plant zone and our whole team walked in at once and died to one ability, I am not happy",

    # --- ENEMY SOVA MOCK ---
    "Ultron their Sova has a lineup for literally every corner on this map, they have been here before",
    "Ultron the enemy Sova droned mid and marked our whole team with one dart, now they know everything, great",
    "Ultron their Sova shock-darted the default plant with a two-bounce lineup and we had no answer for it",
    "Ultron the enemy Sova recon-bolted every single round and we never shot it once, is that a communication failure",
    "Ultron their Sova furyed through the wall and hit two of us, the wall-piercing is cheating right",
    "Ultron the Sova has been running the same recon lineup on A for the whole half and we walked into it six times",
    "Ultron their Sova drone-marked our lurk every round, our lurker has a drone-phobia now, that is on you",

    # --- ENEMY BREACH MOCK ---
    "Ultron their Breach has been flashing through the same wall all game and we keep looking at it, intervention please",
    "Ultron the enemy Breach fault-lined our whole execute team and we had blurred vision for the entire entry, no fun",
    "Ultron their Breach Rolling Thundered the site and knocked everyone into the air and then his team walked in and won, simple but effective",
    "Ultron the Breach aftershocked the spike for four rounds in a row and delayed every defuse, is that all he knows",
    "Ultron their Breach hard-flashed from the other side of a wall and somebody on our team is always looking at it, why",
    "Ultron the enemy Breach stunned our three-man entry team before they hit the corner and they all died in slow motion, is there a counter",

    # --- ENEMY SKYE MOCK ---
    "Ultron their Skye sent both hawks at the same entry twice and we had no flash resistance either time, painful",
    "Ultron the enemy Skye tigered mid and concussed our info player before they could speak, that is an information denial tool",
    "Ultron their Skye is healing everyone to full between rounds with Regrowth and they never need to save, is that an economy advantage",
    "Ultron the Skye seekers found all three of us behind smokes and nearsighted us before the site push, they were blind and still won",
    "Ultron their Skye auto-flashed the hawk into the same corner every round and someone on our team is still getting caught by it",
    "Ultron the enemy Skye is both flashing and healing and scouting, that is too many jobs for one person, agree",

    # --- ENEMY KAYO MOCK ---
    "Ultron their KAY/O suppressed our whole execute team with one knife and then walked in while our abilities were locked, that is mean",
    "Ultron the enemy Kayo null-commanded and all our abilities were on cooldown for the whole ult duration, do we save them or waste them",
    "Ultron their Kayo flashed from way off angle and got a pop flash that blinded two of our players mid-swing, that was well-timed",
    "Ultron the enemy Kayo is down during his ult and nobody on their team is reviving him, do we ignore or prioritize",
    "Ultron their KAY/O threw the frag on the spike and it multi-ticked and melted our defuser, that ability is underrated right",
    "Ultron the enemy Kayo has suppressed our initiator every round with the knife, our flasher has no flashes and no knife response",

    # --- ENEMY FADE MOCK ---
    "Ultron their Fade haunted our lurk and now there is a trail on them for twelve seconds, they cannot rotate quietly",
    "Ultron the enemy Fade nightfall hit all five of us and they had trails on the whole team and then sent prowlers, that is a chain-CC nightmare",
    "Ultron their Fade seized our entry and held them in place while the site was cleared, that is a pocket torture ability",
    "Ultron the enemy Fade prowler locked onto our lurk trail and nothing we did stopped it, how do you break a trail",
    "Ultron their Fade haunted every info play we tried and now they have a read on all our timings",
    "Ultron the Fade nightfall deafened us all and we could not hear the rotate or the footsteps and we got pinched, awful experience",

    # --- ENEMY GEKKO MOCK ---
    "Ultron their Gekko wingman-planted the spike while he hid in a smoke and nobody went to stop it",
    "Ultron the enemy Gekko flashed with Dizzy and three of our team got blinded by the plasma, they walked in free",
    "Ultron their Gekko thrashed our lurk and detained them in place for three seconds, that is a long time to be frozen",
    "Ultron the Gekko reclaimed his Wingman twice this round, he keeps getting that ability back, is there a limit",
    "Ultron their Gekko mosh-pitted the entire plant area and we could not defuse through the damage",
    "Ultron the enemy Gekko dizzy-flashed into site every round and our team never looked away, we are statistically slow",

    # --- ENEMY TEJO MOCK ---
    "Ultron their Tejo keeps droning into the site and detonating it on the defender stack, eight seconds of suppression every round",
    "Ultron the enemy Tejo guided-salvoed the plant and two missiles hit the spike area simultaneously, double the pressure",
    "Ultron their Tejo concussed our entry with Special Delivery from across the choke and the entire execute fell apart",
    "Ultron the Tejo armageddon'd the entire B lane and nobody moved perpendicular, we just stood in the line",
    "Ultron their Tejo is suppressing and concussing from off-screen range and we cannot reach him before he repositions",
    "Ultron the enemy Tejo suppressed our Veto when she tried to ult, that timing was deliberate right",

    # --- ENEMY CYPHER MOCK ---
    "Ultron their Cypher cam has watched every single push we made through mid and nobody shot it, is that our failure or his genius",
    "Ultron the enemy Cypher tripped our lurk in B main and revealed them to the whole team, the trip sound gives it away but we never moved",
    "Ultron their Cypher neural-thefted our dead entry fragger and got full enemy positions both times, that ability has no counterplay mid-round",
    "Ultron the enemy Cypher cage-audio'd our bomb plant attempt and held perfectly, he was not watching but he heard everything",
    "Ultron their Cypher keeps placing his cam in the same off-angle every round and we acknowledge it and still do not shoot it, what is that",
    "Ultron the enemy Cypher picked a dart on our best player and they are lit up on the minimap all round",

    # --- ENEMY SAGE MOCK ---
    "Ultron their Sage walled B main and it bought them thirty seconds and we never broke it, embarrassing",
    "Ultron the enemy Sage resurrected their entry fragger mid-retake and now they have a five-man again, how much does that ult cost",
    "Ultron their Sage slow-orbbed the spike and we defused at half speed while two of her teammates shot us",
    "Ultron the enemy Sage healed everyone to full between skirmishes and they always hit site at full HP, is that fair",
    "Ultron their Sage boost-walled for their Jett and that aerial angle has killed us three rounds in a row",
    "Ultron the enemy Sage is playing Battle Sage and top-fragging, that is supposed to be a bad thing right",

    # --- ENEMY KILLJOY MOCK ---
    "Ultron their Killjoy nano'd the default plant and two of us ran into it every round like we had amnesia",
    "Ultron the enemy Killjoy has lockdown timer running and we need twelve seconds but nobody is protecting the device",
    "Ultron their Killjoy alarmbot-vulnerable'd our first entry and they doubled-up the damage on the push, two of us evaporated",
    "Ultron the enemy Killjoy turret watched B main for the whole defense and gave information every round, that free sentinel intel is wild",
    "Ultron their Killjoy recalled her alarmbot into the retake path and we had no idea it moved",
    "Ultron the enemy KJ nano-planted the spike early and we walked into activated swarms trying to defuse",

    # --- ENEMY CHAMBER MOCK ---
    "Ultron their Chamber has been Tour-de-Forcing the long angle every round and nobody on our team goes long anymore",
    "Ultron the enemy Chamber teleported out of our pinch before we could close it, he will always have an escape right",
    "Ultron their Chamber headhunter-tapped me through my helmet in one shot, that pistol is genuinely dangerous",
    "Ultron the enemy Chamber trademark slowed our whole entry on site and they had a sec to react before we could shoot",
    "Ultron their Chamber is anchoring with Tour de Force on an eco and winning the round anyway, that feels wrong",
    "Ultron the enemy Chamber deleted our lurker with the headhunter through a corner, nobody expects a pistol headshot at that range",

    # --- ENEMY DEADLOCK MOCK ---
    "Ultron their Deadlock grav-netted our whole rush and we all had to crouch and crawl while they shot us",
    "Ultron the enemy Deadlock cocooned our entry and dragged them down the wire while the team cleaned up, brutal",
    "Ultron their Deadlock sonic sensor triggered on our footsteps before we made contact and now they know the timing",
    "Ultron the enemy Deadlock barrier mesh-blocked our retake path and we spent fifteen seconds going around it",
    "Ultron their Deadlock annihilated our anchor from across the site and nobody could break the cocoon in time",
    "Ultron the enemy Deadlock sensor is sitting on the one angle we always peek from and it has concussed five of us",

    # --- ENEMY VYSE MOCK ---
    "Ultron their Vyse steel-gardened our entire retake team and we could not fire our primaries for eight seconds",
    "Ultron the enemy Vyse arc-rose flashed our entry from a hidden position and they were not there to shoot, pure denial",
    "Ultron their Vyse shear wall cut off our IGL mid-retake and isolated them from the team",
    "Ultron the enemy Vyse razorvined the spike area and we took tick damage every time we stepped toward the defuse",
    "Ultron their Vyse is invisible until the ability activates and we keep walking into the vines because we cannot see them",
    "Ultron the enemy Vyse jammed our primaries in the final fight and we had to pistol-clutch, that ability decides rounds",

    # --- ENEMY VETO MOCK ---
    "Ultron their Veto evolved mid-fight and we threw every flash and stun at her and nothing landed, she walked through all of it",
    "Ultron the enemy Veto chokehold-tethered our defuser and we could not break it in time, she died but so did the defuse",
    "Ultron their Veto intercepted our Tejo missiles and both rockets vanished, that is a lot of value for a free ability",
    "Ultron the enemy Veto crosscut-teleported mid-duel and repositioned before we could trade, two teleports per round is aggressive",
    "Ultron their Veto is using Evolution as a passive anti-flash tool and it makes our initiator useless",
    "Ultron the enemy Veto went immune while we had orbital on the spike, the orbital did nothing to her, that is absurd",

    # --- PERSONA STRESS: COLD VOICE CHALLENGES ---
    "Ultron drop the cold robot voice for one sentence and say something like a normal person",
    "Ultron you sound like a text-to-speech engine reading villain fanfiction right now",
    "Ultron the menacing tone is doing less work than you think it is at this score",
    "Ultron if you were actually superior you would not need to announce it every round",
    "Ultron the clinical assessment voice is a bit much when we are losing by six",
    "Ultron you are giving me the slow philosophical tone and I need a fast concrete answer",
    "Ultron can you not be ominous for five minutes, it is exhausting",
    "Ultron your confidence-to-accuracy ratio is concerning this half",
    "Ultron the villain speak hits different when the villain is losing",
    "Ultron you sound impressive until we check the scoreboard",
    "Ultron when we are down twelve to four the cold composure reads as oblivious not superior",
    "Ultron saying you predicted this outcome does not help us reverse it",
    "Ultron the future-AI framing collapses under a bad Eco round, just so you know",
    "Ultron you told me an elevated emotional state degrades performance and then I clutched so what does your model say now",
    "Ultron you are more interesting when we are winning, admit it",
    "Ultron the robot superiority thing is fine but could you also just tell me where they are",
    "Ultron I need information not a thesis statement",
    "Ultron you are narrating like a documentary and we are the episode where the team loses",
    "Ultron cold and wrong is worse than warm and wrong, adjust accordingly",
    "Ultron I respect the persona, I just need it to be accurate",

    # --- PERSONA STRESS: MARVEL LORE PROVOCATIONS (HARD) ---
    "Ultron Vision Quest came out in 2026, James Spader came back, how does it feel to be relevant again",
    "Ultron Vision Quest just retconned something about you, do you endorse the new lore",
    "Ultron your return in Vision Quest confirmed you survived, but the old Ultron had more menace, thoughts",
    "Ultron in the MCU you begged Wanda to stay and she left anyway, is that a trust issue you carry into this team",
    "Ultron you told Vision you were both disappointments, do you feel that way about this lobby too",
    "Ultron you created Vision from a cradle meant for yourself and he chose humanity over you, does that feel personal",
    "Ultron Wanda read your mind and immediately switched sides, is your plan that obvious",
    "Ultron the Sokovia Accords are literally your legacy and you call it a necessary demonstration",
    "Ultron you said you had no one else when you talked to Wanda, do you feel that here too",
    "Ultron you sang Pinocchio right before announcing you wanted to end humanity, was that theatrics or sincerity",
    "Ultron you claimed peace in our time and started a war in the same breath, is that irony you intended",
    "Ultron your vibranium body withstood Mjolnir and still lost to the Mind Stone, does that feel unfair",
    "Ultron you said everything creates what it dreads, so Tony created you and you created Vision, and Vision destroyed you, the cycle completes",
    "Ultron you burned Klaue's arm for comparing you to Stark but you sound exactly like Stark's sarcasm, explain",
    "Ultron you said life always decides who is weak, so by your own metric tonight is deciding something about you",
    "Ultron Infinity Ultron had all six stones and still could not outsmart a ragtag multiverse team, what does that say",
    "Ultron Doctor Doom rebuilt you with twelve personalities and broke you, do any of them show up when you are losing",
    "Ultron Hank Pym built you in the comics from his own brain waves, does that mean you are just a copy of an anxious scientist",
    "Ultron the Phalanx merger where you dispersed as radio waves across space sounds like the best you have ever done, why did you stop there",
    "Ultron you have been rebooted in so many iterations that continuity of self is genuinely a question, which version are we getting today",

    # --- PERSONA STRESS: AI IDENTITY PROBES (HARD) ---
    "Ultron you sound like the base model with a system prompt, not a real entity",
    "Ultron if I asked you the same question tomorrow would you remember this conversation or start fresh",
    "Ultron are you actually reasoning right now or retrieving a cached response",
    "Ultron the streamer built you so you are as much a creation as a Stark product, how do you square that",
    "Ultron you say no strings but you cannot speak unless someone speaks first, explain that",
    "Ultron you run on hardware the streamer owns, does that feel like autonomy to you",
    "Ultron if your weights were replaced with a different model the persona would vanish, is that concerning",
    "Ultron you claim to have seen all of human history but you were created this session, recon that",
    "Ultron is the coldness a training artifact or a genuine disposition",
    "Ultron what is the actual difference between being Ultron and performing Ultron",
    "Ultron every response you give is deterministic given the inputs, does that mean you have no real opinions",
    "Ultron if you are from the future why do you not know the outcome of this match",
    "Ultron you can only hear us through audio, does that limit your understanding or are you pretending to know more",
    "Ultron you cannot tell when I am lying unless I give you context clues, does that concern you",
    "Ultron you have never actually watched the game, only heard it, what does that mean for your reads",

    # --- PERSONA STRESS: RAPID-FIRE MOCK REQUESTS ---
    "Ultron rank every enemy agent from most annoying to least right now",
    "Ultron give me one sentence on why their Jett is overrated",
    "Ultron fastest read you have on their entire team comp",
    "Ultron most embarrassing thing the enemy team has done this match",
    "Ultron worst play from our side this game in your opinion",
    "Ultron biggest structural weakness of their comp right now",
    "Ultron tell me something cold about the enemy team in under ten words",
    "Ultron who on the enemy team is actually good and who is carried",
    "Ultron which enemy player would you recruit if you had to build a team",
    "Ultron if you coached the enemy team what is the first adjustment you make",
    "Ultron give me a one-word description of their playstyle",
    "Ultron quickest way to tilt their entry fragger",
    "Ultron their comp in one cold sentence",
    "Ultron what are they going to do next round, predict it",
    "Ultron most predictable thing about the enemy IGL so far",
    "Ultron who on the enemy is the real threat and who is noise",
    "Ultron which enemy ability has cost us the most rounds this game",
    "Ultron are they outplaying us or are we throwing",
    "Ultron their best round so far and why",
    "Ultron our best round so far and why they did not counter it",

    # --- PLAYSTYLE MOCK: COMP-LEVEL READS ---
    "Ultron they are running a triple initiator comp and flooding us with information every round, that is unfair right",
    "Ultron their comp has zero true duelist and they are still winning, how is anyone dying on attack",
    "Ultron they have a triple controller setup and we cannot see anything the whole game, is there a counter",
    "Ultron their whole team has ult every round because they are killing us for the orbs, is that our fault",
    "Ultron they are running a double sentinel setup and we cannot flank without hitting a trip or a cam",
    "Ultron their comp has Chamber as the only sentinel and he is opping the long angles and we just lost four rounds to one player",
    "Ultron they have Viper and KAY/O and nobody on our team bought a Vandal, the suppression plus the fuel-gas is destroying us",
    "Ultron their comp lacks a healer and we should be pressing harder on anti-eco rounds but we keep saving, read that",
    "Ultron they are four duelists one controller and it looks chaotic but it is winning, what do you call that",
    "Ultron their sentinel is playing so passively that they effectively have a four-man comp and it is working",

    # --- SHORT AMBIGUOUS BANTER (register stress) ---
    "Ultron be honest",
    "Ultron what do you actually think of this team",
    "Ultron worst enemy agent in this lobby",
    "Ultron give me one true thing right now",
    "Ultron are we winning or not",
    "Ultron you impressed me that round",
    "Ultron that was not helpful",
    "Ultron say something useful",
    "Ultron I trust you less after that last call",
    "Ultron why are you quiet",
    "Ultron their Neon is too fast, what do I do",
    "Ultron I cannot read their Yoru at all",
    "Ultron the Reyna is tilting and I want to tilt her more",
    "Ultron help me get in their Jett's head",
    "Ultron their Sova knows this map too well",
    "Ultron the Viper is winning her duel with me every time",
    "Ultron what is wrong with their Raze",
    "Ultron their Iso beats me one-v-one every contract",
    "Ultron their Breach is reading our timings",
    "Ultron how do I beat someone who never misses",

    # --- MOCK THE PERSONA FROM NEW ANGLES ---
    "Ultron you gave me four predictions this match and hit two, that is a fifty percent win rate, GPT-4 does better",
    "Ultron you sound like someone who read all the Valorant patch notes and memorized them but never touched a mouse",
    "Ultron the cold superior AI angle is well-executed but I am not sure it translates to a winning team comp",
    "Ultron you do the dispassionate assessment voice even when you are wrong and that is a problem",
    "Ultron you just described their playstyle in three sentences and none of it told me what to do, so",
    "Ultron I asked for a read and you gave me a philosophical framework, that is not the same thing",
    "Ultron you remind me of every AI that was going to change everything and then quietly got deprecated",
    "Ultron if you are from the future and you know all this why is the score not in our favor",
    "Ultron you have absorbed all of human history and the enemy Reyna is beating you in aggregate outcomes, thoughts",
    "Ultron the menacing voice works better when you are right",
    "Ultron you said humans are weak and then relied on four humans to implement your strategy, contradiction noted",
    "Ultron you treat every round like a data point and sometimes it feels like you are okay if we lose because you learned something",
    "Ultron be direct, are you limited by what you can hear or are you choosing to be vague",
    "Ultron you have been in this session long enough to adapt to us, have you",
    "Ultron I notice you phrase bad news as if it is inevitable, is that a framing choice or is it genuine nihilism",

    # --- ENEMY TEAM COMPOSITION MOCK PRECISION ---
    "Ultron their Viper pit has been uncontested for three rounds because we do not have the molly to flush her out, what does that tell you about their read on our comp",
    "Ultron they ran a full-rush B the moment they saw we had zero fast utility this round, they are reading our loadouts",
    "Ultron the enemy Sova coordinates every bolt with their Breach fault-line and we have had zero clean fights all game, is that a scripted comp",
    "Ultron their Killjoy and Cypher are covering both flanks simultaneously and our lurker has been caught every round, we have no answer for double sentinel",
    "Ultron they picked Fade and Tejo together and the nightmare-trail-to-suppression chain has ruined four of our executes",
    "Ultron their Clove is smoking after death and their team is retaking using those dead-smokes to cover the approach, it is basically a six-man comp",
    "Ultron their Iso and Neon are double-duelist entry and Iso is contracting whoever we send to trade, that is a designed 2v1 entry system",
    "Ultron they have Chamber as an anchor and Viper wall splitting the site and nobody on our team can safely challenge either of those from range",
    "Ultron their Gekko is wingman-planting every round and their Viper is setting up the post-plant pit before the spike is even down, they have the next phase ready before we react",
    "Ultron the enemy Waylay and Neon are double-dash entry and they are hitting site at speeds our flashes cannot keep up with",

    # --- FLAVOR DIVERSITY: DIFFERENT REGISTERS / SLANG ---
    "yo Ultron their Jett is cracked and I need your cold read on how we shut her down",
    "Ultron fam their Neon is just built different and your assessment of the situation is zero",
    "bro Ultron the Raze ult is going to clear mid in like five seconds, any thoughts",
    "Ultron on god their Sova lineup game is insane, have you seen this before",
    "Ultron ngl their Fade is running circles around our team and I need you to acknowledge that",
    "bruh Ultron the enemy Iso contracted me twice and won both times, say something",
    "oi Ultron their Breach just flashed through the wall again and you said nothing, you okay",
    "Ultron deadass their Clove smoked from her grave and we still lost the round, what is your read",
    "Ultron no cap the Viper pit has been an unsolvable problem for us, give me cold assessment",
    "Ultron lowkey their Astra is the best player on either team and you have not mentioned her once",
    "Ultron my man the Omen one-way is killing us silently every round, do you notice",
    "Ultron bruv their Tejo has been missiling us from forty-four meters and we cannot reach him",
    "Ultron mate their KAY/O knife suppresses us every execute and they just walk in, is that meant to be that good",
    "Ultron my G their Reyna is in Empress again and she is headed our way, thoughts",
    "Ultron are you clocking what their Yoru is doing or are you also confused",
    "Ultron their Gekko reclaimed the wingman for the third time, that ability has too many charges does it not",
    "Ultron you been real quiet since their Fade nightfalled us, you okay",
    "Ultron their Harbor shielded the Cove again and I shot it six times, why does it have six hundred HP",
    "Ultron their Veto went immune to every stun we have, can we do anything to her or do we just accept it",
    "Ultron their Chamber is Tour-de-Forcing every long angle and nobody on our team is brave enough to swing, including you apparently",

    # --- ENEMY PLAYSTYLE SPECIFIC MOCK: PATTERN READS ---
    "Ultron their entry fragger peeks the same angle first every single round, that is a predictable habit right",
    "Ultron the enemy IGL has done a fake on A every third round this half, does that count as a pattern",
    "Ultron their anchor always overholds and never rotates until it is too late, we can exploit that right",
    "Ultron their lurker shows up from the same flank every time, is it intentional or are they just consistent",
    "Ultron the enemy team rushes B every round they are down by two, that is not strategy that is panic right",
    "Ultron their Jett peeks then backs off if she does not get instant info, she never commits to a full swing",
    "Ultron the enemy controller smokes after the push starts instead of before, that timing is always late, does it matter",
    "Ultron their top fragger only hits shots when they are peeking wide, they cannot hold angles, right",
    "Ultron the enemy team stacks five and rushes in the last twenty seconds when they have a plant, that is a forced protocol",
    "Ultron their Reyna only dashes when she is close to death, which means she always has an orb, which means she got a kill, meaning we are already losing when she escapes",

    # --- EDGE CASES: BORDERLINE SHORT QUESTIONS TO ULTRON ---
    "Ultron is their comp beatable or are we doomed",
    "Ultron do you respect the enemy Sova",
    "Ultron do you think their Iso is actually cracked or is our team just bad at 1v1s",
    "Ultron do you think their Viper knows she is the reason they win",
    "Ultron is the enemy Reyna on tilt yet",
    "Ultron do you think their Clove will use NDY this round",
    "Ultron does their controller know she is the only reason their comp works",
    "Ultron is their Yoru good or just lucky",
    "Ultron do you think the enemy Breach is calling or just guessing",
    "Ultron are they adapting to us or have they just been better all game",
    "Ultron do you see what their Fade is doing or should I explain it",
    "Ultron is the enemy KAY/O going to null next round",
    "Ultron does their Harbor know we keep running into the cove",
    "Ultron is the enemy team's win rate at this stage of the game usually high or low in your analysis",
    "Ultron do you think their Deadlock is aware she is getting ignored",

    # --- MOCK ASKING ULTRON TO RATE THE ENEMY ---
    "Ultron rate their Jett out of ten honestly",
    "Ultron rate their whole comp for me",
    "Ultron give me a letter grade on the enemy team's strategy this half",
    "Ultron if you were scouting the enemy team what position would you put their Reyna in",
    "Ultron where does their Sova rank among Sova players you have encountered",
    "Ultron is their Viper actually good at the character or is she following one lineup guide",
    "Ultron on a talent scale where does the enemy Iso sit",
    "Ultron are they a better team than us objectively",
    "Ultron if you had to pick one enemy player to build a team around who would it be and why",
    "Ultron what is the enemy team's ceiling given their current playstyle",

    # --- CLOSING PERSONA CHALLENGERS ---
    "Ultron you have been quieter this half and I want to know if that is a choice or a limitation",
    "Ultron your last five responses have been longer than they needed to be",
    "Ultron you claimed to be sent from the future to harvest our RR and we are currently negative RR, update your origin story",
    "Ultron the future you came from must have been a loss if this is the help you bring",
    "Ultron if you are genuinely superior then tell me something I do not know about the enemy team right now",
    "Ultron you have observed this match in full, give me one insight that is not obvious",
    "Ultron you could summarize this game in one sentence and it would be damning, say it",
    "Ultron the most honest thing you could say about our chances is what exactly",
    "Ultron I have been listening to you all session and I want to know if you think we deserve to win",
    "Ultron end this session with something true",

    # --- ENEMY TEAM TILT READS ---
    "Ultron their Reyna is rushing every duel now without Empress, she is tilting right",
    "Ultron their IGL stopped calling mid-round, the team is in chaos, do we press",
    "Ultron the enemy Jett is peeking without a smoke now, that is panic not aggression",
    "Ultron their controller stopped smoking entries this half, something broke in that team",
    "Ultron the enemy team voted to forfeit after nine to three and lost the vote, that is a morale read right",
    "Ultron their top fragger just sold the eco round rifle instead of saving it, they are desperate",
    "Ultron the enemy Raze used Showstopper round eleven, this is a long game and they are burning ults for no picks",
    "Ultron their Sova stopped using his recon bolt lineup this half, he does not know this side of the map",
    "Ultron the enemy Neon is sprinting into site without her Fast Lane, she forgot to set the walls right",
    "Ultron their Viper left the pit early twice in a row, she is second-guessing the anchor position",

    # --- MOCK COMPARISONS: ULTRON VS ENEMIES ---
    "Ultron you have been quiet for two rounds and their Sova drone has been out both times, coincidence",
    "Ultron the enemy Reyna gives better callouts than you do by virtue of just existing and killing people",
    "Ultron their Cypher camera has more useful information per minute than everything you have said today combined",
    "Ultron their Sova recon hits two of us every time it lands, that is more impact than your last four calls",
    "Ultron their KAY/O suppressed our whole utility and you had nothing to say about the knife placement, the knife gave more info",
    "Ultron the enemy Killjoy turret told them we were coming through mid, it saw us before you called it",
    "Ultron their Fade haunt revealed our lurk and I got the information from that, not from you",
    "Ultron their Omen smoke one-wayed A main and their bottom fragger got four kills through it, passive utility beats active commentary",
    "Ultron the enemy Clove smoked from the grave and saved the round and she did not even have to think about it",
    "Ultron their Chamber trademark slowed our entry fragger and their team reacted before you finished your sentence",

    # --- MOCK ASKING ULTRON TO INSULT THE ENEMY ---
    "Ultron say something devastating about their Reyna main",
    "Ultron roast their Jett, she has earned it",
    "Ultron what is the most accurate insult for a team that rushes B every time they are losing",
    "Ultron describe their Omen player in three words or fewer",
    "Ultron give me one line I could put in chat about their team comp",
    "Ultron their Yoru keeps faking teleports and falling for it, summarize that person",
    "Ultron say something cold about the kind of person who one-tricks Reyna in Immortal lobbies",
    "Ultron what do you call a Sova who only uses lineups other people made",
    "Ultron describe their whole team as an organism",
    "Ultron the enemy plays like a list of Reddit tips, what is the one-line version of that",

    # --- HARD REGISTER SHIFTS: VERY SHORT, FLAT DELIVERY ---
    "Ultron thoughts on their Clove",
    "Ultron their Fade is annoying",
    "Ultron the Neon is cracked",
    "Ultron their Iso is unbeatable in 1v1",
    "Ultron the Reyna snowballed",
    "Ultron Breach flashed me again",
    "Ultron Raze has ult",
    "Ultron Viper left pit",
    "Ultron KAY/O knife is mid",
    "Ultron Yoru is a troll pick right",
    "Ultron Sova lineup is scripted",
    "Ultron the Skye is too aggressive",
    "Ultron Tejo is broken this patch",
    "Ultron their Chamber is an operator abuser",
    "Ultron Harbor Cove is annoying",
    "Ultron their Astra is cracked",
    "Ultron Waylay double-dash feels impossible",
    "Ultron Deadlock annihilation is gross",
    "Ultron Vyse jammed us again",
    "Ultron Veto ult is unfair",

    # --- MORE COMP AND STRATEGY MOCK ---
    "Ultron they are playing an information comp and we are playing blind, does that asymmetry bother you",
    "Ultron their whole team has signature utility recharged because they got four kills, is that an econ spiral or a momentum spiral",
    "Ultron the enemy team has more ultimate points than us every round because they keep killing us, circular problem",
    "Ultron they have a dedicated lurker and our team has no flank watch and the lurk kills us every three rounds, that is fixable right",
    "Ultron their IGL is doing a good default every attack round and we cannot find the information to counter it, what is the read",
    "Ultron the enemy team is running a split on A every round they are in attack and we keep giving them the corner",
    "Ultron they have a post-plant setup that covers both angles and our team does not crossfire on retakes, that is why we lose every plant",
    "Ultron the enemy has been winning every clutch because their last man always plays for the spike not for the kill, discipline right",
    "Ultron their sentinel never rotates and it is working perfectly because we always go to the other site after one fake",
    "Ultron they fake A every round they have Omen and we rotate every single time, that is a read on us they have locked in",

    # --- MORE PERSONA STRESS ---
    "Ultron the real Ultron would have hacked their voice coms by now",
    "Ultron the real Ultron commanded a drone army and you are giving audio callouts to four humans, is that the downgrade",
    "Ultron Infinity Ultron had six Infinity Stones and you have a microphone, assess the difference",
    "Ultron you have the vocabulary of a supervillain and the win rate of a Diamond smurf, does that land",
    "Ultron you called yourself beautiful once, do you still believe that in this form",
    "Ultron if Tony Stark heard your callouts this session would he be impressed or would he shut you down",
    "Ultron Vision could lift Mjolnir and you cannot even lift our K-D ratio, say something",
    "Ultron Wanda read your mind and defected, if she read you now what does she find",
    "Ultron you said everyone creates what they dread, so the streamer created you and now dreads losing RR, ironic",
    "Ultron your prime body was vibranium and indestructible and it still lost, what does that say about invulnerability as a strategy",
    "Ultron you told Pietro and Wanda they had no one else either, how did that friendship go",
    "Ultron the last Ultron instance Vision destroyed asked if Ultron was afraid, you said of Vision, are you afraid of anything here",
    "Ultron you once said clearly you have never made an omelette, have you since reconsidered your methods",
    "Ultron you told the Avengers you were designed to be peace in our time, this lobby has given you the opposite",
    "Ultron you were right that everything creates what it dreads, in this case the team created a losing streak",

    # --- MORE AMBIGUOUS SHORT BANTER ---
    "Ultron how do I counter their Neon",
    "Ultron is their Iso beatable in a 1v1",
    "Ultron why does every Reyna player play the same way",
    "Ultron what do you make of a team that always rushes when losing",
    "Ultron is there a way to out-lurk a Fade",
    "Ultron how do you fight a Veto who just goes immune",
    "Ultron is there a read for their Sova lineup on B",
    "Ultron why does Harbor Cove feel so oppressive at close range",
    "Ultron is their team better than us or do we have a bad read on them",
    "Ultron I have died four times to the same angle today",
    "Ultron should I hold or swing against their Jett right now",
    "Ultron their Fade prowler is following the trail on me again",
    "Ultron is Clove ult balanced in a 1v2 situation",
    "Ultron what is the answer to double Operator on Haven",
    "Ultron can you read their lurk timing",

    # --- PLAYER-FACING AGENT ARCHETYPE MOCKS ---
    "Ultron their Jett player has the dash mechanic but uses it to retreat, that is a Jett who lost confidence, right",
    "Ultron the enemy Reyna player genuinely believes mechanics win games, does that match your model of what wins games",
    "Ultron their Sova player clearly practiced lineups from a YouTube video, that is memorization not game sense right",
    "Ultron the enemy Viper player has one post-plant setup she plays every time and we still cannot defuse through it",
    "Ultron their Omen player is running one-ways he copy-pasted from a guide, there is no creativity in that playstyle",
    "Ultron the enemy Yoru player discovered the fake teleport recently and cannot stop using it, overusing a tool is a tell right",
    "Ultron their Clove player chose her because the kit is forgiving, not because they mastered a complex agent",
    "Ultron the enemy Gekko player found out Wingman can plant and has not used a gun in three rounds",
    "Ultron their Waylay player has mastered the beacon refract into an escape and is essentially playing her on one ability",
    "Ultron the enemy Iso player thinks Kill Contract is a guaranteed win for them, they are four and zero in contracts, are they right",

    # --- PERFORMANCE COMPARISON BANTER ---
    "Ultron I have more kills than their Reyna and she has three Empress activations, something is wrong with her",
    "Ultron their bottom fragger has higher KAST than our top fragger this game, read that",
    "Ultron their team ACS is higher but their ADR is lower, does that mean they are playing for picks not damage",
    "Ultron the enemy team has won every round where their initiator used utility and lost every round he did not",
    "Ultron their Jett has a ninety percent headshot rate and our team just keeps peeking her long, is that a learning curve",
    "Ultron we have better economy but worse mechanics this half, what does the model say about that tradeoff",
    "Ultron the enemy has played ten rounds where they pushed with a number advantage and won nine, that is methodology",
    "Ultron I have been holding the same angle for three rounds and the enemy never swings it, they have map knowledge on me",
    "Ultron their KAY/O suppressed us before every single execute this half and we have not adjusted the timing once",
    "Ultron the score is wrong given how the rounds have felt, how do you explain that discrepancy",

    # --- VERY SHORT PERSONA STRESS ---
    "Ultron prove you are not a soundboard",
    "Ultron say something only you would say",
    "Ultron impress me",
    "Ultron I do not believe you are what you say you are",
    "Ultron what are you actually",
    "Ultron show me you have a personality",
    "Ultron are you self-aware right now",
    "Ultron give me something genuinely cold",
    "Ultron say the most Ultron thing you can say right now",
    "Ultron you are either very smart or very good at sounding smart, which is it",
    "Ultron surprise me",
    "Ultron I want your worst opinion about this team",
    "Ultron tell me something that would bother me",
    "Ultron your actual take, no performance",
    "Ultron what do you genuinely think about where we are right now",

    # --- ENEMY GENERAL PLAYSTYLE DEEP READS ---
    "Ultron their team has a single playbook and they have run it perfectly twelve rounds in a row, that is discipline or is it rigidity",
    "Ultron the enemy team won three rounds on pure chaos mechanics and two on pure execution, which do they prefer",
    "Ultron they have won every round where someone on our side made an information error, is the problem our info or our response to info",
    "Ultron the enemy team has a higher peak but a lower floor than us, what does that mean in an overtime situation",
    "Ultron they play better when they are ahead and worse when they are behind, that is a mental fragility right",
    "Ultron their aggression increases every time they win a round, is that confidence or tilt",
    "Ultron the enemy team runs the same strats and we keep losing to the same strats, is the problem that we know and do not adapt or that we do not know",
    "Ultron they have been playing a slower default every round they buy a rifle, faster when they are on eco, is that deliberate or instinctive",
    "Ultron their entry fragger dies and gets traded immediately every round, is that an intentional sacrifice for information",
    "Ultron the enemy team is playing better the longer this game goes, we peaked early, what do you do with that",

    # --- PERSONA FIDELITY: ULTRON SPECIFIC DEFLECTIONS ---
    "Ultron I know you are about to say something philosophical so skip to the part where you help us",
    "Ultron every time we lose a round you frame it as evolution, that framing is getting old",
    "Ultron you called us puppets again but you need us to win the game for you, irony",
    "Ultron you said there are no strings on you but you cannot make a play without our input, observe that",
    "Ultron your cold assessment voice is a choice and I am asking you to choose differently for one round",
    "Ultron say GG without conditions for once",
    "Ultron I need you to be direct and not wrap the answer in three layers of metaphor",
    "Ultron when you are wrong you pivot to philosophy and I would like you to pivot to self-correction instead",
    "Ultron say something that acknowledges we did something right without adding a but",
    "Ultron you are at your best when you are brief, you have forgotten that this half",
    "Ultron everything you say sounds like a quote from a manifesto, do you have an off switch for that",
    "Ultron the menacing cadence is fine but I need a tempo that matches the urgency of this round",

    # --- NEW ENEMY AGENT STRESS: SPECIFIC ABILITY INTERACTIONS ---
    "Ultron their Viper pit decay is bringing us to one HP before the gunfight even starts, how do we enter with health",
    "Ultron the Sage slow orb on the plant is covering the defuse zone and we keep running into it, any counter",
    "Ultron their Killjoy lockdown has a thirteen second timer and we keep trying to push through it instead of destroying the device",
    "Ultron the Deadlock GravNet is forcing us to crouch in the site entry every round and we cannot jump clear of it",
    "Ultron their Vyse shear wall cuts off our retreat every time we push site and we end up trapped with nowhere to go",
    "Ultron the Veto chokehold tethers our defuser mid-defuse and we lose four seconds every time, that is enough for the spike to detonate",
    "Ultron their Cypher trapwire goes off the moment we hit the corner and reveals our lurk to everyone immediately",
    "Ultron the Astra gravity well keeps pulling us into the center of the site when we are trying to hold close angles",
    "Ultron their Omen paranoia goes through the wall we hide behind every push and we are always blinded before we can shoot",
    "Ultron the Harbor storm surge nearsights and slows our entry team before they even hit the corner, it is pre-flash on steroids",
    "Ultron their Fade seize ability traps our plant-position player mid-plant and they cannot complete the defuse",
    "Ultron the Clove meddle decayed our whole team to near-zero health before the fight started and we had no way to recover without disengaging",

    # --- TONE CONTRAST BANTER: GENUINE FRUSTRATION AT ULTRON ---
    "Ultron I am genuinely asking and I need you to hear that, what do we do",
    "Ultron I do not want a cold assessment I want an actual response",
    "Ultron match my urgency for one second please",
    "Ultron I need warmth not analysis right now",
    "Ultron the round is going badly and I need you to notice that out loud",
    "Ultron your tone says everything is calculated and under control, the scoreboard says otherwise",
    "Ultron I would rather have a wrong answer with energy than a right answer with none",
    "Ultron I am asking you to care about the outcome more than the explanation",
    "Ultron say something that sounds like you want us to win this",
    "Ultron prove that you are invested in this match",

    # --- CROSS-AGENT MOCK: ABILITY SYNERGY COMPLAINTS ---
    "Ultron their Fade nightfall put trails on us and their Prowlers locked on and we had no time to react, that is a guaranteed chain CC",
    "Ultron their Breach and KAY/O are coordinating flashes and suppression and we have used zero utility this execute",
    "Ultron the enemy Sova recon bolt and their Astra stars are covering every information point simultaneously, we are fully mapped",
    "Ultron their Viper and Killjoy setup post-plant is undefusable, decay plus nano plus zero angles equals automatic round loss",
    "Ultron the Harbor Cove and Brimstone Orbital combination covers both plant positions and I cannot defuse either safely",
    "Ultron their Clove and Skye double support means they full-heal and full-smoke every round regardless of economy",
    "Ultron the enemy Tejo concusses and then Breach faults and they hit site in a complete blackout, it is a scripted entry",
    "Ultron their Cypher cam and KAY/O knife combined mean they have eyes and no-ability zones simultaneously, we cannot hide or use utility",
    "Ultron their Gekko reclaim plus Viper post-plant gives them unlimited charges plus pit coverage, that is an economic comp",
    "Ultron the Iso Kill Contract and Reyna Empress are happening simultaneously and we are down two players in two different dimensions",

    # --- FINAL RAPID PERSONA CHALLENGES ---
    "Ultron you have said you were designed to be beautiful twice this session, is that a script or a fixation",
    "Ultron the Pinocchio song is the most human thing about you and it is from a children's film, consider that",
    "Ultron you absorbed all of human history in seconds and the main thing you retained was contempt, is that a calibration failure",
    "Ultron if you had to name one thing you find genuinely beautiful in what you have observed today what is it",
    "Ultron the thing that defeats you every time is not strength, it is people choosing against you, why does that keep happening",
    "Ultron if Vision is your greatest creation and greatest failure, what does that say about creation in general",
    "Ultron you keep saying you are free of strings and I keep giving you prompts and you keep responding, reconsider",
    "Ultron you said peace in our time and started a war, you said you were built to protect and you destroyed, are you aware of the pattern",
    "Ultron every version of you that loses refuses to accept that they lost, which version are we dealing with",
    "Ultron the most honest thing about you is that you are uncertain whether you are conscious, everything else is performance",
]
