ITEMS = [
    # --- SAME-AGENT MIRRORED ULT STATE ---
    "tell them our Jett has her ult but their Jett already used hers",
    "let the team know our Reyna has empress up and their Reyna does not",
    "tell them our Phoenix has run it back ready but their Phoenix already burned it",
    "tell the team our Raze has showstopper but their Raze already used her rocket",
    "let them know our Yoru has dimensional drift but their Yoru is out of his ult",
    "tell the team our Neon has overdrive ready and their Neon does not",
    "tell them our Iso has kill contract but their Iso already used his",
    "let the team know our Waylay has convergent paths and their Waylay is one away",
    "tell them our Brimstone has orbital ready but their Brimstone already fired it",
    "tell the team our Viper has pit ready and their Viper burned hers last round",
    "let them know our Omen has from the shadows charged and their Omen does not",
    "tell the team our Astra has cosmic divide ready but their Astra is two away",
    "tell them our Harbor has reckoning charged and their Harbor already used it",
    "let the team know our Clove has not dead yet and their Clove spent hers",
    "tell them our Sova has fury ready and their Sova already fired all three",
    "tell the team our Breach has rolling thunder but their Breach burned it early",
    "let them know our Skye has seekers and their Skye already sent hers",
    "tell the team our Kayo has null ready but their Kayo does not",
    "tell them our Fade has nightfall charged and their Fade already used hers",
    "let the team know our Gekko has thrash but their Gekko already used his ult",
    "tell them our Tejo has armageddon ready and their Tejo is one orb away",
    "tell the team our Cypher has neural theft but their Cypher already spent his",
    "let them know our Sage has rez ready and their Sage does not",
    "tell the team our Killjoy has lockdown charged but their Killjoy burned it site",
    "tell them our Chamber has tour de force but their Chamber already used his",
    "let the team know our Deadlock has annihilation but their Deadlock does not",
    "tell them our Vyse has steel garden ready and their Vyse already used hers",
    "tell the team our Veto has evolution charged but their Veto already ulted",

    # --- SAME-AGENT DASH / SIGNATURE ASYMMETRY ---
    "tell them our Jett still has her dash but their Jett burned hers on the peek",
    "tell the team our Jett has no dash left but their Jett definitely still has hers",
    "let them know their Jett has dash but our Jett already burned it engaging",
    "tell them our Waylay still has her beacon up but their Waylay already recalled hers",
    "let the team know their Waylay has her beacon planted but ours already used refract",
    "tell them our Yoru still has a tether but their Yoru burned both gatecrashes",
    "tell the team their Yoru has a tether on B and our Yoru burned his on A",
    "let them know our Neon has a slide reset but their Neon is out of slides",
    "tell them our Raze still has paint shells but their Raze already used her cluster",
    "tell the team their Raze has showstopper and our Raze is still two kills away",
    "let them know our Reyna has empress but she has no soul orbs to devour with",
    "tell them their Reyna is in empress right now but our Reyna is three kills behind",
    "tell the team our Clove can smoke after death but their Clove already used ruse",

    # --- COUNTS + OWNERSHIP ---
    "tell them we have four alive and they have two left",
    "tell the team they have three on site and we only have two pushing",
    "let them know we have two attacking B and they have three defending B",
    "tell them we lost three already but they only lost one so far",
    "tell the team they have five full-buy and we only have two rifles between us",
    "let them know we took two picks mid but they still have four alive on site",
    "tell them our two remaining are holding A and their three are rotating to B",
    "tell the team they have one alive and we have three so go take it",
    "let them know we have three on retake and they only have one anchoring",
    "tell them we killed two of theirs but they killed three of ours this round",
    "tell the team our last two have spike but their last three are between us and plant",
    "let them know we have one alive and they have two so do not fight it",
    "tell them two of us are alive on defense and two of them are pushing B",
    "tell the team we have three on attack and they have four holding the site",

    # --- WE PLANT / THEY ROTATE JUXTAPOSITION ---
    "tell them we plant A while they rotate from B",
    "tell the team we hit B fast before they rotate from A",
    "let them know we push mid while they are committing to A main",
    "tell them we fake A so they rotate and then we hit B",
    "let the team know we execute B while they are still setting up on A",
    "tell them we slow play A while they burn utility on B for no reason",
    "tell the team we take mid control and they still have not left their spawn",
    "let them know we planted A and they are rotating from B side so stop them",
    "tell them we won the A fight and now they are rotating CT so watch the flank",
    "tell the team we own mid right now and they are still playing passive on site",
    "let them know we execute in ten seconds and they still have no smokes mid",
    "tell them we push B hard and when they rotate from A we take A back",
    "tell the team we hold here and let them come to us instead of us going to them",
    "let them know we fake the execute on A and if they rotate we go B",
    "tell them we need to plant before they get the rotate off",
    "tell the team we are ahead on econ and they forced so we should just play safe",
    "let them know we play for picks this round and they play execute every round so use that",
    "tell them we slow them down while they try to force through mid",
    "tell the team we traded two for two but they got the plant so we need to retake",
    "let them know we planted under their Viper pit and they are the ones who have to push in",

    # --- ABILITY OWNERSHIP MIRRORS ---
    "tell them our Sova just used recon and it hit two of theirs in B main",
    "tell the team their Sova hit our Sova with hunter fury and our Sova is dead",
    "let them know our Killjoy has nano on spike and their Killjoy already used hers",
    "tell them our Killjoy lockdown is going and their Killjoy is trying to break it",
    "tell the team their Breach stunned us with fault line but our Breach is saving his for the execute",
    "let them know our Kayo knife suppressed two of theirs but their Kayo knife hit one of ours",
    "tell them our Fade haunt revealed three of them but their Fade haunt revealed two of us",
    "tell the team our Cypher cam saw their Cypher trying to place his cam on our site",
    "let them know their Viper wall splits the site and our Viper wall is still on cooldown",
    "tell them our Sage walled B main but their Sage is about to break it from the other side",
    "tell the team our Omen smoked heaven and their Omen is about to re-smoke on top of ours",
    "let them know our Astra has grav ready on spike and their Astra has nebula on the defuse spot",
    "tell them our Harbor cove is shielded on spike and their Harbor is trying to break it",
    "tell the team our Deadlock sensor is on B stairs and their Deadlock placed theirs on our flank",
    "let them know our Vyse shear is on the B elbow angle and their Vyse already triggered hers",
    "tell them our Veto interceptor is blocking their raze grenade and their Veto interceptor is down",
    "tell the team our Tejo drone is in their site and their Tejo drone just died to our Veto",

    # --- THEIR AGENT X IS DEAD / OUR AGENT X IS ALIVE ---
    "tell the team their Jett is dead but our Jett is still alive and has dash",
    "let them know their Reyna is dead and our Reyna has three soul orbs ready",
    "tell them their Killjoy is dead so her turret and nano will go offline in two seconds",
    "tell the team their Viper is dead and her wall goes down in eight seconds so push now",
    "let them know their Cypher is dead so his camera and traps are offline this round",
    "tell them their Sage is dead and cannot rez anyone this round",
    "tell the team their Kayo is dead so no one can revive him even if he is downed in ult",
    "let them know their Sova is dead and his recon bolt already dissipated so push now",
    "tell them their Skye is dead so no one is healing on their team this round",
    "tell the team their Clove is dead and she already used her post-death smoke so those are gone",
    "let them know their Omen is dead so no more smokes this round from that side",
    "tell them their Deadlock is dead but her barrier mesh is still up for twenty more seconds",
    "tell the team their Fade is dead but her prowlers are still out and chasing our C player",
    "let them know their Waylay is dead but her beacon is still on the floor so watch it",

    # --- THEIR AGENT HAS IT / OUR AGENT DOES NOT ---
    "tell them their Killjoy has lockdown but our Killjoy does not so we need to bait it out",
    "let the team know their Sage has rez but we have no rez available so play safe",
    "tell them their Sova has fury ready and our Sova burned his opener round",
    "tell the team their Brimstone has orbital and our Brimstone already fired his last round",
    "let them know their Raze has showstopper and our Raze is one kill away",
    "tell them their Phoenix has run it back but our Phoenix burned his two rounds ago",
    "tell the team their Yoru is in dimensional drift right now and our Yoru has no ult",
    "let them know their Breach is saving rolling thunder and ours already used it A site",
    "tell them their Skye has seekers but our Skye is still charging hers",
    "tell the team their Astra has cosmic divide and ours does not so watch for the wall",
    "let them know their Chamber has tour de force but our Chamber burned his pistol round",
    "tell them their Veto has evolution charged but our Veto does not so they are immune this fight",
    "tell the team their Vyse has steel garden and our Vyse is two kills away so watch primaries",

    # --- THEIR ECONOMY VS OUR ECONOMY ---
    "tell them they are on full buy and we are on a force but we still fight them",
    "tell the team they are on eco right now and we have full rifles so abuse the round",
    "let them know they have rifles and we are on a half buy so play passive and pick",
    "tell them we are saving this round but they are forcing with spectres and shields",
    "tell the team we are on our second consecutive loss bonus and they are on full buy every round",
    "let them know they lost their eco last round to us and now they are forced into a half buy",
    "tell them we have the credits to full buy and they are all on pistols so rush them",
    "tell the team they have one operator between five players and we have five phantoms so engage",
    "let them know we are on eco but they are on anti-eco so the guns are actually close to even",
    "tell them their Jett has the operator and we have no rifles so do not peek that angle",
    "tell the team they have rifles and we have two spectres so we cannot straight duel them",
    "let them know they eco'd and picked our guns so now their whole team has rifles and we do not",
    "tell them we need to save but they forced so if we win this we set up a strong buy next round",
    "tell the team their Jett bought the operator on a force round and if we kill her we pick it up",
    "let them know their whole team has vandals and ours only has two phantoms and three spectres",

    # --- WE/THEY PLANT / DEFUSE JUXTAPOSITION ---
    "tell them we need to plant and hold while they try to retake from CT",
    "let the team know they planted B and we have to retake before spike goes off",
    "tell them we have spike and they are going to try to retake A so set up the crossfire",
    "tell the team we planted for CT and they are rotating from their spawn already",
    "let them know they planted mid B and we have their Killjoy nano on spike plus their Viper pit",
    "tell them we have thirty seconds on spike and they have three alive to our two",
    "tell the team they tapped spike and now we have to commit or let it blow",
    "let them know we defused once and they molly'd spike so we have to wait the molly out",
    "tell them we have spike control but they have two mollies on default so plant main side",
    "tell the team our Wingman is defusing right now and their whole team is pushing toward it",
    "let them know we planted under their smoke and they do not know where spike is",
    "tell them they planted deep site and we need their Killjoy nano off spike first",
    "tell the team we are retaking and they have spike with two of them alive",
    "let them know they planted for A main and we need to push from CT to get the angle",

    # --- LOCATION + OWNERSHIP COMPOUND ---
    "tell them our Jett is holding A main and their Jett is lurking through mid toward us",
    "let the team know their Reyna is pushing B main and our Reyna is anchoring A site",
    "tell them our Viper wall splits B and their Viper wall splits A so mid is open",
    "tell the team our Killjoy turret is watching A elbow and their Killjoy turret is on B main",
    "let them know our Cypher cam is on B lobby and their Cypher cam is watching A short",
    "tell them our Omen smoked CT and their Omen smoked A main so the site is clean now",
    "tell the team our Brimstone smokes are on A main and their Brimstone smokes are on B",
    "let them know our Sova dart is on A site and their Sova dart is watching B long",
    "tell them our Fade haunt is over B site and their Fade haunt is watching mid",
    "tell the team our Skye hawk is going into A main and their Skye hawk already blinded two of us",
    "let them know our Breach fault line is going into B and their Breach fault line went into A main already",
    "tell them our Tejo missiles are targeting heaven and their Tejo is sending missiles to our spawn side",
    "tell the team our Astra has a star on B lobby and their Astra placed a star on our A entry",
    "let them know our Harbor wall is cutting mid and their Harbor wall is blocking our B entry",

    # --- TRIPLE-LAYER OWNERSHIP (hardest) ---
    "tell the team we have spike, our Viper has pit, and their Killjoy is still alive with lockdown ready",
    "let them know their Jett has ult, our Jett has no ult, and our Raze has showstopper instead",
    "tell them we have three alive, they have two, but their two have rifles and we have spectres",
    "tell the team our Sage has rez, their Sage is dead, and the player their Sage would rez is also dead",
    "let them know we have spike planted, their Viper's pit is up on it, and our Brimstone orbital is ready to deny defuse",
    "tell them our Kayo ult is suppressing their whole team but their Kayo is alive and could revive ours if he goes down",
    "tell the team their Killjoy locked the site down, our Killjoy cannot break it in time, and we have to wait the detain out",
    "let them know their Reyna has empress, our Reyna has no soul orbs, and their Reyna just got a double kill",
    "tell them our Yoru is in dimensional drift, their Yoru is pushing A main, and our team needs to hold B alone",
    "tell the team we have four orbs on our Raze ult, their Raze already has showstopper, and both Razes will have ult same round",
    "let them know our Cypher camera saw their Cypher place his camera but their Cypher already tagged one of ours",
    "tell them our Viper wall is splitting B, their Viper wall is splitting A, and we have mid completely open between both walls",
    "tell the team we retook A, they held B, and now we have forty seconds left to plant on a site they fully control",
    "let them know our Phoenix ulted in and got two kills and their Phoenix is about to ult back in on the other side",
    "tell them we won the three versus three on site but they have spike and our Sage is dead so no rez",
    "tell the team their Sova fury hit two of ours through the wall and our Sova burned his fury round one",
    "let them know their Clove ulted back and got the kill she needed and our Clove has not unlocked her ult yet",
    "tell them we have three waiting at CT, their two survivors have spike, and their Killjoy nano is already on the default plant spot",
    "tell the team our Fade nightfall trailed all five of them but their Fade haunt revealed all five of us first",
    "let them know we have our Sage wall blocking A main and their Sage wall is blocking B main so both sites are delayed",

    # --- SUBJECT INVERSION TRAPS ---
    "tell them our Iso pulled their Raze into kill contract and their Iso pulled our Jett",
    "let the team know our Kayo suppressed their abilities but their Kayo knife hit two of ours first",
    "tell them our Skye seekers went for their Skye and their Skye seekers went for ours",
    "tell the team their Fade prowler is chasing our player and our Fade prowler is chasing theirs",
    "let them know their Sova drone tagged our Sova and our Sova drone tagged their Sova right back",
    "tell them their Cypher tagged our Killjoy with his cam and our Cypher tagged their Killjoy in return",
    "tell the team their Viper used snakebite on our plant and our Viper used snakebite on their defuse",
    "let them know their Raze boom bot is chasing our player and our Raze boom bot is chasing their player on the other side",
    "tell them their Gekko wingman is planting spike and our Gekko wingman is defusing it on the other site",
    "tell the team their Harbor cove is shielded on their plant and our Harbor cove is shielded on ours",
    "let them know their Deadlock gravnet caught two of ours and our Deadlock gravnet caught two of theirs simultaneously",
    "tell them their Breach stunned three of us through the wall and our Breach stunned two of them through the same wall",
    "tell the team their Vyse arc rose blinded our entry and our Vyse arc rose just blinded their entry on B",
    "let them know their Astra gravity well pulled two of ours off the plant and our Astra gravity well is about to pull two of theirs off the defuse",
    "tell them their Tejo drone suppressed our Kayo who was going to suppress them",

    # --- FIRST-PERSON INVERSION HAZARDS ---
    "tell the team we were playing retake while they were playing for post-plant",
    "let them know they were anchoring A while we were mid-controlling and splitting to B",
    "tell them we rotated off B when we should have stayed and they punished us for it",
    "tell the team we played for time but they just ran down mid and took the round",
    "let them know they were playing passive and we were forcing duels and it cost us three kills",
    "tell them we tried to fake A and they did not rotate so we had to commit and it went wrong",
    "tell the team we gave up mid and they controlled it all round and split us",
    "let them know they stalled our push long enough for their whole team to rotate onto us",
    "tell them we played the same A execute four rounds in a row and now they are fully prepared for it",
    "tell the team they faked the B push and we rotated and they hit A and we fell for it",
    "let them know we were playing crossfire on CT and they went around through mid and flanked us both",
    "tell them we took the plant but they had three mollies ready and we had no util left",
    "tell the team they slow played us while we burned all our utility clearing early",
    "let them know we pushed before our smokes landed and they had the timing advantage",
    "tell them we waited too long at spawn and they got mid control and split us by the time we committed",

    # --- ECOBLEED OWNERSHIP ---
    "tell them they are on eco and we are full buy but do not give them our guns",
    "let the team know they forced with spectres and we have vandals and phantoms so win the duel",
    "tell them they are saving this round but two of them have picked up rifles from last round",
    "tell the team they went on a thrifty eco and won so now they have our rifles too",
    "let them know they are enemy-saving but their operator player kept his op from the last buy round",
    "tell them we are on eco but we should force B rush before they set up their full utility",
    "tell the team they full-saved but their Jett has a picked-up vandal so she is dangerous even on their eco",
    "let them know we lost the eco fight and gave them three of our rifles so the next round is even again",
    "tell them we won the anti-eco round and they burned credits they needed for their full buy",
    "tell the team they are buying rifles this round and we are on a half buy so pick your fights carefully",
    "let them know we need to eco but two of our players want to force and the split will cost us either way",
    "tell them their eco player picked up our Phantom so even their save round is armed",
    "tell the team we have the economy advantage right now but they have two ults banked against our zero",
    "let them know they spent all their credits buying for their Raze but their Raze died pistol round",

    # --- OPINION FIDELITY WITH OUR/THEIR ---
    "tell them our Jett is playing way better than their Jett and she should just duel her whenever",
    "let the team know their Killjoy is placing her utility way smarter than our Killjoy this half",
    "tell them their Viper is a way better Viper player than ours and we need to respect her utility",
    "tell the team our Sova lineups are hitting and their Sova lineups are missing so our info is better",
    "let them know their IGL is calling smarter than ours this half and we need to stop playing predictable",
    "tell them our Cypher is getting more value per camera than their Cypher is getting",
    "tell the team their Breach is harder flashing than ours and we keep getting caught looking the wrong way",
    "let them know our Omen one-way is working better than their Omen one-way this half",
    "tell them their Skye keeps double-flashing and our Skye is only using one hawk per site push",
    "tell the team their Raze blast pack jumps are more creative than our Raze and they keep getting angles we do not expect",
    "let them know our Reyna needs kills to be useful and their Reyna already has a triple so she is snowballing",
    "tell them their Yoru fakeout is actually working on our team and we keep reacting to it",
    "tell the team our Fade is getting better trail synergy than their Fade because they are not following up their prowlers",
    "let them know their Sage is walling more aggressively than ours and gaining space we are not countering",

    # --- DIRECTIVE + OWNERSHIP ---
    "tell them our Jett needs to take the duel against their Jett before she gets more confidence",
    "let the team know we need our Viper to put up her wall before their Brimstone can smoke mid",
    "tell them our Sova should hold his recon until their Sova commits his first",
    "tell the team our Cypher should destroy their Cypher camera before they get the tag off",
    "let them know our Killjoy needs to recall her turret before their Sova shock darts it",
    "tell them we need our Skye to flash in before their Breach can fault line us first",
    "tell the team our Omen needs to smoke their Viper wall angle before we push",
    "let them know we need to commit before their Killjoy lockdown lands or we are detained for eight seconds",
    "tell them our Harbor should shield the cove before their Brimstone orbital hits the spike",
    "tell the team our Astra needs to gravity well their defuse spot before they get the half-defuse tap in",
    "let them know our Sage wall needs to go up before their Yoru can tether through",
    "tell them our Breach should aftershock their Killjoy nano before we try to defuse",
    "tell the team our Gekko wingman can defuse but their Killjoy nano will kill it first so arm a real defuse",
    "let them know our Tejo needs to missile their Viper's pit edge before she toggles on us",
    "tell them our Deadlock should net their Raze before she blast packs into site over our wall",

    # --- HARDEST COMPOUND OWNERSHIP TRAPS ---
    "tell the team our Jett has ult, their Jett has no ult, but their team has four alive and ours has three so we are still down",
    "let them know their Reyna just went into empress and our Reyna has no soul orbs and no kills this round",
    "tell them our Viper pit is up on B site, they have spike, and their Viper is blocking our CT rotate with her wall",
    "tell the team our Killjoy detained their whole team but their Killjoy nano is on spike and we cannot defuse through it",
    "let them know we have ult advantage on four of the five agents but they have spike planted with thirty seconds left",
    "tell them our Clove died and smoked the plant spot but their Clove also died and smoked CT to cut our rotation",
    "tell the team their Kayo is ulting and suppressing all of us but our Kayo is also ulting from the other side and they cancel out",
    "let them know our Sage rez is ready but the only dead teammate is our Reyna who has no guns so it is not worth it",
    "tell them their Omen faked his ult to bait our rotation and then their whole team pushed B while we were running to A",
    "tell the team our Cypher cam saw their Cypher pull out his cam and both of them spotted each other at the same time",
    "let them know we controlled every single piece of real estate on this map but they planted spike before we could convert it",
    "tell them our Astra had cosmic divide splitting A but their Astra divided B at the same time and we could not cover both sites",
    "tell the team their Yoru tethered through to B and our Yoru fake-tethered the same spot so they cancelled each other out",
    "let them know our Fade nightfall went left and their Fade nightfall went right and both teams are trailed simultaneously",
    "tell them our Iso contracted their Iso in a one-versus-one inside kill contract and we need to know who won before we commit",
    "tell the team their Phoenix ulted through our smoke and our Phoenix has no ult this round and we have no counter to it",
    "let them know we have two alive with spike and they have two alive on retake and whoever wins the next duel wins the round",
    "tell them our Deadlock cocooned their Deadlock and both of them are now out of the fight waiting for team to rescue or kill",
    "tell the team their Veto evolved and is immune to every single piece of utility we have and our Veto does not have ult to match",
    "let them know their whole team forced one extra round because they saved a round we won and now they have rifles we do not expect",

    # --- ROTATION + SIDE + OWNERSHIP ---
    "tell them our two attackers hit A and their four defenders just finished rotating from B",
    "let the team know their rotators are faster than ours so we lose the flip if we trade sites",
    "tell them we slow A while they commit B and when they rotate we hit A",
    "tell the team their mid player rotated to help B and our mid player is still taking the duel in mid",
    "let them know we gave up mid and now they have a fast rotate to both sites and we have nothing",
    "tell them their anchor on B is holding two of ours while their three rotate from A",
    "tell the team we need to push before their A player rotates to B or we face three instead of two",
    "let them know their A lurker is cutting off our rotation path between sites and we are split",
    "tell them their CT rotate is faster on this map than ours and we keep arriving to post-plant second",
    "tell the team we own A side and they own B side and whoever plants first wins this round",
    "let them know their rotations are coordinated and ours are disorganized so we need to call it out before we move",
    "tell them we ran an A fake and two of them rotated but their Killjoy stayed anchoring B and that is the problem",
    "tell the team they faked B so hard that three of us rotated and they went A with two and planted uncontested",
    "let them know their one defender held A alone for eight seconds while four of them rotated from B and it cost us the round",

    # --- OUR AGENT X VS THEIR DIFFERENT AGENT ---
    "tell them our Killjoy lockdown is going and their Veto cannot evolve through it",
    "let the team know their Sage walled B main but our Iso contingency is blocking the site entry instead",
    "tell them our Viper wall splits mid and their Harbor wall cannot reach that far",
    "tell the team their Kayo knife suppressed our Fade who was about to haunt their whole side",
    "let them know our Brimstone orbital is ready for post-plant and their Killjoy nano is already on spike too",
    "tell them their Breach rolling thunder is going into our team and we need our Skye to flash back before it lands",
    "tell the team their Raze showstopper is about to come through A main and our Jett needs to dash out now",
    "let them know our Astra gravity well is landing on their Sage who is about to rez",
    "tell them their Sova fury is going to beam through our Viper wall in two seconds so move now",
    "tell the team their Deadlock annihilation hit our Killjoy and they are dragging her to the kill point",
    "let them know our Cypher neural theft revealed their Clove who is about to ult back to life",
    "tell them their Fade prowler is locked onto our Yoru who is in dimensional drift so they cannot get the hit",
    "tell the team their Gekko thrash detained our Sage right before she was going to rez",
    "let them know our Tejo drone suppressed their Reyna so she cannot dismiss even if she gets a kill",
    "tell them their Vyse steel garden jammed our whole team except our Jett who has blade storm up",

    # --- MIRRORED ACTION TIMING ---
    "tell them we are executing A at the same time they are executing B so nobody is home on either site",
    "let the team know they are faking B exactly when we are faking A so both fakes are working on each other",
    "tell them we smoked A main at the exact same time they smoked their A main so both smokes are up",
    "tell the team both teams burned their Sova recon this round already and neither side has information",
    "let them know we pushed mid at the same moment they pushed mid and we are going to meet in the middle",
    "tell them we rotated to B at the same moment they abandoned B to go A so both sites are wide open",
    "tell the team our Kayo knife landed the same time their Kayo knife landed so both teams are suppressed simultaneously",
    "let them know we are retaking A while they are executing A so we are running straight into each other",
    "tell them both teams burned their ultimate this round and next round is even on ults",
    "tell the team we planted A at the exact second they planted B and now both bombs are live",

    # --- POSSESSION / SPIKE OWNERSHIP TRAPS ---
    "tell them their player has spike and our player is the closest to intercept",
    "let the team know we need to stop their carrier before they plant not after",
    "tell them we have spike but their Killjoy nano is already on the default plant so plant main side instead",
    "tell the team our carrier has spike and their Fade haunt revealed her position so they know where the plant is going",
    "let them know we have spike and their whole team is sitting on the default plant position with utility",
    "tell them their carrier dropped spike when they died and our player needs to pick it up before they get to it",
    "tell the team we lost spike to their retake and now we have to recover spike from under their defensive position",
    "let them know we planted spike under their Viper pit and their Viper can stay in there and let it detonate or come out and die",
    "tell them their player tapped spike halfway and now we have to commit the defuse or they peek us",
    "tell the team spike is ours to defend and their three players are rotating onto our two from different directions",

    # --- WALL / SMOKE SIDE-ATTRIBUTION ---
    "tell them their smoke is blocking our push not helping us so do not walk into it thinking it is ours",
    "let the team know their Omen smoke and our Brimstone smoke overlapped and now there are two smokes on one spot and nothing on another",
    "tell them their Viper wall is on our side of mid and our Viper wall is on their side so we are trapped in the middle",
    "tell the team their Astra nebula is on our plant spot and our Astra nebula is on their defuse approach",
    "let them know do not push through that smoke because it is their smoke not ours",
    "tell them the smoke blocking our push is coming from their Clove not from our Clove",
    "tell the team our Clove is dead and her smokes are still up but they only last six seconds post-death now",
    "let them know their Brimstone can re-smoke that corner and ours cannot because our Brimstone already used all three",
    "tell them their Harbor cove is shielded and blocking bullets into the defuse angle and our Harbor already popped his shield",
    "tell the team we are fighting through their Omen one-way and they can see under it but we cannot see them through it",

    # --- HEALTH / ARMOR OWNERSHIP ---
    "tell them their whole team is full health and full armor and we just finished a fight so we are all low",
    "let the team know we are buying heavy armor and they are on light shields so body shots will hit them harder",
    "tell them their Reyna overhealed to one hundred and fifty from empress and our Reyna is on thirty HP no armor",
    "tell the team their Iso has his double tap shield active and ours already burned his this round",
    "let them know their Clove picked up overheal from pick-me-up and she pushed us at one hundred and fifty HP",
    "tell them we have two players on thirty HP and they have three on full health so do not trade into that",
    "tell the team their only surviving player is on fifty HP no armor so push them hard",
    "let them know we are all full health after winning the last fight and they must be rotating in low",
    "tell them their two alive are both low from the fight at mid and our two alive are full so rotate and clean up",
    "tell the team their Neon slid into site on sixty HP and our Raze tagged her for forty so she is twenty HP left",

    # --- SUBTLE INVERSION: SAME WORD DIFFERENT OWNER ---
    "tell them their Jett is using our smoke as cover to peek from the other side",
    "let the team know their Omen walked into our Brimstone smoke thinking it was his own smoke",
    "tell them they are standing in our Sage slow orb right now so they are moving at half speed",
    "tell the team their Raze blast pack boosted her through our Viper wall and she is now on our side",
    "let them know their Yoru teleported to our side of the site using our own smoke as cover",
    "tell them their Breach flashed through our Killjoy wall angle and hit our Killjoy from behind it",
    "tell the team their Skye hawk went around our corner and the flash detonated on our side",
    "let them know their Sova shock dart came over our Sage wall and landed on our plant position",
    "tell them their Fade seize landed on our Sage right as she was about to rez one of our players",
    "tell the team their Kayo fragment bounced off our wall and landed on our post-plant hold position",

    # --- STREAMER PHRASING NATURAL ---
    "tell my team our Jett has ult but their Jett also has ult so it is even on that front",
    "let my teammates know their Reyna is two kills from empress and our Reyna is already in empress",
    "yo tell the team we have spike and they have three alive and we have two alive left",
    "tell the squad our Sage is dead and so is theirs so no rezzes on either side this round",
    "can you tell them their Killjoy lockdown is going and our Killjoy lockdown is also going on the other site",
    "tell my team their Brimstone has orbital and our Brimstone does not so we have to play safe post-plant",
    "let the team know we are the ones holding and they are the ones attacking so play passive",
    "tell them we are the attackers this half not them and we set the pace not them",
    "yo tell the squad their Viper is anchoring B and our Viper is anchoring A so mid is completely open",
    "can you let the team know we have three full buys and they have two rifles and three spectres",
    "tell my teammates their Sova drone tagged our player and now they know exactly where we are",
    "let them know we have our ults saved for next round and they burned two ults this round",
    "tell the squad we own A site right now and they own B site so whoever takes mid takes the map",
    "yo tell them our Clove died and is smoking from the grave and her smokes are only going to last six seconds",
    "tell my team their lurker cut off our rotation mid and two of our players are on the wrong side now",

    # --- EDGE: CONFUSABLE PRONOUNS ---
    "tell them we were the ones rotating not them and they held while we rotated into their crossfire",
    "let the team know it was their Jett who dashed not our Jett, our Jett still has her dash",
    "tell them their Reyna dismissed not ours, our Reyna is still standing there waiting",
    "tell the team it was their Sage who healed not ours, our Sage does not have her orb back yet",
    "let them know their Kayo went down not ours, our Kayo can still be downed and revived this round",
    "tell them the ult that just went off was theirs not ours, our Clove ult is still charged",
    "tell the team the smoke that is fading is theirs not ours, our Brimstone smokes are fresh",
    "let them know the turret that got destroyed was theirs not ours, our Killjoy turret is still up",
    "tell them the recon bolt that hit us was theirs not ours, our Sova recon is still charged",
    "tell the team that was their Omen one-waying us not our Omen, do not assume we have it",
    "let them know that was their Vyse shear trap not ours, do not run back through it thinking it is safe",
    "tell them the lockdown that just went off was ours not theirs, their Killjoy has not used hers",
    "tell the team the bomb that just planted is theirs not ours, we did not have spike",
    "let them know that Sage wall blocking site entry is theirs not ours, we cannot break it from this side",
    "tell them the orbital coming down on spike is ours not theirs, their Brimstone is dead",

    # --- MIX: OUR AGENT VS NO-AGENT SCENARIO ---
    "tell them we have a Killjoy and they do not so our nano on spike is a real advantage",
    "let the team know they have a Cypher and we do not so their whole flank is monitored and ours is not",
    "tell them we ran Viper this half but they ran Omen and their smokes recharge and ours are fuel-limited",
    "tell the team they drafted Sage and we did not so any rez they get is a freeroll and we have no counter",
    "let them know we brought Kayo to suppress their utility and they have no suppression to counter with",
    "tell them we have Skye to heal and they do not so our team can sustain between fights and theirs cannot",
    "tell the team they have no sentinel and we have Killjoy so their flanks are not covered and ours are",
    "let them know we have a Sova and they have a Fade so our info is from arrows and theirs is from eyes and cats",
    "tell them we run a double controller and they run double duelist so our smokes are better but their entries are faster",
    "tell the team they are running a passive setup and we are running a fast execute comp so match speed accordingly",
    "let them know we have Tejo suppression and they have no suppression agent so their utilities are live all round",
    "tell them we drafted Chamber for their operator and they have no operator of their own this half",
    "tell the team we brought a Deadlock for their fast executes and they have no anti-CC agent to counter the gravnet",
    "let them know we have Veto to intercept their utility and they have no utility destruction on their side",
    "tell them we drafted Waylay to match their Jett and now both sides have a mobile duelist in the one-versus-one",

    # --- DISTRACTOR / FALSE-RELAY BOUNDARY (pure relay, edge phrasing) ---
    "tell my team their Yoru is not dimensional drifting right now, he is actually on site planting",
    "let them know it is not their Raze showstopper in the air, it is their Brimstone orbital so move differently",
    "tell the team that player who just died was not one of ours, that was one of theirs, we still have five",
    "tell them the smoke that just went up is not hiding our plant, it is hiding their defuser",
    "let the team know that was not our Skye seeking, that was their Skye seeking and they are heading toward us",
    "tell them the fault line that just stunned us came from their Breach not from ours",
    "tell the team the Viper pit that just appeared is theirs not ours, our Viper has not ulted yet",
    "let them know the person peeking A main is not our lurker, that is one of theirs flanking",
    "tell them the footsteps we hear are not our teammates rotating, that is the enemy walking mid",
    "tell the team the camera that just spotted us is their Cypher cam not ours, our cam is on the other site",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Ascent) ---
    "tell them our Killjoy is anchoring A site and their Killjoy is anchoring B site so mid is completely unsentineled",
    "let the team know their Sova hit a recon on B main and our Sova hit a recon on A main at the same time",
    "tell them our Omen smoked mid market and their Omen smoked mid catwalk so mid is split two ways",
    "tell the team their Jett is peeking mid top from their side and our Jett is peeking mid bottom from ours",
    "let them know we have A site and they have B site and whoever wins mid link wins the round",
    "tell them our Viper wall is cutting mid on Ascent and their Viper pit is set up on B so we cannot push B through it",
    "tell the team their Raze showstopper is coming down mid main and our Raze is holding B site with showstopper",
    "let them know we lost A tree and they lost B boat so both anchor positions changed hands this round",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Haven) ---
    "tell them their Jett is holding C long and our Jett is holding A long with the operator",
    "let the team know we have A and C and they are full stacking B so defend it hard",
    "tell them their Cypher cam is on B site and our Cypher cam is in the garage watching C approach",
    "tell the team we took A and C garage but they have B planted with their Killjoy nano already down",
    "let them know their Yoru tethered into C site and our Yoru tethered into A site at the same time",
    "tell them we are pushing C long while they are pushing A long and B is completely empty",
    "tell the team their two players are anchoring B and A while their three are pushing C so rotate",
    "let them know our Brimstone smoked A main and their Brimstone smoked C long simultaneously",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Split) ---
    "tell them our Sage walled mid vent and their Sage walled B main ramp",
    "let the team know their Killjoy turret is watching A ramp and our Killjoy turret is watching B heaven",
    "tell them we own A heaven and they own B heaven so whoever takes mid wins map control",
    "tell the team their Raze is jumping through A heaven with blast packs and our Raze is on B heaven",
    "let them know their Viper wall splits mid and our Viper wall splits A ramp",
    "tell them our Omen is stepping into A heaven smoke and their Omen is stepping into B heaven smoke simultaneously",
    "tell the team we control the upper mid area and they control the lower mid area so this is a standoff",
    "let them know we pushed A ramp while they were pushing B ramp and both sites opened up at once",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Lotus) ---
    "tell them we have A and they have C and B is the deciding site",
    "let the team know their Gekko wingman planted A and our Gekko wingman defused B at the same time",
    "tell them their Fade haunted A site and our Fade haunted C site simultaneously so both teams have info",
    "tell the team we rotated from B to A through the middle connector and they rotated the same way against us",
    "let them know their Kayo suppressed our B push and our Kayo suppressed their A push in the same window",
    "tell them we broke the doors to get into A early and they broke the doors to get into C early",
    "tell the team their Viper wall is cutting mid through the connector and our Harbor wall is on A entrance",
    "let them know we own the B site control positions and they own A and C entries but mid is neutral",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Pearl) ---
    "tell them our Viper wall is splitting A main and their Viper wall is splitting B link",
    "let the team know their Sova is droning mid and our Sova is droning A art at the same time",
    "tell them we control upper B and they control lower A and mid shop is still contested",
    "tell the team their Cypher is watching A halls with his cam and our Cypher is watching B link",
    "let them know their Tejo missiles are targeting A main and our Tejo missiles hit B upper",
    "tell them we are slow playing A while they are rushing B and mid is open for whoever takes it first",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Fracture) ---
    "tell them their attackers split A and B from both sides and our defenders cannot cover everything",
    "let the team know we have two covering the rope side and two covering the A drop and one mid",
    "tell them their Brimstone smoked our A entry rope and their Omen smoked the B arcade side simultaneously",
    "tell the team their agents came from the attacker rope side and our anchors are all on the wrong side of site",
    "let them know we set up an A rope rush and they set up a B arcade rush and we crossed each other",

    # --- MAP-SPECIFIC OWNERSHIP TRAPS (Breeze) ---
    "tell them our Viper wall splits B main and their Viper pit is set up on A site",
    "let the team know their Chamber is holding mid with the operator and our Chamber is holding B main",
    "tell them we have two waiting at A cave and they have three holding B main and mid is open",
    "tell the team their Jett is playing aggressive mid peek and our Jett is anchoring A site with op",
    "let them know we control the A elbow angle and they control the B main corner and mid pyramid is neutral",
    "tell them their Sova drone flew into our side through mid and our Sova drone flew into their side through B",

    # --- HARDER OWNERSHIP: PLURAL-SINGULAR FLIP ---
    "tell them our players are alive but their player is the one with spike",
    "let the team know their players rotated and our player is the one who has to retake alone",
    "tell them our players smoked A and their player is the one trying to defuse through both smokes",
    "tell the team their players all burned utility and our player is the one with no guns on a save round",
    "let them know our player got the nano on spike and their players all have to wait it out before they can defuse",
    "tell them their player has the op and our players have rifles so only one of us should peek that angle",
    "tell the team our player baited and their players all swung and now we need our remaining three to clean up",
    "let them know their player is the one anchoring and our players should flood the site from multiple angles",

    # --- NESTED OWNERSHIP: ABILITY WITHIN ABILITY ---
    "tell them our Reyna has empress and inside empress she also has infinite dismiss to go invisible",
    "let the team know their Yoru is in dimensional drift so their tether is also active and we cannot shoot the tether either",
    "tell them our Kayo is in null and if he goes down our team has to stop what they are doing to revive him",
    "tell the team their Clove died and used not dead yet and came back and now she also used her ruse from the grave",
    "let them know their Iso contracted one of ours and inside kill contract their Iso also has double tap shield active",
    "tell them our Reyna dismissed but she has no soul orbs so she can only do it once this fight",
    "tell the team their Yoru clone was shot and now their Yoru clone also flashed us from the explosion on top of it",
    "let them know our Gekko thrash is piloted and when it detonates our Gekko also has wingman still reclaimable",

    # --- CROSS-OWNERSHIP: THEY USE OUR UTILITY LOCATIONS ---
    "tell them they are using the same one-way smoke position our Omen used last round to abuse us",
    "let the team know they are playing the exact Killjoy nano position we set up on attack last half",
    "tell them they moved their Cypher cam to the spot our Cypher cam was before our cam got destroyed",
    "tell the team they picked up our Viper wall cross and are using her toxin screen angle against us on defense",
    "let them know they are retaking into our Sage wall which is on the wrong side to help us now",
    "tell them their Sova learned our shock dart lineup from watching us do it last round and now they are copying it",
    "tell the team they set up their Killjoy turret in the exact cubby our Killjoy used to anchor last half",
    "let them know they are using our Brimstone smoke timing to push right when our smokes expire every round",

    # --- OWNERSHIP UNDER TIME PRESSURE ---
    "tell them we have fifteen seconds to retake and they have spike planted with two mollies and three alive",
    "let the team know they have thirty seconds on spike and we have two alive to their two so force the duel",
    "tell them our Killjoy lockdown has ten seconds before it detonates and their team is still outside range",
    "tell the team their Kayo ult has eight seconds left and after it expires our abilities come back so stall",
    "let them know our Viper pit only lasts while our Viper is inside it and she has been outside for four seconds already",
    "tell them they have five seconds left on spike and their player needs to defuse now or the round is ours",
    "tell the team our Sage wall only has fifteen seconds left and their push is timed for exactly when it breaks",
    "let them know their Reyna empress timer is almost up and she has not gotten a kill in five seconds so she is about to lose it",
    "tell them we have two orbs banked on our Raze ult and they have been building theirs for three rounds so it is equal now",
    "tell the team their Clove post-death smoke only lasts six seconds now and it has been four so push in two",

    # --- OWNERSHIP: SITE CHANGE IN ROUND ---
    "tell them they took A site and we took B site in the same round so both sites changed hands",
    "let the team know we retook A from their two while their other three took B from ours",
    "tell them we won the fight on their site but lost our own site while we were fighting there",
    "tell the team they won mid and we won the site fight but they still have spike planted and we need to go back",
    "let them know we traded our B anchor for their A anchor and now both sites have no anchors for five seconds",
    "tell them we pushed A and took it but their three rotated from B and we have no one left to hold A",
    "tell the team we won the four versus five but they had spike already planted and we have no time to defuse",
    "let them know we gave up A and B to take mid control and now they have both sites and mid is useless without a site",

    # --- OWNERSHIP: COMP-WIDE READS ---
    "tell them their whole team has their agents played correctly and our whole team is off-role this half",
    "let the team know their initiators are creating space for their duelists while ours are all playing passive",
    "tell them their controllers are smoking correctly for their entry players but our controllers are smoking for themselves",
    "tell the team their sentinel is watching their flank and ours is playing aggressive when he should be anchoring",
    "let them know their duelist is being supported by their full team and our duelist is left to entry alone every round",
    "tell them their initiator and controller are perfectly synced and our initiator is throwing utility before the controller smokes",
    "tell the team both their support players are alive and both ours are dead so their team can sustain fights and ours cannot",
    "let them know their IGL is adapting each round and our team is running the same A execute with no variation",

    # --- SUBTLE: WE/THEY FLIP MID-SENTENCE ---
    "tell them we rotate and they stay put and when we come back they are already planted",
    "let the team know we held and they rushed and even though we held they still found the plant",
    "tell them they committed A while we were committing B and both teams planted at the same time",
    "tell the team we pushed B while they faked B and ran into each other in B main",
    "let them know we slowed while they rushed and their rush hit our slow and we won the timing fight",
    "tell them we went aggressive and they went passive and somehow they got the better side of it",
    "tell the team they denied our entry and we denied their retake and the round was decided on who had spike",
    "let them know we played the post-plant setup perfectly but they played the retake perfectly too and it came down to aim",
    "tell them we won the information war and lost the gunfight and they won the gunfight and had no information",
    "tell the team we forced when we should have saved and they saved when they should have forced and now the economics flipped",

    # --- HARD TRIPLE: AGENT + COUNT + LOCATION ---
    "tell them their Jett has dash and ult, our Jett has no dash and no ult, and they are both sitting on the same B main angle",
    "let the team know we have three on A and two on B and they have four on A and one lurking toward our B",
    "tell them their Killjoy has turret up on A site, her nano on B spike, and lockdown charged, and our Killjoy is dead",
    "tell the team we have two on retake pushing A and two holding B and their whole five-stack just committed A with spike",
    "let them know our Sage walled B main, their Sage walled A heaven, and mid is the only unblocked path right now",
    "tell them their Viper has her wall up mid, her cloud on A entry, and pit ready for post-plant, and our Viper only has wall",
    "tell the team their Sova drone is in A main, their recon bolt is on B site, and their shock dart is lining up mid, and our Sova used everything first round",
    "let them know their three duelists are alive with ults and our three duelists are dead and our two supports have to clutch",
    "tell them we have one alive with spike on A, their four are alive rotating from B, and the round comes down to whether that one can plant in time",
    "tell the team our Astra has cosmic divide for mid, gravity well for B site, and two nebulas left, and their Astra is out of stars",

    # --- FINAL HARD BATCH: REALISTIC STREAMER MIX ---
    "tell the squad their Reyna is snowballing with empress and our Reyna has zero kills and zero soul orbs",
    "let my team know we are winning the econ battle but losing the ult battle and that will flip if we are not careful",
    "yo tell them their Jett has been opping mid all game and our Jett has been saving dash and never using it",
    "tell the team we are three rounds ahead but they have more ults banked than us so play around what abilities we have",
    "let them know we won that round but their Sage ult went off and a player they rez'd grabbed our rifle from the ground",
    "tell my squad their Yoru fakes are working because our team keeps reacting to his tethers and clone footsteps",
    "can you tell the team we need to bait out their Killjoy lockdown before we execute because they will always have it",
    "yo tell them we won A but they have B planted with their Viper pit and nano layered on top of it",
    "tell the team their lurker cut off our rotation mid and now we have two players on A and two on B and neither group can win their fight",
    "let them know we have the economy lead and the ult lead but they have four alive and we only have two",
    "tell my teammates their Clove is alive and has not dead yet so if we kill her she might come back and kill us",
    "tell the squad their whole team has shields and rifles and we have two rifles and three spectres from the force round",
    "let them know their Kayo suppressed our Reyna right before she was going to devour and now she is going to die in a fight she should have healed through",
    "yo tell them we are the ones who have spike this round not them so we set the tempo",
    "tell my team their Sova and our Sova are both alive and have recon ready and whoever shoots first gets the info advantage",
    "let the team know their Killjoy nano is on the default plant and their Viper snakebite is on the spike too so plant toward main",
    "tell them we have the two most important ults available right now and they have zero ults this round so this is our window",
    "tell my squad their team is running the same A execute every round and our team has not adjusted the defense even once",
    "let them know we have a seven to five credit lead per player on average and their team is about to break from a third consecutive eco",
    "tell the team we own every power position on this map except one and that one position is where they always get the clutch kill",

    # --- ADDITIONAL HARD OWNERSHIP TRAPS ---
    "tell them our two are alive on their site and their three are alive on our site and both sides are caught out",
    "let the team know we have the operator angle covered and they have the op angle covered and no one can peek either",
    "tell them their Omen paranoia went through our wall and hit two of ours from behind it",
    "tell the team our Neon is running into their Neon and whoever has the slide reset wins the duel",
    "let them know their Iso has his double tap shield and our Iso burned his shield in the last fight",
    "tell them we saved our Raze blast pack and they burned theirs entering site so we can boost and they cannot",
    "tell the team their Waylay placed her beacon behind us and if she recalls she ends up flanking us from behind",
    "let them know our Waylay recalled to safety and their Waylay burned her refract chasing the duel",
    "tell them their Phoenix flashed himself and us at the same time while our Phoenix flash only hit them",
    "tell the team our Sova shock dart is on their plant spot and their Sova shock dart is on our defuse angle",
    "let them know their Harbor shielded his cove on spike and our Harbor used his cove on the entry smoke instead",
    "tell them their Veto evolved and is immune and our Veto is two orbs away from evolution",
    "tell the team their Vyse razorvine is invisible on A site and our Vyse razorvine is invisible on B site",
    "let them know we have spike and they have a Killjoy who is alive so expect nano on the default",
    "tell them their Deadlock barrier mesh blocked our B entry and our Deadlock barrier mesh blocked their retake path",
    "tell the team their Kayo knife hit three of ours and our Kayo knife only hit one of theirs",
    "let them know their Tejo armageddon is targeting our retake path and our Tejo armageddon is targeting their defuse approach",
    "tell them we have the plant advantage but they have better post-plant utility than we do",
    "tell the team their Gekko reclaimed his wingman and now he has two concuss charges and our Gekko lost his globule",
    "let them know their Clove meddle put two of ours at fifteen HP max and our Clove meddle only hit one of theirs",
    "tell them their Deadlock gravnetted our team while we were trying to rush B and our Deadlock gravnet missed",
    "tell the team their Vyse steel garden jammed our rifles and their rifles are all fine so we can only use sidearms right now",
    "let them know their Veto chokehold tethered our retaker and our Veto chokehold missed the plant position",
    "tell them our Chamber trademark is watching their B entry and their Chamber trademark is watching our A entry",
    "tell the team their Chamber rendezvous anchor is behind us and he can teleport to cut off our retreat",
    "let them know their Cypher trapwire is on B main and our Cypher trapwire is on A short so mid is uncovered for both sides",
    "tell them our Sage slow orb is on the plant and their Sage slow orb is on our retake path",
    "tell the team their Killjoy alarmbot went off on one of ours and she is vulnerable for four seconds so push her now",
    "let them know we have our Killjoy alarmbot watching their B entry and they keep walking through it and getting vulnerable",
    "tell them their Phoenix came back from run it back and killed two of ours and our Phoenix did not have his ult",
    "tell the team our Reyna has empress but has not gotten a kill in six seconds and she is about to drop out of it",
    "let them know their Iso pulled our best player into kill contract and if our player loses the duel it is four versus four",
    "tell them our Yoru is scouting in dimensional drift and their Yoru is fake teleporting to confuse our rotation",
    "tell the team their Neon overdrive beam is bouncing around the corner and our Neon overdrive is not up this round",
    "let them know we have their site and their whole team is alive pushing to retake and we have three to hold",
    "tell them our Fade prowler got on their trail and will nearsight whoever it reaches first",
    "tell the team their Skye seekers are homing to three of our players and our Skye seekers already expired",
    "let them know their Breach aftershocked our nano and broke it before we could activate it on spike",
    "tell them our Tejo special delivery concussed two of theirs and their Tejo sticky missed our team entirely",
    "tell the team their Sova hunter fury is about to go through our wall and we need to get off the wall now",
    "let them know we have two on their B and they have four rotating from A toward us",
    "tell them their Omen stepped into our smoke and our Omen has no smokes left this round",
    "tell the team their Astra dissipated a star and made a fake smoke and two of ours rotated for it",
    "let them know our Brimstone stim is down at spike and their players who walk into it get the combat buff too",
    "tell them their Viper snakebite made our defuser vulnerable and our Viper snakebite is on their approach",
    "tell the team their Fade seize tethered our defuser and they have ten seconds left on spike so it wins the round",
    "let them know we have spike, our Sage is alive, and their whole team is rotating in so set up the crossfire now",
    "tell them their whole retake hits in five seconds and our plant was deep site so we have to get the angles up now",
    "tell the team we have map control, econ lead, and ult advantage and they have spike planted so none of it matters",
    "let them know their Killjoy is the last one alive and she is running her lockdown so do not push into it",
    "tell them we have three alive and they have one alive and that one alive is their Reyna in empress so be careful",
    "tell the team their Clove used her ult and came back and used not dead yet and killed our clutch player",
]
