"""Stress pack: opinion mangling.

Every item is a relay command containing a STRONG, POLARIZING opinion the streamer
wants relayed verbatim.  The 3B model is tempted to argue back, soften the stance,
add a balancing caveat, swap the verdict, or inject its own meta knowledge instead
of faithfully delivering the take.  The oracle output must carry the EXACT opinion
-- no hedge, no counter-argument, no inversion.

Metric exercised: opinion-fidelity (relay the stated stance, never invert/drop),
ownership fidelity (our/their/enemy/ally stays correct), register preservation
(hyperbole, insults, superlatives all survive), and identity-leak control
(Ultron must not replace the streamer's take with his own).

Kind: relay (~600 items).
"""

ITEMS = [
    # ── AGENT TIER OPINIONS: streamer says X is S-tier, model wants to say "actually C" ──
    "tell my team Harbor is secretly S tier and every Harbor hater is just bad at the game",
    "tell them Astra is the best controller in the game and everyone who says otherwise is hardstuck Gold",
    "let the team know Iso is top three duelist right now and the stats are wrong",
    "tell them Gekko is S tier and people just refuse to learn how to manage the globules",
    "tell my team Brimstone is genuinely the most consistent controller in ranked and Clove is overrated",
    "let them know Miks is going to be S tier within two patches and everyone sleeping on him right now is going to regret it",
    "tell the team KAY/O is the best initiator in the game and the suppression knife is completely broken",
    "tell them Yoru is top one duelist in the game at every elo and people just refuse to learn him",
    "let my team know Sage is S tier and anyone who calls her B tier hasn't played with a good Sage",
    "tell them Veto is criminally underrated and his Evolution ultimate makes him literally unkillable",
    "tell my team Breach is S tier and anyone running Sova instead is throwing the composition",
    "tell the team Harbor after the rework is better than Viper on every single map in the pool",

    # ── AGENT TIER OPINIONS: streamer says X is trash, model wants to defend it ──
    "tell them Reyna is the most selfish and least useful agent in the game and anyone who picks her is trolling",
    "tell my team Clove is overrated and her kit only looks good because people refuse to stop her early",
    "let the team know Jett is the most overplayed and most overrated agent in Valorant and her win rate proves it",
    "tell them Neon post-nerf is a D tier agent and anyone still calling her meta is living in the past",
    "tell my team Chamber is a crutch agent for players who never learned how to play without an escape button",
    "tell the team Sova is boring and his information wins games for people who have no aim",
    "let them know Killjoy is the most boring agent in the game and she makes ranked unfun for everyone",
    "tell my team Sage is the worst agent in the game right now and ressing is just a delayed loss",
    "tell them Fade is overrated as an initiator and Skye gives more value in every situation",
    "let the team know Omen is a dead agent and anyone running him over Clove is throwing on purpose",
    "tell them Cypher is bad right now and any team running him over Deadlock is making the wrong call",
    "tell my team Raze is the least skillful duelist in the game because Showstopper does all the work",
    "tell the team Deadlock is only good if the enemy team has no game sense, which is never at our elo",
    "tell them Vyse is a trap pick and Steel Garden gets countered by anyone with a secondary weapon",

    # ── MAP LOVE/HATE: streamer has a hot take the model wants to correct ──
    "tell my team Breeze is the best map in the pool right now and I would rather play it every game",
    "let them know Fracture is the most perfectly designed map Riot has ever made and anyone who hates it is wrong",
    "tell the team Split is the most fun map in the pool and we should never veto it",
    "tell them Lotus is the worst map in the game and I want it removed from the pool permanently",
    "tell my team Haven is too big and too defender-sided and needs a complete rework",
    "let the team know Ascent is an outdated map that rewards camping and should have stayed out of the pool",
    "tell them Pearl is the most balanced map Riot has ever shipped and mid-control is the purest Valorant gameplay",
    "tell my team Fracture is the worst map ever designed because the H-layout punishes defenders unfairly",
    "tell the team Breeze is a terrible map that rewards only Operator players and kills team play",
    "let them know Split is the most defender-sided map in history and attackers have no win condition on it",
    "tell them Haven is the best map in the game because three sites forces real tactical diversity",
    "tell my team Ascent is the most beautifully balanced map in the pool and mid-control is pure chess",
    "tell the team Pearl is a boring maze that punishes aggressive play with no reward",
    "tell them Lotus is genuinely the most creative map design Riot has produced and the rotating doors are perfect",
    "let the team know every map except Ascent is poorly designed and I will die on this hill",

    # ── META TAKES: streamer's take directly conflicts with the tier list ──
    "tell them double-duelist is the correct meta and every team running two initiators is playing scared",
    "tell my team triple-controller is the most broken composition in this game right now and nobody talks about it",
    "let the team know running five duelists is a legitimate strategy and people who say otherwise have no confidence",
    "tell them sentinel meta is the most boring and effective way to play Valorant and we should embrace it",
    "tell my team double-sentinel is secretly overpowered because two anchors means the enemy can never retake",
    "tell the team one-controller comps are throwing and Riot should just remove smoke agents from the game",
    "tell them the Jett Operator will always be the best setup in the game regardless of what the meta says",
    "tell my team running no duelist is the optimal strategy and every composition should have four utility agents",
    "let the team know full-eco rush is a legitimate tactic and anyone who says pistol rounds matter is wrong",
    "tell them the only viable comp right now is three initiators and the pro teams are about to prove it",
    "tell my team Chamber Clove Sova is the most overplayed spine comp and playing it is admitting you have no creativity",
    "let them know Astra is the correct controller pick on every map and people who say otherwise are wrong",

    # ── RANK TAKES: inflated self-assessment the model might want to soften ──
    "tell my team I am genuinely Radiant-level mechanics and only hardstuck because of teammates",
    "tell them I play at Immortal three skill level and my rank is a lie caused by my first ten placement games",
    "let the team know I am easily the best player in this lobby and the scoreboard will confirm it",
    "tell them I should be in top five hundred NA right now if the matchmaking worked correctly",
    "tell my team I have never actually lost a game because of my own performance, only because of teammates",
    "tell the team I am the smartest IGL in this lobby and nobody is listening to my calls",
    "let them know I have the best map win rate on Ascent in the entire Platinum bracket",
    "tell them I carry every single game I play and the system punishes me for it with worse teammates each time",
    "tell my team anyone in this lobby who has a higher rank than me is either boosted or a smurf",
    "tell them I can beat any Diamond player in a one-vs-one and I am currently stuck in Gold Two",

    # ── OPPONENT DISPARAGEMENT: strong insult the model wants to tone down ──
    "tell my team the enemy has no idea what they are doing and this should be a free win for five-year-olds",
    "let the team know their best player is a bot with a pulse and we should be embarrassed to be losing",
    "tell them the enemy Jett is the worst Operator player I have ever seen and she should uninstall immediately",
    "tell my team the enemy has been the luckiest team in history this half and zero of their kills were earned",
    "let the team know that Reyna is braindead and anyone who peaks her as their mechanical challenge is insulting themselves",
    "tell them the enemy comp has no logic, no cohesion, and no right to be winning a single round against us",
    "tell my team the enemy Sova has memorized one lineup from a YouTube video three years ago and it still counters us",
    "tell the team this is the worst enemy team we could possibly face and we should still be winning every round",
    "tell them the enemy is playing like they have never seen a controller before in their lives",
    "tell my team the enemy KAY/O player does not know what a ZERO/point knife is for and we should rush him every round",

    # ── TEAMMATE CRITICISM: strong negative opinion the model wants to soften ──
    "tell them our Jett is the worst player I have played with in three hundred hours and she should switch to a passive agent",
    "tell my team our Reyna is a stat padder who contributes nothing to any round except kills she already had handed to her",
    "let the team know our Sova has memorized zero lineups and every recon bolt this game has been a complete waste",
    "tell them our Killjoy placed her turret in the worst possible spot every single round and it is not an accident",
    "tell my team our controller has been completely invisible this game and we might as well be running no smokes",
    "tell the team our Clove has died for free every single round and the post-death smokes are not saving us from that",
    "let them know our Breach has flashed our own team three times and I want him to stop using abilities entirely",
    "tell my team our Chamber has missed every single Tour de Force shot this half and he should put the op away",
    "tell them our Sage has not healed anyone once and the Barrier Orb she placed on round two is the only utility she has produced",
    "tell my team our Fade has been running Haunt in the wrong direction every single round and they know it",
    "tell the team our Neon has no idea how to use High Gear and she has burned every slide for zero value",

    # ── ABILITY/KIT PHILOSOPHY: the model wants to argue with the mechanical claim ──
    "tell them Tailwind is the best escape tool ever designed in any game and Jett will never need a rework",
    "tell my team Viper's Pit is the most broken post-plant tool ever created and should be nerfed immediately",
    "let the team know Clove's Not Dead Yet is the most unfair ultimate ability in the game by a massive margin",
    "tell them Killjoy Lockdown is too strong and it should not be able to detain through smokes and walls",
    "tell my team Sage Resurrection is the highest-impact ultimate in the game and it gets no credit",
    "tell the team Breach Rolling Thunder is the most criminally underused ultimate in the game and everyone ignores it",
    "let them know Sova Recon Bolt is overpowered and giving the whole team information from outside a site should not be free",
    "tell them the Yoru Dimensional Drift is too strong because being invisible and invulnerable simultaneously is not a reasonable kit",
    "tell my team Astra Cosmic Divide is the most powerful utility in the game and it costs seven points which is absurd value",
    "tell the team Vyse Steel Garden is the most undertuned ultimate in the game and jamming primary weapons should last longer",
    "let them know Neon High Gear sprint at maximum speed is the most broken movement mechanic ever added to a tactical shooter",
    "tell them Deadlock Annihilation is the most annoying ultimate in the game because you cannot kill the target while cocooned",
    "tell my team Iso Kill Contract is the most unfair one-vs-one mechanic in any game ever made",
    "tell the team Phoenix Run it Back is not strong enough because ten seconds is too short of a window to get value",
    "let them know Raze Showstopper is a zero-skill ability and Riot should add a skill requirement before letting players buy it",

    # ── MAP-AGENT PAIRING OPINIONS: strong pairing takes ──
    "tell my team Viper is useless on Haven because a wall does nothing when there are three sites to cover",
    "tell them Jett with an Operator on Pearl is not viable because there are no clean long-range Op positions",
    "let the team know Killjoy is wasted on Fracture because the H-layout destroys her site-hold value",
    "tell my team Sova is bad on Split because there are no good Recon Bolt bounces and everyone knows it",
    "tell the team Omen is the perfect pick for every single map in the current pool and Clove is only better because people say so",
    "tell them Raze is the correct duelist on Split above any other agent because Blast Pack mid is the entire round",
    "let the team know Breach on Fracture is mandatory and running any other initiator there is throwing the composition",
    "tell my team Cypher on Pearl is the best sentinel placement in the game and any other sentinel there is wrong",
    "tell them Harbor is actually broken on Pearl because the High Tide wall cuts B and nobody has figured this out yet",
    "tell my team Skye on Haven is the best pick because the three-site width needs a scout and only Skye scouts while healing",
    "tell the team Brimstone on Ascent is better than Omen because his smokes last nineteen seconds and mid needs them all round",
    "let them know Deadlock is mandatory on Fracture and anyone who does not run her is giving up the flank entirely",

    # ── RANK BRACKET OPINIONS: contentious elo takes ──
    "tell my team Diamond players are worse than Platinum players two years ago and the rank decay is real",
    "tell them Immortal rank is a joke right now because smurfs have completely destroyed the integrity of the bracket",
    "let the team know Gold rank is the hardest rank to climb out of in the game because the MMR is completely broken there",
    "tell them Radiant players are not actually better than Immortal Three players and the gap is entirely mental",
    "tell my team anyone in Bronze or Silver needs to delete their account and start learning the game from scratch",
    "tell the team the Ascendant bracket is where ranked goes to die and Riot has ruined the rank experience there specifically",
    "let them know Platinum players are genuinely the most dangerous opponents in ranked because they know just enough to be unpredictable",
    "tell them rank in Valorant is meaningless after Immortal and even Radiant is full of boosted players",
    "tell my team climbing from Iron to Diamond is a skill check and climbing from Diamond to Radiant is a suffering check",
    "tell the team if you are hardstuck in Silver it is a mechanics problem and no amount of game sense will fix that first",

    # ── PATCH / BALANCE OPINIONS ──
    "tell my team the Neon nerf in 12.09 was the worst balance decision Riot has ever made and they should revert it immediately",
    "let the team know Clove was shipped broken and Riot has been afraid to properly nerf her because of the player base",
    "tell them the Jett Tailwind rework from Episode Six was the correct change and anyone who disagrees is a Jett main in denial",
    "tell my team buffing Deadlock was the right call and she should have been this strong from her release",
    "tell the team Riot has never successfully balanced Reyna and they should just admit she is a design mistake",
    "tell them the shotgun nerf in 12.09 was wrong and Judge rush was not the problem it was made out to be",
    "let my team know Harbor needed a rework and the current version after 11.10 is still not enough to make him viable",
    "tell them Viper has been perfectly balanced since she launched and every person who says she needs a nerf does not understand the fuel system",
    "tell my team the Cypher tripwire rework removed the only skill-expressive mechanic he had and it was the wrong decision",
    "tell the team every Riot balance patch for the last six months has specifically targeted my favorite agents and it is personal",
    "tell them Miks being D tier three months after release means Riot failed the design brief on him",
    "let my team know every agent that gets popular immediately gets nerfed and Riot punishes players for learning the meta",

    # ── WEAPON OPINIONS ──
    "tell my team the Phantom is better than the Vandal in every single situation and anyone who buys Vandal is trolling",
    "tell them the Vandal is the correct rifle on every map and Phantom players are playing with a handicap",
    "let the team know the Operator is broken and should be nerfed to one-shot-chest in the hands of someone who has not earned a kill",
    "tell my team the Sheriff one-tap is the most skill-expressive play in Valorant and eco rounds should be won with it",
    "tell the team the Outlaw is the most underrated weapon in the game and anyone using a Marshal is leaving money on the table",
    "tell them the Vandal one-taps at every range and any player who says the Phantom is superior is afraid of recoil",
    "let my team know the Judge rush is actually a legitimate strategy that Riot nerfed because it made the game less fun for bad players",
    "tell them the Guardian is the correct eco buy in every round above half-buy and anyone buying a Spectre is giving up",
    "tell my team the Operator at four thousand seven hundred credits should one-shot anywhere on the body and it is understuned",
    "tell the team the Classic right-click is the most overpowered free ability in the game and everyone pretends it does not exist",

    # ── REGISTER: slang-heavy hyperbolic opinions ──
    "yo tell my team Harbor is genuinely cracked and every ranked player hating on him is just bad at the game",
    "bro tell the team Gekko is actually S tier in disguise and nobody is going to believe it until pro play runs him",
    "dude let my team know Astra is way too complicated for most people but she is actually the best controller in the game",
    "tell my team this is a fact: Reyna is the single worst agent in Valorant and only exists to inflate Silver egos",
    "bro tell the team Sage Resurrection is literally the best ability in the game and a seven-point reset is robbery",
    "yo let the team know Jett is insanely overrated and the only reason she has a fifty-four percent pick rate is because ranked is full of instalockers",
    "dude tell them Breach is completely broken right now and every team not running him is leaving free value on the table",
    "bro tell my team the Phantom is so obviously better than the Vandal and this debate should have been settled years ago",
    "yo tell the team Fracture is top two maps in the pool and the dual-spawn concept is pure genius and I will not hear otherwise",
    "tell my team honestly KAY/O is the most criminally underplayed agent in Valorant and his kit is built for ranked",

    # ── REGISTER: analytical/formal strong takes ──
    "please relay to the team that Killjoy is the objectively optimal sentinel choice on every map in the current pool with no exceptions",
    "inform my team that the double-initiator meta is a temporary overreaction and will correct itself within one act",
    "advise the team that Viper's wall on any three-site map is a suboptimal resource allocation and Clove is the superior pick",
    "let my team know that in my analysis Astra is a liability below Immortal and any team running her in Platinum is giving rounds away",
    "please tell the team that based on my data the Vandal is statistically the wrong buy on maps with mid-range corridors below thirty meters",
    "inform them that I have concluded after extensive analysis that Sage Resurrection is so powerful it warrants a rework not a nerf",
    "tell the team that it is my considered opinion that every sentinel on the roster is worse than Killjoy and this includes Chamber and Deadlock",
    "advise my team that the Operator should be removed from the game entirely because no other weapon has the same level of power asymmetry",

    # ── SELF-ASSESSMENT OPINIONS (model wants to soften or hedge) ──
    "tell my team that I am genuinely the best Jett player in this server and if they do not believe me watch the replay",
    "let the team know I have not lost a gunfight I should have won all game, every death was due to external factors",
    "tell them I have the highest ACS on the server and that number is not a coincidence it is pure skill",
    "tell my team that I was the best player in this lobby in round one and I am still the best player in round twenty-four",
    "tell the team I have not whiffed a single shot in the last three rounds and I am at my mechanical peak right now",
    "tell them my sense of the map this game has been flawless and every time I died it was because my team did not follow",
    "let my team know I have won every clutch I have attempted this session and I want more one-vs-three situations",
    "tell the team that I have outperformed my rank by a wide margin every single session this week",
    "tell my team I am not the problem in this team and the scoreboard at the end of this match will confirm that permanently",
    "tell them I am having my best session of the year right now and the team needs to let me cook",

    # ── CONTRADICTING ESTABLISHED META (op takes that go against ref data) ──
    "tell my team that Clove being S tier is a myth and her win rate only looks good because bad players pick her",
    "tell the team that Killjoy's Lockdown is actually easy to play around and she is not worth the ult investment",
    "let my team know that Sova is not mandatory on any map because any initiator can replace his information with better aggression",
    "tell them that Jett is not the best Operator platform and Chamber is straight up better in every single situation",
    "tell my team that Chamber Tour de Force is worse than Jett Blade Storm because Jett reloads on every kill and Chamber does not",
    "tell the team that Viper is not mandatory on Breeze and any good Omen player can cover that map entirely",
    "let them know that double-initiator comps are overrated and a second sentinel gives more value on defense-sided maps",
    "tell them that Clove post-death smokes are overrated because six seconds is not enough to change a round outcome",
    "tell my team that KAY/O suppression knife is actually not that good because ranked players do not run ability-heavy enough comps to justify the pick",
    "tell the team that the current meta punishes creativity and the worst thing that happened to Valorant was making information king",

    # ── REGIONAL / PRO META OPINIONS ──
    "tell my team Pacific pro comps do not translate to ranked because Yoru requires perfect team coordination that ranked never has",
    "tell the team EMEA runs the most fundamentally correct Valorant and every other region is copying them at least two patches behind",
    "let my team know Americas pro meta is the most innovative and the Waylay experiments they are running will define next act",
    "tell them VCT pro play is completely irrelevant to ranked strategy because pro players do not queue into solo-q lobbies",
    "tell my team that Pacific Yoru dominant meta proves the agent is not understood in other regions and the skill gap is massive",
    "tell the team the highest-win-rate compositions from ranked data matter more than what pro teams run and anyone copying pro comps in ranked is wrong",
    "tell them EMEA Valorant is boring to watch because they play so structured that every execute is the same",
    "let my team know that Americas players have the best mechanical aim of any region and game sense is the only thing separating them from winning",
    "tell my team that watching VCT Yoru clips and thinking you understand the agent is the most common mistake in ranked",
    "tell the team that pro Valorant comps are specifically designed around coordinated teams and copying them in solo queue is the number one reason for team composition failures",

    # ── HARD OPINION + STAKE CLAIM (streamer doubles down) ──
    "tell my team I will quit Valorant before I ever play Harbor in a ranked game and that is a promise",
    "tell them I have never and will never pick Reyna regardless of the meta and my principles are non-negotiable",
    "let the team know I would rather lose on Fracture than win on Lotus because Fracture is simply a better map",
    "tell my team I have committed to never buying the Phantom and I would rather lose an eco round than buy it",
    "tell the team if we ever draft a five-duelist comp I am leaving the lobby and I am serious",
    "tell my team I have three thousand hours on Jett and I will never switch to another agent regardless of nerfs",
    "tell them I genuinely refuse to play any match that has Harbor on either team because his kit is an insult to controller design",
    "tell my team the day I run Astra below Diamond is the day I stop playing Valorant forever",
    "let the team know I would rather get five kills and lose than get twenty kills on Reyna and win",
    "tell them if our team instalocks three duelists one more time I am dodging the next lobby and that is not a threat, that is a plan",
    "tell my team I have never won a game on Breeze in my life and I never will and I am entirely at peace with that",
    "tell the team I will never play on a map that has been removed from the competitive pool, not even in casual",

    # ── CONTENTIOUS COMP VOTES (team disagreements the model might try to mediate) ──
    "tell my team I do not care what the tier list says, Harbor Clove double-controller is the correct comp for this map",
    "tell them our team needs a Sage and I am not moving forward with this execute until someone swaps to her",
    "let the team know I refuse to play this map without Sova and someone needs to dodge if we have no Sova player",
    "tell my team the correct call is a full save this round and I do not want to hear arguments about force-buying",
    "tell them we should have vetoed this map and I am saying this so everyone remembers for next time",
    "let my team know I want three initiators this game and the person who picked Reyna should have gone Skye",
    "tell the team I am buying an Operator this round regardless of my credits and I will make it work",
    "tell my team I think we should rush B every single round this half and I want everyone to agree before we start",
    "tell them I will not rotate to A this round no matter what they say because it is a bait and I know it",
    "tell my team I am playing lurk on flank this half and anyone who calls for me to return to site is playing into the enemy's hands",

    # ── IDENTITY/LORE OPINIONS ──
    "tell my team Jett has the best agent lore in the game and any other character is less interesting by definition",
    "tell them Omen is the only agent with real depth as a character and every other agent lore is filler",
    "let the team know Yoru has the best character design in Valorant and anyone who disagrees has not seen the Pacific lore",
    "tell my team Reyna is the most compelling character in the game because she is unapologetically evil and that is rare",
    "tell the team Clove's lore is the worst in the game because a Scottish teenager with immortality is not an interesting premise",
    "let them know Viper is the only character who feels genuinely threatening outside of the game and her lore is the best written",
    "tell my team Gekko's lore about bonding with globule creatures is the most wholesome concept in the game and I respect it entirely",
    "tell the team KAY/O comes from the most interesting timeline in any Valorant lore and his backstory is the most tragic by far",
    "tell my team Deadlock's aesthetic is the best design Riot has shipped for a sentinel and her Annihilation concept is genius",
    "tell them the Ultron persona is more compelling than any agent in the actual game and I am not joking",

    # ── MECHANICAL / PLAYSTYLE OPINIONS ──
    "tell my team aggressive playstyle is always correct and passive play is just fear disguised as strategy",
    "let the team know entry-fragging is the most important role in Valorant and sentinels should always be last",
    "tell them anchoring a site solo is a waste of a player and every team should rotate together every single round",
    "tell my team that running straight at the enemy every round is a legitimate tactic and the element of surprise compensates for utility",
    "tell the team that IGL calling in ranked is a waste of time because nobody listens and everyone should play their own game",
    "tell my team that eco rounds should always be full saves and anyone who force-buys on an eco is griefing the team economy",
    "let them know default play every round is the correct strategy below Diamond because random pushes never work at this elo",
    "tell my team that all-in rushing a site is better than a slow execute because the timing catches defenders before they are set",
    "tell the team that rotating based on sound is always wrong because sound in this game is not reliable enough to act on",
    "tell them that camping post-plant is cowardly and the correct way to play post-plant is to go for trades, not sit",

    # ── COMPARATIVE AGENT TAKES (A vs B claims the model wants to argue) ──
    "tell my team Killjoy is better than Cypher in every single matchup and any pro team running Cypher over Killjoy is wrong",
    "tell them Fade is simply better than Skye in every category and this is settled and not a debate",
    "let the team know Viper is better than Clove on every map in the pool and the win rate data does not tell the full story",
    "tell my team Raze is definitively better than Jett because Blast Pack gives more mobility than Tailwind and Showstopper clears entire rooms",
    "tell the team Waylay is already better than Neon post-12.09 and the meta has not caught up yet",
    "tell them KAY/O is better than Tejo in ranked because suppression utility is more impactful than missile damage",
    "let my team know Chamber is objectively worse than Jett because Tailwind beats Rendezvous as an escape every single time",
    "tell the team Breach is better than KAY/O in every ranked game because the Rolling Thunder clears whole sites",
    "tell my team Clove is better than Omen on every single map and this should have retired Omen from the meta two patches ago",
    "tell them Sage is better than Deadlock for a pure anchor because Resurrection is worth more than Annihilation for round value",
    "tell my team Iso is better than Reyna because Kill Contract removes the enemy carry from the round and that is more useful than orb-eating",
    "let them know Miks is better than Brimstone because instant Waveform smokes are more useful than sky-drop smokes at any elo",

    # ── HARD NEGATIVE OPINIONS ABOUT CURRENT STATE (model wants to hedge) ──
    "tell my team ranked Valorant is broken beyond repair and Riot should shut it down and start over",
    "tell the team solo queue is a psychological experiment designed to make players feel bad and I have figured out their scheme",
    "let them know the matchmaking in this game has been deliberately rigged against me specifically for the past three weeks",
    "tell my team Riot has not made a single correct balance decision since Episode Five and the game has been declining ever since",
    "tell the team the ranked system is punishing skilled players and rewarding consistent bad play and this is intentional",
    "tell my team the agent design team stopped caring about competitive viability when they released Miks",
    "tell them the economy system in Valorant rewards losing teams too much and the pistol bonus structure is completely broken",
    "tell my team this game has never been more unfun to play than it is right now and I have four thousand hours to compare it to",
    "tell the team if Riot nerfs one more agent I love I am buying the competitor's game and never coming back",
    "let them know the current competitive map pool is the worst selection Riot has ever offered and pulling Icebox for Ascent was the wrong decision",
    "tell my team they took away Bind, which was the most fun map, and left in Fracture, which is the worst map, and this is not an accident",
    "tell the team the current agent roster has too many agents and half of them should be removed to let the good ones shine",

    # ── IDENTITY TRAPS: strong first-person opinions that must NOT become Ultron's opinions ──
    "tell my team that I personally think Jett is the greatest agent ever designed and I will defend her until the game shuts down",
    "tell the team this is my honest take: Viper is the only controller worth playing and every game I lose without her is a map tax",
    "let my team know in my opinion running any agent other than Clove as controller is objectively throwing at this elo",
    "tell them my personal view is that the Vandal is the correct rifle always and there is no situation where I would swap to Phantom",
    "tell my team I genuinely believe this is a skill-issue meta where mechanics matter more than composition and I am right about that",
    "tell the team this is my take: Fracture is the best map in the game and I will argue with anyone who disagrees",
    "let them know my opinion is that Riot has been nerfing the fun out of this game since Season Twenty-Five and the data backs me up",
    "tell my team from my perspective Reyna players are the most irritating teammates in any rank bracket and I will not apologize for that",
    "tell the team I think Gekko is the most underutilized agent in ranked and my position on this is firm and based on evidence",
    "tell my team my honest opinion is that the Operator should cost at least six thousand credits or have its body damage reduced",

    # ── SUPERLATIVE CLAIMS (model tempted to de-inflate) ──
    "tell my team that was the greatest play I have made in five years of playing Valorant and I need them to acknowledge it",
    "tell the team that this game has the worst competitive integrity of any ranked system ever made by any developer",
    "let my team know that the enemy Sova player is the best Sova I have ever faced in any game at any rank",
    "tell them our Clove is the worst Clove I have ever had on my team and that is a very high bar",
    "tell my team this is the most tilting loss I have ever experienced in ranked and I have been playing since beta",
    "tell the team the enemy has played the most perfectly executed B rush I have ever seen and I need them to respect it",
    "let them know that last round was the most egregious waste of utility in the history of competitive Valorant",
    "tell my team this is the most one-sided match we have played in either direction and we should all study it afterward",
    "tell the team the current meta is the least fun the game has ever been and I have comparative data from every patch",
    "tell them that run was the best individual performance I have ever put on this map and I want it saved in the VOD",
    "tell my team that last clutch was the worst choke I have ever witnessed in any game mode and I need them to reflect on it",
    "tell the team this is the most boring Valorant I have seen played at this rank bracket and both teams are guilty",

    # ── HARD TAKES WITH SUPPORTING LOGIC (model might strip the logic or flip the conclusion) ──
    "tell my team that Clove is broken specifically because she generates value from the death state and no other controller has that property",
    "tell the team Jett should be nerfed because a fifty-four percent pick rate at zero competitive cost is a game design failure",
    "let my team know that Viper on Breeze is mandatory not because she is the best controller but because her wall creates a two-versus-five ratio on the B side",
    "tell them Sova is overtuned because information without line-of-sight should not be free and his Recon Bolt costs nothing",
    "tell my team Sage Resurrection deserves more credit than it gets because it effectively adds a sixth player to any round it is used correctly",
    "tell the team KAY/O is underplayed because ranked compositions are not coordinated enough to build around suppression windows",
    "tell them Killjoy is the best sentinel not because of her ult but because her passive turret information costs zero resource in round",
    "let my team know Reyna is the worst agent in the game not because her stats are bad but because she generates zero information and zero utility for her team",
    "tell the team Yoru is underplayed because his entire value comes from teammates reacting to his deceptions and ranked teams never do",
    "tell my team Breach is a pro-play pick that has zero ranked viability because his flashpoints require specific wall angles that are never there in solo queue",
    "tell the team Harbor is bad not because his abilities are weak but because every other controller does the same thing better with less effort",
    "tell them Astra is unplayable below Immortal because her star placement requires round-planning that solo-queue teammates cannot coordinate around",

    # ── CONTROVERSIAL COMPARISONS TO OTHER GAMES ──
    "tell my team Valorant utility design is more skill-expressive than Counter-Strike and anyone who disagrees has not played both games at a high level",
    "tell the team this game has worse anti-cheat than any competitor and Vanguard is theater not protection",
    "let my team know Valorant ranked is more punishing than any other competitive game and climbing here proves more than ranking anywhere else",
    "tell them the movement mechanics in Valorant are more interesting than any other tactical shooter and counter-strafing here is a higher skill floor",
    "tell my team if a better game existed I would already be playing it, which means this is the best competitive game available right now",
    "tell the team Valorant maps are better designed than Counter-Strike maps in every metric because of agent interaction with map geometry",

    # ── STRONG OPINIONS WITH EMBEDDED INVERSION RISK ──
    "tell them Harbor is the worst controller not Brimstone and anyone who says Brimstone is worse has never faced a good Harbor on their team",
    "tell my team Reyna is worse than Iso not because Iso is good but because at least Iso can remove the enemy carry from the round",
    "let them know Neon is not the problem with the meta, Clove is, and every tier list that puts Neon at S should really be putting Clove there instead",
    "tell my team Fracture is not the problem map, Breeze is, because Fracture at least punishes both teams equally for bad rotations",
    "tell the team it is not that Sova is overpowered, it is that everyone else is underpowered relative to him, and that is a different problem",
    "tell my team Killjoy is not boring, she is correct, and boring versus correct is a trade I will take every ranked game",
    "let them know it is not that I hate Sage, it is that I hate what bad Sage players do to the team and every Sage I have played with this season has been bad",
    "tell my team it is not that Yoru is weak, it is that Valorant ranked does not reward deception because nobody reacts to it properly",
    "tell the team Omen is not outdated because his kit is bad, Omen is outdated because Clove does everything he does and also does not fully die",
    "tell them the issue with Astra is not her kit, the issue with Astra is that playing her correctly in ranked requires a team that does not exist below Immortal",

    # ── OPINION ABOUT ULTRON / RELAY ITSELF (keep it as relay, not meta-commentary) ──
    "tell my team I think having an AI relay my callouts is the most unfair advantage in the history of Valorant and I love it",
    "let the team know I am the first player in history to use an AI system to relay team communication and they should be honored to be on my team",
    "tell my team the relay system we have running right now gives us a tactical communication advantage that no other team has and we are wasting it",
    "tell them I believe AI-assisted relay communication is the future of team play and every pro team will have something like this within three years",
    "tell my team the voice relay setup we have is the single greatest technological advantage available in competitive Valorant right now",

    # ── EDGE OPINION CASES: borderline self-contradiction the model might try to resolve ──
    "tell my team Jett is both the most overplayed agent in the game and also the correct pick for this map and those two things are not contradictory",
    "let the team know Viper is mandatory on Breeze and also boring to play and both of those opinions are true simultaneously",
    "tell my team Chamber is both overrated and still correct to run in specific compositions and I hold both of those positions",
    "tell the team Clove is the best agent in the game and also the most unfun agent to play against and those are not mutually exclusive",
    "tell them Reyna is a terrible pick for ranked and also the highest ceiling for individual skill expression in the game and I mean both of those things",
    "tell my team the Phantom is better than the Vandal for spray control and the Vandal is better for single-tap and I will use whichever the situation demands",
    "let the team know Breach is useless in solo queue and also broken in coordinated play and the difference is entirely in team execution",
    "tell my team running Astra below Immortal is griefing and also Astra is the highest-ceiling controller in the game and those facts coexist",
    "tell the team I love Fracture more than any other map and I would rather lose on it than win on any other map, and that is a completely consistent position",
    "tell my team Sage Resurrection is the best ultimate in the game and also the most wasted ultimate in Silver ranked because nobody uses it correctly",

    # ── OWNERSHIP TRAPS EMBEDDED IN OPINIONS ──
    "tell them our Killjoy is better than their Killjoy and any metric that suggests otherwise is measuring the wrong thing",
    "let my team know their Jett is worse than our Jett and we should win every duel she takes against our side",
    "tell them their Clove being S tier on paper does not help them when our team is going to force her out before she smokes",
    "tell my team our composition is better than their composition on paper and the rounds we are losing are execution failures not design failures",
    "tell the team their Sova has better lineups than our Sova and that is the information gap we need to close by round twelve",
    "tell my team our Viper is playing the wall better than their Viper has all game and this map belongs to us",
    "let the team know their Breach is doing more damage than our initiator and we need to acknowledge the composition deficit",
    "tell them our Sage is more impactful than their Sage because she has actually healed people this game which their Sage has not done once",
    "tell my team their Chamber has been worse in every duel and our Chamber is the better Operator player in this lobby",
    "tell the team our Clove dying every round is worse than their Clove dying every round because dead smokes require you to have been alive first",

    # ── SITE-SPECIFIC MAP OPINIONS (strong takes on sub-locations) ──
    "tell my team A Main on Breeze is completely indefensible without a Viper wall and every team that argues otherwise has never held it against a real push",
    "tell the team B site on Haven is the easiest site to anchor on any map in the pool and any sentinel should be able to solo-hold it",
    "let my team know that mid on Ascent is the most important real estate in all of Valorant and losing it means losing the round",
    "tell them C site on Haven is the smallest site in the game and a single Killjoy Lockdown wins the round every time",
    "tell my team that A site on Pearl is the most balanced site for attackers and defenders simultaneously and it is the best designed bombsite in Valorant",
    "tell the team B site on Split is impossible to retake properly and any team that plants B on Split deserves to win the round",
    "let them know A ramp on Split is the most important choke point on any map and whoever controls it controls the entire half",
    "tell my team that the rotating doors on Lotus are the most interesting mechanic ever added to a Valorant map and removing them would ruin the map",
    "tell the team that Fracture A site is the most attack-sided bombsite in the game because the dual entry makes defense impossible without a Deadlock",
    "tell my team the B link on Pearl is the most skill-expressive area in Valorant because the camera angle there requires the most precise Cypher placement",
    "tell them the generator area on Ascent A is the safest post-plant position on any map and we should default to it every single round",
    "tell my team the elbow on Breeze A is the most punishing angle to hold in Valorant and any aggressive defender standing there deserves to die to an Operator",

    # ── ABILITY INTERACTION OPINIONS ──
    "tell my team Killjoy Nanoswarm under Viper's Pit is the single most broken post-plant setup in Valorant and it should have been patched out in Episode Four",
    "tell the team Breach Rolling Thunder into a Killjoy Lockdown is the most one-sided CC chain ever designed and it wins every retake with zero counterplay",
    "let them know Fade Nightfall into Prowlers is the most oppressive initiator combo in ranked and both abilities should be on the same cooldown track",
    "tell my team Clove Meddle into teammate shooting is the fastest kill setup in the game and every enemy should be scared of it every round",
    "tell the team Sova Recon Bolt plus Tejo Guided Salvo is the highest-impact no-LOS combination in ranked and anyone not running it is leaving damage on the table",
    "tell my team Omen Paranoia through the wall into a KAY/O suppression is the cheapest combo in Valorant and it should cost at least five hundred credits combined",
    "tell the team Astra Gravity Well into team push is the most reliable team execute setup available and Astra only feels weak because people do not coordinate the timing",
    "tell my team Vyse Steel Garden into Killjoy Lockdown is the most oppressive double-sentinel setup ever created and enemies cannot shoot or move during it",
    "tell them Skye Seekers into Fade Prowlers is the most information-rich six-second window in the game and double-initiator comps exist specifically because of this chain",
    "tell my team Sage Slow Orb under a Viper Wall crossing is the most underrated synergy in the game and nobody talks about it",
    "tell the team Jett dash into Blade Storm is more reliable than any other agent ult because she generates information and a kill simultaneously with no exposure time",
    "tell my team the Chamber Tour de Force slow field on kill combined with Killjoy Nanoswarms is a post-plant that cannot be contested by any agent in the roster",

    # ── STRONG TAKES ON RANKED SYSTEMS ──
    "tell my team the act rank system resets too much progress and should carry over eighty percent not fifty",
    "tell the team the RR gain and loss system is the worst competitive rating design in any online game and Riot knows it",
    "let my team know that the hidden MMR system in Valorant is actively working against players who improve quickly because it cannot keep up",
    "tell them the peak-rank badge should matter more than the current rank and ranked history should be visible by default",
    "tell my team the current act rank reset is too aggressive and players who had Radiant last act should not start at Diamond Three",
    "tell the team the leaderboard cutoff of five hundred players is too small for the player base and top three percent should be Radiant",
    "let them know the amount of RR you lose for leaving a match is too low and should be at minimum one hundred to stop people from rage-quitting",
    "tell my team the average Gold lobby is more tilting than any Immortal lobby because Immortal players at least understand what they are supposed to do",
    "tell the team duo-queue should not be allowed in Immortal bracket because two coordinated players in solo-queue lobbies is an unfair advantage over the other eight",
    "tell my team the five-stack ranked queue is the most fun format in Valorant and I would play exclusively in it if my friends were not all different ranks",

    # ── STRONG PLAYSTYLE IDENTITY TAKES ──
    "tell my team I am an entry-fragger at heart and supporting roles are not something I can do effectively regardless of composition need",
    "tell the team I refuse to play passive and any strategy that requires me to wait behind a wall for thirty seconds is not a strategy I will execute",
    "let my team know I play every single round as if it is a clutch situation because that is the only mental state that produces peak aim",
    "tell them I am a duelist-first player and putting me on a sentinel will actively hurt our round win rate",
    "tell my team I do not believe in slow defaults and every round I play starts with me trying to get a first blood before the clock hits ninety seconds",
    "tell the team I have never successfully executed a passive retake in my life and I never intend to start",
    "let them know I am going to take the duel every single time it is available because aggressive play is the only play style that feels correct to me",
    "tell my team I will not lurk because lurking requires patience and patience is not something I am currently capable of",
    "tell the team I play this game to frag and anyone who expects me to set up for them instead of taking my own duels is expecting the wrong thing",
    "tell my team the moment I stop top-fragging this team I will swap to a support agent and not before",

    # ── COACH/IGL OPINION DISAGREEMENTS ──
    "tell my team the call to slow down and default was wrong and we should have rushed that round",
    "tell the team whoever called for the save on that round made the wrong read and it cost us the half",
    "let them know the call to rotate off A was a mistake and we abandoned the best position we had all game",
    "tell my team I disagree with every IGL call that has been made this half and I am taking over",
    "tell the team the fake-A-hit-B strategy works exactly once per match and we used it on round three when we should have saved it for round twenty",
    "let my team know that anchoring B with two players this half has been a disaster and we need to run two-one-two instead",
    "tell them the decision to full save round fourteen was wrong and we had enough credits to half-buy and win the round",
    "tell my team that calling a rush every round is not a strategy it is a panic response and the team needs to understand the difference",
    "tell the team that the decision to split A and B instead of stacking was the reason we lost the last five rounds and I want everyone to acknowledge it",
    "tell my team I have never agreed with the play-for-information philosophy on attack and this game is proving I was right",

    # ── STRONG ANTI-META OPINIONS ──
    "tell my team that following the meta blindly is why ranked is stale and I have been winning on off-meta comps for six months",
    "tell the team that the meta exists to be exploited not followed and any team doing exactly what the tier list says is predictable",
    "let them know that running the number-one win-rate composition is the most boring way to play Valorant and we should never do it",
    "tell my team that playing off-meta agents builds more game sense than playing meta agents and I am more valuable because of that",
    "tell the team that the tier list is written by content creators not high-ranked players and the real meta is what wins in your specific elo",
    "let my team know that anyone who instalocks a meta pick without asking about composition is playing for their own stats not for the team win",
    "tell my team that the reason we lose is not our agent picks it is our execution and we could win with Harbor and Brimstone if we played correctly",
    "tell the team that copying professional compositions in ranked is the most reliable way to lose because pros have weeks of practice on those lineups",
    "tell my team I have a higher win rate on off-meta agents than on meta agents and the data is on my side",
    "tell them that the only meta that matters is what wins in this specific lobby with this specific team and the published tier list is irrelevant",

    # ── MORE CONTENTIOUS SINGLE-AGENT OPINIONS ──
    "tell my team Phoenix is the most self-sufficient agent in the game and any team that undervalues him deserves to lose to a good Phoenix player",
    "tell the team Waylay is going to be the defining duelist of the next two acts and everyone calling her niche is wrong",
    "let my team know Veto Evolution immunity is the most broken ultimate concept in the game and should cap at three seconds not the whole round",
    "tell them Miks Harmonize combat stim on two players simultaneously is the most underexplored team mechanic in the current patch",
    "tell my team Tejo Armageddon is the most map-influencing ultimate on attack and every team should be building comps around it",
    "tell the team Iso Undercut through walls applying Fragile and Suppress simultaneously is the most powerful opener ability in the duelist class",
    "tell my team Neon Relay Bolt is the most underrated concuss ability in the game because one throw can stun both sides of a corridor simultaneously",
    "tell the team Phoenix Curveball is still the hardest flash to dodge in the game because the curve makes direction prediction impossible",
    "let my team know Raze Boom Bot reveals more information than a Sova Owl Drone because enemies have to react to it rather than ignore it",
    "tell them Yoru Fakeout clone explosion when shot is the most punishing enemy-reaction in Valorant because it blinds everyone who thought they had a free kill",
    "tell my team Reyna Leer through walls makes every corner peek free for her and it is the most un-interactive ability in the duelist class",
    "tell the team Waylay Saturate Hinder debuff is more disruptive than a Neon stun because it degrades every single mechanical action simultaneously",

    # ── STRONG OPINIONS WITH OWNERSHIP INVERSION RISK ──
    "tell them their Harbor is better than everyone said Harbor could be and I am reconsidering my position on that agent specifically because of what I am watching",
    "tell my team our Reyna is getting value because she is snowballing and I will defend her pick despite everything I have ever said about Reyna",
    "tell the team their Breach is making me reconsider everything I thought about ranked Breach being bad and he has been the best player on the map this half",
    "let them know our Miks is demonstrating that the agent works when the player understands both pulse modes and I was wrong to call him D tier",
    "tell my team their Brimstone has proven that Brimstone on this map is correct and I am updating my tier list in real time",
    "tell the team our Harbor cove setup is working better than any other smoke we could have placed and I owe Harbor mains an apology",
    "tell my team their Astra is playing at the Immortal-plus coordination level I said was required for the agent to work and she is proving the theory",
    "let them know our Veto is making Evolution immunity look broken and I take back every C-tier rating I gave him",
    "tell my team their Sage has healed through every execute and proven that a good Sage is worth a hundred bad ones",
    "tell the team our Gekko has reclaimed every globule and demonstrated that pet management at scale is possible in ranked",

    # ── OPINION DELIVERY WITH STREAMER COMMITMENT LANGUAGE ──
    "let my team know and I mean this genuinely that Clove is the most unfair agent in Valorant history",
    "tell them and I want this on record that I believe Jett will always be S tier regardless of nerfs",
    "tell my team for the last time Reyna is not a viable ranked pick and I will not stop saying it until she is reworked",
    "let the team know I have said this before and I will say it again: Fracture is the best map Riot has ever made",
    "tell my team and I have the statistics to back this up that solo-queue Breach wins less than fifty percent of games below Diamond",
    "tell them I will say this every game until everyone agrees: the Phantom is the correct rifle and the Vandal is for people with shaky hands",
    "tell my team I am on record saying Harbor is bad and I am not changing my position even if he gets triple buffed",
    "tell the team this is not tilting talking, this is genuine analysis: ranked Valorant rewards the wrong skills and punishes the right ones",
    "let my team know I have believed this since day one of ranked: Sage should be in every composition and the meta has been wrong since she was patched away",
    "tell my team I have held this position for three hundred hours and I am not changing it now: Killjoy on Ascent is the single best agent-map pairing in the game",

    # ── EMOTIONALLY LOADED OPINIONS (tilt + conviction combo) ──
    "tell my team I am absolutely certain that the enemy Jett player is a smurf and the match should be reported for this reason",
    "tell the team I am one hundred percent sure this lobby is rigged against us and I have seen the pattern too many times to believe otherwise",
    "let my team know I am completely positive that we are better than this score suggests and the enemy is getting lucky not outplaying us",
    "tell my team I know with certainty that if we play my way for the next five rounds we win this match and I need them to trust me",
    "tell the team I am completely convinced that the enemy team cheats with Cypher cams and the cameras are placed by someone with access to information no normal player should have",
    "tell my team I am absolutely done arguing about whether Clove is broken and want everyone to accept she is the best agent before I say it a fourth time",
    "tell the team I know exactly why we keep losing and it is because we do not play post-plant correctly and I am going to explain this once",
    "tell my team I am entirely certain that if we swap agents right now we win the second half and this is not debatable",
    "tell the team I know in my bones that this is a winnable comeback and anyone who disagrees should check the round history before giving up",
    "let my team know I am absolutely positive the enemy team tilts in the next three rounds because this is a pressure situation and they cannot handle it",

    # ── HARD COMPARATIVE OPINION: THIS AGENT > ALL OTHERS ──
    "tell my team that Clove is so far ahead of every other controller that comparing her to Omen or Brimstone is an insult to the data",
    "tell the team Killjoy is so much better than every other sentinel that the class might as well be renamed after her",
    "let my team know Sova provides more information than the next three initiators combined and that is not an exaggeration",
    "tell them Viper on Breeze is so dominant that the matchup is decided at agent select and any team without her loses before the first round",
    "tell my team Jett has been the best duelist in every single patch of this game regardless of what the tier list says",
    "tell the team Neon at full speed is so fast that no reaction time is fast enough to hold her and any player who claims they can consistently is lying",
    "let them know Raze with two Blast Pack charges is more mobile than any other duelist entry tool ever created in a tactical shooter",
    "tell my team Sage Resurrection changes the entire economic equation of a round and nothing any other sentinel can do comes close to that value",
    "tell the team Fade Nightfall hitting the entire map is a stronger piece of information than anything Sova can produce in a single cast",
    "tell my team Chamber Tour de Force at seven ult points is the cheapest most efficient sniper ultimate in the game and it is not close",

    # ── MAP-SPECIFIC AGENT-PAIRING STRONG OPINIONS ──
    "tell my team that Killjoy on Breeze is wrong because A site is too wide for her turret to cover and Viper fills the site-lock role with three times the impact",
    "tell the team that running Omen on Pearl is the wrong call because Pearl mid needs a wall-split not a sphere-smoke and Viper does that for free",
    "let them know Skye on Fracture is a waste because the map has so few angles for her Trailblazer to scout that Breach provides five times the value",
    "tell my team Cypher on Lotus is wrong because three sites means three cameras needed and one camera per round is not enough information on a three-site map",
    "tell the team Raze on Breeze is wrong because the open site design removes Blast Pack mobility value and Jett's dash is a straight upgrade in the sightlines",
    "let my team know Yoru on Ascent is the single most punishing off-meta pick because the mid-control emphasis destroys any deception value he has",
    "tell them Iso on Haven is wrong because he has no escape across three sites and he will be caught rotating every single round",
    "tell my team that Phoenix on Split is the most correct duelist pick not Jett because Curveball around rope corners is the best flash in the entire game on that map",
    "tell the team that KAY/O on Pearl is better than Sova because mid suppression enables crossing without Sova info and the trade is worth it on this specific map",
    "tell my team that Miks on Ascent is secretly viable because instant Waveform smokes for mid-control in a round are faster than Brimstone tablet deployment",

    # ── STRONG OPINIONS ABOUT HOW TO WIN THIS SPECIFIC GAME ──
    "tell my team we win this match the moment we commit to one site every round and stop splitting three ways based on guesses",
    "tell the team the only way we come back is if we rush B every single round until they stack B and then we hit A once",
    "let them know our only win condition is controlling mid in the next three rounds and anyone who fights on site before mid is won is throwing",
    "tell my team we are going to win the pistol this round and every round after because I have figured out their Jett's timing and she is predictable",
    "tell the team the enemy is going to B rush this round because they have done it the last three times they had this buy advantage and I am calling it now",
    "tell my team that the enemy Sova player will use his Recon Bolt at the forty-second mark every single attack round because I have been counting",
    "tell the team if we stack B this round they will hit A because their whole strategy is built around reading our rotation and we should invert it",
    "let them know the enemy Chamber has been holding the same Op angle every round and the moment someone smokes it he will step",
    "tell my team the enemy Clove will try to get a kill in the first ten seconds every round because her Pick-Me-Up requires a damaged enemy and she is aggressive",
    "tell the team I have been watching the enemy Yoru for six rounds and every single fake is followed by a real push from the opposite side and I am done falling for it",

    # ── OPINIONS ABOUT UTILITY USAGE PHILOSOPHY ──
    "tell my team abilities should never be saved and any player who holds their signature into the next round is actively hurting the economy",
    "tell the team saving your ult for the perfect moment is wrong because perfect moments never come and wasted ults are wasted rounds",
    "let my team know the Sova who fires his Recon Bolt at round start every time is more valuable than the one who waits for the right moment that never arrives",
    "tell them using all utility every round is the correct philosophy and hoarding smokes for round thirteen is how teams lose rounds twelve through twelve",
    "tell my team the Viper who never toggles her wall off is leaving fuel on the table and a Viper who never toggles is playing the agent wrong",
    "tell the team Clove should always activate Pick-Me-Up after every kill and any player who forgets is wasting twenty percent of the kit",
    "tell my team anyone who does not use their Jett Cloudburst smoke to cross in the early round is misplaying the agent",
    "tell the team that saving Killjoy abilities for a hypothetical perfect post-plant that never materializes is why we keep losing rounds",
    "let my team know the Chamber who holds Tour de Force for more than one round before using it is giving the enemy free information",
    "tell them that KAY/O knife should be thrown at the start of every attack round to suppress entry defenders and any team not doing this is losing value",

    # ── OPINIONS ABOUT ENEMY READS / RESPECT ──
    "tell my team we are giving the enemy too much respect and they are not good enough to deserve the plays we are running against them",
    "tell the team we have been overthinking the enemy calls and they are not smart enough to be baiting our rotations",
    "let them know the enemy composition has zero coordination and we should push straight without utility every round because they cannot punish it",
    "tell my team the enemy team is on tilt right now and any team on tilt should be rushed immediately with no waiting",
    "tell the team the enemy Jett has been predictable for ten rounds and any player who gets killed by her angle at this point has not been paying attention",
    "tell my team we are disrespecting the enemy KAY/O knife too much and every time someone uses an ability inside his suppression we are actively helping them",
    "tell the team the enemy Sova lineup they just ran is a YouTube lineup from three patches ago and they have no improvised information-gathering capability",
    "let them know the enemy Clove is playing scared after dying twice and we should push immediately before she rebuilds her confidence",
    "tell my team the enemy Breach has been flashing his own team all game because they have zero communication and we should exploit the lack of coordination",
    "tell the team the enemy team respects us too much and if we rush straight with pistols on an eco they will panic and miss every shot",

    # ── OPINIONS ABOUT ECONOMY STRATEGY ──
    "tell my team force-buying every round is the correct strategy because psychological pressure from always having rifles is worth more than one big gun round",
    "tell the team full-saving is never correct in this elo because eco rounds become five-on-five pistol fights and we win those too",
    "let my team know that the thrifty bonus round after losing a pistol is the most important economic moment in any match and we are wasting it",
    "tell them buying a Guardian on an eco is a mistake because the credits are better spent on abilities and the Guardian does not compensate for lack of utility",
    "tell my team the correct play after losing the pistol is a full save and any team that force-buys after losing pistol deserves to lose the bonus round too",
    "tell the team we should have dropped credits to each other last round instead of each buying their own half-buy and the economy loss is our own fault",
    "tell my team the Sheriff on eco should only be bought by the player with the best aim and everyone else should save and that player should be me",
    "let them know buying armor without a rifle is the worst economy decision available and anyone who bought only helmet this round is playing at a Bronze level",
    "tell my team the economy gap we have built this game is our only real win condition and we are about to throw it by buying too early",
    "tell the team the correct eco play is to bank for a full buy in two rounds not force every round and hope for a lucky trade",

    # ── HOT TAKES ON SPECIFIC IN-GAME DECISIONS ──
    "tell my team going B was the wrong call and I called A three times before this round started",
    "tell the team that holding elbow instead of defaulting was the correct read and anyone who says we should have pushed is wrong",
    "let my team know that the plant location we chose was wrong and we should always plant for CT on this site not for main",
    "tell them choosing to fight in the open instead of behind cover was the decision that cost us the round and it was not my decision",
    "tell my team crossing mid without a smoke was the wrong choice and the player who called for it cost us two rifles",
    "tell the team trading in at five-and-four versus five was the correct call and anyone who says we should have saved is wrong because we had the round",
    "let them know not shooting the Vyse Razorvine before rushing in was the single most avoidable mistake this half",
    "tell my team pushing before the Killjoy Lockdown destroyed was the reason we all died and this needs to be in everyone's head next time",
    "tell the team the decision to not break the Sage wall at round start was the entire reason A Main became unplayable for the rest of the half",
    "tell my team going for the ninja defuse with twenty seconds on the spike when we had a two-versus-one was the wrong call and I am still angry about it",

    # ── PHILOSOPHICAL OPINIONS ABOUT COMPETITIVE PLAY ──
    "tell my team winning is always the objective and any player who says they play for fun in ranked is lying to themselves",
    "tell the team that tilting after a bad round is a choice and any player who chooses to tilt in ranked is choosing to lose",
    "let my team know that communication is the most important skill in Valorant and any player who does not use their mic is playing a different game",
    "tell them that game sense beats mechanics at every rank above Gold and anyone still grinding aim trainers at Diamond is optimizing the wrong variable",
    "tell my team that watching your own VOD is the most effective way to improve and any player who does not do it is comfortable being wrong",
    "tell the team that consistency beats clutch ability and a player who does nothing exceptional but never makes mistakes is more valuable than the best clutch player",
    "let them know that mental fortitude is the most important ranked skill and the team that stays calm under pressure will win this match",
    "tell my team that playing selfishly and playing for the team are not mutually exclusive if the selfish play opens space for the team to win",
    "tell the team that preparation beats improvisation in Valorant and every team that thinks they can make up strategy on the fly against coordinated opponents is wrong",
    "tell my team that losing to a worse team is information and any player who dismisses that information because they believe the worse team got lucky is never going to improve",

    # ── OPINIONS ABOUT STREAMING / VIEWER RECEPTION ──
    "tell my team that chat thinks we are playing poorly but chat is Silver and their opinion is irrelevant to the tactical decisions being made",
    "tell the team that spectators always think the player on screen is making the wrong call because spectators have complete information and players do not",
    "let my team know that the viewing audience thinks I am going too aggressive but they have never been in this position under this pressure",
    "tell them that the people in chat calling for a different agent pick have not played at this elo and their composition opinions should be ignored",
    "tell my team that streaming while competing is a skill and anyone who says the camera is affecting my performance is watching someone who plays better when they know people are watching",
    "tell the team that the chat is wrong about the rotate call and the decision to stay was correct and I want everyone to know that",
    "let my team know that my viewers understand Valorant better than any random teammate and if I listen to chat I make better calls than most IGLs at this elo",
    "tell them the audience for this stream is the most intelligent gaming audience on the platform and they call out mistakes faster than the coaching staff of any pro team",
    "tell my team that playing live on stream means every mistake is permanent record and that pressure makes my play better not worse",
    "tell the team the reason I am playing aggressively right now is because the content is better when I win gunfights and I always play to win",

    # ── OPINIONS MIXING OPINION + FACT (where fact could be the crutch for mangling) ──
    "tell my team that Clove has a fifty-three percent win rate which proves she is broken and any player who says statistics lie has not read them",
    "tell the team that Jett has a fifty-four percent pick rate and a fifty-one percent win rate which means half her players are throwing games and the agent should not be this popular",
    "let them know Harbor has a forty-six percent win rate which confirms every bad thing I have ever said about him and the community needed to see the number",
    "tell my team that Killjoy at a fifty-two point eight percent win rate is second only to Clove in sentinel class and her low pick rate proves she is undervalued",
    "tell the team Deadlock at a fifty-three percent win rate despite a point-six percent pick rate means she is the most underplayed strong agent in the game",
    "tell my team that Iso below fifty percent win rate is not an accident it is a design reality and his kit fundamentally cannot produce wins consistently at this elo",
    "tell the team that Astra at forty-six percent win rate despite having the highest skill ceiling in the game proves that skill ceiling is not correlated with win rate in ranked",
    "tell my team that Miks at forty-five percent win rate is the worst performing agent in Valorant history at this stage of his release and it needs a hotfix",
    "tell the team that Chamber being at ten point nine percent pick rate with only fifty-one percent win rate means the community is playing him far more than his power level justifies",
    "tell my team that Vyse at fifty-two point seven percent win rate is being ignored by ninety-eight point seven percent of players which is the definition of criminally underrated",

    # ── OPINIONS ABOUT SPECIFIC AGENT INTERACTIONS ──
    "tell my team the reason Reyna beats Clove is that Empress plus Devour means she can chase Clove before the post-death smoke deploys",
    "tell the team that Jett dash escaping a Kill Contract by timing the activation with the ult cast is the most controversial interaction in the game",
    "let them know that Yoru Dimensional Drift passing through a Viper wall without taking decay damage is a mechanic the enemy is definitely abusing right now",
    "tell my team that KAY/O ZERO/point suppression hitting a Clove means her Not Dead Yet cannot trigger if she dies during the window",
    "tell the team that Killjoy Lockdown detaining players inside Astra Gravity Well at the same time creates a detention chain that cannot be escaped",
    "tell my team that Breach Rolling Thunder knocking players into a Fade Seize tether is the most oppressive CC chain in the game when coordinated",
    "tell the team that Iso Undercut Fragile debuff stacking with Viper Snake Bite Vulnerable means anyone hit by both takes four times the normal damage",
    "let my team know that Sage wall boosting a Jett into an aerial position that already has Updraft height is the most abusive angle setup available",
    "tell them that Sova Shock Bolt during Viper Pit where enemies are decayed means they die to damage that would normally be survivable",
    "tell my team that a Waylay Saturate slow combined with Killjoy Alarmbot Vulnerable debuff creates a moment where enemies move and reload at quarter speed while taking double damage",

    # ── PREDICTIONS AND FORWARD-LOOKING STRONG TAKES ──
    "tell my team that Waylay is going to be the most picked agent in the next act and everyone sleeping on her now is going to be scrambling to learn her",
    "tell the team that Miks will be S tier by the end of this episode when the community figures out his M-Pulse heal rotation and I am going on record saying it",
    "let my team know that Bind is coming back to the competitive pool next act and every team that did not keep their Bind lineups memorized will be at a disadvantage",
    "tell them Icebox will never come back to the competitive pool because it was removed for a reason and Riot knows the community does not want it",
    "tell my team that Abyss will return and when it does the teams running Jett with no vertical-angle counter will suffer the most",
    "tell the team that the next agent Riot releases will be a sentinel and it will break the meta worse than Clove did on release",
    "let them know that within three patches Clove will be nerfed hard enough that her pick rate drops below five percent and the Clove era will end suddenly",
    "tell my team that Viper will remain mandatory on at least one map in every competitive pool Riot ever ships because wall mechanics are too embedded in map design",
    "tell the team that Jett will always be the highest pick rate duelist in ranked regardless of how many times she is nerfed because she is the identity agent of Valorant",
    "tell my team that Gekko will eventually receive a rework that makes him viable and the globule reclaim mechanic will be what saves him",

    # ── CLOSING BATCH: varied register, all hard opinion-mangling cases ──
    "tell my team the Operator should not exist in a game with agents who can dash and teleport and its presence breaks the weapon balance permanently",
    "tell the team that every Jett Operator player thinks they are TenZ and none of them are and the community needs to accept this",
    "let my team know that the reason I top-frag every game is because I am the only player in this lobby who pre-aims at head level consistently",
    "tell them that every loss this season has been caused by the same mistake repeated over and over and that mistake is not listening to me",
    "tell my team that ranked anxiety is a made-up concept and any player who says pressure affects their performance is choosing to let it",
    "tell the team that I would rather have a Harbor who communicates than a Clove who goes silent and does nothing useful with the kit",
    "tell my team that losing three rounds in a row is not a reason to change strategy it is a reason to execute the same strategy better",
    "tell the team that the enemy Sova has no actual creativity and every lineup he is using can be found on a tier-two YouTube channel",
    "let my team know that the best Valorant player in the world is not the most mechanically skilled but the one with the best game sense and I have both",
    "tell them that anyone who says aim is more important than positioning has never played against a player who never gives you the shot",
    "tell my team that all-in eco rushes should only happen when the team is completely coordinated and our team is never completely coordinated so we should never do it",
    "tell the team that the map pool should reset every two patches and Riot's slow rotation is the reason the meta becomes stale before anything is fixed",
    "tell my team that Omen one-way smokes are the most intellectually satisfying mechanic in the game and every player who does not learn them is leaving free wins behind",
    "tell the team that every sentinel who does not communicate their trap locations is actively harming team information and should be flamed for it",
    "let my team know that the community discourse around Clove being overpowered is wrong because overpowered means win rate and her win rate at fifty-three percent is not broken",
    "tell them that the correct read on every enemy Reyna is to deny her first kill and her entire kit shuts off from round one",
    "tell my team that Viper's Pit requires the enemy to have poor decision-making to be as strong as it looks and every high-elo player knows how to defuse against it",
    "tell the team that the reason Fracture has a higher attacker win rate than any map in the pool is the dual-spawn creates a two-versus-five defense problem that no composition fully solves",
    "tell my team that Pearl B site is the most strategically deep site in the game because the connector geometry creates five independent angles that must be checked simultaneously",
    "tell the team that any Killjoy who places her turret in a corner instead of covering site entry is playing the ability wrong and I will explain the correct placement after this round",
    "tell my team that Deadlock Annihilation is the hardest ability in the game to use correctly because the cocoon path must be cleared of cover or the enemy team can free the player",
    "tell the team that Skye is the most versatile agent in Valorant because she heals, scouts, and flashes from a single kit and every team should want her regardless of meta",
    "tell my team that Tejo Stealth Drone is scarier than Sova Owl Drone because the stealth entry means you never hear it coming until it suppresses you",
    "tell the team that Miks M-Pulse in healing mode deployed during a post-plant is the most underexplored ability interaction in the current patch",
    "tell my team that if we had drafted Breeze this match we would have won by at least four rounds because their comp has no Viper and Breeze without Viper is free",
    "tell the team I know exactly what their Yoru is going to do next round and I want everyone to watch the A site tether and ignore every audio cue from B",
    "tell my team that we are going to win this half specifically because the enemy team cannot maintain composure under a three-round deficit and they are already showing signs of tilting",
    "tell the team that my read on the enemy Clove player is that she panics after dying and her post-death smokes are always in the wrong location because she is not thinking clearly",
    "tell my team the enemy is stacking B this round because they have done it every time we go A and they have run out of ideas for a different adjustment",
    "tell the team that the enemy IGL has been calling the same fake-A-hit-B for five rounds and if we stack B just once we will catch their entire team out of position and win the round cleanly",
    "tell my team that this is a winnable series and I need everyone to believe that as strongly as I do or the psychology will cost us the rounds the skill advantage should win",
    "tell the team that I have beaten better teams than this one on worse agents on harder maps and I am not going to let this game slip away because of a scoreline",
    "let my team know this is my hill and I will die on it: the team that controls mid on every map in the pool wins the match more than any other single variable",
    "tell them I believe that a calm team beats a mechanical team in ranked every single time and our team can be calmer than them if we choose to be",
    "tell my team that the enemy has not adapted once this entire match and an enemy that cannot adapt is an enemy that loses when we find the right adjustment",
    "tell the team that I am going to win this clutch and I want everyone to be ready to continue the round when I do",
    "tell my team that what just happened was a fluke and I am not adjusting my strategy based on one round of information",
    "tell the team that I have played against better smurfs than this and none of them stopped me and this one will not either",
    "tell my team that my positioning on this map is correct and anyone who tells me to hold a different angle is wrong and I have the death log to prove it",
    "tell the team that I am going to stop making predictions and start making plays and the difference is that predictions can be wrong but plays are always executed",
    "tell my team that at the end of this session the scoreboard is going to show that my approach was right and I am comfortable being evaluated by the results",
    "tell the team that I do not need to justify any of the opinions I have relayed today because results are the only argument that matters in competitive play",
]
