"""Relay corpus: stress_compounds_5fact (kind=relay, ~600 cases).

CHARGE: 4-5 fact compounds — the hardest fact-retention stress for the pipeline.
Every item is a realistic streamer utterance encoding FOUR OR FIVE discrete facts
that the relay must preserve verbatim or faithfully rephrase:
  - count  (1-5 or "all", "both", "last")
  - agent identity (theirs or ours)
  - location callout (exact per-map name)
  - ability / weapon state (used/active/ready/down)
  - ownership or ownership inversion (their X vs our X)
  - HP / armor condition
  - second location or second agent
  - economic state (eco/force/full-buy)
  - directive embedded in the callout

Joiners exercised: "and", "but", "plus", "so", "with", "already", "also",
"while", "she/he/they", comma splice, semicolon, slash, run-on.

Metrics stressed:
  - fact-token retention p50/p95/p99 per category
  - compound zero-fact-loss
  - ownership/subject/directive/first-person inversion
  - hallucinated-specific rate (no invented cooldown numbers)
  - ecobleed (save vs force vs full vs enemy-save)
  - latency (dense compounds pressure the 3B)
"""

ITEMS = [
    # ================================================================
    # ASCENT — 4-5 fact compounds
    # ================================================================
    "two A main, one has the Op and the other used her Jett dash already",
    "their Killjoy has lockdown up and she has a nano on the default plant",
    "three B main, their Sova just shot a recon bolt into site and it hit two of us",
    "one in wine, full health, no armor, and she has her Reyna dismiss still",
    "their Omen teleported into market and he has two smokes left and paranoia",
    "two B, both full buy, their Raze has showstopper and the other one has an Op",
    "our Sage walled B main but their Raze already shot a blast pack at the wall",
    "their Jett dashed to catwalk, she has Op and blade storm up, no smokes used",
    "one holding heaven with Op, he's full health, and their second is in garden",
    "their KAY/O knife hit three of us at mid tiles and his ult is ready this round",
    "two pushing through A door, door is broken, and one of them has vandal plus heavy armor",
    "their Viper toggled the wall off, fuel is low, and her pit ult is up next round",
    "one hiding in hell under heaven, one shot, no armor, and they have spike",
    "their Fade haunted A main, hit two people, and she has two prowlers plus seize left",
    "three rotating CT through garden, their Brimstone already dropped two smokes and molly",
    "their Reyna is in empress, she got two kills, souls are up, dismiss is active",
    "one peeking catwalk with Op, he dashed once already, blade storm is charged",
    "their Killjoy has turret watching mid link and alarmbot on B back and lockdown ready",
    "two B long, one is their Jett with no dash left and a sheriff on eco",
    "their Sova droned through A lobby, hit someone with the dart, and shock is set for heaven",
    "one tucked in workshop with spike, one shot, no armor, and we have no flash",
    "their Clove already died and smoked CT from the grave, post-death smoke is six seconds",
    "three A execute, smokes on heaven and CT, their Breach is faulting through the A main wall",
    "their Astra pulsed mid tiles with nova pulse, it hit two of us, and she has grav ready",
    "one in hell, defusing, and their Viper already molly'd the spike site with snakebite",
    "two market, one has Op and the other is their Skye with two hawk flashes left",
    "their Yoru teleported to B short, he faked it first and now he is real behind us",
    "our Omen stepped into his smoke but their Breach flashed through the wall and lit him 70",
    "one in A peek holding with vandal, 80 HP, and their Killjoy nano is on the generator",
    "their Iso walled B main, his double tap is active, and undercut hit our entry already",
    "two holding B back, one is their Chamber with tour de force, slow field on default plant",
    "their Neon slid into site, she used her relay bolt to stun two of us, overdrive is up",
    "one rotating from garden to tree, she is their Clove, ult not dead yet is charged",
    "their Tejo suppressed three of us with stealth drone, eight seconds, abilities are all locked",
    "two A, one pushed A main, one teleported into garden, their Yoru is playing both angles",

    # ================================================================
    # HAVEN — 4-5 fact compounds (3 sites, A/B/C)
    # ================================================================
    "three C long, their Jett has Op, their second is Skye with tiger, and the third has vandal",
    "one holding A heaven with op, one shot, no armor, and they have lockdown ready on A site",
    "their Breach faulted through the C long wall, it stunned two of us, rolling thunder is up",
    "two garage, one is their Omen with two smokes and he already stepped into nest",
    "their Sova recon hit three B, he has two shock darts left, and fury is charged",
    "one defusing C default, their Killjoy nano is on the spike, and she has lockdown armed",
    "three B stacked, their KAY/O knife suppressed mid for eight seconds, all abilities gone",
    "their Viper walled garage, fuel is half gone, and pit is activated post-plant on C",
    "two A long, both vandal full buy, their Waylay has beacon on A link and convergent charged",
    "one in hell, playing post-plant, their Brimstone already orbital'd A site and it's gone",
    "their Reyna is empress, three kills so far, auto-dismiss is infinite, leer is up",
    "two C link, one is their Deadlock with gravnet thrown at C site, annihilation is ready",
    "their Fade nightfalled all three of us at mid, trails are active and prowlers are locked on",
    "one lurking through A sewer, their Yoru made a fake tp sound, he is actually real in garden",
    "two B, their Sage walled B main doors and she has slow orb plus her rez is up",
    "their Iso pulled our Jett into kill contract, and Iso came back at 100 HP, double tap up",
    "one C site planting, their Gekko wingman is planting the spike, Gekko is free to fight",
    "three rotating CT to A, they confirmed no one B, so they are stacking A right now",
    "their Astra divided across C long with cosmic divide, and she has grav and pulse in place",
    "one A heaven no armor, one shot, got hit by our Sova shock, and he has blade storm up",
    "their Raze boosted two blast packs from B main into nest, showstopper is fully charged",
    "two A short sewer, their Neon sprint is active, fast lane walls are up in A site",
    "their Tejo guided salvo hit both A and C simultaneously with two missiles, armageddon up",
    "one C platform, Op, full health, slow field from tour de force is on default C plant",
    "their Skye released three seekers and hit all three of our players, all nearsighted now",

    # ================================================================
    # BIND — teleporter + tight-corridor compounds
    # ================================================================
    "two through A short TP into hookah, one is their Raze with showstopper and she has blast pack",
    "their Viper walled B long, fuel is down to half, and her snakebite is on the B default plant",
    "one holding A heaven with Op, he has full health plus heavy armor, no util used yet",
    "three B hookah, their Skye flashed the window twice with hawks, tiger is pushing B site",
    "their Cypher cammed A bath and darted our entry, he is tagged and revealed through walls",
    "two B long, TP is active, their Brimstone smoked hookah and window from the map tablet",
    "one lurking B elbow, one shot, he has no armor, and their Killjoy nano is on B default",
    "their Breach hard flashed through the A bath wall, hit three of us, and rolling thunder is up",
    "two A short, one is their Jett with Op and dash still up, the other has a phantom",
    "their Sova droned hookah and shot the dart onto our A site player, he is fully revealed",
    "one holding A triple box from heaven, she is their Chamber, tour de force slow on plant",
    "three B site, spike planted behind container, their Killjoy lockdown is going off in 13",
    "their Reyna dismissed into the B hookah smoke, she has souls, no flash hit her, she is invis",
    "two rotating B to A via B long TP, the TP sound went off, rotate back A to cut them",
    "their Omen stepped into his smoke at lamps, he has paranoia through the wall ready",
    "one A ninja spot, full health, no armor, vandal, and they have not used any utility yet",
    "their Fade seize landed in bath and our entry is tethered and deafened, push is blocked",
    "two B short into hookah, their Harbor storm surged the hookah entry, both are nearsighted",
    "their Yoru sent footsteps fake into B long while his real TP went to hookah roof angle",
    "one under hookah no armor, one shot, and our KAY/O knife suppressed him for eight seconds",
    "their Gekko wingman is planting at B default, Mosh pit is on site, Dizzy already flashed",
    "three A, two bath one short, their Astra activated grav in A bath and they are vulnerable",
    "their Clove smoked A lamps from the grave, dead smoke is up for six seconds, rotate cut off",
    "two B hookah window, one is their Iso with contingency wall and undercut thrown to site",
    "their Neon slid through B short with fast lane walls, overdrive is active, she is beaming",

    # ================================================================
    # SPLIT — vertical / rope compounds
    # ================================================================
    "two A ramps, their Jett updrafted to A heaven and she has blade storm and no smokes used",
    "their Viper walled A main from outside, screen is active, and snakebite is on A default",
    "one holding A heaven with Op, full health heavy armor, our Sova shock is set for the corner",
    "three B pushing through garage, their Raze has showstopper and two blast packs, go now",
    "their KAY/O knife hit all five at mid vents, eight second suppress, ult is null cmd active",
    "two A screens, their Breach flashpointed through screens wall and faulted into A site",
    "one hiding B ninja spot, one shot, no armor, spike is planted at B default behind boxes",
    "their Fade nightfalled through B heaven, trails on our two back site players, prowlers out",
    "two B hell, rope up to B heaven, one is their Chamber with tour de force, trademark on ramp",
    "their Cypher cammed A heaven and darted our Jett, she's revealed, trip is on the sewer",
    "one A main, he is their Omen with two dark covers and paranoia through the wall toward ramps",
    "their Skye sent tiger into B garage, it concussed one, and she has two hawks and seeker up",
    "three pushing mid vent, their Tejo suppressed from stealth drone above vent, eight seconds",
    "two A site, one is their Deadlock with gravnet thrown at A default, mesh is up on ramps",
    "their Neon slid up the rope at B hell to heaven, fast lane walls are in garage right now",
    "one B site, defusing B default plant, their Killjoy nano is activated on the spike now",
    "their Iso pushed through contingency wall in A main, undercut hit our entry, he is fragile",
    "two B alley, one is their Sage with barrier on B stairs and slow orb thrown into site",
    "their Astra pulsed nova into B garage, concussed two, and cosmic divide is cutting A ramps",
    "one hiding flowerpot on A site, full health, vandal, and they still have spike unplanted",
    "their Yoru faked the TP sound at mid market, he is real at B site flanking from behind",
    "two rotating mid mail to A via catwalk vents, one is their Jett with Op and no dash yet",
    "their Breach rolling thunder is going off in B garage right now, three of us are in there",
    "one A heaven, one B heaven, their Omen has two smokes used and is stepping between spots",
    "their Gekko reclaimed wingman at A terminal, Mosh pit is on A back site, dizzy incoming",

    # ================================================================
    # LOTUS — three-site compounds
    # ================================================================
    "two pushing A main, their Jett has Op and dash still up, and their Raze has showstopper",
    "their Viper walled C main, fuel is almost gone, and her pit ult is ready for post-plant",
    "one B site, defusing default, their Killjoy lockdown is arming right now, thirteen seconds",
    "three rotating A to C via CT, their Sova recon bolt hit three at C lobby on the scan",
    "their Breach faulted through the B main wall and hit two of us, rolling thunder is ready",
    "two C long, one is their Chamber with tour de force, slow field is on C default plant spot",
    "their Astra divided B site with cosmic divide, she has grav and pulse stars on both entries",
    "one holding A heaven with Op, no armor, one shot from our Sova shock dart earlier",
    "their Skye seekers tracked all three of us into A site, everyone is nearsighted right now",
    "two B, one is their Reyna in empress with infinite souls, one is their Iso with kill contract up",
    "their Fade haunted the C connector and hit two people, she has two prowlers plus nightfall",
    "one lurking A link, their Yoru made fake footsteps in C main while his real TP is A site",
    "their Gekko wingman is defusing B default plant, Mosh pit is up on C site, and ult is charged",
    "two A site, their Neon slid in with fast lane walls and is beaming with overdrive right now",
    "their Tejo guided salvo hit both B and C plant spots with one missile each, armageddon up",
    "three stacked C short, their Harbor storm surged the corner and both entries are nearsighted",
    "one A link no armor, one shot, and our Cypher trap hit him so he is also revealed",
    "their Deadlock caught two of us in annihilation cocoons at B site, break the cocoons now",
    "two rotating B main to A main, both vandal full buy, their Omen has paranoia and three smokes",
    "their Iso pulled our Raze into kill contract from C long, Iso came back at 100 HP full health",
    "one C heaven, Op, full health, and their KAY/O knife suppressed C main entry for eight seconds",
    "their Clove smoked B entry from the grave and the dead smoke only lasts six seconds now",
    "two A main, their Waylay used lightspeed dash twice and beacon is down at A link for escape",
    "their Brimstone dropped orbital on B default plant, 570 total damage zone, hold the defuse",
    "one A site, planting default, their Sage slow orb is on the path to stop us rushing in",

    # ================================================================
    # BREEZE — long-range / open-map compounds
    # ================================================================
    "two A main, one is their Jett with Op on mid arch angle, dash is still up, no smokes used",
    "their Viper pit is activated on A site, she has full vision inside, decay kills at low health",
    "one holding B main with Op, full health, heavy armor, and their Sova fury ult has three beams",
    "three B executing, their KAY/O suppressed A hall with knife, eight seconds no abilities there",
    "their Astra cosmic divided across mid, blocking audio and bullets for twenty one seconds now",
    "two A cave, their Fade nightfalled through the wall, three of our players have trails active",
    "one B back site, defusing default, their Brimstone orbital is dropping on the spike right now",
    "their Raze boom bot cleared B halls and showstopper is charged plus she has blast pack boost",
    "two mid arch, one is their Chamber with tour de force, the other has outlaw and light armor",
    "their Skye trailblazer concussed our entry in A main, she has two hawks and seekers up",
    "one lurking A hall, their Yoru has gatecrash tether at B site and dimensional drift is active",
    "their Neon fast lane walls are up in B site, she stunned two with relay bolt and overdrive ready",
    "two B hall, one is their Cypher with cam watching B main and trip is on B halls floor",
    "their Iso contingency wall blocked our push across mid, undercut hit two, double tap is active",
    "one holding A mid top with Op, no smokes used, one is their Killjoy with lockdown charged",
    "their Breach flashed A cave with flashpoint twice, one fast one slow, fault line ready",
    "two pushing B site through elbow, their Reyna got two kills, empress is still running now",
    "their Gekko wingman is planting A default, mosh pit is on B halls, dizzy flashed mid arch",
    "three stacked A main, their Tejo special delivery concussed entry and drone is suppressing",
    "one A back site, spike planted close to their wall, defusing triggers viper snakebite vulnerable",
    "their Deadlock mesh is across B main, gravnet thrown at B site, annihilation ult is ready",
    "two rotating from A to B via mid arch, their Clove is dead but smoking A CT right now",
    "one B heaven, Op, one shot, he got hit by our Sheriff on eco, no armor, he is glass",
    "their Sage walled B main entry and slow orbed the elbow push, rez ult is charged this round",
    "two A main both eco, sheriff and ghost, and their Omen faked going B with a shade teleport",

    # ================================================================
    # FRACTURE — attacker-flank + defender-spawn compounds
    # ================================================================
    "two rope drop A main, one is their Jett with blade storm and a vandal, dash was used already",
    "their Brimstone smoked both A main and B main simultaneously from the top of attacker spawn",
    "one holding A dish with Op, he got hit 60 by our Sova shock on the lineup, one shot now",
    "three B arcade pushing, their Breach faulted through the left wall and hit all three of us",
    "their Viper toxic screen split A right from A main, fuel is at half, snakebite on default plant",
    "two A tower, one is their Chamber with headhunter and trademark on both rope exits below",
    "their Sova owl drone cleared B main and marked two players, fury has three beams charged",
    "one lurking from attacker spawn around to A link, their Yoru fake tp'd to B site first",
    "their KAY/O null cmd is active, he is pulsing suppress every three seconds near A site",
    "two B main, both have rifles, their Killjoy turret is watching B site and nanos are planted",
    "their Fade seize landed at A dish and tethered our Raze there, prowlers are homing on trails",
    "one B site defusing, their Sage slow orb is on the spike defuse path, rez is charged",
    "three executing A right plus dish split, their Astra nova pulsed A dish and grav is up",
    "their Iso pulled our best player into kill contract at B site, he is inside right now",
    "two B tree, one is their Neon with overdrive active beaming into B main, she slid under ropes",
    "their Tejo armageddon is going along B main right now, move perpendicular or you will die",
    "one A main, no armor, one shot, and our Cypher trip hit him, he is slow and fully revealed",
    "their Raze blast packed over attacker spawn wall to A tower, showstopper armed and ready",
    "two rotating A dish to B site, both confirmed vandal full buy, their Skye has seeker ult up",
    "their Deadlock gravnetted the A dish entry, everyone is crouching, annihilation cocoon ready",
    "one A generator, holding post-plant, their Clove not dead yet ult is ready from last round",
    "their Omen paranoia went through the B arcade wall and hit two of us before we could peek",
    "two A main rope area, one is their Waylay with beacon at A link and convergent paths active",
    "their Gekko reclaimed dizzy at B tree, wingman ran into A dish and mosh pit is on B default",
    "three B arcade both eco plus one force with spectre and their Brimstone has stim beacon ready",

    # ================================================================
    # PEARL — underwater-city compounds
    # ================================================================
    "two A main, one is their Jett with Op and both updrafts used, she has blade storm charged",
    "their Viper walled mid link, fuel is depleted, pit is on A site post-plant covering default",
    "one holding B site from B link elbow, full health, heavy armor, Op, and signature trap is up",
    "three A main executing, their Sova recon bolt hit the whole site, fury has three beams ready",
    "their Astra cosmic divided A link from CT to cut off defender rotation to A for twenty seconds",
    "two mid plaza, their Breach fault lined down the plaza wall, rolling thunder is armed now",
    "one A art, defusing, their Killjoy lockdown just went off and three of us are detained right now",
    "their Fade nightfalled mid, trails on two players, prowlers are locked on both trails already",
    "two B main, one is their Reyna in empress with dismiss on, the other has a vandal and leer out",
    "their Chamber is playing off-angle at B link with tour de force, slow field on B default plant",
    "one A site back wall, no armor, one shot, and our Sova shock dart is lined up on that corner",
    "their Skye released seekers at A main entry, three seekers homed three players, all nearsighted",
    "two CT rotation through connector, their Omen smoked both A link and mid market simultaneously",
    "their Raze boom bot cleared B hall and her showstopper is up, she has two blast packs still",
    "three B site took it, their KAY/O null cmd went off mid-site and is suppressing every three sec",
    "one planting A default, their Gekko wingman is doing the plant so Gekko is free to fight us",
    "their Iso walled B link, undercut hit our entry, and kill contract is armed and aimed our way",
    "two rotating from A to B mid, one is their Waylay with lightspeed dash and beacon at mid plaza",
    "their Tejo guided two missiles on A art and B default simultaneously and armageddon is charged",
    "one A heaven, Op, full health, no util used, and their Killjoy nano is hidden on A default plant",
    "their Deadlock annihilation caught our clutch player at B site, 600 HP cocoon, break it now",
    "two A main push, their Clove died trying to entry but is smoking A link dead with six seconds",
    "one mid connector, their Cypher spycam is watching A art doorway and has trip on connector floor",
    "their Neon slid into A site with fast lane walls, relay bolt stunned two at A default entry",
    "two B main both full buy, their Harbor storm surged B hall entry, both players are nearsighted",

    # ================================================================
    # ICEBOX — ropes + vertical compounds
    # ================================================================
    "two A main, one is their Jett on the snowman box with Op, she has blade storm and no dash used",
    "their Viper walled A site from the snowball structure, snakebite is on A default, pit is ready",
    "one B yellow, full health, heavy armor, Op, and their Killjoy turret is also watching B site",
    "three B site took it, their Sova fury has three beams left, recon bolt already hit mid tubes",
    "their Breach faulted through the B tube wall, hit two of us, and his rolling thunder is charged",
    "two A main, their Cypher cam is watching the cross to A site and trip is on A pipes floor",
    "one holding A rafters with vandal, he is one shot, no armor, our Sova shock is lined up there",
    "their Fade haunted A main, hit three, trails are active, seize landed at A site entry already",
    "two B yellow, one is their Chamber with tour de force and trademark on B pipes below him",
    "their KAY/O suppressed B site with ZERO point knife, eight seconds, all of their util locked",
    "one A site defusing, their Brimstone dropped a molly on the spike defuse, and orbital is up",
    "their Raze blast packed over the B yellow structure and showstopper is armed, she is airborne",
    "three A executing through snowball, their Astra divided snowball from A site, twenty one sec",
    "two rotating B to A through B belt, their Omen smoked both A main cross and rafters spot",
    "their Skye tiger concussed our entry in B main, two hawks are up, seekers ult is charged",
    "one mid, their Yoru gatecrash tether is near A site, he faked tp at B site two seconds ago",
    "two B site, one is their Deadlock with mesh up at B entry and gravnet thrown at B default plant",
    "their Neon slid through B tube with fast lane walls, relay bolt hit two and overdrive is running",
    "one A pipes, no armor, one shot, and our Sova shock dart lineup is already prepped",
    "their Iso contingency wall is pushing through B pipes, undercut hit one, double tap shield is up",
    "two A site both eco sheriff and shorty, and their Sage rez ult is charged and waiting",
    "their Tejo stealth drone flew into B site, suppressed three players, eight seconds all abilities off",
    "one planting A default, spike down, their Killjoy nano is activated at the exact plant spot now",
    "their Clove not dead yet just activated, she came back at 75 HP at the B site and has meddle",
    "two B yellow to A via belt, their Jett has Op and dashed to A rafters, fury is two shots left",

    # ================================================================
    # ABYSS — no-boundary / void compounds
    # ================================================================
    "two A main, one is their Jett at A bridge edge, she has Op and blade storm, dash already used",
    "their Viper walled A main from mid library, fuel is half gone, pit is up at A default plant",
    "one on A bridge, full health, Op, they have spike, and our Sova shock dart lineup is ready for bridge",
    "three B site, their KAY/O null cmd went off, suppressing all of us at B link every three seconds",
    "their Fade haunted A bridge, hit two of us crossing, prowlers are chasing both trailed players",
    "two rotating mid library to A via A link, one is their Omen with smokes on A tower and library",
    "one holding A tower from the elevated position, Op, one shot, and their Killjoy nano is on A default",
    "their Breach fault lined down mid bottom, it hit three, rolling thunder is prepped for B site",
    "two B nest, their Raze blast packed to a ledge above B nest and showstopper is armed",
    "their Sova owl drone flew across the mid void, marked two at B main, fury has three beams",
    "one A site defusing, their Brimstone orbital is incoming to the spike location right now",
    "their Skye seekers hit all three of us at A link, nearsighted everyone, regrowth heal incoming",
    "two A vent area, one broke through the vent door, their Jett is in A tower with Op and dash",
    "their Deadlock gravnetted B site entry and annihilation hit our entry player, 600 HP cocoon",
    "one mid catwalk, full health, vandal, no armor, and our Cypher cam is watching that angle",
    "their Reyna dismissed through A link smoke, souls are up from two kills, empress is active",
    "two pushing through A vent, the 120 HP door is blown, one is their Neon beaming in overdrive",
    "their Astra nova pulsed A bridge, concussed two people crossing the void, grav is up at B link",
    "one at A secret outer ledge, their Yoru is playing off-angle out there near the death drop",
    "their Tejo armageddon went along mid bottom from attacker spawn to B site, move or die now",
    "two A tower ropes, their Chamber is ascending at A tower rope with tour de force, trademark below",
    "their Iso kill contracted our Jett at B nest, both are inside arena, one of them dies now",
    "one A security, holding, no armor, one shot, and our Sova recon hit him through the wall",
    "their Clove smoked mid library from the grave, dead smoke for six seconds is blocking rotation",
    "two B danger, both dropped to the ledge shortcut, one is their Waylay with beacon at B site",

    # ================================================================
    # CORRODE — flooded walkway + elevation compounds
    # ================================================================
    "two A main, one is their Jett with Op at A elbow angle, she used both smokes already",
    "their Viper walled mid stairs, fuel is nearly empty, snakebite is on A default plant",
    "one B tower, full health, heavy armor, Op, and their Killjoy alarmbot is hidden at B link",
    "three A yard executing, their Breach faulted through A pocket wall, rolling thunder is armed",
    "their Sova recon bolt hit three in mid stairs area, fury has three beams locked in",
    "two B arch, one is their Chamber with tour de force, slow field already on B default plant",
    "their Fade nightfalled mid bottom, trails on two players, prowlers are chasing them now",
    "one A crane, they are holding high ground, Op, and our Sova shock is set for crane angle",
    "their KAY/O knife hit four at mid top, eight seconds suppress, all abilities gone go now",
    "two rotating mid top to B via B link, one is their Omen with two smokes left and paranoia",
    "one B site defusing, their Killjoy nano is activated on the spike and she has lockdown ready",
    "their Raze showstopper is up, she blast packed over mid stairs wall, she is in the air now",
    "three B site stacked, their Astra cosmic divided B link from CT and it blocks bullets and audio",
    "two A main both full buy vandal heavy armor, their Waylay has beacon at A yard and convergent up",
    "their Neon slid through flooded mid bottom, fast lane walls are up in mid stairs right now",
    "one A elbow, no armor, one shot, our Cypher trip hit him, he is slow and revealed",
    "their Skye tiger went through mid window, it concussed one, two hawks left and seekers ready",
    "two B elbow, one is their Iso with contingency wall pushing to B link, undercut hit entry",
    "their Deadlock gravnetted A yard and mesh is up at A elbow blocking entry, annihilation armed",
    "one A crane defender holding with Op, full health, and their Brimstone stim beacon is on site",
    "their Tejo special delivery concussed B link, stealth drone suppressed B arch, eight seconds",
    "two A link both eco sheriff and ghost, our team has rifles full buy, push them now",
    "their Reyna dismissed through mid stairs smoke, empress is active, auto-dismiss is running",
    "one planting A default, their Gekko wingman is doing the plant while Gekko fights at A elbow",
    "two B tower to B link rotate, one is their Jett, she dashed already and blade storm is charged",

    # ================================================================
    # MIXED MAP / CROSS-AGENT HARD COMPOUNDS
    # ================================================================
    "their Sova recon hit four of us and fury is up this round, retreat from the site right now",
    "two their Jett and their Reyna both have ults, Jett blade storm Reyna empress, entry now is suicide",
    "their Killjoy has lockdown and nanos on the spike, thirteen seconds to lockdown, do not defuse yet",
    "one holding heaven, one holding site, their Killjoy has turret watching elbow, and nano on default",
    "their Viper has pit up and full fuel and two snakebites and she is inside her pit seeing us all",
    "two their Chamber has tour de force and one trademark on each rotation route toward the spike",
    "their KAY/O null cmd is active and he is not dead so the suppress pulse is hitting every three sec",
    "one shot one job their Reyna has dismiss and souls from two kills and empress is running still",
    "our Sage rez is up, our Killjoy lockdown is up, their team has no ults, this round is ours",
    "their Fade nightfall hit all five of us, trails are active and both prowlers are tracking each trail",
    "two eco round, they have sheriffs and no armor, our team has vandals, full buy, rush them now",
    "their Astra nova pulsed B and activated grav on A simultaneously, she is in astral form right now",
    "one their Iso pulled our Jett into kill contract, and their Reyna used empress to chain kill two more",
    "their Raze showstopper and our Sage wall blocked entry, both ults went in the same three seconds",
    "two holding both heaven positions simultaneously, one Op each, they cover the entire site from above",
    "their Brimstone orbital is coming and his stim beacon is down and two smokes are already deployed",
    "one in defuse, their Killjoy nano is on the spike, their Viper snakebite is also on the spike",
    "their Skye hawk flashed three of us, tiger concussed one, seekers are homing on all three players",
    "two C site and three A site, their team split five zero, no one held mid this entire round",
    "their Breach rolling thunder went off mid site and three of us were knocked airborne and stunned",
    "their Clove ult activated and she came back and killed our clutch player and smoked the route off",
    "one their Jett dashed to heaven, their Sova recon is up on site, we have no flash to counter",
    "two their Deadlock and their Cypher both have ults, annihilation and neural theft both charged",
    "their Omen ulted from A to B mid round and no one saw his shade and now he is behind us",
    "their Tejo armageddon plus Brimstone orbital are both incoming on spike simultaneously right now",

    # ================================================================
    # ECONOMY + ABILITY COMPOUND FACTS
    # ================================================================
    "three of us have rifles and two are on half buy with spectre and their whole team has vandals",
    "their Jett has Op on eco round, she saved it last round, dash is up, blade storm is charged",
    "we are all on eco, they are full buy vandal heavy armor, do not force a fight this round please",
    "their Reyna is on eco with sheriff and no armor but she has empress up and leer for cover",
    "two of them have Operators, their Jett and Chamber both opping, they own both long angles",
    "we force bought with spectres and they are full rifles, but their Killjoy lockdown is not up",
    "their whole team is on eco save except their Sova who kept his vandal from last round rifle drop",
    "we have 4200 credits this round, enough for full buy plus abilities, call the buy for everyone",
    "their team has rifles and full util and their Skye seekers are charged, do not run into site",
    "two of us are 2800 credits, we can half buy with spectre and light armor and one ability each",
    "their Raze blast packed to an Op she found on the ground and now she has showstopper too",
    "we saved two rounds in a row, loss bonus is 2900 credits each, everyone can full buy this round",
    "their Killjoy has lockdown and full utility and full buy, they are ready to defend this site hard",
    "one eco player with sheriff got two kills and now he has 400 extra credits from eco kills",
    "their Viper saved her pit ult for three rounds and it is finally up, this is a big round now",
    "we have ult advantage, three of our ults are charged, only one of theirs is up this round",
    "their Astra bought all five stars and has three abilities placed already before round started",
    "two of us are short 800 credits each, we need drops from the players who have 5000 credits",
    "their Sage has rez ult up and their Killjoy has lockdown up, two ults on defense this round",
    "we are full buy rifles plus heavy armor plus full utility on all five, this is our gun round",

    # ================================================================
    # OWNERSHIP INVERSION STRESS — who has what, our vs their
    # ================================================================
    "our Jett used her dash but their Jett still has her dash saved for this engagement right now",
    "their Killjoy is using her turret to watch our flank while our Killjoy is watching their flank",
    "our Sova recon hit two of theirs but their Sova recon hit three of ours in the same exchange",
    "our Viper pit is up but their Viper already walked out of their own pit to bait us in",
    "their Sage can rez our dead Jett cannot rez because our Sage already used rez last round",
    "our Breach has fault line left but their Breach used all utility, we have the advantage now",
    "their Clove smoked after dying but our Clove died without using ruse, their smokes are up ours are not",
    "our KAY/O null cmd is active but their KAY/O also activated null cmd at the same moment",
    "their Skye used both hawk flashes but our Skye still has two hawks and tiger and seeker up",
    "our Omen has three dark covers but their Omen already spent all smokes and has no paranoia left",
    "their Raze showstopper went off on us but our Raze blast packed away and still has showstopper",
    "our Fade has nightfall but their Fade already haunted the site and has trails on two of our players",
    "their Astra pulsed our entry but our Astra has grav and pulse both ready plus cosmic divide up",
    "our Deadlock gravnetted their B push but their Deadlock annihilation hit our A side player",
    "their Cypher darted our lurker but our Cypher neural theft revealed all five of them last round",

    # ================================================================
    # SUBJECT / DIRECTIVE INVERSION COMPOUNDS
    # ================================================================
    "tell my team their Jett has Op at B main, she has one dash left and blade storm is charged",
    "let them know their Killjoy lockdown is going off in thirteen seconds at A site right now",
    "tell my teammates their Sova recon hit three of us and fury has three beams left this round",
    "let my team know their Viper pit is up at B site and she sees us all inside her own pit",
    "tell them their Breach rolled thunder into A main and three of us are stunned for six seconds",
    "tell my squad their Reyna empress is active, she got two kills, dismiss and souls are both up",
    "let my team know their Clove ult activated and she is alive again and she needs one kill to stay",
    "tell my teammates two of their players have Operators, one at A heaven one at C heaven right now",
    "tell my team their KAY/O knife suppressed A site for eight seconds, all abilities are locked out",
    "let them know their Fade nightfall hit all five of us and both prowlers are tracking our trails",
    "tell my team to not defuse yet because their Killjoy nano is active on the spike right now",
    "let my squad know their Astra has cosmic divide cutting B site and grav plus pulse in A",
    "tell my team their Tejo armageddon is along B main right now, move sideways or you die",
    "tell them their Waylay beaconed at A link, she dashed both times, convergent paths is charging",
    "let my team know their Skye seekers are homing toward all three of our players at A site",

    # ================================================================
    # FIRST-PERSON / SELF-STATUS RELAY COMPOUNDS
    # ================================================================
    "I am planting A default, their Killjoy nano is activated on the spike, cover me until it dies",
    "I have Op at B heaven, no dash left, blade storm is charged, they are pushing garage now",
    "I lit their Jett for 70 in wine, she has no armor, one shot, and she still has dash up",
    "I used my Viper wall and fuel is half gone, pit is up, I see two of them through the pit right now",
    "I am in the Killjoy lockdown, detained for eight seconds, I have spike, do not push yet",
    "I used both flashes and all my faults, I am dry, but their Sage rez target is in front of me",
    "I tagged their Reyna for 80, she has no orbs, no dismiss, and empress is not active this round",
    "I droned mid, marked two players at mid tiles, and shock dart is lined up for them now",
    "I have 60 HP no armor, one Op shot kills me, I am holding heaven, cover me from the side",
    "I am in their Viper pit, I can barely see, decay is eating my HP, I have one second before dead",
    "I used my KAY/O knife and it hit three of them, eight seconds, no abilities, push site now",
    "I am defusing B default, their Brimstone molly is on the spike, I cannot complete the defuse",
    "I have full health and full utility and vandal, I am playing A lurk while team executes B",
    "I need a drop, I am at 2400 credits, I can buy one ability, please send me a phantom",
    "I have ult ready, their Jett has Op at A main, I will Killjoy lockdown on the site in 13 sec",

    # ================================================================
    # ABILITY-CHAIN / MULTI-TRIGGER COMPOUNDS
    # ================================================================
    "their Breach flashed A main and then fault lined immediately after, both hit two players",
    "their Sova recon hit two then he instantly fired shock dart at both revealed positions",
    "their Skye flashed with hawk then sent tiger through the same gap into A site entry",
    "their Raze blast packed into site then immediately fired showstopper in the same motion",
    "their KAY/O popped flash then immediately threw knife and both abilities landed in B site",
    "their Viper toggled wall on to block A and at the same time activated pit with fuel remaining",
    "their Astra nova pulsed then activated grav on the same star location, double ability on site",
    "their Fade haunted then prowler followed the reveal trail into the same corner at B site",
    "their Gekko wingman ran in, concussed, then Gekko followed behind with mosh pit on site",
    "their Deadlock gravnetted site entry then immediately fired annihilation into the crouched group",
    "their Omen stepped into smoke then immediately paranoia'd through the wall toward our lineup",
    "their Clove meddled site entry then threw ruse smoke on the same spot while still alive",
    "their Tejo special delivery concussed B then guided salvo missile hit the same location after",
    "their Neon fast laned both corridors then relay bolt stunned behind the walls simultaneously",
    "their Iso undercut hit two players then immediately walled the entry route off with contingency",

    # ================================================================
    # TIME-PRESSURE DENSE COMPOUNDS (most latency stress for 3B)
    # ================================================================
    "two A main both Op no armor, their Sova fury three beams ready, retake is a death trap",
    "five full stack B pushing, their Breach thunder is going, KAY/O null cmd suppressing, do not go",
    "last one site defusing, their Killjoy nano is on the spike, Viper snakebite is also there",
    "three rotating fast, their Omen smoked both sites, Astra pulsed mid, we are split and blind",
    "four A their whole team except one, Sova recon hit three, Skye seekers hit two, all countered",
    "one eco two force three full buy their side, prioritize the full buys and eco kills for gun drops",
    "both their Jett and Chamber have Operators, both heaven positions covered, do not dry peek",
    "their Killjoy lockdown out in thirteen, Sage has rez up, Clove has not dead yet armed",
    "one holding A one holding B one lurking mid, their three site coverage is a three player trap",
    "their Reyna empress got three kills in a row, four souls, dismiss unlimited, do not peek alone",
    "two their Astra pulsed site and Brimstone orbital is incoming simultaneously on the same plant",
    "five push B their full eco rush, sheriffs and no armor, vandals on our side, push back now",
    "last round of half their whole team is saving for a full buy, let them save and eco this round",
    "their KAY/O null cmd is up and Breach rolling thunder is up and Sova fury is up this round",
    "three sites to cover, three ults to use, three people alive, match every ult to the right site",

    # ================================================================
    # EDGE-CASE DISAMBIGUATION COMPOUNDS
    # ================================================================
    "two A not B, I repeat two A, their Jett dashed to A heaven, not the B site, rotate A",
    "one shot him for 80 not 18, he has 20 HP, no armor, he is one shot from any gun right now",
    "their Killjoy lockdown not their Sage wall, Killjoy lockdown thirteen seconds, do not stay site",
    "their Jett dash is used not her ult, blade storm is still up, her escape is gone but ult ready",
    "four A not rotating, their whole team is A, B is wide open, go B immediately right now",
    "I have spike not him, I have the spike, I will plant, cover my plant at A default please",
    "their Sova recon not our recon, their Sova hit two of ours, our recon has not been fired yet",
    "their Viper pit not wall, pit is activated on A site not just the screen, do not enter the pit",
    "two of ours down not two of theirs, we are the ones who lost two, now it is three versus five",
    "their Clove smoked from the grave not alive smoke, dead smoke is only six seconds not fourteen",
    "one holding A not rotating, their anchor is on A heaven, their rotators are going to C right now",
    "their Raze has blast pack not showstopper, showstopper is charged but she has not fired it",
    "force buy not full buy, we can afford spectres and light armor but not vandals and heavy armor",
    "eco not save, eco means buy light, full save means classic only, we are going eco with sheriff",
    "half buy not force, half buy is two thousand credits not spending everything, spectre plus light",

    # ================================================================
    # AGENT-SPECIFIC SIGNATURE MECHANIC COMPOUNDS
    # ================================================================
    "their Reyna used dismiss but she has no soul orbs left so she cannot dismiss again this fight",
    "their Jett killed two so her tailwind dash recharged, she has the dash back, she can escape again",
    "their Clove picked up after a kill, she has overheal plus speed buff and not dead yet is armed",
    "their Gekko reclaimed wingman at A site, fifteen second cooldown, then wingman is back and ready",
    "their KAY/O is downed in null cmd, he is not dead, one of us needs to walk up and revive him",
    "their Phoenix run it back is active, if we kill him he respawns at his marker in ten seconds",
    "their Viper fuel is at zero, her screen dropped automatically, wait for her to toggle it off to push",
    "their Astra is in astral form right now placing stars, she is vulnerable in her body at B site",
    "their Yoru used fake tp sound, do not rotate, he did not actually teleport, he is still B",
    "their Sova recon bolt landed but enemies immediately shot it, zero scans, we got no info",
    "their Raze boom bot is locked onto one of us in A main, he is chasing and will deal 100 damage",
    "their Sage slow orb reduced dash speed by fifty percent, even Jett and Neon are slowed in it",
    "their Iso double tap orb is floating above the kill right now, shoot the orb to steal his shield",
    "their Waylay beaconed before peeking, she will recall to beacon if the duel goes wrong for her",
    "their Neon killed in overdrive so her slide just reset and she can slide again immediately now",

    # ================================================================
    # RARE/HARD ABILITY INTERACTIONS
    # ================================================================
    "their Veto evolution is active, he is completely immune to our flash, stun, slow and decay now",
    "our Vyse steel garden went off, their primaries are all jammed for eight seconds, push now",
    "their Deadlock annihilation cocoon is 600 HP, we have to shoot it or our player dies in seven sec",
    "our Chamber tour de force slow field is on the B default plant, they are walking through it",
    "their Tejo stealth drone revealed all five of us continuously for eight seconds not just a snapshot",
    "their Vyse shear triggered behind their B main entry, the wall is indestructible for six seconds",
    "their Veto chokehold tethered two of us at A site, we are immobilized deafened and decaying",
    "our Iso contingency wall is blocking bullets both directions, our Omen can step inside it safely",
    "their Waylay convergent paths expanded the beam and hindered four of us, she has speed too",
    "their Iso kill contract happened, Iso won, he came back at 100 HP with double tap immediately active",
    "their Veto interceptor is active in B main, it will destroy our Raze paint shells if we throw",
    "our Vyse arc rose is hidden at A main, when I trigger it, everyone look away from A main entry",
    "their Harbor cove shield has 680 HP now, we need to break the shield before we can see through it",
    "their Clove meddle decayed our entry and now Clove is picking him up at maximum overheal 50 HP",
    "their Deadlock barrier mesh is across B site, bodies cannot cross it but bullets pass right through",

    # ================================================================
    # HAVEN — additional 3-site hard compounds
    # ================================================================
    "two A long and one C long simultaneously, their team is splitting three ways with no B player",
    "their Sova fury went through the C long wall and all three beams hit our players holding there",
    "their Viper walled garage from mid courtyard, fuel gauge is red, pit is active at C site plant",
    "one holding A heaven, Op, one shot, and their Killjoy lockdown is going off in B site right now",
    "their Astra pulled us with grav on C link then teammates rushed in while we were vulnerable",
    "two B, one is their Chamber with tour de force and one trademark on A link and one on C link",
    "their Breach rolling thunder rolled through garage hitting all three B-side defenders at once",
    "one C platform no armor, one shot, their Killjoy nanoswarm is active at C default right now",
    "their Skye tiger ran into B from garage, concussed two players, and seekers are targeting three",
    "their Yoru fake teleported to C long and his real gatecrash deposited him behind us at A heaven",
    "one A short sewer, their Fade seize landed in the tunnel, our player is tethered and deafened",
    "their Omen paranoia went through the B wall from mid courtyard and hit two of us simultaneously",
    "two rotating garage to A, one is their Neon with overdrive active beaming our anchor at heaven",
    "their Tejo guided salvo hit A site and C site with one missile each, armageddon is charged now",
    "three A long push, both their Jett and Raze have ults, blade storm and showstopper both up",
    "their Reyna dismissed through A heaven smoke and she has souls from two kills and empress active",
    "one lurking C link, their Cypher cammed the C link doorway and darted our player there",
    "two A short sewer, both eco with sheriffs, our full buy team should push A long to counter",
    "their Clove activated not dead yet, she came back at C site, needs one kill to survive next ten sec",
    "three B stacked, their Harbor storm surged B main from mid courtyard, all three nearsighted",

    # ================================================================
    # LOTUS — additional hard compounds
    # ================================================================
    "their Fade haunted A main and hit three people, she has prowler plus seize still unused",
    "two B rotating to A via CT, their Omen smoked both A link and B main simultaneously",
    "one B site, defusing, their Brimstone orbital is incoming on the spike, do not commit to defuse",
    "their Raze blast packed over A main wall and showstopper is armed, she is in the air now",
    "three C main push, their Breach flash pointed twice through C main wall, rolling thunder up",
    "their Astra pulsed C connector, concussed two, and cosmic divide is cutting B from CT access",
    "one A heaven, full health, Op, and their Killjoy alarmbot is hidden at A link doorway",
    "two rotating mid to B via B link, their Sova recon bolt hit two players at B site entry",
    "their KAY/O null cmd suppressed B site for fifteen seconds, every three second pulse hit us",
    "one C default defusing, their Killjoy lockdown just detained all three remaining defenders",
    "their Jett dashed to A heaven with Op, no smokes used, blade storm up, our flank is exposed",
    "two eco round at B, sheriffs and one ability each, our team should not eco trade our rifles",
    "their Neon slid into C site, fast lane walls blocking both C main and C link angles simultaneously",
    "their Waylay double dashed into A site, beacon is at A link, convergent paths hindered entry",
    "one B site planting, their Gekko wingman is on the spike, Mosh pit is blocking B link retake",
    "their Deadlock annihilation hit our defuser at B default, 600 HP cocoon, she dies in seven sec",
    "two A main, one has the Op and one has a vandal, their Cypher cam is watching from A tree",
    "their Skye used guiding light twice, auto flashed both times, tiger is ready, seekers charged",
    "their Omen stepped from mid into C short garage smoke, two covers left and paranoia still up",
    "one A link, their Iso walled A link with contingency, undercut went through toward the site",

    # ================================================================
    # SPLIT — additional rope + screen compounds
    # ================================================================
    "their Viper screen is cutting A main from A site, snakebite is on A default, fuel is half",
    "two B heaven, one is their Jett with Op and one is their Chamber with tour de force, both opping",
    "their KAY/O knife hit four at A ramps entry, eight second suppress, all their abilities gone",
    "one holding A screens gap, one shot, no armor, and our Sova shock dart lineup is set there",
    "their Breach fault lined through A screens wall and hit two before they could close the gap",
    "two mid bottom, their Sova recon bolt went up through mid vent and scanned two at A tower",
    "their Neon slid through the B hell rope area, fast lane walls are in B garage blocking sight",
    "one A rafters, holding post-plant, their Killjoy nano is at A terminal and turret watches main",
    "their Fade seize landed in A sewer and our player is tethered and deafened in the sewer now",
    "two B site, one is their Reyna with empress, one is their Iso in kill contract pulling someone",
    "their Astra cosmic divided A ramps from A site, blocking bullets and audio for twenty one sec",
    "one B alley, their Cypher trip is on B stairs and cam is watching B heaven from CT side",
    "their Raze boom bot rolled through B garage and locked onto our player, chasing for 100 damage",
    "two rotating A heaven to B via mid mail, one is their Omen with smokes and one has an Op",
    "their Tejo special delivery bounce hit into A site from outside the screen, concussed two",
    "one B default plant, their Killjoy nano is active on spike, deadlock mesh is also at B entry",
    "their Skye tiger ran up A ramps and concussed our heaven player, two hawks still up plus seeker",
    "their Waylay beaconed at A screens corner, dashed in with lightspeed, convergent paths armed",
    "two A main both vandal full buy, their Viper snakebite made us vulnerable as we passed through",
    "their Deadlock gravnetted B garage push and annihilation hit our entry player behind the net",

    # ================================================================
    # PEARL — additional underwater compounds
    # ================================================================
    "their Viper pit is on A site, fuel is gone, she is inside seeing all of us with decay active",
    "two B link elbow, one is their Chamber with tour de force, slow field already on B default",
    "their Breach rolling thunder went off at A main entry, three stunned six seconds, push now",
    "one holding A art, full health, heavy armor, Op, and our Cypher trap is on A link floor",
    "their Sova owl drone flew through B main, marked two, and fury has three beams charged",
    "two A site, their Reyna in empress got three kills, automatic devour, infinite dismiss active",
    "their Astra pulsed A main entry, concussed two, grav is armed at A link for follow-up pull",
    "one defusing B default, their Brimstone orbital is dropping on spike position right now",
    "their KAY/O suppressed mid plaza for eight seconds, null cmd active, he is revivable if downed",
    "two rotating A to B through connector, their Omen smoked connector and stepped into his smoke",
    "their Fade nightfall hit three at B main, trails are active and prowlers are locked on trails",
    "one hiding B cubby, no armor, one shot, our Sova shock dart is already lined up on that spot",
    "their Raze showstopper is fully armed, she blast packed to elevated spot above B hall right now",
    "two B site stacked, their Killjoy lockdown and Deadlock annihilation both up same round",
    "their Skye guiding light auto flashed at end of path, tiger concussed our entry simultaneously",
    "one A art lurking, their Yoru made fake footstep sound in B main while gatecrash is A site",
    "their Iso pull contracted our Jett at A main, Iso won the 1v1, returned at 100 HP double tap up",
    "two mid plaza, one is their Waylay with lightspeed dash and one is their Neon with relay bolt",
    "their Tejo drone detonated over A site, revealed four and suppressed them for eight seconds",
    "one B back site, spike planted close to the B hall entry, their Killjoy nano is on the defuse path",

    # ================================================================
    # BREEZE — additional open-map compounds
    # ================================================================
    "their Viper walled A main, fuel is depleted, she toggled off and now needs 30 sec to regen",
    "two mid arch, one is their Jett with Op and one is their Neon sliding with relay bolt charged",
    "their Sova recon hit three at B hall, fury three beams ready, shock darts set for B default",
    "one holding A hall with Op, full health, heavy armor, and their Astra star is placed at A site",
    "their Breach fault lined through A cave wall, hit two, rolling thunder is charged for A site",
    "two B elbow, one is their Killjoy with lockdown charged and nanos hidden on B default plant",
    "their Fade seize landed at mid arch and tethered our entry, prowlers homing on the trail now",
    "one lurking A hall, their Cypher cam is watching mid arch angle from A side, trip is on A caves",
    "their Raze blast packed to B heaven position and showstopper is armed, she is up there now",
    "two B site, their KAY/O null cmd suppressing site every three seconds, he is revivable if down",
    "their Astra cosmic divided B from mid, blocking audio and bullets for full twenty one seconds",
    "one B back site, defusing, their Brimstone molly is on the spike right now, wait it out",
    "their Iso contingency wall pushed mid arch and undercut went through to hit our crossing players",
    "two B halls, one is their Chamber with tour de force, one trademark at mid arch and one B halls",
    "their Skye seekers hit three of our players at A cave, all nearsighted, tiger is already in",
    "one holding A mid top no armor, one shot, their Sage slow orb is on the ground below that spot",
    "their Deadlock gravnetted A hall entry and annihilation hit the first person through the net",
    "two rotating from B to A via mid arch, their Waylay beaconed at mid, dashed twice to A cave",
    "their Neon overdrive is active beaming through A cave, fast lane walls are blocking B simultaneously",
    "one A site defusing, their Viper snakebite makes us vulnerable there, and pit cloud has decay",

    # ================================================================
    # FINAL 50 — additional stress cases across all categories
    # ================================================================
    "their Jett updrafted to A heaven and used blade storm, no smokes, no dash, she is committed",
    "two B main, one has a vandal one has Op, their Killjoy lockdown is going off at B site now",
    "their KAY/O null cmd hit B site and he got downed, one of us needs to revive him in 1.5 sec",
    "one holding C long with Op, he is one shot from our Sova shock dart that is already lined up",
    "their Viper snakebite made our entry vulnerable, shoot them now they take double damage there",
    "three A long both their Jett and Sova have ults, blade storm and fury three beams, do not peek",
    "their Gekko wingman is defusing B default while Mosh pit blocks our retake path through B link",
    "two rotating C to B mid round, their Omen smoked B link from outside and stepped through smoke",
    "their Reyna has no orbs left, she got zero kills this round, dismiss and devour are both locked",
    "one A main one shot, no armor, and their Sova recon dart from drone revealed his position to us",
    "two mid tiles, their Astra activated nova pulse then grav on the same tile spot simultaneously",
    "their Sage rez ult is up this round, do not rush into the site because she can bring someone back",
    "one lurking mid catwalk, their Yoru gatecrash is fake, he did not teleport, he is still there",
    "their Neon relay bolt bounced twice and stunned our two players holding B site entry right now",
    "two their Chamber and Killjoy both have ults, tour de force and lockdown both ready this round",
    "their Fade prowlers are locked on both our trailed players, nearsight is guaranteed incoming now",
    "one A site, defusing, spike is at A default behind generator, their Brimstone molly is there",
    "their Raze boom bot locked onto our entry in A main, it is chasing, 100 damage on contact",
    "three B site their team ran an eco rush with sheriffs, our rifles should win every duel there",
    "their Iso undercut hit our Jett and she is fragile and suppressed for four seconds right now",
    "two pushing B short into hookah, one is their Raze with showstopper up and blast pack boost",
    "their Sova owl drone flew mid and shot marking dart onto our player, they are fully revealed",
    "one holding B heaven with Op, one trademark on B hell rope and one trademark at garage entry",
    "their Clove has not dead yet armed, she is playing aggressive because she can come back once",
    "two A and three B, their team split perfectly, we cannot rotate in time to defend both sites",
    "their Waylay recalled to beacon at A link, she is invulnerable during recall transit right now",
    "one lurking B alley on Split, no armor, one shot, our Cypher trip is on B alley floor there",
    "their Deadlock sonic sensor triggered at B main, everyone in B main is concussed for 3.5 sec",
    "two full buy A, two eco B, their IGL is setting up a rifle sacrifice on A to open B eco rush",
    "their Veto evolution is active, he is running through our Skye flash, stun, and seize with no effect",
    "one their Vyse triggered steel garden, our primaries are jammed for eight seconds, use pistols",
    "their Harbor high tide water wall slowed our A long cross, we took 30 percent speed reduction",
    "two rotating from B to A, our Cypher cam confirmed the rotation, they went through mid connector",
    "their Tejo armageddon targeted A site from outside A main, move sideways off the line right now",
    "one B default defusing, their two nanoswarms are both activated on the spike simultaneously",
    "their Phoenix run it back is running, kill him again before ten seconds or he survives the round",
    "two A site, both vandal, and their Sova recon bolt is going to hit A site on the next scan",
    "their Iso contingency wall is an indestructible bullet blocker, do not try to shoot through it",
    "one mid tiles, their Breach aftershock is set through the tile wall to punish a static hold",
    "their Skye regrowth is healing our tagged players, we need to push before they all hit 100 HP",
    "two B hookah, one is their Omen with paranoia to throw through the B site wall at any time",
    "their Astra dissipated a fake smoke at A and she is resetting the star to place it at B instead",
    "one holding A wine with vandal, full health, heavy armor, and no A door has been broken yet",
    "their Sage barrier is blocking B main on Ascent, their other player is healing in the wall now",
    "two rotating from A to B in Lotus, they confirmed spike is at A default and they left one anchor",
    "their Killjoy alarmbot exploded on our entry and he is vulnerable for four seconds, push now",
    "one A site one shot, they have spike unplanted, our full team is alive, retake is favourable",
    "their Breach fault line is going off in B site right now, anyone inside B is dazed for 3.5 sec",
    "two mid and one A heaven, their Jett controls both mid and heaven angle, she has Op and dash",
    "their Viper pit activated and decayed our entry to one HP, do not enter the pit without armor",
]
