"""Stress pack: first-person preservation traps.

Every item is a relay command where the STREAMER self-reports their own state,
position, capability, or intent IN THE SAME BREATH as a directive to teammates.
The pipeline must keep 'I' anchored to the streamer (the speaker) and not
invert subject/ownership, hallucinate cooldown numbers, or drop the directive.

Hard axes exercised:
  - 'I am <doing X>, you do <Y>' -- self-status + directive tightly coupled
  - 'I will <action>, you <action>' -- intent + coordination pair
  - 'I have <resource>, rotate / push / plant' -- capability + directive
  - 'I have no <resource>, so you must <X>' -- negative self-report + compensating directive
  - 'I am anchoring <site>, <movement call>' -- anchor self-decl + rotate/push dir
  - Agent-named self-decl ('I am Viper, I need you to...') -- persona ID + dir
  - Ability ownership flip traps ('I will flash, you look away')
  - Subject inversion bait: 'I am their entry, you are my trade'
  - Compound: three or more self-facts before the directive
  - Ownership stress: 'my X vs their X' adjacent to directive
"""

ITEMS = [
    # === ANCHOR + ROTATE DIRECTIVES ===
    "I am anchoring A, rotate to me if they push",
    "I am anchoring B, you guys rotate when I call it",
    "I am holding A site alone, rotate only if I confirm contact",
    "I am the anchor on A main, nobody rotate unless I die",
    "I am staying B and anchoring, push A without me",
    "I am locking down B site, rotate to A if I call clear",
    "I am anchored at CT, everyone else rotate mid",
    "I am at B back site anchoring, do not rotate to me unless I say",
    "I am solo-anchoring A, you two rotate B and I will hold",
    "I am holding this site alone, rotate when you hear my contact",
    "tell my team I am the last anchor on A, give me backup or rotate",
    "tell them I am anchoring B single-handedly, play off my information",
    "I am pinned at elbow anchoring, rotate toward me from CT",
    "I am the one holding heaven, you rotate to A main on my call",
    "I am anchoring garage on Haven, rotate C if I go down",

    # === I WILL DO X, YOU DO Y ===
    "I will take B, you take A",
    "I will flash first, you swing right after",
    "I will entry, you trade me if I die",
    "I will go in first, everyone follow at five seconds",
    "I will absorb the utility, you push after",
    "I will bait the corner, you swing when he peeks",
    "I will lurk mid, you two push A",
    "I will fake A, you all go B",
    "I will hold link while you execute A",
    "I will take the early peek, you play off my contact",
    "I will smoke CT, you plant in the cloud",
    "I will stim the plant point, you stand in it",
    "I will drop the wall across mid, you cross on my call",
    "I will send the recon first, you push when it scans",
    "I will drone mid, you wait for my mark before moving",
    "I will knife their site and suppress them, you rush in after",
    "I will seize their plant position, you push through the tether",
    "I will throw the Nightfall, you push the three that get trailed",
    "I will use the Showstopper, you stay out of the blast radius",
    "I will Gatecrash to the off-angle, you push through main simultaneously",
    "I will haunt B site, you push when I call how many I see",
    "I will send both missiles at their default, you execute after impact",
    "I will anchor while you rotate, I will call when it's safe",
    "I will fake my ult teleport to bait them, you hit the real site",
    "I will activate the lockdown, you protect the device from them",

    # === I AM GOING / PUSHING + DIRECTIVE ===
    "I am going in first, play off my entry",
    "I am pushing A main right now, someone cover me from mid",
    "I am taking mid control, you take B when I hold mid",
    "I am running the flank through their side, you push front",
    "I am pushing into their smoke, follow me on my call",
    "I am crossing mid, cover me so I do not die in the open",
    "I am going aggressive at elbow, play off my contact when I call it",
    "I am taking top mid right now, you take B lobby",
    "I am entry-fragging this round, everyone else second-entry",
    "I am going deep to lurk, you hold front site",
    "I am rushing hookah, someone follow me into hookah",
    "I am taking bath entry, smoke heaven before I go in",
    "I am pushing B long, someone take Garden simultaneously",
    "I am entering through the TP, watch the TP exit on their side",
    "I am going through mid panels, you come from B main at the same time",

    # === I HAVE <RESOURCE> + DIRECTIVE ===
    "I have ult, let me open the round",
    "I have my dash back, let me be the entry this time",
    "I have ult and I will pop it on execute, coordinate with me",
    "I have both flashes left, let me flash you into A main",
    "I have my recon bolt up, wait for my scan before you push",
    "I have the Op, let me hold B long while you push A",
    "I have all my util left, let me entry A this round",
    "I have the Operator and I am holding mid, do not cross without me",
    "I have seekers charged, let me send them into site before you push",
    "I have my blade storm, use me as the entry this round",
    "I have the orbital ready, let me hit their default then you push in",
    "I have two nanos on the spike already, you just need to hold the defuse",
    "I have my pit up, you plant inside my cloud and I will anchor",
    "I have my cosmic divide ready, let me cut the site on execute",
    "I have my stim beacon, let me drop it at plant before you execute",
    "I have my Lockdown ready and I want to set it up, protect me while I do",
    "I have my Annihilation and I will cocoon their entry, you push on my shot",
    "I have my hawk and I will flash A main, close your eyes and swing",
    "I have my gravity well on their default, activate it and push when they are pulled",
    "I have my Steel Garden, if they rush I jam their primaries so push through",
    "I have both Blast Packs and I will boost to the elevated angle, cover my landing",
    "I have my Fault Line, I will stun them through the wall and you push right after",
    "I have my wolf ready and I will send it in first, follow when they are concussed",
    "I have my Rolling Thunder, let me earthquake the site before you enter",
    "I have my Reckoning wave ready, I will push it through the choke and you follow",

    # === I HAVE NO <RESOURCE>, YOU MUST ===
    "I have no flash left, someone else has to blind the angle before I go in",
    "I have no smoke, you need to smoke CT before I can plant",
    "I have no ult this round, do not count on me for the execute opener",
    "I have no armor, I cannot take the first fight, someone else go first",
    "I have no util left, I need a flash from someone before I push",
    "I have no recon bolt yet, you go in without the scan this time",
    "I have no dash, so do not expect me to escape after the peek",
    "I have no wall this round, you need a different smoke for the cross",
    "I have no stim beacon this round, you will have to execute without the buff",
    "I have no Lockdown this round, play aggressive defense instead",
    "I have no nanos on the spike, they can defuse freely, someone has to hold it",
    "I have no Wingman, I will plant manually but I need cover",
    "I have no molly for post-plant, someone buy one or we hold the site",
    "I have no seekers, we go in blind this time, someone else give info",
    "I have no Blade Storm, do not use me like a Jett entry fragger today",

    # === SELF-REPORT NEXT TO OWNERSHIP TRAP ===
    "I am low HP but I have their rifle, should I keep it or drop it",
    "I am at 30 HP with the Op, I will hold long but trade me if I fall",
    "I am dead but I am watching their position, someone rotate to where I died",
    "I am one shot but I am the last one alive, everyone please go silent",
    "I am the one with the Op, not them, I am playing long angles",
    "I hit him for 80, he is one shot, their Jett is one shot near A main",
    "I tagged their Reyna for 60, she has no armor now, push her",
    "I traded their entry but I am at 25 HP, their second entry should be close",
    "I have the spike but I am at 15 HP, someone needs to cover my plant",
    "I picked up their dropped Vandal, I am not on eco anymore, let me entry",
    "I took their Operator after the kill, do not put me in a close-range fight",
    "I have their dropped Op and I am holding B long now, do not push without me",
    "I hit their Phoenix for 45, he is at 55, he will try to use Run It Back",
    "I see their Killjoy setting up, I will call when her util is placed",
    "I am watching their Sova, he has no recon left, safe to push blind",

    # === I AM + AGENT SELF-DECLARATIONS + DIRECTIVE ===
    "I am Jett and I have my dash, let me be the hard entry",
    "I am Jett with no dash, do not send me in first until I recharge",
    "I am Reyna and I am in Empress right now, feed me more enemies to chain",
    "I am Reyna but I have no soul orbs, I cannot dismiss so play careful",
    "I am Phoenix and I have Run It Back active, kill me fast or I am back at full HP",
    "I am Phoenix and my ult just expired, do not count on the respawn play",
    "I am Viper and I need you to plant inside my pit, do not go outside it",
    "I am Viper and I am outside my pit, call if you see them so I can re-enter",
    "I am Neon and I have my slide back, let me sprint entry the site",
    "I am Neon and I used my slide already, I need a second to recover before I go in",
    "I am Omen and I will teleport behind them with my ult, do not rotate until I call",
    "I am Omen with no smokes left this round, someone cover our angles",
    "I am KAY/O and I will throw my knife on site, push the second you hear it suppress",
    "I am KAY/O and I went down during Null, someone revive me from my body",
    "I am Sage and I will wall A main to stall them, rotate to B while I hold",
    "I am Sage with no wall this round, I bought slow orbs instead, play around that",
    "I am Yoru and I will fake teleport to bait their rotation, go B when they leave A",
    "I am Yoru and my tether is at their CT, I can teleport behind them on your call",
    "I am Clove and I died but I am smoking the site from the grave, use the smoke",
    "I am Clove and my Not Dead Yet is active, I need a kill in 10 seconds to stay alive",
    "I am Gekko and I will send Wingman to plant the spike, I need cover while he does",
    "I am Gekko and I reclaimed my Dizzy, I have a second flash after the cooldown",
    "I am Brimstone and I am smoking A with all three clouds, execute when I say go",
    "I am Sova and I have three Fury beams, tell me where to shoot them",
    "I am Killjoy and I placed Lockdown, I need someone to protect the device",
    "I am Cypher and my cam was destroyed, I have no information until it respawns",
    "I am Chamber and my anchor is placed at elbow, I will TP to it if they rush",
    "I am Fade and I haunted B site, three enemies are trailed, sending Prowlers",
    "I am Breach and I will stun through the wall, push the second I release it",
    "I am Harbor and I will cove the plant, shield it before you plant the spike",
    "I am Iso and my wall is up, push through it, they cannot shoot us through it",
    "I am Astra and I am going into astral form, cover my body while I place stars",
    "I am Skye and I am healing the team right now, group up and give me two seconds",
    "I am Veto with Evolution active, I am immune to all their utility, push with me",
    "I am Deadlock and I netted their push, they are crouched and pinned, push now",
    "I am Vyse and I just jammed their primaries with Steel Garden, rush them now",
    "I am Tejo and I detonated my drone on their cluster, they are suppressed 8 seconds",
    "I am Waylay and my Refract beacon is placed, I will recall if the peek goes bad",

    # === COMPOUND SELF-FACTS BEFORE DIRECTIVE ===
    "I am low, I have no armor, and I have no ult, so you go first this round",
    "I have the Op, I am at 40 HP, and I am holding B long, do not break my angle",
    "I am the entry, I have my dash, and I have ult, let me open A this round",
    "I am Reyna with Empress active and three soul orbs banked, please do not steal my kills",
    "I am at 15 HP, no armor, but I have full util, let me flash you in and I will follow",
    "I am the lurk, I am mid right now, and I have my knife for suppression, call when to throw",
    "I am anchoring B, I have ult, and I have 3 nanos on the spike, hold the site with me",
    "I have the Op, heavy armor, and ult charged, I need a smoke on CT so I can peek",
    "I am one shot, I have no util left, and I am the last one alive, please be quiet",
    "I have full HP, full armor, both flashes, and recon, let me be the info agent this round",
    "I am Viper, I have my pit set up, and the spike is planted inside it, anchor with me",
    "I have no dash, no ult, and no armor, I am playing for information not frags today",
    "I am at 80 HP, I have my Updraft, and I have the Op, let me hold from heaven",
    "I am Sova, I have recon and two shock bolts, let me set up for post-plant before you execute",
    "I have the rifle, heavy armor, and both my hawks, I will flash the whole site for you",
    "I am the entry fragger, I have a flash and my dash, I go in first and you second-entry me",
    "I am at full HP, I have ult, and I will tank the first shot, trade me if it goes wrong",
    "I have the Operator, no armor, and I am holding this lane alone, do not rotate to me",
    "I am 100 HP, I have all 3 smokes, and I want to execute B this round, coordinate with me",
    "I have no smokes, no flash, and no molly, I need someone else to do the utility work",
    "I am Killjoy, I have Lockdown charged, and I placed nanos on default, protect the device",
    "I am at 30 HP with ult and the Op, let me bait one kill and then you rotate to me",
    "I have the Vandal, no ult, and two flashes, I can open mid and flash the site push",
    "I am Phoenix, I am in Run It Back, and I am going aggressive, kill me fast or I respawn",
    "I have both Blast Packs, I am at full HP, and I will rocket-jump to heaven, cover my landing",

    # === INTENT + CONDITIONAL SELF + DIRECTIVE ===
    "I am going to entry and if I die you need to trade immediately",
    "I will peek the corner and if he is there you rush him from the other side",
    "I am going to bait his shot and when he shoots you swing hard from the right",
    "I will hold mid and if they contest it you rotate to help me",
    "I am going to take the Op angle and if I miss you push before he reloads",
    "I will throw the recon and if it hits you push on the scan ping",
    "I am going to activate the Lockdown and if they destroy it we retake differently",
    "I will entry and if I get the kill the site is open, if I die you trade",
    "I am going to plant the spike and if they defuse you molly them off it",
    "I will fake the teleport and if they rotate you push the real site",
    "I am going to use my ult and if I win the contract the site is weakened",
    "I will use Viper's Pit and if I die within 8 seconds it collapses, hold them out",
    "I am going to dash to the angle and if they see me coming you push from the other side",
    "I will throw the Nightfall and if it hits three you rush all three trails",
    "I am going to pilot Thrash in and if I detain someone you push instantly",

    # === POSITION SELF-DECL + MOVEMENT DIRECTIVE ===
    "I am at A main right now, you two push B",
    "I am at heaven watching site, you push through A main",
    "I am in hookah already, someone come into hookah with me",
    "I am at elbow and holding, rotate through CT to get behind them",
    "I am at back site anchoring, you rotate through link from mid",
    "I am at CT right now, push B main and I will rotate to cut them off",
    "I am taking catwalk and I need someone at A main to pressure simultaneously",
    "I am at the cubby on B and I need backup, someone rotate to B",
    "I am at A lobby, you go through showers while I go through A short",
    "I am holding the Sova spot at A main, you lurk B while I stall",
    "I am at B long and pinching, you push B site from hookah at the same time",
    "I am at garden side on Ascent, you push through market",
    "I am at tree holding mid, push A main from outside while I flank from tree",
    "I am at the default plant position on A, hold CT side for me",
    "I am taking the rope ascender to the top, cover me while I ascend",
    "I am playing B nest on Abyss, you push A while I info from nest",
    "I am at A security on Abyss, push into A main from my side",
    "I am holding mid bottom on Abyss, you push B from hookah side",
    "I am at A bridge on Abyss, someone hold A main so they do not flank me",
    "I am taking the outer ledge on Abyss, you take A main entry",
    "I am at A tower on Abyss, push A main while I have the high angle",
    "I am at mid catwalk on Abyss, you push B while I info from catwalk",
    "I am at A crane on Corrode, push A site while I hold the high angle",
    "I am at B arch on Corrode, come to B arch so we can pinch the site",
    "I am at B tower on Corrode, someone push B lobby so I can cover",
    "I am holding mid stairs on Corrode, push whichever site you want and I will pivot",
    "I am at A link on Corrode, push A site from my side and someone come through B",
    "I am at B lobby on Corrode pushing to elbow, someone come through B main",
    "I am at mid library on Abyss, push B while I watch the B rotation from here",
    "I am at A pocket on Corrode, come A pocket and we will double the corner",

    # === OWNERSHIP / SUBJECT INVERSION TRAPS ===
    "I am the entry fragger and you are my trade, not the other way around",
    "I am their Jett right now, no wait I am our Jett, I am holding Op on long",
    "I have their dropped rifle and I am pushing, do not shoot me from behind",
    "I died and their Sova got a pick, tell my team to rotate before they take mid",
    "I tagged their Reyna and she took 60 damage, she has no armor, push her",
    "I am the one with ult, not their Killjoy, I am the one placing lockdown",
    "I have our recon up and their side has no flash, push them now",
    "I killed their lurker and I am coming back through mid, let me know where their 4 are",
    "I am watching their Astra, she is going astral, push before she places more stars",
    "I see their Cypher camera, I will shoot it so we have no info for 45 seconds",
    "I am their worst matchup right now, I know all their positions, let me call",
    "I am the reason we are losing mid, sorry, let me fix it this round",
    "I saw their Phoenix ult expire, he got no value from it, push him now",
    "I hit their Viper and she stepped outside her pit, 8 seconds on the cloud",
    "I killed their Killjoy, her turret and bot are still up, shoot the turret",

    # === DIRECTIVE WITH SELF-TIMING CONSTRAINT ===
    "I am rotating in five seconds, hold them off until I arrive",
    "I am 10 seconds out from A, delay the execute until I get there",
    "I am almost at B, stall one more second and I will be in position",
    "I am defusing right now, cover all four angles for 7 seconds",
    "I am planting, give me 4 seconds of cover",
    "I am in the smoke and I cannot see, call when it is safe to peek",
    "I am setting up my pit, give me 6 seconds to let the cloud form",
    "I am droning mid right now, do not push until I get you information",
    "I am placing my nanos on the spike, give me 3 seconds before you plant",
    "I am healing the team right now, group up for 2 seconds before you go",
    "I am charging my double tap, give me 2 seconds before the fight starts",
    "I am waiting for my hawk to recharge, 5 more seconds until I have a flash",
    "I am reclaiming my Gekko globule, 15 second cooldown and then I have a second flash",
    "I am closing the B door right now, push B main before they destroy it",
    "I am activating cosmic divide right now, push through as the wall goes up",

    # === SELF-CAPABILITY CLAIM + DIRECTIVE ===
    "I can solo hold A, you rotate everyone to B for the execute",
    "I can plant through smoke with Wingman, someone just smoke the two chokes",
    "I can handle this 1v2, do not rotate, conserve your positions",
    "I can ninja defuse if you create a distraction somewhere else",
    "I can fake the teleport sound to bait their rotation, go B when they leave A",
    "I can survive this peek if someone flashes for me, do you have a flash",
    "I can win this 1v1 if no one interferes, just wait",
    "I can hold the angle all round with my Operator, someone protect my flank",
    "I can cover two angles at once from heaven, push from A main",
    "I can drone the site before you push, just give me 7 seconds",
    "I can Wingman plant so Gekko does not need to go close, let me send him",
    "I can wallbang through this surface, tell me if he is still there",
    "I can entry on your flash but someone needs to throw it, do you have one",
    "I can slow the entry to A with my orb, push B before they rotate",
    "I can jiggle peek to bait his Op shot, you swing for real when he fires",

    # === INABILITY CLAIM + COMPENSATING DIRECTIVE ===
    "I cannot take that fight without a flash, please flash before I go in",
    "I cannot reach B in time from here, someone else rotate to B",
    "I cannot entry without armor, someone take the first fight for me",
    "I cannot push that angle without a smoke, put a cloud on their heads before I go",
    "I cannot see them through the smoke, someone call their position",
    "I cannot defuse in time, let the spike blow and we play next round",
    "I cannot trade the entry fragger, I am too far back, someone closer trade him",
    "I cannot rotate without crossing mid, smoke mid before I try to rotate",
    "I cannot hold this alone, I need someone to come to A right now",
    "I cannot peek the Op without a flash, either flash me in or pick another angle",
    "I cannot plant safely without someone covering heaven, take heaven first",
    "I cannot lurk mid if they have a drone up, someone shoot the drone",
    "I cannot buy util this round, I am short 200 credits, someone drop me a flash",
    "I cannot anchor B and watch mid at the same time, I need a second player at B",
    "I cannot win this clutch without your silence, everyone stop calling",

    # === MIXED SELF + TEAMMATE STATUS IN ONE UTTERANCE ===
    "I am at 80 HP, you are free to entry and I will trade you if needed",
    "I am the one with the Op and you have the rifle, play at distance, I cover long",
    "I am flashing, you look away and then swing right when it pops",
    "I will smoke and you plant, I need you to plant while I smoke CT and heaven",
    "I will stun and you entry, do not wait for the stun to end, push on the stun",
    "I am the anchor and you are the rotator, anchor means I do not rotate first",
    "I am taking the first duel, you watch my back and trade if I fall",
    "I will do the fake at A, you do the real push at B, start your push when I use my util",
    "I am setting the angle and you are setting the second angle, do not overlap me",
    "I will entry and you second-entry, that means you wait 0.5 seconds after me",
    "I am holding heaven and you are holding site, if heaven falls rotate up to me",
    "I will recon the site and you wait for the scan before you push, do not push blind",
    "I am the lurk and you are the entry, when I get a pick on their flank you push",
    "I will molly the spike and you hold the defuse angle, do not let them defuse",
    "I am the one planting and you are the one covering heaven, do not break that assignment",

    # === ECONOMY SELF-REPORT + DIRECTIVE ===
    "I am on eco this round but I still need you to buy and not save with me",
    "I have 4200 credits, full buy, and I think you should also full buy",
    "I am dropping you a Vandal right now, do not waste it on a bad peek",
    "I bought the Op and I have no armor, you need to play around me this round",
    "I am going eco but I still need someone to buy a flash for the site push",
    "I have 1800 credits left and I need to save, but I still need your rifle in the fight",
    "I am buying light this round because I am short, but I need you to buy heavy armor",
    "I spent everything on util and I have no gun, someone let me pick up their drop",
    "I have enough credits to buy you a rifle but not myself one, tell me who needs it",
    "I am forcing this round and spending everything, you should eco and save for next",
    "I am buying the Marshal as a budget Op, do not expect me at short range",
    "I am on Spectre this round, keep me away from the long sightlines",
    "I bought the Ares for spraying through smokes, you take the corners",
    "I have credits for the Op plus all my util, I am the economy anchor this round",
    "I forced and I am on a Bulldog, just know my range is shorter than a Vandal",

    # === ROUND PHASE SELF + DIRECTIVE ===
    "I am planting right now, give me 4 seconds of full coverage",
    "I am defusing at 20 seconds, I need two people holding angles for me",
    "I planted the spike, now I need you to hold heaven and hold CT simultaneously",
    "I planted at default, you play post-plant from A main side",
    "I am holding defuse position, you rotate through CT to close off their retake",
    "I planted in my pit, do not come inside the pit, hold the outside angles",
    "I am tapping the spike to fake defuse, you need to make noise elsewhere",
    "I have 10 seconds to defuse and there are two of them, rush them now",
    "I am half-defusing right now, if they peek I will stop and shoot",
    "I will let the spike blow if they are both alive, do not die for the defuse",
    "I planted and I am at 5 HP, I need a full hold from the team this post-plant",
    "I am going for the ninja defuse, everyone create noise somewhere else",
    "I planted open because we had no time, everyone commit to holding the retake",
    "I planted for CT side because they were watching main, hold main for me",
    "I planted at B triple box default, you hold workshop side for the post-plant",

    # === CLUTCH SELF-DECL + INSTRUCTION ===
    "I am the last one alive, please go silent for the clutch",
    "I am in a 1v3 and I know where all three are, let me cook, no calls",
    "I am clutching right now, I need complete silence from everyone",
    "I am alive in a 1v2, do not call out their positions, I can see them",
    "I am doing the clutch and I need 7 seconds of silence to think",
    "I am the sole survivor, the spike is planted, I am playing for detonation",
    "I am 1v1 and I have ult, stand by and watch, do not coach me",
    "I am alive with 5 HP in a 1v3, let me attempt the ninja defuse",
    "I am the clutch player this round, the last thing I need is noise in my ear",
    "I am 1v2 and I know one of them is planting, I am flanking behind",
    "I am baiting the defuse, one of you was supposed to stay quiet",
    "I am in a 1v1 post-plant, the spike is at 15 seconds, play for time not kills",
    "I am alive and they do not know where I am, hold calls until I ask",
    "I am the clutch, I have their positions, I have the map sense, just trust me",
    "I am going for the ace in this 1v5 because why not, cheer for me",

    # === SELF-STATUS + MULTI-STEP DIRECTIVE ===
    "I am pushing and I need you to first smoke heaven then push with me after",
    "I have ult and I want to first recon the site then pop ult and then you push",
    "I am entry and the plan is I go first, you trade, then the third person plants",
    "I am going to drone mid and when I mark him you push B and I will cover A",
    "I will flash first, then push, then you follow 2 seconds later and we double the corner",
    "I am using my Lockdown and the order is: I place it, you cover it, then we retake",
    "I am Viper and the order is I wall then I cloud then you push through the split",
    "I have seekers and the plan is: I send seekers, you push on the nearsight, I follow",
    "I am Breach and I will stun then flash and you push right after the flash clears",
    "I am the info agent, I will haunt first, call the count, then we execute together",
    "I have the orbital and the sequence is orbital on spike then you close on their position",
    "I will plant, drop nano on spike, then you play post-plant from CT side",
    "I am Killjoy and the plan is Lockdown to clear the site then you retake on detain",
    "I will send my Reckoning forward and you push directly behind the wave not before it",
    "I will knife their site with zero-point and the second you hear the suppress you rush in",

    # === SUBTLE PRONOUN TRAPS / AMBIGUOUS REFERENTS ===
    "I am the Jett, not them, I am the one dashing, their Jett is somewhere else",
    "I saw them pushing and I pushed back, I am ahead of our spawn now",
    "they killed me but I tagged one of them for 60, go push the 60 HP one",
    "I am the one that got suppressed, I need someone to make plays for me while I wait",
    "I hit him for 80 and I am at 30 HP now, that trade might be in their favor",
    "I am alive and the spike is planted and I have ult, now what do you want me to do",
    "I heard the footsteps and I think it is me they are trying to flank",
    "I killed their entry but their second entry killed me, it is a 4v4 now",
    "I am holding the angle they are pushing and you should hold the angle they are not",
    "I am the one being chased, rotate to me, not away from me",
    "I flanked them but they heard me, I am dead, but now you know their back is exposed",
    "I have the information and I am the one making the call this round, follow my lead",
    "I see where the spike is planted and I know where they are, give me the green light",
    "I cleared the corner but the second one was hiding, I am dead, he is at the box",
    "I am alive, they think I am dead, let me be the surprise this round",

    # === DIRECTIVE WITH FIRST-PERSON CONDITION CLAUSE ===
    "rotate to me the moment I call contact on A",
    "push B when I confirm I have eyes on their rotation",
    "execute when I tell you I have smokes up",
    "plant the spike only after I say I cleared heaven",
    "swing the corner after I tell you I baited his shot",
    "do not rotate until I confirm I have the position locked",
    "push when I say I dropped the stun on them",
    "execute the moment I say I have the orbital ready",
    "go in when I tell you I am on their flank",
    "rush when I say I have their positions from the drone",
    "push through when I call that I activated the pit",
    "force the retake once I say I set the lockdown",
    "go B when I tell you I faked the A teleport",
    "execute A when I confirm I haunted the site and have the count",
    "take the site the second I tell you I have their whole team suppressed",

    # === FIRST-PERSON PLAYSTYLE READS + DIRECTIVE ===
    "I am the IGL this round and my call is execute A immediately",
    "I am playing the information role and I need you to trust my calls",
    "I am on a hot streak right now, let me entry every round for a while",
    "I am tilting and I should not entry, someone else take the first fight",
    "I am the anchor player and that means I do not rotate unless the site is gone",
    "I am the lurker and that means you push first, I come from behind",
    "I am the support player this round, I flash and smoke but do not entry",
    "I am playing aggressive this round, play off my contact rather than calling me back",
    "I am playing passive and reading their patterns, follow my calls this half",
    "I am the one solo holding mid and I need to know if you see their mid player",
    "I am the one who knows their Killjoy setup, let me call their default",
    "I am playing around their Jett's Op and I need you to pressure her from another angle",
    "I am trying to get the early pick and then rotate, do not commit until I call",
    "I am planning to bait mid and fall back, push B the second I get contact",
    "I am calling a slow default this round so we gather info, do not rush",

    # === REGISTER VARIETY: CLIPPED, STREAMER-VOICE ===
    "yo tell them I am anchoring A, rotate when I say",
    "bro tell my team I am going in first, trade me if I die",
    "ngl I have ult and I am entry-fragging, just play off me",
    "bro I am at 15 HP but I have Empress, feed me enemies",
    "tell the boys I am holding B long with the Op, do not break my angle",
    "fr tell them I am the lurk mid, push A when I get the flank kill",
    "yo I am planting, smoke CT and heaven before I do",
    "deadass tell them I have no smokes this round so someone else cover the site",
    "tell the squad I have the Operator and I will hold this lane all round",
    "bro tell them I am rotating through mid and I need a smoke on the cross",
    "yo let them know I have my knife and I will suppress their site, rush in after",
    "honestly tell them I am on 10 HP and I am still anchoring because nobody else can",
    "tell them ngl I have no util left so someone flash me into the site",
    "tell the squad I am going for the ninja defuse, make some noise",
    "yo tell them I am alive in the clutch, everybody shut up please",
    "frfr tell my team I have the Lockdown placed and I need cover on the device",
    "bro I am Viper and I am outside my pit, 8 seconds left on the cloud",
    "yo tell them I am Sage with no wall so they have to slow-push without the block",
    "ngl tell my team I whiffed the entry and I am at 3 HP, please trade me",
    "tell them straight up I am entry-fragging and I need one flash from our Breach",

    # === ULTRA-HARD COMPOUND TRAPS: THREE+ SELF-FACTS ===
    "I am at 20 HP, I have no armor, I have ult, and I am anchoring B, rotate to me only if site is gone",
    "I am Reyna in Empress, I have 3 soul orbs banked, I am chain-killing, do not interfere or take my kills",
    "I am the last alive, I am 1v3, I have 15 HP, and I have planted the spike, play for detonation not me",
    "I have the Op, I am at 80 HP, I have both Cloudburst smokes left, let me hold B long while you push A",
    "I am Killjoy, I have Lockdown placed, my nanos are on the spike, and my turret is watching stairs, hold the site",
    "I am Viper, my pit is active, the spike is inside it, and I am at 40 HP, do not let them force me out",
    "I am Sova, I have recon up, two shock bolts, and a drone ready, let me set up the execute from a safe distance",
    "I am at 50 HP, I have heavy armor, I have no ult, and I have one flash left, I will flash you in once",
    "I am Jett with no dash, I am at 15 HP, I am one shot, and I am anchoring A main, rotate if I go down",
    "I have ult, full HP, heavy armor, and the Operator, I need one smoke on CT so I can peek out comfortably",
    "I am the entry, I have my dash, I have ult, and I have a flash, let me open A with all of this at once",
    "I am Fade, my Nightfall hit three enemies, all three are trailed, and I have two Prowlers ready, push the trails",
    "I am Clove, I am dead, I am smoking from the grave for 6 seconds, use that smoke and push immediately",
    "I am in Null/cmd, I am pulsing suppression, and I am going to go down, someone revive me from my body",
    "I am anchoring A, I have ult, I have no armor, and the spike is planted at generator, hold CT and heaven for me",
    "I planted in the Viper pit, I am at 30 HP, I have no util left, and I am outside the pit now counting 8 seconds",
    "I am KAY/O, I suppressed their whole site, they have 8 seconds of no abilities, rush in right now before it ends",
    "I am Breach, I have Rolling Thunder charged, I have both Flashpoints left, and I have Aftershock ready, let me clear the site",
    "I am one shot, I am the clutch player, and I have the spike planted, absolutely no callouts from dead players please",
    "I am Waylay, I have my Refract beacon placed at CT, I have both Lightspeed dashes, and I have ult, let me entry",

    # === SELF-REPORT ABOUT WHAT I HEARD / SAW + DIRECTIVE ===
    "I heard footsteps at B main, rotate before they take B",
    "I saw their Jett dash to heaven, smoke heaven before we push A",
    "I heard the TP sound, someone rotated through A short, watch hookah",
    "I spotted their Cypher camera at A main, I will shoot it before we push",
    "I saw their Viper close her wall, push through mid before she toggles it back",
    "I heard their Killjoy Lockdown starting, destroy the device before the 13 seconds",
    "I saw their Phoenix activate Run It Back, kill him fast before the timer expires",
    "I spotted their KAY/O knife at B site, push the second you hear the suppress",
    "I heard their Reyna dismiss, she went intangible, wait 1.5 seconds before you shoot",
    "I saw their Neon slide in, she used her slide, she cannot slide again until she kills",
    "I heard their Omen step, he teleported into our smoke, be careful",
    "I spotted their Sova drone, someone shoot it before he marks one of us",
    "I saw their Iso wall go up, do not try to shoot through it, it blocks bullets",
    "I heard their Fade seize land on someone, push that tethered player now",
    "I spotted their Astra going into astral, push before she places more stars and gains control",

    # === NEAR-NEGATIVE TRAPS (relay-shaped but with explicit directive) ===
    "I should anchor A but I need backup first, someone come before I hold alone",
    "I should rotate but I will not until I hear from you, call when you need me",
    "I was going to entry but I am 10 HP so someone else has to do it",
    "I would push but they still have the Op on B long, smoke it and I will go",
    "I think I can clutch this but I need complete silence, if anyone talks I will lose focus",
    "I could solo this site but I want a second player just in case, come to me",
    "I want to entry but I am not going without a flash, please throw one",
    "I meant to plant at default but I planted open, hold the site angles for me now",
    "I tried to flash them but it landed short, someone re-flash before we push",
    "I was going to take mid but they had an aggressive player there, fall back and regroup",

    # === ROLE SWAP / ROLE CORRECTION DIRECTIVES ===
    "I said I was lurking but I changed my mind, I am going entry, adjust your position",
    "I told you I was anchoring but they pushed and I am rotating to B now",
    "I am not the IGL today, you call it and I will follow",
    "I was playing support but the entry fragger died so I am going in now",
    "I was supposed to plant but I am low so someone else pick up the spike",
    "I was holding heaven but I left to rotate, someone replace my heaven angle",
    "I called for a fake but I actually want to execute for real, push now",
    "I said I was anchoring but the site is empty, I am rotating to you",
    "I was the second entry but now I am going first, adjust and follow me",
    "I tried to lurk but they pushed me, I am back at spawn, find someone else to lurk",

    # === SELF + OPPONENT COMPOUND (ownership precision) ===
    "I am holding their Jett's Op angle and I need you to draw her attention from another entry",
    "I am watching their Killjoy setup and I will call when she has finished placing her util",
    "I am the counter to their Viper pit, let me push into it first since I have armor",
    "I am being targeted by their Reyna in Empress, someone help me before she chains kills",
    "I am burning their utility by bating here, push B when their smoke and flash run out",
    "I have eyes on their flanker and I will deal with him, you push the site front",
    "I am countering their lurker, someone go mid while I handle this one",
    "I am blocking their Sova recon line with my position, do not move or you break my cover",
    "I am playing off their Clove death, her dead smokes last 6 seconds now, push before they fade",
    "I am waiting for their Omen to run out of smokes, he has 30 second cooldown, push after",
    "I am watching their Harbor wall, when she toggles it off push through the gap",
    "I am tracking their Cypher camera dart on our B main player, shoot the cam",
    "I am watching their KAY/O for the knife, the second he winds up I will call and you push",
    "I am counting their smokes and they only have one smoke left, push when it goes dark",
    "I am reading their Viper's fuel, she is going to run out soon, push when the wall drops",

    # === HAVEN / SPLIT / FRACTURE / PEARL MAP-SPECIFIC SELF + DIRECTIVE ===
    "I am holding garage on Haven, you two push A and I will rotate if C goes quiet",
    "I am at C long on Haven, push A short while I pressure C from long",
    "I am holding window on Split, someone push B main while I watch window",
    "I am at ramp on Split and I have the angle, push A from outside while I cover ramp",
    "I am at A main on Haven, you take short and I will hold long simultaneously",
    "I am holding B heaven on Haven, push B main and I will cover from above",
    "I am at C heaven on Haven, someone take C main from below while I watch from top",
    "I am crossing mid on Split, flash the screens before I commit to the cross",
    "I am at mid top on Split and I have the angle down, push B from below while I cover",
    "I am at A link on Fracture, go right side while I push from left side",
    "I am at B arcade on Pearl, you push B main and I will cover from arcade",
    "I am taking Pearl mid from attacker side, push B main when I confirm mid control",
    "I am at A art on Pearl, push through mid while I hold this angle",
    "I am holding A heaven on Fracture, you push A main from your side",
    "I am at B rope on Fracture, push B from your side and I will push from rope",

    # === SELF-STATUS WHILE GIVING ECONOMY DIRECTIVE ===
    "I am buying Op this round and I need you to buy armor since I cannot afford both",
    "I am the one full buying and you should also full buy, do not eco when I am buying",
    "I am on eco this round and I need someone who full bought to entry for me",
    "I spent everything on util and I need you to carry the rifle fights this round",
    "I have credits to drop someone a Vandal, who needs a gun, call out",
    "I am going glass cannon with Op and no armor this round, play around me carefully",
    "I saved last round and I can full buy now, but you should also buy not eco",
    "I bought the Outlaw as a budget Op and I am holding long, you take the close fights",
    "I am on the Ares for spray through smokes, you play outside the smoke with rifles",
    "I went Spectre on this bonus round, I need someone with a rifle to go first",
    "I am buying heavy armor and all util but only a pistol, someone give me a rifle",
    "I have enough to drop two rifles, call out who needs guns before buy phase ends",
    "I bought a Guardian for long range, keep me off close angles, you handle close",
    "I have the Stinger and I know you have a rifle, let me flank and you take front",
    "I bought the Bucky for the bathroom, let me go in the narrow corridor first",

    # === SELF + CONDITIONAL BASED ON TEAMMATE ACTION ===
    "I will entry if you flash, if you do not flash I will not go in",
    "I will rotate to B if you confirm there is nobody on A, do not guess, confirm",
    "I will plant if someone covers heaven, if heaven is not covered I am not planting",
    "I will anchor if you rotate, if you rotate I hold, if you do not rotate I also rotate",
    "I will use my ult if you commit to the execute, do not ask me to ult and then bail",
    "I will drone if you wait for me, if you push before my drone is done you waste it",
    "I will stay alive if you give me a smoke, if no smoke I am dying on this cross",
    "I will hold the clutch if everyone stays quiet, one callout and I lose this",
    "I will push on the stun if you throw the stun, if you do not throw it I am holding",
    "I will help on retake if you tell me the spike location, call it before you die",
    "I will wall the entry if you let me set up first, push only after my wall is up",
    "I will send seekers if you wait, if you push before they home in they miss",
    "I will take the first duel if you second-entry behind me, do not hang back further",
    "I will do the fake if you are ready to go B, call ready when you are in position",
    "I will bathe them in decay if you push right after, do not wait for the decay to finish",

    # === HARD FIRST-PERSON WITH EXPLICIT SUBJECT CLARIFICATION ===
    "tell them I am going in, not them, I am the one making the play right now",
    "let my team know I have the information, not a teammate, I saw where they are",
    "tell them it is me holding A, not them, I am alive on site",
    "let the team know I am the one with the Op, not the enemy, I picked it up",
    "tell them I am the one they should rotate to, I am alive and in position",
    "let them know I am the entry this round, not our Jett, I am calling myself entry",
    "tell them I am the one that planted the spike, I have it down on A",
    "let my team know I am the last alive, I am not dead yet, let me work",
    "tell them I am the one watching flank, I have that covered, you play site",
    "let the squad know I am the anchor, I stayed, I did not rotate, I am on site",
    "tell them I am the lurker, I am on their side of the map right now",
    "let my team know I am the one with ult, I have it charged, ask me to pop it",
    "tell them I am the player holding heaven, I did not leave that angle",
    "let the team know I am defusing right now, nobody else touch the spike",
    "tell them I am the one who called it, I take responsibility for this round",

    # === STREAMER SELF-COACHING RELAYED AS DIRECTIVE ===
    "tell my team I am going to stop peeking dry and start using my flashes better",
    "let them know I am going to play tighter this half and not give away free peeks",
    "tell the team I am calling a slower tempo this round so nobody rushes",
    "let them know I am trying a new position this round so adjust your reads",
    "tell my team I am going to anchor harder and not rotate so early",
    "let the team know I am going to hold ult for the clutch, do not ask me to pop early",
    "tell them I am going to play off information this round rather than forcing",
    "let my team know I am going to comm more clearly this half so listen for my calls",
    "tell the team I am setting up a crossfire this round and I need someone on the second angle",
    "let them know I am taking a more passive role this round and farming information",
    "tell my team I am going to play lurk and I need them to make noise front",
    "let the team know I am the IGL this round and I want everyone to follow my calls",
    "tell them I am baiting the early peek to gather info before committing the team",
    "let my team know I am playing for a late pick and I need patience from everyone",
    "tell the team I am reading their patterns and my call for this round is execute B",

    # === SELF-REPORT WITH TIMING + DIRECTIVE ===
    "I will have my flash back in 5 seconds, hold the execute until I reload",
    "I am 3 seconds away from site, delay the push until I arrive",
    "I need 10 seconds to rotate, keep them occupied on A until I get there",
    "I will have my Op ready in 2 seconds, do not peek until I am set",
    "I am 15 seconds out from B, stall them at the choke until I rotate",
    "I need 30 seconds for my smokes to recharge, play passive until then",
    "I am running to the plant position right now, cover me for the next 5 seconds",
    "I will detonate my drone in 3 seconds, rush in the moment it goes off",
    "I need 7 seconds for my pit cloud to fully form, plant after 7 seconds not before",
    "I am going to throw the recon in 2 seconds, be ready to push on the scan",
    "I will activate the lockdown right now, protect it for the next 13 seconds",
    "I need 4 seconds to heal up with Sage's orb, hold the line for 4 seconds",
    "I am going to pop my ult in 5 seconds, coordinate your push with my ult timing",
    "I will flash in 3 seconds, count it down and swing on 1",
    "I need 6 seconds for the pit cloud to clear if I move out, hold the site until then",

    # === FINAL BATCH: HARD MIXED-AXIS CASES ===
    "I am the only person alive and I have the spike unplanted, let the round play out in silence",
    "I am Clove, I just triggered Not Dead Yet, I have 10 seconds, do not steal the kill I need",
    "I am the one who knows their Cypher cam position, let me shoot it before we push",
    "I am at 1 HP, I have the Op, I am holding B long, do not expect me to survive a trade",
    "I have the Vandal and no util bought and I am going to entry, someone flash me in",
    "I am the one Breach is faulting for, close your eyes after I warn you and push on my call",
    "I am going aggressive and I need you to play passive, do not both go aggressive",
    "I am the info player today and I will call positions but I need silence when I do",
    "I took their Op off the ground and I am holding B long now, you push A",
    "I have both Curveball flashes and I am Phoenix, let me flash the whole site twice",
    "I am taking the first duel intentionally to bait their util, do not follow until I am dead",
    "I have the spike and I have no armor and I have 20 HP, someone shield me",
    "I am using my Kill Contract on their entry fragger right now, push while they are in the arena",
    "I am alive in post-plant and I have my orbital queued on the spike, call when they defuse",
    "I am Astra and I need to enter astral form, keep me safe from flanks for 3 seconds",
    "I have one smoke left and I am going to use it for the cross, you push through it",
    "I am the one being hunted by their Prowlers, I am Fade-trailed, they can find me",
    "I am at the off-angle they never check and I will call if they push through main",
    "I have the stim beacon down at plant, everyone stand in the blue circle for the buff",
    "I am running a jiggle peek right now to bait his Op shot, swing for real when he fires",
    "I am Waylay and I dashed to the aerial angle, I am above them, they will not expect it",
    "I have both Blast Packs left and I will rocket-jump to the roof, someone cover the landing",
    "I am at 5 HP and I am going to make noise to drain their util, let me sacrifice",
]
