"""Relay corpus: stress_slang_runons (kind=relay, ~600 cases).

CHARGE: Heavy slang + run-on multi-clause callouts — facts must survive through
colloquial noise. Every item is a realistic streamer utterance heavy with gamer
slang, filler words, run-on structure, and embedded facts. The pipeline must strip
the slang wrapper and relay the core facts faithfully.

Metrics stressed:
  - fact-token retention p50/p95/p99 (counts, agents, locations, abilities, ownership)
  - compound zero-fact-loss (multiple facts chained with 'like', 'and', 'bro', 'yo')
  - ownership/subject inversion (our vs their buried in slang)
  - hallucinated-specific rate (streamer says 'like 80' — don't invent a number)
  - ecobleed (eco/save/force blurred by slang like 'just yolo', 'going in dry')
  - identity-leak (streamer narrates to chat vs commands team)
  - false-relay (narration that mimics relay but must NOT relay)
  - flavor presence (Ultron persona must survive slang rephrasing)

Slang exercised: yo, bro, fam, ngl, lowkey, highkey, cracked, lit, goated,
cooked, cooked bro, no cap, sheesh, ight, aight, fr fr, bussin, it's giving,
slept on, just dead, gone, deleted, diff, diff'd, on god, actually insane,
not gonna lie, deadass, bussing, NPC, vibing, glazing, glazed, throwing,
inting, cooked, tweaking, sus, yeet, gigachad, ratio, L, W, slay, ate,
goes hard, goated, goober, cope, mid, dog, lowkey sauced, menacing, clean,
clean af, stupid good, stupid damage, stoopid, actually bussin, cooked him,
diff'd him, got deleted, got cooked, got yeeted, no chance, zero chance.

Run-on joiners: 'like', 'and', 'but', 'yo', 'bro', 'so', 'then', 'also',
'plus', 'ngl', 'fr', 'deadass', 'not gonna lie', 'like bro', 'yo bro'.
"""

ITEMS = [
    # ================================================================
    # ASCENT — heavy slang + run-on
    # ================================================================
    "yo tell them two guys are like dead in A main and one more is peeking wine bro",
    "ngl bro there's like three of them cracked on B main and their Jett has the op no cap",
    "yo fr fr tell my team their Killjoy has lockdown and she's like two orbs away from it actually",
    "bro deadass their Reyna is in empress right now and she's just deleting everyone on A site",
    "yo like four of them are just vibing on B and one dude is lowkey holding logs with a vandal bro",
    "ngl the Sova drone just came out of catwalk and it went all the way to A main and tagged me bro",
    "tell them bro the smoke on market door is fading like right now and nobody is covering it fr",
    "yo their Omen just teleported into garden and he's like just chilling there no cap",
    "bro their whole team is on A fr like all five of them just pushed A main with a Jett entry",
    "yo deadass the Killjoy turret in workshop is hitting me through the door and it's actually stupid bro",
    "ngl tell them we're saving this round our whole team is on eco and two guys have classics bro",
    "yo the Jett on their team literally just dashed into catwalk and she has an op it's not okay bro",
    "bro fr the recon bolt hit mid courtyard and tagged two of their guys like one of them is probably lit",
    "yo their Neon is actually insane bro she slid into B site and just deleted our Sage like one tap",
    "tell them bro two are pushing B main and one dude is lurking through market towards CT fr",
    "yo their Viper wall is like almost gone and the smoke on CT is fading like right now bro push",
    "ngl bro their whole eco team just rushed A main with judges and they're gonna diff us fr",
    "yo deadass the door on A is still up and their Reyna is holding behind it one shot bro",
    "bro they have Jett op on B main and the smoke is gone so it's wide open actually insane",
    "yo three of them are rotating off A like right now through garden towards B actually fr",
    "ngl the Killjoy lockdown is already planted and it's gonna pop in like three seconds bro run",
    "tell them yo their Iso just pulled someone into kill contract and now they're down to four fr",
    "bro the Sova recon hit heaven and tagged two people like their Jett is one shot prob no cap",
    "yo their Phoenix ult is up and he went run it back aggressive on A main bro not gonna lie that's lowkey scary",
    "ngl four of them are stacking A fr and one is lurking mid through the tiles area bro",
    "yo the Omen smoke on market is a one way bro like you can't see through it from our side at all",
    "bro their Raze just blasted into B site with satchels and planted the spike already deadass",
    "yo tell them fr their Astra has cosmic divide ready and she's about to cut B main in half",
    "ngl their Waylay dashed into A site twice and she placed her beacon at tree so she'll snap back bro",
    "yo three of them got cooked by our Brimstone orbital but two are still alive at back site fr",

    # ================================================================
    # HAVEN — heavy slang + run-on
    # ================================================================
    "yo bro tell them their whole team is just going C long and one person is faking A fr fr",
    "ngl deadass their Jett has an op on C long and she already deleted our entry like it's not looking good bro",
    "yo five of them went B site bro like all five I'm not even joking and it's gonna be a rush fr",
    "tell them bro the Breach just faulted through the double doors and it went all the way to garage it's insane",
    "yo their Reyna is at A heaven with a vandal and she's just holding the angle like a bot fr",
    "ngl bro two of them pushed garage and one more is lurking through mid towards B it's sus fr",
    "yo deadass the smoke on A short is gone and now there's like two people just sitting in sewer no cap",
    "bro tell them their Sage walled A long and that thing is still full hp like nobody touched it fr",
    "yo fr their Omen just TP'd into B site from out of nowhere and planted already bro that's cooked",
    "ngl three of them have rifles and two are on eco so they're gonna split it fr watch A and C",
    "yo their whole team is stacking C and they have a Skye with a dog out going into C site bro",
    "bro the Cypher cam is in nest and it's been there all game like our Sova needs to break it fr",
    "yo ngl one dude is lurking A long with a vandal and he's moving super slow like shift walking bro",
    "tell them bro two pushed A from sewer and one is peeking heaven stairs it's a split fr",
    "yo their Iso just ulted and pulled our Jett into a contract like she's gonna lose fr she's already tilting",
    "ngl bro the Skye bird is heading to C site and their whole team is pushing right behind it deadass",
    "yo four of them are rotating from C to B through CT right now and one is staying back to hold fr bro",
    "bro their Neon sprinted into garage and she already has fast lane walls up on B site fr that's lowkey cracked",
    "yo tell them the KAY/O knife landed in garage and suppressed like two or three people no cap that's huge",
    "ngl one of their guys is holding C platform with an op and nobody can push long while he's there fr bro",
    "yo their whole eco team has judges and they're gonna rush A short with a Reyna entry bro not gonna lie",
    "bro tell them two are on B and three rotated to C so B is short right now fr push it",
    "yo their Fade haunt is revealing mid courtyard and she knows exactly where our whole team is bro cooked",
    "ngl the Viper wall is splitting C long and it gives them a free plant if nobody pushes through fr",
    "yo two cracked players on their team are holding A heaven and hell simultaneously bro it's a free crossfire fr",
    "tell them bro their Yoru sent a clone running into garage and the real one is lurking C long fr fr",
    "yo their Killjoy lockdown got planted in B site and nobody is clearing it bro that's gonna pop fr",
    "ngl bro one person is holding A long cubby with a vandal and she already got two picks from there no cap",
    "yo fr the Breach flash went through the A long wall and blinded like three of our guys bro insane util",
    "tell them bro three rotated B and the spike is planted at B default and nobody knows where the last two are fr",

    # ================================================================
    # SPLIT — heavy slang + run-on
    # ================================================================
    "yo bro their Jett is up in A heaven with the op and she's holding the whole ramp approach fr fr",
    "ngl two of them are in mid mail and one is lurking through the vent towards A lower bro it's giving info",
    "yo deadass their Raze just satcheled up to A tower and she's like cracked from up there actually insane bro",
    "tell them bro the Sage wall on A main is broken and now three of them are just rushing through fr push",
    "yo fr their Killjoy put a nanoswarm on the default spike plant and it's gonna go off if you defuse bro",
    "ngl bro one dude is hiding in A screens and two are holding elbow and it's a free crossfire fr cooked",
    "yo their Breach aftershocked through the A screens wall and hit like three of our guys bro that's dirty fr",
    "tell them bro the Omen smokes on B heaven and B alley are fading like right now go rotate fr",
    "yo their Neon sprinted up B ramp with walls covering her and she's already on B site with the spike bro",
    "ngl the Sova recon hit B site and tagged two defenders like one is lowkey one shot fr push B",
    "yo bro two are holding B heaven with rifles and one more is in B hell waiting for a rope clutch fr",
    "tell them bro their whole team five stacked B and our Killjoy lockdown is the only thing that can stop it fr",
    "yo ngl one of their guys is ratting in A rafters and nobody knows he's there it's a free exit frag bro",
    "bro their KAY/O just threw his knife into A site and suppressed our Killjoy her turret is dead fr cooked",
    "yo fr three of them are walking up mid mail super slow and they have a Cypher with a cam in top mid bro",
    "ngl bro their Waylay placed her beacon at A screens and she's gonna snap back if anyone pushes her fr",
    "yo their Astra just activated cosmic divide cutting off A main from A site bro like nobody can cross fr",
    "tell them the Skye dog went through mid vent and it's heading to A lower and it already tagged someone bro fr",
    "yo bro two are on B and three rushed A and our whole team is mid right now like we're cooked fr",
    "ngl their Iso walked contingency wall forward on A ramp and two of our guys got suppressed bro that's diff",
    "yo fr their Reyna got empress activated on A site and she's just eating everyone no cap zero chance bro",
    "tell them bro one dude has an op in B heaven and the smoke is gone so B garage approach is completely exposed fr",
    "yo ngl their Yoru teleported from mid to B site and it's a fake and the real one is lurking A ramp bro cooked",
    "bro four of them are stacking A after the Breach flash and their Jett is gonna be first on site fr fr",
    "yo their Tejo just dropped special delivery on A screens and the drone is up in mid mail fr actually scary bro",
    "ngl bro the Viper pit is on B site and nobody can retake while it's active fr at least thirty seconds left",
    "yo two of them fell back from A and rotated through mid mail and they're pushing B from link fr bro",
    "tell them bro their Sage is rezzing someone in B rafters and she's not even protected she's just vibing fr",
    "yo the Phoenix ult is active on B site and he's in run it back taking insane duels bro don't let him frag fr",
    "ngl their Chamber has a trademark on B hell and a TP anchor at B heaven so he's two spots at once fr bro",

    # ================================================================
    # PEARL — heavy slang + run-on
    # ================================================================
    "yo bro four of them are full buying and they're about to execute A site with a Raze entry fr fr",
    "ngl tell them one dude is holding mid top link with an op and two more are lurking art bro not gonna lie",
    "yo their Fade just haunted B main and now they know exactly where our anchor is bro fr cooked",
    "tell them bro the Clove smokes are covering both A main and CT link and the wall is gone fr",
    "yo deadass their Reyna got like four kills in a row and she's still in empress bro zero chance fr",
    "ngl two pushed A link and one is holding B connector and they're splitting both sites fr it's actually insane",
    "yo bro tell them their Viper pit just dropped on A site and they planted default inside of it fr we can't retake",
    "yo their Gekko wingman is currently planting the spike on B site and their whole team is holding retake bro fr",
    "ngl the Sova drone went through A main and tagged two people like one is probably cracked hard fr bro",
    "yo bro four of them have vandals and one dude is on a marshal saving for op next round fr",
    "tell them bro the Cypher cam is watching mid top and they know every rotate we make fr cooked",
    "yo their KAY/O knife went into B main and suppressed like two or three of our guys bro that's huge fr",
    "ngl bro their Iso has his contingency wall pushing forward in A main and their Jett is dashing through fr",
    "yo fr three are stacking B and their Skye dog is going in first through the main bro watch out for the stun",
    "yo bro tell them the Killjoy bots are all over B site and there's a nanoswarm on the default plant fr cooked",
    "ngl their Waylay put her beacon at B connector and she's gonna snap back after she peeks fr don't chase",
    "yo deadass one of them is holding the art wall angle with a guardian and he's already got two picks bro fr",
    "tell them bro their Astra nova pulse is primed for B main and they're using it to entry fr watch the stun",
    "yo fr their whole team eco rushed A with judges and our Sage wall is the only thing slowing them down bro",
    "ngl bro two of them rotated off B real quick and they're pushing A link right now with their Reyna fr fr",

    # ================================================================
    # BREEZE — heavy slang + run-on
    # ================================================================
    "yo bro tell them three of them are pushing A hall and their Jett has the op and it's like wide open fr",
    "ngl one dude is holding B elbow with an op and two more are behind him in B main bro it's a stacked peek fr",
    "yo deadass their Viper wall is cutting mid from spawn and nobody can cross without taking damage fr bro",
    "tell them bro the Omen smokes are covering A cave and CT and now they're going A with like four people fr",
    "yo fr fr their Raze roomba came out of A hall and it's heading to site and it's gonna explode fr dodge it bro",
    "ngl bro their whole team is doing a slow push through mid and their Fade dog is scouting canvas fr cooked",
    "yo three of them have rifles and two are on eco but they're forcing it with judges fr their eco is diff bro",
    "tell them bro the KAY/O knife landed in A site and suppressed our Killjoy and her whole setup bro fr disaster",
    "yo their Neon is sprinting through B main with walls covering her and she's gonna get a free entry fr cooked bro",
    "ngl two are on A and three pushed B elbow with an op holding B lobby it's giving prison vibes fr bro",
    "yo bro tell them the Cypher cam is in the alcove above mid and it's been watching everything fr cooked",
    "yo their Jett dashed all the way to A cave and she's lurking from there with an op it's not okay fr bro",
    "ngl bro their Skye seekers are heading to our positions and one of them is gonna lock on fr heads up",
    "yo deadass four of them stacked B and one dude faked A so hard with a full Brimstone smoke package fr",
    "tell them bro the Viper snake bites are on the default B plant like two of them and defuse is gonna hurt fr",
    "yo fr their Iso just ulted and pulled our Chamber into a 1v1 and honestly our Chamber is cooked bro no cap",
    "ngl bro three are pushing A and one is lurking through mid and one is holding B elbow it's a three lane spread fr",
    "yo their Sage walled off B lobby and now their whole team is slow pushing through B elbow fr deadass bro",
    "tell them bro their Astra gravity well is set up in A hall and it's gonna pull you into it if you push fr",
    "yo ngl two of them are holding mid with Operators and their whole economy is just op diff fr no cap bro",

    # ================================================================
    # LOTUS — heavy slang + run-on
    # ================================================================
    "yo bro their Jett has the op on A main and two more are lurking through canopy and it's like insane fr",
    "ngl deadass tell them three rushed C through mound and they have a KAY/O who just threw his knife fr fr",
    "yo five of them stacked B and our whole team is spread out fr this is gonna be a nightmare bro cooked",
    "tell them bro the rotating door is already open and they're pushing through B to C right now fr cooked",
    "yo their Fade prowlers are going through the A tunnel and they're gonna lock on bro fr don't peek it",
    "ngl bro their whole team is forcing this round with Spectres and armor and they have like 2k each fr",
    "yo deadass one dude is holding B root with a guardian and two more are behind him in B main bro fr fr",
    "tell them bro the Clove smoke is covering the C link and she can still resmoke it after she dies fr cooked",
    "yo their Raze just satcheled into A site from canopy and planted already and she has showstopper ready fr bro",
    "ngl two are lurking through the back hallways and three are pushing A loud with a Breach flash fr bro",
    "yo bro tell them the Killjoy lockdown is planted somewhere on B site and it's gonna pop fr nobody stop it",
    "yo fr their Omen TP'd into C link from spawn and he's lurking with a vandal bro that's actually scary fr",
    "ngl bro one is holding A heaven with an op and two more are covering the push from tree bro it's a crossfire fr",
    "yo deadass their Skye and Tejo combo is like the hardest combo to deal with and they're executing B fr bro",
    "tell them bro their Viper wall is splitting A from C and they're just walking through on C side fr cooked",
    "yo fr their Iso has full kit and their Jett has an op and they're both stacked mid fr it's a diff bro",
    "ngl three of them have their ults ready and they're gonna use all of them on A this round bro fr insane",
    "yo bro their Sage just rezzed their Reyna on B site and now she's back in empress fr we're cooked deadass",
    "tell them bro four are pushing C and one dude is holding A just to waste our time fr fake rotate bro",
    "yo ngl their Waylay beaconed at B root and she's gonna dash in and snap back if it goes wrong fr annoying bro",

    # ================================================================
    # FRACTURE — heavy slang + run-on
    # ================================================================
    "yo bro fr three of them came from A rope and two came from B and they're pinching us fr cooked bro",
    "ngl tell them their Neon sprinted through the zipline at A and she's already on A main bro that's fast fr",
    "yo deadass their Brimstone dropped three smokes on B site and their Raze is boosting in with satchels fr",
    "tell them bro the KAY/O knife went into A arcade and it suppressed like four abilities at once fr that's cracked bro",
    "yo fr their Breach rolled thunder from T rope all the way through the connector and it hit two of us bro insane",
    "ngl bro two from T side and three from CT side are pinching B at the same time it's a classic fracture split fr",
    "yo their Omen just TP'd from CT to A drop and he's flanking our whole team from behind fr bro cooked",
    "tell them bro the Viper wall is up across the middle and they're splitting both halves independently fr diff",
    "yo fr fr one is holding A main with an op and he's already got one kill and his Jett team is covering him bro",
    "ngl their Fade nightfall is going off right now in B site and it's deafening and decaying everyone bro fr run",
    "yo bro tell them three are eco rushing A and two are holding B to get picks fr watch for the Reyna entry",
    "yo their Tejo dropped an armageddon on B site and it went through the walls fr nobody can plant bro cooked",
    "ngl two pushed A rope and one lurked through the T connector and two are holding CT side with rifles bro fr",
    "yo deadass their Killjoy has alarmbot and two nanoswarms on the B default plant like that's disgusting fr bro",
    "tell them bro the Jett and Raze are double entry fragging A and they're coordinating their movement ults fr",
    "yo fr their Skye dog went through A connector and it concussed our Sage before she could wall fr cooked bro",
    "ngl bro one is in the A secret area and nobody knows he's there and he's been there since round start fr spooky",
    "yo their Iso sent the contingency wall through the B chokepoint and it's pushing everyone back fr bro",
    "tell them bro three have rifles and two are on eco but they have Reyna who can snowball fr watch the entry",
    "yo ngl their whole team is low because our Brimstone orbital hit the B default and got like three of them bro fr",

    # ================================================================
    # ECONOMY / ECO SLANG — heavy run-on
    # ================================================================
    "yo bro tell them we should full save this round fr like everyone needs to not buy anything no cap",
    "ngl deadass their whole team is on eco right now like all five have classics or pistols bro rush them",
    "yo fr tell my team we're forcing this round everyone buy a spectre and light armor and we go A bro",
    "bro ngl their eco team has judges and they're gonna rush B with like five judges it's a valid strat fr cooked",
    "yo tell them we're on a three round loss streak bro so we have max loss bonus and we can full buy next fr",
    "ngl fr bro their Jett dropped the op and if we can pick it up this whole round is actually a W economically",
    "yo deadass our team has no money bro like three people have under a thousand credits fr we need to save",
    "tell them bro their team full bought and we're on eco so we should just plant spike and save guns fr fr",
    "yo ngl two of our guys can buy rifles but three can't so we need drops or we force with Spectres bro",
    "bro fr their team is doing an anti-eco setup with Spectres because they think we're saving fr smart plays bro",
    "yo tell them the round we just won gave us the spike plant bonus so everyone has like extra three hundred bro fr",
    "ngl deadass their Jett has an op on eco and she's basically a glass cannon bro one body shot and it's gone fr",
    "yo bro the enemy team is on their second consecutive save so they're getting like 2400 loss bonus fr careful",
    "tell them fr fr we should force a half buy with marshals this round and play for picks bro don't die fr",
    "yo ngl bro their econ is cooked they lost like three guns last round so they're all on pistols fr push hard",
    "yo deadass the thrifty medal is in reach if we win this with Spectres against their full buy bro fr fr",
    "ngl bro if our Jett dies with the op that's like 4700 credits gone fr please save the gun if you can't win",
    "tell them yo we should drop one rifle to our Reyna she's at like 1200 credits and she can snowball fr bro",
    "yo fr their two kills got them each 200 so they might be able to force next round bro keep that in mind",
    "ngl bro one of their guys saved his vandal and the rest eco'd so it's like a split buy for them fr weird strat",

    # ================================================================
    # ABILITY / UTILITY STATUS — heavy slang
    # ================================================================
    "yo bro tell them the Sova recon is going to hit A site in like two seconds so don't be exposed fr fr",
    "ngl their Killjoy turret in workshop has been hitting me through the door this whole round bro it's cooked fr",
    "yo fr the Fade haunt is in the air above mid and it's about to reveal all of us bro don't be in the open",
    "tell them bro the Breach flash went through the wall and it's coming from A main direction fr look away bro",
    "yo deadass their Viper snake bite is on the B default plant like right in the middle fr don't defuse yet bro",
    "ngl bro the Skye bird just popped in B main and flashed like three of our guys fr and now they're rushing",
    "yo their KAY/O just threw his knife and it suppressed our Sage so she can't wall or heal fr that's cracked bro",
    "tell them bro the Raze roomba is heading our way through A main and it's gonna lock on fr dodge or shoot it",
    "yo fr their Omen paranoia is going through mid and it's gonna nearsight the whole team bro don't peek it",
    "ngl bro one Cypher trap is on A sewer and one is on garden and they know every time we rotate fr cooked",
    "yo their Astra pulled a gravity well in B main and then nova pulsed it fr that combo is actually insane bro",
    "tell them bro the Clove smoke is still active even though she's dead because she can resmoke from death fr",
    "yo deadass the Killjoy lockdown radius covers all of A site and it's gonna pop fr nobody defuse yet bro",
    "ngl bro the Tejo guided salvo hit B main and it concussed like four people it's actually diff fr no cap",
    "yo their Vyse steel garden is active and forced all five of our team to switch to sidearms fr bro cooked",
    "tell them bro the Deadlock grav net is somewhere on B site and it'll force you to crouch fr watch out",
    "yo fr the Iso wall is pushing through A ramp and it blocks bullets on both sides fr their entry is safe bro",
    "ngl bro the Waylay just used convergent paths and she has that speed boost up fr don't duel her right now",
    "yo their Harbor used reckoning on B site and the geysers are everywhere fr nobody can hold angles bro",
    "tell them bro the Veto evolution is active and that guy literally cannot be debuffed or slowed right now fr scary",

    # ================================================================
    # ULT STATES — heavy slang
    # ================================================================
    "yo bro their Reyna empress is up and she's like two kills away from losing it but she's snowballing fr fr",
    "ngl tell them their Killjoy lockdown is ready this round and they're gonna use it on execute fr save your ults",
    "yo deadass their Jett blade storm is up and she's gonna try to op-snipe from catwalk this round bro fr",
    "tell them bro our Sage has rez ready and she's gonna bring someone back if we get a pick fr good timing",
    "yo fr the Phoenix run it back is up so he's gonna take insane peeks this round bro don't let him frag out fr",
    "ngl bro their Yoru dimensional drift is active right now he's invisible and scouting our positions fr spooky",
    "yo their Raze showstopper is up and she's been holding it for like four rounds bro it's gonna pop fr fr",
    "tell them bro the Viper pit is coming down on A site this round fr their whole execute is built around it bro",
    "yo deadass the KAY/O null cmd is up and he's gonna suppress the whole team during execute fr that's cracked bro",
    "ngl fr bro the Sova hunter's fury has been saved for like three rounds and she's gonna use three blasts fr fr",
    "yo their Breach rolling thunder is up and it's gonna clear A main entry bro their execute is gonna be clean fr",
    "tell them bro the Iso kill contract is up and he's gonna pull our best player into a 1v1 fr hope they're cracked bro",
    "yo ngl the Harbor reckoning is up and it's gonna stun the whole retake fr nobody can retake while it's active bro",
    "bro fr their Astra cosmic divide is ready and she's about to cut the whole map in half fr game changing bro",
    "yo their Chamber tour de force is up and he's been positioning near B heaven for an op angle fr cooked bro",
    "tell them bro our Killjoy lockdown is ready and if we execute A this round it's a free plant fr let's go bro",
    "yo deadass their Gekko thrash is heading towards our side and it's gonna detain someone fr shoot it bro fr",
    "ngl bro the Clove not dead yet is up and she's gonna revive herself if she dies and the team plants fr scary",
    "yo fr the Fade nightfall is being held for the execute and it's gonna deafen and decay everyone on site bro",
    "tell them bro the Neon overdrive is up and she's gonna sprint beam everyone fr nobody can out-aim that bro",

    # ================================================================
    # DAMAGE / TRADE SLANG — run-on
    # ================================================================
    "yo bro I hit him for like 80 something and he's probably one shot fr somebody push him in A main now",
    "ngl deadass I tagged the Jett in A main for like 60 and she used dash but she's lowkey one shot bro fr",
    "yo fr I dinked the guy at B logs like full headshot and he's probably at like 1 hp fr somebody finish him",
    "tell them bro I traded that guy at A site and the one behind him is still alive but cracked hard fr push",
    "yo their Reyna got a soul off our guy and she healed back up to like full hp bro she's not one shot fr",
    "ngl bro I hit him through the B door with like 70 wallbang damage and he's definitely one shot fr go in",
    "yo fr I shot the Neon through the Viper wall and got like 58 damage fr she's lowkey lit go finish her bro",
    "tell them bro I dinkd the op player at B heaven and he's one shot but he's on high ground fr be careful",
    "yo deadass I got trade killed so that's even but the one who killed my teammate is cracked bro like one shot fr",
    "ngl I two tapped the Raze with my Vandal and she dismissed fr so she's alive but on like 1 hp bro fr fr",
    "yo bro I prefire the corner and hit him for 76 and I think he has light armor fr so he's one shot no cap",
    "tell them fr the Breach came around the corner and I hit him for 90 headshot but I died to his fault line bro fr",
    "yo their Reyna is like six kills in and she's probably full hp because she keeps devouring bro fr careful",
    "ngl bro I shot through the B triple box and hit someone for like 40 fr someone peek that position now bro",
    "yo fr I whiffed the easiest shot of my life on the Jett and she dashed away but I think I hit her for like 20 bro",
    "tell them bro their whole team is cracked like every single one of them can one tap fr our aim needs to diff bro",
    "yo ngl I died immediately but I got trade so it's like even and the next two alive are cracked bro fr fr",
    "bro fr I hit the guy at A peek for 80 and my team walked away and now he's full healed bro waste fr fr",
    "yo their Iso has that double tap shield active and he absorbed one hit already so he's not as fragile fr bro",
    "tell them bro I shot the Viper through her own wall from mid and got like 60 damage fr one more hit and she's gone bro",

    # ================================================================
    # POSITION / COUNT SLANG — run-on
    # ================================================================
    "yo bro fr fr like four of them are stacking A and one dude is holding B all alone fr push B now bro",
    "ngl tell them three are in garage and two of them have rifles and they're about to push C fr bro cooked",
    "yo deadass one is lurking somewhere and we can only find four of them bro the fifth is probably flanking fr",
    "tell them bro five of them just rushed B in like ten seconds fr that's a full send B bro no cap",
    "yo fr two are in A heaven and two in A hell and one more is holding garden fr that's a layered defense bro",
    "ngl bro one dude is holding the off angle in the cubby and everyone is pre-aiming the wrong spot fr cooked",
    "yo their anchoring Cypher has been sitting B site alone for like the whole round and he has a cam fr bro fr",
    "tell them bro three are walking mid super slow and they might be faking towards one site fr don't rotate yet bro",
    "yo fr one of their guys is camping in A screens and he's been there all round nobody has checked fr bro",
    "ngl bro two are pushing from A long and two from A short and one is coming from mid for a three way pinch fr",
    "yo their last player alive is somewhere on B site and the spike is planted and he's probably near the spike fr",
    "tell them bro I saw three at C and then they rotated to B through CT so now B might have five fr cooked bro",
    "yo ngl there's one dude deep in A back site and everyone walked past him fr he's gonna get the ninja defuse bro",
    "bro fr fr one is peeking and retreating and the two behind him are ready to trade fr it's a classic bait bro",
    "yo their whole team is grouped up in B main and our molly can literally clear five people fr use it now bro",
    "tell them bro two rotated off C long and they're pushing mid now and C is probably open fr fake rotate bro",
    "yo fr one of them is boosted up on a weird angle at A site and nobody expects him to be there fr off angle bro",
    "ngl bro three of them pushed aggressive mid in round two and took complete map control fr they're playing default bro",
    "yo one is at B heaven and one is at B alley and the third is holding CT stairs fr three different angles bro fr",
    "tell them bro their Yoru sent a gate to A main and everyone is gonna think he's teleporting there fr don't react bro",

    # ================================================================
    # ROTATION / MOVEMENT SLANG
    # ================================================================
    "yo bro tell them to rotate B right now like right now four of them are already entering site fr fr",
    "ngl deadass two rotated off A super early and they're pushing mid to B fr A is wide open go plant bro",
    "yo fr fr their whole team fake rotated to A and they're actually gonna hit C fr don't fall for it bro",
    "tell them bro don't rotate off B yet we don't have enough info and C might be a fake fr hold bro fr",
    "yo ngl one lurker is watching our rotations through Cypher cam and calling our moves fr cooked bro",
    "bro fr one of them is playing for late picks in CT hallway and they're burning our clock fr don't rush bro",
    "yo their Omen is using his TP to fake rotate to A while the rest of the team hits B fr classic bro fr",
    "tell them bro three already rotated from A through garden and they're entering B from CT stairs fr fr cooked",
    "yo deadass their rotation speed is crazy because they have Clove smoking from death fr they never stop bro",
    "ngl bro one gave up A long and rotated to CT really early and it opened up A for like fifteen seconds fr push",
    "yo fr tell them stop rotating every time you hear footsteps bro they're faking the rotation fr hold positions",
    "tell them bro one fell back from C platform to CT and now C is wide open for like ten seconds fr push it bro",
    "yo their Yoru fake gate in B main caused two of our guys to rotate off A fr exactly what he wanted bro fr",
    "ngl bro their whole defense rotated to A because of the Raze fake and now B is completely unguarded fr cooked",
    "yo two are pushing through mid really slow and they're setting up for a split between A and B fr fr bro",
    "tell them bro their rotation time is like seven seconds from CT to B so don't plant til they're dead fr",
    "yo ngl the fast rotate from B to A through CT is only like six seconds for them fr push before they get there bro",
    "bro fr fr they have a lurker watching mid every round and she calls all our rotations fr cooked information diff bro",
    "yo tell them we need to fake rotate to A and then full send B fr their anchor is calling our movement bro fr",
    "ngl bro they rotated three to B and left two on A so it's either a fake or they genuinely think we're going B fr",

    # ================================================================
    # SPIKE / PLANT / DEFUSE SLANG
    # ================================================================
    "yo bro fr tell them somebody needs to pick up the spike bro it's just sitting there in A main fr",
    "ngl deadass our Gekko wingman is planting the spike right now and we need to cover the two angles fr bro",
    "yo their Gekko wingman is defusing our spike right now fr like actually right now bro stop him fr fr",
    "tell them bro plant it behind the generator it's the safest plant for post plant fr and two of us hold tree bro",
    "yo fr fr one of them just started defusing and nobody is on it bro like go stop it now fr cooked",
    "ngl bro they planted default on B and there's a KJ nanoswarm on the spike so defusing is gonna hurt fr",
    "yo deadass they ninja planted in A back site and nobody saw it happen fr our Cypher cam wasn't watching bro",
    "tell them bro we need to fake defuse like tap the spike once and see if anyone peeks fr classic mind game bro",
    "yo fr the spike is at thirty seconds and there's still two alive on their team and a molly on it fr bro",
    "ngl bro they planted for the tree angle which means we need to come from garden to defuse safely fr cooked",
    "yo their Viper snake bite is literally sitting on top of the spike fr someone needs to either wait it out or eat it bro",
    "tell them bro thirty seconds on spike and we still have three alive so full commit retake fr go bro fr",
    "yo ngl the wingman plant just finished and we have forty seconds and only two of them are alive fr clean retake bro",
    "bro fr fr someone tap the spike once to bait the Reyna out of her corner and then swing her fr",
    "yo their whole post plant setup is a crossfire from A tree and A heaven fr we need to come from garden bro fr",
    "tell them bro they planted it deep in B workshop and it's completely covered fr we need a KJ lockdown to clear it bro",
    "yo deadass the spike at B default has a Clove molly on it and a KJ nanoswarm fr we need util to defuse bro fr",
    "ngl bro they planted it on A site and the timer is at forty five seconds fr we need to full commit retake now bro",
    "yo fr the spike is planted for the main angle so whoever holds main gets the post plant crossfire bro fr",
    "tell them bro if we fake defuse and they peek we can swing them fr but if they don't peek we need to stick it bro",

    # ================================================================
    # BANTER / OPINION — still relay-shaped commands
    # ================================================================
    "yo bro tell them their Reyna is actually just inting like she's feeding kills and not using her souls at all fr",
    "ngl fr fr their Jett thinks she's cracked with the op but she's missed like four shots this round bro diff fr",
    "yo tell my team their KAY/O is actually goated and he's been suppressing abilities every single round fr fr bro",
    "bro deadass that Sage wall on A main was the cleanest wall I've seen in a minute fr actually bussin bro",
    "yo ngl their Raze just used showstopper for one kill and wasted it fr that's genuinely cooked decision making bro",
    "tell them bro their Omen plays the same spot every round like every single round fr anti-strat him fr fr",
    "yo fr their Iso is a gigachad like he won two kill contracts this match fr actually diff bro no cap",
    "ngl bro their Chamber has been holding B heaven op every single round like every round and nobody checks him fr",
    "yo tell them our Killjoy is literally carrying this match fr like every round she has three piece fr actually insane bro",
    "bro fr their Viper wall placements are actually stupid like she keeps walling herself in fr cooked controller bro",
    "yo ngl the Tejo on their team is actually criminally underrated like he's been doing like 230 ACS fr diff bro",
    "tell them bro our Skye has been guiding light flashing every entry and it's actually been the perfect timing fr fr",
    "yo fr their Yoru is a menace bro like he faked three rotations this match and got picks every time fr actually scary",
    "ngl bro tell them their Fade is lowkey goated for this map her haunt to prowler combo keeps hitting fr no cap bro",
    "yo the Harbor on their team is actually trolling bro like he walled his own teammates twice fr cooked fr",
    "tell them bro their Neon is running around like she has an actually insane eDPI and she keeps hitting shots fr diff",
    "yo ngl their Iso won three kill contracts bro he's just built different fr like nobody can beat him in a 1v1",
    "bro fr fr their Waylay is so annoying because she keeps beaconing and snapping back and nobody can finish her bro",
    "yo tell them their Astra is goated at smokes but she's not converting her gravity wells into kills fr wasted util bro",
    "ngl bro their Brimstone keeps stiming his own team before every execute and it's actually cracked fr no cap",

    # ================================================================
    # PLAYSTYLE READS — relay-shaped run-ons
    # ================================================================
    "yo bro tell them their whole team plays A every round on defense and B is always like one person fr split it",
    "ngl fr their Jett always pushes mid catwalk early round every single game fr counter peek her bro",
    "yo deadass their Cypher always puts his cam in the same spot in B main fr our Sova should shock dart it bro fr",
    "tell them bro they stack A every time we have Jett and Raze on attack so fake A and hit B fr fr bro",
    "yo fr their Reyna entry frags alone every round and her team just follows bro time the trade fr cooked bro",
    "ngl bro their IGL always calls a B execute when we go default for thirty seconds fr get ready for B bro",
    "yo ngl their lurker always goes through mid at the same time every round fr KAY/O knife mid should stop him fr",
    "tell them bro they're running the same Breach Raze A execute every single attack round fr anti-strat time bro",
    "yo fr their Killjoy always puts turret in the same corner at B fr destroy it with Sova shock dart bro fr fr",
    "ngl bro their Omen always TPs into garden on round start fr if we're holding garden we get a free pick bro",
    "yo their Sage walls the same spot on B every single round and everyone walks around it fr bro actually predictable fr",
    "tell them bro their Chamber has been TP anchoring between B heaven and B hell every round fr play for the TP bro",
    "yo fr they always send two to contest mid in round one and it's always the same two players fr punish it bro",
    "ngl bro their Yoru's gate is always going to A site and it's always real fr they're not faking fr shoot the gate bro",
    "yo their Astra keeps using cosmic divide to cut mid every single execute fr we need to go before she gets set fr",
    "tell them bro every time we go B their Viper drops her pit immediately and it's always in the same spot fr bro",
    "yo ngl their KAY/O always uses his knife from the same angle in garage fr peek him before he throws it bro fr",
    "bro fr their Raze satchels from B lobby to B heaven literally every round fr someone pre-aim that angle bro",
    "yo their Clove always uses ruse to smoke the same two spots fr we know the lineup now fr push through fr bro",
    "tell them bro their Breach always flashpoints through the same wall into A main entry fr look away when you see it fr",

    # ================================================================
    # MIXED HARD CASES — maximum slang + maximum fact density
    # ================================================================
    "yo bro ngl fr fr four of them are lit and cracked on A site with rifles and their Jett has op and lockdown is planted bro",
    "yo deadass tell them two are eco rushing B with judges and two more have full buys and one is lurking mid fr fr bro",
    "ngl bro tell them the Sova recon tagged their Reyna at A main for like thirty and she's in empress and one shot fr push",
    "yo their Iso has kill contract and his Jett has blade storm and they're both on site at the same time fr bro cooked",
    "bro fr deadass three of them are cracked lit players and they're executing B with full kit and KAY/O null fr actually diff",
    "yo tell them their Viper pit is active on B site and there's a nanoswarm on default and lockdown just popped fr fr bro",
    "ngl bro one dude is in A hell with a vandal and one is in A heaven with an op and one is lurking garden fr crossfire bro",
    "yo fr the Fade nightfall went off and deafened and decayed our whole team and now they're rushing with Raze rocket fr cooked bro",
    "tell them bro three of them rotated B from CT while their Jett is lurking A tree with an op and their Sage is rezzing fr fr",
    "yo deadass their eco team has judges and a Reyna who's snowballing and their Jett somehow saved her op fr bro fr cooked",
    "ngl bro the Skye seekers are locking on plus the Breach flash went through the wall and KAY/O knife is in the air fr diff bro",
    "yo fr fr two pushed catwalk and three pushed A main and they have Brimstone smokes on heaven and hell fr bro that's an execute",
    "tell them bro their Omen TPs are covering their Jett op angles on B main and the smokes are a one-way fr actually insane bro",
    "yo ngl the Killjoy lockdown radius covers A site and their Viper pit is up and two have rifles bro this retake is cooked fr",
    "bro deadass their Waylay beaconed at mid catwalk and dashed into A site and she's holding A from an off-angle fr spooky fr",
    "yo fr tell them five of them full sent B with a Neon entry sprint and Breach rolling thunder and KAY/O flash all at once bro fr",
    "ngl bro their Raze showstopper and Killjoy lockdown both popped on A site at the same time like that's actually insane fr cooked bro",
    "yo tell them one is one shot at B heaven with no armor and one is cracked at B hell with full kit fr bro completely different threats",
    "tell them bro their Astra cosmic divide cut mid and their Viper wall cut A main and nobody can enter either site fr cooked bro fr",
    "yo deadass the Cypher cam in nest and the Killjoy alarmbot on B default together create like perfect info fr bro actually insane util",

    # ================================================================
    # NARRATION TRAPS (false-relay — must NOT relay)
    # ================================================================
    "yo I keep thinking I should tell them there are two on B but they never listen to me bro fr fr",
    "ngl I was gonna say something about their Jett having the op but chat is distracting me fr bro",
    "yo fr I'm literally talking to chat right now but there are like three enemies on A bro I'll call it next round",
    "bro I know I should relay the info but honestly I'm so tilted right now fr not gonna lie",
    "yo deadass my teammate is so bad I want to tell them to rotate but what's the point bro they won't listen fr",
    "ngl fr I'm explaining to my viewers why you always eco after losing a full buy bro it's just math fr fr",
    "yo bro I could have relayed that there was an op on B but honestly I thought he'd miss fr my mistake",
    "bro fr fr I should have said something about their Killjoy setup like two rounds ago bro I just forgot fr",
    "yo I'm lowkey mumbling about their Reyna being cooked but it's not really a callout bro fr fr just venting",
    "ngl I'm telling chat about the Sova recon that hit us but I don't need to tell my team fr they saw it bro",
    "yo fr bro I keep wanting to roast their Jett but it's not a real callout it's just me being salty fr",
    "bro deadass I said to my viewers there are two on A but I didn't mean to relay it fr just narrating bro",
    "yo ngl I'm just thinking out loud about whether we should save this round fr not actually calling it bro fr",
    "tell chat bro that was the worst KAY/O knife placement I've seen in my life fr completely wasted it no cap",
    "yo fr I'm just rambling to my audience about how their Astra comp counters ours bro it's not a relay fr",
    "ngl bro I was gonna call out their Yoru gate but then I was like no I'll just vibe fr my bad team fr",
    "yo fr fr I told chat there are four on B but my teammates have eyes they can see it too fr not relaying bro",
    "bro I'm discussing with chat whether we should execute A or B next round fr it's a strategy discussion not a relay",
    "yo ngl I'm not actually calling anything I'm just freestyling to chat about how their eco is cooked fr fr bro",
    "deadass bro I said three are on C but I said it as a joke to chat not as a real callout fr don't relay it",

    # ================================================================
    # EDGE CASES — ambiguous relay vs. narration
    # ================================================================
    "yo bro like maybe someone should tell them there's a lurker in CT area fr I don't know if they heard me",
    "ngl fr I think we should be telling the team their Jett has no dash right now but fr whatever bro",
    "yo I'm kind of mumbling that their eco is cooked but I don't know if that warrants a relay fr bro",
    "bro fr the Killjoy has ult and I mentioned it but I don't know if my team actually heard me fr bro relay it",
    "yo ngl I keep saying there's two on A but my voice is so quiet they can't hear me fr someone relay it bro",
    "tell them bro or whatever I mean there's like four stacking B and one is lurking mid fr someone say it fr",
    "yo bro I'm calling it out but my mic might have cut fr relay it that there are three on A main fr fr",
    "ngl bro I whispered that the Sage wall was broken but I don't think anyone heard fr say it again fr",
    "yo fr like I'm pretty sure I said two are rotating but nobody rotated so maybe relay it again bro fr fr",
    "bro deadass I called the op at B heaven but with all the noise I don't think they heard fr say it again fr",

    # ================================================================
    # ADDITIONAL MIXED SLANG — filling to ~600
    # ================================================================
    "yo bro fr their Raze is just diff'ing our whole team with satchels from angles we didn't even think to check fr",
    "ngl tell them bro one of them is literally holding the most cracked off angle I've ever seen in logs fr cooked",
    "yo fr fr two are just vibing in B main and they're waiting for us to peek so they can prefire fr don't bro",
    "tell them bro their Phoenix flash curve is actually disgusting fr it goes around the corner perfectly every time bro fr",
    "yo ngl their Neon overdrive beam accuracy is actually insane fr she's beaming while sprinting fr stupid fr bro",
    "bro deadass the Sova drone got me tagged and I'm lowkey one shot so I'm not gonna push fr tell them bro",
    "yo fr their Skye is sending dog through every corner before her team pushes fr it's actually goated utility bro",
    "tell them bro one is camping the flower pot spot on A and everyone is walking past him fr it's a ninja fr",
    "yo ngl fr fr their Iso is literally playing like a 1v9 this match and his kill contract is up and ready bro",
    "bro their Viper wall lineup for B execute is actually insane like it covers both B main and market door fr fr bro",
    "yo fr the Sage rez went off in A rafters and now they have five alive again after we killed four fr cooked bro",
    "tell them bro their Clove is actually cracked she keeps smoking from death and picking up souls fr non-stop bro fr",
    "yo ngl two of our guys are sitting at like 10 hp and three are full and they think they can push A fr cooked bro",
    "bro fr deadass their Tejo armageddon is going to land on B site in like two seconds fr get out of there bro fr",
    "yo fr fr their Deadlock annihilation grabbed two of our guys and nobody is freeing them fr they're just cooked bro",
    "tell them bro one anchored B with full kit and the other four rotated A fr B is basically a free peek fr bro",
    "yo ngl their Vyse steel garden popped and all five of us have sidearms only fr our vandals are useless bro fr",
    "bro their Veto evolution is so cracked fr he can't be debuffed or slowed and he has a vandal bro fr diff",
    "yo fr fr tell them two of them are lurkng through the vent and they have utility ready for a B execute bro fr",
    "ngl bro the Waylay saturated B main and everyone inside is hindered and slowed fr it's a free entry after bro fr",
    "yo tell them bro their whole team has ults ready this round like five ults at once fr that's an execute round fr",
    "bro deadass fr their KAY/O got revived during null cmd and he's back up and still suppressing bro fr cooked",
    "yo fr ngl one is holding A with an op and three are stacking B and one is lurking mid and they're all full buy bro",
    "tell them bro the Breach aftershock went through the B main wall and it's gonna pop in like two seconds bro fr dodge",
    "yo deadass their Reyna dismissed from my shot and she's back in empress and she's one kill from going infinite fr bro",
    "ngl bro tell them four of them are pushing with rifels and one eco player has a judge and she's the entry fr fr",
    "yo fr their Fade prowler chased our Jett through A ramps and nearsighted her fr she can't see anything bro fr cooked",
    "tell them bro their Omen is playing off-angles and he keeps one tapping from unexpected spots fr anti-camp him bro fr",
    "yo ngl the Harbor high tide wall is splitting A main and half of them are on each side of the wall fr fr bro",
    "bro deadass fr their whole eco rush has five judges and they're all going B garage at the same time bro fr cooked",
    "yo tell them fr fr one has an op and is lurking CT and two have rifles stacking A and two are eco on B fr diff",
    "ngl bro their Yoru sent a fake gate audio to A and his real gate went to B site fr he's actually smart bro fr",
    "yo fr their Gekko wingman defused the spike and Gekko retrieved him fr that's two defuse interactions from one ability bro",
    "tell them bro the Astra dissipated one smoke to put in the next location and now mid is open for like one second fr bro",
    "yo ngl deadass one is holding B heaven with a tour de force and he has trademark traps in B hell too fr chamber diff bro",
    "bro fr fr their Skye seekers locked on all five of our guys so they know every position we're in fr cooked bro fr",
    "yo their Iso contingency wall pushed through A ramp and it's blocking bullets fr their team is walking through safe fr bro",
    "tell them bro deadass their whole team is tilted and they're just gonna rush B next round I can feel it fr fr bro",

    # ================================================================
    # ADDITIONAL BATCH — reaching ~600
    # ================================================================

    # Pearl / Breeze extended
    "yo bro fr their whole team just full sent A art with a Raze satchel entry and KAY/O knife and it's not looking good fr",
    "ngl tell them bro two are holding mid top with Operators and they're basically unpushable without util fr cooked",
    "yo deadass three of them pushed through A link and they have a Fade haunt revealing our CT positions bro fr fr",
    "tell them bro the Killjoy lockdown covers all of B and our Sova is the only one who can break it fr drone the bot bro",
    "yo fr ngl their Tejo drone is sneaking through mid and it's about to do a sonar pulse fr shoot it bro fr fr",
    "bro their Viper pit dropped on B site and there's snake bite on the default and nobody can retake fr actually cooked fr",

    # Split extended
    "yo bro tell them one is holding A ramps off-angle with a guardian and nobody expects him there fr fr",
    "ngl deadass their Raze satcheled up to B heaven from B hell and she's got a free angle on our whole team bro fr",
    "yo fr the Sage walled A main but one of them shot it down from B side through the connector fr it's gone bro",
    "tell them bro three of them rushed A ramps at the same time and their Breach faulted through screens fr bro cooked fr",
    "yo ngl two are on B and three are lurking through mid vent and they're about to split A from behind fr fr bro",
    "bro their Killjoy alarmbot made our Jett vulnerable and she got deleted in A screens fr no way bro fr fr",

    # Haven extended
    "yo bro their Reyna just got triple kill at C long and she's in empress and walking to B fr cooked bro fr",
    "ngl fr their whole team stacked B and our anchor died so nobody is watching A long and C long fr go push fr",
    "yo tell them bro the Skye seekers locked on our whole team through the CT walls fr they know every position fr bro",
    "tell them bro two are pushing C from garage and two from C long and they're gonna pinch our guy on C fr bro",
    "yo fr ngl their Chamber trademark tripped our Reyna in A short and she's stuck moving super slow bro fr",
    "bro deadass their Yoru drift is active on A long and he's scouting our positions before the push fr cooked fr bro",

    # Ascent extended
    "yo bro fr their Omen smoke on market door is a perfect one-way and our whole team doesn't know fr tell them bro",
    "ngl tell them three full bought and two eco'd so they're doing a split economy execute which is weird fr bro fr",
    "yo deadass their Fade prowlers went into A main and nearsighted our Killjoy turret position fr that's dirty bro",
    "tell them bro one is holding B workshop with a vandal and he has an alarmbot covering him fr it's a two-layer trap bro",
    "yo fr their Sova shocked the triple box plant and hit someone for like sixty fr they know we're on B default bro fr",
    "ngl bro the mid door is broken and they used it to push through tiles and they're coming from pizza fr fr",

    # Lotus extended
    "yo bro tell them all three doors rotated and they went from C to A using the shortcut door fr fr cooked",
    "ngl their whole team has KAY/O in it and he's been suppressing our abilities every single execute fr diff bro fr",
    "yo deadass one is holding A heaven with a guardian and two more are in tree and it's a layered defense fr bro fr",
    "tell them bro three are rushing C mound with a Neon entry and she has fast lane walls covering her fr cooked bro fr",
    "yo fr their Viper used toxic screen through the long wall and it splits A from the back garden fr bro",
    "ngl bro the Gekko mosh pit is expanding on B root and nobody can hold that angle while it's active fr fr bro",

    # Fracture extended
    "yo bro both ziplines are being contested and they have two players on each side fr it's like a full fracture split fr",
    "ngl tell them their Omen TPs from CT side to attack side through the middle fr don't let him get that bro fr",
    "yo deadass their Raze and Jett are coordinating double entry through the rope and the zipline at the same time fr bro",
    "tell them bro the Breach rolling thunder is gonna push everyone off the B main area fr get off the default plant fr bro",
    "yo fr three are coming A with a Sova drone leading and two are faking B side fr anti-strat the drone first bro",
    "ngl bro their Tejo guided salvo hit both entrance points at once fr he fired both missiles simultaneously bro fr cooked",

    # WEAPON-SPECIFIC slang run-ons
    "yo bro their whole team has vandals except one guy who saved his op fr and he's holding the longest angle fr",
    "ngl tell them one dude has a spectre on anti-eco and he's actually running at us fr don't give him a free kill bro",
    "yo deadass their Jett has blade storm and she's using it like an op from catwalk fr it's actually accurate bro fr",
    "tell them bro two of them dropped their rifles when they died so it's free guns for us fr pick them up fr bro",
    "yo fr their Chamber has eight headhunter bullets loaded and he's one-tapping through heavy armor fr fr bro actually diff",
    "ngl bro their eco player bought a marshal and he's actually hitting shots from A main bro fr cracked fr",
    "yo tell them one dude saved his outlaw from last round and he's holding B main with it fr budget op bro fr fr",
    "bro fr fr their whole team is running Spectres except the Reyna who has a vandal fr it's a weird hybrid force bro",
    "yo ngl their Jett is running with no armor but has her op and it's glass cannon time bro fr fr classic fr",
    "tell them bro one teammate needs a rifle and he's at like 2900 credits fr drop him a phantom bro fr fr",

    # STATUS EFFECTS + DEBUFFS slang
    "yo bro the Iso undercut went through the wall and our Sage is fragile and suppressed fr she can't heal bro fr fr",
    "ngl their Waylay saturated the B entrance and everyone inside is hindered fr fire rate and movement is gutted bro fr",
    "yo deadass the Fade seize tethered our Killjoy and she can't move or use abilities fr she's just stuck there fr bro",
    "tell them bro the KAY/O suppression hit two of our guys fr their abilities are down for four seconds fr push now bro",
    "yo fr the Deadlock grav net hit A main and everyone inside has to crouch fr you can't jump or dodge fr bro cooked",
    "ngl bro the Veto chokehold decayed and deafened one of our players fr he literally can't hear footsteps bro fr fr",
    "yo their Neon relay bolt concussed B lobby fr everyone inside is stunned for three seconds fr rush it bro fr fr",
    "tell them bro the Reyna leer nearsighted three people who were holding garden fr they can't see anything bro fr cooked",
    "yo deadass the Breach fault line stunned our whole B push and now they're trading off the stun fr bro fr fr",
    "ngl bro the Clove meddle decay zone is on A main and our entry is rotting just standing in it fr fr",

    # RETAKE + CLUTCH slang
    "yo bro tell them one is alive on our team and the spike is planted and she's in a 1v2 fr actually clutch time bro",
    "ngl fr their last player is lurking somewhere on site and the spike has like twenty seconds fr find him bro fr fr",
    "yo deadass one of us can ninja defuse if the last two alive on their team are fighting each other fr fr bro",
    "tell them bro go silent right now our guy is clutching and dead players need to shut up fr no comms fr bro",
    "yo fr the last alive on our team has two alive against her and spike is at fifteen seconds bro play for time fr fr",
    "ngl bro she just tapped the spike to bait the Jett out and she's gonna swing the peek fr classic fake defuse bro",
    "yo their last player is holding the default plant angle with a vandal and spike has ten seconds fr just play time bro",
    "tell them bro stick the defuse we have time and it's a 1v1 retake fr don't stop the defuse bro fr commit it",
    "yo fr ngl our Reyna is in a 1v3 clutch and she's in empress and she has three souls to burn fr actually bro fr fr",
    "bro deadass the KAY/O got knocked down but he's revivable while null cmd is active fr rez him bro fr fr",

    # CROSSFIRE + SPLIT angles slang
    "yo bro their whole defense is running a double op crossfire on A long and sewer simultaneously fr bro fr fr cooked",
    "ngl tell them two are holding catwalk and tree at the same time fr it's a pinch fr we need to clear both fr bro",
    "yo deadass their B defense has one in heaven and one in hell and it's literally an instant crossfire fr bro fr",
    "tell them bro they have a crossfire set up from A screens and A elbow fr don't walk into it fr bro fr fr",
    "yo fr one is holding C platform and one is holding C long corner and anyone who enters gets two-way'd fr bro fr",
    "ngl bro one in A garden and one in A heaven means they cover the same spot from two different heights fr fr bro",
    "yo bro they planted for main angle so there's crossfire from main and B alley both covering the spike fr cooked fr",
    "tell them bro their whole post-plant has two in heaven two in hell and one lurking garden fr it's a nightmare retake bro",
    "yo ngl fr the Chamber TP anchor is between two positions so he's covering two crossfire spots at once fr bro diff fr",
    "bro fr fr a one-way smoke plus a lurker gives them a free two-man crossfire fr anti-strat the lurker first bro fr",

    # ECONOMY + BUY PHASE edge cases
    "yo bro fr if we win this round we can all full buy next round so please don't feed your gun fr bro fr",
    "ngl deadass tell them we need to save our abilities this round for the full buy push next round fr bro fr",
    "yo fr fr their loss bonus is maxed so next round they're definitely full buying whatever we do bro fr fr",
    "tell them bro two of us have enough for full buy and three don't so we either drop or force fr bro fr",
    "yo ngl bro their team won the pistol and now round two they're doing spectre bonus round fr play anti-eco bro",
    "bro fr deadass they're doing an all-marshal force and it's cracked because every one of them one-taps fr no cap bro",
    "yo tell them fr fr they eco'd two rounds so they have like eight or nine thousand saved up bro full send buy fr",
    "ngl bro one person on their team threw their gun and now they're down a rifle fr free economic advantage fr bro",
    "yo fr their Jett dropped her op when she died bro pick it up that's like four thousand credits for free fr fr",
    "tell them bro if the round goes to time they save credits fr don't extend the round for no reason bro fr fr",

    # MIND GAMES + FAKES slang
    "yo bro their Yoru is faking the A long push with fake gate audio fr the real push is coming from sewer fr fr",
    "ngl fr tell them that Astra gravity well was a fake pull she dissipated it fr don't react to the fake bro fr",
    "yo deadass their Raze sent the roomba to B but their whole team is going A fr classic roomba fake bro fr fr",
    "tell them bro the Brimstone smokes went on A but nobody is behind them fr it's a pure fake execute bro fr",
    "yo fr fr their Clove smoked A hard and everyone ran A sounds but they're actually hitting B fr classic bro fr",
    "ngl bro one guy made a lot of noise in C long and the rest of their team went A fr don't fall for it fr bro",
    "yo their Omen paranoia went into A site but their whole team is on C fr the paranoia was just a fake fr bro",
    "tell them bro the Sova recon hit A site but they actually went B fr the recon was informational not commitment fr bro",
    "yo fr ngl they committed two flashes to A and then pulled back fr it was a full fake execute bro fr fr",
    "bro deadass one of their guys is just baiting mid while the four stack goes A fr ignore mid right now fr bro",

    # INDIVIDUAL PLAYER READS
    "yo bro their Jett has been entry fragging A every single round and her team just follows bro anti-strat it fr fr",
    "ngl tell them their Reyna is actually tilting fr like she's 1 and 8 and she's inting bro she'll rush alone fr",
    "yo fr their Omen is a gigachad at one-ways bro like every smoke is perfect placement fr it's a controller diff fr",
    "tell them bro their KAY/O throws the knife from the same spot every round fr somebody rush him before he throws it bro",
    "yo deadass their Skye is goated fr every guiding light flash is perfectly timed to her team's push fr fr bro diff",
    "ngl bro their Iso is on like ten kills already and he's gonna pull contract on our best player this round fr cooked",
    "yo their Neon is running around every round with insane eDPI and she's hitting every spray transfer fr fr bro fr",
    "tell them bro their Cypher has been getting info on every single rotation through the cams fr it's information diff bro fr",
    "yo ngl fr their Sage walls in creative spots every round bro like nobody can predict where the wall goes fr diff bro",
    "bro fr fr their Tejo has been abusing guided salvo lineups all game and we need to dodge them bro fr fr",

    # MISCELLANEOUS HARD SLANG
    "yo bro fr fr tell them two are cooked one shot and one more is a fresh vandal full hp fr don't all peek bro",
    "ngl deadass one enemy is a gigachad and four are basically NPCs fr the diff player is their Jett bro fr fr",
    "yo their whole team is lowkey sauced on abilities like every single ability is up for them fr bro fr",
    "tell them bro it's giving full eco vibes from them this round fr their guns look cheap fr fr rush bro fr",
    "yo fr ngl one of them is just completely vibing in a corner camping fr not gonna lie cowardly fr tell them to push bro",
    "bro deadass fr fr their Reyna is just glazing her op player by following him everywhere bro diff fr no cap fr",
    "yo ngl tell them that guy is literally inting fr like he peaked the same angle five times fr he'll peek again bro fr",
    "tell them bro their Raze is actually going goblin mode bro like she's satcheling everywhere fr impossible to track fr",
    "yo fr fr two of them are actually cooked at aiming but three are cracked so it's a mixed team bro fr fr",
    "ngl bro their whole team is on copium fr we're winning every eco round and they're not adjusting bro fr fr",

    # ================================================================
    # FINAL BATCH — reaching ~600 total
    # ================================================================
    "yo bro fr fr one dude is lurking A tree with a vandal and their whole team is pushing B fr it's a fake bro fr",
    "ngl tell them the Clove not dead yet is gonna go off this round so kill her last fr she's the revive threat bro fr",
    "yo deadass two of them are on the ropes in B and one is holding from hell below fr it's a vertical crossfire bro fr",
    "tell them bro the Astra cosmic divide is splitting B main horizontally and nobody can cross it fr bro fr cooked fr",
    "yo fr fr their Neon entry plus Breach rolling thunder combo is actually the cleanest execute in the game bro fr",
    "ngl bro one of their guys ratted in A hall all round and he's gonna get a free exit frag when we retake fr cooked",
    "yo bro tell them their Vyse shear trap is hidden on B site and it's gonna pop an indestructible wall fr bro fr fr",
    "tell them bro three stacked B and two faked C and now B has no anchor and C has no pressure fr go A bro fr fr",
    "yo deadass fr ngl their Veto interceptor destroyed our Killjoy bots before the round even started fr sentinel diff bro",
    "bro fr their Deadlock sonic sensor is on the staircase and any loud ability is gonna trigger it fr don't use util bro",
    "yo tell them bro their Miks bassquake ult is going off on B site and it's concussing everyone fr cooked fr bro fr",
    "ngl two of our teammates got hit by the Miks M-pulse and they're deafened fr they can't hear footsteps bro fr",
    "yo fr their Harbor storm surge just waved through A main and it concussed everyone in the corridor fr bro fr fr",
    "tell them bro the Harbor cove blocked the spike from being shot and the planter has full protection fr fr bro cooked",
    "yo bro ngl two are pushing B main and one is coming from mid link and it's a split from two directions fr fr cooked",
    "bro fr fr their Crosscut vortex anchors from Veto let him TP back instantly after a bad peek fr annoying bro fr",
    "yo fr deadass their Brimstone stim beacon went on B site and now they all have faster movement and fire rate fr bro",
    "tell them bro one is hiding in B hell and nobody has a util to clear him fr it's a nightmare retake situation bro fr",
    "yo ngl bro their whole team is healthy because Skye keeps healing between fights fr non-stop regrowth healing bro fr",
    "bro fr fr their Tejo special delivery concussed both angles at B simultaneously fr one grenade cleared the site bro fr",
    "yo tell them bro one player is holding the A generator with their back against it and watching both A main and garden fr",
    "ngl deadass fr fr their Sage slow orb hit A ramps and everyone is slow fr and their Jett is gonna dash through fr",
    "yo bro the Breach aftershock went through B main wall and damaged two of our guys through the actual concrete fr bro fr",
    "tell them bro their Sova owl drone is actively pinging mid and it knows where our lurker is bro shoot the drone fr fr",
    "yo fr two faked the zipline noise at A and their real three-man push is coming from B rope at fracture fr bro fr",
    "ngl bro one crouched behind the double box on B and four are in B main ready to burst fr don't peek the box bro fr",
    "yo deadass they set up a fake defuse with their Gekko wingman bro like wingman tapped it and then they swung fr cooked",
    "tell them bro their Killjoy placed her turret in B alley and it covers the spike from behind fr retake is cooked bro fr",
    "yo fr ngl two are at A main with rifles and three more are at B main with rifles fr they're going both at once fr bro",
    "bro fr fr their Fade nightfall decayed and trailed our whole team bro the trail shows everyone where we ran fr cooked fr",
    "yo tell them bro one is playing off the A screens angle and another is deep in hell bro two-man trap fr fr cooked bro",
    "ngl bro their Omen from the shadows teleported to our spawn area and he's flanking our entire team fr from behind fr",
    "yo fr deadass tell them the Sova shock dart is set up on the default plant and it pulses every few seconds fr wait it out bro",
    "tell them bro their Raze paint shells hit the B door and the sub-munitions spread into B site fr chaotic frag fr bro fr",
    "yo bro fr ngl one is in the log pile cubby and he's been there since round start and nobody checked him fr bro fr fr",
    "bro fr fr their Skye trailblazer went through A screens and it concussed our guy holding elbow fr free entry now bro fr",
    "yo ngl their Vyse arc rose is hidden on the wall at B tower and anyone who looks at it gets flashed fr bro fr fr",
    "tell them bro two of our guys have no armor because they force bought rifles only fr they're fragile in gunfights bro fr",
    "yo fr their Iso double tap shield let him absorb the first vandal bullet bro they're not going to win through damage bro fr",
    "ngl bro two enemies fell back from A and rotated through CT to stack B before we could push A fr missed the window bro",
    "yo bro tell them the Miks waveform smokes are covering both B main and B alley simultaneously fr double smoke fr bro",
    "tell them bro three of them have rifles and two have marshals and it's actually a cracked anti-op setup fr bro fr",
    "yo fr fr their Gekko dizzy is in the air and it's gonna pop on B site fr don't look at the green flash bro fr fr",
    "ngl bro one anchored with a tripwire on B short and one is holding B long and it's a two-way crossfire fr cooked bro",
    "yo deadass tell them their whole utility package got used on the fake execute so they're dry for real push fr go now bro",
    "bro fr fr their Jett and Raze did a double rocket jump satchel into A site and they're both on site bro fr fr insane",
]
