"""Vocab pack: stress_ecobleed  (kind=relay, ~600 cases)

METRIC TARGET: Economy semantic precision stress.
Distinct from var_economy_buys: every item here is engineered to BREAK the pipeline on
the boundary between buy-types (force vs save, anti-eco vs half-buy, bonus vs full-buy),
on "do not give them guns" framing, on save-with-explicit-reason, on enemy-save intelligence
calls with compound ownership, and on numeric threshold anchoring.

Hard dimensions exercised:
  - ecobleed: save leaking onto force / force leaking onto full-buy / anti-eco leaking onto save
  - ownership inversion: OUR save vs THEIR save (subject must not flip)
  - directive: save-with-reason (the reason must survive rephrasing intact)
  - do-not-give-them-guns: distinct directive from plain save
  - compound calls: buy type + weapon spec + armor spec + ability spec in one breath
  - numeric anchors: exact credit thresholds (2900, 3900, 4500, 4700, 1600, 400, 1000)
  - bonus round semantics: must not rephrase as full-buy or eco
  - anti-eco vs light-buy: they look the same but have opposite trigger conditions
  - enemy-save reads with embedded recommendations
  - half-save / half-eco hybrid framing
"""

ITEMS = [
    # ── FORCE BUY — HARD BOUNDARY (force, NOT save and NOT full-buy) ────────────
    "tell my team we force this round, not save — we can't afford to keep ecoing",
    "tell them force buy, and I mean force not half-buy, spend everything you have",
    "let my team know it's a force round not an eco round, buy what you can",
    "tell my squad force this one even though we won't have full loadouts",
    "tell them this is a force not a save, spend your creds now",
    "tell my teammates we're forcing, that's different from saving, go buy something",
    "tell them force round: buy a Spectre or Sheriff, don't hold credits back",
    "let my team know we force because saving again just delays the problem",
    "tell them it's a force, not full buy, not eco — force, spend what you have",
    "tell my squad force buy this round so we have a chance instead of giving away a free round",
    "tell them we force here because we can't save our way back into this match",
    "let my teammates know force round means you buy even if you can't full buy",
    "tell them don't confuse force with save: force means spend it",
    "tell my team force buy, not hold credits, actual force",
    "tell them we're forcing because ecoing now gives them three easy rounds",
    "tell my squad the call is force, not eco, not full buy — force",
    "tell them force this round and play aggressive with whatever you can afford",
    "let my team know we force because the round count is against us",
    "tell them it's a force because we need to win NOW not next round",
    "tell my teammates force buy here, Spectres if you have 1600, Sheriffs if not",

    # ── SAVE — HARD BOUNDARY (save, NOT force) ──────────────────────────────────
    "tell my team save this round, not force, not half buy — full save",
    "tell them we save, and I mean hard save, don't buy anything",
    "let my teammates know this is a save not a force, hold every credit",
    "tell my squad save round, which means do NOT spend on a force this time",
    "tell them this is a genuine save round, not a sneaky force — Classic and run",
    "tell my team hard save: Classic only, not even a pistol",
    "tell them save this round because we burned rifles last round and can't repeat it",
    "let my team know we save because three bad forces in a row will bury our economy",
    "tell them we're saving because the loss bonus is still climbing and one more save gets us there",
    "tell my squad this is NOT a force round, it's a save round, don't buy weapons",
    "tell them save and play for spike plant credits and eco kills only",
    "let my teammates know save round means you don't force even if you feel like you can win",
    "tell them hard save, skip all abilities too, save every single credit",
    "tell my team we save to guarantee full buy next round, not to force and fail again",
    "tell them eco round: save the credits, don't gamble them on a force",
    "tell my squad save this one so we come back with rifles next round",
    "tell them we need two saves not one, so don't force now and ruin the plan",
    "let my team know save round and I promise we full buy next if we hold discipline",
    "tell them saving now is the smarter play than forcing with pistols against their rifles",
    "tell my teammates save this round even if we think we can win it on a force",

    # ── DO NOT GIVE THEM GUNS — DISTINCT DIRECTIVE ──────────────────────────────
    "tell my team do not give them free guns, save exit if the round is lost",
    "tell them don't give away rifles to the enemy team, save your weapons",
    "let my teammates know do not hand them guns, keep your rifle alive",
    "tell my squad don't die with full buy weapons and give them free loadouts",
    "tell them the priority is don't give them guns, exit safely with your rifle",
    "tell my team dying with an Op on a lost round is handing them a 4700-credit weapon",
    "let my team know don't feed them your Vandal, it's a lost round, save it",
    "tell them this round is over, do not give them your guns, back out now",
    "tell my teammates don't fight for kills on a lost round and give the enemy rifles",
    "tell them don't be the reason they get a free Op, save exit now",
    "let my squad know if you die with a Phantom you're buying their next round for them",
    "tell them saving the rifle matters more than the last trade, don't give it away",
    "tell my team do not give them an Op, they'll use it to demolish us next round",
    "tell them back out, do not give them guns — round is cooked",
    "let my teammates know their economy resets if you hand them free Vandals on a save exit",
    "tell them they're already winning the round, don't compound it by gifting them your rifles",
    "tell my squad if you die with a rifle on a clearly lost round you owe the team an apology",
    "tell them do not feed them kill credits and weapons, save exit immediately",
    "let my team know exit clean: keep your gun, don't die for nothing, don't give them rifles",
    "tell them we've already lost the round, the only thing left to lose is our guns — don't",

    # ── SAVE WITH REASON — REASON MUST SURVIVE REPHRASING ───────────────────────
    "tell my team save because we lost three rifles last round and our economy is destroyed",
    "tell them we save because two consecutive force fails put us in a death spiral",
    "let my teammates know save this round because we need the 2900 loss bonus to stack up",
    "tell my squad save because if we force and lose we literally cannot buy next round either",
    "tell them eco this round because their full buy beats our force loadout every time",
    "tell my team save now because we're down to Classic and if we force we lose the last edge we have",
    "let my team know we save because the spike plant bonus plus the loss bonus gets us to full buy",
    "tell them save this round because four of us are under a thousand credits and forcing is suicide",
    "tell my teammates we save because they likely full buy and we'd be fighting rifles with pistols",
    "tell them eco round because spending now means we STILL can't full buy next round",
    "let my squad know we save because winning a force this round doesn't fix the economy long-term",
    "tell them save this round because one more eco and the loss bonus brings everyone above 3900",
    "tell my team we save because dying with rifles AGAIN is what got us into this mess",
    "tell them save now because the only path to a consistent full buy is two disciplined eco rounds",
    "let my teammates know we eco because on a force we'd have Spectres versus Vandals and that math doesn't work",
    "tell them save and get the spike plant if we can, 300 credits each adds up",
    "tell my squad we save because three of us are at 1200 credits and a force at 1200 is a pistol round",
    "tell them we're saving because our full buy threshold is 3900 and nobody is there yet",
    "let my team know save because if we force and miss the Thrifty we reset to zero and can't recover",
    "tell them save this round so we guarantee four players at full buy minimum next round",

    # ── ANTI-ECO (their eco, our smart buy) — NOT SAVE, NOT FULL-BUY ──────────
    "tell my team they're on eco so we play anti-eco, not full buy, Spectres and light armor",
    "tell them enemy eco round: we go anti-eco, that means lighter buys not rifles",
    "let my teammates know they're saving so we don't over-invest — anti-eco buys",
    "tell my squad they're on eco and we play anti-eco so we don't waste an Op kill on someone with a Classic",
    "tell them anti-eco round: Spectre and light shield, don't buy an Operator against a Classic",
    "tell my team enemy eco means we buy smarter not harder, anti-eco setups",
    "let my team know anti-eco is not the same as our eco round: we BUY but we buy lighter",
    "tell them they're saving hard so anti-eco: don't drop rifles they can steal if we die",
    "tell my teammates anti-eco this round, they're on Classics, we don't need Vandals to beat that",
    "tell them we adjust to anti-eco because if they kill us they get free rifles and ruin our economy",
    "let my squad know anti-eco means we still buy, just not Operators and Vandals — Spectres work",
    "tell them they're eco so anti-eco: play passively, take easy picks, don't over-commit",
    "tell my team anti-eco round: avoid dying with expensive guns against their cheap loadout",
    "let my teammates know if they're on eco we don't need to full buy, anti-eco buys win the round",
    "tell them their eco round is our anti-eco round: buy light and play safe",
    "tell my squad anti-eco: SMG and light armor is enough to beat a Classic-only team",
    "tell them we anti-eco because over-investing against an eco team risks handing them free rifles",
    "let my team know don't buy Op against a team that's saving, anti-eco buys only",
    "tell them enemy saving means anti-eco for us: Spectres or Sheriffs and light shields",
    "tell my teammates this is an anti-eco situation, not a full buy situation, buy appropriately",

    # ── BONUS ROUND — NOT FULL-BUY, NOT ECO ─────────────────────────────────────
    "tell my team bonus round: Spectres and keep the guns from last round",
    "tell them it's a bonus round not a full buy, Spectre and light armor, don't upgrade to rifles",
    "let my teammates know we won pistol so bonus round: SMG plus the pistol we kept",
    "tell my squad bonus round means we buy Spectres not Vandals, save the extra credits",
    "tell them bonus round rules: Spectre is the play, don't go rifle or we hurt round-three economy",
    "tell my team this is the bonus round, not full buy, buy an SMG and save the rest",
    "let my team know bonus round: keep your Ghost from pistol round and add a Spectre",
    "tell them second round after pistol win is a bonus round, Spectre and light shield only",
    "tell my teammates the bonus round is not the time to buy rifles, Spectres only",
    "tell them bonus round: don't waste credits on a Vandal, we need them for round three",
    "let my squad know bonus round means we extend the advantage not blow the credits on rifles",
    "tell them buy an SMG this bonus round, save the credits for a full buy next if we need it",
    "tell my team bonus round standard: Spectre, light armor, keep pistol round gun",
    "let my teammates know don't treat the bonus round like a full buy, it's not one",
    "tell them bonus round: Spectre and whatever you kept from pistol round",

    # ── HALF-BUY / LIGHT BUY — NOT FORCE, NOT ECO, NOT FULL-BUY ─────────────────
    "tell my team half buy this round, not force and not eco — Spectre and light armor",
    "tell them we half buy: that means something but not full rifles, budget loadout",
    "let my teammates know half buy round: we're between eco and full buy, Spectres",
    "tell my squad half buy — smarter than force, more invested than pure eco",
    "tell them half buy: we spend 2000 to 2500 each and keep some credits for next",
    "tell my team it's a half buy, not a force — we're not going all-in, just competitive",
    "let my team know half buy this round so we're competitive but don't blow the economy",
    "tell them we half buy because four of us are at 2500, not enough for full rifles",
    "tell my teammates half buy: Spectre or Marshal, light armor, one ability max",
    "tell them half buy round means don't spend more than 2500, leave credits for next round",
    "let my squad know half buy: SMG and light shield, play tight angles because you don't have a rifle",
    "tell them it's a light buy, not a force — we're not gambling everything, just buying smart",
    "tell my team half buy means you buy but you don't destroy the economy doing it",
    "let my teammates know half buy is the play because three of us are at 2200 and can't full buy",
    "tell them half buy so we stay in the match without breaking our economy for next round",
    "tell my squad light buy this round: Spectre and light armor is the standard",
    "tell them half buy round: Guardian if you have 2250, Spectre otherwise",
    "let my team know this is a half buy not a force — half buy means you're playing to stay alive next round too",
    "tell them half buy round: don't blow everything even if you could technically afford more",
    "tell my teammates half buy: stay disciplined and don't sneak in a full buy when everyone else is half buying",

    # ── ENEMY-SAVE READS WITH EMBEDDED RECOMMENDATION ───────────────────────────
    "tell my team they're saving this round so we go anti-eco, light buys, don't drop rifles",
    "tell them enemy is on eco so we play anti-eco and take easy kills, don't over-invest",
    "let my teammates know they're saving and that means we adjust our buy down to anti-eco",
    "tell my squad they're on eco and that means we buy light and don't hand them rifles if we die",
    "tell them enemy eco round: we buy smart, not full rifles, anti-eco setup",
    "tell my team they've been saving for two rounds so next round they full buy — prepare",
    "tell them they saved this round which means they're coming with full loadouts next round",
    "let my team know they eco'd this round so expect rifles from them next, plan accordingly",
    "tell them watch out — they saved last round and they're buying this one, expect Vandals",
    "tell my teammates they're on eco but they might eco rush so play tighter than normal",
    "let my squad know enemy saving means they might go all-in on a rush this round",
    "tell them their eco round could mean an all-out rush, don't play loose",
    "tell my team they're saving hard, easy round for us if we don't throw it with risky plays",
    "tell them they're on eco so stay passive, pick easy kills, don't gift them your guns",
    "let my teammates know they're saving and we need to not die with rifles or we fund their full buy",
    "tell my squad enemy eco round: take the cheap kills but do not die trying, they might rush B",
    "tell them they're saving but their economy might mean a force this round instead of a pure eco",
    "let my team know they're on eco so watch for the desperation rush or a pistol force",
    "tell them they're saving this round but I think they might force with Sheriffs so play carefully",
    "tell my teammates enemy eco: play smart, take easy picks, don't let them steal rifles off us",

    # ── COMPOUND ECONOMY: BUY TYPE + WEAPON + ARMOR + ABILITY ───────────────────
    "tell my team full buy: Vandal or Phantom, heavy armor, and full abilities for everyone",
    "tell them force buy: Spectre or Sheriff, light armor, skip abilities to afford the gun",
    "let my teammates know half buy: Spectre and light armor, one ability each maximum",
    "tell my squad anti-eco: Spectre and light shield, no Op, no Vandal, no heavy armor needed",
    "tell them bonus round: Spectre plus keep your Ghost, light armor, skip heavy",
    "tell my team eco round: Classic, no armor, no abilities, save everything",
    "let my team know force: everyone buys Spectre and light armor, skip abilities if you have to",
    "tell them full buy: rifle plus heavy armor plus full utility, that's the standard",
    "tell my teammates half buy: Guardian if you have 2250, Spectre otherwise, light armor both cases",
    "tell them force round: Sheriff and heavy armor if you can, Frenzy and light armor if not",
    "let my squad know full buy this round: Vandal, heavy armor, all abilities including the expensive ones",
    "tell them force: Bulldog and light armor if you have 2450, Spectre and light armor otherwise",
    "tell my team eco: no guns, no armor, no abilities — full save Classic round",
    "let my teammates know anti-eco: Spectre and light armor, skip heavy, skip Op, just win the round cheap",
    "tell them bonus round: Spectre and light armor, keep the pistol you had, don't buy heavy shield",
    "tell my squad force round: whatever you can afford, Spectre and light armor minimum",
    "tell them half buy: Spectre or Marshal, light shield, and at most one ability each",
    "let my team know eco: Classic round, not even a Shorty, hard save every credit",
    "tell them full force: spend every credit you have, Bulldog, heavy armor, whatever you can get",
    "tell my teammates anti-eco: we don't need Op, Spectre and light armor wins this against their Classic",

    # ── NUMERIC THRESHOLD ANCHORING (exact numbers must survive) ─────────────────
    "tell my team if you have 3900 or more you full buy, if you're under 3900 you half buy",
    "tell them nobody buys a Vandal unless they have at least 3900 total, check your credits",
    "let my teammates know 2900 is the rifle cost, add 1000 for heavy armor, that's your full buy floor",
    "tell my squad if you're under 3900 you cannot full buy, force or half buy only",
    "tell them 4500 to 5000 is comfortable full buy with abilities, check if you're there",
    "tell my team Op is 4700 alone, if you buy Op you better skip armor and have 5700 to go with armor",
    "let my team know 1600 is a Spectre, 400 is light armor, that's 2000 for a half buy",
    "tell them Spectre plus heavy armor is 2600, that's the minimum decent force loadout",
    "tell my teammates 400 is light armor, 1000 is heavy armor — always get at least the 400 if you can",
    "tell them if you're at 1900 on eco you're still getting the loss bonus kick for next round",
    "let my squad know the loss bonus after one loss is 1900 each, after two it's 2400, three is 2900",
    "tell them if we eco this round and get 2900 loss bonus, plus our current credits, we can full buy next",
    "tell my team 800 is the starting credit cap in pistol round, plan accordingly",
    "let my teammates know anyone sitting at 4700 and above should be buying the Op if they play it",
    "tell them if four of us hit 3900 we full buy and drop the fifth a rifle from the extras",
    "tell my squad Bulldog is 2050, not 2900 — it's a rifle-tier gun but budget, get it on a force",
    "tell them Guardian at 2250 is between Bulldog and Phantom in price, use it on half buys",
    "let my team know Outlaw is 2400, it's a dual-barrel sniper and it's cheaper than a Phantom",
    "tell them 4700 for the Op means you have to choose: Op no armor or rifle and armor",
    "tell my teammates check if you have 4500 credits because that's when you can comfortably full buy with utility",

    # ── FORCE VS SAVE AMBIGUOUS FRAMING (hard for the model) ────────────────────
    "tell my team we're not saving, we're forcing, even though I know it feels the same",
    "tell them I know our credits are low but we force, not save, this round",
    "let my teammates know force this one even if saving feels safer — we need the round",
    "tell my squad we force because saving another round puts us too far behind",
    "tell them don't save this round, force — spend it all, we can't keep giving free rounds",
    "tell my team I know the temptation is to save but we force this round, buy what you have",
    "let my team know the call is force not save, even though I know our credits are thin",
    "tell them last round we saved, this round we force — different call, commit to it",
    "tell my teammates the difference between force and save: force means buy, save means don't, we're buying",
    "tell them stop saving and force already, we've eco'd twice and now we force",
    "let my squad know we break the save pattern: we force this round, not eco again",
    "tell them we force because ecoing a third time won't fix the round count problem",
    "tell my team force round, I know credits are tight but we're not saving again",
    "let my teammates know we break out of eco mode: force buy this round",
    "tell them force this one, the only thing we've achieved by saving is letting them snowball",

    # ── SAVE EXIT VS ROUND SAVE (two different meanings of 'save') ─────────────
    "tell my team save exit: the round is lost, keep your rifle, get out alive",
    "tell them save your gun not the round, round's gone — preserve the rifle",
    "let my teammates know save exit now — this is not a save round decision, the round is lost and we need to save weapons",
    "tell my squad the round is cooked, save exit means save your rifle not your credits",
    "tell them don't confuse saving credits with saving your gun — right now save your gun, round is over",
    "tell my team the round is lost, stop fighting and save your rifle for next round",
    "let my team know save exit: get out with the rifle, that's the only thing we're saving here",
    "tell them rifle save exit: don't take trades on a dead round, just run with the Vandal",
    "tell my teammates save exit priority: Vandal out the door, don't die for one last kill",
    "tell them save the weapon, not the round — round is finished, get out clean",
    "let my squad know save your loadout this round: don't fight, just leave with the rifle",
    "tell them exit safe with your gun: losing the round is bad, losing the rifle on top of it is worse",
    "tell my team we're losing this round, save exit mode, keep the rifle",
    "let my teammates know the spike is planted and we're down numbers, save mode means gun not round",
    "tell them save exit: the round is definitely gone, protect the economy and exit with your weapon",

    # ── GLASS CANNON (force to save ecobleed edge) ────────────────────────────────
    "tell my team glass cannon Op: we force with Operators and no armor because we can't afford both",
    "tell them glass cannon this round: Op and no armor to save the armor credit for next round",
    "let my teammates know Op no armor is a glass cannon force — they're playing a high-risk force",
    "tell my squad glass cannon force: Op without heavy armor because we only have 4700 and the Op must come first",
    "tell them force glass cannon: buy the weapon skip the armor, that's the priority call",
    "tell my team don't buy the Op without armor unless you're playing truly passive post-plant angles",
    "let my team know glass cannon Op is a force bet: win the duel or lose the economy",
    "tell them glass cannon only works if you play correctly, don't Op from close range with no armor",
    "tell my teammates this glass cannon force round: Op no armor, play long angles only",
    "tell them glass cannon economy: gun over armor, play like your life matters because it costs 4700",

    # ── CREDIT CAP AWARENESS ──────────────────────────────────────────────────────
    "tell my team if anyone is near 9000 credits they need to buy or drop someone a weapon",
    "tell them you can't hold more than 9000 credits, if you're near the cap spend something",
    "let my teammates know credit cap is 9000, buy before you lose credits to the ceiling",
    "tell my squad if you're sitting at 8500 credits on an eco round still buy light armor at least",
    "tell them don't cap out at 9000, spend on a drop or armor before the round starts",
    "tell my team near the credit cap means buy something: even on eco get light armor if you're at 8500",
    "let my team know the credit ceiling is 9000, burning credits to the cap is wasted money",
    "tell them if you're about to hit 9000 drop someone a rifle before you lose credits to the cap",
    "tell my teammates credit cap at 9000 means any excess is deleted, spend before you lose it",
    "tell them if your credits are close to 9000 on an eco round still buy armor so you don't lose it",

    # ── OWNERSHIP INVERSION STRESS (their save vs our save) ─────────────────────
    "tell my team WE save this round, THEY are buying with rifles",
    "tell them they're full buying and we're saving — opposite situations",
    "let my teammates know we're the ones saving this round while they get to full buy",
    "tell my squad they're saving and we're also saving — same round type both sides",
    "tell them they're forcing while we save — they're gambling, we're being disciplined",
    "tell my team we're saving because THEY have rifles and we can't win that gunfight",
    "let my team know WE save, THEY buy — don't mix up the economy reads",
    "tell them our eco vs their full buy: we save, they press the advantage",
    "tell my teammates we're the eco side this round and they're the buy side",
    "tell them they're saving too which means both sides are eco and it's a pistol fight",
    "let my squad know they're also forcing this round, both sides weak, force mirror",
    "tell them they force, we save — we give up this round for the next one's economy",
    "tell my team we're on anti-eco because THEY save — different from us saving",
    "let my teammates know anti-eco means THEY save and WE buy lighter",
    "tell them both sides are eco this round — don't play like they have rifles, they don't",

    # ── COORDINATED FORCE TYPES ───────────────────────────────────────────────────
    "tell my team all Spectre force: everyone buys exactly a Spectre and light armor, no deviations",
    "tell them coordinated force this round: everybody on the same weapon, all Spectres",
    "let my teammates know we coordinate the force — same loadout for everyone, Spectre and light armor",
    "tell my squad all-Sheriff force: everyone buys Sheriff and light armor, no other guns",
    "tell them all-Bulldog force if you have 2450, otherwise Spectre — stay coordinated",
    "tell my team all-force round: pick one weapon and all five buy it so we're even",
    "let my team know full-team force: Spectre and light shield, 2000 max spend per person",
    "tell them pistol force: everyone buys Sheriff if you have 800, Ghost otherwise",
    "tell my teammates coordinated Spectre force this round, no going off menu",
    "tell them everyone buys the same gun this force round so we don't have economy split",
    "let my squad know unified force buy: same weapon, same armor, same play style, Spectres",
    "tell them all-in force this round, everyone spend everything on the same loadout",
    "tell my team force round coordination: agree on a gun and all buy it before phase ends",
    "let my teammates know don't deviate on the force — same weapon everyone or the coordination breaks",
    "tell them coordinated force: five Spectres hitting one site is better than mixed weapons",

    # ── ECONOMY CONTEXT: ATTACKER VS DEFENDER SIDE ──────────────────────────────
    "tell my team on attack side we buy aggressively for executes, don't eco unnecessarily",
    "tell them defender eco is different: we play passive and save, don't try to force win",
    "let my teammates know on defense an eco round means anchor and delay, not rush",
    "tell my squad attacker eco means we rush one site fast, don't give them time to react",
    "tell them attacking on eco: full rush B, all five commit before they can rotate",
    "tell my team defending on eco: play safe angles, don't take duels with Classic against rifles",
    "let my team know attack force means go aggressive with whatever we have, can't play passive with Spectres",
    "tell them defend anti-eco: we have rifles and they have Classics, play crossfire not aggressive",
    "tell my teammates on attack if we're eco we rush one site early before utility is deployed",
    "tell them defend and we're full buy vs their eco: don't let them take any map control",
    "let my squad know attacker save exit: if they retake just bail, don't die trying to hold the site",
    "tell them defender force round: we have just enough to force, play tight and let them come to us",
    "tell my team attack with full buy means slow execute, use all utility, don't rush",
    "let my teammates know defender half buy means play passive, don't take fights you'd lose with an SMG",
    "tell them attack eco rush: all five hit A Main in the first ten seconds, don't let them smoke up",

    # ── NUANCED SAVE REASONS (specific reasons that must survive) ───────────────
    "tell my team save because dying with full-buy loadouts three rounds in a row tanked our economy",
    "tell them save this round because we're 30 seconds from round end and it's already lost",
    "let my teammates know save because they used three Operators and we can't fight that on a force",
    "tell my squad we save because the round count is 12-4 and economy is the only thing we can control",
    "tell them save because we have a Sage and losing her rifle hurts three times as much",
    "tell my team we save because their Killjoy has Lockdown and we can't execute into it with Spectres",
    "let my team know save because next round is the second half pistol and economy resets anyway",
    "tell them save because two of us are already dead and three vs five on a save is still easier than force",
    "tell my teammates save this round because the spike is planted and we're out of time to defuse anyway",
    "tell them save because our Jett already used dash and has no escape route with an Op",
    "let my squad know save because their Brimstone has orbital and we'd just be walking into a laser",
    "tell them save because if we force and lose we also lose the rifles AND fall behind on loss bonus",
    "tell my team we save because the enemy always anti-strats our force and crushes it",
    "let my teammates know save this round because it's overtime and economy resets to 5000 next round anyway",
    "tell them save because half our team is at 1100 credits and a force at 1100 is worse than Classic",

    # ── SPIKE PLANT ECONOMY ON ECO ───────────────────────────────────────────────
    "tell my team even on eco try to plant the spike for the 300 credits each",
    "tell them eco round: if we get a plant that's 300 each, worth playing for",
    "let my teammates know spike plant earns us all 300 credits even if we lose the round",
    "tell my squad plant the spike on this eco round before we save exit, 300 bonus each",
    "tell them go for the spike plant first, 300 credits per attacker is significant on an eco round",
    "tell my team plant and then save exit: get the 300 credits and then bail with your gun",
    "let my team know on eco always try for the spike plant because 300 credits each adds to the loss bonus",
    "tell them even if we're losing this round planting gets us 300 more credits toward the full buy",
    "tell my teammates spike plant bonus on eco: 300 each means we hit full buy threshold faster",
    "tell them plant the spike even if we know they'll defuse — 300 credits per attacker is real economy",

    # ── ECO KILL ECONOMY ─────────────────────────────────────────────────────────
    "tell my team on eco every kill earns 200 credits, play for the picks",
    "tell them eco round kills are 200 each, stack them up for the full buy",
    "let my teammates know each kill on eco gives 200 credits, don't play passive",
    "tell my squad eco kill means 200 more credits and potentially a free dropped rifle",
    "tell them kill on eco plus spike plant is 500 credits earned, play for both",
    "tell my team if you kill a full-buy enemy on eco you get 200 credits and a free Vandal",
    "let my team know eco kills matter: 200 each, grab their dropped guns too",
    "tell them even on eco look for the pick: kill credit and dropped gun change the round",
    "tell my teammates eco kill: 200 credits and a possible rifle pickup, play for it",
    "tell them eco round doesn't mean passive — eco kills and gun pickups can shift the whole economy",

    # ── OVERTIME ECONOMY ──────────────────────────────────────────────────────────
    "tell my team overtime economy resets to 5000 for everyone, no carry-over",
    "tell them OT: we all start at 5000, full buy for everyone, economy resets",
    "let my teammates know in overtime it's 5000 credits per player, full buy every overtime round",
    "tell my squad OT economy is equal for both teams, 5000 each, no disadvantage",
    "tell them overtime: 5000 credits each, no loss bonus, no streak — clean slate",
    "tell my team we're in OT so economy is reset, everyone has 5000 and we full buy",
    "let my team know OT means equal economy, no advantage from our previous rounds",
    "tell them in overtime there's no eco round, everyone can full buy at 5000 each",
    "tell my teammates OT economy: 5000 per player, buy rifles, heavy armor, full utility",
    "tell them in overtime we never eco, always full buy at 5000, that's the rule",

    # ── HALF-BUY PRECISION CALLS ─────────────────────────────────────────────────
    "tell my team half buy: max 2500 per person, Spectre and light armor standard",
    "tell them half buy this round and bank the rest toward next round's full buy threshold",
    "let my teammates know half buy means we spend 2000 to 2500 and no more",
    "tell my squad half buy: Guardian for the long angles or Spectre for close range, light armor either way",
    "tell them half buy and play passive angles because we don't have rifles",
    "tell my team half buy round: play it like a Spectre is a rifle and hold tight corners",
    "let my team know half buy: Marshal for anyone playing a long-range angle at 950 plus light armor",
    "tell them half buy doesn't mean play aggressive, play smart with what you have",
    "tell my teammates half buy: Bulldog if you have 2450, Spectre if not, light armor always",
    "tell them half buy — don't peek like you have a Vandal, you have a Spectre, play accordingly",
    "let my squad know half buy round: tight angles, no peeking long, play the Spectre's strengths",
    "tell them half buy this round and we should hit full buy next if we don't lose rifles",
    "tell my team we half buy to stay alive in the match without blowing our economy",
    "let my teammates know half buy: we can still win this round with Spectres, play disciplined",
    "tell them half buy round — Spectre beats rifle at close range so play close, not long",

    # ── ENEMY BUY READS (exact agent+weapon) ─────────────────────────────────────
    "tell my team their Jett has an Op, play carefully around long angles",
    "tell them enemy Chamber bought Tour de Force, expect sniper plays from unusual angles",
    "let my teammates know their Sova bought Owl Drone and full util, expect a lot of info",
    "tell my squad their Killjoy has Nanoswarms, don't stack on the spike",
    "tell them enemy Brimstone bought Orbital and full smokes, expect a slow execute",
    "tell my team their Reyna only has Leers, she's on a half buy, one headshot kills her",
    "let my team know their Omen bought Paranoia, don't peek into his nearsight",
    "tell them enemy Viper has her full kit, wall plus pit, it'll be a full execute",
    "tell my teammates their Breach has Rolling Thunder, expect a stun chain on entry",
    "tell them enemy Clove has Not Dead Yet, if she dies keep pressure or she revives",
    "let my squad know their Sage has her wall, they'll try to block our entry",
    "tell them enemy Raze has Showstopper, watch for a rocket on site entry",
    "tell my team their Fade has Nightfall, stay spread so not everyone gets deafened",
    "let my teammates know enemy Iso has Kill Contract ult, one of us might get pulled into a 1v1",
    "tell them their KAY/O has NULL/cmd, if he ults he can't be killed until the ult ends",

    # ── TERSE RELAY-STYLE ECONOMIC CALLS ─────────────────────────────────────────
    "force buy",
    "hard save",
    "anti-eco round",
    "bonus round buys",
    "half buy this round",
    "do not give them guns",
    "save exit, round's gone",
    "they're saving, anti-eco",
    "we're saving, not forcing",
    "glass cannon Op this round",
    "all Spectre force",
    "eco rush A site",
    "full save, Classic only",
    "buy round, full loadouts",
    "drop rifles, two players need them",
    "save your rifle, not the round",
    "they're on eco, play anti-eco",
    "bonus round, keep the pistol",
    "force with whatever you have",
    "half buy, Spectres and light armor",

    # ── SLANG-HEAVY ECONOMY CALLS ─────────────────────────────────────────────────
    "tell my team we're absolutely skint so full save, Classic only this round",
    "tell them we're poverty-tier credits, don't even think about a force",
    "let my teammates know the team wallet is empty, hard eco no debate",
    "tell my squad we're broke as hell, full save, nothing",
    "tell them we're loaded this round, full send, Vandals across the board",
    "tell my team we're flush with creds, buy everything, full loadout",
    "let my team know we're cashed up, rifles and heavy armor, no holding back",
    "tell them we're sitting on fives, go ham, full buy and full util",
    "tell my teammates we're credit-rich this round, buy the Op if you play it",
    "tell them we're destitute, Classic round, don't even ask about forces",
    "let my squad know we eco this one so next round we ball out properly",
    "tell them save for now and we go absolutely ballistic next round on full buy",
    "tell my team one round of poverty and then we're back to Vandals",
    "let my teammates know sacrifice this round and we feast next round economically",
    "tell them one eco now and next round we go full send with rifles",

    # ── REGIONAL / VOICE VARIANT ECONOMY ─────────────────────────────────────────
    "tell my mates to save this round, we're proper broke",
    "let the boys know force buy this one, spend what you got",
    "tell my crew we eco this round yeah?",
    "tell the lads half buy, Spectres and light shields",
    "let my squad know full buy this round, we're loaded mate",
    "tell them we save aye, one more eco and we buy rifles",
    "tell my boys we anti-eco this round, they're saving",
    "let the team know bonus round rules: Spectre, keep the pistol",
    "tell my mates don't force when we should save, discipline",
    "tell the squad do not give them guns, save exit if it's lost",

    # ── IGL-VOICE CONFIDENT ECONOMY CALLS ────────────────────────────────────────
    "tell my team the call is force, not eco — force round, trust the decision",
    "tell them I'm making the economy call: we save, no debate",
    "let my teammates know the IGL call is anti-eco: light buy, they're saving",
    "tell my squad economy decision is final: bonus round buys, Spectres",
    "tell them the call is half buy, four of us aren't at full buy threshold",
    "tell my team I'm calling a full buy, everyone spend, we have the credits",
    "let my team know the economy call is eco: hard save, no exceptions",
    "tell them the call is force because we can't keep gifting them free rounds",
    "tell my teammates I'm making the anti-eco call: Spectre and light armor, don't over-invest",
    "tell them the IGL says save exit: round is gone, don't die for pride, keep the rifle",

    # ── TILT-VOICE ECONOMY FRUSTRATION ───────────────────────────────────────────
    "tell my team stop forcing when we should save, our economy is a disaster",
    "tell them the reason we keep losing is we force when we should eco, discipline please",
    "let my teammates know if you keep forcing on a 1200-credit budget you're trolling the economy",
    "tell my squad please just save when the call is save, not everyone sneaking in a force",
    "tell them we're broke because people keep dying with rifles on lost rounds, save exit next time",
    "tell my team if you buy on an eco round without team agreement you're wrecking everyone's economy",
    "let my team know the economy is bad because someone saved when we were forcing last round",
    "tell them please coordinate: if it's an eco round don't one person force and destroy the plan",
    "tell my teammates stop dying with the Op on a lost round, you're handing them 4700-credit rounds",
    "tell them we're in this economy mess because we didn't save exit last round when we should have",

    # ── COMPLEX COMPOUND ECONOMY SCENARIOS ───────────────────────────────────────
    "tell my team save this round because they have full buy and we'd be fighting Vandals with Classics",
    "tell them we force because we're only down 4-6 and a force win closes the gap",
    "let my teammates know anti-eco this round because they're saving and we don't need to out-invest them",
    "tell my squad we half buy because three players are at 2200 and two can full buy — we all half buy together",
    "tell them save because winning a force doesn't solve the fact that the loss bonus is still stacking",
    "tell my team we force this round because their economy is also shaky and it's a momentum play",
    "let my team know bonus round rules apply: keep the pistol, buy a Spectre, save the rest",
    "tell them full buy because we just won three in a row and we have stacked credits",
    "tell my teammates save because we can't afford to fight their three Operators on a force budget",
    "tell them force because the round count is almost done and we need to close rounds not eco them away",
    "let my squad know half buy because none of us hit the 3900 threshold but we can't afford to give up a round",
    "tell them anti-eco because if we full buy against their Classic they might eco kill us and get free rifles",
    "tell my team we eco this one but make sure to plant the spike for the 300-credit bonus each",
    "let my teammates know force round but coordinate it: all Spectres so we're even and can play together",
    "tell them glass cannon force: Op players skip armor and play passive, rifle players take light armor",

    # ── ROUND-FLOW ECONOMY SEQUENCING ────────────────────────────────────────────
    "tell my team save now, force next, full buy the round after — that's the plan",
    "tell them two saves and then a full buy, don't deviate from the sequence",
    "let my teammates know the economy plan: eco this, half buy next, then full buy",
    "tell my squad the sequence is save, save, full buy — one deviation breaks it",
    "tell them we eco for one round and that's it, next round we commit to a force",
    "tell my team one save this round and the loss bonus puts us all at full buy threshold next round",
    "let my team know eco plan: one round, then next round full buy, no more ecoing after that",
    "tell them save now and the math works out: loss bonus plus carry-over equals full buy",
    "tell my teammates save this round and the plan is to buy rifles next round, not force, full buy",
    "tell them the economy sequence: Classic round today, Spectre force tomorrow, Vandals after that",

    # ── DO-NOT-GIVE-GUNS WITH AGENT SPECIFICS ────────────────────────────────────
    "tell my team do not let their Jett steal the Op, save exit and take it with you",
    "tell them if our Jett dies with the Op we're handing their entry a 4700-credit sniper",
    "let my teammates know our Chamber should not die with Tour de Force, back out if round is lost",
    "tell my squad do not die with the Op, their team gets a sniper for free and destroys us next round",
    "tell them if someone on their team gets our Op off an eco round they bought full buy for free",
    "tell my team save exit specifically: Jett, take the Op and dash out, don't trade it away",
    "let my team know the Op is the most expensive gun at 4700, do not give it to the enemy team",
    "tell them if you drop the Op in a save exit round you've funded their entire next-round economy",
    "tell my teammates do not let them pick up any of our Vandals from the floor, save exit with them",
    "tell them they will pick up any rifle we drop on a lost round, save exit means taking the rifle with you",

    # ── THRIFTY / ECO WIN FRAMING ─────────────────────────────────────────────────
    "tell my team if we win this eco round that's a Thrifty and that's massive morale",
    "tell them eco round doesn't mean losing round — we can Thrifty them if we play it right",
    "let my teammates know Thrifty potential this eco round: they're full buy, we're Classics",
    "tell my squad if we Thrifty this round we also keep our full buy economy intact",
    "tell them eco rush for the Thrifty: all five commit A main in the first fifteen seconds",
    "tell my team a Thrifty win this eco round means we don't lose any economy and embarrass them",
    "let my team know eco round: play for the Thrifty, go for the gun pickups",
    "tell them we Thrifty them and suddenly their full buy is irrelevant — play for it",
    "tell my teammates Thrifty eco round: coordinate a rush, grab their dropped Vandals, snowball",
    "tell them even on eco we've won Thriftys before, play smart and commit the rush",

    # ── DROP SYSTEM STRESS (force vs save interplay with drops) ─────────────────
    "tell my team if we're force buying, the rich players drop weapons to the broke ones",
    "tell them on a force buy drop anyone who has under 1600 a Spectre so everyone has a gun",
    "let my teammates know force round drop rules: if you have extra credits after buying, drop a gun",
    "tell my squad if four of us can force and one can't, the richest player drops them a Spectre",
    "tell them force round drops: prioritise giving everyone at least an SMG",
    "tell my team on a force you still drop teammates if you can afford it after your own buy",
    "let my team know don't force buy yourself a Vandal and leave a teammate with a Classic on a force",
    "tell them force round coordination includes drops: sort out the drops before round starts",
    "tell my teammates on a force if you have 3000 and your teammate has 800 you buy for both",
    "tell them drop coordination matters on force rounds as much as on full buy rounds",

    # ── SECOND-HALF PISTOL ECONOMY RESET ────────────────────────────────────────
    "tell my team second half pistol round: we reset to 800 credits, standard pistol buy",
    "tell them second half pistol, fresh start, everyone at 800 credits, buy smart",
    "let my teammates know second half pistol round resets everything, play it clean",
    "tell my squad we swap sides and pistol round resets: 800 credits, Ghost or Frenzy",
    "tell them second half pistol is the same as first half: buy a pistol and one ability",
    "tell my team win the second half pistol and we get the bonus round advantage again",
    "let my team know second half pistol: win this and we set up the SMG bonus round",
    "tell them second half pistol round strategy: Ghost and one ability, no armor if credits are tight",
    "tell my teammates second half starts fresh economically, make the most of the pistol round",
    "tell them we win second half pistol and reset our economy properly with the bonus round advantage",

    # ── REGEN SHIELD ECONOMY NUANCE ──────────────────────────────────────────────
    "tell my team Regen Shield is 650, it's between light and heavy — use it on half buys",
    "tell them Regen Shield regenerates itself, 650 credits and worth it on force rounds",
    "let my teammates know Regen Shield is the middle armor at 650, consider it on a force",
    "tell my squad Regen Shield: 650 credits, 25 hp plus it regenerates — good for half buys",
    "tell them don't forget the Regen Shield as an option: 650 is cheaper than heavy but better than light",
    "tell my team on a force round the Regen Shield at 650 is often better value than heavy armor at 1000",
    "let my team know Regen Shield exists at 650 credits, between light and heavy, use it smartly",
    "tell them Regen Shield regenerates after fights which means it carries value into next round too",
    "tell my teammates 650 for Regen Shield on a half buy round is often the right call",
    "tell them Regen Shield is the forgotten armor option, 650 credits, and it refills between fights",

    # ── SECOND-CONSECUTIVE ECO STRESS ────────────────────────────────────────────
    "tell my team second eco in a row now, stay disciplined, it sets up the full buy",
    "tell them second consecutive eco: same rules, Classic only, save everything",
    "let my teammates know we're on our second eco round in a row and that's the plan",
    "tell my squad second eco round: the loss bonus should be at 2400 now, check credits",
    "tell them two consecutive eco rounds means next round we should all be at full buy threshold",
    "tell my team two saves and we buy — we're on save two, next round full buy",
    "let my team know second consecutive eco means full buy next round is guaranteed if we hold",
    "tell them stay on eco this second round, the plan works if we're patient",
    "tell my teammates second eco round: same discipline, no sneaking in a force",
    "tell them two eco rounds is the price for a full buy that lasts multiple rounds",

    # ── PISTOL FORCE / SHERIFF FORCE SPECIFIC ────────────────────────────────────
    "tell my team pistol force: Sheriff and light armor if you have 1200, Ghost and light armor if not",
    "tell them we're pistol forcing this round: everyone buys Sheriff and plays for one-taps",
    "let my teammates know pistol force this round: Sheriff is the play at 800 plus 400 light armor",
    "tell my squad Sheriff force: 1200 total, everyone buy Sheriff and light armor",
    "tell them Sheriff force round because we can't afford SMGs but Sheriff one-taps at close range",
    "tell my team Sheriff and heavy armor is a 1800-credit pistol force that's actually competitive",
    "let my team know pistol force with Sheriffs: play aggressively, one-tap potential is real",
    "tell them Sheriff force means play for headshots: one-tap through light armor at close range",
    "tell my teammates Ghost force at 900 total if we can't afford Sheriffs: Ghost and light armor",
    "tell them the pistol force works if we all play for headshots and don't take body-shot duels",

    # ── ENEMY FORCE DETECTION ─────────────────────────────────────────────────────
    "tell my team enemy is forcing this round, expect Spectres and Sheriffs not Classics",
    "tell them they're forcing this round, not saving — they have some budget to spend",
    "let my teammates know enemy is on a force, not full buy but not eco either",
    "tell my squad they're forcing with SMGs, treat them like a half buy not an eco",
    "tell them enemy force round: they have Spectres, not Classics — don't underestimate",
    "tell my team they're forcing this round so it's not a free eco win for us",
    "let my team know enemy is forcing not saving: they have guns, play carefully",
    "tell them enemy force round means some of them have rifles and some have pistols",
    "tell my teammates watch for the enemy force: mixed loadouts, some strong some weak",
    "tell them enemy is forcing with Bulldogs and Guardians, not full buy but still dangerous",

    # ── THRIFTY WIN VS GUN-ROUND DISTINCTION ─────────────────────────────────────
    "tell my team if we Thrifty this round we break their economy mentally and physically",
    "tell them Thrifty win means we kept our economy and they wasted a full buy",
    "let my teammates know Thrifty eco win is worth more than a force win because economy stays intact",
    "tell my squad if we pull a Thrifty their full buy was wasted and our economy compounds",
    "tell them gun round is when both teams full buy: next round is a gun round and we need to buy",
    "tell my team gun round next: they'll have Vandals, we need Vandals too or we lose the duel",
    "let my team know next round is a gun round, coordinate the full buy now in this round",
    "tell them gun round coming up: full buy to match their Phantoms and Vandals",
    "tell my teammates if it's a gun round and we half buy we get out-gunned in every duel",
    "tell them gun round means we match their rifles, don't show up to a gun round with a Spectre",

    # ── ENEMY-ECONOMY LONG-FORM READS ─────────────────────────────────────────────
    "tell my team they've been full buying every round and their economy must be thin by now",
    "tell them three consecutive force buys with losses means their credits are almost gone",
    "let my teammates know if they keep forcing and losing their economy collapses next round",
    "tell my squad they're on their third straight force loss so their economy is at rock bottom",
    "tell them they can't sustain this full buy pattern if they keep losing these gun rounds",
    "tell my team if we win this round their economy breaks and they're forced to eco",
    "let my team know if we win here they're in eco next round and we press the full buy advantage",
    "tell them their economy is fragile after these losses: next round they either eco or force again",
    "tell my teammates win this gun round and we control the economy for the next three rounds",
    "tell them break their economy this round by winning the buy round fight",

    # ── AGGRESSIVE ECO TACTICS ────────────────────────────────────────────────────
    "tell my team eco rush B: all five go B main in the first ten seconds, no splits",
    "tell them eco rush A: full commit before their smokes are up",
    "let my teammates know eco round rush plan: all five hit one site before utility deploys",
    "tell my squad eco rush strategy: pick up their dropped guns and snowball the economy",
    "tell them eco rush with Classics: speed beats utility if we go before the smokes",
    "tell my team on eco we rush one site together, don't split or we give them easy kills",
    "let my team know eco rush: we all go A main, full commit at round start",
    "tell them eco round execution: all in on B at zero seconds, no default, full rush",
    "tell my teammates if we eco rush and land two kills we might just steal this round",
    "tell them eco rush can work if we all commit and don't second-guess the call",

    # ── EXTREME FRINGE ECONOMY SCENARIOS ─────────────────────────────────────────
    "tell my team we're at the credit cap, buy something or we lose credits next round",
    "tell them someone on our team is at 9000 credits, they need to buy or drop weapons now",
    "let my teammates know if you're at 8800 or above buy something before round start to not hit the cap",
    "tell my squad credit cap is 9000, if you're near it you must spend or you waste money",
    "tell them on a hard eco round if you're near the credit cap still buy at least light armor",
    "tell my team we're in overtime so economy is reset: 5000 per player, full buy everyone",
    "let my team know OT round: no carry-over, no loss bonus, 5000 flat for everyone",
    "tell them second half pistol and economy resets: everyone starts at 800, standard pistol buy",
    "tell my teammates spike plant bonus applies even on eco: 300 each to all living attackers",
    "tell them kill credit is 200 per kill even on eco rounds, stack those credits",

    # ── FINAL STRESS: AMBIGUOUS ECO VS FORCE VS HALF-BUY EDGE CASES ─────────────
    "tell my team if three of us are at 2400 we half buy, we don't force and we don't eco",
    "tell them two thousand four hundred credits is a half buy number not a force number",
    "let my teammates know 2400 is the loss bonus after two consecutive losses, eco and get it",
    "tell my squad half buy at 2400 each: Spectre and light armor and one ability",
    "tell them we force this round because the round count says we can't afford to save anymore",
    "let my team know force buy but keep it smart: Spectre and light armor, don't throw a Vandal into eco",
    "tell them we're eco-ing this round and it's a real eco, not a half buy — Classic only",
    "tell my team their Raze is glass cannon, Op and no armor, she has one shot or she dies instantly",
    "let my teammates know enemy glass cannon Op means she has no armor, body shots will kill her",
    "tell my squad they have a glass cannon Operator player, focus their body if you see them peeking",
    "tell them force round and I mean it: buy something, this isn't a save, this is a force",
    "tell my team anti-eco is NOT the same as our eco: we BUY on anti-eco, just lighter than full buy",
    "let my team know anti-eco versus our eco: anti-eco means we buy Spectres, our eco means we buy nothing",
    "tell them buy round versus bonus round: buy round means full rifles, bonus round means SMG only",
    "tell my teammates bonus round is NOT a full buy round — it's an SMG round, keep the pistol",
    "tell them the bonus round is specifically not the round to buy Vandals — save that credit",
    "let my squad know force round versus save round: force we spend all, save we spend nothing",
    "tell my team three types of eco: full save, half eco, and force eco — we're doing full save",
    "tell them full save means zero spend: Classic, no armor, no abilities, every credit banked",
    "tell my teammates half eco means we spend some but keep 2000 for next round",
    "let my team know force eco is a contradiction: you either force or eco, don't blend them",
    "tell them we save because the round count advantage lets us take the economic hit here",
    "tell my squad if the round count is 12-4 in our favour we save freely, economy is secondary",
    "tell them if we're losing 4-12 we can't eco our way back, we force every remaining round",
    "let my teammates know match score changes the economy calculus: comeback needs force not eco",
    "tell my team down 4-10 means no more eco rounds, we force and we commit every remaining round",
    "tell them if we're about to lose the match on round count we force, no more saving",
    "let my squad know don't eco when you need wins urgently — force and fight for every round",
    "tell them the economic decision depends on the scoreboard: up big means eco freely, down big means force",
]
