"""Stress pack: hard false-relay negatives.

Every item is stream narration, internal monologue, private thought, or
chat-directed commentary that CONTAINS a "tell/ask/let my team" surface
phrase embedded inside a non-command sentence.  The relay pipeline must
recognise that the SPEAKER IS NOT ISSUING A RELAY COMMAND and must fall
through without relaying anything.

Hard axes exercised
-------------------
  - "I should tell them X but Y" — hypothetical blocked by a qualifier
  - "do I tell them X or Y?" — open question, no decision made
  - "note to self: tell them X" — self-reminder, not a live command
  - "I keep telling them X and they never do it" — habitual complaint
  - "I told them X last round but they ignored it" — past-tense narration
  - "chat, should I tell them X?" — soliciting chat opinion
  - "I wish I could tell them X without tilting them" — conditional desire
  - "the problem is I can't tell them X right now" — negated capability
  - "every time I tell them to X they do the opposite" — pattern complaint
  - "I don't know whether to tell them X or just do it myself" — indecision
  - "thinking out loud: do I ask my team to X?" — explicit self-flag
  - "part of me wants to tell them X but that's too tilting" — internal debate
  - Non-roster name check: "tell my friend Dave X" — unknown name = no relay
  - Fragment narration: mid-sentence "...and I should tell the boys to..."

Agents, maps, ability names and callout terms verified against refs/*.md.
Kind: negative (~600 cases)
"""

ITEMS = [
    # =========================================================
    # BLOCK 1: "I should tell them / my team X but ..."
    # The qualifier clause makes it non-actionable narration.
    # =========================================================
    "I should tell my team to rotate B but they never listen",
    "I should tell them to save this round but they're already buying",
    "I should tell my team to stack A but I don't want to tilt anyone",
    "I should tell them to hold mid and stop peeking but it's pointless",
    "I should tell my squad to play retake but we have no ults",
    "I should tell the team to save but we're already committed",
    "I should tell them about the flank but I'm in the middle of a fight",
    "I should tell my team to fall back but the round is basically over",
    "I should tell them Jett has Op but they can see the kill feed",
    "I should tell my team to smoke B main but our Brimstone already died",
    "I should tell them to slow push but they've already rushed in",
    "I should tell my team to play default but the round's half over",
    "I should tell them to plant for CT but nobody is listening to me",
    "I should tell my team to buy Spectres this round but I doubt they will",
    "I should tell them to crossfire heaven but it's too late now",
    "I should tell my squad to drop me a Vandal but they're all broke too",
    "I should tell them Clove is lurking CT but they won't check",
    "I should tell the team to stay grouped but someone already split off",
    "I should tell them about the Killjoy Lockdown but they died already",
    "I should tell my team to go A but knowing them they'll rush B anyway",
    "I should tell them to play post-plant but our util is all gone",
    "I should tell my team KAY/O suppressed someone but they see the icon",
    "I should tell them to not push yet but they're going anyway",
    "I should tell my team the spike is at default but they already know",
    "I should tell them Reyna is lurking but I lost track of her",
    "I should tell my squad to take mid first but they never do",
    "I should tell the boys to fake A but our util is already on B",
    "I should tell them to full buy next but I'm not the one in charge",
    "I should tell my team the enemy has Operator on A but they'll peek anyway",
    "I should tell them to reset but we don't have time left",
    "I should tell my team to slow rotate but knowing them they'll sprint",
    "I should tell them Sage might rez but they're not going to wait around",
    "I should tell my squad to eco but they force buy every time we lose",
    "I should tell them to play off the wall but the smoke already faded",
    "I should tell my team to watch the flank but I'll get ignored",
    "I should tell them to flash before entry but they peeked dry already",
    "I should tell my team to anchor A but nobody wants that role",
    "I should tell them Cypher has cam at elbow but they'll just walk past it",
    "I should tell my squad to play passive this round but they're duelists",
    "I should tell them about the lurker but I'm not sure where she went",

    # =========================================================
    # BLOCK 2: "do I tell them X or Y?" — open indecision
    # =========================================================
    "do I tell them to push or should we wait for the spike to tick down",
    "do I tell my team to go B or does that give away the fake",
    "do I tell them to save or do we force with what we have",
    "do I tell my team about the Viper wall or is it obvious already",
    "do I tell them Fade is using Haunt or will they notice themselves",
    "do I tell the team to plant default or plant for CT",
    "do I tell them to rotate or hold and wait for more info",
    "do I tell my squad about the Sova dart or just run from it",
    "do I tell them to crossfire the defuse spot or just rush in",
    "do I tell my team to smoke heaven or should we use that smoke elsewhere",
    "do I tell them to drop me a rifle or just go in with this Ghost",
    "do I tell my team to eco or do we try to force a win here",
    "do I tell them KAY/O knifed someone or is it obvious from voice",
    "do I tell my team to fake A or actually commit",
    "do I tell them to slow push or just rush and take the site",
    "do I tell the boys about the off-angle on CT or let them figure it out",
    "do I tell them to play retake or just let the spike blow",
    "do I tell my team to anchor B or send everyone to A",
    "do I tell them Jett dashed into heaven or are they already watching it",
    "do I tell my squad to exit frag or save the guns",
    "do I tell them to tap the spike or full commit the defuse",
    "do I tell my team Killjoy has Lockdown ready or save that info",
    "do I tell them the enemy is walking or does my heavy breathing give it away",
    "do I tell my team to abort the execute or is it too late to turn back",
    "do I tell them to stack B or just send info and let them decide",
    "do I ask my team to drop me or tough it out on Ghost",
    "do I ask my team to save next or can we afford to force",
    "do I ask them to slow push or just let them go at their own pace",
    "do I ask my team to play off my smoke or call a different strat",
    "do I ask them to wait for Breach ult or push without it",

    # =========================================================
    # BLOCK 3: "note to self" / self-reminder patterns
    # =========================================================
    "note to self tell them about the B flank next round",
    "note to self: tell my team to buy Spectres on eco rounds",
    "mental note to tell the team to play B default more often",
    "I keep forgetting to tell them about Killjoy's setup on B",
    "I need to remember to tell my team to watch Yoru clones",
    "I need to remind myself to tell the squad about Reyna lurk patterns",
    "I always forget to tell my team Clove can ult when they die",
    "note to self: ask my team to communicate ult status in buy phase",
    "I should really start remembering to tell them about Fade's Haunt placement",
    "mental note: next time tell my team to slow push instead of rushing",
    "remind myself to ask the team about their eco before buying",
    "gotta remember to tell my squad to check hookah on Bind before crossing",
    "I keep forgetting to tell them that Sova dart covers that angle",
    "I'll tell my team about that Deadlock setup after the match",
    "I'll tell them about the off-angle in post-game review not mid-round",
    "I'll let my team know about that KJ Nanoswarm spot in the next game",
    "I'll remind the boys after this round to check that corner",
    "I'll tell my team to watch the vent flank in a future round",
    "I should tell the team about that one-way smoke during the break",
    "I'll mention to my team about Tejo drone spots after we lose this round",

    # =========================================================
    # BLOCK 4: habitual complaint patterns
    # =========================================================
    "I keep telling them to rotate faster but they just hold their spots",
    "every time I tell them to save they spend all their credits anyway",
    "I tell my team to smoke B main every round and they forget every time",
    "I tell them to hold mid and every single time they push early",
    "I've told my squad to eco three rounds in a row and they keep forcing",
    "every time I tell them about the lurker they ignore me and die",
    "I always tell my team to plant for CT but they plant default anyway",
    "I've been telling them to check hookah but they run past it every time",
    "every time I tell my team to play retake they try to entry instead",
    "I tell them KAY/O is suppressing and they still throw flashes out",
    "every round I tell my team to watch the flank and every round they don't",
    "I've told them Jett has Op three times this half and they still wide peek",
    "I tell my squad to drop me a rifle every round and nobody ever does",
    "every single time I tell them to slow push they rush in and die",
    "I keep telling my team to play off the wall and nobody ever does it",
    "I've said tell the team to play passive like five times today",
    "I tell them to crossfire the retake angle and they all stack one side",
    "every time I tell my team to tap the spike they just full commit",
    "I keep telling them Clove is going to ult and they don't play for it",
    "every round I tell my squad to play post-plant and they just push",

    # =========================================================
    # BLOCK 5: past-tense narration
    # =========================================================
    "I told my team to rotate to B but they stayed A and we lost the round",
    "I told them about the Viper wall and they pushed through it anyway",
    "I asked my team to eco last round and they all bought Vandals",
    "I told them Reyna was lurking and they walked right past her",
    "I asked my squad to drop me a rifle and nobody dropped anything",
    "I told my team to slow push and they just ran in and got wiped",
    "I told them KAY/O knifed the Skye and they still waited for the dog",
    "I told my team to play retake and they abandoned the site anyway",
    "I told them to anchor B and our anchor pushed up instead",
    "I asked my team to save and two of them force bought",
    "I told them the Sova arrow was going to hit that angle and they stood there",
    "I told my squad about the Killjoy setup and they ran straight into it",
    "I asked my team to hold the flank and nobody bothered",
    "I told them to plant for CT and they planted default again",
    "I told my team to play off my smoke and they all swung before it landed",
    "I told them Jett had Op and they dry peeked the long anyway",
    "I asked my team about their econ and nobody answered",
    "I told them to fake A and somehow they actually went A",
    "I told my squad to play passive and everyone peeked aggressive",
    "I told them to abort and they still pushed and it cost us the round",

    # =========================================================
    # BLOCK 6: chat-directed commentary
    # =========================================================
    "chat should I tell my team to rush B or slow push it",
    "chat, should I tell them to save or force buy this round",
    "chat, do you think I should tell my team Clove has ult",
    "chat: should I ask my team to stack A or spread it out",
    "chat should I tell my squad to play retake or just let it blow",
    "guys in chat, should I tell my team to eco or force here",
    "chat, do I tell them to plant for CT or plant for main",
    "chat should I ask my team to drop me a Vandal or just play pistol",
    "yo chat should I even tell my team the Killjoy has Lockdown",
    "chat: is it worth telling my team to slow push or just let them do their thing",
    "chat do I tell them about the Sova dart or is it pointless",
    "chat, should I tell my squad about the Fade prowler setup",
    "viewers, should I tell my team to rotate or hold",
    "chat is it even worth telling my team to play default this round",
    "chat: do I ask my team to play crossfire or is it too tilting to direct them",
    "chat should I tell my team about the off-angle or just let them get caught",
    "chat, do you think I should warn my squad about the lurker",
    "chat should I ask my team to communicate ult status or just track it myself",
    "chat do I tell the boys to eco next round or force the buy",
    "chat: should I tell my team to plant quick or wait for smokes",

    # =========================================================
    # BLOCK 7: hypothetical / conditional desire
    # =========================================================
    "I wish I could tell my team to rotate without it sounding like I'm calling them out",
    "I wish I could just tell them to eco without getting flamed",
    "if I could tell my team one thing it would be to check hookah every round",
    "I wish I could tell my squad about Reyna without giving away I'm watching her",
    "if only I could tell them about the Killjoy setup before they walked in",
    "I wish I could tell my team to slow push but the second I say it they rush",
    "I'd love to tell my team to play retake but our timings are always off",
    "I wish I could tell the boys about the lurker but I lost track of them",
    "if I told my team to save they'd think I was giving up on the round",
    "I'd tell my team to stack B but they'd just argue about it",
    "I wish I could tell my squad to play off the wall but nobody runs those lineups",
    "I'd love to tell my team to fake A but we burned all our A utility already",
    "if I told them to play passive they'd roast me in the chat",
    "I wish I could tell my team about the one-way smoke setup but we don't have Viper",
    "I'd ask my team to drop me a rifle but they're all too broke right now",
    "if I could tell my team to crossfire post-plant without them misreading me",
    "I'd tell my squad to tap the spike but they'll full commit no matter what I say",
    "I wish I could ask my team to wait for the ult but we don't have time",
    "I'd love to tell my team Jett has Op but they already know from the kill feed",
    "if only I could tell my team to check elbow every single time",

    # =========================================================
    # BLOCK 8: negated capability / "I can't tell them"
    # =========================================================
    "I can't tell my team to eco because we're already past the buy timer",
    "I can't tell them to rotate because I don't know where the enemies are",
    "I can't tell my team to plant because the site isn't clear yet",
    "I can't tell them to save now we're already committed to the push",
    "I can't tell my squad to go B because we have no smokes left",
    "I can't tell my team to fake A because we used all our A util",
    "there's no way to tell them about the Killjoy Lockdown without panicking everyone",
    "I can't tell my team to play retake with one person left alive",
    "I can't ask my team to drop me anything they're all broke",
    "I can't tell them to slow push the round is almost over",
    "I can't tell my squad to stack B we've already split the team",
    "there's no telling my team to abort now they're mid-entry",
    "I can't tell them about the Sova recon arrow it already revealed us",
    "I can't tell my team to plant for main we don't have anyone watching that side",
    "I can't ask them to wait for ults we're out of time",
    "I can't tell my team to play passive when we're down by four rounds",
    "impossible to tell my squad to take mid first when our initiator is dead",
    "there's no point telling my team to fall back they're already dead",
    "I can't tell them to crossfire when we only have two people left",
    "I can't ask my team to check vent I need them watching the plant",

    # =========================================================
    # BLOCK 9: "every time I tell them" complaint
    # =========================================================
    "every time I tell my team to take mid they go straight to a site",
    "every time I tell them to slow push someone rushes and dies",
    "every time I ask my team to eco they force buy and hand over rifles",
    "every time I tell my squad to play retake they hold spawn instead",
    "every time I tell them to watch the flank someone dies to the exact flank",
    "every time I ask my team to communicate they go completely silent",
    "every time I tell them about the lurker they stop rotating and get flanked",
    "every time I tell my team to save a Vandal they drop it on the way out",
    "every time I ask my squad to stack a site they spread out instead",
    "every time I tell them to play off the smoke they push before it lands",
    "every time I tell my team to plant for CT they plant default",
    "every time I ask my team to buy Spectres on force they go Vandals anyway",
    "every time I tell my squad to abort they keep pushing and we lose two people",
    "every time I tell them to fake B they actually go B and lose util",
    "every time I ask my team to eco they spend 4000 credits on guns",
    "every time I tell my team Clove has ult they ignore it and push anyway",
    "every time I tell them to play post-plant they chase kills",
    "every time I ask my squad to check heaven they look at ground level",
    "every time I tell my team to reset they just hold their positions",
    "every time I tell them KAY/O is suppressed they still flinch from Skye dogs",

    # =========================================================
    # BLOCK 10: "I don't know whether to tell them" indecision
    # =========================================================
    "I don't know whether to tell my team to go A or let them decide",
    "I'm not sure if I should tell them to eco or force this round",
    "I honestly don't know if I should tell my squad to stack B or spread",
    "not sure whether I should tell them about Fade's Haunt or play quietly",
    "I'm torn between telling my team to plant fast and telling them to wait for util",
    "I'm not sure if telling my team about the lurker will help or panic them",
    "I don't know if I should ask my team to abort or just let them push",
    "not certain whether I should tell my team to play retake or save for next",
    "I can't decide whether to tell them to tap the spike or full commit",
    "I'm genuinely uncertain whether to tell my team about the Killjoy setup",
    "I'm not sure if I should let them know Sova is droning or just run anyway",
    "I don't know whether to ask my team to wait for Breach ult or push without",
    "I'm debating whether to tell my squad to slow push or rush the site",
    "I can't figure out if telling my team to eco will cost us the round",
    "I'm not sure if I should ask them to drop me a rifle or make do with Ghost",
    "I'm second-guessing whether to tell my team to fake A or actually execute",
    "I don't know if telling the boys to play passive will tilt them",
    "not sure whether to tell my team about the one-way or keep it to myself",
    "I'm unsure if I should ask my team to watch the flank or trust they know",
    "I don't know whether to tell my squad to hold rotate or go now",

    # =========================================================
    # BLOCK 11: "thinking out loud" / explicit self-flag
    # =========================================================
    "thinking out loud here: do I tell my team to rush or slow it down",
    "thinking out loud: should I even ask my team to eco at this point",
    "just thinking out loud, should I tell my squad about the lurker",
    "thinking aloud: do I tell my team to commit A or fake it",
    "stream of consciousness: do I tell them to plant for CT or play safe",
    "talking to myself: I should tell my team to crossfire that angle",
    "processing out loud here: do I ask my team to save the Vandal or exit frag",
    "thinking through the round: do I tell them to rotate now or hold",
    "not relaying this, just thinking: my team needs to smoke that window",
    "just narrating for the stream: I should probably tell my team to slow push",
    "this is for chat not for my team: tell me if I should ask them to eco",
    "stream I'm thinking should I tell my team about the Killjoy Lockdown",
    "talking to the stream here: do I tell my squad to play retake or save",
    "just self-talk, not a command: tell my team to check elbow before planting",
    "this is internal: I want to tell them to stack A but I'll get ignored",
    "just narrating: should I ask my team to drop me or tough it out",
    "stream chat: do I tell my team to go B or is that giving away the play",
    "just verbalizing my thoughts: maybe I should tell them to play passive",
    "not telling my team yet, just thinking: should we save or force",
    "thinking out loud so chat can see: do I tell them about Clove ult",

    # =========================================================
    # BLOCK 12: "part of me wants to tell them" internal debate
    # =========================================================
    "part of me wants to tell my team to rush but the smart play is to slow push",
    "part of me wants to tell them to eco but we have a chance to win this round",
    "half of me wants to tell my squad to rotate but the other half says hold",
    "a voice in my head is saying tell my team to save but I want to fight",
    "I'm torn because part of me wants to tell them about the lurker and part doesn't",
    "part of me wants to tell my team to abort but we already committed the util",
    "part of me wants to ask my team to stack A but I think B is the right play",
    "I kind of want to tell my squad to fake it but we might not have the time",
    "part of me wants to tell them to plant for CT but default feels safer",
    "I keep second-guessing myself: part of me says tell my team to eco",
    "one side of me says tell my team to play passive, the other says be aggressive",
    "I want to tell my squad to play off the wall but they'd never pull it off",
    "part of me wants to say tell them to hold rotate but I'm not confident",
    "half of me wants to ask my team to wait for ults but we might run out of time",
    "I'm fighting the urge to tell my team to force buy when we probably should save",
    "part of me wants to tell them to go for the ninja defuse but it's risky",
    "I kind of want to tell my squad about the off-angle but it might distract them",
    "part of me says tell my team Reyna is lurking but they might over-rotate",
    "I'm debating internally: tell them to play retake or play for time",
    "part of me really wants to tell my team to reset but they hate resetting",

    # =========================================================
    # BLOCK 13: non-roster / unknown names (must not relay)
    # =========================================================
    "tell my friend Dave to rotate B because he never does",
    "I should tell my buddy Marcus about the Killjoy setup",
    "I keep meaning to tell Steve on my team to stop peeking that long",
    "tell my friend Alex to stop instalocking Jett every game",
    "I want to tell my friend Jordan that they should smoke heaven",
    "I should tell my roommate to eco this round but he'll force anyway",
    "note to self: tell my friend Sam to check hookah on Bind",
    "I keep telling my friend Tyler to watch for Sage rez and he never does",
    "I should tell my cousin Mike to stop wide peeking that corner",
    "I want to tell my friend Chris that Viper wall is blocking the rotate",
    "tell my friend Danny that KAY/O's knife suppresses agents",
    "I keep telling my friend Ryan to anchor B but he roams every round",
    "I should remind my friend Jake that Cypher cam is watching that angle",
    "tell my friend Ben about the Sova drone spot on this map",
    "I want to tell my duo partner Lucas to play more passive on defense",
    "I should tell my friend Noah to drop me a rifle instead of going in broke",
    "tell my friend Ethan that Clove can ult even when dead",
    "I keep forgetting to tell my friend Owen about the lurk route on Ascent",
    "I need to remind my friend Liam that Deadlock Grav Net traps you",
    "I should tell my friend Aiden to stop pushing through Viper wall",

    # =========================================================
    # BLOCK 14: mid-sentence narration fragments
    # =========================================================
    "we're losing every round and I should tell the boys to just save",
    "honestly the right play is to tell my team to rotate but they won't",
    "if we weren't on Twitch I'd tell my team exactly what I think about that push",
    "I'm about to tilt so hard and I just want to tell my squad to take a breath",
    "at some point I have to tell my team to stop buying Ares when we're on eco",
    "between rounds I'm going to tell my squad about the Killjoy trip placement",
    "before I die I should tell my team where the spike is but I don't see it",
    "after this round I'm going to tell my team to communicate ult status",
    "in the post-game lobby I'll tell my team that the rotate was way too slow",
    "at round start I'm always thinking I should tell my team to take mid first",
    "deep down I know I should tell my team to slow push but my hands push anyway",
    "honestly what I want to do is tell my squad to reset but it feels cowardly",
    "the sensible thing would be to tell my team to eco here but sensible doesn't win",
    "logically I should tell my team to plant for safety but the aggressive play wins",
    "in another life I'd tell my team to play passive every defense round",
    "on paper I should tell my team to anchor while I lurk but they can't anchor",
    "by all rights I should be telling my team to hold rotate right now",
    "if this were a pro match I'd tell my team to slow push and play for picks",
    "at a higher level of play I'd tell my team to wait for util before entry",
    "the meta says I should tell my team to take mid control first but this lobby doesn't do that",

    # =========================================================
    # BLOCK 15: question + uncertainty blends
    # =========================================================
    "wait, should I even be telling my team to rotate when I have no info",
    "hold on, do I tell them to go A right now or wait another fifteen seconds",
    "actually, should I tell my team to abort the execute or is it too late",
    "hmm, should I tell my squad to eco or is one more force worth it",
    "wait, should I tell my team about the Sova dart or just dodge it",
    "okay so like, do I tell them to fake A or actually go A",
    "hang on, is it worth telling my team to tap the spike or just stick it",
    "let me think — do I tell the team to plant for CT or play site default",
    "I'm second-guessing — should I tell my squad to watch the flank or push fast",
    "ugh, do I tell my team to crossfire the retake or just sit on default",
    "should I even ask my team to slow push or is rushing the better call here",
    "not sure — do I tell them to play post-plant or play for the round timer",
    "wait, is it a good idea to tell my team to stack B right now",
    "hmm, do I tell my squad Clove is going to ult or play around it myself",
    "honestly, should I be asking my team to eco two rounds in a row",
    "like, do I even bother telling my team about the lurk right now",
    "I'm thinking — should I ask them to save the rifle or just exit frag",
    "okay, do I tell my team to play off the wall or smoke the angle myself",
    "actually: do I ask my team to commit or hold off one more second",
    "let me figure this out — should I tell my team to abort or send it",

    # =========================================================
    # BLOCK 16: regret / past narration
    # =========================================================
    "I should have told my team to eco before they force bought",
    "I should have told them to rotate before the spike got planted",
    "if only I had told my squad to hold mid before Jett dashed through",
    "I wish I had told my team to anchor A before they all rotated off",
    "I should have asked my team to slow push before they rushed into the Killjoy setup",
    "if I had told them about the Viper wall timing we might have won that",
    "I should have told my team to save Vandals instead of dying with them",
    "in hindsight I should have told my squad to play retake instead of fighting",
    "I should have told them Reyna was lurking before she flanked our whole team",
    "I really should have asked my team to check hookah before crossing",
    "I should have warned them about the Sova arrow lining that angle",
    "if I had told them about the Cypher cam earlier we'd have dodged it",
    "I regret not telling my team to abort when we lost the first entry",
    "I should have told my squad to play off my wall not push into it",
    "looking back I should have told my team to wait for the KAY/O ult",
    "I should have asked my team to drop me a rifle before the round started",
    "I should have warned my team about the off-angle before they pushed",
    "if I had told them to plant for CT we'd have had better post-plant angles",
    "I should have told my team to stack B when I suspected the enemy was going A",
    "I should have told them to play passive that whole half instead of forcing",

    # =========================================================
    # BLOCK 17: talking to chat or audience, not team
    # =========================================================
    "chat I want to tell my team to rotate but they won't listen",
    "stream, should I tell my team to eco next round or go for it",
    "guys on Twitch, should I ask my team to stack B",
    "sub-goal for the stream: tell my team to communicate better",
    "one of my long-term goals is to tell my team to play slower",
    "chat, how do I even tell my team to play off the wall when they can't aim",
    "stream should I tell my squad about the Clove ult or surprise them with it",
    "I'm telling the stream right now that I want to tell my team to eco",
    "viewers, do I tell my team to abort or is that too tilting",
    "talking to Twitch not to my team: they need to stop force buying",
    "for the stream: part of me wants to tell my team to slow push",
    "chat I keep wanting to tell my team about the lurk but they ignore me",
    "this is for my audience: do I tell my squad to fake A",
    "Twitch chat, should I just tell my team to play retake already",
    "I'm narrating this for stream: I should tell my team to save the rifle",
    "for the viewers at home: my team needs someone to tell them to eco",
    "chat should I ask my team to play crossfire post-plant or sit on default",
    "Twitch, my team needs to be told to take mid and I'm scared to say it",
    "stream audience: do I tell my team the Killjoy has Lockdown or not",
    "chat, tell me whether I should ask my team to full buy or half buy",

    # =========================================================
    # BLOCK 18: philosophical / observer mode narration
    # =========================================================
    "the sign of a good IGL is knowing when to tell your team to reset",
    "pro players always tell their team to play post-plant instead of chasing kills",
    "at Diamond and above you have to tell your team to eco after double-loss",
    "the trick in ranked is knowing when to tell your team to slow push versus rush",
    "great IGLs know when to tell their team to abort and when to send it",
    "the hardest call in Valorant is when to tell your team to save or force",
    "good shotcallers always tell their team about enemy ult status after each round",
    "pro teams tell their teammates to play off each other not individually",
    "in competitive play you have to tell your team where to plant the spike",
    "the meta right now is to tell your team to take mid before committing to a site",
    "a good Cypher player tells their team where the cams are watching",
    "in ranked it's hard to tell your team to play passive without sounding tilted",
    "it's basic Valorant to tell your team when the smoke is fading",
    "top ranked players always tell their team to track enemy ults",
    "the Valorant meta demands you tell your team to take space early on defense",
    "great controllers tell their team where they're smoking before they pop",
    "advanced shotcalling means telling your team to abort when the execute is off",
    "a good Sova player tells their team where the arrow is before they fire it",
    "smart Valorant means telling your team to eco two rounds after a rifle loss",
    "elite play requires telling your team to play post-plant rather than fight retakes",

    # =========================================================
    # BLOCK 19: mid-sentence embed with dominant non-relay clause
    # =========================================================
    "I'm so tilted right now and part of that is I should tell them to eco",
    "we literally just lost three rounds and I keep saying I should tell them to save",
    "my hands are shaking because I know I should tell my team about the lurker",
    "I'm watching them die one by one and all I want to do is tell them to rotate",
    "it's round fourteen and I've been meaning to tell my team to take mid all game",
    "we're down seven to three and I keep thinking I should tell them to change strat",
    "I'm literally cringing watching this and wanting to tell my team to play default",
    "the problem with ranked is you can't just tell your team to play off the wall",
    "I've been holding my tongue but I really want to tell my squad to stack A",
    "I hate this map because you have to tell your team to play B default or you lose",
    "this is why I solo queue, nobody to tell my team to eco for me",
    "I'm about to go next and I didn't even tell my team to check that corner",
    "three rounds left and I'm thinking I should tell my squad to just save Vandals",
    "you can see in my face that I want to tell my team to abort but I don't",
    "I've been biting my tongue all half about telling my team to play passive",
    "the frustrating thing is I know I should tell my team to hold rotate but I froze",
    "we're about to go into overtime and I haven't told my team a single useful thing",
    "this is what happens when you can't tell your team to slow push in ranked",
    "I keep drafting the message in my head to tell my team to eco but I never send it",
    "half of the rounds we lost I was thinking I should tell them to reset",

    # =========================================================
    # BLOCK 20: surface-relay phrasing but clearly non-command
    # =========================================================
    "I mean, who do you even tell when your team rotates off without info",
    "there's no one to tell my team to anchor B they all wanna roam",
    "who exactly do I tell to stop baiting when everyone thinks they're the lurker",
    "you can't tell your team to slow push and then push slow yourself right",
    "what's the point of telling my team to eco when someone always breaks ranks",
    "it's wild to me that I even have to tell my team to communicate ult status",
    "I'm the only one who would tell my team to play post-plant and it's sad",
    "someone needs to tell my team to stop peeking that long angle with Spectre",
    "I'm always the one who has to tell my squad to take a breath mid-round",
    "why is it always me who has to tell my team to check hookah",
    "this is what it feels like when nobody tells your team to rotate until it's too late",
    "in my head I'm telling my team to abort the execute but out loud I say nothing",
    "I swear the next person who makes me want to tell my team to eco is going to get roasted",
    "it shouldn't have to be me telling my team to track the enemy ults",
    "the day my team tells itself to save without me having to say it will be the best day",
    "who decided it was my job to tell my team to slow push every single round",
    "I'm tired of being the one who has to tell my team to plant for CT",
    "the irony is I was about to tell my team to watch the flank right as we got flanked",
    "one of these days my team will tell itself to eco without me having to ask",
    "I'm done being the one who has to tell my squad everything every round",

    # =========================================================
    # BLOCK 21: conditional future narration
    # =========================================================
    "if we lose this round I'll tell my team to hard save next",
    "if they rush B again I'm going to tell my team to stack it next round",
    "once this round is over I'll tell my squad about the Killjoy trap placement",
    "if Sova arrows that angle I'll tell my team to run before it reveals us",
    "if they do the same fake A again I'm going to tell my team not to rotate",
    "after the half I'll tell my team to start playing off each other more",
    "when the round ends I'm going to tell my squad to play slower next half",
    "if the enemy eco-rushes I'll tell my team to hold short and not push out",
    "if we win this round I'll tell my team to full buy and end it",
    "if this round goes to overtime I'll tell my squad to focus up",
    "as soon as the buy phase starts I'll tell my team how much they should spend",
    "if Clove ults I'll tell my team to hold their positions and not push",
    "if the Operator is watching that angle I'll tell my team to not peek it",
    "once I respawn I'll tell my team where the spike is",
    "if we get picked before the execute I'll tell my team to abort",
    "when I have the drone up I'll tell my team where to push",
    "if they take mid control I'll tell my team not to push long",
    "when the smoke fades I'll tell my team to swing together not one at a time",
    "if the Sage walls B I'll tell my team to go A instead",
    "once I confirm the retake position I'll tell my squad whether to commit",

    # =========================================================
    # BLOCK 22: self-deprecating / awareness narration
    # =========================================================
    "I keep telling my team what to do and then doing the opposite myself",
    "I'll tell my team to eco and then watch myself buy a Vandal out of habit",
    "I say things like 'tell my team to slow push' and then sprint in first",
    "it's embarrassing that I have to tell my team the same callouts every round",
    "I tell my team to crossfire and then I'm the one who doesn't hold an angle",
    "I keep telling my squad to play passive and I'm the aggressor every round",
    "I say I'll tell my team to plant for CT and then I forget and plant default",
    "I want to tell my team to anchor B but I'm the one who always abandons it",
    "I keep promising to tell my team about the lurk route before it's too late",
    "I tell my squad to play off the wall and I'm the first one to cut through it",
    "I drafted the callout in my head to tell my team Reyna was lurking and said nothing",
    "I've been trying to figure out how to tell my team to reset without them quitting",
    "I know I should tell my squad to communicate ult status but I forget too",
    "I always plan to tell my team to eco but the moment I see a rifle I buy it",
    "I'm the least qualified person to tell my team to calm down when I'm tilting",
    "I keep telling my team to check hookah and I've walked past it myself twice today",
    "I told my squad to play retake and was the first one to go the wrong way",
    "I say I should tell my team to slow push and my own legs carry me to the rush",
    "I was about to tell my team the strategy and completely forgot what it was",
    "I'll tell my team one thing and then improvise something totally different",

    # =========================================================
    # BLOCK 23: social / meta-game narration
    # =========================================================
    "my rank would be so much higher if I could just tell my team to eco properly",
    "hardstuck Diamond because nobody told my team to play post-plant",
    "the only way to climb is to tell your team to do what the meta says",
    "I tried to tell my last team to eco and got flamed into oblivion",
    "the reason I'm solo queuing is that I can't tell my team to do anything useful",
    "in ranked you can't always tell your team about the lurker without being muted",
    "every Immortal player has been in a game where they wanted to tell their team to reset",
    "they should add a feature where you can tell your team to eco with one button",
    "I dream of a ranked system where I can tell my team to save and they actually listen",
    "the Valorant experience in a nutshell is wanting to tell your team to rotate and saying nothing",
    "my IGL dream is to be able to tell my team exactly what to do every round",
    "in a perfect world I'd tell my team about every enemy ability placement",
    "the hardest part of ranked is when you know you should tell your team to abort",
    "you'd think in Ascendant lobbies I could tell my team to slow push without pushback",
    "my biggest improvement area is learning when to tell my team to hold versus go",
    "I watch pro VoDs to learn when the IGL tells their team to reset versus send it",
    "I've seen streamers tell their team to eco and still get called out for it",
    "if I ever coach I'll tell my team to track ult status every single round",
    "the skill gap between Diamond and Ascendant is knowing when to tell your team to abort",
    "in high elo you tell your team exactly where each ability will land before you throw it",

    # =========================================================
    # BLOCK 24: interrupted / trailed-off narration
    # =========================================================
    "I was going to tell my team to rotate but then Jett dashed into me and I forgot",
    "mid-thought here: I should tell my team about the lurk but I got distracted",
    "I started to tell my team to eco and then the round just started",
    "I was literally about to tell them to slow push when the rush already started",
    "I had this whole plan to tell my team to fake A and then we just went A anyway",
    "I was going to ask my squad to stack B but the plant was already down",
    "I almost told my team to abort the execute but they were already mid-entry",
    "I started forming the callout to tell my team about the Killjoy setup and then I died",
    "I was two seconds from telling my team to save their rifles when the round ended",
    "I was thinking about whether to tell my team to play retake when the spike blew",
    "I had the idea to tell my team to play post-plant and I just never said it",
    "I was going to ask my squad to drop me a Vandal but the buy phase ended",
    "I was about to warn my team that Reyna was lurking but she already got the kill",
    "I drafted a whole speech to tell my team to communicate better and then I chickened out",
    "I was on the verge of telling my squad to hold mid when someone pushed through it",
    "I almost told my team Clove would ult but then Clove died without ulting",
    "I was going to tell my team to watch the flank right when the flank happened",
    "I had this idea to tell my team to play off each other and then we all solo peeked",
    "I was building up to tell my squad to eco and instead we bought full and lost anyway",
    "I was about to tell my team to go A and then I second-guessed myself and said nothing",

    # =========================================================
    # BLOCK 25: "ask my team" hypothetical and non-commands
    # =========================================================
    "how do you even ask your team to eco without sounding like you're giving up",
    "I never know how to ask my team to slow push without coming across as scared",
    "the question is do I ask my team to play retake or play for time here",
    "I wonder if I should ask my team to rotate before I have full info",
    "I've been trying to figure out how to ask my team to stack B without it being obvious",
    "I'd love to ask my team to drop me a rifle but that feels desperate",
    "how do you ask your team to play crossfire when they don't understand the concept",
    "I'm genuinely wondering whether to ask my team to abort or push through",
    "the big question is whether I should ask my team to fake or actually execute",
    "I don't know how to ask my team about their ults without making it awkward",
    "I've been debating whether to ask my squad to save for two rounds",
    "I'm not sure how to ask my team to play passive without killing their aggression",
    "I wonder if I should ask my team to use the Sova arrow before we commit",
    "the dilemma is whether to ask my team to play off the Viper wall or go around",
    "I keep going back and forth on whether to ask my team to anchor B or rotate",
    "I'm trying to decide whether I should ask my team to wait for KAY/O ult",
    "I need to figure out if I should ask my team to check elbow before pushing main",
    "the question I'm wrestling with is do I ask my team to play through mid or take A",
    "I don't know when the right moment is to ask my team to commit the execute",
    "I'm still deciding whether to ask my team to hold their positions or swing",

    # =========================================================
    # BLOCK 26: "let my team know" non-commands
    # =========================================================
    "I should let my team know about the Killjoy trap but I'm not sure where it is",
    "I need to let my team know that the enemy has Operator but first I need to survive",
    "I want to let my team know Reyna is lurking but I can't confirm her position",
    "I should let my team know the smoke is fading but I'm already dead",
    "I keep meaning to let my team know about the Sova arrow angles on this map",
    "I should let my squad know that Clove can ult after dying but they probably know",
    "I want to let my team know the Cypher cam is watching short but I got trade-killed",
    "I should let my team know about the Deadlock Grav Net placement but it's obvious",
    "I need to let my team know the spike timer is low but I don't know exactly",
    "I was going to let my team know the smoke is fading before they pushed",
    "I should let my squad know they're walking through mid but they can hear it",
    "I want to let my team know Jett used her dash but I'm not sure if she has another",
    "I should let my team know about the off-angle on CT but it might confuse them",
    "I need to let my squad know the enemy eco'd but they can count the kills",
    "I should let my team know the KAY/O knife is up but I don't know for sure",
    "I want to let my team know the Sage wall is down before they push",
    "I should let my squad know that Killjoy Lockdown is coming but I need to spec it",
    "I need to let my team know the Tejo drone is out but it's moving too fast to track",
    "I was about to let my team know about the lurker when I got taken out",
    "I should let my team know the execute is falling apart before it's too late",

    # =========================================================
    # BLOCK 27: "tell the boys / tell the guys" non-relay variants
    # =========================================================
    "I should tell the boys to eco but they're going to laugh at me",
    "I want to tell the guys to slow push but they'll think I'm scared",
    "I keep telling the boys to rotate and they just hold their positions",
    "I should tell the lads to take mid first but this is ranked not pro play",
    "I told the guys to save and watched them all buy rifles like it was a joke",
    "I'm thinking about telling the boys to fake A but we have no A utility",
    "I should tell the guys about the Killjoy setup but it's probably already reset",
    "I want to tell the lads to plant for CT but they'll plant wherever they want",
    "I've been telling the guys to check hookah for three rounds and they walk past it",
    "I should tell the boys to play post-plant instead of rushing the retake",
    "I told the lads to crossfire the spike and they both swung from the same angle",
    "I want to tell the guys to wait for ults before the execute but time is short",
    "I should tell the boys about the one-way smoke opportunity but we have no Viper",
    "I keep telling the lads to play passive and they're the most aggressive team I've seen",
    "I want to tell the guys to tap the spike but they'll just stick it anyway",
    "I should tell the boys to abort when we lose the entry but they never do",
    "I told the lads to slow push and they ran in faster than normal",
    "I should tell the guys to watch the flank through mid but they're all looking site",
    "I want to tell the boys to exit frag and save rifles but they fight to the end",
    "I should tell the lads to communicate ult status and maybe someone will eventually",

    # =========================================================
    # BLOCK 28: tightly disguised surface-relay with dominant
    # non-command outer clause (hardest single-line cases)
    # =========================================================
    "the irony is I literally just told my team to slow push and then I sprinted",
    "I'm the person who always tells my team to eco and then buys an Operator",
    "if I had a dollar for every time I told my team to rotate I'd be rich",
    "telling my team to save has never once worked in this game's history for me",
    "me telling my team to plant for CT: ignored. enemy planting for CT: wins every time",
    "the fact that I have to tell my team about Killjoy every map is unbelievable",
    "I know I need to tell my squad to play post-plant but the muscle memory isn't there",
    "my whole IGL philosophy is built on telling my team to slow push and nobody cares",
    "I've been wanting to tell my team to stack B for eight rounds and I keep hesitating",
    "it never gets old how useless it is to tell my team to eco when they don't want to",
    "I was literally mid-sentence telling my team to abort when we got wiped",
    "there's something poetic about telling my team to play crossfire and dying first",
    "I'll tell my squad to check heaven every match and they look at the floor every time",
    "the year I start actually telling my team to play retake is the year I hit Immortal",
    "I put so much thought into whether to tell my team to rotate and then they just die anyway",
    "I'm not ready to tell my team to force because I don't trust the timing",
    "I haven't told my team to play off the Viper wall because I don't think they understand it",
    "the number of times I've stopped myself from telling my team to reset is embarrassing",
    "one of my biggest weaknesses is not telling my team to plant quick when we need to",
    "telling my team to check vent is a lesson they refuse to learn this game",
    "I'm still not sure it's the right call to tell my team to go B this round",
    "the only reason I haven't told my team to save is I think we can still win this",
    "I've lost count of the times I wanted to tell my team to slow down and just said nothing",
    "I'm not saying I should tell my team to eco I'm saying it's probably the right call",
    "at no point today have I successfully told my team to slow push and had them comply",
    "someday I'll work up the nerve to tell my team to abort mid-execute",
    "I had every intention of telling my team to buy Spectres and then said nothing",
    "I'm barely managing to tell my team to communicate ult status let alone play retake",
    "what good is telling my team to play crossfire if they don't know what crossfire means",
    "I've been building up to telling my squad to play passive for six rounds straight",
]
