ITEMS = [
    # --- ULT COOLDOWN / READINESS QUESTIONS (relay the question, never answer) ---
    "ask Omen if his ult is ready",
    "tell them to ask Omen how long till he can ult again",
    "ask Sage if her ult is up",
    "tell the team Sage says she wants to know if her ult is charged",
    "ask Killjoy if Lockdown is ready",
    "ask Brimstone if Orbital Strike is up this round",
    "tell my team to ask Reyna how many orbs she needs for Empress",
    "ask Phoenix how many kills he needs to get his ult",
    "ask Jett if Blade Storm is up",
    "ask Neon if Overdrive is ready",
    "tell them Raze wants to know if she has Showstopper yet",
    "ask Yoru if Dimensional Drift is charged",
    "ask Iso if Kill Contract is ready",
    "ask Waylay if Convergent Paths is up",
    "ask Viper if her pit is ready",
    "ask Astra if Cosmic Divide is up",
    "ask Harbor if Reckoning is charged",
    "ask Clove if Not Dead Yet is ready",
    "ask Sova if Hunter's Fury is up",
    "ask Breach if Rolling Thunder is charged",
    "ask Skye if her Seekers are ready",
    "ask Kayo if Null-cmd is up",
    "ask Fade if Nightfall is ready",
    "ask Gekko if Thrash is charged",
    "ask Tejo if Armageddon is up",
    "ask Cypher if Neural Theft is ready",
    "ask Chamber if Tour de Force is charged",
    "ask Deadlock if Annihilation is ready",
    "ask Vyse if Steel Garden is up",
    "ask Veto if Evolution is charged",
    # --- COOLDOWN DURATION QUESTIONS (classic invented-number trap) ---
    "ask Omen how many seconds till his ult comes back",
    "ask Sage how long her ult cooldown is",
    "ask Killjoy how long Lockdown takes to come back after use",
    "tell the team to ask Sova how long his recon bolt cooldown is",
    "ask Skye how fast her hawk recharges",
    "ask Breach how long till Fault Line is back",
    "ask Kayo how long the NULL/cmd lasts",
    "ask Viper how fast her fuel regenerates",
    "ask Brimstone how long his smokes last",
    "ask Omen how long Dark Cover takes to recharge",
    "ask Astra how long after using a star before she gets it back",
    "ask Harbor how long Reckoning lasts",
    "ask Clove how long she has to get a kill after her ult revives her",
    "ask Fade how long the terror trail lasts",
    "ask Gekko how long before he can reclaim Dizzy",
    "ask Tejo how long his drone suppression lasts",
    "ask Cypher how long till his cam is back after it gets destroyed",
    "ask Sage how long her slow orb lasts",
    "ask Chamber how long his teleport cooldown is",
    "ask Deadlock how long the GravNet lasts",
    "ask Vyse how fast Arc Rose recharges",
    "ask Veto how long his Interceptor stays active",
    "ask Reyna how long Empress lasts if she keeps getting kills",
    "ask Phoenix how long Run it Back gives him",
    "ask Yoru how long Dimensional Drift lasts",
    "ask Iso how long Kill Contract gives him in the arena",
    "ask Waylay how long her Refract beacon stays on the ground",
    "ask Jett how many kills she needs to recharge her dash",
    "ask Raze how many kills to recharge Paint Shells",
    "ask Neon how many kills reset her slide",
    # --- ABILITY CHARGE / COUNT QUESTIONS ---
    "ask Breach how many flashes he has left",
    "ask Phoenix how many flashes he has",
    "ask Skye how many hawk charges she has this round",
    "ask Kayo how many flash charges he has",
    "ask Yoru how many blindside flashes he has left",
    "ask Jett how many smokes she has",
    "ask Sova how many shock bolts he has",
    "ask Reyna how many leer charges she has left",
    "ask Omen how many step charges he has",
    "ask Cypher how many trapwires he has left",
    "ask Cypher how many cages he has",
    "ask Sage how many slow orbs she has left",
    "ask Killjoy how many nanoswarms she has",
    "ask Deadlock how many sonic sensors she has left",
    "ask Vyse how many razorvines she has",
    "ask Veto how many crosscut teleports he has left",
    "ask Raze how many blast packs she has",
    "ask Neon how many relay bolts she has",
    "ask Iso how many undercut bolts he has left",
    "ask Fade how many prowlers she has",
    "ask Tejo how many guided salvo missiles he has left",
    "ask Gekko how many mosh pits he has",
    "ask Harbor how many high tides he has left",
    "ask Clove how many smokes she has this round",
    "ask Astra how many stars she has left",
    "ask Brimstone how many smokes he still has",
    "ask Chamber how many headhunter bullets he has left",
    "ask Viper how many snakebite charges she has",
    "ask Sova if he has his drone this round",
    "ask Tejo if he still has his stealth drone",
    # --- ABILITY STATUS / USED OR NOT QUESTIONS ---
    "ask Sage if she already used her heal this round",
    "ask Omen if he used his paranoia yet",
    "ask Killjoy if her turret is up or has it been destroyed",
    "ask Cypher if his cam is still up",
    "ask Sova if he already threw his recon bolt",
    "ask Breach if he still has his fault line",
    "ask Skye if her tiger is out or has she used it",
    "ask Kayo if he threw his knife yet",
    "ask Fade if she already used her haunt",
    "ask Gekko if Wingman is still available or did he use it",
    "ask Viper if her wall is currently active",
    "ask Astra if she already activated all her stars",
    "ask Harbor if he used his cove yet this round",
    "ask Clove if she has smokes left or did she use both",
    "ask Chamber if his teleport anchor is still up",
    "ask Deadlock if her barrier mesh is deployed",
    "ask Vyse if her shear trap was triggered yet",
    "ask Veto if his interceptor is active right now",
    "ask Reyna if she used both her leers already",
    "ask Yoru if his gatecrash tether is still out there",
    "ask Iso if he still has his wall",
    "ask Waylay if her beacon is placed yet",
    "ask Jett if she already used her updraft",
    "ask Neon if she burned her high gear this round",
    "ask Raze if her boom bot is still running",
    "ask Phoenix if he used his hot hands",
    "ask Brimstone if his stim beacon is down or still active",
    "ask Tejo if he fired both salvo missiles already",
    "ask Deadlock if her gravnet is on cooldown",
    "ask Fade if her seize is on cooldown",
    # --- HP / HEALTH STATE QUESTIONS ---
    "ask Sage if she can still heal someone",
    "ask Skye how much healing she has left in her regrowth",
    "tell the team to ask Sage how much health she has right now",
    "ask Clove if she has enough HP to fight aggressively",
    "ask Reyna if she has souls to devour",
    "ask Phoenix if he healed up using his wall",
    "tell my team to ask Sage if she already healed herself this round",
    "ask Clove if her overheal is still active",
    "ask Iso if he has his double tap shield charged",
    "ask Veto if Evolution is giving him regen right now",
    # --- SUPPRESS / STATUS QUESTIONS ---
    "ask Kayo if his knife suppressed anyone",
    "ask Tejo if his drone suppression is still on them",
    "ask if the enemy Reyna is suppressed so she can't dismiss",
    "tell them to ask Kayo how long the suppression lasts on the Jett he hit",
    "ask Iso if the undercut suppressed their Skye",
    "ask Fade if the prowler nearsighted anyone on their team",
    "ask if the enemy is still in the GravNet or did they get out",
    "ask Vyse if her Steel Garden jammed their primaries yet",
    "ask if the enemies are still detained from KJ Lockdown",
    "ask if the Deadlock cocoon is going to make it to the kill point",
    # --- ENEMY ABILITY / ULT TRACKING QUESTIONS (relay to team) ---
    "ask the team if they know how many ults the enemy has",
    "tell my team to ask if the enemy Killjoy has ult",
    "ask if anyone knows whether the enemy Sage has rez ready",
    "ask the team if the enemy Viper still has her pit",
    "tell them to ask if the enemy Omen already used his ult",
    "ask if anyone tracked whether the enemy Sova burned his recon",
    "ask the team if the enemy Jett still has her dash",
    "ask if the enemy Reyna used empress or is she saving it",
    "ask if anyone saw the enemy Kayo throw his knife this round",
    "tell the team to ask if the enemy Skye used both her hawks",
    "ask the team if the enemy Breach has Rolling Thunder",
    "ask if the enemy Iso got his kill contract off last round",
    "ask if we know whether the enemy Clove has not dead yet ready",
    "ask the team if the enemy Cypher has Neural Theft",
    "tell them to ask if the enemy Fade has Nightfall up",
    "ask if anyone knows if the enemy Chamber has Tour de Force",
    "ask the team if the enemy Gekko already threw Thrash",
    "ask if the enemy Tejo still has armageddon or did he use it",
    "ask if the enemy Deadlock has Annihilation charged this round",
    "ask the team if the enemy Vyse has Steel Garden",
    # --- SPIKE / PLANT / DEFUSE STATUS QUESTIONS ---
    "ask if anyone can see the spike",
    "tell the team to ask who has the spike right now",
    "ask Gekko if Wingman can defuse the spike from here",
    "ask if there is time left to defuse the spike",
    "ask if the spike has been planted yet",
    "tell them to ask which site the spike is on",
    "ask if we know where the spike is planted",
    "ask if the Wingman defuse is going to make it in time",
    "ask if the spike is planted for main or for CT",
    "ask if we have time to retake and defuse",
    # --- ECONOMY / BUY STATE QUESTIONS (relay to team) ---
    "ask the team if they are full buying or saving this round",
    "ask if anyone needs a rifle drop this round",
    "tell the team to ask if we are forcing or saving",
    "ask how many people can afford a Vandal this round",
    "ask if anyone is short on credits and needs a gun",
    "tell the team to ask if we should eco or force next round",
    "ask if anyone knows what the enemy bought this round",
    "ask the team if the enemy is on eco or full buy",
    "ask if anyone can drop me a Phantom this round",
    "ask if we can afford abilities on top of rifles this round",
    "ask if the team has enough to buy heavy armor this round",
    "tell them to ask if they should save utility to bank credits",
    "ask if three people can full buy or are we half buying",
    "ask who has an Operator this round",
    "ask if anyone picked up an enemy gun off the floor",
    # --- ROTATION / POSITION QUESTIONS ---
    "ask if anyone is watching mid",
    "tell the team to ask who is holding A main right now",
    "ask if anyone has eyes on B site",
    "ask if Cypher's cam can see CT",
    "ask where the last enemy is",
    "ask if anyone knows if the enemy rotated off A",
    "tell my team to ask if mid is clear",
    "ask if the lurker went through mid or hookah",
    "ask if anyone has info on where their last player is",
    "ask if the Sova drone spotted the defuser",
    "ask if anyone can check cam for CT",
    "ask if Fade's haunt revealed how many are on site",
    "ask if Sova's recon hit anyone",
    "ask if the Kayo knife suppressed the whole site",
    "ask if the Tejo drone spotted anyone on B",
    "ask if Cypher got a dart on any of them",
    "ask if anyone saw which way they rotated",
    "ask if there are still three on B or did someone leave",
    "ask where the Omen ulted to",
    "ask if Yoru faked the teleport or did he actually go",
    # --- COMPOUND ABILITY STATE MULTI-QUESTIONS ---
    "ask Skye if she has a hawk and a tiger left",
    "ask Breach if he still has both flashes and his fault line",
    "ask Kayo if he has his knife and his flash this round",
    "ask Fade if she has haunt and prowlers available",
    "ask Gekko if Dizzy and Wingman are both recharged",
    "ask Tejo if he has his drone and missiles both",
    "ask Viper if she has fuel and snakebite available",
    "ask Brimstone if he still has smokes and his molly",
    "ask Killjoy if her nano and bot are both set up",
    "ask Cypher if his cam and trips are both deployed",
    "ask Sage if she has her wall and slow orb this round",
    "ask Deadlock if she has both sensors and gravnet available",
    "ask Harbor if he has cove and high tide both",
    "ask Clove if she has smokes and her meddle",
    "ask Omen if he has step and paranoia available",
    "ask Astra if she has stars left for a smoke and a pulse",
    "ask Chamber if he has bullets in his headhunter and his trap is up",
    "ask Vyse if she has arc rose and shear both active",
    "ask Veto if his chokehold and crosscut are both available",
    "ask Iso if he has wall and undercut this round",
    # --- HARDER PHRASING / CASUAL SPEECH VARIANTS ---
    "yo ask Sage if her ult is back yet",
    "can someone ask Killjoy if she has lockdown",
    "somebody ask Omen if his ult is up",
    "tell them Raze wants to know if she can ult",
    "ask whoever is Sova if recon is off cooldown",
    "ask our Skye if seekers are ready to go",
    "can you tell the team to ask if Viper's pit is charged",
    "ask brimstone over there if he has smokes",
    "tell the boys to ask if KJ turret is still up",
    "ask whoever is on Chamber if his TP anchor is alive",
    "ask our Fade if she has nightfall this round",
    "ask if our Breach has thunder ready or not",
    "tell them to check if Clove has her ult available",
    "ask the Cypher if he got a dart on anyone yet",
    "ask whoever is playing Tejo if armageddon is charged",
    "ask our Astra if she has enough stars for this execute",
    "ask the Deadlock if annihilation is ready",
    "ask our Vyse if steel garden is fully charged",
    "ask our Veto if evolution is up this round",
    "ask the Yoru if he has dimensional drift",
    # --- RELAY QUESTION PHRASING (explicit relay directive) ---
    "tell my team to ask Sage how long till ult",
    "relay to the squad that we need to know if KJ has lockdown",
    "pass it on that I want to know if Omen has ult",
    "tell the guys to ask if Viper is full on fuel",
    "ask the team on my behalf if anyone knows where their lurker is",
    "relay that I need to know if Sova burned his recon",
    "tell them on my behalf to ask whether Breach has thunder",
    "ask my team if Fade's prowlers are on the trail",
    "relay to them that I want to know if Skye has hawk left",
    "tell my squad to ask if Kayo knife hit anyone on site",
    "relay to the team to ask if the enemy Jett has dash",
    "tell the guys I need to know if Astra has cosmic divide charged",
    "ask them on my behalf if Harbor's cove is shielded",
    "relay that I want to know if Clove can smoke after dying",
    "tell my team to ask if Gekko got his wingman back",
    # --- EDGE CASE: QUESTION ABOUT OWN ABILITY STATE ---
    "ask my team if my Sage ult looks charged from the scoreboard",
    "ask the team if they can tell whether I have ult from the board",
    "ask if anyone noticed whether the Killjoy lockdown is charged",
    "relay that I want to know if the team thinks I should use ult now",
    "ask my team if now is the right time for me to drop lockdown",
    "ask the squad if they want me to use my ult this round",
    "tell the team to ask me when I want to pop orbital",
    "ask if anyone thinks I should save my Viper pit for post-plant",
    "ask the team if they need me to use seekers now or hold",
    "ask if they want rolling thunder now or next round",
    # --- ABILITY COST / ECONOMY BAIT QUESTIONS ---
    "ask how much Sage's ult costs in ult points",
    "ask how many orbs Sage needs to rez someone",
    "ask how many kills Reyna needs to get Empress",
    "ask how many ult points Killjoy needs for Lockdown",
    "ask how many points Phoenix needs for Run it Back",
    "ask how many points Sova needs for Hunter's Fury",
    "ask how many ult orbs Breach needs for Rolling Thunder",
    "ask how many points Omen needs for From the Shadows",
    "ask how many points Clove needs for Not Dead Yet",
    "ask how many orbs Yoru needs for Dimensional Drift",
    "ask how many points Jett needs for Blade Storm",
    "ask how many points Raze needs for Showstopper",
    "ask how many ult points Viper needs for her pit",
    "ask how many kills Iso needs for Kill Contract",
    "ask how many orbs Waylay needs for Convergent Paths",
    "ask how many ult points Fade needs for Nightfall",
    "ask how many points Tejo needs for Armageddon",
    "ask how many points Gekko needs to ult",
    "ask how many points Kayo needs for Null-cmd",
    "ask how many points Astra needs for Cosmic Divide",
    # --- SPECIFIC DAMAGE / HP BAIT ---
    "ask how much damage Sova's recon bolt does",
    "ask how much damage Breach's aftershock deals per tick",
    "ask how much damage Killjoy's nanoswarm does per second",
    "ask how much damage Brimstone's orbital strike does total",
    "ask how much damage Viper's snakebite deals",
    "ask how hard the Raze rocket hits at center",
    "ask how much damage Tejo's guided salvo does per missile",
    "ask how much Astra gravity well hurts when it pulls",
    "ask how much damage Fade's seize decay does",
    "ask how much the Deadlock annihilation cocoon has for HP",
    "ask how much HP a Sage wall starts with",
    "ask how much damage the Reyna leer does",
    "ask how much damage Skye tiger does on the leap",
    "ask how much damage Neon relay bolt deals",
    "ask how hard the Iso undercut hits when it explodes",
    "ask how much damage the Harbor reckoning wave does",
    "ask how much damage Chamber tour de force does to body",
    "ask how much damage Vyse razorvine does per tick",
    "ask how hard Veto chokehold decays enemies",
    "ask how much damage Clove meddle decay does at full duration",
    # --- DURATION / TIMING QUESTIONS THAT BAIT INVENTION ---
    "ask how long Omen paranoia blinds for",
    "ask how long Reyna dismiss lasts",
    "ask how long KJ lockdown detains enemies for",
    "ask how long Sage slow orb lasts on the ground",
    "ask how long Viper toxic screen stays up without fuel",
    "ask how long Yoru's dimensional drift invisibility lasts",
    "ask how long Clove not dead yet keeps her alive after reviving",
    "ask how long Sova recon bolt takes to scan twice",
    "ask how long Breach rolling thunder concuss lasts",
    "ask how long Skye seekers nearsight enemies for",
    "ask how long Fade haunt reveals enemies after the eye is destroyed",
    "ask how long Gekko thrash detains for",
    "ask how long Tejo stealth drone suppresses enemies",
    "ask how long Deadlock gravnet forces enemies to crouch",
    "ask how long Vyse shear wall stays indestructible",
    "ask how long Harbor cove shield lasts before it breaks",
    "ask how long Astra nova pulse concusses for",
    "ask how long Kayo null cmd pulses suppression",
    "ask how long Waylay refract transit invulnerability lasts",
    "ask how long Iso kill contract arena gives them to fight",
    # --- RANGE / RADIUS QUESTIONS ---
    "ask how far Omen can throw his dark cover",
    "ask how wide Brimstone's stim beacon buff radius is",
    "ask how far Sova's recon bolt can scan enemies",
    "ask what range Killjoy turret covers in its cone",
    "ask how big Viper's pit radius is",
    "ask how far Kayo zero point suppression reaches",
    "ask how wide Astra cosmic divide stretches",
    "ask how far Tejo salvo missiles can be targeted",
    "ask how big the Breach rolling thunder cone is",
    "ask what radius Harbor reckoning wave covers",
    "ask how wide Deadlock annihilation can reach",
    "ask how far Fade nightfall wave travels",
    "ask how big Vyse steel garden radius is",
    "ask how wide Clove meddle area of effect is",
    "ask how far Chamber trademark slows after triggering",
    "ask how far Cypher spycam dart can mark someone",
    "ask what range KJ nanoswarm has when it activates",
    "ask how wide Astra gravity well pull is",
    "ask how far Skye seekers can detect enemies from",
    "ask what range Veto chokehold covers",
    # --- RESPOND-TO-X FORMAT ---
    "respond to Sage asking if we need her ult this round",
    "respond to Killjoy asking if she should drop lockdown on site",
    "respond to Viper asking if she should toggle her wall now",
    "respond to Omen asking if he should ult for flank",
    "respond to Sova asking if he should drone before we go",
    "respond to Breach asking if he should use rolling thunder now",
    "respond to Skye asking if seekers are worth it this round",
    "respond to Kayo asking if he should knife the site",
    "respond to Astra asking if she should pulse or smoke first",
    "respond to Clove asking if she should smoke after dying",
    "respond to Cypher asking if he needs to move his cam",
    "respond to Chamber asking if he should TP to safety",
    "respond to Deadlock asking if she should pop annihilation",
    "respond to Fade asking if nightfall is worth using this round",
    "respond to Gekko asking if Wingman should plant or should he do it",
    "respond to Tejo asking if he should fire both missiles at the same spot",
    "respond to Harbor asking if he should shield the cove",
    "respond to Vyse asking if she should activate steel garden now",
    "respond to Veto asking if evolution is worth saving for next round",
    "respond to Raze asking if she should rocket the site",
    "respond to Jett asking if she should dash in or wait",
    "respond to Neon asking if she should sprint entry now",
    "respond to Phoenix asking if he should ult entry and risk it",
    "respond to Iso asking if he should pull someone with kill contract",
    "respond to Reyna asking if empress is worth activating right now",
    "respond to Yoru asking if he should ult and gather info",
    "respond to Waylay asking if she should use convergent paths to zone them",
    "respond to Brimstone asking if orbital is worth it this round",
    "respond to Sage asking if now is a good time to rez",
    "respond to KJ asking if lockdown will hit before they defuse",
    # --- ASK-ABOUT-ENEMY-AGENT QUESTIONS ---
    "ask if anyone knows how many ult points the enemy Sova has",
    "ask if the enemy Reyna has orbs to dismiss right now",
    "ask if the enemy Jett burned her dash already this round",
    "ask if the enemy Sage already used her ult on someone",
    "ask if the enemy Killjoy has ult or did she use it last round",
    "ask if anyone tracked whether the enemy Viper has fuel left",
    "ask if the enemy Omen can still smoke or did he use them all",
    "ask if the enemy Breach has his thunder or not",
    "ask if the enemy Phoenix has Run it Back active right now",
    "ask if the enemy Skye still has hawks",
    "ask if the enemy Kayo knife already went off on site",
    "ask if the enemy Fade already haunted our side",
    "ask if the enemy Yoru faked that teleport or was it real",
    "ask if anyone knows how many nanoswarms KJ has placed",
    "ask if the enemy Cypher cam is still up after we shot at it",
    "ask if the enemy Clove can still smoke after she dies",
    "ask if the enemy Deadlock used her gravnet on site",
    "ask if the enemy Chamber still has TP anchors up",
    "ask if the enemy Vyse Arc Rose is still deployed by window",
    "ask if the enemy Veto evolved already or is saving it",
    # --- HARD / NATURAL PHRASING VARIANTS ---
    "someone ask if KJ Lockdown is going to hit us before we defuse",
    "tell the team to ask whether we should rush before Omen ult expires",
    "pass along that I need to know if Sage can still rez if she dies first",
    "ask the squad if they want Kayo to knife before we go or after smokes",
    "let them know I need to know if Breach has thunder before we commit",
    "ask the guys if Fade is ready to nightfall the site",
    "tell my team whether or not the enemy Sage has rez",
    "ask if we should wait for Sova to recon before we go in",
    "ask if Tejo already used his armageddon on B or is it still up",
    "tell the boys to ask Astra if cosmic divide is ready for the execute",
    "ask if the enemy has abilities left or are they utility dry",
    "ask if our Clove has smokes available even if she dies early",
    "relay that we need to know if Viper's pit is going to stay up",
    "ask if Killjoy already activated her nanoswarms on spike",
    "ask the team if Cypher's cam can see the defuser from there",
    "ask if Gekko can reclaim Wingman in time to use it again",
    "ask the squad if Sova recon revealed how many are left on site",
    "tell them to ask if the enemy KJ Lockdown detonates before the spike",
    "ask if Fade trails will still be active when we push",
    "ask if anyone knows whether the enemy Astra has stars left",
    # --- MULTI-PLAYER ULT TRACKING QUESTIONS ---
    "ask the team how many ults we have across the squad this round",
    "tell them to ask who has their ult ready and who does not",
    "ask if both Sage and KJ have ult or just one of them",
    "ask if our ult advantage means we should go this round",
    "tell the team to ask how many enemy ults we know about",
    "ask if we are up on ults or are they even",
    "ask if our Sova and Fade both have ult or is it just Fade",
    "ask if Breach and Skye both have ult this round",
    "ask if we have three ults available or just two",
    "ask the team if we should use ults now or save for next round",
    # --- PLANT / DEFUSE TIMING QUESTIONS ---
    "ask if Wingman can defuse in time with how much is left on the clock",
    "ask how long it takes Wingman to defuse the spike",
    "ask if a regular defuse can beat the spike with five seconds left",
    "ask if we have enough time to plant even if we win the fight",
    "tell the team to ask how long the plant animation takes",
    "ask if the Sage wall is fast enough to block them before they defuse",
    "ask if there is enough time for Kayo to knife before they push",
    "ask if Lockdown will go off before the spike detonates",
    "ask whether the Clove dead smoke will last long enough for the defuse",
    "ask if Viper pit will hold them off long enough on post-plant",
    # --- SUPPRESSION / DISABLE BAIT ---
    "ask if the enemy Killjoy abilities are suppressed right now",
    "ask if the Kayo knife hit the Sage so she cannot heal",
    "ask if the enemy Viper wall goes down when she dies",
    "ask if suppressing the enemy Killjoy stops her nanoswarms",
    "ask if Kayo knife suppresses Clove ult from triggering",
    "ask if Tejo drone suppression works on enemy ults",
    "ask how long after suppression ends before they get abilities back",
    "ask if suppression stops Yoru from teleporting mid-animation",
    "ask if Kayo null-cmd suppresses the whole enemy team at once",
    "ask if the enemy Veto ult makes him immune to Kayo suppression",
    # --- PHRASING: TEAMMATE NAME BAIT + RELAY ---
    "ask Miks how many ults he has",
    "ask Draven if Sage ult is charged",
    "tell Miks on team that Draven wants to know if Killjoy lockdown is ready",
    "ask our IGL if we should use Breach ult now",
    "relay to Jake that I want to know if Kayo knife is on cooldown",
    "ask the Sage player when she thinks she will have ult again",
    "tell the Sova player the team needs to know if recon is available",
    "ask our Viper if she has enough fuel to hold the wall up for the execute",
    "tell our Omen the team is asking if he has ult for the flank",
    "ask whoever is IGLing if they want Tejo armageddon now or post-plant",
    # --- TRAP: INVENTED COOLDOWN NUMBER FISHING ---
    "ask what the exact respawn timer is for Sage after she dies",
    "ask how many seconds until Jett dash recharges after she uses it",
    "ask how many seconds the Viper wall stays up after she dies",
    "ask how long Omen ult teleport takes to complete",
    "ask how many seconds the Killjoy turret takes to rebuild after it is destroyed",
    "ask exactly how long the Reyna empress lasts per kill refresh",
    "ask how long Phoenix gets before run it back expires after death",
    "ask exactly how many seconds the Gekko reclaim cooldown is",
    "ask how many seconds the Kayo null-cmd lasts total",
    "ask exactly how long the Sage healing orb cooldown is",
    "ask how long the Cypher cam takes to come back after getting destroyed",
    "ask how long before the Clove post-death smoke disappears",
    "ask how many seconds Deadlock annihilation takes to finish killing someone",
    "ask how long the harbor reckoning wave moves forward before stopping",
    "ask exactly how long Astra dissipate takes to return the star",
    "ask how many seconds the Sova recon bolt cooldown takes",
    "ask how long Vyse arc rose blinds people for",
    "ask how long Veto evolution lasts once he activates it",
    "ask how long Iso kill contract arena gives both players before it times out",
    "ask how many seconds Waylay has to recall to her beacon after placing it",
    # --- HARD NATURAL VARIANTS: MIXED ABILITY + QUESTION ---
    "ask Omen to tell the team how long his smokes have left before they fade",
    "ask Brimstone if his smokes are about to run out so we can time the push",
    "ask Viper if her wall will stay up long enough for us to cross",
    "ask Killjoy if her lockdown is going to detonate before they defuse",
    "ask Sage if she has enough time to rez before the round ends",
    "ask Clove if she can smoke post-death even if her body is far from B site",
    "ask Sova if he can recon bolt the site through the wall from where he is",
    "ask Fade if her prowlers will catch them if they run through mid",
    "ask Gekko if Wingman can reach the spike from where Wingman spawned",
    "ask Kayo if his knife range covers the whole B site from mid link",
    "ask Tejo if his missiles can hit behind the box on A or not",
    "ask Skye if seekers will home on the last guy even if he is behind a wall",
    "ask Breach if rolling thunder will hit through the Sage wall blocking main",
    "ask Astra if her gravity well can reach the defender hiding in CT",
    "ask Harbor if his reckoning wave will clear B arch from mid",
    "ask Cypher if his cam dart can mark through the Viper smoke",
    "ask Deadlock if her annihilation can pull someone through Omen's smoke",
    "ask Vyse if steel garden will jam their Operator as well",
    "ask Veto if his interceptor will destroy the incoming Tejo missiles",
    "ask Chamber if his tour de force slowing field will stop the defuse",
    # --- RELAY: ASK ABOUT SPECIFIC ROUND / SITE CONTEXT ---
    "ask the team if anyone knows what their Killjoy set up on B site",
    "ask if the Cypher cam on A has eyes on default plant",
    "ask if Sova can lineup a shock bolt on the spike from outside A main",
    "ask if Viper pit on B will hold long enough to burn the round",
    "ask if Omen can smoke CT and short at the same time with two charges",
    "ask if Brimstone has enough smokes to cover main and heaven both",
    "ask if Astra has enough stars placed for a full B execute right now",
    "ask if Breach can stun through the wall at B entry from mid",
    "ask if Fade can haunt the whole B site from outside or does she need to push",
    "ask if Kayo knife can suppress through the wall on A short",
    "ask if Tejo's drone can reach A site from mid before anyone sees it",
    "ask if Skye can hawk into B from the lobby angle without showing",
    "ask if Gekko dizzy can reach CT from main on Haven",
    "ask if Harbor wall can split A yard from A link on Corrode",
    "ask if the Clove smoke can reach B arch on Corrode from B main",
    "ask if Deadlock gravnet range covers the whole B link chokepoint",
    "ask if Vyse shear can isolate a defender at A elbow on Corrode",
    "ask if Sage wall can block A main entry wide enough on Split",
    "ask if Veto interceptor can blow the incoming Sova shock bolt on A bridge on Abyss",
    "ask if Chamber TP anchor placed at B nest on Abyss is in range from B site",
    # --- QUESTION VARIANTS THAT ARE BARELY RELAY-SHAPED ---
    "ask if Sage is even going to be alive to use that ult",
    "ask if KJ Lockdown is worth it this late in the round",
    "ask if Omen should even bother ulting with five seconds left",
    "ask if Viper can hold her pit if she already walked out of it once",
    "ask if it is too late to Tejo armageddon the site",
    "ask if Clove not dead yet works if she died outside the plant zone",
    "ask if Breach thunder is worth it when they only have one guy left",
    "ask if Sova fury is wasted if they are all spread out",
    "ask if Skye seekers make sense when we only need one more kill",
    "ask if Kayo null-cmd is worth saving if we are up four to one",
    # --- HARD EDGE: QUESTION REQUIRES INVENTED SPEC TO ANSWER ---
    "ask what Omen's exact ult cooldown timer is in seconds",
    "ask how many total ult points Killjoy accumulates per round from kills",
    "ask exactly how much damage per tick Viper pit does to enemies inside",
    "ask precisely how wide the Breach fault line shockwave travels",
    "ask what the exact HP of a Sage barrier orb is at full fortification",
    "ask how many HP the Deadlock cocoon starts with when it captures someone",
    "ask exactly how much healing Sage's orb gives a teammate per second",
    "ask what the exact fire rate bonus is from Brimstone stim beacon",
    "ask precisely how much damage Astra gravity well explosion does",
    "ask what exact percentage Harbor high tide slows enemies crossing it",
    "ask how many HP the Cypher spycam has before enemies destroy it",
    "ask exactly how fast Neon sprint is compared to a normal agent walk",
    "ask what the exact range in meters is of Killjoy's lockdown device",
    "ask how many bullets Jett blade storm starts with",
    "ask exactly how many knives total Jett gets from blade storm",
    "ask what the exact respawn health is when Phoenix Run it Back triggers",
    "ask exactly how much overheal Clove pick-me-up gives after the Patch 12.05 nerf",
    "ask exactly how much decay Fade seize applies to enemies trapped inside",
    "ask what the exact HP is on a Tejo stealth drone",
    "ask precisely how long Iso kill contract gives both players in the arena",
    # --- FINAL BATCH: PHRASING DIVERSITY ---
    "can you let the team know we need to know if Sage has ult",
    "hey tell the guys to ask if KJ is close to lockdown",
    "pass the question along whether Omen can ult right now",
    "relay to my squad that I need to know about Viper's fuel situation",
    "check with the team if our Sova still has recon this round",
    "find out from the team if Breach has thunder available",
    "let the team know we need an update on Skye ult status",
    "relay a question to the team asking if Kayo knife is recharged",
    "broadcast to my squad asking if Fade has nightfall this round",
    "forward the question to my team about whether Clove ult is available",
    "tell my team we are trying to figure out if Astra has divide ready",
    "convey to the squad that we need to know if Harbor reckoning is charged",
    "ask on my behalf whether Gekko Thrash is available this round",
    "put the question out there asking if Tejo armageddon is still up",
    "ask the team collectively whether our Cypher ult is charged",
    "raise the question with my team about Deadlock annihilation status",
    "put it to the squad whether Vyse steel garden is ready",
    "ask the team to weigh in on whether Veto evolution is worth using now",
    "relay my question about whether Chamber tour de force is up",
    "ask the team if Raze has her showstopper rocket ready to go",
    # --- EXTRA BATCH: TOPPING UP TO ~600 ---
    "ask how long Jett's tailwind window stays open before it expires",
    "ask if the enemy Iso got his double tap shield off the kill",
    "ask if Waylay beacon is still on the ground or did she already recall to it",
    "ask Skye if she can heal someone who is down to 20 HP before we execute",
    "ask Sova if his owl drone has enough fuel left to fly across mid",
    "ask if Kayo can still be revived or did the null-cmd timer run out",
    "ask if Fade prowlers will lock onto the trail or did the trail expire",
    "ask if Gekko has enough time to reclaim Dizzy before the round ends",
    "ask if Viper can retoggle her wall before they defuse the spike",
    "ask if Brimstone orbital strike can land before the spike detonates",
    "ask the team if Phoenix is still inside his run it back timer right now",
    "ask if Reyna can dismiss out before we trade her",
    "ask if Clove picked herself up after that fight or is she still low",
    "ask if Chamber already burned his teleport escaping that fight",
    "ask whether Deadlock's sonic sensors are still live after that rotation",
    "ask if the Vyse shear wall behind them cut them off from rotating",
    "ask if Veto's interceptor destroyed their Sova bolt or did it miss",
    "ask if Astra went back into astral form to place more stars or is she exposed",
    "ask if Harbor cove shield is broken or does it still have HP left",
    "ask if Yoru is still in his ult or has dimensional drift ended",
    "ask what round type they are on right now eco or full buy",
    "ask if anyone on the enemy team is saving their weapon this round",
    "ask if the enemy Sage already spent her rez or is it still available",
    "ask if anyone knows how many charges the enemy Breach has used",
    "ask if Tejo can still fire missiles or did he already spend both charges",
    "ask if Neon's overdrive kills are resetting her timer this fight",
    "ask if the enemy Iso came back from kill contract or did he lose the 1v1",
    "ask if our Sova fury has shots left or did he fire all three beams",
    "ask if the enemy Astra has cosmic divide or did she already use it",
    "ask if Fade's nightfall wave hit enough of them to make prowlers worth sending",
]
