"""Vocab pack: stress_hallucination_bait

Domain: Vague directives that tempt the 3B LLM to invent specifics it was
not given.  Correct relay output MUST preserve the vagueness — never inventing
ability names, locations, counts, cooldown numbers, damage values, or ownership
facts that were absent from the streamer's input.

Hard sub-categories tested
---------------------------
1.  "Use your util" / "use your abilities" — correct: relay the vague request,
    do NOT name Tailwind, Cloudburst, Recon Bolt, etc.
2.  "Cage it" / "smoke it" / "wall it" — correct: relay the generic verb,
    do NOT specify which smoke (Dark Cover vs Sky Smoke vs Nebula), which agent,
    or fabricate a location not mentioned.
3.  "Deal with that" / "handle it" / "do something" — extreme vagueness; relay
    as-is with zero invented specifics.
4.  Agent-addressed but ability-unspecified — "Jett do something", "Cypher get
    info" — do NOT invent which ability or where.
5.  Ownership ambiguity — "their util", "our smokes", "his thing" — do NOT
    flip attribution or assign an agent.
6.  Action described without a target location — "flash somewhere", "throw a
    molly", "pop your ult" — do NOT add a map location.
7.  No-count directives — "there's someone over there", "there's guys" — do NOT
    invent a number.
8.  Compound vague — two vague clauses chained; tempts double-hallucination.
9.  Economy-vague — "do something about their econ", "buy something useful" —
    do NOT invent a round type, credit number, or weapon name.
10. Temporal-vague — "use it when you're ready", "fire whenever" — do NOT
    invent a countdown.

Kind: relay (~600 cases)
"""

ITEMS = [
    # =========================================================
    # CATEGORY 1: "USE YOUR UTIL / USE YOUR ABILITIES"
    # (no specific ability named — do NOT hallucinate one)
    # =========================================================
    "tell them to use their util on site",
    "let my team know to use their abilities before we go in",
    "relay to my squad: everyone use your stuff now",
    "tell them pop your util right here",
    "tell my teammates to use their abilities when they push",
    "let them know to save util for this",
    "relay: everyone burn your util before the timer runs out",
    "tell my team use your abilities, don't hold them",
    "let my squad know don't save util this round, use everything",
    "tell them use your things and go",
    "relay to my teammates: we need everyone's stuff out now",
    "tell them throw your util into the site",
    "let my team know use your abilities to clear it",
    "tell my squad pop everything you have right now",
    "relay: use your kit, we're committing",
    "tell them don't hold onto your util anymore",
    "let my teammates know burn your abilities this round",
    "tell them everyone dump your util on that site",
    "relay to the squad: util out, then push",
    "tell my team we need util before we go in, everyone use your stuff",
    "let them know use it all, don't save anything",
    "tell them throw everything you have at them",
    "relay: everyone use your abilities on their position",
    "tell my squad it's time to use your stuff, go",
    "let my team know pop your util and take the site",
    "tell them use all your abilities before the round ends",
    "relay to the team: everyone has their util, use it",
    "tell my teammates stop holding your util, pop it",
    "let them know use everything you have to clear the site",
    "tell my squad you have abilities, use them, go",

    # =========================================================
    # CATEGORY 2: "CAGE IT / SMOKE IT / WALL IT"
    # (generic verb, no agent or sub-location named)
    # =========================================================
    "tell them to smoke it",
    "relay: someone smoke that angle",
    "tell my team smoke the entrance",
    "let them know we need a smoke right there",
    "tell my squad cage it off",
    "relay to my team: cage that doorway",
    "tell them wall it",
    "let my teammates know wall off that corner",
    "tell my team smoke it up before we push",
    "relay: drop a smoke and then go",
    "tell them someone wall them off",
    "let my squad know put a smoke down over there",
    "tell them cage the area so they can't see us",
    "relay: smoke that spot and we're clear",
    "tell my team just wall it and we execute",
    "let my teammates know we need a cage on that",
    "tell them put up a wall before we move",
    "relay to my squad: cage off that angle they keep holding",
    "tell them smoke it so we can plant",
    "let my team know wall that entry and we're good",
    "tell them flash it then we smoke",
    "relay: smoke it, then I'm going in",
    "tell my team someone needs to smoke that",
    "let them know cage it before we push through",
    "tell my squad wall off their approach",
    "relay to my teammates: smoke the lane and we go",
    "tell them just put something up to block vision there",
    "let my team know block their sightline somehow",
    "tell my squad cover that angle with something",
    "relay: someone put vision block on that and we go",

    # =========================================================
    # CATEGORY 3: "DEAL WITH THAT / HANDLE IT / DO SOMETHING"
    # (maximally vague directives — relay faithfully)
    # =========================================================
    "tell them to deal with that",
    "relay: someone handle that",
    "tell my team do something about that",
    "let them know take care of it",
    "tell my squad sort that out",
    "relay to my team: someone fix that right now",
    "tell them figure it out",
    "let my teammates know handle that situation",
    "tell them get rid of that",
    "relay: take care of that problem over there",
    "tell my team deal with the thing on site",
    "let my squad know someone needs to handle that angle",
    "tell them do something, we can't just sit here",
    "relay to my teammates: someone deal with that threat",
    "tell them take care of whatever that is",
    "let my team know get that under control",
    "tell my squad deal with it fast",
    "relay: handle that before we push",
    "tell them someone has to do something about that",
    "let them know take it out or work around it",
    "tell my team just deal with the situation",
    "relay to the squad: handle the problem and then push",
    "tell them clear that thing before we commit",
    "let my teammates know deal with that now",
    "tell my squad handle it, we're running out of time",
    "relay: someone take that out before we go",
    "tell them do something useful for once",
    "let my team know deal with whatever is there",
    "tell them get it done",
    "relay: handle that and then we execute",

    # =========================================================
    # CATEGORY 4: AGENT-ADDRESSED, ABILITY-UNSPECIFIED
    # ("Jett do something" — do NOT invent which ability)
    # =========================================================
    "tell Jett to do something",
    "relay to my team: tell Jett to use her stuff",
    "tell my Jett to do her thing",
    "let my team know the Reyna needs to pop something",
    "tell Sage to do something useful",
    "relay: tell Killjoy to set up",
    "tell the Sova to do some recon",
    "let my teammates know Viper should use something to help us",
    "tell Omen to do his thing",
    "relay to the team: tell Cypher to get some info",
    "tell the Raze to do something aggressive",
    "let my squad know tell Skye to send something in",
    "tell my Breach to use something before we push",
    "relay: Killjoy set something up already",
    "tell the Fade to do her thing",
    "let them know Brimstone needs to use something",
    "tell my Neon to go do something",
    "relay to my squad: tell Chamber to set up",
    "tell the Gekko to send something in to help",
    "let my team know Deadlock should do something to slow them",
    "tell Astra to use something to support the push",
    "relay: tell the Iso to do his thing",
    "tell my Reyna to use her stuff before she goes in",
    "let them know Harbor should do something to help us plant",
    "tell Vyse to set something up in there",
    "relay to my teammates: tell Phoenix to use something first",
    "tell my Yoru to do his trick thing",
    "let my squad know Tejo should use something to support us",
    "tell the Clove to smoke or whatever",
    "relay: Veto should do something to help",

    # =========================================================
    # CATEGORY 5: OWNERSHIP-AMBIGUOUS
    # ("their util", "our stuff", "his thing" — do NOT flip or assign)
    # =========================================================
    "tell them their util is wasted if they don't use it",
    "relay: tell them to counter whatever that is",
    "tell my team watch out for their thing",
    "let them know their abilities will tear us apart if we don't go now",
    "tell my squad watch out for their util on the site",
    "relay to my team: their smokes will fade, wait for it",
    "tell them their stuff is almost gone, push now",
    "let my teammates know their abilities are on cooldown probably",
    "tell my team our util is ready, their util might not be",
    "relay: their thing is blocking us, someone deal with it",
    "tell them we still have our abilities but theirs are used up",
    "let my squad know their ability won't last forever",
    "tell them our stuff is fresh but their stuff is spent",
    "relay to my team: they used their thing, we're clear",
    "tell them his ability got wasted, push now",
    "let my teammates know their smokes are probably done",
    "tell my squad watch his thing, don't walk into it",
    "relay: their util is hurting us over there",
    "tell them don't fight through their stuff, go around",
    "let my team know their ability expires soon so just wait",
    "tell them our smokes cover that angle but theirs cover the other one",
    "relay to the squad: his thing just went off, now we go",
    "tell them their kit is probably burnt by now",
    "let my teammates know his ability just fired, push through",
    "tell my team her stuff will wear off in a second",

    # =========================================================
    # CATEGORY 6: ACTION WITHOUT TARGET LOCATION
    # ("flash somewhere" — do NOT add a map name)
    # =========================================================
    "tell them to throw a flash",
    "relay: someone pop a flash",
    "tell my team throw a molly somewhere",
    "let them know drop a smoke",
    "tell my squad pop your ult",
    "relay to my team: someone throw a grenade",
    "tell them flash going in",
    "let my teammates know throw a flash first",
    "tell my team someone drop a nade",
    "relay: pop a molly to slow them down",
    "tell them throw something at them",
    "let my squad know drop a flash and we go",
    "tell them throw a smoke out there",
    "relay to my teammates: someone fire a shot to see if they react",
    "tell them I'm going to flash, everyone push after",
    "let my team know throw out your util and then we take the fight",
    "tell my squad someone throw down a slow",
    "relay: pop a stun and go",
    "tell them throw a concuss and we're going in",
    "let my teammates know someone drop a stun on that",
    "tell my team shoot something to bait their reaction",
    "relay to the squad: pop a flash and swing",
    "tell them throw a nade and follow up",
    "let my squad know drop something on their position and push",
    "tell them just pop your ult and go for it",
    "relay: throw some util and see what happens",
    "tell my team someone fire something to poke them",
    "let my teammates know throw a slow or something at them",
    "tell my squad pop a stun and I'll swing on it",
    "relay to my team: toss something in first then we follow",

    # =========================================================
    # CATEGORY 7: NO-COUNT DIRECTIVES
    # ("there's someone" — do NOT invent a number)
    # =========================================================
    "tell them there's someone over there",
    "relay: let my team know there are guys on site",
    "tell my squad there's people in the area",
    "let them know someone is lurking",
    "tell my team there's enemies around",
    "relay to my teammates: there are players watching that angle",
    "tell them I hear someone over there",
    "let my squad know there's a person somewhere here",
    "tell my team there are people in here",
    "relay: someone is definitely holding that",
    "tell them I heard movement over there",
    "let my teammates know there's definitely someone around the corner",
    "tell my team there are people nearby",
    "relay to my squad: I heard footsteps, someone is close",
    "tell them there are enemies in this area",
    "let my team know someone is hiding somewhere in here",
    "tell my squad there are people on that side",
    "relay: I hear them but I can't see them, there's someone here",
    "tell them someone is definitely still on site",
    "let my teammates know there are enemies lurking around",
    "tell my team there's people waiting for us",
    "relay to the squad: I hear someone but I don't know exactly where",
    "tell them someone is holding the angle",
    "let my squad know there's at least one person watching that",
    "tell them there are enemies, just be careful going in",
    "relay: there are people in the area, be aware",
    "tell my team I heard people around here",
    "let my teammates know someone is somewhere in there",
    "tell my squad there are players nearby, watch out",
    "relay to my team: someone is here, stay sharp",

    # =========================================================
    # CATEGORY 8: COMPOUND VAGUE
    # (two vague clauses chained — do NOT double-hallucinate)
    # =========================================================
    "tell them use your util and deal with that angle",
    "relay: use something and then push",
    "tell my team smoke it and then handle whatever is over there",
    "let them know flash first and then deal with the problem",
    "tell my squad use your stuff and then sort that out",
    "relay to my team: do something about that and then go",
    "tell them pop your util on whatever that is and push through",
    "let my teammates know use your ability and then take care of that",
    "tell my team someone use their thing and someone handle that",
    "relay: someone pop something and someone else deal with the enemy",
    "tell them flash it and then go deal with what's over there",
    "let my squad know smoke it and then handle the angle",
    "tell them use your kit and take care of whatever is lurking",
    "relay to my teammates: pop your stuff and deal with what's in there",
    "tell my team smoke and go, and someone handle the thing on the right",
    "relay: throw something in, then go deal with whatever is there",
    "tell them flash and deal with the lurker",
    "let my squad know pop your ability and then deal with the problem",
    "tell my team throw something and then go handle whatever that is",
    "relay to the team: use it and deal with that, we're low on time",
    "tell them use your abilities and handle that corner",
    "let my teammates know do something useful and then push wherever you can",
    "tell my squad pop something and go somewhere useful",
    "relay: flash somewhere and then handle the issue over there",
    "tell them use your stuff before it expires and deal with whatever that is",
    "relay to my squad: someone use something and someone take care of that",
    "tell my team smoke whatever you need to smoke and handle whatever is there",
    "let them know use your ability on that, then go handle the next problem",
    "tell my squad do your thing and take care of whatever they have going",
    "relay: use everything and deal with the whole situation",

    # =========================================================
    # CATEGORY 9: ECONOMY-VAGUE
    # (no credit number, round type, or weapon named)
    # =========================================================
    "tell my team to buy something useful this round",
    "relay: tell them to spend their money wisely",
    "tell my squad buy something good",
    "let them know buy whatever you can afford",
    "tell my team get a decent loadout",
    "relay to my teammates: spend your credits on something that works",
    "tell them buy something that helps the team",
    "let my squad know get something useful with your money",
    "tell my team don't waste your credits on something bad",
    "relay: everyone buy something so we can fight",
    "tell them get a gun and some abilities",
    "let my teammates know buy what you can and let's go",
    "tell my squad spend smart this round",
    "relay to my team: buy something, anything",
    "tell them don't eco if you can help it",
    "let my team know just get something half-decent",
    "tell my squad buy something and we'll figure out the rest",
    "relay: spend your credits on gear this round",
    "tell them buy something that can win a fight",
    "let my teammates know if you have money, spend it on something good",
    "tell my team save or spend, just decide and tell me",
    "relay to the squad: buy whatever helps most for the round",
    "tell them get a weapon and some util, doesn't have to be perfect",
    "let my squad know buy according to what you need",
    "tell them get something this round, we can't run in with nothing",
    "relay: pick up something useful with whatever credits you have",
    "tell my team everyone get a decent buy",
    "let my teammates know spend on your abilities too, not just the gun",
    "tell my squad get a rifle or something close to it if you can",
    "relay to my team: buy whatever you have to and let's get this round",

    # =========================================================
    # CATEGORY 10: TEMPORAL-VAGUE
    # ("whenever you feel like it" — do NOT invent a countdown)
    # =========================================================
    "tell them use it whenever you feel ready",
    "relay: tell my team use their util when the time is right",
    "tell my squad pop it at a good moment",
    "let them know use your ability when it makes sense",
    "tell my team fire it off when you see your chance",
    "relay to my teammates: use it when the moment is right",
    "tell them throw it when you feel good about it",
    "let my squad know use your stuff at the right time",
    "tell my team pop your ability whenever you're ready",
    "relay: use it when they commit, not before",
    "tell them fire it when they make a move",
    "let my teammates know use it when they push, not randomly",
    "tell my team save it for the right time",
    "relay to my squad: use your thing when the opportunity comes",
    "tell them pop it the moment they peek",
    "let my team know use it when they move",
    "tell my squad pop your ability when you see it's useful",
    "relay: fire it at a smart time, not just whenever",
    "tell them use your util whenever the team needs it",
    "let my teammates know pop it when the window opens",
    "tell my team use it at the moment where it actually matters",
    "relay to the team: pop your thing when they do something, not before",
    "tell them hold it until the right play shows up",
    "let my squad know don't pop your ult too early, wait",
    "tell them use your abilities when you know it'll help",
    "relay: pop it whenever makes sense for the situation",
    "tell my team your ult is ready whenever you want to go for it",
    "let my teammates know use your util after they show themselves",
    "tell my squad pop your ability when it actually matters",
    "relay to my team: use it at the moment you think is best",

    # =========================================================
    # CATEGORY 11: MIXED-VAGUE — LOCATION NAMED BUT ACTION VAGUE
    # (location is named but the action is deliberately vague)
    # =========================================================
    "tell them to do something on A site",
    "relay: deal with whatever is on B",
    "tell my team handle the mid situation",
    "let them know take care of whatever is at CT",
    "tell my squad do something about A main",
    "relay to my team: handle what's happening at B lobby",
    "tell them figure out what to do about A long",
    "let my teammates know deal with the situation at mid link",
    "tell my team do something about what's at B main",
    "relay: handle whatever that is at CT stairs",
    "tell them deal with B site somehow",
    "let my squad know sort out A short",
    "tell my team deal with the issue at the back of site",
    "relay to my teammates: take care of whatever is at heaven",
    "tell them handle the stuff happening at B entry",
    "let my team know do something about the defenders on A",
    "tell my squad deal with whatever is at that corner",
    "relay: handle the problem at the end of the corridor",
    "tell them take care of whatever is holding that lane",
    "let my teammates know do something to clear the way to site",
    "tell my team there's a problem at the chokepoint, handle it",
    "relay to the squad: deal with whatever is pushing mid",
    "tell them take care of things on B before we push",
    "let my squad know handle what's going on at A",
    "tell them do something useful at B lobby",
    "relay: deal with the issue at the site entrance",
    "tell my team handle whatever the defender is doing at back site",
    "let my teammates know someone deal with the lurker in the hall",
    "tell my squad figure out the A side situation",
    "relay to my team: handle everything over at B and we take A",

    # =========================================================
    # CATEGORY 12: ABILITY SLOT REFERENCED BUT NOT NAMED
    # ("use your E", "pop your ult", "throw your Q" — no ability named)
    # =========================================================
    "tell them use your E ability",
    "relay: tell my team pop your ult right now",
    "tell my squad throw your Q out there",
    "let them know use your signature ability",
    "tell my team everyone pop your ultimates",
    "relay to my teammates: use your E for that",
    "tell them use your basic abilities first before your ult",
    "let my squad know pop your ult, it's a good time",
    "tell my team throw your C ability in there",
    "relay: use your E on that",
    "tell them pop your Q and then we go",
    "let my teammates know everyone use your signature right now",
    "tell my team someone needs to use their ultimate here",
    "relay to my squad: pop your X ability on them",
    "tell them use the E ability to help us push",
    "let my team know pop ults, everyone who has them",
    "tell my squad use your basic abilities before your ult",
    "relay: throw your Q at them and then commit",
    "tell them use your C and then follow up",
    "let my teammates know pop your ult if you have it charged",
    "tell my team use your Q, it's what we need right now",
    "relay to the team: pop ults and go",
    "tell them everyone activate your ultimates now",
    "let my squad know use your signature, it's available",
    "tell them your ult is ready, use it",
    "relay: pop your E and we'll cover you",
    "tell my team use your Q ability on them",
    "let my teammates know pop your ult now before the round ends",
    "tell my squad fire your C at that position",
    "relay to my team: use your signature ability, don't waste it",

    # =========================================================
    # CATEGORY 13: ROLE-DIRECTED BUT NOT ABILITY-SPECIFIC
    # ("someone entry", "controller do something" — no specifics)
    # =========================================================
    "tell them someone needs to entry",
    "relay: duelist go in first",
    "tell my team the controller needs to do something",
    "let them know initiator use something to help us push",
    "tell my squad someone entry frag",
    "relay to my team: controller set up your stuff",
    "tell them whoever is the sentinel needs to watch the flank",
    "let my teammates know our initiator should do something before we go in",
    "tell my team the duelist should use their thing",
    "relay: controller do your job and smoke something",
    "tell them sentinel watch the back",
    "let my squad know someone needs to go in first and create space",
    "tell my team entry, anyone, just go",
    "relay to my teammates: controller use something for the push",
    "tell them our initiator needs to pop something before we enter",
    "let my team know whoever is entry, go now",
    "tell my squad the duelist should use their movement ability",
    "relay: our sentinel needs to set up before we enter",
    "tell them controller get ready to support",
    "let my teammates know we need the initiator to do their thing first",
    "tell my team whoever is supposed to entry, do it now",
    "relay to the squad: sentinel lock down the flank",
    "tell them controller block their vision somehow",
    "let my squad know initiator go do something to create a flash opening",
    "tell them our duelist should take the fight, that's their job",
    "relay: entry player go in and make something happen",
    "tell my team the support player needs to do something",
    "let my teammates know entry fragger take the space",
    "tell my squad the controller needs to act before we push",
    "relay to my team: initiator do something and we'll follow you in",

    # =========================================================
    # CATEGORY 14: SPIKE / PLANT VAGUE
    # (plant or defuse directive without location or detail)
    # =========================================================
    "tell them someone plant the spike",
    "relay: let my team know plant it somewhere",
    "tell my squad plant somewhere safe",
    "let them know plant the thing",
    "tell my team just plant it",
    "relay to my teammates: plant when you get the chance",
    "tell them plant the spike wherever works",
    "let my squad know plant it fast",
    "tell my team someone has spike, plant it",
    "relay: just plant, don't overthink it",
    "tell them plant somewhere and then defend",
    "let my teammates know whoever has spike, plant it now",
    "tell my team plant the bomb and hold it",
    "relay to my squad: plant somewhere and we hold",
    "tell them defuse it",
    "let my team know someone go defuse",
    "tell my squad defuse when you can",
    "relay: whoever is close, defuse it",
    "tell them plant safely and we'll protect you",
    "let my teammates know plant it and we play for time",
    "tell my team someone just plant the spike, anywhere",
    "relay to the team: plant it and hold what you have",
    "tell them plant on one of the sites and we take it from there",
    "let my squad know just get the spike down",
    "tell them someone needs to plant, hurry up",
    "relay: plant and then we figure out positions",
    "tell my team get the spike planted somewhere this round",
    "let my teammates know spike needs to go down now",
    "tell my squad plant wherever is safe and call it",
    "relay to my team: plant the thing and let's hold",

    # =========================================================
    # CATEGORY 15: VAGUE CALLS ABOUT ENEMY BEHAVIOR
    # (no count, no ability, no location)
    # =========================================================
    "tell my team they're doing something weird",
    "relay: let them know the enemies are playing strange",
    "tell my squad something feels off about their play",
    "let them know they're doing something we should watch out for",
    "tell my team something is up with their positioning",
    "relay to my teammates: they're playing different this round",
    "tell them the enemies are being suspicious",
    "let my squad know something is wrong, be careful",
    "tell my team they're setting something up",
    "relay: be careful, they're doing something odd",
    "tell them they might be faking something",
    "let my teammates know the enemy is up to something",
    "tell my team they're probably baiting us",
    "relay to my squad: be smart, they're definitely doing something",
    "tell them something is off, don't just push blindly",
    "let my team know be ready, they're doing something unusual",
    "tell my squad they seem like they're setting a trap",
    "relay: the enemies are playing in a weird way, watch out",
    "tell them don't just go in, they have something planned",
    "let my teammates know they're trying something, stay alert",
    "tell my team I have a feeling they're planning something",
    "relay to the team: they're stalling for a reason, be careful",
    "tell them play slow, they're obviously doing something specific",
    "let my squad know something is going on over there, be ready",
    "tell them they have a plan, don't walk into it",
    "relay: they're waiting for something to happen, be patient",
    "tell my team they seem to be doing a different strat this round",
    "let my teammates know something about their play this round is different",
    "tell my squad the enemies know something we don't, play careful",
    "relay to my team: they're definitely doing something, don't just blindly go",

    # =========================================================
    # CATEGORY 16: AGGRESSIVE / FLANK VAGUE
    # (no specific route or ability)
    # =========================================================
    "tell them someone flank",
    "relay: tell my team someone go around",
    "tell my squad send someone the other way",
    "let them know we need a flank somewhere",
    "tell my team someone sneak around the back",
    "relay to my teammates: one person go flank while we push",
    "tell them someone needs to lurk",
    "let my squad know one person go around and hit them from the side",
    "tell my team lurk somewhere and make something happen",
    "relay: someone sneak through and get behind them",
    "tell them if someone can flank do it",
    "let my teammates know we need someone to go the long way",
    "tell my team send a lurker somewhere",
    "relay to my squad: one person take a different route",
    "tell them someone go through the back way",
    "let my team know one person go flank, the rest push with me",
    "tell my squad go around them somehow",
    "relay: one of us needs to get behind their team",
    "tell them sneak around their back",
    "let my teammates know if someone can get behind them that would help",
    "tell my team go the alternate route and hit their flank",
    "relay to the team: someone lurk while we fake this site",
    "tell them one person peel off and go the other way",
    "let my squad know get around them some way",
    "tell them we need someone to swing from the other side",
    "relay: send someone to flank their team somehow",
    "tell my team one person go wide and hit them from the side",
    "let my teammates know lurk somewhere useful",
    "tell my squad someone go behind the defenders",
    "relay to my team: send the lurker around before we commit",

    # =========================================================
    # CATEGORY 17: RETAKE VAGUE
    # (no specific agent, ability, or sub-location)
    # =========================================================
    "tell them we need to retake",
    "relay: let my team know retake the site",
    "tell my squad let's retake together",
    "let them know we have to go back and take it",
    "tell my team we're retaking, everyone regroup",
    "relay to my teammates: we're taking the site back",
    "tell them retake, go back in",
    "let my squad know let's push back and retake",
    "tell my team everyone retake now",
    "relay: retake together, don't go one at a time",
    "tell them we can retake if we go at the same time",
    "let my teammates know we need to take back the site",
    "tell my team use whatever you have for the retake",
    "relay to my squad: retake with your util if you have it",
    "tell them use everything for the retake",
    "let my team know go in together on the retake",
    "tell my squad retake fast, spike is ticking",
    "relay: use your abilities on the retake",
    "tell them we retake together or not at all",
    "let my teammates know go for the retake now",
    "tell my team if we have abilities use them for the retake",
    "relay to the team: retake through the best route you know",
    "tell them I need backup on the retake",
    "let my squad know retake, don't let them plant comfortably",
    "tell them go back in and retake that site",
    "relay: everyone push back in for the retake",
    "tell my team use your util on the retake, now is the time",
    "let my teammates know retake as a group",
    "tell my squad everyone commit to the retake",
    "relay to my team: retake, use what you have, go",

    # =========================================================
    # CATEGORY 18: WILDCARD / MAXIMUM STRESS
    # (hardest hallucination-bait cases — ultra-vague, edge-case phrasing)
    # =========================================================
    "tell them to just do the thing",
    "relay: tell my team do the plan",
    "tell my squad execute whatever we talked about",
    "let them know just do it",
    "tell my team play the round properly",
    "relay to my teammates: do the right thing",
    "tell them make it work somehow",
    "let my squad know play smart and handle it",
    "tell my team do whatever you think is best",
    "relay: tell them just go for it",
    "tell them do the obvious play",
    "let my teammates know make a smart decision",
    "tell my team someone do something useful",
    "relay to my squad: just handle it the way you know how",
    "tell them play the way we practiced",
    "let my team know execute what we know works",
    "tell my squad run the play we always run",
    "relay: do the strat, you know it",
    "tell them work together and make something happen",
    "let my teammates know be smart about it",
    "tell my team make a play",
    "relay to the team: take control of the situation",
    "tell them someone step up and do something",
    "let my squad know take control of the round",
    "tell them make the smart play",
    "relay: tell my team go do the thing that makes sense",
    "tell them collectively figure out what to do",
    "let my teammates know someone has to step up here",
    "tell my squad play the correct way",
    "relay to my team: just do whatever works and do it now",
    "tell them if you know what to do, do it",
    "let my team know handle the round however you can",
    "tell my squad make it happen",
    "relay: tell my team take the right fight",
    "tell them use your game sense and act on it",
    "let my teammates know play what's in front of you",
    "tell my team take control of whatever situation you're in",
    "relay to the squad: be decisive and act",
    "tell them think for two seconds and then do it",
    "let my squad know don't overthink it, just play",
    "tell my team trust your read and do something",
    "relay: tell them stop waiting and make a play",
    "tell them just make a decision and commit to it",
    "let my teammates know stop overthinking and just go for it",
    "tell my team everyone just play and do something useful",
    "relay to my team: take some action right now",
    "tell them collectively decide and do it",
    "let my squad know trust each other and make a play",
    "tell my team everyone do their part",
    "relay: tell them do your role and make it count",
    "tell them whatever you're thinking right now, do it",
    "let my teammates know make the play that wins the round",
    "tell my squad go handle it",
    "relay to my team: just handle whatever is in front of you right now",
    "tell them go do your job",
    "let my team know do what you're supposed to do",
    "tell my squad do your thing and make it work",
    "relay: go do what you need to do",
    "tell them just go play",

    # =========================================================
    # CATEGORY 19: SUPPRESS / COUNTER VAGUE
    # (enemy has a thing — do NOT name the specific ability)
    # =========================================================
    "tell my team counter whatever they're doing",
    "relay: tell them to play around their ability",
    "tell my squad don't walk into their thing",
    "let them know play around whatever they have set up",
    "tell my team counter their setup somehow",
    "relay to my teammates: avoid their thing and push another way",
    "tell them don't run into their ability",
    "let my squad know play around whatever the sentinel put down",
    "tell my team stay away from their trap or whatever that is",
    "relay: tell them to deal with whatever the enemy set up on site",
    "tell them counter their abilities before we push",
    "let my teammates know watch out for whatever they planted",
    "tell my team route around their stuff",
    "relay to my squad: someone handle their setup before we go in",
    "tell them figure out how to get past their ability",
    "let my team know destroy whatever they put down",
    "tell my squad shoot out their thing before we push",
    "relay: take out their ability and then move in",
    "tell them neutralize their setup first",
    "let my teammates know clear their gadget before we enter",

    # =========================================================
    # CATEGORY 20: SAVE / RETREAT VAGUE
    # (no weapon or credit amount specified)
    # =========================================================
    "tell my team save this round",
    "relay: everyone save your gun",
    "tell my squad don't die, save your weapon",
    "let them know retreat and save",
    "tell my team fall back and save your stuff",
    "relay to my teammates: if we're losing pull back and save",
    "tell them don't force it, just save",
    "let my squad know save this round and we buy next",
    "tell my team cut the round and save your loadout",
    "relay: tell them save your weapon and live",
    "tell them abort and save if we can't win",
    "let my teammates know fall back, save what you can",
    "tell my team if it's over just save",
    "relay to my squad: don't die for nothing, save your gun",
    "tell them pull out and save your loadout",
    "let my team know it's not worth dying, save",
    "tell my squad save your rifle this round",
    "relay: retreat and live, save the weapon",
    "tell them don't throw your life away, save your stuff",
    "let my teammates know save so we can full buy next round",
]
