"""Vocab pack: stress_compounds_3fact (kind=relay, ~600 items).

CHARGE: 3-fact compounds (position + ult + directive; count + ability-state +
action; ownership-mixed our/their) joined naturally. Engineered to BREAK:
  - compound zero-fact-loss (all three facts must survive rephrase intact)
  - fact-token retention per category (counts, agents, locations, abilities, ownership)
  - ownership/subject/directive/first-person inversion
  - hallucinated-specific rate
  - ecobleed (save vs force vs full vs enemy-save)
  - ask-vs-answer, opinion fidelity, identity-leak control
  - latency (dense triples pressure the 3B)

Every item is a RELAY command (streamer telling Ultron to relay to teammates).
No wake-word prefix. Double-quoted strings only; single-quotes used inside.

Distinct within this file and engineered to differ from existing packs.
"""

ITEMS = [
    # =========================================================================
    # BLOCK 1 — POSITION + ULT STATE + DIRECTIVE  (our side, agent explicit)
    # =========================================================================
    "tell my team our Jett has blade storm ready, she is anchoring A Heaven, hold entry until she confirms",
    "let my team know our Sova has hunter's fury up and his recon bolt is placed on B Long, do not peek yet",
    "tell my teammates our Killjoy has lockdown ready, she is setting it on B Site right now, push after the detain",
    "warn the team our Viper has her pit set on A Site and her ult is ready, do not enter the cloud while she holds",
    "tell my team our KAY/O has null command up and he is pushing mid with it, follow him through on his suppression pulse",
    "let them know our Raze has showstopper ready and she is boosting through B Short right now, cover her landing",
    "tell the guys our Reyna hit empress this round and she is pushing C Long, fall in behind her kills",
    "remind them our Sage has resurrection up, she is anchoring back site, do not throw before she can rez",
    "tell my team our Omen has from the shadows ready, he just stepped into A smoke and is about to ult flank",
    "let my teammates know our Skye has seekers charged, she is releasing them on B Site now, push behind the nearsight",
    "tell my team our Breach has rolling thunder ready and is charging fault line on A Main, execute after the ult lands",
    "call out that our Yoru is in dimensional drift scouting C Site right now, wait for his info before committing",
    "tell my team our Astra has cosmic divide ready and she has a gravity well on B Main, activate on my mark",
    "warn them our Clove is dead but she has ruse and she is smoking A from the grave, use the dead smokes to push",
    "tell my team our Fade has nightfall ready and she has haunt up on CT, push on her nightfall when she hits three",
    "tell the squad our Chamber has tour de force up and he is holding A Long with it, do not cross until he rotates",
    "let them know our Gekko has thrash ready and his wingman is planting B right now, cover the wingman while it plants",
    "tell my team our Deadlock has annihilation ready and she placed gravnet at B Elbow, go in after the net hits",
    "tell my teammates our Tejo has armageddon up and his salvo missiles are aimed at C Heaven right now, push after impact",
    "call out that our Neon has overdrive ready and she is already sprinting up A Main, everyone follow her rush",
    "tell my team our Vyse has steel garden ready, she is popping it on B Site now, push while their primaries are jammed",
    "let my teammates know our Harbor has reckoning up and his cove is shielded on the spike, push through the wave",
    "tell my team our Iso has kill contract ready, he is contingency-walling A Main right now, entry behind the wall",
    "warn them our Waylay has convergent paths ready and her refract beacon is on B Heaven, watch for the recall",
    "tell the guys our Veto has evolution up and he is pushing through B Link right now, do not flash him by accident",
    "tell my team our Cypher just used neural theft on that body, full enemy reveal incoming, push on the info",
    "remind the team our Phoenix has run it back active, he is pushing A with the ult timer running, trade him if he dies",
    "tell my team our Brimstone has orbital strike ready and his smokes are up on B Site, execute now before smokes fade",
    "tell my teammates our Sova's owl drone marked their Jett on A Long and his fury is ready, do not peek into it",

    # =========================================================================
    # BLOCK 2 — POSITION + ULT STATE + DIRECTIVE  (their side, agent explicit)
    # =========================================================================
    "tell my team their Jett is at A Long with blade storm up, do not take any long duels this round",
    "warn my team their Killjoy is anchoring B Site with lockdown ready, do not rush in or she detains all of us",
    "tell my teammates their Viper just set up pit on A Site and her ult is active, she can see us all inside the cloud",
    "let them know their Reyna is in empress and she is pushing mid right now, do not take the duel alone",
    "tell my team their KAY/O has null command up and is ulting B Short, hold B and do not use abilities in his radius",
    "warn the team their Raze has showstopper and is boosting toward A from B Short, smoke the landing zone",
    "tell my team their Sage has resurrection up and she is anchoring C Long, burst through before she can rez",
    "call out that their Omen is ulting to our side, shade spotted at A CT, destroy the shade immediately",
    "tell my team their Skye has three seekers out on A Site, fall back and break line of sight before they hit",
    "warn them their Breach is rolling thunder onto A Main right now, everyone back up and let it pass",
    "tell my team their Yoru is in dimensional drift somewhere in mid, assume he knows our positions",
    "let my teammates know their Astra just activated cosmic divide on A Site, she split it, go B instead",
    "tell my team their Fade ulted with nightfall and hit all five of us, we all have terror trails, send prowlers our way",
    "warn the team their Chamber is holding C Long with tour de force, do not push until we can smoke him off",
    "call out that their Gekko's thrash is piloting through mid right now, shoot it before it detonates on us",
    "tell my team their Deadlock just annihilated our Jett, break the cocoon or she is dead at the end of the wire",
    "warn them their Clove died but she still has ruse, her dead smokes will cover A Short for six more seconds",
    "tell my team their Tejo just sent his armageddon along A Main, get out of the line and wait it out",
    "tell my teammates their Neon has overdrive up and she slid onto B Site, do not dry peek the slide",
    "let them know their Vyse just popped steel garden on our whole team at B Site, drop to pistols and fall back",
    "warn my team their Harbor has reckoning ready and cove is shielded on the spike, break the shield before defusing",
    "tell my team their Iso just kill-contracted our Brimstone, four of us versus four of them while the duel runs",
    "call out that their Waylay is converging on A with her ult, everyone in the beam radius will be hindered",
    "tell my team their Cypher just ulted on our dead Reyna, full position reveal going out to their team right now",
    "warn the team their Phoenix has run it back active and he is pushing A Bath, kill him before the timer or he comes back",
    "tell my team their Brimstone has orbital strike and his three smokes are landing on B Site, hold for the smokes to clear",
    "tell my teammates their Sova has hunter's fury and just fired the first beam across mid, two charges left",
    "let them know their Veto has evolution up and he is completely immune, do not bother flashing or netting him",
    "warn my team their Fade has prowlers chasing our terror trails right now, break line of sight in the next two seconds",
    "tell my team their Astra activated gravity well on B Main with three of us clustered there, scatter immediately",

    # =========================================================================
    # BLOCK 3 — COUNT + LOCATION + ULT/ABILITY STATE  (snap-complex hybrids)
    # =========================================================================
    "tell my team two of them are at B Hookah and their Skye has a hawk ready to flash us off the site entry",
    "let my team know three enemies are holding A Long and their Jett still has her dash, do not take that fight yet",
    "warn them one enemy is at C Platform and their Chamber has tour de force up, single shot will one-tap anyone on C Long",
    "tell my teammates two at mid courtyard and their Omen has two smokes ready, they can cover any entry instantly",
    "call out that four are stacking B Site and their Killjoy has lockdown charged, do not commit all five into that site",
    "tell my team one lurker at A Sewer and their Reyna used empress already this round, she has no souls left now",
    "let them know two pushing C Garage and their Clove has not dead yet ready, burst her down before she can revive",
    "tell my team three at A Main and their Breach has rolling thunder up, expect the ult before they hit site",
    "warn my team one is hiding in B Cubby and their Cypher has a cam dart on our Jett, she is revealed to their team",
    "tell my teammates two enemies at mid library on Abyss and their Sova just fired a recon bolt toward A Tower, it will scan twice",
    "call out four at B Main on Fracture and their Tejo has armageddon ready, they are about to nuke the entry",
    "tell my team one is deep at A Secret on Abyss with an operator and their teammate has tour de force on C Long",
    "let them know two at C Short on Haven and their Astra has a gravity well placed at C Site default already",
    "warn my team three are holding A Heaven on Bind and their Viper toggled her wall on A Short, do not cross it",
    "tell my team one at B Nest on Abyss and their Deadlock has annihilation ready, watch for the cocoon shot",
    "tell my teammates two at B Arch on Corrode with smokes incoming and their Brimstone has orbital on the spike",
    "call out that one is at mid top on Corrode by the stairs and their KAY/O knife just hit two of us, abilities gone for eight seconds",
    "let my team know two enemies at A Crane on Corrode with an operator and their Harbor has reckoning up to rush us",
    "tell my team three at A Garden on Haven and their Fade haunted the site, five second reveal still ticking",
    "warn them one is ninja-holding B Cubby on Bind and their Sage has rez up, she is waiting for a trade before rezzing",
    "tell my team two are at B Danger on Abyss trying to jump over and their Raze has showstopper, smoke that ledge",
    "let my teammates know four at A Main on Split and their Breach just fault-lined the entry, everyone is dazed for three and a half seconds",
    "tell my team one at nest above garage on Haven and their Vyse has arc rose planted up there, do not push until she pops it",
    "call out two at B Link on Corrode and their Iso has contingency wall ready to push through to B Site",
    "warn my team three on A Bridge on Abyss and their Neon has overdrive up, if she slides off the bridge she can reposition instantly",
    "tell my team one at mid catwalk on Abyss by the vent door and their Yoru placed a gatecrash tether through the vent, watch for the fake",
    "let them know two at C Long on Haven and their Waylay just placed her refract beacon at C Platform, she will recall if she loses the duel",
    "tell my teammates three at B Long on Bind with an operator and their Jett has blade storm, double op pressure on long",
    "tell my team four at A Short on Haven with their Gekko's dizzy ready to flash everyone in A Lobby before they hit",
    "warn the team one is at hell on Ascent under A Heaven and their Killjoy has nanoswarms placed at A default, do not defuse without clearing them",

    # =========================================================================
    # BLOCK 4 — OUR POSITION + THEIR ULT + DIRECTIVE  (mixed ownership)
    # =========================================================================
    "tell my team we are all on B Site right now and their Killjoy has lockdown, everyone find cover or fall back before the detain",
    "let my teammates know I am planting at A default and their Viper is about to pit us, someone needs to bait her out of the cloud",
    "warn my team we are retaking C Site and their Sage has resurrection up, burst through before she can rez whoever we kill",
    "tell the guys we are holding A Heaven and their Omen just ulted to our CT, check CT immediately and destroy the shade",
    "tell my team we are slow-pushing B Main on Fracture and their Tejo still has armageddon, do not cluster in the corridor",
    "let them know I just planted on B default on Ascent and their Harbor has reckoning up to clear us off post-plant",
    "tell my teammates we are taking mid on Haven and their KAY/O is about to null-command the entire mid, abort entry until his ult fades",
    "warn the team our entry fraggers are already on A Site and their Fade nightfalled them, they all have terror trails on",
    "call out that we are pinching B from both sides and their Astra has cosmic divide ready to split the site and cut off one push",
    "tell my team I am in B Hookah right now and their Raze has showstopper aimed at window, smoke it before I push through",
    "let my team know we are executing A on Haven and their Breach has rolling thunder up for A Long, delay the entry by three seconds",
    "tell my teammates we are running A Bath on Bind and their Skye has seekers, they will home to us the moment we push through",
    "warn them we are retaking B on Corrode and their Chamber is sitting at B Tower with tour de force, smoke the tower first",
    "tell the team we are setting up post-plant on A and their Reyna just went empress, do not let her chain into us",
    "call out that I am Wingman-planting right now and their Cypher has a cam dart on the wingman, they know exactly where the spike goes",
    "tell my team we are holding C Long on Haven and their Yoru just sent a gatecrash tether through C Short, watch for the teleport",
    "let them know we are on B default plant and their Brimstone has orbital on the spike position, delay the defuse",
    "tell my teammates we are rushing A Short on Haven and their Neon has overdrive up at A Lobby, she will beam everyone in the chokepoint",
    "warn my team we are in mid catwalk on Abyss near the vent and their Deadlock placed gravnet at the vent exit, walk through slowly or get pinned",
    "tell my team I am defusing right now and their Clove died but she still has a ruse smoke active, she is buying time for them to retake",
    "tell the guys we are taking A Crane on Corrode and their Iso has undercut coming through the wall to suppress our entire push",
    "let my team know we are playing A default plant and their Vyse has razorvine invisible on that spot, do not run through it",
    "tell my teammates we have three on B Site right now and their Veto has evolution active, every flash and net we throw at him is wasted",
    "warn them we are anchoring B with our Killjoy and their Gekko's thrash is being piloted toward the nanoswarms, shoot it now",
    "call out that I am rotating through mid on Ascent and their Sova fired hunter's fury beams across mid, two beams left, hold",
    "tell my team we are splitting A on Split and their Waylay has convergent paths ready, the beam zone will hinder our second wave",
    "let them know we are on a bonus round and their team is full-buying with a KAY/O who has null command, do not group up",
    "tell my teammates we just took Garage on Haven and their Astra pulled back a star to fake smoke at B, do not fall for the fake rotate",
    "warn my team we are holding A Long with our Chamber op and their Reyna is about to leer through the wall to nearsight him, shoot the eye",
    "tell the guys we are mid-executing on Pearl and their Fade has prowlers ready on top of the nightfall terror trails she already put on two of us",

    # =========================================================================
    # BLOCK 5 — ABILITY STATE + POSITION + ECO DIRECTIVE  (ecobleed stress)
    # =========================================================================
    "tell my team they are on an eco round, their Jett has no abilities but she still has a marshal, do not throw positions",
    "let my teammates know we are force-buying and their team is full-buy with ults ready, play passive and pick one before committing site",
    "warn the team they are saving hard and their Killjoy has lockdown from last round, even eco she is dangerous if we rush",
    "tell my team we need to save this round but our Sage still has resurrection, do not die with that ult available",
    "call out that they are force-buying with pistols and their Reyna is running empress on a sheriff, she can still chain through us",
    "tell my teammates we are on a full buy and their team just eco-rushed A Short on Bind, they have no abilities at all, rush them back",
    "let them know they won the last pistol so they are on a bonus and their Skye bought a spectre with guiding light, expect two hawks",
    "tell my team we all need to save but our Raze has showstopper, use it if we get a good spot and then save the vandal",
    "warn my team they are half-buying and their Brimstone only has one smoke, only one site can be properly blocked this round",
    "tell my teammates it is an eco round and we are force-rushing B, their Chamber has tour de force from the orbs he got last round, be careful on long",
    "let the team know they are full-buying after an eco loss, all five have rifles and their KAY/O bought his knife, expect a zero-point before site entry",
    "tell my team we are full-buy and they are on pistols, do not let Reyna get a single kill or she will empress through all of us on a ghost",
    "warn them we cannot afford to force and we need to save, but their Viper has pit from last round and will anchor A Site for free",
    "call out that they are eco and rushing hard with classic pistols and their Yoru is faking tethers to waste our utility, do not shoot the fakes",
    "tell my team we are thrifty-buying with spectres and their full-buy has an operator Jett at A Long, smoke long before any commit",

    # =========================================================================
    # BLOCK 6 — COUNT + ULT OWNERSHIP + ACTION DIRECTIVE (high density)
    # =========================================================================
    "tell my team two of ours have ult, our Breach has rolling thunder and our Skye has seekers, pop both on A at the same time",
    "warn them one enemy has ult and three of ours do, their Reyna has empress, hold it tight while our Omen ulting flanks her",
    "let my teammates know all five of their team have ults charged this round, do not commit any site until we burn at least one from range",
    "tell my team three of them have ult and only our Brimstone has orbital, play passive and look for picks before we execute",
    "call out that their Killjoy and their KAY/O both have ult and they are stacking A, both ults are primed to deny site access simultaneously",
    "tell my team our Sova has fury and our Breach has rolling thunder and we have a three-man ready to go, double ult A Long then hit site",
    "warn them their Clove and their Viper both have ults up on A, the site is a dual-ultimate pit and decay nightmare, go B",
    "let my teammates know their Astra has divide and their KAY/O has null command, those two ults together lock down an entire site completely",
    "tell my team their Jett and their Neon both have ults and they are mid, do not take any duel in the open against either of them",
    "call out that we have four ults ready across our team but they also have three, the ult economy is even so play for picks first",
    "tell my team their Raze has showstopper and their Breach has rolling thunder, classic double ult execute coming, brace for a loud entry",
    "warn them their Yoru has dimensional drift and their Fade has nightfall primed, information overload is coming, play off sound and minimap",
    "tell my teammates our Gekko has thrash and our KAY/O has null command and our Tejo has armageddon, three ult execute on B this round",
    "let my team know their Sage has rez and their Deadlock has annihilation, losing a duel near either of them can cost us two targets at once",
    "tell my team their Vyse has steel garden and their Viper has pit and they are defending A, our primaries get jammed inside a decay pit simultaneously",

    # =========================================================================
    # BLOCK 7 — POSITION + DAMAGE STATE + DIRECTIVE  (three-fact health/position/action)
    # =========================================================================
    "tell my team I tagged their Jett for 74 at A Long and she dashed away, she is low near A Heaven now, push heaven before she heals",
    "let them know I dink'd their Chamber at C Long for 83 damage, he is one shot behind C platform, do not peek from range",
    "warn my team their Reyna got a kill and is at 150 HP with overheal from empress in B Short, she will dismiss if pressured",
    "tell my teammates two of them are on B Site at 50 HP or less and our Clove has meddle, decay them and burst through",
    "call out that their Neon took 60 from our Vyse vine and she is low mid, hit her before the slide resets on overdrive",
    "tell my team I traded one at A Short for 80 damage and he fell back to A Heaven stairs, he is one shot and cannot use heaven angles safely",
    "let my team know their Skye got tagged 65 at B Lobby and she still has two hawks left, she will burn both before she dies",
    "warn them their Raze is at B Hookah at 40 HP, our KAY/O should zero-point through the wall to suppress before she showstoppers",
    "tell my team I hit their Iso for 55 at mid courtyard on Haven and he stepped behind the box, he is low and he has contingency wall ready",
    "call out that their Killjoy is at 30 HP at B back site and she still has lockdown active, kill her before the detain fires",
    "tell my teammates I shot their Yoru twice at C Short for 70 total and he faked a gatecrash, he is low and faking near C Logs",
    "warn the team their Sage healed herself in heaven on Ascent and she is back to 100 HP, she still has rez and the slow orb",
    "let my team know their Viper is at 25 HP outside her pit at A Site, eight seconds on the cloud before it collapses if we bait her out",
    "tell my teammates their Waylay took 55 from our Sova dart at B Main and her refract beacon is already placed at B Heaven, she will recall if pressured",
    "tell my team I hit their Clove for 90 and she went into not dead yet, she needs one kill in ten seconds or she dies permanently, do not let her get it",

    # =========================================================================
    # BLOCK 8 — ABILITY CHAIN COMPOUNDS (3 facts = two ability events + directive)
    # =========================================================================
    "tell my team their KAY/O zero-pointed mid and suppressed three of us for eight seconds and his null command is also up, do not entry at all",
    "let them know our Breach fault-lined A Main and our Skye hawk-flashed behind it, entry on the stun before the hawk lands",
    "warn my team their Fade haunted our position and she is releasing prowlers on our terror trails, break line of sight in the next three seconds",
    "tell my teammates our Sova recon hit four of them on B Site and our Tejo salvo missiles are landing in five seconds, push on the explosion",
    "call out that their Astra pulled nova pulse on B Entry and has gravity well primed at the spike, the stun is clearing but do not plant until the well fires",
    "tell my team their Neon relay-bolted the stairs on Split and her fast lane walls are also up, the staircase is stunned and walled simultaneously",
    "let them know I fired two shock bolts into A Heaven on Ascent and our Phoenix is flashing through the window immediately after the second explosion",
    "warn them their Harbor storm-surged B Elbow and his reckoning wave is pushing in right behind it, we are about to get nearsighted twice in a row",
    "tell my team our KAY/O flashed through the wall at B Hookah and his frag is also on the floor, two-ability clear before we push the window",
    "call out that their Viper toggled her wall on and threw snakebite at our A Short crossing at the same time, they tracked our exact timing",
    "tell my teammates our Breach aftershocked the defuse spot and our Brimstone has orbital primed to follow, post-plant double layer coverage on the spike",
    "warn my team their Gekko's dizzy is in the air toward A Main and wingman is also pushing B simultaneously, they are splitting utility across both sites",
    "tell my team their Iso undercut three of us through the wall and he is now pushing through with contingency up, abilities locked and a bullet-proof wall approaching",
    "let them know our Clove smoked A after dying and our Omen is stepping into the dead smoke to get a one-way angle, do not push the smoke from our side",
    "tell my team their Skye tiger concussed our entry and her seekers are tracking our three remaining players, everyone break line of sight in the next second",
    "call out that their Tejo stealth drone popped and suppressed four of us for eight seconds and his armageddon is lined up on our retake path, hold the retake",
    "warn my team their Vyse shear triggered behind our Jett and cut off her retreat and steel garden fired on the whole team, she has no dash and we have no primaries",
    "tell my teammates our Sova owl drone marked their Jett and his recon bolt is also live on A Site, two information sources on the same player right now",
    "let them know their Breach hard-flashed A Main and his rolling thunder fired immediately after the flash, both landed at the same time on entry",
    "tell my team their Deadlock sonic sensor triggered on our push and gravnet fired at the same chokepoint, concussed and pinned simultaneously at B Main",
    "warn them their Veto chokehold tethered our Neon in mid and his interceptor destroyed her fast lane walls at the same time, she has no walls and she cannot move",
    "tell my team our Harbor storm-surged their A Lobby push and his reckoning followed right behind it, both CC abilities hit them at once, push now",
    "call out that their Reyna leer flew through the wall into our B Site hold and she is about to empress with three kills already on her hands",
    "tell my teammates their Astra dissipated a fake smoke at A to bait our rotation then immediately activated real nova pulse at B Main, classic fake",
    "warn my team their Yoru sent fakeout footsteps toward A Long and his gatecrash tether is actually heading to B through mid, watch the real teleport",
    "tell my team our Gekko reclaimed his wingman globule and dizzy globule, both are recharged and coming back up in fifteen seconds for the retake",
    "let them know their Killjoy recalled her alarmbot and repositioned it at A Link and her turret is now watching A Short simultaneously",
    "tell my team their Phoenix used curveball to flash into his own blaze wall and he is healing inside it, kill him now before he recovers full HP",
    "warn them their Iso double-tapped an orb after killing our Breach and now has a shield, he has shield plus contingency wall plus kill contract ready this round",
    "tell my team our Fade nightfalled into C Long and three of them got trails and now our prowlers are locked onto those trails, they cannot escape",

    # =========================================================================
    # BLOCK 9 — MAP-SPECIFIC POSITION + ULT + DIRECTIVE  (per-map variety)
    # =========================================================================
    # Haven
    "tell my team their Sage walled B Doors on Haven and she has resurrection up and is holding Gong, burst the wall before she rezzes",
    "warn them their Chamber is at Nest above Garage on Haven with tour de force and he has a trap on C Short, do not push C or Garage",
    "let my team know we are pushing A Long on Haven and their Viper toggled her wall at A Sewer, one entry is blocked and she has pit up",
    "tell my teammates their Astra has cosmic divide cutting across mid courtyard on Haven and nova pulse is primed at C Long, rotate A instead",
    "call out that their KAY/O zero-pointed Garage on Haven and suppressed two of us and his null command is active too, every ability is gone in garage",

    # Ascent
    "tell my team their Killjoy has lockdown and nanoswarms placed at A default on Ascent and her turret is watching A Link, that site is locked",
    "warn them their Jett is holding A Long on Ascent with blade storm and she closed the A Door, do not try to force that angle",
    "let my team know we have B Window control on Ascent and their Fade haunted through B Main, fall back from the window before prowlers hit",
    "tell my teammates their Sova just fired two shock darts into A Heaven on Ascent and has fury ready, do not take the Heaven angle this round",
    "call out that their Omen stepped into B Market on Ascent and dark-covered the B Site entrance, he has a second smoke and paranoia still available",

    # Split
    "tell my team their Raze is at Ramps on Split with showstopper and she blast-packed up to the boxes, flank incoming from heaven",
    "warn them their Cypher has a cam above B Heaven on Split and neural theft ready, every rotate we make goes to their team in real time",
    "let my team know we are executing B on Split and their Harbor reckoning-waved into our push from CT and his high tide wall is also up",
    "tell my teammates their Breach flashed through the wall at A Main on Split and has rolling thunder primed for the execute follow-through",
    "call out that their Viper walled Mid Vent on Split and her pit is already set on B Site, that entire site is a fuel-gated decay trap",

    # Fracture
    "tell my team their KAY/O is ulting through B Arcade on Fracture and has two flash drives left, abilities gone for fifteen seconds along that flank",
    "warn them their Neon is sprinting through A Rope on Fracture with overdrive and she has relay bolt aimed at A Site entry",
    "let my team know we are pushing A on Fracture and their Tejo's stealth drone popped at Dish suppressing three of us for eight seconds",
    "tell my teammates their Astra gravity-welled the A main entry on Fracture and has cosmic divide up to split the site simultaneously",
    "call out that their Yoru placed gatecrash through the wall near B Arcade on Fracture and is running dimensional drift, double fake incoming",

    # Pearl
    "tell my team their Viper has pit set on A Site on Pearl and her wall splits mid, she controls both mid approaches from the same pit",
    "warn them their Chamber is deep at B Main on Pearl with tour de force and his rendezvous anchor is in B Hall, he will TP back instantly",
    "let my team know we are taking A Art on Pearl and their Skye has three seekers tracking our whole push, break line of sight in the art room",
    "tell my teammates their Fade haunted A site on Pearl and nightfalled into our approach simultaneously, double-reveal on all five of us",
    "call out that their Brimstone smoked all three B entry points on Pearl and has orbital primed on the default plant, do not touch that spike",

    # Lotus
    "tell my team their Deadlock has annihilation ready at A Tree on Lotus and gravnet is placed at the A swing angle",
    "warn them their Gekko wingman is planting B on Lotus and dizzy is covering the B entry simultaneously, spike going down and entry is flashed",
    "let my team know their Iso contingency-walled C Main on Lotus and has kill contract ready to pull our entry fragger, hold the push",
    "tell my teammates their Astra divided C connector on Lotus and her nova pulse is placed at the C site default, both CC abilities are on our retake path",
    "call out that their Harbor coved the spike on Lotus B and his reckoning wave cleared the retake path, the spike is shielded and our retake is stunted",

    # Breeze
    "tell my team their Jett is holding mid on Breeze with blade storm and an operator and she has her dash, pure death angle",
    "warn them their Viper walled mid on Breeze and has pit set on A Site with her wall as an outer layer, double chemical death zone",
    "let my team know we are going B Main on Breeze and their Sova fired recon bolt at B Site and has fury up, all three beams aimed at B Main",
    "tell my teammates their Fade haunted B Elbow on Breeze and nightfall is incoming from mid, full reveal on our B push imminent",
    "call out that their Astra used cosmic divide across the mid opening on Breeze, infinite wall blocking all mid bullets for twenty one seconds",

    # Icebox
    "tell my team their Killjoy has lockdown on B Site on Icebox and nanoswarms planted at B Default, dual detain and denial on the spike",
    "warn them their Sova is at B Snowman on Icebox with owl drone marking and fury ready, he has eyes and three beams on B Site",
    "let my team know we are trying to take A Rafters on Icebox and their Viper wall blocks the A connector and pit is active at A Site",
    "tell my teammates their Skye seekers launched into A Site on Icebox and her tiger concussed our entry at the same time, double CC at entry",
    "call out that their Omen stepped up to A Rafters on Icebox from CT and has two smokes plus paranoia through the Rafters wall ready",

    # Bind
    "tell my team their Raze showstopped into A Bath on Bind and blast-packed onto the triple box, we need to clear heaven before planting",
    "warn them their Killjoy has lockdown at B Cubby on Bind and nanoswarm is placed at B Elbow, both guard the B Hall rotation",
    "let my team know we are pushing through hookah on Bind and their Sage walled the B window and has rez up at back-site",
    "tell my teammates their KAY/O flashed through the A Lamps wall on Bind and his frag landed at A Bath entry, both abilities at one chokepoint",
    "call out that their Viper walled through A Short on Bind and her poison cloud blocks A Bath simultaneously, both routes to A are chemical-blocked",

    # Abyss
    "tell my team their Jett is at A Bridge on Abyss with blade storm, if she dashes off the bridge she lands at A Tower angle",
    "warn them their Deadlock gravnetted mid library on Abyss and annihilation is ready, anyone crossing mid bottom will be pinned",
    "let my team know their Sova recon hit three of us at A Tower on Abyss and he has fury, do not stay on the tower ascender",
    "tell my teammates their Neon overdrive-slid through the breakable vent door on Abyss and is now at A Tower, she reset her slide with a kill",
    "call out that their Yoru's gatecrash tether went through the vent wall on Abyss and he is in dimensional drift scouting A Secret",

    # Corrode
    "tell my team their Tejo stealth-droned into A Crane on Corrode and suppressed our Sova for eight seconds and armageddon is lined on A Site",
    "warn them their Iso undercut our retake push through A Yard on Corrode and has contingency wall ready at A Elbow",
    "let my team know their Viper walled mid stairs on Corrode while we were in the flooded walkway so our footsteps were already audible",
    "tell my teammates their Astra pulled gravity well at B Link on Corrode and cosmic divide is ready to split the B approach right after",
    "call out that their Harbor storm-surged B Elbow on Corrode and then reckoning-waved into B Main, double water CC on our entire B push",

    # =========================================================================
    # BLOCK 10 — FIRST-PERSON + 3-FACT COMPOUND (streamer self-reports + directives)
    # =========================================================================
    "tell my team I have blade storm ready, I am holding A Long right now, and I will use it the moment I see their Jett peek",
    "let them know I have resurrection up, I am anchoring B back-site, and I will only rez whoever dies closest to the spike",
    "warn the team I have hunter's fury charged, my recon bolt is live on A Site, and I am about to fire all three beams across A Main",
    "tell my team I have lockdown ready, I placed nanoswarms at A default, and I will detain the moment our retake reaches the site",
    "call out that I have not dead yet up, I will ult after I die, and I need one kill within ten seconds or I am gone for real",
    "let my teammates know I have null command active, I am pushing mid on Haven right now, and every enemy in range cannot use a single ability",
    "tell my team I have showstopper ready, I am blast-packing toward B Short right now, and I will rocket the site on landing",
    "warn them I have from the shadows up, I am stepping into B smoke now, and I am about to ult to A CT to catch them rotating",
    "tell my teammates I have cosmic divide charged, I am entering Astral Form right now, and I will divide A Site on the execute signal",
    "let my team know I have seekers ready and my tiger is pushed into A Site right now, three enemies spotted and seekers incoming immediately after",
    "tell my team I have tour de force up, I am holding C Long right now with my op, and I have a trademark at C Short to catch the rotate",
    "warn my teammates I have reckoning ready, my cove is shielded on the spike right now, and I will wave the retake path when they push",
    "tell my team I have armageddon charged, my stealth drone suppressed their Killjoy for eight seconds, and the airstrike is going on her setup",
    "let them know I have overdrive active right now, I already slid onto A Site, and my relay bolt hit two of them in the entry at the same time",
    "tell my team I have nightfall up, my haunt revealed three of them at B Main, and I am launching nightfall down that corridor right now",
    "warn the team I have steel garden ready, I am popping it on their push at B Elbow right now, their primaries are jammed for eight seconds",
    "tell my teammates I have annihilation ready, my gravnet is at B Short, and I will cocoon whoever walks through the net first",
    "let my team know I have not dead yet available this round, I am defusing the spike right now, and I will ult back up if they kill me before it finishes",
    "tell my team I have evolution up, I am completely immune right now, and I am pushing through their killjoy lockdown and their viper molly at the same time",
    "warn them I have convergent paths ready, my refract beacon is placed at B Heaven right now, and I will fire the ult to hinder their retake then recall to safety",

    # =========================================================================
    # BLOCK 11 — COMPOUND WITH DIRECTIVE + TIME PRESSURE  (round clock stress)
    # =========================================================================
    "tell my team we have thirty seconds left, their Sage has rez up at A default, and we cannot afford to lose another body near that site",
    "warn my team the spike has twenty seconds left, their Viper is still inside her pit, and we have to bait her out before the eight second pit timer even starts",
    "let them know we have fifteen seconds to defuse and their Brimstone has orbital already landed on the spike, wait out the orbital then full-defuse immediately",
    "tell my teammates the spike is at ten seconds, I see a Clove dead smoke covering CT entry, use the smoke and ninja-defuse right now",
    "call out that we have forty seconds left, their KAY/O zero-pointed mid, and our abilities are locked for eight more seconds so we cannot execute yet",
    "tell my team the round clock is at twenty-five seconds and their Astra has cosmic divide on A Site, we do not have time to go around it and we need to force B",
    "warn them their lockdown was just deployed with thirteen seconds on the windup and we have thirty seconds on the round clock, the detain fires before we can rush it",
    "let my team know spike is down with forty-five seconds and their whole team has ults, we play passive around spike and let their ults expire before we peek",
    "tell my teammates we have twenty seconds left to plant and their Harbor has reckoning up, we need to commit immediately before the wave cuts us off",
    "call out that the round clock is under thirty seconds, their Killjoy still has nanoswarms placed at B default, and we have to activate them before planting or the spike burns",

    # =========================================================================
    # BLOCK 12 — MIXED OUR/THEIR MULTI-AGENT COMPOUNDS  (complex ownership)
    # =========================================================================
    "tell my team our Sage is walling B Heaven and their Raze has showstopper ready to blast-pack over the wall, smoke above the wall before she jumps",
    "let them know our KAY/O zero-pointed B Site and suppressed three of them, but their Killjoy lockdown is still ticking because she is not suppressed",
    "warn my team our Viper walled mid and our Sova recon revealed two behind it, but their Astra has a gravity well placed on our side of the wall",
    "tell my teammates our Skye flashed A and our Breach fault-lined behind the flash, but their KAY/O absorbed both with null command already up",
    "call out that our Tejo droned and suppressed their whole flank but their Clove died and is rusing smoke from the grave, a live smoke appeared despite the suppress",
    "tell my team our Gekko's dizzy blinded two of them at B Main but their Veto has evolution active and he is completely immune to the plasma blind",
    "let my team know our Fade nightfalled into three of them and our prowlers are tracking the trails, but their Waylay recalled to beacon before the prowler hit her",
    "warn them our Brimstone smoked all three B entry points but their Jett blade-stormed and is going aerial over the smokes with an updraft, check sky",
    "tell my teammates our Killjoy placed nanoswarms at A default and their Deadlock annihilated our entry, we lost the entry and now their retake is free",
    "call out that our Omen dark-covered garage and stepped into it but their Cypher had a cam inside the smoke, Omen's position is revealed to all of them",
    "tell my team our Phoenix flashed with curveball and ran it back for a second push but their Reyna dismissed and waited out the respawn timer behind cover",
    "let them know our Yoru faked a gatecrash at A and real-teleported to B but their Fade's haunt eye was on B Site and she spotted the arrival and trailed him",
    "warn my team our Neon slid onto B with overdrive and killed one but their Sage just resurrected the person she killed, kill count reset by the rez",
    "tell my teammates our Chamber is holding A Long with tour de force but their Iso undercut through the wall to suppress him and he cannot use rendezvous right now",
    "call out that our Harbor shielded the cove on the spike but their Vyse popped arc rose to blind our Viper who was watching the defuse, the hold is broken",
    "tell my team our Astra divided B Site and pulsed B entry but their Clove died and her ruse smoke is now covering the exact hole in the divide wall",
    "let my teammates know our Sova fury fired all three beams at B Main but their Iso used contingency wall to block two of the beams from hitting their team",
    "warn them our Breach rolling-thundered A Long but their Neon was in overdrive sprint and out-ran the concuss wave, she is already on site unsuppressed",
    "tell my team our Viper toggled her wall off to let us cross but their Tejo sent a guided salvo right through the gap in the wall at that exact moment",
    "call out that our Deadlock gravnetted B Elbow and their Veto's evolution made him fully immune, he walked through the net at full speed while the rest of their team was pinned",

    # =========================================================================
    # BLOCK 13 — IDENTITY/PERSONA EDGE CASES mixed with 3-fact
    # =========================================================================
    "tell my team I am not a soundboard, I am an AI sent from the future, and I am telling you right now that their Jett has blade storm at A Long so do not peek",
    "let them know their Killjoy lockdown is set at B default, two nanoswarms are placed around it, and if you rush in anyway that is on you not me",
    "warn my team their Reyna has empress, she just got two kills, and she is going to chain through all of us unless someone stops baiting and trades",
    "tell my teammates I have calculated this: three of them have ults, they are stacking A, and the only rational play is a fast B execute right now",
    "call out that I am watching their eco patterns and they are force-buying with their Chamber still holding tour de force from last round, do not ignore that",

    # =========================================================================
    # BLOCK 14 — NATURAL PHRASING VARIETY (different relay trigger words)
    # =========================================================================
    "pass to my team that their Fade has haunt up, she haunted A Site on Lotus, and prowlers are incoming on the two revealed targets",
    "relay to my teammates that I have three charges left on blade storm, I am at A Heaven on Split, and I will dash to safety if we win the duel",
    "shout out to the team that their KAY/O just suppressed B Main on Fracture, his null command is active, and their whole team is following his pulse",
    "let the team know that I have empress active, I already got two kills on A Long, and I am pushing through A Short solo right now",
    "tell them for me that their Brimstone smoked the three B exits on Pearl, has orbital on the spike, and they are playing full post-plant behind the smokes",
    "pass along that our Yoru faked a gatecrash at B, actually real-teleported to A Short, and now he has dimensional drift up to scout before re-engaging",
    "relay that their Sage slow-orbed A Bath on Bind, walled the bath exit simultaneously, and still has resurrection in case the push falls apart",
    "tell my guys that I have convergent paths charged, my beacon is at B Hookah on Bind, and I am about to hinder their entire A push while recalling to safety",
    "let the squad know their Tejo droned and suppressed four of us, salvo missiles are already in the air, and armageddon is lined up right behind both",
    "shout to the team that their Clove rused A smoke while dead, not dead yet is about to fire, and she needs one kill in the next ten seconds to stay alive",

    # =========================================================================
    # BLOCK 15 — HARD AMBIGUOUS STRUCTURES (inversion bait)
    # =========================================================================
    "tell my team it is not our Killjoy who has lockdown, it is their Killjoy who has lockdown, and she is at A Site not B Site",
    "warn them that was not our Sova recon that hit us, it was their Sova recon, and it revealed all five of us near mid library",
    "tell my teammates our Sage has rez, their Sage does not have rez, and we need to use that advantage when we retake",
    "let my team know I said their Jett has blade storm not our Jett, do not take the A Long duel this round period",
    "call out that it is their Viper in the pit, not ours, she can see us but we cannot see her, the ownership matters for the post-plant",
    "tell my team our ult is ready, specifically our Breach has rolling thunder, not their Breach who used his ult two rounds ago",
    "warn them the KAY/O who suppressed mid was theirs not ours, our KAY/O is still saving his knife for the execute",
    "tell my teammates that the recon bolt that scanned B Main was our Sova's, it hit three of their players, and their positions are live on the minimap",
    "let my team know the person in empress right now is their Reyna, she already got two kills, not our Reyna who died in round two",
    "call out that the phoenix who respawned at A was their Phoenix using run it back, our Phoenix is dead for real and has no ult this round",

    # =========================================================================
    # BLOCK 16 — QUESTION-ADJACENT but clearly RELAY (ask-vs-answer stress)
    # =========================================================================
    "tell my team whether their Killjoy has lockdown this round — our Cypher cam shows her buying a nanoswarm but not the lockdown in the buy phase",
    "let them know I cannot confirm if their Sage has rez right now but she got zero kills last round so she probably does, play as if she does",
    "warn my teammates I do not know exactly where their Yoru teleported but his gatecrash tether was last seen heading toward A Short, watch A",
    "tell my team I got shot from an unexpected angle at B Cubby and took 72 damage, do not know who it was but someone is off-angle back-site",
    "call out that their Omen stepped somewhere in the last three seconds, I heard the audio but cannot confirm destination, watch every angle simultaneously",
    "tell my team we do not know how many ults they have but they won four of the last five rounds, assume full ult stacking and play accordingly",
    "warn my teammates I hit someone at C Long for unknown damage before I died, someone is low at C Long but I cannot call the number",
    "tell the team I think their Astra has a star placed at our rotation path but I cannot confirm activation yet, tread carefully through that corridor",
    "let my team know I spotted a Cypher trapwire somewhere in A Short but I did not see exactly where, clear A Short carefully before crossing",
    "call out that I heard the sound of a Killjoy nanoswarm arming somewhere on B Site but I cannot see it yet, do not rush plant position until it shows",

    # =========================================================================
    # BLOCK 17 — ULTRA-DENSE 3-FACT COMPOUNDS (latency stress for 3B)
    # =========================================================================
    "tell my team their Jett used blade storm to op and is holding at A Long and she still has her tailwind dash available to escape after the pick",
    "warn them our Sova owl-droned B and marked their Chamber who has tour de force and is sitting at B CT while his rendezvous anchor is on B Site",
    "let my team know their Astra has cosmic divide cutting from mid to A Site and she has a nova pulse primed at A Lobby and a gravity well at A Main entry simultaneously",
    "tell my teammates their Fade haunted and nightfalled simultaneously, trails are on our three entry fraggers at A, and prowlers are already homing along the trails",
    "call out that their KAY/O null-commanded mid, suppressed all five of us, and their whole team is rushing through on his suppression pulse right now while none of us can ability-fight back",
    "tell my team our Tejo suppressed their Killjoy with the stealth drone so her lockdown device cannot arm while suppressed, push lockdown now during the eight second window",
    "warn my team their Iso undercut through the wall to suppress and fragile our Sage who was about to rez, the rez is cancelled and Sage is now vulnerable to double damage",
    "tell my teammates our Clove smoked A and B simultaneously from the grave, our Omen dark-covered C, and we effectively have three site smokes up with only one live controller",
    "let my team know their Vyse steel-gardened our whole retake at B and their Viper pit is still active on B Site, jammed primaries inside a nearsight decay cloud is unwinnable",
    "call out that their Breach rolling-thundered A Long, their Skye simultaneously flashed A Short, and their Neon has overdrive to exploit both CC windows as they expire sequentially",
    "tell my team their Raze showstopped through B Hookah window on Bind, blast-packed onto back-site, and paint-shells are landing on B Default plant position right now",
    "warn them our Brimstone smoked all three of their A exits, dropped stim beacon at A default, and is about to orbital the back of site where their Viper is holding in pit",
    "tell my teammates their Yoru faked a gatecrash at A Long, sent fakeout footsteps down C Long, and is actually in dimensional drift waiting to ambush our mid rotation",
    "let my team know their Killjoy alarmbot is at A Link and turret is watching A Short and nanoswarms are placed at A default and she still has lockdown charged, that site is impenetrable",
    "tell my team our Gekko thrash-piloted into their backline on B Site, detained two of them, and wingman already planted the spike while the detained targets could not shoot",
    "warn my team their Waylay double-dashed through our B smoke, saturated the team inside the smoke to hinder everyone, and her convergent paths ult is about to expand and hit us all",
    "tell my teammates their Deadlock annihilated our Brimstone as he was placing smokes and the cocoon is pulling him to a kill point while their team pushes freely without smoke",
    "let my team know their Veto interceptor is active and destroying all our raze grenades and KAY/O frags and Killjoy nanoswarms that touch its radius, and his evolution makes him immune while we lose utility",
    "call out that their Phoenix has run it back active, he is pushing A Bath on Bind at 100 HP with curveball in both hands, and his blaze wall is already healing him through the damage we deal",
    "tell my team their Reyna has empress, no soul orbs are dropping because she used dismiss to pass through our Killjoy lockdown, and she is now fully healed at B back-site with leer covering her position",

    # =========================================================================
    # BLOCK 18 — NEGATIVE EDGE (clearly relay, not question, not narration)
    # =========================================================================
    "tell my team their Killjoy has no lockdown this round, she used it last round, do not play cautious on A Site",
    "let them know their Jett has no dash, she burned tailwind on that peek and missed, push her immediately",
    "warn my team their Sova has no recon this round, cooldown is running, we have a window before the next scan",
    "tell my teammates their Phoenix has no flash left, both curveballs are spent, we can push his position dry",
    "call out that their Viper has no fuel left, both wall and cloud will drop in seconds, cross immediately",
    "tell my team their Clove has no ult this round, she used not dead yet last round and needs eight more points",
    "let my team know their Astra has no stars left, she burned everything on the execute, no more smokes or CC this round",
    "tell my teammates their Breach has no rolling thunder, he used it on the B rush two rounds ago and is still one orb short",
    "warn them their Skye has no hawks remaining, both charges are gone, we can push A with no flash threat from her",
    "call out that their Chamber has no teleport anchor, enemies destroyed his rendezvous, he cannot escape this duel",
    "tell my team their Neon has no slide this round, she used both blast packs and overdrive expired, she has no escape from this 1v1",
    "let my team know their Fade has no prowlers this round, she threw both on our last push, follow the trail safely",
    "tell my teammates their Brimstone has no smokes remaining, he used all three last round and cannot re-smoke until next round",
    "warn the team their KAY/O has no knife this round, zero-point is on a forty second cooldown, abilities are safe temporarily",
    "tell my team their Deadlock has no gravnet this round, cooldown is active, the B push has no net threat for the next thirty seconds",

    # =========================================================================
    # BLOCK 19 — PLAYSTYLE + POSITION + ULT READS (opinion stress)
    # =========================================================================
    "tell my team their Jett is always going aggressive on A Long with blade storm and she always dashes back after the first trade, bait the dash first",
    "warn my teammates their Killjoy is anchoring B every round with lockdown, she never rotates, hit A and force her off with information",
    "let my team know their Reyna is snowballing off our worst player every round and she has empress again, stop letting one person fight her alone",
    "tell my team their Sova is running the same fury lineup through B Main every execute, he will fire it this round too, stand off the wall",
    "call out that their Omen is teleporting from shadows to our flank every other round with his dark cover on site, expect the flank when smokes go up",
    "tell my teammates their Clove is playing like she is unkillable with not dead yet every time she gets low and runs at us, burst her faster",
    "let my team know their Neon is rushing A every round with overdrive and she gets a slide reset on the first kill, do not give her that kill",
    "warn them their Tejo is droning mid every round and detonating on the player checking library on Abyss, stop going library first",
    "tell my team their Waylay is double-dashing into site every execute and immediately recalling to beacon, she is never committed, do not chase the beacon",
    "call out that their Breach always rolling-thunders after the third flash on A Main, the pattern is consistent, move laterally on the third flash count",
    "tell my teammates their Chamber takes the same off-angle by the wine shelf on Ascent A Main every round and rendezvouses out, pre-fire that exact spot",
    "let my team know their Cypher is setting up cams at the same three spots every round on Haven, our Raze should room-boom one to free us from the info",
    "warn them their Viper always toggles her wall off at exactly thirty seconds left so their team can cross, we can time our push to that toggle window",
    "tell my team their Yoru is sending fake footsteps to A every round and real-teleporting to B, we have spotted the pattern three rounds in a row",
    "call out that their Fade haunts our push every single entry, plant the haunt in front of our push and she wastes the cooldown every time",

    # =========================================================================
    # BLOCK 20 — SPIKE + ULT + DIRECTIVE  (spike state as one of the three facts)
    # =========================================================================
    "tell my team the spike is planted at A default on Ascent and their Killjoy has nanoswarms on it and lockdown is armed, do not touch the spike area",
    "warn my team I am defusing and their Brimstone has orbital on the spike position and his smokes are fading in two seconds, hold them off for five more",
    "let my team know spike is down at B default on Ascent and their Viper pit is active over the plant site and she can see all of us inside the cloud",
    "tell my teammates I am planting at B back-site on Haven and their Astra has a gravity well primed at default, I need two people to cover the grav",
    "call out that spike is planted at C default on Haven and their Sage has resurrection up and she is at C CT, burst through before she can rez the one we killed",
    "tell my team the spike is down at A Bath on Bind and their Chamber has tour de force watching heaven above bath, do not take the heaven angle mid-defuse",
    "warn them spike is planted at B hookah side on Bind and their KAY/O zero-pointed the retake path and suppressed our whole team, no abilities for eight seconds on the retake",
    "let my team know spike is down on A Site on Pearl and their Fade haunted the retake path and prowlers are on the three people coming to retake",
    "tell my team spike is planted at B Catwalk on Fracture and their Raze has showstopper aimed at the plant and their Breach has aftershock on the defuse spot",
    "call out that spike is down at A crane side on Corrode and their Viper toggled her wall on to cut off our rotation from mid and she still has pit up",
    "tell my team spike is planted at B default on Fracture and their Harbor shielded the cove on it and reckoning wave is blocking our B Link retake path",
    "warn my team spike is at B nest side on Abyss and their Jett has blade storm and is holding the B tower ascender angle with it, do not take the ascender",
    "let my team know spike is down at mid side A on Lotus and their Iso contingency-walled the B connector and has kill contract to pull whoever retakes through B",
    "tell my teammates spike is planted at C short side on Haven and their Deadlock annihilated our Breach who was trying to aftershock the defuse spot",
    "call out that spike is at A default on Split and their Vyse steel-garden ult is going off on the retake team right now, they cannot use primaries to break the wall",

    # =========================================================================
    # BLOCK 21 — FURTHER MIXED COMPOUND VARIETIES (fill to 600+)
    # =========================================================================
    "tell my team their Killjoy turret spotted our lurker at A Link on Ascent and lockdown is activating at A Site right now, the lurk is compromised",
    "warn them our Cypher cam caught their Omen stepping into B smoke on Ascent and he is lining up a paranoia through the market wall, cover your eyes",
    "let my team know their Viper wall is toggling off for exactly four seconds at the thirty-second mark and she has snakebite ready to throw at the crossing point",
    "tell my teammates their Skye tiger concussed our entry fragger at B Main on Pearl and two hawks are still up to flash the rest of the team entering",
    "call out that their Sova recon hit all five of us at B Lobby on Pearl and fury is ready with three beams, do not hold B Lobby angles",
    "tell my team their Astra pulled a nova pulse at our A execute entry on Lotus and then immediately dissipated the star to bait our follow-up smoke read",
    "warn my team their Yoru gatecrash-teleported into our post-plant hold at B on Fracture and has dimensional drift ready to escape after he kills the spike watcher",
    "let my teammates know their Neon relay-bolted the staircase on Split and fast-lane walls are also up there, the staircase is stunned and walled and she still has overdrive",
    "tell my team their Breach hard-flashed A Lobby on Haven through the wall and is ulting A Long at the same time, two CC abilities on the same route simultaneously",
    "call out that their Harbor storm-surged our B push on Fracture and then reckoning-waved into B Main, our entire push is nearsighted and slowed back-to-back",
    "tell my teammates their Tejo special-delivery concussed our Fade at mid top on Corrode and his guided salvo missiles are landing on A Crane in three seconds",
    "warn my team their Clove picked up a kill and used pick-me-up so she is at 150 HP with overheal and she has meddle plus not dead yet still on cooldown",
    "let my team know their Iso kill-contracted our Sova and the arena is running so we are four versus four and their other four have ults primed",
    "tell my team their Deadlock sonic-sensor concussed our whole team crossing B Main on Pearl and gravnet is landing right behind the sensor trigger",
    "call out that their Vyse shear wall trapped our Jett at B Short on Bind and arc rose is blinding everyone watching the shear from site-side",
    "tell my team their KAY/O flashed from safety through B hookah wall on Bind and his frag-ment is already on B site floor behind the hookah window",
    "warn my team their Reyna leer flew through the ceiling into our A Heaven on Ascent and she has empress active with four kills already this round",
    "let my teammates know their Sage slow-orbed our B push on Haven and walled B main entry simultaneously, both abilities at one chokepoint and she has rez still charged",
    "tell my team their Raze boom-bot rolled into our A site hold on Fracture and showstopper is ready to rocket anyone who shoots the bot",
    "call out that their Omen paranoia flew through the wall at mid top on Split and he dark-covered the top mid and bottom mid simultaneously from global range",
    "tell my team their Fade seize-tethered our Jett at B short on Lotus and prowlers are homing on her terror trail and she has no dash to escape the prowler",
    "warn them their Harbor high-tide walled our mid push on Pearl and storm-surge hit the three players trying to walk through the tide wall simultaneously",
    "let my team know their Brimstone stim-beacon dropped at A default on Haven and he is about to orbital the B site as a fake to pull our rotation",
    "tell my teammates their Waylay saturated our retake cluster at C Short on Haven and convergent paths is expanding to hinder our whole retake team",
    "call out that their Veto chokehold landed on our Sage mid-rez on B and tethered and deafened and decayed her before the resurrection finished",
    "tell my team their Gekko mosh-pit is landing at A site entry on Lotus and wingman is simultaneously pushing B from the B connector route",
    "warn my team their Astra cosmic-divide cut our A push on Breeze in half and gravity well activated on the back half of our push that is now separated",
    "let my team know their Chamber headhunter one-tapped our Sova in mid on Ascent and he has tour de force ready now that the orb from that kill charged him up",
    "tell my teammates their Deadlock barrier-mesh went up at B main on Icebox and annihilation fired through it immediately, wall plus nanowire cocoon at the same time",
    "call out that their Cypher placed two trapwires at B Hookah exit on Bind and his spycam dart is aimed at the B site default plant spot to reveal the planter",
    "tell my team their Phoenix blaze-wall blocked our A bath push on Bind and he is healing in it while curveball flashes the entry behind the wall",
    "warn my team their Iso double-tap shield ate the first shot from our Sova shock dart and he swapped to contingency wall to push forward under cover",
    "let my team know their Skye guiding-light hawk is in the air toward A main on Haven and her trailblazer tiger is also being piloted into A Long simultaneously",
    "tell my teammates their Sova owl-drone marked our Jett at A heaven on Ascent and the marking dart is live, their whole team sees her real-time position",
    "call out that their Neon fast-lane walls went up across A main on Split, she relay-bolted the staircase, and she slid onto A with overdrive active already",
    "tell my team their Astra nova-pulsed the B main entry on Split and gravity well fired at the spike position simultaneously, B site entry and post-plant both covered by ult",
    "warn them their Viper toggled wall back on right as our mid player crossed and snakebite landed on the crossing point at the exact same timing",
    "let my team know their KAY/O null-command is pulsing every three seconds, the fifteenth second is about to expire, get abilities back and execute immediately",
    "tell my teammates their Reyna just dismissed through our Killjoy lockdown and is re-engaging at full empress uptime because she stayed invulnerable through the detain",
    "call out that their Fade nightfall hit three of us at A Long on Haven and haunt eye is also up on A Tower, they have double-reveal plus terror trails on our push",
    "tell my team their Clove meddle-decayed our entry fragger at A short on Haven and then picked up the orb to go to 150 overheal right after we killed her teammate",
    "warn my team their Breach aftershocked our post-plant hold at B default on Split and rolling thunder is now going off on our entire retake path simultaneously",
    "let my team know their Jett cloudburst-smoked A long on Haven and pushed the smoke with blade storm active and an operator, free op angle inside her own smoke",
    "tell my teammates their Harbor coved the spike at B default on Pearl, shielded it with 680 HP, and high-tide wall is blocking our B short retake lane",
    "call out that their Killjoy alarmbot set off on our Yoru clone and now the clone is going to blind everyone who shot it before alarmbot tagged them",
    "tell my team their Tejo armageddon is running along A main on Ascent from garden to lobby direction and his stealth drone already suppressed our three-man retake",
    "warn my team their Vyse razorvine triggered on our Jett at B short on Lotus and steel garden fired simultaneously, she is slowed and her primary rifle is jammed",
    "let my team know their Skye seekers launched toward our two remaining players at B site on Lotus and her regrowth is topping off her own HP while seekers home",
    "tell my teammates their Omen dark-covered A long on Breeze from global range and from-the-shadows teleported to our CT behind us simultaneously",
    "call out that their Sova recon hit two at A main on Fracture and shock bolt double is landing in three seconds on the revealed positions, do not stand still",
    "tell my team their Breach fault-lined A lobby on Haven and our Sage started walling A main at the same time, the fault line passed through our own wall and hit us",
    "warn my team their Raze paint-shells landed inside B hookah on Bind and showstopper is aimed at whoever runs through the window after the cluster clears",
    "let my team know their Yoru fakeout footsteps went toward C long on Haven and his actual gatecrash tether is sitting at B site mid-map already placed",
    "tell my teammates their Astra dissipated a star at A to fake smoke while real nova-pulse is primed at B main and cosmic divide is charged for the follow execute",
    "call out that their Iso undercut our whole B push through the wall on Breeze, every one of us is suppressed and fragile, and he is pushing through with contingency wall blocking our shots",
    "tell my team their Chamber trademark triggered on our rotation at A link on Ascent and tour de force headshot killed our Sova who was droning at the time",
    "warn my team their Neon relay-bolted mid library on Abyss and overdrive slid through mid bottom simultaneously, she is already at B link before we can react",
    "let my team know their Deadlock gravnet landed on our three-man rush at B main on Split and annihilation is ready to cocoon whoever we send to break the net",
    "tell my teammates their Clove rused both smokes at B right after dying on Lotus and not dead yet fired at B short so she is alive at B with two smokes still running",
    "call out that their Gekko thrash-piloted into our KAY/O who was ulting and detained him so null-command ended early and our team lost the suppression pulse",
    "tell my team their Fade nightfall hit our whole team in the B main corridor on Pearl, five terror trails active, and prowlers are incoming in three seconds",
    "warn them their Viper snakebite landed right at our A site plant position on Lotus and the pit is activating on top of it, the spike cannot be defused inside the acid decay",
    "let my team know their Harbor storm-surge hit our retake at A Crane on Corrode and reckoning wave is pushing behind it through A Elbow simultaneously",
    "tell my teammates their Brimstone smoked A heaven and A short on Split simultaneously and orbital strike is aimed at the A default plant position right now",
    "call out that their Reyna leer flew through the B Hookah wall on Bind and empress is active, she dismissed through the molly to engage us on B site at full speed",
    "tell my team their KAY/O zero-pointed B main on Fracture and hit their own teammate too but null command cancelled our Breach rolling thunder that was already in the air",
    "warn my team their Sova fury-beamed across the top of A Rafters on Icebox and the second beam is aimed at our retake path through B green, spread out",
    "let my team know their Skye tiger concussed our entry at A main on Lotus and immediately flashed behind the concuss with guiding light before the daze expired",
    "tell my teammates their Omen paranoia flew through the B short wall on Bind toward our hookah hold and he dark-covered the hookah window simultaneously from the other side",
    "call out that their Vyse arc-rose flashed our Brimstone while he was on the map tablet for smokes and shear cut off his retreat so he could not escape while blinded",
    "tell my team their Veto evolution is active, he is immune to our KAY/O zero-point suppression and our Skye seekers and our Deadlock gravnet simultaneously, none of our utility works",
    "warn my team their Iso kill-contract pulled our Waylay right when she was about to recall to beacon, she cannot refract inside the contract arena and she will lose the duel",
    "let my team know their Neon overdrive beam is firing and she is sprinting at the same time, the beam has zero spread while she moves and she reset the slide with that kill",
    "tell my teammates their Astra gravity-welled the B main choke on Lotus, cosmic divide is cutting across site, and nova pulse is primed at the site itself, three ult abilities in one round",
    "call out that their Jett activated blade storm and then updrafted above our smoke to get an aerial op angle on our entry fraggers coming through the smoke below",
    "tell my team their Phoenix curveball flashed around the A garden wall on Haven and his run-it-back is active, if we kill him in garden he comes back at the C link marker",
    "warn them their Cypher spycam dart hit our Killjoy who is placing nanoswarms at A default on Lotus, they know exactly where every swarm lands",
    "let my team know their Tejo guided-salvo hit B elbow on Corrode twice with both missiles and armageddon is now targeted along B link which is the only other retake path",
    "tell my teammates their Clove pick-me-up activated after getting a kill on our entry, she is now at 150 HP with overheal inside her ruse smoke holding A tower on Haven",
    "call out that their Deadlock barrier-mesh went up in mid on Ascent and annihilation fired through it from the far side, the wall blocks our shots at the cocoon",
    "tell my team their Fade seize tethered our Neon right as she slid onto A main on Fracture, she is pinned for four and a half seconds and getting decayed at the entry",
    "warn my team their Chamber rendezvous anchor was destroyed by our Raze blast pack so he cannot teleport out after taking the tour de force shot on B Long on Breeze",
    "let my team know their Harbor cove shield on B default on Lotus just had its 680 HP broken by our Raze showstopper, the spike is now exposed for a clean defuse",
    "tell my teammates their Breach rolling-thundered A main on Fracture right as their Skye tiger was concussing the same players at A lobby, back-to-back CC on the same route",
    "call out that their Gekko's wingman defused four percent of our spike at B before we killed it, globule dropped and they can reclaim wingman to keep disrupting the defuse",
    "tell my team their Vyse steel garden fired on our B retake team on Haven and their Viper's pit is still active, our primaries are jammed inside a decay nearsight cloud simultaneously",
    "warn my team their Sova owl-drone is in the air scanning B short on Bind and his recon bolt is already placed at B site, we are about to have two information sources on our retake",
    "tell my team their Astra nova-pulsed our entire A execute on Haven, gravity-welled the default plant position, and cosmic divide is being lined up to split our follow-up team in half",
    "let my team know their Iso undercut came through the wall at A lobby on Split, suppressed and fragiled our Breach who was about to rolling-thunder the site, the ult is gone",
    "call out that their Neon high-gear-sprinted through our Killjoy gravnet and relay-bolted the corner behind the net, the stun hit three of our players who thought they were safe behind the net",
    "tell my teammates their Fade nightfall hit all of us at C short on Haven, all five terror trails are active, and she has prowlers that will move at triple speed along those trails",
    "warn my team their Raze blast-packed above our Viper wall on Icebox and paint-shells dropped on our side of the wall while we could not see through it",
    "let my team know their Killjoy lockdown detain is firing right now at A site on Breeze and their Viper pit is active on A site simultaneously, detained inside a decay zone",
    "tell my teammates their Omen stepped into his own dark cover at B main on Fracture and paranoia flew through the workshop wall at the same time, two abilities from inside his own smoke",
    "tell my team their Phoenix just killed two of us in run-it-back, his timer is extended, he is going to heal in his blaze wall and we are now in a three versus five",
    "call out that their Yoru dimensional-drift scout confirmed we are stacking B and he exited drift at A short on Haven and flash-gatecrashed A with blindside to exploit the info",
    "tell my team their Skye sent seekers on all three remaining players on our team and regrowth healed the last thirty HP she needed while seekers were flying",
    "warn my team their Deadlock sonic-sensor is covering B main on Pearl and gravnet is landing at mid window as a double-trap on the approach to B and A simultaneously",
    "let my team know their Brimstone stim-beaconed A main on Fracture for his rushers, smoked all three angles, and orbital is ready to drop on whoever defuses the spike",
    "tell my teammates their Waylay double-dashed through B short on Bind into hookah and saturated everyone inside hookah to hinder them and then recalled to beacon at B main immediately",
    "call out that their Viper fuel ran out and her wall is dropping in one second but her pit is still active, cross the wall instantly when it drops but do not step inside the pit",
    "tell my team their Clove died at B short on Lotus and smoked B main from the grave and immediately activated not dead yet, she is reviving at the dead smoke entry point",
    "warn them their KAY/O flash-drove B hookah window on Bind from safe range and frag-mented the B site floor behind it, both abilities through and over the window at the same time",
    "tell my team their Astra cosmic-divide landed perpendicular to our B execute on Pearl and her gravity well is on one half of our split team, one group cannot push while the other is pulled",
    "let my teammates know their Reyna leer through A long on Haven nearsighted our Chamber who was trying to counter-snipe with tour de force, the tour de force shot missed because of nearsight",

    # =========================================================================
    # BLOCK 22 — FINAL DENSITY FILL (position + two distinct ability facts)
    # =========================================================================
    "tell my team their Skye is at B main on Lotus with a hawk ready and a tiger already pushed past the B connector, double scout pressure on B",
    "warn my team their KAY/O zero-pointed our retake team at A main on Fracture and his flash-drive is already in the air behind the knife blast",
    "let my team know their Viper pit is active at B site on Breeze and her wall is cutting off our mid-to-B retake rotation at the same time",
    "tell my teammates their Killjoy turret is watching B main on Pearl and her lockdown is activating at B site right now, the turret gives her the info to lockdown on us",
    "call out that their Sova recon-bolted through B short on Bind and the drone is also in the air above hookah, two information tools on the same site simultaneously",
    "tell my team their Breach flashed B hookah on Bind through the wall and aftershocked the B cubby at the same time, double-ability clear before their push",
    "warn them their Omen stepped into C garage on Haven and dark-covered C Long simultaneously, he has both position and vision block on C in one move",
    "let my team know their Raze blast-packed to B heaven on Split and paint-shells are landing on B site below, aerial position plus grenade pressure at the same time",
    "tell my teammates their Neon relayed-bolt stunned our mid push on Ascent and her fast-lane walls are also up at mid, stun and wall at the same crossing point",
    "call out that their Astra nova-pulsed A lobby on Haven and gravity well pulled the players running out of the stun simultaneously, back-to-back CC at A lobby",
    "tell my team their Fade prowlers are on our terror trails from A and haunt eye is live above A site seeing through all our smokes simultaneously",
    "warn my team their Harbor reckoning wave hit our B push on Split and high-tide wall is also up at B heaven blocking our upper retake simultaneously",
    "let my team know their Tejo special-delivery concussed our A link player on Pearl and guided-salvo missiles are aimed at A site simultaneously from off-map range",
    "tell my teammates their Jett updrafted to A heaven on Breeze and blade-stormed the mid area from height before dashing back to safety, aerial op with escape",
    "call out that their Clove meddle-decayed our spike planter at B on Lotus and then used pick-me-up on the kill to go to 150 HP and she still has ruse ready",
    "tell my team their Deadlock mesh-barriered the B main chokepoint on Breeze and placed sonic-sensor behind the barrier, anything breaking the barrier triggers the concuss",
    "warn them their Iso undercut came through the A garden wall on Ascent and contingency-wall is pushing through the doorway at the same time, both abilities from one direction",
    "let my team know their Vyse arc-rose is planted at A heaven stairs on Ascent and razorvine is covering A default plant position invisibly, flash trap plus thorn trap at A",
    "tell my teammates their Yoru fakeout footsteps are going toward C long on Haven and his blindside flash is following the same path to make the fakeout look real",
    "call out that their Veto interceptor blocked our Sova recon bolt and our Raze paint shells in the same round, both information and damage utility cancelled in one interceptor",
    "tell my team their Sage slow-orbed B main on Lotus and barrier-orbed the B connector entrance simultaneously, approach is slowed and physically blocked at the same time",
    "warn my team their Waylay saturated our C push on Haven to hinder everyone and then double-dashed through the slowed group before we could react to her speed",
    "let my team know their Reyna dismissed through our Sage wall that was supposed to protect us and then leer-nearsighted our whole team through the wall on the other side",
    "tell my teammates their Phoenix hard-curveball-flashed A short on Haven and blaze-walled the exit of A short simultaneously, flashed and walled at the corner at the same time",
    "call out that their Gekko dizzy-flashed our retake team at B on Pearl and mosh-pit is landing at B default to deny the defuse while we are blinded",
    "tell my team their Breach fault-lined the top of A main on Split and his teammate Skye simultaneously hawk-flashed the same entry, double CC from two agents at one chokepoint",
    "warn them their Killjoy alarmbot tagged our Reyna at A link on Lotus making her vulnerable and nanoswarm activated on top of the alarmbot explosion for double damage",
    "let my team know their Sova shock-bolted A heaven on Ascent twice with a two-bounce lineup and fury is ready for whoever survives both shocks and stays in heaven",
    "tell my teammates their Chamber trademark slowed our Jett at B short on Bind after she dashed in and tour de force shot killed her while she was slowed from the trademark",
    "call out that their Neon overdrive beam fired at our KAY/O and he went down but null-command was active so he did not die, he is in the downed state waiting for a revive",
    "tell my team their Astra dissipated her B smoke to create a fake pulling our rotation off B and then activated real gravity well at A main where we all just rotated to",
    "warn my team their Fade haunt eye revealed our whole team clustered at B lobby on Pearl and nightfall is coming down the B main corridor directly at our revealed positions",
    "let my team know their Raze showstopper is aimed at A site from the air after a blast-pack jump and her boom-bot is rolling toward the spike position simultaneously",
    "tell my teammates their Viper snakebite hit the defuse spot at A on Breeze making the defuser vulnerable and her wall toggled back on to cut off our backup defusers",
    "call out that their KAY/O suppressed our Killjoy with zero-point and activated null-command, the lockdown stopped arming mid-windup and the entire ult reset on suppression",
    "tell my team their Omen from-the-shadows ulted to our spawn on Haven and dark-covered the spawn exit, one enemy is already behind us and the exit is smoked",
    "warn them our Breach rolling-thundered A long on Haven and their Waylay double-dashed through the entire rolling thunder cone before the concuss wave could hit her",
    "let my team know their Clove not-dead-yet fired and she got the assist from her own meddle that was ticking on our player, meddle assist counted toward the ten second requirement",
    "tell my teammates their Veto crosscut teleported behind our smoke at A main on Fracture and his chokehold landed right where we were standing inside the smoke",
    "call out that their Iso double-tapped an orb to get shield after killing our Sage and now has shield plus kill contract ready in the same round on a full HP body",
    "tell my team their Harbor storm-surged the A lobby push on Ascent and his cove shielded the spike at A default simultaneously, entry nearsighted and spike shielded at once",
    "warn my team their Cypher neural-theft ulted on our Breach body at A site on Lotus and full enemy positions revealed twice, the first wave shows they are all still on site",
    "let my team know their Jett blade-stormed our Viper who was toggling the wall at B main on Fracture and without Viper the wall dropped permanently for the rest of the round",
    "tell my teammates their Gekko thrash detained our Skye who was in the middle of sending her seekers, the seekers stopped mid-flight when she got detained and wasted the ult",
    "call out that their Deadlock annihilation pulled our Sova into the cocoon right as he fired the third beam of hunter's fury, the beam kept going but Sova is now being pulled to a kill point",
    "tell my team their Astra gravity-welled our whole A execute and cosmic divide went up behind the gravity pull to trap our team on site with no way back through the divide",
    "warn them their Skye regrowth healed their Neon to full during the overdrive window, Neon got a slide reset from the kill and is now back at 100 HP running overdrive with a fresh slide",
    "let my team know their Breach aftershocked our Gekko wingman as it was planting the spike on Lotus and the wingman died so the spike is still unplanted and our round plan collapsed",
    "tell my teammates their Vyse steel-garden fired on our post-plant hold at A on Haven and their Fade prowler was already homing on our terror trail in the same area simultaneously",
    "call out that their Tejo stealth drone detonated and suppressed our three-man B push on Pearl, their guided salvo is already aimed at B site and all three suppressed players cannot use abilities to dodge",
    "tell my team their Reyna empress fired right when our Killjoy lockdown started detaining, she got auto-devour from an orb inside the lockdown zone and is healing through the detain",
    "warn my team their Brimstone orbital struck the A site default plant on Ascent before our Sova recon even scanned the site, we have no plant position and no info simultaneously",
    "let my team know their Phoenix run-it-back marker is at A short on Haven and he is about to hard-curveball-flash A site from the marker position after respawning at full HP",
    "tell my teammates their KAY/O null-command is expiring in three seconds and we need to use all our abilities the instant suppression lifts to execute before they reset",
    "call out that their Neon relay-bolt hit two of us at mid on Ascent and their Breach fault-lined the same mid position right behind the relay bolt, double CC from two different agents",
    "tell my team their Yoru sent gatecrash tether to A and fakeout footsteps to A and then came out of dimensional drift right behind our B hold while we were watching A for both fakes",
    "warn them their Chamber trademark tracked our Yoru's real gatecrash teleport and tour de force was pre-aimed at the teleport arrival point, he was instantly killed at full HP on arrival",
    "let my team know their Iso contingency-walled A main on Split, kill-contracted our entry fragger through the wall, and won the contract so he came back at 100 HP with our entry dead",
    "tell my teammates their Astra was in astral form placing stars when our Neon rushed mid, we killed her body but she was in astral and her four stars are still active all round",
    "call out that their Viper pit is collapsing in eight seconds because she was forced out of it by our push, rush the defuse right now before she can re-enter and reset the timer",
    "tell my team their Deadlock gravnet pinned our Jett and she used tailwind dash to escape the net but the net also reduced her dash speed so she barely made it out and is now low",
    "warn my team their Clove ruse smoke went up at B on Fracture right as our Tejo armageddon was aimed at that exact spot, the dead smoke blocked visual of the airstrike zone",
    "let my team know their Waylay convergent paths ult hindered our entire retake team at B and then she double-lightspeed-dashed through the hindered team to kill the first two",
    "tell my teammates their Fade seize tethered our Brimstone in mid on Haven while he was on the tablet placing smokes, he cannot move or smoke and he will be decayed to low HP",
    "call out that their Gekko reclaimed both dizzy globule and wingman globule from B main on Ascent, both abilities are coming back in fifteen seconds for a second round execute",
    "tell my team their Sova recon hit all of us clustered at B hookah on Bind and the marking dart from the owl drone tagged our Jett at the same time, dual information on our whole team",
    "warn my team their Neon relay-bolted the B main entry on Pearl and immediately fast-lane walled the entry behind the stun, the entry is stunned and walled simultaneously",
    "let my team know their Veto interceptor destroyed our Sova recon bolt that was already in the air and our Skye hawk at the same time, both info abilities gone before they could scan",
    "tell my teammates their Breach rolling-thundered our retake at C on Haven and their Skye hawk-flashed the C long entry at the exact moment the thunder was landing on our team",
    "call out that their Killjoy nanoswarm activated at A default on Lotus right as their Astra pulled gravity well on the same spot, one player in the well is also getting nano-swarmed",
    "tell my team their Phoenix healed to full inside blaze wall on A short on Haven, curveball is already being thrown around the corner, and run it back timer is ticking with him at full HP again",
    "warn my team their Jett smoked A long on Haven with cloudburst and pushed the smoke with blade storm and an operator so she has vision through her own cloud while we cannot see her",
    "let my team know their Omen stepped B short on Bind and dark-covered B hookah window simultaneously from inside the step destination, he is inside the hookah with a smoke on the window",
    "tell my teammates their Raze boom-bot rolled through our Killjoy nanoswarm without triggering it since it is not an agent and showstopper is ready to rocket whoever shoots the bot",
    "call out that their Skye tiger concussed our Omen at B heaven on Split right as he was about to from-the-shadows teleport, the ult triggered during the concuss animation and teleported to a wrong destination",
    "tell my team their Tejo guided salvo hit A site on Pearl twice from outside the 45-meter range limit, but he was inside the limit when he aimed even though we were surprised by the angle",
    "warn my team their Vyse shear trapped our Reyna at B main on Fracture and she dismissed through the indestructible wall since dismiss makes her intangible, shear does not stop a dismiss",
    "let my team know their Viper wall blocks mid on Breeze and she acid-sniped our player crossing through the wall because snakebite can curve around the wall edge in that specific lineup",
    "tell my teammates their KAY/O frag-mented B lobby on Lotus and null-commanded right after the frag landed so the frag kept ticking through the null-command suppression pulse",
    "call out that their Clove picked up a kill with not dead yet, the ten seconds extended, and she used pick-me-up on the same body to go to 150 HP before the revive window even closed",
    "tell my team their Deadlock annihilated our Gekko right as thrash was being piloted, the cocoon pulled Gekko away and thrash had no pilot and kept moving in a straight line harmlessly",
    "warn them their Iso kill-contracted our Omen right after he used from-the-shadows, Omen teleported into the contract arena mid-arrival and the arena started with Omen disoriented from the teleport",
    "let my team know their Sage resurrection started on our Breach body at A site on Lotus but we killed the Sage mid-rez, the rez cancelled and Breach stayed dead",
    "tell my teammates their Fade nightfall hit us coming out of the B TP exit on Bind, we were completely exposed in the TP exit room and got decayed and trailed the moment we emerged",
    "call out that their Waylay beacon was destroyed by our Raze blast-pack explosion so she cannot recall anymore and she is exposed at B heaven on Split with her double dash already burned",
    "tell my team their Astra entered astral form to activate a star and our Neon rushed her physical body in astral form and killed it instantly before the star could fire",
    "warn my team their Jett has dash and blade storm and an op at A Long on Haven, that is three tools for the same angle and she cannot be dry-peeked under any circumstance",
    "tell my teammates their Killjoy lockdown fired at B site on Fracture while their KAY/O null-commanded mid, both ults are running simultaneously across both sites right now",
    "let my team know their Reyna got empress from our dead entry, dismissed through our molly, and is now at the back of A site at 150 overheal with four kills extending her timer",
    "tell my team their Viper has pit active at A on Lotus and their Killjoy turret is watching A link and nanoswarms are placed at A default, that site has three layers of denial",
    "call out that their Sova recon hit two of them at B main on Ascent and shock bolts are also landing at the revealed positions, info plus follow-up damage in a two-second window",
    "warn my team their Skye used guiding light twice on our A execute and tiger is also being piloted into A site, three animal-companion abilities on one execute route",
    "let my team know their Omen dark-covered B on Pearl, stepped into the smoke, and paranoia flew through the wall ahead of his step to clear the angle before he arrived inside the smoke",
    "tell my teammates their Clove rused a smoke dead at A on Split, not dead yet activated for the second time this match, and she is inside the dead smoke at 75 HP",
    "call out that their Breach rolling-thundered C Long on Haven and their KAY/O zero-pointed the Garage door at the same time, rolling thunder on C while abilities are suppressed in Garage",
    "warn my team their Veto evolution activated at B main on Corrode and his chokehold trapped our Fade who was about to haunt, immune to all our CC and Fade cannot use haunt inside the chokehold",
    "tell my team their Tejo armageddon line runs directly from A yard through A elbow on Corrode and stealth drone already suppressed our three players waiting at A elbow for the execute",
    "let my team know their Iso kill-contract arena ended with Iso winning, he came back at 100 HP to A main on Split while our four remaining teammates have no ults and are on pistols",
]
