ITEMS = [
    # ── ROTATE CALLS — simple / snap ──────────────────────────────────────────
    "rotate B",
    "rotate A",
    "everyone rotate B now",
    "hard rotate A, don't stop",
    "rotate mid, fast",
    "full rotate C, go",
    "slow rotate, don't commit yet",
    "rotate CT, use the halls",
    "rotate through mid, careful",
    "rotate B but hold for my call",
    "rotate now, they're committing",
    "everyone rotate off A, hit B",
    "rotate through garage",
    "rotate via link",
    "rotate C through waterfall",
    "B rotate, use B alley",
    "rotate off B, we're going A",
    "hard commit rotate, don't look back",
    "rotate quickly, spike's planted",
    "rotate but play for time, don't rush in",
    "rotate — I got info they're B",
    "rotate mid first then call it",
    "rotate C door, now",
    "rotate through sewers",
    "rotate up ramps",
    "tell them to rotate B",
    "tell the team rotate A right now",
    "yo tell them rotate, full rotate",
    "someone needs to rotate off that site",
    "rotate — they only have two left",

    # ── HOLD ROTATE / DON'T ROTATE ────────────────────────────────────────────
    "hold rotate, not confirmed yet",
    "don't rotate, I'm faking",
    "hold rotate — could be a bait",
    "nobody rotate, I got this angle",
    "stay, hold rotate, it's a split",
    "hold the rotate — we need one more piece of info",
    "don't rotate off B yet, wait",
    "tell them hold rotate, it might be a fake",
    "don't rotate away from information",
    "hold — could be a fake execute",
    "hold rotate, anchor the site",
    "don't rotate, we got two here still",
    "stay put, don't rotate blindly",
    "hold rotate until we see util",
    "no rotate, play where you are",

    # ── FAKE ROTATE ───────────────────────────────────────────────────────────
    "fake rotate B, make noise",
    "let's fake rotate A, then commit C",
    "walk toward B to fake, then come back",
    "fake the rotate — step past garage doors",
    "fake rotate mid, let them hear us",
    "run the fake rotate, they'll pull a defender",
    "fake A rotate, hit B clean",
    "make it sound like we're rotating",
    "let them think we rotated off",

    # ── THEY ROTATED / ENEMY MOVEMENT INFO ────────────────────────────────────
    "they rotated off B",
    "their whole team rotated A",
    "they rotated through mid",
    "one rotated, three still B",
    "they didn't rotate — A is undefended",
    "their Omen rotated CT, watch the flank",
    "they're rotating now, push before they get there",
    "two rotated B, one anchor on A",
    "they rotated early — fake worked",
    "they gave up mid and rotated",
    "their KJ rotated off site, retake window is open",
    "they're rotating through garage right now",
    "they rotated — hit the other site fast",
    "one of them rotated into mid, lurk watch",
    "they all rotated off C, hit C",
    "tell them their Jett rotated to A",
    "enemy Reyna rotated through CT",
    "they rotated B — A is open",
    "they rotated two to A, B should be soft",
    "their whole defensive rotation just broke",

    # ── SLOW PUSH / PLAYING SLOW ──────────────────────────────────────────────
    "slow push mid, burn their util",
    "play slow this round, don't force it",
    "slow it down, make them use smokes",
    "take it slow through main, make them commit",
    "we're going slow — absorb their kit",
    "play slow — let their smokes expire",
    "slow push A, we have time",
    "no rush, slow it out",
    "slow walk through hall, don't make noise",
    "take it methodical, clear every corner",
    "slow play — extract information first",
    "ease up, slow push into mid",
    "play slow on B approach, wait for support",
    "don't rush — slow through hookah",
    "grind it slow, they'll do something stupid",
    "slow it down, their util is still up",
    "play slow and look for the lurk to pop",
    "slow rotate, don't sprint",
    "slow walk this, no footsteps",
    "tell them slow push B, walk it in",

    # ── RUSH CALLS ────────────────────────────────────────────────────────────
    "rush B, full send",
    "five rush A, go now",
    "rush mid before they set up",
    "rush B on my mark, go",
    "eco rush A, all in",
    "full team rush B — three seconds",
    "rush hookah into B",
    "rush short into A, don't slow",
    "rush ramps, all five",
    "rush the site before utility lands",
    "rush C through short, no smoke needed",
    "judge rush B, go",
    "speed boost rush, Neon lead",
    "rush A main, shock them",
    "tell them rush B, no hesitation",
    "full rush now — they have no util",
    "rush A before KJ sets up",
    "rush through garage, catch them rotating",

    # ── FAST ROTATE ───────────────────────────────────────────────────────────
    "fast rotate B, skip the info",
    "fast rotate — we know they're there",
    "hard fast rotate A now",
    "sprint rotate, no time to think",
    "fast rotate off B, don't slow down",
    "fast rotate CT corridor, go",
    "fast rotate through link",
    "fast rotate mid and drop down",
    "full speed rotate, spike's going down",
    "fast rotate — 20 seconds left",

    # ── LURK CALLS ────────────────────────────────────────────────────────────
    "someone lurk mid while we hit A",
    "Reyna lurk through CT",
    "I'm lurking B, send it A",
    "lurk through sewers, pick up CT",
    "one lurk on short, rest hit B",
    "their lurker is coming, watch behind",
    "I'm lurking garage — don't call the execute yet",
    "play lurk on mid link",
    "lurk the flank, cut their rotation",
    "tell them lurk through sewer while we execute B",
    "lurk from spawn side, get their rear",
    "lurking A short — give me 10 seconds",
    "one of them is lurking, I can feel it",
    "their Yoru is lurking somewhere, watch flanks",
    "tell the team one lurk B link, rest execute A",
    "their Omen's been lurking mid this whole half",
    "lurk through hall into their CT, cut rotations",
    "that guy is definitely lurking behind us",
    "lurk the B site connector, get their rotate",
    "lurk it — don't engage, just watch and report",

    # ── FLANK CALLS ────────────────────────────────────────────────────────────
    "watch the flank",
    "flank coming from short",
    "they're flanking through mid",
    "someone is flanking us from behind",
    "flank watch on my right",
    "their Jett is flanking via CT",
    "we're getting flanked — someone check",
    "flank through their spawn, cut em off",
    "tell them watch for the flank from B link",
    "two flanking through lower mid",
    "send one to flank while we execute",
    "flank right, kill the anchor",
    "don't get flanked — clear behind you",
    "their lurker is setting up the flank right now",
    "flank from catwalk into their retake",
    "getting flanked from tree, watch A link",
    "flank the B retake from alley",
    "they pulled a flank — abort execute",
    "one of them flanked us through market",
    "flanked — two from behind, one in front",

    # ── FALLING BACK / PULLING BACK ────────────────────────────────────────────
    "fall back, don't fight it",
    "pull back — their util is too heavy",
    "fall back to spawn, reset",
    "don't peek that, fall back",
    "falling back off A, get back to lobby",
    "pull off, save your gun",
    "fall back mid, give up the space",
    "back off, let them push",
    "fall back and retake on information",
    "retreat — they have ults",
    "back up, their Breach is ulting",
    "pull back B — too much pressure",
    "fall back now, spike can handle itself",
    "back off A and play for retake",
    "pull out of mid, give them the space",
    "fall off garage, they have the numbers",
    "back out through sewer",
    "retreat to short, hold from there",
    "pull back CT side, don't over-extend",
    "fall back — we're two down",

    # ── ANCHORING ──────────────────────────────────────────────────────────────
    "anchor A while we rotate",
    "someone anchor B site, give us time",
    "anchor mid and buy us 10 seconds",
    "anchor the site, stall them out",
    "I'm anchoring, rotate everyone else",
    "KJ can anchor B solo",
    "anchor CT, don't rotate yet",
    "anchor with info — tell us where they stack",
    "anchor and play for the trade",
    "you anchor A, we rotate and come back",
    "anchor B — you have two nanos and the turret",
    "stay and anchor, make them work for it",
    "anchor until we hear from mid",
    "anchor that site, do not rotate",
    "anchor A, I'll check mid and come A link",

    # ── POSITIONING / TAKING SPACE ────────────────────────────────────────────
    "take mid control first",
    "we need to control mid before anything",
    "fight for mid top early",
    "take catwalk before they do",
    "contest catwalk, don't give it free",
    "take tree control — that opens everything",
    "contest garage, don't let them take it",
    "push mid, take the space",
    "we need short control",
    "take A lobby before they counter",
    "fight for the orb early",
    "take B lobby control — cut off their rotate",
    "contest elbow, push them off",
    "fight for mid link before committing site",
    "take top mid, own it",
    "take market early, then B execute",
    "control mid stairs first",
    "take A ramps before they set up heaven",
    "win B main before touching site",
    "take the space, don't let them give it for free",
    "push for mail room control",
    "fight for the wood doors early",
    "take the garage, it controls both B and C",
    "take B pillars — that's our lane to site",
    "take the mound, control the C door",
    "contest mid bottom then decide",
    "control the tiles, then cut mid",
    "take hell side after clearing heaven",
    "fight for A security before they wall you out",
    "take double doors before they can smoke it",

    # ── GIVING SPACE / CONCEDING ──────────────────────────────────────────────
    "give up mid this round",
    "give them mid, we play passive",
    "concede the space, pull to site",
    "give them A long, hold from site",
    "give up the space, play for retake",
    "let them have mid — we info play",
    "give it up, play from far",
    "concede short, play back",
    "don't fight for it — too expensive",
    "give them the lobby, play B default",
    "give up the map, play slow",
    "give B main, fall to site",

    # ── ENTRY / SITE TAKE ─────────────────────────────────────────────────────
    "entry in three, flash coming",
    "I'm entrying, support me",
    "entry B on my go",
    "who's the entry this round?",
    "entry A main, support on ramps",
    "Jett entry B, rest follow",
    "entry through hookah",
    "Raze entry with satchel",
    "entry off my flash — go",
    "let Phoenix entry, he has flash",
    "entry A short, second player follow fast",
    "tell them entry B main now, smokes are up",
    "entry on smoke — go",
    "Neon entry, you're fastest",
    "push entry through mid link",
    "entry A from two angles simultaneously",
    "entry B lobby — they have no util left",

    # ── COMMIT / ABORT ─────────────────────────────────────────────────────────
    "commit A, we're going",
    "commit B, don't second-guess",
    "commit now — smokes are in",
    "abort, pull back",
    "abort execute — too many",
    "abort A, hit B",
    "commit through mid, we have numbers",
    "go — commit, don't slow up",
    "abort the push, they're stacked",
    "commit off this flash, now",
    "abort — I heard their ult charge",
    "send it — full commit B",
    "late commit off the smoke, go",
    "abort and reset — we have time",
    "commit C on the door sound",
    "commit A link side, now",

    # ── SPLIT ATTACKS ─────────────────────────────────────────────────────────
    "split A — two main two short",
    "split hit B — three main one link",
    "split the site, two angles",
    "split A from lobby and sewer",
    "mid then split — catwalk and tiles",
    "pinch them — hit from both sides",
    "split C — mound and main",
    "split B pillars — two lane two link",
    "split from A link and A main simultaneously",
    "two go A main, two flank through mid to tree, split A",
    "split them on B — one comes garage, rest hit main",
    "tell them split B — three main and two from short",
    "split the A execute, don't stack",

    # ── DEFAULT ROUND CALLS ────────────────────────────────────────────────────
    "let's default this round",
    "play default — gather info first",
    "default it, don't force",
    "play default, let's see where they set up",
    "go default, no commit",
    "default and adapt",
    "play a soft default and pivot",
    "default spread — we need info",
    "slow default, gather information",
    "let's default and find their positions",
    "play info round, default",
    "default — nobody commit until we have something",

    # ── RETAKE CALLS ───────────────────────────────────────────────────────────
    "retake B, they're planting",
    "retake A — two left on site",
    "full retake, everyone B",
    "retake from CT, cross spawn",
    "retake — smoke up before we go in",
    "retake A from link and heaven",
    "retake B from alley and garage",
    "retake through B short into site",
    "retake — play crossfire",
    "retake C — use waterfall side",
    "hold retake position, wait for me",
    "retake from two angles, don't straight-push",
    "retake B — smoke their corner first",
    "retake A — sage wall's already down",
    "retake now — they're still planting",
    "retake — their Jett dashed in, she might flank",
    "retake from ramps and CT simultaneously",
    "let them retake — we play around spike",
    "retake but play off each other, don't die alone",
    "retake B now, we have the numbers",
    "retake from catwalk angle — clean crossfire",
    "tell them retake B but watch for the lurker on link",

    # ── PLAY STYLES — aggressive vs. passive ───────────────────────────────────
    "play aggressive on mid early",
    "play passive this round — no peeking",
    "play aggressive A lobby, get early picks",
    "play passive on B, hold angles",
    "play aggressive CT, catch their rotation",
    "play passive and let them come to us",
    "play off angles — don't give information",
    "be aggressive on short, catch them off-guard",
    "play passive B, anchor and info",
    "play aggressive ramp side, deny heaven",
    "play passive for the retake",
    "play aggressive mid but don't over-extend",
    "play passive on link, let them push",
    "play aggressive on C main early, take the mound",
    "play passive — we don't need to peek anything",

    # ── CROSSING / MOVEMENT ────────────────────────────────────────────────────
    "cross mid on smoke",
    "don't cross until smoke is up",
    "cross main fast, hug left wall",
    "cross B main on my wall",
    "crossing mid — cover me",
    "cross short, single file",
    "cross via CT connector",
    "don't cross mid without a flash",
    "cross fast — smoke's already fading",
    "cross B — they have no util left",
    "cross the courtyard carefully",
    "cross A long on the flash count",
    "crossing hookah — watch from spawn",
    "cross through the sewer",
    "cross garage on my smoke",
    "cross mid top — orb side cover",
    "cross B link — I'll flash for you",
    "cross quickly, smoke's at five seconds",
    "cross via the drop, catch them off guard",

    # ── FOOTSTEP / AUDIO INTEL ─────────────────────────────────────────────────
    "I hear footsteps B main",
    "footsteps mid — two players",
    "they're walking it — shift-walking B",
    "I hear them through the door",
    "footsteps A long, they're pushing",
    "they're walking mid, no sprint",
    "they're walking — they know we're here",
    "I hear footsteps above me, heaven",
    "I hear them breaking the wall",
    "footsteps in garage — they have it",
    "they opened the door — I heard it",
    "footsteps top mid — they contested",
    "they're walking the water section — don't rush",
    "I hear footsteps on ropes",
    "footsteps CT side — rotate coming",
    "I hear a player on my right",
    "their footsteps gave them away",
    "they're walking — don't play for sound",
    "footsteps near spike — they're defusing",
    "I hear someone above me on heaven",

    # ── SCOUT / INFO-GATHER MOVEMENT ───────────────────────────────────────────
    "scout mid before we commit",
    "peek for info, don't die",
    "jiggle peek A main for info",
    "shoulder peek and pull back",
    "quick peek to see if they set up",
    "dry peek B short for info",
    "scout with the drone before we push",
    "send the dog in first, get info",
    "peek mid on my flash",
    "jiggle garage before crossing",
    "scout the lobby — we don't know their setup",
    "peek heaven, see if they're there",
    "shoulder peek link before running it",
    "don't commit, just peek for a count",
    "info peek B long — stay safe",

    # ── STACKING ──────────────────────────────────────────────────────────────
    "stack B this round",
    "three B, two A",
    "stack A — four on A one fake B",
    "stack mid, nobody commits site",
    "stack C — four players",
    "stack garage side",
    "stack A lobby and wait for their push",
    "stack B with four, anchor A with one",
    "let's stack three mid and two B",
    "stack ramps side this round",
    "stack the site they keep hitting",
    "stack B but one lurks mid",
    "tell them stack A — they keep going there",
    "double stack B with nanos and turret",

    # ── TIMING CALLS ─────────────────────────────────────────────────────────
    "we have 30 seconds, push now",
    "force it — running out of time",
    "plant quick, 20 seconds left",
    "don't have time to retake",
    "spike at 30 — let it blow",
    "burn their time first",
    "they're burning time, watch for late rush",
    "we have time — don't force",
    "play for time, spike detonates in 20",
    "plant fast, no time to clear",
    "time is running out, commit now",
    "play for time — we don't need kills",
    "15 seconds — plant or save",
    "they're timing us out, go now",
    "late round — play for picks not site",
    "don't rush — 40 seconds left, plenty of time",
    "commit before the smoke expires",
    "their smoke is fading — push",
    "smoke fading on main, go before it's clear",
    "one smoke left, push on its last seconds",
    "their molly's about to expire, go",
    "wait for their flash to go — then cross",
    "wait 5 seconds for the slow orb to fade",

    # ── PIVOT / MID-ROUND ADJUSTMENT ──────────────────────────────────────────
    "pivot to B — they're stacked A",
    "adjust, go B",
    "pivot off A, commit C now",
    "adjust to the information — go B",
    "pivot through mid, hit B clean",
    "adjust mid round, switch to A",
    "pivot — they're not rotating fast enough",
    "adjust the play, hit the open site",
    "pivot off C, go B via door",
    "we need a mid-round adjustment, go A",
    "pivot and explode B — they're all A",
    "adjust to B based on what we're hearing",
    "abort and pivot, fresh plan",
    "quick pivot — their lurker gave it away",

    # ── RESET / ABORT / REGROUP ────────────────────────────────────────────────
    "reset — pull back and start over",
    "full reset, back to spawn",
    "abort and reset, don't force",
    "reset the round, play late",
    "we need to reset — too much pressure",
    "abort — too many of them are up",
    "reset position and regroup",
    "pull off and reset — their utility is up",
    "abort A, reset, play B next",
    "full reset — gather in spawn",
    "reset mid round, don't die randomly",
    "abort the execute — their ult is ready",
    "reset and play for picks",

    # ── LATE ROUND / CLUTCH MOVEMENT ──────────────────────────────────────────
    "play late round — look for picks",
    "spread out and look for 1v1s",
    "late round — don't group up",
    "play for picks — let them come to you",
    "late rotation, last man anchor",
    "spread and hunt",
    "last one alive — play for time",
    "play crossfire post-plant, two angles",
    "play off spike — don't get found",
    "late round lurk, get their last man",
    "last alive, play around spike",
    "spread post-plant and play time",
    "clutch — play around the spike position",
    "post-plant crossfire, two players",
    "play for the tap-defuse bait",
    "hold two angles — watch both ends",

    # ── MAP-SPECIFIC ROTATIONS — Ascent ───────────────────────────────────────
    "rotate through market to B",
    "rotate B via market stairs",
    "rotate A through garden and tree",
    "rotate A via catwalk",
    "take catwalk to tree, flank A from behind",
    "rotate through tiles to B main",
    "rotate CT to garden, then A",
    "rotate A from tree side — cut their CT rotation",
    "rotate through catwalk cubby",
    "close the B door and rotate A",
    "break the mid panel, rotate through",
    "rotate B via screens on CT side",
    "push catwalk for A split",
    "market side rotate — hit B from stairs",

    # ── MAP-SPECIFIC ROTATIONS — Haven ────────────────────────────────────────
    "rotate C through garage",
    "rotate B from A link side",
    "rotate A via the sewer",
    "rotate garage to C short",
    "rotate B to C through CT",
    "rotate A through nest position",
    "rotate C — open the door from nest",
    "rotate A link into B for a pinch",
    "rotate through courtyard to B",
    "rotate off A, go C long",
    "rotate C through garage — they own mid",
    "rotate mid doors — control B and C",
    "rotate C link into B for crossfire",
    "rotate via CT connector — all three sites",

    # ── MAP-SPECIFIC ROTATIONS — Split ────────────────────────────────────────
    "rotate A via mid vent rope",
    "rotate B from A heaven via CT",
    "rotate mid sewer to A lobby",
    "rotate up the ropes to A tower",
    "rotate B heaven from CT stairs",
    "rotate via top mid to B link",
    "rotate A from below, sewer into main",
    "rotate mid to mail, cut their push",
    "rotate A from B through the back CT",
    "rotate B via B alley",

    # ── MAP-SPECIFIC ROTATIONS — Lotus ────────────────────────────────────────
    "rotate B via A link",
    "open the C door and rotate B",
    "rotate through C door to B main",
    "rotate B via A link after breaking the wall",
    "break the B wall — rotate through",
    "rotate C through waterfall and hall",
    "rotate A from C via link",
    "rotate A via the silent drop",
    "rotate C door — let the sound tell them",
    "rotate B through A link after we break the wall",
    "open A door, rotate through tree",

    # ── MAP-SPECIFIC ROTATIONS — Pearl ────────────────────────────────────────
    "rotate B via mid connector",
    "rotate A through A art",
    "rotate mid doors to B link",
    "rotate B via defender water side",
    "rotate A via art flanking from mid",
    "rotate from A flowers to B via connector",
    "rotate B through records to tower",
    "rotate A via mid shops and art",
    "rotate fast — no mechanics, it's all footwork",
    "rotate B hall side after clearing mid",

    # ── MAP-SPECIFIC ROTATIONS — Breeze ───────────────────────────────────────
    "rotate A via A hall",
    "rotate B through mid elbow",
    "rotate through arches to B",
    "rotate A hall to site — metal doors",
    "rotate B via B tunnel",
    "rotate mid — B elbow to B main",
    "rotate A via wood doors from top mid",
    "rotate B from cannon side",
    "rotate through A bridge on defender side",
    "mid nest rotate — needs ability to get up",

    # ── MAP-SPECIFIC ROTATIONS — Fracture ──────────────────────────────────────
    "zip to A side, rotate fast",
    "use the zipline — flip and hit A",
    "rotate B via B link from CT",
    "rotate A via A link from defender spawn",
    "rotate — take the zip to the other side",
    "fake A side, zip to B",
    "rotate B canteen — cut the push",
    "rotate A link into a pinch",
    "take the zip, come in from behind",
    "zip across and rotate to the open site",

    # ── ENEMY MOVEMENT READS ───────────────────────────────────────────────────
    "they're pushing A main hard",
    "they're rushing B, full team",
    "they defaulted — no commitment yet",
    "they're slow pushing mid",
    "their whole team is A, rotate now",
    "they gave up B — hit B",
    "they're stacking A every round",
    "they're doing the same rotate every half",
    "their Jett is pushing aggressive lobby",
    "they're holding passive this time",
    "they're sitting at default — no rush",
    "they're hunting mid — fight for it or give it",
    "their lurker broke the pattern — check behind",
    "they rotated way too fast, it was a bait",
    "they keep hitting B so let's overload B",
    "they gave us mid for free — something's wrong",
    "their Cypher set up in that exact spot again",
    "they're burning time — late round aggression incoming",
    "they've been stacking C all game",
    "their pattern is A fake B — call it before they do",

    # ── PLAYER/ROLE-TAGGED MOVEMENT CALLS ──────────────────────────────────────
    "Jett push B main, we'll follow",
    "Neon you're fastest, lead the rush",
    "Raze satchel up to heaven",
    "Reyna take the duels on short",
    "Yoru gate B — fake their rotation",
    "Breach fault line then we push",
    "Skye dog into A main first",
    "Sova drone mid before we commit",
    "KAY/O knife, then we push",
    "Gekko wingman scouting ahead",
    "Fade haunt into B site, then we go",
    "Tejo drone the angle before we push",
    "Omen teleport behind and catch their rotate",
    "Clove smokes C main, then we move",
    "Viper wall B main, we rotate behind it",
    "Astra pull on their rotate, then we go",
    "Harbor wall for the push, we follow",
    "Cypher cam watching their rotate",
    "KJ anchor B — everyone else rotate A",
    "Sage wall the ramp — slow their push",
    "Chamber op'd up on the long — cover our rotate",
    "Deadlock grav net the rotate path",
    "Vyse shear on the rotate corridor",
    "Veto interceptor on the flank route",
    "Waylay refract through — get the fast angle",
    "Iso push through short — I'll hold mid",
    "Phoenix run it back to info-gather",

    # ── MID-ROUND INFO-BASED PIVOT EXAMPLES ────────────────────────────────────
    "they're two A one mid two B — hit B hard",
    "we know where two are — find the lurker before rotating",
    "three confirmed B — rotate fast, get there before plant",
    "one anchoring each site — hit mid link and split",
    "their lurker is unaccounted — wait before rotating",
    "four confirmed A — rotate B clean, no defenders",
    "we have mid — let's threaten both sites and pick",
    "three B is confirmed — that's not enough to hold with util",
    "after this pick they'll rotate — beat them there",
    "two mid on info — that means one site is soft",
    "contact A — don't panic rotate yet, could be distraction",
    "they smoked B but only two pushed — something's off",
    "five B rush — they go every pistol — stack it",

    # ── POST-EXECUTE POSITIONING ──────────────────────────────────────────────
    "spread out on site, don't stack",
    "clear every angle before planting",
    "one unaccounted — find them before we plant",
    "spread across site, play all angles",
    "don't cluster — they'll nade us",
    "hold the retake — play off spike",
    "post-plant crossfire — two positions",
    "hold B from two corners — crossfire their retake",
    "don't over-extend on site, hold near spike",
    "check heaven — defender might be there still",
    "don't peek, wait for retake and play slow",
    "hold from site after plant — don't push out",
    "post-plant — let them retake into you",
    "play around spike position, don't wander",
    "watch the flank after plant — their lurker is live",
    "post-plant — one watches main, one watches link",
    "play off site after plant, don't give information",
    "hold from two angles and play for time",
    "spread post-plant, watch all entry points",

    # ── MIXED REGISTER — casual phrasing ──────────────────────────────────────
    "yo rotate B, let's go",
    "bro just rotate, stop holding",
    "we need to play faster — stop waiting",
    "can we just commit something?",
    "stop playing so passive and go",
    "we're burning time standing around",
    "let's actually move — rotate",
    "stop peeking random and just rotate",
    "we keep losing mid, let's give it up and play site",
    "stop overthinking it — rotate B",
    "just rotate fast and we beat them there",
    "we're too slow, they set up every round",
    "somebody needs to anchor, rest rotate",
    "can we push mid for once instead of waiting",
    "let's just rush this — no more slow plays",
    "stop lurking and help us commit",
    "we keep getting flanked — someone watch mid",
    "just go, stop second-guessing",
    "we need to move faster on the rotation",
    "bro push aggressive or stay out of mid",

    # ── MIXED REGISTER — formal/IGL phrasing ──────────────────────────────────
    "full team slow push mid, don't give information unnecessarily",
    "rotate B and play for the retake window",
    "hold the rotate until we have confirmation",
    "anchor A with information, everyone else B",
    "play off the lurk — don't commit until he pops",
    "methodically clear and rotate, don't overextend",
    "the execute window is open — commit now or lose it",
    "rotate clean — no random duels mid-rotation",
    "use the rotation to set up a split execute",
    "we rotate B but watch for the counter-lurk",
    "do not rotate without information — stay put",
    "anchor with utility, stall them and rotate off the back",
    "rotate but do not give them free picks mid-rotate",
    "stagger the rotation — don't all go at once",
    "play asymmetric — one anchor, four rotate hard",

    # ── ANTI-STRAT / PATTERN BREAK ────────────────────────────────────────────
    "they know we keep rotating late — go early this time",
    "they anti-stratr our B rotate — fake it this round",
    "they've been catching us rotating through mid — use CT",
    "they camped our rotate route — change it",
    "anti-strat their stack — fake B then commit A",
    "they know our pattern — switch it up",
    "they've been setting for our catwalk move — fake it",
    "break the pattern — go somewhere we haven't hit",
    "they're reading our rotations — go a different route",
    "anti-strat the anchor — rush before he sets up",

    # ── INFORMATION ABOUT OWN MOVEMENT (first-person style) ────────────────────
    "I'm rotating B now",
    "I'm on my way to A",
    "rotating through mid",
    "I'm flanking from short",
    "I'm going through garden to A",
    "rotating via CT right now",
    "I'm pushing mid for info",
    "going up ropes to heaven",
    "I'm lurking behind them",
    "I'm rotating to B through link",
    "I'm going A — tell them to flash me in",
    "I'm slow pushing main right now",
    "crossing mid on the smoke",
    "I'm falling back, saving gun",
    "I'm anchoring B, rest rotate",
    "I'm in position, call when ready",
    "I'm mid for control, need a push",
    "holding catwalk right now",
    "I'm sitting at the T in mid, watching both ways",
    "I'm B site anchor — rotate the others",

    # ── NEGATIVE-INFO MOVEMENT CALLS ──────────────────────────────────────────
    "mid is clear, no contact",
    "nothing B main, they gave it",
    "A lobby is empty — they're not here",
    "no contact short — they're not there",
    "mid is uncontested — take it",
    "B long is empty, pushed free",
    "they gave mid for free — suspicious",
    "A main is open, no one's there",
    "no resistance on ramps — they're passive",
    "nothing in catwalk, free movement",
    "mid is clear — no defenders early",
    "B entrance has no one — they're passive",
    "no sound from A long — they're not contesting",
    "garage is empty — rotate through free",
    "they're not fighting for mid this half",

    # ── MISC BROADER MOVEMENT CONCEPTS ────────────────────────────────────────
    "play for picks, don't force a site",
    "spread the map, gather information first",
    "we need one player to identify the lurker",
    "play off the information before committing",
    "win the early fight mid then pick a site",
    "don't bunch up — give us options",
    "stagger the push so we don't all die to one util",
    "play the map, not the scoreboard",
    "keep them guessing — vary the rotate routes",
    "use CT side to cut their rotation timing",
    "play from distances where you have the advantage",
    "abuse their slow rotation — hit fast",
    "play off their economy — they can't have a plan",
    "hold two areas at once — they can't rotate to both",
    "move as a unit until mid then split",
    "use sound — let them hear you one place, go another",
    "play the space, not the angle",
    "force a reaction — then punish the rotation",
    "don't let them dictate the pace, push them off",
    "keep one player alive mid at all times for info",
]
