"""Spike plant / defuse relay test corpus.

KIND: relay
Domain: All utterances that a streamer says to relay spike-related information
  to teammates -- plant calls, defuse calls, post-plant holds, retake calls,
  spike carrier management, timer countdown, fake defuse bait, ninja defuse,
  Wingman plant/defuse, and negative / false-relay shadow cases.

Register mix:
  - Snap (terse, literal): "planting", "spike A", "defusing", "30 seconds"
  - Extended relay: strategy, post-plant positioning, retake reads
  - Ability-linked: Wingman planting, Gekko defuse, KJ nanoswarm on spike
  - Compound: spike position + timer + post-plant angle in one breath
  - Ownership: "I'm planting", "he's defusing", "they're on the spike"
  - Urgency gradients: calm plant → frantic "he's almost done"
  - Negative/false-relay: private narration that LOOKS like a relay but is NOT
  - Questions TO Ultron (kind=question): a handful for contrast
"""

ITEMS = [
    # ------------------------------------------------------------------ SNAP PLANT CALLS
    "planting",
    "I'm planting now",
    "planting A",
    "planting B",
    "planting C",
    "spike down",
    "spike A",
    "spike B",
    "spike C",
    "planted",
    "spike is down",
    "spike down A",
    "spike down B",
    "spike down C",
    "planted A default",
    "planted B default",
    "planted C default",
    "planted for main",
    "planted for CT",
    "planted for heaven",
    "safe plant, spike A",
    "spike A, planted safe",
    "open plant A",
    "open plant B",
    "quick plant, spike B",
    "fast plant A",
    "I'm going for a fast plant",
    "spike down, play post-plant",
    "planted, play off me",
    "spike down, spread out",
    "spike down, hold your angles",
    "planted, watch for the retake",
    "spike A gen",
    "spike A generator",
    "spike A behind gen",
    "planted at generator",
    "planted in front of dice",
    "spike A heaven side",
    "spike behind the box A",
    "planted at triple box B",
    "planted at default B",
    "spike B triple",
    "planted behind workshop",
    "spike B back site",
    "planted at logs side B",
    "spike at the pyramids A",
    "planted behind right pyramid",
    "spike A orange container side",
    "planted at mid-pyramid A",
    "spike B Ascent, triple box",
    "planted behind generator, play off tree",
    "planted for A main angle",
    "spike at the hut A",
    "planted near hut, lotus A",
    "spike down at A hut",
    "planted default A lotus",
    "spike at double box A",
    "planted A site pillar side",
    "spike near platform C",
    "planted at C platform lotus",
    "planted at B default lotus, middle of site",
    "spike B stairs side",
    "planted in the pit B",
    "spike B pillars side",
    "spike at the radianite boxes B",
    "planted at radianite, pearl B",
    "spike B ramp side pearl",
    "spike near B screen pearl",
    "planted behind cafe A pearl",
    "spike A vending machines",
    "planted behind B hall side",
    "spike A dugout side",
    "spike Haven A default",
    "planted Haven A, generator",
    "spike Haven B gong side",
    "planted B back haven",
    "spike C platform haven",
    "planted C default haven",
    "spike C logs haven",
    "planted B default split",
    "spike B back site split",
    "spike A default split, terminal",
    "planted backsite A split",
    "spike at the terminal",
    "planted near hologram box A split",
    "spike A ascent, behind dice",
    "planted near the rafters A ascent",
    "planted at B boathouse ascent",
    "spike B workshop",
    "planted B lane ascent",
    "spike A breeze, right pyramid",
    "planted A left pyramid",
    "spike B breeze default",
    "planted B tunnel side breeze",
    "spike at B nest breeze",
    "spike fracture A top site",
    "planted A heaven fracture",
    "planted A bottom fracture",
    "spike fracture B arcade side",
    "planted B main fracture",
    "spike fracture B generator",
    "planted near B canteen fracture",
    "need a plant, I'm covering",
    "someone plant, I'm watching main",
    "plant the spike, I'll cover heaven",
    "plant it quick, 40 seconds left",
    "go plant, I've got the angle",
    "plant now, smokes are fading",
    "plant while the smoke holds",
    "plant through the flash, go",
    "wingman is planting, watch the site",
    "Gekko's wingman handling the plant",
    "wingman plant on A, cover it",
    "wingman planting B, hold off the retake",
    "let wingman plant, you get the angle",

    # ------------------------------------------------------------------ SPIKE CARRIER CALLS
    "who has spike",
    "who's got the spike",
    "which one of you has spike",
    "I have spike",
    "I got it",
    "I'm carrying spike",
    "I have the bomb",
    "drop spike, I'll plant",
    "drop it, let me plant",
    "give me spike, I'll handle the plant",
    "drop spike on me",
    "pick up spike",
    "grab the spike",
    "someone pick up the bomb",
    "spike on the ground at A main",
    "spike dropped at B main",
    "spike on the floor at lobby",
    "I dropped spike at B, someone grab it",
    "spike is at CT, pick it up",
    "don't forget spike, someone grab it",

    # ------------------------------------------------------------------ TIMER / COUNTDOWN CALLS
    "30 seconds on the spike",
    "spike at 30",
    "30 seconds left on bomb",
    "20 seconds on the spike",
    "spike at 20",
    "15 seconds on the bomb",
    "10 seconds left",
    "spike detonates in 10",
    "bomb goes off in 10 seconds",
    "5 seconds, let it go",
    "5 seconds, don't defuse",
    "save it, it's blowing",
    "don't risk the defuse, 5 left",
    "let the spike blow, 4 seconds",
    "40 seconds on spike",
    "spike has 40",
    "spike A, 35 seconds",
    "planted spike, 45 seconds left",
    "spike B, 50 seconds",
    "we have 50 seconds on spike",
    "spike down, you have time",
    "45 on the clock, hold angles",
    "spike ticking, 25 left",
    "bomb is at 25, retake fast",
    "25 seconds guys, push the retake",
    "we're running out of time, 15 seconds",

    # ------------------------------------------------------------------ POST-PLANT POSITIONING CALLS
    "play post-plant",
    "play for time",
    "play off the spike angle",
    "hold the defuse",
    "watch the spike",
    "cover the spike",
    "hold near spike",
    "don't fight, play around spike",
    "play crossfire on the spike",
    "set up crossfire at A",
    "two angles on spike, play crossfire",
    "play around the bomb, don't peek",
    "play slow, let them come to you",
    "sit on it, don't peek",
    "let the timer run, don't take unnecessary fights",
    "hold your angles, spike is doing the work",
    "post-plant, hold main and tree",
    "post-plant A, hold garden and heaven",
    "hold CT and tree, spike A ascent",
    "one in heaven, one at tree, spike A",
    "spike A gen, play tree and garden crossfire",
    "one on B stairs, one in workshop, spike B ascent",
    "spike B, hold market and CT stairs",
    "hold workshop and alley, spike B",
    "spike A haven, hold heaven and short",
    "post-plant A haven, one in hell, one on heaven",
    "spike B haven, play the gong angle",
    "spike C haven, hold from platform",
    "hold C platform and logs, spike C",
    "spike B split, hold from back pillar",
    "post-plant B split, watch tower and CT",
    "spike A split, hold from rafters",
    "one on a rafters, one watching terminal, spike A split",
    "post-plant pearl B, hold ramp and hall",
    "spike B pearl, play ramp and B link crossfire",
    "spike A pearl, hold from dugout",
    "post-plant A pearl, dugout and flowers angle",
    "hold off A flowers, spike down pearl",
    "spike B lotus, hold from upper",
    "post-plant lotus B, upper and stairs crossfire",
    "spike A lotus, play off hut",
    "hold the stairs and hut, spike A lotus",
    "post-plant lotus C, hold from bend",
    "spike C lotus, play bend and hall crossfire",
    "spike A breeze, play the pyramid angles",
    "post-plant breeze A, hold from back site",
    "spike B breeze, hold from the nest",
    "play nest angle, spike B breeze",

    # ------------------------------------------------------------------ DEFUSE CALLS (OWN TEAM)
    "defusing",
    "I'm defusing",
    "sticking it",
    "I'm sticking the defuse",
    "full defuse, don't interrupt me",
    "going for the full stick",
    "I got the defuse",
    "I'm on the spike",
    "I can defuse, cover me",
    "cover me I'm on the bomb",
    "cover me, defusing now",
    "push me, I'm defusing",
    "someone cover, I'm going for the defuse",
    "can someone flash so I can defuse",
    "need a flash, going for defuse",
    "smoke the angle, I'll defuse",
    "smoke CT, I'm defusing",
    "smoke main, I'm going for the defuse",
    "need smokes, I'm defusing A",
    "molly the spike, I'll cover",
    "tap spike, I'll swing",
    "I'll tap it, you swing",
    "tap it first, bait them out",
    "fake defuse, he's gonna peek",
    "half defuse, see if he peeks",
    "going for ninja defuse",
    "ninja defuse attempt",
    "I'm going for the sneaky defuse",
    "silent defuse, no one knows I'm here",
    "nobody's watching, I can ninja this",
    "they don't see me, I'm going for it",
    "defused",
    "defuse complete",
    "we got the defuse",
    "spike defused",
    "bomb defused, we win",

    # ------------------------------------------------------------------ ENEMY DEFUSING CALLS
    "they're defusing",
    "he's defusing",
    "someone's on the spike",
    "enemy defusing",
    "defuse started",
    "they started the defuse",
    "defuse happening A",
    "defuse at A",
    "they're defusing A",
    "defusing B",
    "they're on the bomb",
    "he's going for it, push him",
    "they're tapping it",
    "he tapped it, he's baiting",
    "tap spike, bait",
    "it's a fake defuse, don't peek",
    "fake defuse, hold your position",
    "don't peek, it's a bait",
    "he started then stopped, it's a bait",
    "they half-defused, be careful",
    "he's almost done, push now",
    "defuse almost complete, go now",
    "he's about to finish the defuse",
    "he's got 2 seconds left on defuse, rush him",
    "they're gonna get the defuse, push",
    "stop the defuse, rush him now",
    "defuse happening, trade into him",
    "they're defusing, don't let them finish",
    "he defused",
    "they defused the spike",
    "bomb defused by enemies",
    "they got the defuse",

    # ------------------------------------------------------------------ RETAKE CALLS
    "retake A",
    "retake B",
    "retake C",
    "play the retake",
    "retaking now",
    "we're retaking",
    "push the retake",
    "let's retake",
    "go for the retake",
    "retake A together",
    "we need to retake B fast",
    "retake C, spike is down",
    "retake A, bomb is planted",
    "coordinate the retake",
    "retake through CT",
    "retake from CT side",
    "we retake from main",
    "retake off main",
    "retake from two angles",
    "two angle retake, one from CT one from main",
    "split the retake",
    "crossfire retake",
    "play crossfire, retake",
    "don't retake alone",
    "wait for me before retaking",
    "sync the retake",
    "retake on three",
    "swing together on the retake",
    "don't go in one by one on the retake",
    "use util for the retake",
    "flash into the retake",
    "molly spike before retake",
    "deny spike before you go in",
    "flash me in for the retake",
    "Breach, roll thunder into the retake",
    "KAY/O, knife before we retake",
    "Sage wall, then retake",
    "hold retake, I'm rotating",
    "wait for my rotation, then retake",
    "they're holding retake from heaven, careful",
    "they're playing for the retake, don't push",
    "wait on retake, they have util left",
    "retake is too risky with their ults up",
    "let the spike blow, don't give them a free retake kill",
    "don't retake, spike blows in 10",
    "retake is off the table, play for time",
    "not enough time to retake, save it",
    "can't retake, save your gun",
    "site lost, try to get a pick",

    # ------------------------------------------------------------------ MOLLY / UTILITY ON SPIKE
    "molly on spike",
    "they put molly on the spike",
    "incendiary on the spike",
    "viper snake bite on the bomb",
    "nanoswarm on the spike",
    "KJ nano on the defuse spot",
    "KJ's gonna molly when you defuse",
    "there's a nanoswarm on the spike",
    "molly spike on defuse, don't commit yet",
    "wait for the molly to go out before defusing",
    "molly is on the bomb, wait it out",
    "the incendiary is fading, defuse after",
    "nanoswarm done, now defuse",
    "smoke the nano before you go in",
    "Sage slow on the bomb",
    "slow orb on the spike, can't defuse through it",
    "sage wall is blocking the defuse",
    "there's a slow orb right on the spike",
    "wait for slow orb to expire",
    "Deadlock wall is blocking the bomb",
    "barrier mesh is blocking the spike",
    "barrier in front of the defuse, need to break it",
    "Killjoy locked down spike, retreat",
    "lockdown on the spike, everybody out",
    "lockdown just deployed, fall back and retake after",
    "careful, Viper pit is on the bomb",
    "viper pit is around spike, you're gonna melt",
    "defuse through the pit, you have time",
    "Orbital on the spike, don't go near",
    "Brimstone orbital on the bomb area",
    "Sova shocked the spike, it's clear now",

    # ------------------------------------------------------------------ DIRECTIONAL PLANT CALLS
    "plant for main",
    "plant for CT",
    "plant for heaven",
    "plant for elbow",
    "plant for tree",
    "plant facing main",
    "orient the spike toward main",
    "plant it so we hold main angle",
    "plant for the garden angle",
    "plant for hall side",
    "plant CT side, play crossfire",
    "plant for B main angle",
    "plant at B default, play workshop",
    "plant facing market stairs",
    "plant deep, back site",
    "deep plant, backsite of B",
    "plant safe behind the box",
    "plant behind gen, play tree",
    "safe plant, play off heaven",
    "plant open, we'll cover",
    "don't open plant, it's too risky",
    "plant in the hut, lotus A",
    "plant near the waterfall side C",
    "plant C platform side",
    "plant default C, play bend",
    "plant for the B upper angle lotus",

    # ------------------------------------------------------------------ WINGMAN / GEKKO PLANT
    "wingman, plant the spike",
    "send wingman to plant",
    "let wingman handle the plant",
    "wingman is going for the plant",
    "wingman planted, cover the site",
    "wingman planted A, hold the retake",
    "wingman planted B, watch for defuse",
    "wingman is defusing",
    "wingman is on the spike defusing",
    "Gekko's wingman defusing now",
    "wingman defusing, cover the angles",
    "wingman almost done defusing",
    "wingman defused it",
    "recall wingman after the plant",
    "recall wingman, keep him alive",
    "Gekko can defuse from here, send wingman",

    # ------------------------------------------------------------------ FAKE PLANT / DECOY
    "fake the plant",
    "fake planting",
    "go through the plant motion, don't plant",
    "fake A, we're hitting B",
    "make noise planting A, we go B",
    "decoy plant A",
    "run to A, fake plant, then rotate B",
    "let one person fake plant at A",
    "fake the spike plant to draw rotations",
    "start planting, bail out last second",
    "they'll rotate off the fake plant",

    # ------------------------------------------------------------------ RETAKE AFTER PLANT FAILS
    "they stopped the plant",
    "plant was stopped",
    "couldn't get the plant off",
    "plant was denied",
    "they denied plant",
    "no plant this round",
    "reset, couldn't plant",
    "re-execute, plant was stopped",
    "pull back, plant denied",
    "try B next, A plant got denied",

    # ------------------------------------------------------------------ NEGATIVE / NARRATION (must NOT relay)
    "I should've planted earlier but I was scared",
    "honestly I always forget to plant when I'm tilted",
    "chat, I panicked and didn't plant in time",
    "I didn't plant because I choked",
    "I keep forgetting to plant in that spot",
    "they should have planted sooner, terrible timing",
    "if our Sage walled earlier we could have planted",
    "I was thinking about planting but I hesitated",
    "I don't want to plant without backup",
    "personally I think the default plant is boring",
    "I wish I had planted at the pyramid instead",
    "I was about to defuse but decided not to risk it",
    "my hands were shaking when I went for the defuse",
    "chat, did you see that ninja defuse attempt",
    "that was the closest defuse I've ever done",
    "watch this defuse play, it's crazy",
    "I should have faked the defuse but I panicked",
    "I was going to fake the defuse and bait him but I forgot",
    "in hindsight we should have done a fake defuse",
    "I hate when they put nanoswarm on the spike",
    "these guys always plant at B default, so predictable",
    "I hope they plant B, I have a great angle there",
    "they'll definitely plant A this round, I can feel it",
    "every time I try to ninja defuse I get caught",
    "my teammate is so slow to defuse it hurts",
    "I cannot believe he let the spike blow",
    "we lost because nobody defused, gg",
    "thinking about whether to defuse or save",
    "not sure if I should risk the defuse here",
    "honestly just let it blow, it's not worth it",
    "I think we let too many spikes go this half",
    "our whole game plan was to plant A and they knew it",
    "sub I know I should have planted but chat was distracting me",

    # ------------------------------------------------------------------ EXTENDED / OFF-SNAP RELAY
    "tell them to plant B default and play workshop",
    "plant at generator and two of us hold tree and garden",
    "we should plant for main angle and hold from heaven",
    "plant B and one holds market stairs, one holds CT stairs",
    "spike at triple, play workshop and alley angles",
    "plant deep B, play from backsite",
    "if we get the plant, hold two angles and let the clock win",
    "plant B haven for the gong angle and hold with two",
    "plant C and hold platform with two players, one in hall",
    "spike A lotus, one in heaven, one at hut, one watching link",
    "we need to plant safe and then play passive post-plant",
    "get a safe plant and don't take unnecessary duels",
    "plant then go silent, make them dig you out",
    "plant behind the box and don't peek anything",
    "if spike is down just play for time, they're good aimers",
    "plant and let them come to us, we have better positions",
    "we win if spike is planted, don't force anything",
    "plant at B and three of us hold from different spots",
    "if we plant A gen, I'll hold tree and someone holds hell",
    "hell is the best post-plant spot, plant and I'll go hell",
    "hold heaven and hell and the spike wins itself",
    "whoever has spike, plant it at the pyramid and hold back site",
    "don't open plant, play around the boxes",
    "plant in cover, never plant in the open",
    "plant behind something, don't let them spam it",
    "plant and watch for the fast ninja defuse from CT",
    "they love to ninja defuse from garden, watch it",
    "careful of the silent CT rotate for a ninja",
    "after the plant watch for the sneaky defuse from behind",
    "they might have someone still alive for a sneaky defuse",
    "plant and watch all angles, one might still be alive",
    "spike B lotus, one person watch the wall door for a B door push",
    "if they break the wall now we're exposed on B lotus",
    "watch A link wall, if it breaks we need to cover B from two sides",
    "if they tap it, he's trying to bait, hold fire",
    "if he taps and stops it's a fake, hold your corners",
    "they're gonna do a fake defuse bait, don't peek it",
    "he's been tapping it twice, he's baiting you",
    "half-defuse means he wants you to peek, just wait",
    "don't shoot at the tap, he's trying to pull you out",
    "let him start defuse and then pinch from two sides",
    "let him tap it, then swing him from both angles",
    "wait until he fully commits to the defuse, then swing",
    "once defuse bar is half gone, swing him",
    "time the swing, defuse takes 7 seconds with kit",
    "kit cuts defuse to 4 seconds, be ready to swing fast",
    "they have a defuse kit, watch the spike time",
    "their sage might have kit, she's fast enough to defuse",
    "assume they have kit, don't let them get on spike unchallenged",
    "they're timing the retake to defuse without fighting",
    "one is lurking for a last second ninja, watch backsite",
    "their Omen might teleport behind us for the defuse",
    "Omen could shadow step onto the spike from weird spots",
    "Yoru might fake gate and then go for the defuse",
    "their Yoru placed a gate near the spike, watch it",
    "Yoru gate next to spike is a defuse attempt setup",
    "if their Clove dies she might rez onto the spike",
    "Clove Not Dead Yet near the spike is dangerous",
    "Gekko Wingman defusing, we need to stop the wingman",
    "kill the wingman before it finishes the defuse",
    "their wingman is on the spike, focus it",
    "can you kill the wingman before it finishes",
    "Wingman defuse is faster, it can catch you off guard",
    "molly the wingman away from spike",
    "Sage could res someone right next to the spike, careful",
    "they might res Jett onto the spike for a last second defuse",
    "Sage rez incoming near spike, don't let her get near",
    "get the Sage before she resurrects anyone",
    "Killjoy lockdown expired, retake window is open",
    "lockdown is over, push the retake now",
    "once the lockdown ends we go in",
    "wait for lockdown to clear then hit the retake",
    "wait out the orbital then we take the site",
    "orbital is done, hit the retake",
    "Brim orbital faded, three of us retake now",
    "viper pit is down, retake now",
    "once the pit drops we retake hard",
    "Viper's Pit is almost down, push on the edge",
    "their post-plant is two in heaven and one at generator",
    "they always play heaven and tree post-plant on A ascent",
    "counter their post-plant, one pushes main one goes link",
    "they're stacked post-plant, need util before retake",
    "don't dry retake into their post-plant setup",
    "flash into the retake, don't dry push",
    "use Breach ult for the retake",
    "flash into A then retake, don't dry swing",
    "Sova dart the site before we retake",
    "Fade haunt into the site before retake",
    "Skye dog the site for info before the retake",
    "use KAY/O knife before we retake",
    "suppressed the whole site, now retake",
    "KJ lockdown on the retake, they can't hold",
    "Killjoy ult and we hard retake",
    "spike B, one holds from B link and two retake from main",
    "retake B from both angles, CT and main",
    "pinch the retake from link and from CT",
    "two man retake, one main one CT",
    "three man retake, two main one link",
    "full five retake if they all stack site",
    "don't go one by one, wait and full retake together",
    "sync the push, 3 2 1 go on the retake",
    "let's full commit the retake, smokes first then push",
    "get a smoke for retake on main then hit it",
    "smoke heaven and then swing main on retake",
    "Brim smoke heaven before we retake A",
    "we're retaking through mid, spread out",
    "retake through link, faster than main",
    "CT rotate for the retake, faster path",
    "Omen TP behind them on the retake",
    "Omen can shadow step behind for the retake",
    "flanked from CT on the retake, they won't expect it",
    "one flanks CT, two push main for the retake",

    # ------------------------------------------------------------------ CLOCK + PLANT PRESSURE COMBOS
    "plant quick, 40 seconds",
    "plant it now, you have 35",
    "quick plant, don't waste time",
    "we need to plant in the next 20 seconds or we lose",
    "go plant, you still have 30 on the clock",
    "not enough time for a full execute, just run and plant",
    "rush plant, 15 seconds",
    "no time, someone plant",
    "forget the angles, plant now",
    "plant or we lose the round on time",
    "just drop the spike and plant, they're all dead",
    "spike is down, 45 left, hold tight",
    "bomb planted with 40 on the clock, that's good",
    "spike A, 38 seconds, you have time to play",
    "planted with a minute left, perfect timing",
    "spike B, 50 seconds, slow play from here",

    # ------------------------------------------------------------------ ECONOMIC CONTEXT PLANT CALLS
    "plant the spike, we're on eco, let it do the work",
    "spike down on eco, play for time",
    "we're on a save, plant and hide",
    "plant and save your gun",
    "plant and run, save the rifles",
    "spike down, save exits after",
    "they're on eco, plant fast before they rush",
    "plant quick, eco team can't retake well",
    "eco team won't do a good retake, plant and hold",
    "they're full buy, be careful retaking against rifles",
    "don't risk the retake, they have rifles and we have pistols",
    "spike is planted, but be careful, they have a full buy left",
    "we can't retake into rifles, let the spike blow if needed",
    "if we die going for defuse we feed rifles, just let it go",

    # ------------------------------------------------------------------ VARIETY: REGISTER / REGIONAL VOICE
    "yo spike is down",
    "bro the bomb's planted",
    "spike is down bro, hold your spot",
    "plant it fam",
    "dawg plant the bomb",
    "bro just stick the defuse",
    "let him cook, he's going for the defuse",
    "he's cooking the defuse",
    "send it, plant the spike",
    "spike it",
    "we spiked it",
    "we bombed it boys",
    "bomb's in the ground",
    "it's planted mate",
    "planted bruv",
    "spike's down, hold those angles",
    "get on that spike and defuse it",
    "hop on the bomb quick",
    "hit that defuse",
    "run it down and plant it",
    "rush the plant",
    "gunner, plant it now",
    "quick everyone, spike is lit, defuse it",
    "on the spike, don't stop me",
    "they know where we are, plant fast",
    "don't hesitate, plant the bomb",
    "less yapping, more planting",
    "stop overthinking, plant the spike",
    "forget the angles, stick the bomb",
    "get on that defuse before he peeks you",
    "peek and defuse, don't just sit there",

    # ------------------------------------------------------------------ HAVEN-SPECIFIC (3 SITES)
    "spike A haven",
    "spike B haven",
    "spike C haven",
    "planting C, cover garage",
    "planting A, hold long and short",
    "planted B haven, play B back",
    "planted A haven, one hold heaven one hold hell",
    "spike C haven, hold platform",
    "planted C haven default",
    "one defusing C, cover link",
    "retake A haven from link",
    "retake B haven from both links",
    "retake C haven through garage",
    "defuse A haven, I have heaven covered",
    "they're defusing B haven, push from A link",
    "defuse happening C haven, push from garage",
    "B haven spike, play gong and link angles",
    "planted A haven for long angle, hold from long",

    # ------------------------------------------------------------------ LOTUS-SPECIFIC (3 SITES + DOORS + WALL)
    "spike A lotus, door is closed",
    "spike A lotus, they didn't break the wall",
    "the A link wall is broken, they can push B from A",
    "wall broken lotus, cover B from link side",
    "watch the B door, wall's down lotus",
    "spike B lotus, watch A link if wall breaks",
    "spike C lotus, C door closed",
    "C door rotating, they're faking",
    "A door just opened, they might rotate",
    "door rotating A, adjust positions",
    "rotate when the A door opens",
    "retake C lotus, use the C door shortcut",
    "go through C door for the retake",
    "rotate through A door for the retake",
    "dropped from A heaven on the retake",
    "silent drop, going for the defuse",
    "I'm dropping silently for the defuse",
    "silent drop and then defuse",
    "going for silent drop retake",
    "silent drop on the retake, they won't hear me",
    "planted A lotus default near hut",
    "spike B lotus pillars side",
    "spike C lotus platform",
    "planted C lotus, play bend and hall",
    "defuse B lotus, watch upper",
    "stop the defuse B lotus, push from upper",

    # ------------------------------------------------------------------ SPLIT-SPECIFIC (ROPES + HEAVEN)
    "spike A split, terminal default",
    "spike B split, back site",
    "planted A split, hold from rafters",
    "spike A split, heaven and rafters crossfire",
    "spike B split, hold tower and CT stairs",
    "planted B default split, play off pillar",
    "retake A split through mid vent",
    "retake B split from CT alley",
    "defusing A split, hold from screens please",
    "defuse B split, watch heaven",
    "someone hold ropes, I'm defusing",
    "they climbed the rope, they're going for heaven",
    "he rope'd up to B heaven for the angle on defuse",
    "cover me from heaven, I'm defusing B",

    # ------------------------------------------------------------------ PEARL-SPECIFIC
    "spike A pearl, planted behind cafe",
    "spike B pearl, behind radianite boxes",
    "planted B pearl default",
    "planted A pearl behind vending machines",
    "spike A pearl, play dugout and flowers",
    "spike B pearl, play ramp and hall crossfire",
    "defuse A pearl, watch link",
    "defuse B pearl, watch tower and hall",
    "stop defuse pearl B, push from B hall",
    "retake A pearl from art and main",
    "retake B pearl from B link and main",
    "spike B pearl, hold the ramp angle",
    "play B upper ramp, spike is B default pearl",
    "spike A pearl, one hold flowers, one hold art",

    # ------------------------------------------------------------------ ASCENT-SPECIFIC
    "spike A ascent, behind generator",
    "spike A ascent, dice side",
    "spike B ascent, triple box default",
    "spike B ascent, back site workshop",
    "planted A ascent, play tree and garden",
    "planted A gen, one hell, one heaven",
    "spike B ascent, hold market stairs and CT stairs",
    "planted B workshop side, hold alley",
    "defuse A ascent, clear heaven and hell first",
    "defuse B ascent, watch workshop",
    "stop defuse B ascent, push from market",
    "retake A ascent from garden",
    "retake B ascent through market",
    "one in hell and one in heaven, spike A ascent",
    "they're defusing A gen, push from tree",
    "defuse at generator ascent, push through garden",

    # ------------------------------------------------------------------ BREEZE-SPECIFIC
    "spike A breeze, behind right pyramid",
    "spike A breeze, left pyramid side",
    "planted A breeze, play back site",
    "spike B breeze, default position",
    "planted B breeze, nest side",
    "spike B breeze, hold from nest and arches",
    "defuse A breeze, one holds back site",
    "stop defuse breeze A, push from hall",
    "retake A breeze from hall and main",
    "retake B breeze from arches",
    "spike A breeze, hold both pyramids",
    "they're defusing B breeze, push from arches",

    # ------------------------------------------------------------------ FRACTURE-SPECIFIC
    "spike A fracture, top site",
    "spike A fracture, bottom site",
    "planted at A heaven fracture",
    "planted at A hell fracture",
    "planted A fracture, play top and link crossfire",
    "spike B fracture, arcade side",
    "spike B fracture, main side",
    "planted B fracture near generator",
    "planted B canteen side fracture",
    "retake A fracture from link",
    "retake B fracture from arcade",
    "defuse A fracture, watch the rope",
    "stop defuse fracture B, push from tree",
    "they're on spike B fracture, rush from B main",

    # ------------------------------------------------------------------ MISC NUANCE / EDGE CASES
    "spike at the default, play it standard",
    "one of them is going for the defuse, push him",
    "I think someone's sneaking for the defuse",
    "sounds like they're on the spike",
    "I hear defuse audio",
    "defuse sound, he's going for it",
    "I hear them defusing, push now",
    "they might be tapping it right now",
    "spike might be getting defused, I can't see",
    "check spike, they might be on it",
    "watch the bomb, someone might sneak it",
    "don't let them sneak the defuse",
    "always check spike on the retake",
    "confirm spike location before retaking",
    "where's the spike, nobody called it",
    "someone call where spike is planted",
    "I need a spike callout, I can't see it",
    "spike location, quick",
    "where's the bomb",
    "where did they plant",
    "I didn't see where they planted",
    "did they plant A or B",
    "spike A or B, I'm rotating",
    "no spike callout yet",
    "first, where's the spike",
    "I can see spike from here, it's at generator",
    "I spotted the spike, it's at triple box B",
    "spike confirmed at B default",
    "I have eyes on spike, it's at the pyramid A",
    "spike visible from my angle, playing on it",
    "defuse kit on, going in",
    "I bought a defuse kit for this",
    "kit means faster defuse, I'll go",
    "she has a kit, she can get the defuse in time",
    "don't bother, the kit doesn't matter now, not enough time",
    "even with kit there's only 3 seconds left",
]
