"""Vocab pack: variety/nuance directives and strategies.

Domain: ALL strategic relay directives with maximum phrasing variety —
register variety (casual slang, clipped IGL-style, verbose), nuance across
ALL subdomain slices (execute, default, rush, slow play, lurk, anchor,
retake, rotate, stack, split, post-plant, spike management, eco, force,
trade, flank, off-site, crossfire, clutch, time pressure, utility, mental
reset, round-management, half-play, comp-wide decisions, site-specific
tactical reads). Every item is something a real Valorant streamer/teammate
actually says to Ultron to relay to teammates — maximally broad and unique.

Agents, abilities, and maps verified against refs/*.md. June 2026.

Kind: relay (~700 cases)
"""

ITEMS = [
    # =========================================================
    # EXECUTE / SITE HITS — varied phrasing / nuance
    # =========================================================
    "tell them we're going A, full send",
    "let my team know full execute B right now",
    "relay to my squad: hit A together, no stragglers",
    "tell them fast exec mid to B, go now",
    "let my teammates know execute A, commit hard",
    "tell my team we're all hitting B this round, no split",
    "relay: flash execute A main, don't stop moving",
    "tell them smoke and go A, now",
    "let my squad know fast exec B before they rotate",
    "tell my team we execute C, Haven, everyone go",
    "relay to teammates: smash B site while their smokes are burnt",
    "tell my team execute the second Brimstone drops smokes",
    "tell them we go A the moment his orbital lands",
    "let my teammates know hit B on Skye's Seekers, they'll scatter",
    "tell my squad execute through Catwalk into A, Ascent",
    "relay to my team: execute as a coordinated five, not a dribble",
    "tell them don't walk, run the execute",
    "let my team know entry fragger first, rest follow immediately",
    "tell my squad execute B from both angles, split the site",
    "tell them we do a clean execute, use everything we've got",
    "relay: once the flash pops, we go — no hesitation",
    "tell my team contact execute, only go once we spot them",
    "let my teammates know slow execute, drain their util first",
    "tell my squad quick execute, don't give them time to set up",
    "tell them eco execute, rush B, numbers advantage",
    "relay to my team: fake execute A then swing B hard",
    "tell them split execute, two A short, three A long",
    "let my team know we hit A from Haven long and short simultaneously",
    "tell my squad triple execute on Haven A site, everyone commits",
    "tell them execute B site on Haven through Garage",
    "relay: execute mid to B on Ascent, take Catwalk first",
    "tell my team hit B main on Split, util heavy execute",
    "let my teammates know execute A tree on Ascent after smokes",
    "tell my squad execute B through market on Ascent, clean line",
    "tell them entry on my flash, I throw in three two one",
    "relay to my team: entry in, trade if he dies, don't flinch",
    "tell them full team A, don't slow it down",
    "let my squad know if they're all B, we execute A right now",
    "tell my team we have a numbers advantage, exec fast",
    "relay: execute now while KAY/O has their abilities suppressed",

    # =========================================================
    # DEFAULT SETUPS — varied language and nuance
    # =========================================================
    "tell my team default this round, gather info",
    "relay: spread and default, no hard commit yet",
    "let my teammates know run a default, don't peek for no reason",
    "tell my squad default and burn their util before committing",
    "tell them slow default, we want information not blood",
    "relay to my team: default, see where they stack",
    "let my team know default A side first then pivot",
    "tell them default and lurk, extract as much info as possible",
    "tell my squad default setup, let them show their hand",
    "relay: default this round, we're playing for late info",
    "tell my team default and look for the early pick",
    "let my teammates know play default mid control first",
    "tell them default spread, two A two B one mid",
    "relay to my squad: default this round, decide late",
    "tell my team default and figure out what they're doing",
    "tell them run a default, don't burn smokes early",
    "let my squad know default and wait for their rotation tells",
    "relay: default setup, play off their aggression",
    "tell my team play a default and draw out their Sova dart",
    "let my teammates know default and absorb their utility",

    # =========================================================
    # RUSH / FAST PLAYS — phrasing variety, registers
    # =========================================================
    "tell my team we rush A, go go go",
    "relay: rush B, no util, just speed",
    "let my squad know we're rushing, don't slow down",
    "tell them five rush A main right now",
    "relay to my team: rush B, they won't expect it on eco",
    "tell my teammates rush C on Haven, they don't have it covered",
    "let my team know rush mid before they can set up",
    "tell them full B rush, five man",
    "relay: rush A, force them off their angles",
    "tell my squad rush it, they're buying, no util set",
    "tell them straight rush B main, no detours",
    "relay to my team: knife run then swap, rush A",
    "let my teammates know rush now while they're distracted B",
    "tell my squad rush, they don't have time to set up",
    "tell them judge rush B, get close and go",
    "relay: rush A with the force, numbers over guns",
    "tell my team fast push A lobby before they take space",
    "let my squad know wide rush, spread across the lane",
    "tell them rush while they still think we're defaulting",
    "relay to my teammates: rush and don't stop at any angle",

    # =========================================================
    # SLOW PLAY / PASSIVE / CLOCK MANAGEMENT
    # =========================================================
    "tell my team slow it down this round",
    "relay: play slow, we own the clock",
    "let my teammates know take your time, no reason to rush",
    "tell my squad stall them out, play for late round",
    "relay to my team: play slow, burn their patience",
    "tell them slow play and let them walk into our angles",
    "let my squad know slow walk, gather info, decide at thirty seconds",
    "tell my team play slow this round, use the full clock",
    "relay: no peeking, hold angles and play slow",
    "tell my teammates slow play, make them come to us",
    "let my team know if they don't push, we push at fifteen seconds",
    "tell them play passive, they have to plant",
    "relay: stall the round, run the clock, play time",
    "tell my squad play for time, let the spike do the work",
    "tell my team absorb their util with slow play, then commit",
    "relay to my teammates: late push, wait them out",
    "let my squad know slow play then explode late",
    "tell them no aggression this round, just hold",
    "relay: play deliberate, extract information, don't contest blindly",
    "let my team know play the clock, we have the advantage on time",

    # =========================================================
    # ROTATE — variety of phrasing and sub-variants
    # =========================================================
    "tell my team rotate to B now",
    "relay: rotate A fast, they're committing B",
    "let my teammates know rotate off B, hit A",
    "tell my squad rotate immediately, they're planting",
    "relay to my team: everyone rotate B, they're faking A",
    "tell them fast rotate, through mid",
    "let my team know rotate CT to B, don't go through mid",
    "tell my squad rotate the second I call, not before",
    "relay: hold the rotate, wait for my confirmation",
    "tell my teammates don't rotate yet, could be a fake",
    "let my team know soft rotate, keep one player A",
    "tell them rotate B but keep an eye on A",
    "relay to my squad: rotate as two, not all five",
    "tell my team slow rotate, don't leave A completely open",
    "tell them fake rotate, make noise and come back",
    "relay: one player stay A, rest rotate B",
    "let my teammates know rotate the moment they commit the spike",
    "tell my squad rotate off, this site is gone, save your life",
    "tell my team rotate CT, fastest path to B",
    "relay to teammates: hard rotate B, five of them are there",

    # =========================================================
    # RETAKE — nuanced sub-variants
    # =========================================================
    "tell my team play for retake",
    "relay: set up the retake, don't rush in",
    "let my teammates know retake together, don't trickle",
    "tell my squad retake B with util, dry peek is death",
    "relay to my team: retake from CT into B, clear site methodically",
    "tell them coordinate the retake, two from each entry",
    "let my team know retake only once we know where the spike is",
    "tell my teammates save your molly for the retake",
    "relay: retake as five, we have the numbers",
    "tell my squad retake B through back site, avoid main",
    "tell them play position for retake, don't over-rotate",
    "relay to my team: retake A short, cover B angles",
    "let my teammates know hold retake angles, don't fight in the open",
    "tell my team let them plant, then retake cleanly",
    "tell them retake once their smokes fade",
    "relay: retake on my call, not before",
    "let my squad know save utility for the retake, not the entry",
    "tell my teammates retake B, spread to cover both angles",
    "relay to my team: play off the spike during retake, use it as bait",
    "tell my team molly spike, then retake around it",
    "tell them retake using the Sage wall to split the site",
    "relay: retake and stick the defuse if they're all dead",
    "let my squad know retake A Haven from short and long simultaneously",
    "tell my teammates retake through Garage on Haven, they won't expect it",
    "tell my team retake B on Split through vent",

    # =========================================================
    # STACK / SPLIT — comprehensive sub-variants
    # =========================================================
    "tell my team stack B this round",
    "relay: stack A, they keep defaulting there",
    "let my teammates know we stack their favorite site",
    "tell my squad full stack B, all five",
    "relay to my team: stack A on defense, they're telegraphing it",
    "tell them stack C, Haven, three of them are always C",
    "let my team know stack B but rotate one player to A in case",
    "tell them three two split, you choose sides",
    "relay: two A three B, force a decision from them",
    "tell my squad split attack this round, don't clump",
    "tell my team split A and mid, cut off their rotate",
    "relay to my teammates: four stack B, one fakes A",
    "let my squad know split B and C on Haven, spread them thin",
    "tell them split the sites, their rotates can't cover both",
    "relay: split three to B, two to A, pick your read",
    "tell my team stack mid first then go from there",
    "let my teammates know full stack A, they're ignoring it",
    "tell my squad split then converge on whichever site opens up",
    "tell them four B one A fake, commit when they rotate",
    "relay to my team: split execute, attack from two angles",

    # =========================================================
    # LURK — various registers and setups
    # =========================================================
    "tell my team I'm lurking, play without me",
    "relay: I'm going to lurk their flank, hold tight",
    "let my teammates know send a lurker to cut off their rotate",
    "tell my squad someone lurk mid while we pressure A",
    "relay to my team: I lurk their CT, you pressure B",
    "tell them lurk and flank when they commit to the site",
    "let my team know lurk B while we fake A",
    "tell my teammates hold lurk position, don't go aggressive yet",
    "relay: I'm lurking their spawn, they won't see it coming",
    "tell my squad I'm cutting off their rotate with a lurk",
    "tell them play slow, I'm lurking their CT for the pick",
    "relay to my teammates: lurk and punish their rotate",
    "let my squad know one player lurk, rest play default",
    "tell my team I'm lurking mid, they won't rotate clean",
    "tell them hold A, I'm lurking their flank from B",
    "relay: lurk their backline while the team pressures",
    "let my teammates know deny their lurker, watch mid",
    "tell my squad lurk and don't go aggressive until I call",
    "tell my team I'm going to get the lurk pick and then you push",
    "relay to my team: I'll lurk mid, commit A when they go to trade",

    # =========================================================
    # ANCHOR — standalone and compound calls
    # =========================================================
    "tell my teammates one person anchor B while we rotate",
    "relay: anchor A, stall them until we arrive",
    "let my squad know anchor and delay, don't give the site",
    "tell my team anchor B while I go for the lurk",
    "relay to my teammates: anchor and provide info",
    "tell them anchor the site and slow them down",
    "let my team know anchor mid, don't let them through",
    "tell my squad anchor and play for time on the clock",
    "tell my teammates anchor A, hold until five seconds left",
    "relay: anchor with crossfire, not alone",
    "tell my team keep one anchor at B, rest rotate if needed",
    "let my teammates know anchor and call their positions",
    "tell my squad anchor the site and give info, don't die early",
    "relay to my team: I'm anchoring A, rotate freely if B is contested",
    "tell them anchor and stall, we'll rotate in twenty seconds",

    # =========================================================
    # SPIKE MANAGEMENT — plant calls, post-plant, defuse
    # =========================================================
    "tell my team plant the spike",
    "relay: plant it, we'll hold post-plant",
    "let my teammates know plant default, spread after",
    "tell my squad plant for CT, hold the CT angle",
    "relay to my team: plant for main, we've got main covered",
    "tell them plant in the corner, harder to defuse",
    "let my team know plant safe, don't plant in the open",
    "tell my teammates plant fast, we don't have time to clear",
    "relay: plant and spread, cover both defuse angles",
    "tell my squad plant and back off the spike, don't sit on it",
    "tell my team plant B for main, we play off it",
    "relay to my teammates: plant and post-plant, hold crossfire",
    "let my squad know plant and play time, let it cook",
    "tell my team plant quick and play around it",
    "tell them plant, then molly the spike position",
    "relay: once spike is down, play for time, no risks",
    "let my teammates know post-plant, spread out and hold angles",
    "tell my squad plant and play crossfire on the defuse",
    "tell my team play around the spike, not on it",
    "relay to my team: post-plant, play off-angles, not on the bomb",
    "tell my teammates post-plant positions, don't cluster around spike",
    "let my team know hold the defuse, they need to clear angles first",
    "tell them someone defuse, I'll watch the angle",
    "relay: don't defuse yet, they're baiting us",
    "tell my squad defuse on my call, not alone",
    "tell my teammates fake defuse, bait them out then swing",
    "relay to my team: half the defuse, see if they push, then commit",
    "let my squad know stick the defuse, they're all dead",
    "tell my team tap the spike and bait the swing",
    "tell them ninja defuse, go around their position",
    "relay: defuse through the smoke, they won't expect it",
    "let my teammates know don't defuse yet, thirty seconds is fine",
    "tell my squad defuse from the safe side, not the angle",
    "tell my team plant and let their Reyna run out of Devour charges",
    "relay to teammates: molly the spike after plant, they can't clear it",
    "let my team know Wingman is planting, Gekko fights for us",
    "tell them plant quick, KJ has Lockdown, don't let her set up",

    # =========================================================
    # TIME / CLOCK PRESSURE
    # =========================================================
    "tell my team we have time, don't force it",
    "relay: run the clock, twenty seconds is enough to plant",
    "let my teammates know don't rush, we have thirty seconds",
    "tell my squad stall the round, let the clock work",
    "relay to my team: play for time, they have to come to us",
    "tell my team we're low on time, commit immediately",
    "let my teammates know fifteen seconds left, make a move",
    "tell my squad force a decision now, clock is dying",
    "relay: ten seconds, push or plant now",
    "tell my team manage the clock, no point rushing",
    "tell them force it now, they're burning time on us",
    "relay to my teammates: they're delaying, watch for a late rush",
    "let my squad know don't wait past forty seconds, execute",
    "tell my team go now, clock is not on our side",
    "tell them play for time on defense, survive the round",

    # =========================================================
    # TRADE DISCIPLINE
    # =========================================================
    "tell my team trade every frag, don't die for nothing",
    "relay: if I die, trade me immediately",
    "let my teammates know always have a trade partner",
    "tell my squad never fight alone, always with a backup",
    "relay to my team: trade discipline this round, no wasted deaths",
    "tell them take the trade, don't bait each other",
    "let my team know play for swaps, not solo heroics",
    "tell my teammates always trade, we can't afford one-for-nothing",
    "relay: if entry dies, second player goes immediately",
    "tell my squad play off each other, force the trade",
    "tell my team don't take risks unless you have a trade partner",
    "relay to my teammates: double swing the corner, force a trade",
    "let my squad know entry and trade partner only, rest hold",
    "tell my team if you go in, someone covers your back",
    "tell them play with backup, no dry swings alone",

    # =========================================================
    # CROSSFIRE SETUPS
    # =========================================================
    "tell my team set up crossfire angles",
    "relay: play crossfire on that entry",
    "let my teammates know set up crossfire at the defuse",
    "tell my squad crossfire the doorway, one each side",
    "relay to my team: play crossfire on post-plant, catch them both ways",
    "tell them hold crossfire and make them choose",
    "let my team know crossfire this corner, both angles covered",
    "tell my teammates set up the crossfire before they push",
    "relay: play crossfire CT, one main one close",
    "tell my squad crossfire B site, hold both entry angles",
    "tell my team crossfire and let them walk into it",
    "relay to my teammates: crossfire the spike, they can't defuse safe",
    "let my squad know play crossfire on Haven B, one from garage one from lobby",
    "tell my teammates hold the crossfire, don't both swing at once",
    "tell my team crossfire entry and deep, not both at the door",

    # =========================================================
    # PLAY SAFE / LIFE MANAGEMENT
    # =========================================================
    "tell my team play their lives",
    "relay: don't feed them kills, play safe",
    "let my teammates know play safe this round, we can't lose more players",
    "tell my squad play for survival, not for frags",
    "relay to my team: don't die without getting info",
    "tell them hold back, play defensive",
    "let my team know no solo plays, play conservative",
    "tell my teammates play back, don't peek unless you're sure",
    "relay: protect your gun, don't get traded cheap",
    "tell my squad don't go aggressive, we're fragile this round",
    "tell my team play your life, we retake with numbers",
    "relay to my teammates: no risks, play tight",
    "let my squad know don't feed the Op, play passive",
    "tell my team play off their aggression, don't peek",
    "tell them play it safe, we need the credit save",

    # =========================================================
    # FLANKING — call it out, set it up, deny it
    # =========================================================
    "tell my team I'm going to flank their backline",
    "relay: I'll flank while you hold them",
    "let my teammates know watch for the flank through mid",
    "tell my squad two players hold flank",
    "relay to my team: I'm flanking their CT, pin them down",
    "tell them I go around for the flank, pressure them front",
    "let my team know they love the flank here, check it",
    "tell my teammates someone cover flank before we execute",
    "relay: they're flanking us, turn around",
    "tell my squad rotate to stop the flank",
    "tell my team hold flank watch while we execute",
    "relay to my teammates: I'll cut their flank off, push on my signal",
    "let my squad know watch for the lurker flanking our CT",
    "tell my team deny their flank so we can execute clean",
    "tell them cover mid flank, don't let them cut us off",

    # =========================================================
    # OFF-SITE / RETREAT PLAY
    # =========================================================
    "tell my team fall back, regroup",
    "relay: fall back now, we're getting pushed",
    "let my teammates know pull back to CT",
    "tell my squad fall back and reset",
    "relay to my team: retreat, don't die holding nothing",
    "tell them fall back and play for retake",
    "let my team know fall back, let their smokes burn out",
    "tell my teammates fall back and regroup before retake",
    "relay: pull back to safety, save your life",
    "tell my squad fall back, don't chase their exits",
    "tell my team fall back mid, they have numbers",
    "relay to my teammates: fall back and hold, don't push",
    "let my squad know don't chase, fall back and hold your spot",
    "tell my team play off site, come back after their util fades",
    "tell them play off site, their Raze has ult and we die on site",
    "relay: play off site, let the smokes clear",
    "let my teammates know play off the site and come back in",
    "tell my squad off site, their Killjoy has Lockdown ready",
    "tell my team play off site, Viper's pit will clear in ten seconds",
    "relay to my team: off site, let the molly burn, then retake",

    # =========================================================
    # UTILITY COORDINATION
    # =========================================================
    "tell my team smoke the CT before we go",
    "relay: flash in on my countdown",
    "let my teammates know coordinate smokes, don't double up",
    "tell my squad don't burn util before the execute",
    "relay to my team: save smokes for post-plant",
    "tell them pop util on the execute, not before",
    "let my team know smoke and flash in together, not separately",
    "tell my teammates util up before we push",
    "relay: save your flash for after the smoke drops",
    "tell my squad Brimstone smokes first, then everyone goes",
    "tell my team hold your Breach flash for the execute",
    "relay to my teammates: Omen smoke mid so we can rotate safe",
    "let my squad know Sova dart first, then commit",
    "tell my team don't waste the dog on an uncontested area",
    "tell them save Killjoy util for post-plant, not the entry",
    "relay: KAY/O knife first, then execute while they're suppressed",
    "let my teammates know Sage wall the entry before we take B",
    "tell my squad coordinate: smoke, flash, then entry",
    "tell my team harbor wall before we push, we walk through",
    "relay to my team: Astra gravity well the spike, deny their defuse",
    "tell them don't pop util yet, wait for them to peek",
    "relay: use Fade Haunt for info before we commit",
    "let my squad know Skye bird flash into site, go on the pop",
    "tell my team Gecko Dizzy the entry, entry goes right after",
    "tell them Tejo guided salvo the site before we hit it",

    # =========================================================
    # MENTAL RESET / MORALE
    # =========================================================
    "tell my team reset after that round",
    "relay: shake it off, new round",
    "let my teammates know don't tilt, we reset",
    "tell my squad forget the last round, move forward",
    "relay to my team: reset your mental, play your game",
    "tell them clean reset, we go again",
    "let my team know don't carry tilt into this round",
    "tell my teammates no rage, reset and focus",
    "relay: one round at a time, reset",
    "tell my squad wipe it and play clean",
    "tell my team keep composure, we're fine",
    "relay to my teammates: don't let that throw affect us",
    "let my squad know take a breath, reset mental",
    "tell my team it's one round, we fix it next",
    "tell them calm down, play structured",

    # =========================================================
    # ECONOMY — nuanced sub-variants
    # =========================================================
    "tell my team we're saving this round",
    "relay: full eco, don't buy anything",
    "let my teammates know save, bank credits for next round",
    "tell my squad don't give them your guns, save rifles",
    "relay to my team: save round, buy nothing unless you have pistol",
    "tell them eco round, play for survival not kills",
    "let my team know pistols only this round, save rifles",
    "tell my teammates don't buy rifles on eco, we need next round",
    "relay: full save, everyone bank your credits",
    "tell my squad one more eco and we full buy next",
    "tell my team save your gun if the round is lost",
    "relay to my teammates: full buy this round, we have the credits",
    "let my squad know everyone full buy, rifles and armor",
    "tell my team full buy, we can't eco into a rifle round",
    "tell them buy rifles and go, we're ready",
    "relay: we're full buying, no excuses",
    "let my teammates know full buy, this round we fight properly",
    "tell my squad force buy, spend everything we have",
    "relay to my team: force buy, we can't eco another round",
    "tell my team force, it's do or die",
    "tell them force buy, we need guns to win this",
    "relay: force this round, save nothing",
    "let my teammates know half buy this round, SMGs and light armor",
    "tell my squad half buy, Spectres and shields is enough",
    "tell my team light buy, Bulldog and armor",
    "relay to my teammates: half buy, don't go full rifle yet",
    "let my squad know buy what you can, half buy round",
    "tell my team drop the credits into rifles if you can",
    "tell them armor at minimum, don't fight naked",
    "relay: pocket Guardian this round, punch above our budget",
    "let my teammates know Sheriff only, don't waste credits",
    "tell my squad Spectre force, everyone matching",
    "relay to my team: they're on eco, anti-eco this round",
    "tell my team anti-eco round, buy down, save money",
    "tell them don't over-buy against eco, they might clutch it",
    "relay: they're saving, adjust our buy accordingly",
    "let my squad know they're on eco, play aggressive",
    "tell my teammates they're pistol-only, push them hard",
    "relay to my team: their eco means we have a gun advantage, use it",
    "tell my team two more saves and we full buy next half",
    "tell them one save and we're set for full buy",
    "relay: we need two rounds of credits, hold discipline",
    "let my teammates know don't throw eco, we need the credits",
    "tell my squad don't feed them rifles on an eco round",

    # =========================================================
    # ROUND-WIDE IGL / STRATEGIC CALLS
    # =========================================================
    "tell my team default this round, look for information",
    "relay: play for picks this round, no full commit",
    "let my teammates know play for information, no blind exec",
    "tell my squad one round at a time, no tilting",
    "relay to my team: we play for the information advantage",
    "tell my team this round we slow play and react",
    "let my teammates know play to their tendencies, we anti-strat",
    "tell my squad we play aggressive mid, force a decision",
    "tell my team contest mid early, control the map",
    "relay: early mid control then decide A or B",
    "let my teammates know contest mid on Ascent, gate their B rotate",
    "tell my squad win mid control on Split, use the ropes",
    "relay to my team: take mid on Haven then pick A or C",
    "tell my team play for mid control first, then execute",
    "tell them early mid contest, don't let them have it",
    "relay: pressure mid with util, not bodies",
    "let my squad know if we have mid, their rotates are slow",
    "tell my teammates early mid pick then we go from there",
    "relay to my team: if mid is contested, default and re-evaluate",
    "tell my team don't fight mid for nothing, play for info",

    # =========================================================
    # AGENT-SPECIFIC TACTICAL CALLS
    # =========================================================
    "tell them Jett leads the entry, dash out after the pick",
    "relay: Reyna entry, you get the Devour and go again",
    "let my team know Neon entries, use the Fast Lane wall",
    "tell my squad Phoenix run it back entry this round, use the ult",
    "relay to my team: Raze Boom Bot the corner before entry",
    "tell my teammates let Iso kill contract a duel, give him space",
    "let my team know Waylay flank while we pressure",
    "tell them Raze Showstopper when they cluster on site",
    "relay: Yoru Gatecrash the spike plant location, hold post-plant",
    "tell my team Sage wall the entry so they can't push through",
    "relay to my squad: Killjoy turret here, Nanoswarm the spike",
    "let my teammates know Cypher cam here, we get info",
    "tell my team Chamber Rendezvous and hold the Op angle",
    "relay: Deadlock Barrier Mesh B main, slow their rush",
    "tell my squad Vyse Razorvine the spike, deny clean defuse",
    "tell my team Veto Evolution when they cluster for retake",
    "relay to my teammates: KAY/O knife first, suppressed enemies can't flash us",
    "let my squad know Fade Haunt for info, then we commit",
    "tell my team Skye dog scouts the angles before entry",
    "relay: Breach Rolling Thunder the site before we hit",
    "let my teammates know Sova Recon Bolt before the execute",
    "tell my squad Tejo Stealth Drone for info, then salvo the site",
    "relay to my team: Gekko Wingman plants the spike, we fight",
    "tell my team Brimstone stim beacon on the plant site",
    "relay: Viper pit the site after plant, hold inside",
    "let my teammates know Omen teleport to the off-angle after smoke",
    "tell my squad Astra gravity well the defuse spot post-plant",
    "tell my team Harbor Reckoning when they stack retake",
    "relay: Clove Not Dead Yet, she'll revive after entry if she dies",
    "let my squad know Miks Bassquake if they cluster the retake",

    # =========================================================
    # POST-ROUND COMMUNICATION
    # =========================================================
    "tell my team their Chamber has Op, track him next round",
    "relay: their Jett has ult next round, respect the knives",
    "let my teammates know their Killjoy has Lockdown charged",
    "tell my squad their Sova has Hunter's Fury ready",
    "relay to my team: we have four ults between us, this round is ours",
    "tell my team who has ult, report now",
    "let my teammates know our Sage has rez, save it for the right moment",
    "tell my squad their Reyna has Empress, don't feed her kills",
    "relay: their Viper has Pit charged, don't fight inside it",
    "tell my team track their ults, KAY/O NULL/cmd and Breach ult are both up",

    # =========================================================
    # CLUTCH SITUATIONS
    # =========================================================
    "tell my team I've got this, no comms",
    "relay to teammates: last one, let me clutch, go silent",
    "let my squad know it's a one v two, stay quiet",
    "tell my team play for spike, not kills, it's a clutch",
    "relay: I see the spike, I'm going for the ninja defuse",
    "let my teammates know I'm clutching, no advice please",
    "tell my team dead players shut up, I'm clutching",
    "relay to my squad: clutch player needs silence, zip it",
    "tell them play for spike detonation, don't risk the defuse",
    "relay: it's a clutch situation, let him play it out",
    "tell my team give the clutch player space and silence",
    "let my teammates know call your position and go quiet",
    "relay: one alive vs three, spike detonation is the win condition",
    "tell my squad no coaching from the dead, silence",
    "tell my team play for time in the clutch, spike does the work",

    # =========================================================
    # HALF-PLAY / MATCH PACE
    # =========================================================
    "tell my team close the half strong",
    "relay: win this round, take the half momentum",
    "let my teammates know take the pistol, set up the half",
    "tell my squad win the first gun round, set the economy",
    "relay to my team: close this half with a clean round",
    "tell my team protect the lead this half",
    "let my teammates know don't throw the half, we're ahead",
    "tell my squad take this round and we flip their economy",
    "relay: win this round for the full buy next",
    "tell my team we're up, play smart this half",
    "tell them tie it up this round, we close the half clean",
    "relay to my teammates: match point, don't get cocky",
    "let my squad know overtime rules, win two in a row",
    "tell my team one more round for the half lead",
    "relay: close the gap this round, one at a time",
    "tell my teammates take the pistol round, it sets the half",
    "relay to my team: win this and we have full buy all half",
    "let my squad know don't throw the pistol, it matters",
    "tell my team clean up this round and we go half-up",
    "relay: last round of half, play composed",

    # =========================================================
    # MAP-SPECIFIC TACTICAL CALLS (accurate locations from refs)
    # =========================================================
    # Haven
    "tell my team three on C Haven, rotate immediately",
    "relay: fake A on Haven, commit C",
    "let my teammates know stack C Haven, they love it",
    "tell my squad split A and C on Haven, leave B light",
    "relay to my team: lurk through Garage on Haven, cut CT",
    "tell my team pressure B mid doors on Haven to split their defense",
    "relay: fake Haven B through Garage, pivot C Long",
    "let my squad know execute A Haven from both Long and Short simultaneously",
    "tell my teammates slow play Haven C, drain their util",
    "relay to my team: anchor B Haven, rotate A or C on contact",
    # Ascent
    "tell my team take mid Ascent first, then decide",
    "relay: control Catwalk on Ascent before executing A",
    "let my teammates know Market control on Ascent gives us B access",
    "tell my squad execute Ascent B through Market after taking tiles",
    "relay to my team: deny Ascent mid with smoke on top then push",
    "tell my team push Ascent A tree with flash and commit",
    "let my teammates know close the A door on Ascent to deny",
    "relay: open A door with the switch, force their hand",
    "tell my squad Ascent mid control then hit B from market",
    "tell my team execute A Ascent from lobby through main, hard commit",
    # Split
    "tell my team Split A site, hit from ramp and main",
    "relay: control mid Split, use the ropes to take site quick",
    "let my teammates know slow play Split B main, they lurk there",
    "tell my squad Split B execute through main, smoke Heaven",
    "relay to my team: take Split mid tower then commit A",
    # Pearl
    "tell my team Pearl A execute, smoke CT and main simultaneously",
    "relay: Pearl B main execute, everyone through at once",
    "let my teammates know Pearl mid control, then B from mid link",
    "tell my squad slow push Pearl B, they like to hold cubby",
    "relay to my team: Pearl A hall to A site, use the off-angle",
    # Lotus
    "tell my team execute Lotus C this round",
    "relay: Lotus B execute after rotating the door",
    "let my teammates know stack Lotus A, they like to default there",
    "tell my squad fake Lotus A, commit B through connector",
    "relay to my team: lurk Lotus mid while we pressure A",
    # Fracture
    "tell my team attack Fracture B Dish this round",
    "relay: split Fracture both sides, pressure A Rope and B Main",
    "let my teammates know fake A Rope on Fracture, hit B Arcade",
    "tell my squad Fracture mid control is the key, take Bridge",
    "relay to my team: Fracture unique split, attack from both spawns",
    # Breeze
    "tell my team open B main Breeze, hit the site fast",
    "relay: Breeze A execute after taking mid wood doors",
    "let my teammates know Breeze B is wide, use smokes across site",
    "tell my squad take mid Breeze first, control the island",
    "relay to my team: Breeze A execute split from cave and main",

    # =========================================================
    # NUANCED / COMPOUND CALLS (stress-test compounding)
    # =========================================================
    "tell my team eco this round, force next, then full buy the round after",
    "relay: force now or eco, we need three credits minimum to buy next",
    "let my teammates know save this round and we full buy in two",
    "tell my squad save and full buy vs force: save wins here",
    "relay to my team: we eco, they eco, but we want the next full buy",
    "tell my team execute A while Clove distracts B with Ruse smokes",
    "relay: Sova Recon Bolt the site, Breach Fault Line the entry, then we go",
    "let my teammates know flash execute A, Breach flash first, Skye second",
    "tell my squad execute with Brimstone smokes and Breach stun at the same time",
    "relay to my team: anchor B and send the lurker mid while we fake C",
    "tell my team stack B, but keep one player lurking their CT rotate path",
    "relay: execute A fast on my smoke, Breach stun the close angle",
    "let my squad know Omen teleport off angle on site while we entry from main",
    "tell my teammates Sage wall the doorway and we push through before they break it",
    "relay to my team: Viper screen splits the site, entry A side, support B side",
    "tell my team close the defuse half before their Sage uses Resurrection",
    "relay: fake the defuse to bait Reyna Dismiss, then swing hard",
    "let my squad know play for time on spike with KJ Nanoswarm denying the defuse",
    "tell my team Cypher cam the defuse angle, we know when they push",
    "relay to teammates: play crossfire post-plant and force them to defuse under pressure",
    "tell my team execute A while lurker cuts off B CT rotate simultaneously",
    "relay: double-entry with Jett and Neon, they can't stop both",
    "let my teammates know Phoenix Run It Back the entry, worst case we reset",
    "tell my squad Raze Boom Bot the corner before entry fragger goes",
    "relay to my team: Iso Kill Contract one duel to open the site",
    "tell my teammates stack three B, send lurker mid, one anchor A",
    "relay: slow push, take mid, wait for their Recon Bolt to fade, then execute",
    "let my squad know absorb their flash with passive play, then execute clean",
    "tell my team don't go before I drop the orbital on site",
    "relay to teammates: take catwalk, smoke screens on Ascent, entry from above",

    # =========================================================
    # EDGE CASES / NUANCED REGISTER VARIETY
    # =========================================================
    # Very short clipped IGL-style
    "team: save",
    "team: full buy",
    "team: force",
    "team: execute A",
    "team: B rush",
    "team: rotate now",
    "team: retake B",
    "team: fall back",
    "team: plant it",
    "team: post-plant crossfire",
    # Verbose / frustrated
    "tell my team for the love of everything please stop trickle-entering B site one by one",
    "relay to my squad that we need to actually commit to one site and execute it properly",
    "let my teammates know we can't keep defaulting forever, we need a decision at thirty seconds",
    "tell my team stop lone-wolfing, this is a team game, play together",
    "relay that they need to stop wasting util before the execute",
    # Casual slang register
    "yo tell my team just rush B bro",
    "tell my squad to just full send A, we overthinking it",
    "relay to my teammates we just gotta force, we're cooked if we save again",
    "tell my team we vibing with a default this round",
    "relay: boys we're going B, full send, no hesitation",
    # British-register
    "tell my team we're doing a proper execute A, no messing about",
    "relay to my squad sort it out and hit B, we've been defaulting all half",
    # Strategic mid-round adjustments
    "tell my team abort, pull back, we're not executing",
    "relay: abort the execute, they have info on us",
    "let my teammates know abort A, pivot B while there's time",
    "tell my squad abort, reset, play default again",
    "relay to my team: abort, we got spotted, they know we're coming A",
    "tell my team one more, wait for one more pick before we execute",
    "relay: hold, wait for the smoke, then go",
    "let my teammates know one more player on site before we retake",
    "tell my squad wait for Sage wall to go up, then push",
    "relay to my team: contact execute, only go after we spot them",
    "tell my team send it, go now, no more waiting",
    "relay: go now, don't wait for the smoke to be perfect",
    "let my teammates know it's go time, push immediately",
    "tell my squad don't go yet, we wait for their smokes to expire",
    "relay to my team: adjust to B, forget A, go B right now",
    # Defensive IGL calls
    "tell my team play passive this half, let them make the mistakes",
    "relay: hold all angles, don't give away position",
    "let my teammates know play reactive, respond to their moves",
    "tell my squad don't take early peeks, hold the crossfire",
    "relay to my team: passive hold, let them hit the angles",
    "tell my team play off angles, don't hold the expected spots",
    "relay: switch up your spots, they know where you hold",
    "let my teammates know change positions, they're pre-aiming our usual spots",
    "tell my squad play unexpected angles, mix it up",
    "relay to my team: play patient defense, make them come to us",
    "tell my team aggressive defense this round, push them early",
    "relay: early aggression, push their spawn timing",
    "let my teammates know aggressive hold, punish their approach",
    "tell my squad push up and contest early, deny their space",
    "relay to my team: play contest defense, win the early fight",
    # Economic strategy sentences
    "tell my team we're in a save spiral, we need to force now to break it",
    "relay: we force because the economy is broken and eco isn't working",
    "let my teammates know if we save again we hand them the economy all half",
    "tell my squad the math says save but the momentum says force",
    "relay to my team: we eco then they eco, we both reset, play for the advantage",
    # Entry / second entry roles
    "tell my team I entry, second person follows immediately",
    "relay: entry fragger goes, second entry trades if needed",
    "let my teammates know support entry with flash, then follow in",
    "tell my squad entry commits, rest play off the info",
    "relay to my team: entry creates space, support cleans up",
    "tell my team lead with util, entry second, not before",
    "relay: entry on the flash pop, don't wait",
    "let my teammates know entry dry peek is suicide, flash in",
    "tell my squad double entry this chokepoint, overwhelm them",
    "relay to my team: second entry ready, don't let entry die wasted",
    # Post-plant pure strategy
    "tell my team post-plant one three, one spike side one open",
    "relay: post-plant, play time, don't fight unless forced",
    "let my teammates know post-plant crossfire A site",
    "tell my squad post-plant corners, not center",
    "relay to my team: post-plant from off angles, not on the spike",
    "tell my team hold off-angles post-plant, catch their retake",
    "relay: post-plant, if they retake from CT, we hold short",
    "let my teammates know post-plant near spike but not on it",
    "tell my squad post-plant, play for the long game",
    "relay to my team: post-plant crossfire, two angles covered",

    # =========================================================
    # ADDITIONAL VARIETY — fill to ~700
    # =========================================================
    # Weapon-specific eco directives
    "tell my team buy Spectre and shields, that's our force",
    "relay: everyone Bulldog this round, save the credits",
    "let my teammates know Sheriff only, don't buy rifles",
    "tell my squad Odin force, spray them off site",
    "relay to my team: Ares force, suppress their push",
    "tell my teammates buy Judge for the rush, it's close quarters",
    "relay: Marshal force, keep distance and pick from range",
    "let my squad know pocket Guardian is fine this round",
    "tell my team Outlaw force, two shots one kill",
    # Attitude / command variety
    "relay to my squad: we play disciplined or we lose the half",
    "tell my team play to win, not to frag",
    "relay: execute with intent, don't wander",
    "let my teammates know play with purpose, we have a plan",
    "tell my squad execute like we practiced, clean and fast",
    "relay to my team: no reckless plays, play to the strat",
    "tell my teammates this round we win through discipline, not chaos",
    # Info-first calls
    "tell my team don't commit until we have information",
    "relay: get info before you execute, no blind commits",
    "let my teammates know wait for info, then make the call",
    "tell my squad gather info this round, execute next",
    "relay to my team: play for information advantage first",
    "tell my teammates one player sacrifices for info, rest hold",
    # Spike carrier directives
    "tell my team drop spike, I'll plant",
    "relay: who has spike, call it out",
    "let my teammates know pick up the spike, don't leave it",
    "tell my squad carrier stay safe, let others frag",
    "relay to my team: spike carrier stays back until site is clear",
    "tell my teammates protect the spike carrier",
    # Crossfire / angle discipline combo
    "tell my team don't both hold the same angle",
    "relay: spread your angles, cover more of the site",
    "let my teammates know two players same angle is wasteful",
    "tell my squad split angles, one each side",
    "relay to my team: hold separate angles so they can't double-peek us",
    # Mid-round pivots
    "relay: pivot B, forget A, something opened up",
    "tell my team adjust the plan, they didn't rotate",
    "let my teammates know pivot mid, take the opening",
    "tell my squad change of plans, go B while we can",
    "relay to my team: adjust, they gave us the site for free",
]
