"""Vocab pack: greetings, GGs, GHs, GLHFs, and end-of-match sportsmanship for the relay corpus.

Domain: Everything in the greeting / farewell / sportsmanship slice of relay traffic.
Covers:
  - Pre-game greetings (GLHF, good luck, let's go, etc.) relayed to teammates or enemies
  - Mid-match acknowledgment phrases (nice shot, well played, good round)
  - Half-time calls (good half, GH, switch sides, adjustments)
  - Post-match GGs, GG EZs, GG WPs, NT, good games of all registers
  - Congratulatory / morale lines after clutches, aces, team aces, thrifties
  - Trash-talk / taunting GGs that border on GG EZ
  - Commiserations / sportsmanship after a loss
  - Full-variety register: terse, verbose, slang-heavy, formal, regional, sarcastic

All items are KIND=relay: the streamer is directing Ultron to say the line
to teammates or enemies in voice chat. Relay triggers vary maximally
('tell them', 'say to my team', 'let them know', 'tell the guys', 'call out',
 'say', 'pass on', 'remind my team', 'tell those guys', bare callout style, etc.).

Phrasing uniqueness enforced: no near-duplicates within this file.
"""

ITEMS = [
    # -----------------------------------------------------------------------
    # PRE-MATCH / ROUND-START GREETINGS — GLHF, let's go, greetings to team
    # -----------------------------------------------------------------------
    "tell my team good luck have fun this match",
    "say good luck have fun to everyone",
    "let my teammates know GLHF and let's get this",
    "tell the guys glhf and play clean",
    "say to my team good luck have fun, let's win this",
    "tell them good luck out there",
    "let my team know I'm wishing everyone luck this game",
    "tell my squad good luck and let's take this match",
    "say good luck have fun to the whole lobby",
    "let my team know good luck, play calm, and we've got this",
    "tell my teammates have fun and may the best team win",
    "say glhf to both sides",
    "pass on good luck and have fun to my team",
    "tell the guys we've got this, good luck everyone",
    "remind my team to say good luck have fun at the start",
    "tell them to have fun out there and not stress",
    "let the team know it's just ranked, good luck, play loose",
    "say GLHF and focus up, team",
    "tell my crew good luck and let's run it back if we lose",
    "say good luck have fun to the other team too, keep it clean",

    # -----------------------------------------------------------------------
    # PRE-MATCH HYPE / LET'S GO openers
    # -----------------------------------------------------------------------
    "tell my team let's go, we're winning this",
    "say let's go to my squad right now",
    "let my teammates know we're cooking this game",
    "tell the guys let's get it, focus from round one",
    "say let's run it to my team",
    "tell them we're ready, let's go",
    "let my team know let's lock in from the jump",
    "say let's get this bread to my team",
    "tell my teammates it's time to cook, let's go",
    "say let's get it to the whole team",
    "let them know we mean business today",
    "tell my squad let's run it up from round one",
    "say let's go boys to my team",
    "tell the guys we're playing clean today, let's go",
    "remind my team stay locked in from the start, let's do this",
    "tell my teammates we're here to win, let's run it",
    "say let's focus up and get the first round to my team",
    "let my team know energy's high, let's get this W",
    "tell them it's go time, no messing around",
    "say let's run it back twenty-five times if we have to, let's go",

    # -----------------------------------------------------------------------
    # GOOD ROUND acknowledgments mid-match
    # -----------------------------------------------------------------------
    "tell my team good round",
    "say good round to my squad after that one",
    "let my teammates know good round, well played",
    "tell the guys good round, clean execution",
    "say good round everyone to my team",
    "let my team know nice round, that was clean",
    "tell them good round, let's keep it going",
    "say that was a good round to my team",
    "tell my teammates good round, that execute was crisp",
    "let them know good round, now reset and do it again",
    "say solid round to my team",
    "tell my squad solid round, good reads all around",
    "say nice round to my team after that clutch",
    "tell them good round, don't get complacent though",
    "let my team know good round, one round at a time",
    "say that was a well-played round to my teammates",
    "tell the guys good round, now let's talk the next one",
    "say good round, we're building momentum now to my team",
    "let my teammates know good round, keep the same energy",
    "tell them good round even though we lost it, we played that right",

    # -----------------------------------------------------------------------
    # NICE SHOT / NS / N1
    # -----------------------------------------------------------------------
    "tell my team nice shot on that one",
    "say nice shot to whoever got that kill",
    "let my teammates know nice shot, that was a filthy flick",
    "say NS to my squad",
    "tell them nice shot, clean one-tap",
    "say nice one to my team",
    "tell my teammates N1 on that pick",
    "let my team know that was a beautiful shot",
    "say nice shot bro to the person who just aced",
    "tell the guys nice flick right there",
    "say clean shot to my team",
    "let them know that was a nasty one-tap",
    "tell my squad that shot was absolutely filthy, nice one",
    "say good shot, I saw that, to my team",
    "tell them sick shot on that rotating Jett",
    "let my teammates know that was a cracked shot, well done",
    "say nice deag to whoever popped that headshot",
    "tell my team that was an insane flick, nice shot",
    "say that clip is going in the highlights to my team after that ace",
    "let them know nice shot, that was effortless",

    # -----------------------------------------------------------------------
    # NICE TRY / NT
    # -----------------------------------------------------------------------
    "tell my team nice try on that clutch attempt",
    "say NT to my squad after that 1v3",
    "let my teammates know nice try, that almost worked",
    "say nice try to the person who just lost the clutch",
    "tell them NT, that was a good attempt",
    "say nice try, it's all good to my team",
    "let my team know nice try on that eco round, we almost stole it",
    "tell the guys NT we were so close",
    "say good try to my teammates after that failed retake",
    "tell them nice try, bad break, reset your mind",
    "say NT that bomb play was almost perfect to my team",
    "let my squad know nice try on the ninja defuse, unlucky",
    "tell my teammates NT, no shame in that, you gave everything",
    "say good try, next round to my team",
    "tell them nice try, you made them work for it",
    "let my team know NT even on the loss, that was well played",
    "say nice try to the guy who just 1v4'd and almost pulled it off",
    "tell my squad nice try on the fake defuse, they just got lucky",
    "say NT on the peek, you read it right just got beaten on timing",
    "let them know nice try, that clip will haunt me but NT",

    # -----------------------------------------------------------------------
    # WELL PLAYED / WP individual shoutouts
    # -----------------------------------------------------------------------
    "tell my team well played this round",
    "say well played to my squad",
    "let my teammates know well played, that was a smart round",
    "tell them WP, clean across the board",
    "say well played guys to my team",
    "let my team know well played on that execute, perfect timing",
    "say WP to the whole team after that retake",
    "tell my teammates well played, especially on the util usage",
    "tell the guys well played, that site take was textbook",
    "let them know well played, nobody panicked",
    "say that was well played to my squad",
    "tell my team well played on the retake, we were so coordinated",
    "say WP on the fake, they completely bought it",
    "let my teammates know well played, I can't fault a single decision",
    "tell them well played, we deserved that round",
    "say well played to everyone who survived that round",
    "tell my squad well played, even the guys who died went in the right order",
    "let my team know well played, that was some IGL-level execution",
    "say that round was chef's kiss to my team, well played",
    "tell them well played, we're starting to look like a real team",

    # -----------------------------------------------------------------------
    # GOOD HALF / GH at the halftime break
    # -----------------------------------------------------------------------
    "tell my team good half",
    "say good half to my squad at halftime",
    "let my teammates know good half, we did great",
    "tell the guys GH, we're in a good position",
    "say good half everyone to my team",
    "let my team know good half, switch sides and let's lock in again",
    "say GH and let's come out strong next half to my teammates",
    "tell them good half, we learned a lot in those first twelve rounds",
    "tell my squad good half, now we adjust on defense",
    "say good half to my team, let's not throw it though",
    "let them know good half, 7-5 is still a win we can take into second half",
    "tell my teammates good half, we're controlling this match",
    "say good half and don't change what's working to my team",
    "let my team know good half on attack side, now defend cleanly",
    "tell them good half, we identified their reads and now we flip them",
    "say GH to my squad, they threw that last round so morale is high",
    "tell the guys good half, we're tied at six-six, that's actually fine",
    "let my teammates know good half, we stayed composed when it got tight",
    "say that was a good half to my team, 8-4 is a solid lead",
    "tell them GH, nine-three lead, don't get comfortable though",
    "say good half and let's not nine-three curse ourselves to my team",
    "let my team know GH, we outplayed them every execute this half",
    "tell my squad GH, the win condition is clear now, stay patient",
    "say good half, some of those rounds were ugly but we closed to my team",
    "tell them good half, we played smart under pressure and it showed",

    # -----------------------------------------------------------------------
    # GOOD GAME / GG — post-match, after win
    # -----------------------------------------------------------------------
    "tell my team good game after this match",
    "say GG to my squad",
    "let my teammates know GG, well played everyone",
    "tell the guys good game, we earned that",
    "say good game, we deserved the W to my team",
    "tell them GG WP, they gave us a run",
    "let my team know good game, we controlled from start to finish",
    "say GG to both teams, that was competitive",
    "tell my teammates good game, especially the last few rounds",
    "say GG to the other team too, they played hard",
    "let them know good game, clean win",
    "tell my squad GG, we were the better team today",
    "say good game, let's queue again to my team",
    "tell the guys good game, now let's review what we can improve",
    "let my teammates know good game, our comms were on point",
    "say GG and let's run it back to my team",
    "tell them good game, they made it close but we finished it",
    "let my team know GG, top performance from everyone",
    "say good game everyone to my squad, that was fun",
    "tell them GG, that's how we win ranked",
    "say good game and let's get another one going to my team",
    "let my teammates know GG, we never tilted and it paid off",
    "tell my squad good game, that comeback in the second half was real",
    "say GG WP to my team after that grind",
    "tell them good game, we outplayed them in all the right moments",
    "let my team know GG, we kept our cool when they were on a run",
    "say good game especially on attack side to my squad",
    "tell them GG, we defended beautifully in that second half",
    "say GG to my team, we did it the right way",
    "let my teammates know good game, we should be proud of that one",

    # -----------------------------------------------------------------------
    # GG EZ — taunting / trash-talk post-match
    # -----------------------------------------------------------------------
    "tell the other team GG EZ",
    "say GG EZ to the enemy team",
    "tell them GG easy to the other side",
    "say GG EZ they got bodied to my team",
    "let my team know GG EZ, we never felt it",
    "tell the enemy team good game, very easy",
    "say that was an easy GG to the other team",
    "tell my squad say GG EZ to them, we outclassed them",
    "say GG EZ it wasn't even close to the enemies",
    "tell the other side GG, comfortably easy",
    "say easy game to the enemy team",
    "tell them GG EZ, we lapped them twice",
    "say good game easy to the other team, no offense",
    "tell my teammates to say GG EZ in chat because that was easy",
    "let the enemy know that was an EZ GG from us",
    "tell the other team GG EZ, we were always in control",
    "say GG EZ they were a free lobby to my team",
    "tell them GG not even close, they never threatened us",
    "say GG EZ and thanks for the free RR to the enemy side",
    "tell my squad GG EZ, they were half-asleep",

    # -----------------------------------------------------------------------
    # GG AFTER A LOSS — sportsmanship, commiseration
    # -----------------------------------------------------------------------
    "tell my team GG, we'll get them next time",
    "say GG to my squad even though we lost",
    "let my teammates know GG, they were the better team today",
    "tell the guys GG, we fought hard",
    "say good game to my team even on the loss",
    "tell them GG, no shame in this loss, they outplayed us",
    "let my team know GG, we ran out of steam in the second half",
    "say GG to my squad, we'll review what went wrong",
    "tell the guys GG, we hit a rough eco and couldn't recover",
    "say good game they were just better to my team",
    "tell them GG, we'll hit back next game",
    "let my teammates know GG even though the result hurts",
    "say GG and let's go again to my squad",
    "tell my team GG, heads up, we were close on a lot of those rounds",
    "let them know GG, we actually played well but luck wasn't on our side",
    "say GG to the other team, they earned that win",
    "tell my team good game even though we threw that last half",
    "say GG to my squad and let's queue immediately",
    "tell the guys GG, don't tilt, we'll bounce back",
    "let my teammates know GG, one bad game doesn't define the session",
    "say good game, they just played a better default than us today",
    "tell my team GG and hold our heads up",
    "let them know GG, we should have won that but hats off to them",
    "say GG my team, that pistol loss hurt us the whole game",
    "tell them GG, we'll come back stronger on the next one",

    # -----------------------------------------------------------------------
    # CONGRATULATIONS — clutch, ace, team ace, thrifty
    # -----------------------------------------------------------------------
    "tell my team that was insane, congrats on the ace",
    "say holy moly to my squad after that ace",
    "let my teammates know that ace was unreal, well done",
    "tell the guys that was a crazy ace, best play of the match",
    "say congrats on the ace to whoever just did that",
    "tell my team that clutch was absolutely nuts",
    "let them know that 1v4 was one of the best rounds I've ever seen",
    "say congrats on the clutch to my teammate",
    "tell my squad that was an insane 1v3, we would have lost without that",
    "say GGs after that team ace, absolutely perfect to my team",
    "tell my teammates that team ace was beautiful, one kill each and zero deaths",
    "let my team know that was a thrifty win on eco, incredible",
    "say we just thrifted them, let's go to my squad",
    "tell the guys that win on eco was legendary, they had full rifles",
    "say that was a ridiculous clutch to my team after the 1v5",
    "tell them congrats on the thrifty, they never expected that",
    "let my teammates know the ace was clutch, that swung the match",
    "say that ace just won us the game, incredible to my squad",
    "tell my team good game but that ace was the highlight of the match",
    "say well done on the 1v2 clutch, that was textbook to my teammate",
    "tell my squad that team ace was a thing of beauty, one for the books",
    "let them know that thrifty might be the best round we've played all act",
    "say insane play to my team, that 1v4 defuse was impossible",
    "tell my teammates that clutch was some Radiant-level play",
    "say congrats to everyone on the team ace, perfect execution",

    # -----------------------------------------------------------------------
    # GOOD LUCK on specific rounds — eco, pistol, clutch upcoming
    # -----------------------------------------------------------------------
    "tell my team good luck on the pistol round",
    "say good luck on this eco round to my squad",
    "let my teammates know good luck on this force, play smart",
    "tell the guys good luck, we need to steal this round",
    "say good luck on the clutch to whoever's left alive",
    "tell my team good luck on this half buy, make it work",
    "let them know good luck on the bonus round, let's carry the guns",
    "say good luck on the pistol to my team and don't panic buy",
    "tell my squad good luck, this is a must-win round for the economy",
    "say good luck on the clutch, I believe in you to my teammate",
    "let my team know good luck on the 1v2, play slow",
    "tell them good luck on this full eco, don't feed rifles",
    "say good luck to whoever's left, play for time to my team",
    "tell my teammates good luck on the retake, we still have players alive",
    "say good luck on the execute, we have the util for it",
    "tell my squad good luck on this overtime round, it means everything",
    "let them know good luck on the pistol, we all start fresh",
    "say good luck on the ninja defuse to my teammate",
    "tell my team good luck, keep it together, we can win this round",
    "say good luck on the clutch, they're both one-shot to my teammate",

    # -----------------------------------------------------------------------
    # PRE-MATCH / AGENT SELECT GREETINGS — to the team, before the game
    # -----------------------------------------------------------------------
    "tell my teammates hey, good to be on your team this match",
    "say hi to my team in the agent select",
    "tell the guys hey what's up to start the lobby off right",
    "say yo let's run it to my squad at the start",
    "tell my team hey, glad we all got into the same lobby",
    "let them know hey what's good, let's play clean today",
    "say yo team, let's win this to my squad",
    "tell the guys what's up and ask if we have a designated IGL",
    "say hey team, let's communicate all game to my squad",
    "tell my teammates yo, good energy only today",
    "say what's up everyone, let's run some good strats to my team",
    "tell the guys hey, I'll call this game if nobody else wants to",
    "say yo what is up to my team in the pre-game lobby",
    "tell my teammates hi, let's play for fun and the W",
    "say good morning team, let's get the blood flowing with a win",
    "tell my squad hey, ggs on deck, let's go",
    "say yo let's get in formation, introduce yourselves to my team",
    "tell the guys hey, first round energy is everything, let's go",
    "say what's good to my team and say we're cooking today",
    "tell my teammates yo, we're the five best players in this lobby by default",

    # -----------------------------------------------------------------------
    # GOODBYE / FAREWELL / END-OF-SESSION to teammates
    # -----------------------------------------------------------------------
    "tell my team good games today, see you next time",
    "say GG and good night to my squad",
    "let my teammates know it was fun, good games, we'll run it again",
    "tell the guys good games, that was a great session",
    "say bye to my team and say good games",
    "tell them it was fun playing with you all to my teammates",
    "let my team know GGs and we're done for the night",
    "say good games everyone to my squad at the end of the session",
    "tell the guys thanks for the games, stay in touch",
    "say good run today to my team, we played well",
    "tell my teammates GGs and let's do this again tomorrow",
    "let them know it was a pleasure fragging with you all tonight",
    "say good games and get some rest to my team",
    "tell my squad GGs, tonight we ranked up as a team and individually",
    "say nice playing with everyone, let's queue again to my team",
    "tell the guys good session, we can improve but overall solid",
    "let my teammates know good games, I'm logging off but GGs",
    "say good games and thanks for the good comms to my team",
    "tell them it's been a pleasure, good games to my squad",
    "say good games to everyone in the lobby including the enemy team",

    # -----------------------------------------------------------------------
    # SARCASTIC / IRONIC GGs — close losses, throws, bad rounds
    # -----------------------------------------------------------------------
    "tell my team GG, we totally didn't just throw that from nine-three",
    "say GG to my squad, that comeback they ran on us was embarrassing",
    "let my teammates know GG, we completely nine-three cursed ourselves",
    "tell the guys GG, that was the most brutal throw in ranked history",
    "say GG in all caps to my team ironically",
    "tell them good game, we were up by so much and still found a way to lose",
    "let my team know GG, we're cooked, that was a certified throw",
    "say GG we bottomed out at the worst time to my squad",
    "tell my teammates GG, my fault, I should not have peeked that",
    "say what a game, GG, and we get to learn from this nightmare to my team",
    "let them know GG, whoever said nine-three leads are safe was lying",
    "tell my squad GG and let's never speak of that second half again",
    "say GG, the nine-three curse is real and it claimed us tonight to my team",
    "tell the guys GG, I tapped in too early, my bad, good game though",
    "say great game to my team completely sarcastically after that collapse",
    "tell my teammates GG, we did not deserve overtime but we got it so that's okay",
    "say GG what is actually happening to my squad mid-collapse",
    "let my team know GG, this is why we don't peek long on eco rounds",
    "tell the guys good game to my team after a ten-round losing streak",
    "say GG we had it and then we really really didn't to my team",

    # -----------------------------------------------------------------------
    # ROUND-WIN ACKNOWLEDGMENTS — after taking a round
    # -----------------------------------------------------------------------
    "tell my team let's go after we win that round",
    "say that's what I'm talking about to my squad",
    "let my teammates know nice round, we keep building",
    "tell the guys yes, let's go, to celebrate the round win",
    "say that's a round win, let's not overthink it to my team",
    "tell them good round, now we stay calm and do it again",
    "let my team know we got that, don't celebrate too long",
    "say yes, clean round, reset and go to my squad",
    "tell my teammates good round, the reads are starting to click",
    "say that's the round, one at a time to my team",
    "tell the guys nice work, we're getting into a rhythm",
    "let my team know good round, take a breath and set up for the next",
    "say that's the one, good round everyone to my squad",
    "tell them nice, we punished their eco perfectly that round",
    "let my teammates know good round, they threw everything at us and we held",
    "say that's how we execute to my team, good round",
    "tell my squad nice round, the timing on that entry was perfect",
    "let them know good round, our smokes won that site take",
    "say that round was clean start to finish to my team",
    "tell the guys good round, we're playing our best Valorant right now",

    # -----------------------------------------------------------------------
    # ROUND-LOSS ACKNOWLEDGMENTS — morale, reset, move on
    # -----------------------------------------------------------------------
    "tell my team it's okay, we reset and go again",
    "say it's fine, one round at a time to my squad after losing",
    "let my teammates know that's one round, shake it off",
    "tell the guys it's okay, next round is a clean slate",
    "say don't tilt, it's one round to my team",
    "tell them we'll bounce back, stay focused to my teammates",
    "let my team know it's fine, we played it right, they got lucky",
    "say shake it off to my squad after the bad round",
    "tell my teammates it's all good, reset your heads",
    "say one bad round doesn't lose the match to my team",
    "tell the guys it's okay, we learn from this and move on",
    "let my team know that's on me, sorry, let's regroup",
    "say it's fine, we're still in control of this match to my squad",
    "tell my teammates it's alright, our reads will catch up",
    "say don't stress about that round, next one is ours to my team",
    "tell the guys reset and let's come out clean next round",
    "let my team know we can fix that, no worries",
    "say it's just a round, it's fine to my squad",
    "tell my teammates don't let that round get in your head",
    "say next round, clean slate, let's go to my team",

    # -----------------------------------------------------------------------
    # OVERTIME greetings / morale
    # -----------------------------------------------------------------------
    "tell my team let's go, we're in overtime, anything can happen",
    "say we made it to OT to my squad with some hype",
    "let my teammates know overtime, let's close this out now",
    "tell the guys we're tied, overtime, one round at a time",
    "say OT let's go, I love overtime to my team",
    "tell them overtime means we're evenly matched, play your best to my squad",
    "let my team know it's OT, every round is a match point",
    "say we've come this far, let's not let it slip in OT to my team",
    "tell my teammates overtime, lock in, we've got the momentum",
    "say overtime one round at a time, no panic to my squad",
    "tell the guys OT, this is what we trained for",
    "let my team know overtime means anything can happen, stay composed",
    "say it's sudden death OT, let's make it count to my teammates",
    "tell them overtime, full buy, let's execute to my team",
    "say overtime and we're buying full this round to my squad",
    "tell my team GG almost, overtime here we go",
    "let my teammates know great game so far, now let's win this OT",
    "say OT is good, it means they couldn't close us out to my team",
    "tell the guys overtime, our comms need to be perfect right now",
    "say we're going to overtime baby, let's take it to my team",

    # -----------------------------------------------------------------------
    # ENCOURAGING / MORALE GREETINGS — don't tilt, stay together
    # -----------------------------------------------------------------------
    "tell my team we've got this, stay positive",
    "say stay together guys to my squad",
    "let my teammates know heads up, we can still win this",
    "tell the guys don't tilt, we're better than this score suggests",
    "say keep your chins up to my team",
    "tell them we're fine, just breathe and play to my squad",
    "let my team know we've been in worse spots and won, keep going",
    "say we're still in this to my teammates",
    "tell my squad let's stay calm and trust each other",
    "say don't panic, we've got enough rounds to turn this around",
    "tell the guys good vibes only, let's grind it out",
    "let my team know we're not dead yet, let's go",
    "say we've played great rounds today, this is just a dip to my team",
    "tell my teammates stay locked in, the comms are still good",
    "say we win these to my squad about the current map situation",
    "let them know we just need to string two or three rounds together",
    "tell the guys we are going to be fine, trust the process",
    "say I believe in this team to my squad",
    "tell my teammates heads down, grind this match out, we win",
    "say it's not over till it's over, we keep fighting to my team",
    "let my team know everyone stay calm and just play your game",
    "tell the guys we're a good team having a rough patch, not a bad team",
    "say stay together, we've almost pulled comebacks from worse to my team",
    "tell my teammates good energy, we can feel the tide turning",
    "say keep communicating, as long as we talk we have a chance to my team",

    # -----------------------------------------------------------------------
    # ANTI-TILT / CALMING GREETINGS mid-match
    # -----------------------------------------------------------------------
    "tell my team to calm down and stop getting tilted",
    "say everybody breathe to my squad",
    "let my teammates know less rage, more game",
    "tell the guys stop tilting and play your game",
    "say calm down and focus to my team",
    "tell them no rage comms, clean communication only to my squad",
    "let my team know cut the negativity, we need clean calls",
    "say less complaining more playing to my teammates",
    "tell my team it's ranked, not the World Championship, relax",
    "let them know bad comms cost us rounds, let's go quiet and clean",
    "say to my team everybody take a deep breath between rounds",
    "tell my squad stop blaming each other and focus forward",
    "say it's okay to make mistakes, just learn and move on to my team",
    "tell the guys no raging in vc, we're here to win not argue",
    "say clean comms from here on out to my team",
    "tell my teammates save the blame for after the match, play now",
    "let my team know we play better when we're calm, so calm down",
    "say to my squad no ego, no tilt, just Valorant",
    "tell the guys take it one round at a time and chill out",
    "say positive comms only, it genuinely makes us better to my team",

    # -----------------------------------------------------------------------
    # RIVAL TEAM / ENEMY TEAM greetings and acknowledgments
    # -----------------------------------------------------------------------
    "say good game to the enemy team at the end",
    "tell the other team GG WP, they played well",
    "say good luck to the enemy team at the start of the match",
    "tell them GLHF to the other side",
    "say good game they played better than us to my team about the enemy",
    "tell the enemy team good half after the first twelve rounds",
    "let the other team know good game, they had better utility usage",
    "say GG to both sides equally, it was a clean match",
    "tell the enemies gg, they were hard to play against",
    "say hats off to the other team, they held B flawlessly to my teammates",
    "tell my team say GG to the enemy side, be respectful",
    "say shoutout to the enemy Cypher, those trips were everywhere to my team",
    "let the other team know good game via my team's voice",
    "tell my teammates the enemy played a great match, give them a GG",
    "say well played enemy team, you earned the win",
    "tell the other side good game, we'll get you next time",
    "say gg to the enemy, their coordination was actually impressive to my team",
    "tell the enemy team good game through voice chat",
    "let my team know to say GG in voice to the other side too",
    "say their Sage was a battle Sage but effective, GG to them to my team",

    # -----------------------------------------------------------------------
    # SPECIFIC CONGRATS CALLS — Radiant plays, clutch moments
    # -----------------------------------------------------------------------
    "tell my team that was Radiant-level play right there, incredible",
    "say that was top-500-worthy to my squad after that outplay",
    "let my teammates know that's the best play I've seen this act",
    "tell the guys that 1v5 was legitimately pro-level",
    "say that play deserves a clip in the highlights to my team",
    "tell my teammates that flick was inhuman, nice shot",
    "say I have no idea how you won that 1v4 to the player who just clutched",
    "tell my squad that was a god-tier round, no other way to describe it",
    "let them know that defuse was legendary, we thought it was over",
    "say I can't believe we just won that to my team",
    "tell the guys that was the clutch of the session right there",
    "say that ace broke their morale, this changes the match to my team",
    "tell my teammates that was a carry performance, incredible individual effort",
    "say you're not normal for pulling that off to the clutch player",
    "let my team know that's going in the session VOD as the best round",
    "tell my squad that play single-handedly swung the match, well done",
    "say insane clutch, I actually stood up to my team",
    "tell the guys let's go after that insane ace, momentum is ours",
    "let my teammates know that was textbook 1v2 execution, calm and clean",
    "say that's the most impressive round I've seen all week to my squad",

    # -----------------------------------------------------------------------
    # CLOSING OUT THE MATCH — final round GGs, celebrations
    # -----------------------------------------------------------------------
    "tell my team we won, good game everyone",
    "say we got it, GG to my squad",
    "let my teammates know that's thirteen rounds, we won, GG",
    "tell the guys good game, we won that cleanly",
    "say we closed it out, let's go to my team",
    "tell them we won, don't gloat, just GG to my squad",
    "let my team know we close the match out right here, GG",
    "say that's the match, good game to my teammates",
    "tell the guys good game, we took it convincingly",
    "say we finished it, GG WP to my squad",
    "tell my team match point, let's not throw it",
    "let them know it's match point, one more clean round",
    "say it's match point, play to win not to not lose to my team",
    "tell my teammates match point, stay focused, don't celebrate early",
    "say match point let's execute perfectly to my squad",
    "tell my team match point, full buy, full comms, let's seal it",
    "let the guys know match point, this is ours, don't stop now",
    "say match point and we finish this to my teammates",
    "tell my squad match point, win it for the good comms we had all match",
    "say match point, let's dedicate this round to the team to my team",

    # -----------------------------------------------------------------------
    # THANKS TO SPECIFIC TEAMMATE ROLES (relay-flavored gratitude)
    # -----------------------------------------------------------------------
    "tell my team thanks to whoever was IGLing, the calls were on point",
    "say tell our Sage good heals tonight to my team",
    "let my teammates know our Cypher had incredible info all game",
    "tell the guys shoutout to our Breach, those flashes were perfectly timed",
    "say tell the Brimstone thanks for the smokes, they were all crisp",
    "tell my team shoutout to our Killjoy, that lockdown changed the game",
    "let them know our Sova had great recon arrows all match",
    "say shoutout to the entry fragger, he cleared the way every round",
    "tell my squad thanks to whoever traded me every time I died, I see you",
    "let my teammates know the lurker plays today were elite, shoutout",
    "say tell the Skye her dogs were everywhere to my team",
    "tell the guys the Viper wall on that site take was incredible",
    "say shoutout to our Jett, every dash was exactly right to my team",
    "let my team know the Omen teleport flanks were disgusting, well done",
    "tell my squad shoutout to the one who saved the match with that final clutch",
    "say tell our Gekko the Wingman plants were so helpful to my team",
    "let them know our Fade haunts were putting the enemy everywhere",
    "tell my teammates shoutout to the anchors, they held sites when we rotated",
    "say shoutout to whoever bought me a rifle that round, you saved me to my team",
    "tell the guys big up to the whole team, everyone contributed that match",

    # -----------------------------------------------------------------------
    # POST-LOSS SPORTSMANSHIP — graceful defeat acknowledgment
    # -----------------------------------------------------------------------
    "tell my team GG, they outclassed us mechanically",
    "say good game to my squad, they were better today and we accept that",
    "let my teammates know GG, we learn from this and come back harder",
    "tell the guys good game, they had better reads all match",
    "say GG to my team, we need to revisit our default setup",
    "tell them good game, their economy management beat ours completely",
    "let my team know GG, their smokes were more disciplined than ours",
    "say GG to my squad, we played well on attack but defense fell apart",
    "tell my teammates GG, those first four rounds set the wrong tone",
    "say good game and let's not make excuses to my team",
    "tell the guys GG, they played a patient default and we never adapted",
    "let my team know good game, they were well-coordinated and we weren't",
    "say GG to my squad, the eco management broke us in the second half",
    "tell my teammates good game, credit to them for a great performance",
    "say GG we had stretches of good play but couldn't sustain it to my team",
    "tell the guys GG, no excuses, they earned it",
    "let them know good game, our clutch rate was lower than theirs and that's why we lost",
    "say GG to my team and let's queue the next one with better comms",
    "tell my teammates GG, I'm proud of how we competed even in a loss",
    "say good game, they were the better five today to my squad",

    # -----------------------------------------------------------------------
    # GENERAL RAPPORT / BANTER GREETINGS during the match
    # -----------------------------------------------------------------------
    "tell my team I love playing with you guys",
    "say you guys are actually a lot of fun to play with to my team",
    "let my teammates know I'm glad we ended up in the same lobby",
    "tell the guys this is the most fun ranked game I've had this week",
    "say you guys have great comms, honestly to my team",
    "tell my squad I appreciate the good communication today",
    "let them know this team is gelling, I can feel it",
    "say tell my team that this is some of the best ranked I've played",
    "tell the guys I'm honoured to be on this squad right now",
    "say this is what Valorant is supposed to feel like to my team",
    "tell my teammates you guys actually listen to calls, it's refreshing",
    "say good vibes in this lobby to my team",
    "let my team know we should five-stack some time, we have good chemistry",
    "say honestly five-stack these guys to my squad after this match",
    "tell the guys I'd play with every one of you again",
    "let my team know good game energy, this is why I play ranked",
    "say this is what clean comms looks like to my team",
    "tell my teammates you guys made this match fun even when it was hard",
    "say shoutout to this whole lobby, no toxicity all game to my team",
    "tell the guys we should all add each other after this match",

    # -----------------------------------------------------------------------
    # FAREWELL TO LEAVING PLAYERS / lobby changes
    # -----------------------------------------------------------------------
    "tell whoever is leaving good games, see you around",
    "say good games and good luck with the rest of your session to my leaving teammate",
    "let the team know good run, thanks for the games",
    "tell any leavers good luck in future ranked games",
    "say good playing with you to anyone who has to leave after the match",
    "tell my team thanks for the session, good games all around",
    "let my teammates know it was a pleasure, GGs",
    "say GGs and hope to see you in the ranked queue again to my team",
    "tell the guys good games, take care of yourselves out there",
    "say see you in the next lobby to my team",
    "let my teammates know good games, I'm heading off but this was fun",
    "tell the guys good luck with your next session, GGs",
    "say stay hydrated and good luck with the ranking grind to my team",
    "tell my squad GGs, I'm done for tonight, great playing with you",
    "say good games everyone, go get some rest to my team",
    "let them know this was a great session, GGs and take care",
    "tell my teammates good games, you're all solid players",
    "say thanks for the energy today, GGs to my team",
    "tell the guys stay positive in future lobbies, good games",
    "say GGs and see you all in a future lobby to my whole team",

    # -----------------------------------------------------------------------
    # VARIETY EDGE CASES — unusual registers, long-form, regional voice
    # -----------------------------------------------------------------------
    "bruv tell my team good game that was mad",
    "tell my squad ggs mate, that was a proper banger of a match",
    "say well played lads to my team after the win",
    "tell my team gg fam, we played clean start to finish",
    "say ggs gang to my squad",
    "tell my crew ggs, that was a vibe to my teammates",
    "say good game dawg to my team in voice",
    "tell my teammates gg bestie, that was a fun one",
    "say ggs homies to my squad",
    "let my team know gg no cap we dominated that lobby",
    "tell the guys gg frfr to my team in voice",
    "say good game on God to my squad",
    "let my teammates know that was lowkey one of the best matches I've played gg",
    "tell the guys gg istg we played so well today",
    "say gg and that's on the algorithm to my team",
    "tell my squad gg we're goated no notes",
    "let my team know that was a certified banger, gg",
    "say gg bro we actually cooked this lobby to my team",
    "tell my teammates gg bestie that defuse was peak",
    "say gg they were actually decent but we were more decent to my squad",
    "tell my team that was a real team game, gg from me to everyone",
    "let the guys know gg this lobby was actually a sweat fest but we survived",
    "say gg and we shall never speak of that second half again to my squad",
    "tell my team gg the nine-three curse almost got us but we held strong",
    "say gg lads now we watch the VOD and find out why we struggled on B to my team",
    "tell my teammates gg but our eco discipline needs work, noted for next session",
    "say gg our Sage heals literally saved three rounds, shoutout to my squad",
    "tell the guys gg and please add me so we can five-stack next time",
    "say good game everyone, our comms were actually the MVP today to my team",
    "tell my team gg and that's how you close a match, no drama, just W",

    # -----------------------------------------------------------------------
    # MATCH START RITUALS / VIBES CHECK
    # -----------------------------------------------------------------------
    "tell my team vibes check, everyone good?",
    "say to my squad are we ready to go this game",
    "let my teammates know everyone warmed up and ready?",
    "tell the guys are we all feeling it today, let's lock in",
    "say vibe check before round one to my team",
    "tell my team let's start this match with good comms and good energy",
    "let them know we're setting the tone from round one to my teammates",
    "say are we feeling the win tonight to my squad",
    "tell my team energy check, I need everyone switched on",
    "let my teammates know let's start with a pistol win and build from there",
    "say first round is key, let's not throw the pistol to my team",
    "tell the guys let's play the pistol round perfectly to my squad",
    "say we are winning this pistol and this match to my team",
    "tell my team okay fresh lobby let's make some noise",
    "let them know let's out-comm them from round one to my squad",
    "say match starts now, good luck and have fun everyone to my teammates",
    "tell my team alright we're going to win this and have fun doing it",
    "say everyone breathe and let's just play Valorant to my squad",
    "let my team know it's just a game, let's enjoy it and pick up the W",
    "tell the guys same energy we had at the start of the last win, let's go",

    # -----------------------------------------------------------------------
    # ADDITIONAL VARIETY — unique registers, post-game reflection, multi-round flow
    # -----------------------------------------------------------------------
    "tell my team nice carry tonight, everyone pulled their weight",
    "say tell my squad we played elite Valorant in that last map",
    "let my teammates know that's a clean thirteen-two win, absolute dominance",
    "tell the guys that win felt good, crisp comms from start to finish",
    "say gg to my team, we executed on everything we talked about",
    "tell my squad good game and our retakes were elite today",
    "let my team know good game, we peaked at the right moment",
    "say good game we're the most disciplined team in this elo to my squad",
    "tell the guys gg and I'm hyped up after that win",
    "say tell my team that win just shot my RR up nicely",
    "let my teammates know gg that was satisfying, we earned every round",
    "tell my squad gg and the shotcalling was on another level today",
    "say good game everyone to my team, one of our cleanest wins this session",
    "tell the guys good game no wasted utility, that was textbook",
    "let my team know good game, that comeback from five-eight down was insane",
    "say tell my teammates gg and I'd run it back with this team every day",
    "tell the guys gg, our entry timing was beautiful this match",
    "say gg to my team, our post-plant setups were immaculate",
    "let my teammates know gg, the lurk plays flipped two rounds minimum",
    "tell my squad gg, that might be our best team game all act",

    "say to my team that was a proper fight and we won it, gg",
    "tell my teammates gg, nothing fluky, we outplayed them step by step",
    "say gg my squad, we're peaking and I can feel it",
    "tell the guys good game, that eco frag was the turning point",
    "let my team know gg and we never gave up even at five-nine down",
    "say gg to my squad, the defense was a brick wall today",
    "tell my teammates good game, those crossfires on B were immovable",
    "let my team know gg, the enemy gave up mid and we punished it perfectly",
    "say good game everyone, we're starting to look like a five-stack to my team",
    "tell the guys gg and I love how we swapped strategies mid-match",
    "say gg we actually out-stratted them to my team, feels good",
    "tell my squad gg we were five steps ahead the whole second half",
    "let my teammates know gg, that split execute on A was our best one this week",
    "say good game to my squad, we didn't throw when we had the lead, that's growth",
    "tell the guys gg and our spike management at the end was ice cold",
    "let my team know gg, no tilting, no blame, just good Valorant",
    "say tell my team gg and our eco management was so much cleaner today",
    "tell the guys good game, we killed zero rifles on eco rounds, perfect",
    "say gg and the fake on C completely broke their defense to my team",
    "tell my teammates gg, the timing on that A rush was pitch perfect",

    "say gg to my team, I think we hit a new peak today",
    "tell the guys gg and honestly we were the better team from round one",
    "say gg from the bottom of my heart to my squad, that was a blast",
    "let my team know gg and thank you for the clean comms all game",
    "tell my teammates gg and whoever made that last call, genius level",
    "say gg to my team, we stayed cool when they threatened to comeback",
    "tell my squad good game and let's keep this energy in the next queue",
    "let my team know gg and if we play like that every game we're climbing fast",
    "say good game and I'm proud of this team to my squad",
    "tell the guys gg and the trade discipline was impeccable today",

    "say gg and glhf next game to both teams from me to my team",
    "tell my teammates okay that was tough but gg they earned it",
    "say gg and they played us like a piano to my team after the loss",
    "tell the guys gg, their viper setup was prepared specifically for us",
    "let my team know gg, we scouted wrong and they punished it, respect",
    "say gg to my squad, that was a true 50-50 match and it could have gone either way",
    "tell my teammates gg even though we lost, we played good Valorant",
    "say good game to my team, we gave ourselves chances and that's all you can do",
    "tell the guys gg and we should never have given up that mid control",
    "let my team know gg and the lesson is don't peek the op without utility",

    "say gg and let's grab water before the next game to my team",
    "tell my squad gg and let's debrief quickly then queue again",
    "say gg to my team and take five then we're going again",
    "tell the guys gg and same time tomorrow to my teammates",
    "let my team know gg and great session, we hit our goals today",
    "say gg to my squad and we're done grinding for the day",
    "tell my teammates gg and I'll review the replay tonight",
    "say gg to my team, tonight was productive, we improved real things",
    "tell the guys gg and we'll go over comms after this to my squad",
    "let my team know gg, take a break, come back fresh for the next session",

    "tell my team good luck on your placement matches this act",
    "say glhf on your rankeds today to my squad before we split",
    "let my teammates know good luck grinding this act, you've got the skills",
    "tell the guys keep it up, good luck with the rank push",
    "say gl on the climb to my team, see you at Immortal",
    "tell my squad good luck with the act grind, these games matter",
    "let my team know glhf in the next match after I leave",
    "say good luck on act finals to my teammates",
    "tell the guys I'll be rooting for you all in ranked, good luck",
    "say gg and good luck reaching Radiant this act to my squad",
]
