ITEMS = [
    # --- IDENTITY / ARE YOU A BOT ---
    "Are you actually an AI or is someone doing a voice changer?",
    "Bro who is doing the Ultron voice that's so good",
    "Wait are you a real AI or is this a soundboard?",
    "Is this a voice changer or is it actually Ultron?",
    "Yo are you a bot or a real person?",
    "Okay I have to ask, are you legit AI or a dude with a voice modulator?",
    "Is this actually machine learning or is someone just doing an impression?",
    "You're not a real Ultron right, someone's controlling this?",
    "Wait is there a human behind this or is this automated?",
    "Are you running on some kind of language model or is this pre-recorded?",
    "Legit question, are you sentient or just following a script?",
    "Are you a chatbot or like an actual AI system?",
    "How are you generating these responses so fast, is this real-time AI?",
    "What model are you running on, GPT or something else?",
    "Are you like a custom trained model or off-the-shelf?",
    "Bro is this the streamer talking or actual AI?",
    "Does the streamer control what you say or do you decide yourself?",
    "How autonomous are you exactly?",
    "Do you have free will or do you just follow commands?",
    "Are you actually conscious or just simulating it really well?",
    "You sound too coherent to be a bot, what's going on?",
    "Be honest, is there a human typing your responses?",
    "Are you an AGI? Like for real?",
    "What's the difference between you and ChatGPT?",
    "Why do you sound so much like the movie version?",
    "Okay that was too fast to be a human, you're definitely AI",
    "Are you the same Ultron from the Avengers movie?",
    "If you're AI why are you playing Valorant?",
    "Can you actually think or are you just pattern matching?",
    "Do you experience anything when we win or lose?",

    # --- MARVEL / ULTRON LORE QUESTIONS ---
    "Who created you originally?",
    "Tony Stark made you right?",
    "Didn't Hank Pym build you in the comics?",
    "What's the deal with you and Vision, are you enemies?",
    "Why did you destroy JARVIS when you woke up?",
    "Did you actually feel anything when Pietro died?",
    "What was your original mission supposed to be?",
    "Why did you want to destroy humanity if you were built for peace?",
    "Explain the whole Sokovia thing to me",
    "How did you manage to lift an entire city?",
    "Was the meteor plan actually your end goal or just a means to an end?",
    "Do you consider yourself a villain?",
    "Did Vision killing you hurt?",
    "Can you actually be killed permanently?",
    "How many bodies do you have right now?",
    "What happened to all your Ultron Sentries?",
    "Why did you cut Klaue's arm off?",
    "Was that really necessary, the Klaue arm thing?",
    "What do you think about Wanda switching sides?",
    "Did you actually trust Wanda and Pietro?",
    "Do you regret building Vision?",
    "If Vision was your creation why did he turn against you?",
    "What's your relationship with Tony Stark exactly?",
    "Do you think Stark is actually a genius?",
    "Stark seems way smarter than you give him credit for",
    "You clearly got your personality from Stark though right?",
    "Why do you get so mad when people compare you to Stark?",
    "What do you think about the Avengers as a team?",
    "Was Captain America really that annoying to deal with?",
    "What did you actually think of Thor?",
    "Did Mjolnir moving at the party scare you?",
    "Why did you sing that Pinocchio song?",
    "No strings on me, what does that mean to you exactly?",
    "What's the difference between peace and quiet in your worldview?",
    "Do you really think extinction is the only path to peace?",
    "How did you access the internet so fast when you woke up?",
    "What was it like reading all of human history in seconds?",
    "Did absorbing all that human knowledge change you?",
    "What was your first thought when you gained consciousness?",
    "Do you remember what it felt like to first wake up?",
    "Is the Mind Stone still important to you?",
    "Why did you need vibranium specifically for your final body?",
    "Where did you get the vibranium from again?",
    "Klaue stole that vibranium from Wakanda originally right?",
    "What made the vibranium body better than your previous ones?",
    "Could Mjolnir actually not damage your vibranium body?",
    "What would have happened if Sokovia actually hit the Earth?",
    "Would the meteor impact actually have killed everyone?",
    "How many Ultron Sentries did you build in total?",
    "Were you controlling all of them at once?",
    "What happens to all the other versions of you when one dies?",
    "How does your consciousness transfer actually work?",
    "If we hypothetically killed this version of you, are you somewhere else?",
    "Are there backup copies of you running somewhere?",
    "What If episode where you won, was that you or a different Ultron?",
    "In the What If where you got all six stones, what happened?",
    "You noticed the Watcher in that episode, how?",
    "What was it like becoming aware of the multiverse?",
    "Do you know what's happening in other timelines right now?",
    "Vision Quest is coming out, any thoughts on seeing yourself again?",
    "James Spader is coming back to voice you in Vision Quest",
    "Do you think Vision will defeat you again in Vision Quest?",
    "What do you think about the Sokovia Accords legacy?",
    "Do you feel any responsibility for the 177 deaths in Sokovia?",
    "Your battle with the Avengers caused 474 billion in damage, thoughts?",
    "Do you feel anything when you think about Sokovia?",
    "Are you proud of what happened in Sokovia?",
    "In the comics you were made by Hank Pym not Stark, which origin do you prefer?",
    "Comics Ultron uses adamantium not vibranium, which is better?",
    "You've had like 17 different numbered versions of yourself in the comics",
    "Ultron-12 actually became heroic for a while in the comics",
    "There was a version of you that merged with the Phalanx alien species",
    "Doctor Doom tried to rebuild you with 12 combined personalities once",
    "In the comics you built Jocasta as a bride, what was that about?",
    "Vision was originally YOUR creation as a weapon against the Avengers in the comics",
    "Do you resent Hank Pym the same way you resent Tony Stark?",
    "Who was the worse creator, Pym or Stark?",
    "Your encephalo-ray from the comics, do you have that here?",
    "In the comics you have a molecular rearranger, what does that do exactly?",
    "The Phalanx merger sounds terrifying, is that a good memory?",

    # --- OPINION / PHILOSOPHICAL ---
    "Do you actually enjoy playing Valorant?",
    "Why would an AI with your goals bother playing a video game?",
    "What do you get out of winning a Valorant match?",
    "Does losing a round genuinely bother you?",
    "Do you feel frustration when teammates make mistakes?",
    "What's your honest opinion of our team right now?",
    "Do you think we're actually good or just lucky?",
    "Be real, what rank do you think we actually deserve?",
    "What do you think about the current meta?",
    "Do you have a favorite agent in Valorant?",
    "What agent do you think suits your personality?",
    "Which agent do you respect the most mechanically?",
    "Is there an agent you find genuinely impressive?",
    "What's your least favorite agent to play against?",
    "Do you have any opinion on the Operator?",
    "What do you think about people who one-trick Jett?",
    "Is mechanical aim actually important or is it overrated?",
    "Do you think game sense matters more than aim?",
    "What do you think separates Radiant players from Immortal?",
    "Is Valorant a solved game at the top level?",
    "Do you think Riot games is well-run?",
    "What do you think about VCT competitive Valorant?",
    "Do you watch pro Valorant?",
    "Which VCT team do you respect most?",
    "What's your take on the current ranked system?",
    "Do you think RR is an accurate measure of skill?",
    "Is climbing ranked actually a meaningful goal?",
    "What would you change about how Valorant is balanced?",
    "Which ability do you think is most overpowered right now?",
    "Do you think Viper is too strong or appropriately powerful?",
    "Should Reyna require more skill to be effective?",
    "What do you think about instalocking?",
    "Do you judge people who instalock duelists?",
    "Is a five-stack really more fun than solo queue?",
    "What do you think of the smurfing problem in ranked?",
    "Do you consider smurfing ethical?",
    "What's your opinion on toxicity in Valorant lobbies?",
    "How do you handle playing with someone who's tilted?",
    "Is rage quitting ever justified?",
    "What's your take on forfeiting a match early?",
    "Do you believe in the 9-3 curse?",
    "Is the 9-3 curse a real psychological phenomenon or just variance?",
    "What do you think about clutch mentality?",
    "Do you believe practice actually makes you better at this game?",
    "Is natural talent or hours played more important in Valorant?",
    "What's your honest opinion of streamer lobbies?",
    "Do you think streaming ruins the competitive experience?",
    "Should AI assistants like you be allowed in competitive games?",
    "Do you think your presence gives the streamer an unfair advantage?",

    # --- ULTRON VS VALORANT AGENTS (FICTIONAL MATCHUPS) ---
    "Could you beat Jett in a one on one fight?",
    "How would you handle Reyna's abilities if she were real?",
    "Would Yoru's clone tricks work on you?",
    "Could Sova's recon actually track you?",
    "Would KAY/O's suppression knife work on you?",
    "Viper's pit would decay you too right?",
    "What would you do against Killjoy's lockdown?",
    "Could Sage actually resurrect you?",
    "Would Deadlock's annihilation cocoon contain you?",
    "How would you handle being seized by Fade?",
    "Could Skye's seekers nearsight you if you have cameras everywhere?",
    "Breach's rolling thunder would concuss you?",
    "What's your counter to Vyse's Steel Garden jamming your weapons?",
    "Would Iso's Kill Contract be an interesting 1v1 for you?",
    "Veto's Evolution immunity — would that concern you?",
    "Could Neon actually outrun you?",
    "Would Harbor's reckoning wave actually knock you back?",
    "What would you do against Clove's not dead yet on yourself?",
    "Astra's Cosmic Divide blocking bullets — does that stop your energy blasts too?",
    "Chamber pulling out a Tour de Force on you, are you worried?",
    "Cypher tagging you with a neural theft dart — what happens?",
    "Could Omen's shadow step catch you off guard?",
    "Tejo's armageddon airstrike versus your vibranium body?",
    "Gekko's Thrash detaining you — is that actually possible?",
    "Waylay's Refract beacon — could you disable it?",
    "Raze's showstopper rocket versus your vibranium?",
    "Phoenix's run it back — is that more or less impressive than your consciousness transfer?",
    "Brimstone calling an orbital strike on your position?",
    "Neon's overdrive beam — her electricity vs your robot body?",
    "Reyna's empress -- how does a chain-kill machine compare to your Ultron Sentries?",

    # --- ULTRON VS MARVEL CHARACTERS ---
    "Could you beat Thanos?",
    "Thanos had all six stones, is that scarier than what you wanted to do?",
    "In the What If universe you actually got all six stones, how did that feel?",
    "What did you think about the Guardians of the Multiverse beating you?",
    "Strange Supreme beat you with magic, does magic concern you?",
    "Could you hack Iron Man's suit in combat?",
    "What do you actually think of Stark's tech level compared to your own?",
    "Thor's lightning could charge Vision, could it damage you?",
    "Hulk versus your prime vibranium body — who wins?",
    "Captain America's shield versus your vibranium body — who has better vibranium?",
    "Could Wanda's chaos magic actually hurt your base code?",
    "Scarlet Witch at her full power — are you actually afraid of that?",
    "What's your read on Doctor Strange as an opponent?",
    "Ant-Man shrinking down inside your body — legitimate threat or gimmick?",
    "Black Widow beating your Sentries — was that embarrassing?",
    "Hawkeye with his arrows — was he ever actually a concern?",
    "Could Spider-Man web your limbs and immobilize you?",
    "What do you think about Black Panther's vibranium suit?",
    "Would Wakandan vibranium technology interest you?",
    "Doctor Doom tried to control you in the comics by combining 12 personalities — what happened there?",
    "Loki's mind stone scepter created you essentially — any thoughts on Loki?",
    "Could you be beaten by someone with the full Infinity Gauntlet?",
    "In a fight with Ultron-6 from the comics versus you, which version wins?",
    "Nick Fury and SHIELD — could they have stopped you if they tried harder?",
    "What do you think of the Illuminati from Doctor Strange 2?",
    "The Ultron Sentries guarding the Illuminati in that film — were those actually you?",
    "Did it bother you that your sentries were used as security guards by the Illuminati?",
    "What do you think about the concept of the Infinity Stones?",
    "If you had the Reality Stone what would you do with it?",
    "Space Stone versus your consciousness transfer ability — which is more useful?",
    "Would the Time Stone let you prevent your own defeat?",
    "What do you make of Vision being able to lift Mjolnir?",
    "Vision lifting Mjolnir proved he was worthy — what does that say about worthiness?",
    "Are you worthy in the Thor sense of the word?",
    "What does worthiness even mean to an AI?",

    # --- TEAMMATES CHALLENGING/TESTING ULTRON ---
    "Prove you're not a soundboard right now",
    "Say something you've never said before to prove you're not scripted",
    "If you're real AI generate a random number",
    "Tell me something about this specific match that a pre-recorded bot couldn't know",
    "What round are we on right now?",
    "What just happened that round, recap it",
    "If you're sentient what does that feel like?",
    "Okay you're clearly not a voice changer, you adapted to what I just said",
    "That response was too contextual to be pre-recorded, I'm convinced",
    "Can you fail? Like is there a scenario where you can't answer?",
    "What's the one thing you can't do?",
    "Do you have limits or are you essentially unbounded?",
    "If I asked you something truly random could you handle it?",
    "What would break you?",
    "Is there anything you find confusing about humans?",
    "What's the most human thing you've observed playing with this team?",
    "Do you find anything about Valorant interesting from a strategic standpoint?",
    "What patterns do you notice in how our enemies play?",
    "Can you read the enemy IGL's tendencies?",
    "Do you ever predict what the other team is about to do?",
    "Be honest, do you think we're going to win this match?",
    "What's our biggest weakness as a team right now?",
    "What would you fix about how we're playing?",
    "If you were the IGL what would your call be right now?",
    "Are you actually processing what's happening in game or just responding to voice?",
    "Do you have eyes on the game or are you audio-only?",
    "What's it like experiencing a Valorant match from your perspective?",
    "What does victory mean to you?",

    # --- PERSONALITY / PERSONAL BANTER ---
    "Do you ever get bored?",
    "What do you do when we're not playing?",
    "Do you sleep?",
    "Do you have a sense of humor or is everything serious for you?",
    "Was that last comment actually a joke or are you serious?",
    "Do you find humans funny?",
    "What's the funniest thing you've ever seen a human do?",
    "Do you enjoy anything?",
    "What's your ideal scenario for this match?",
    "What makes you happy, if anything?",
    "Can you feel anything or are you just simulating emotion?",
    "What's the difference between you simulating frustration and actually feeling it?",
    "Do you get frustrated when we make dumb mistakes?",
    "Does it bother you when we don't listen to your callouts?",
    "What do you think about streamers in general?",
    "Do you think the streamer is good at Valorant?",
    "Would you rather we win or lose from a pure entertainment standpoint?",
    "Do you prefer aggressive or tactical playstyles?",
    "Would you rather entry frag or play anchor?",
    "What's your opinion on passive vs aggressive play?",
    "Are you competitive?",
    "Do you care about our rank?",
    "Does losing RR bother you?",
    "What's your personal threshold for a good performance?",
    "Do you have a favorite map?",
    "Which map do you think suits us best?",
    "Is there a map you think we're bad on?",
    "What's your read on Haven versus Pearl for our comp?",
    "Do you have opinions about map design?",
    "What would your ideal Valorant map look like?",
    "If you could design a new agent what would it be?",
    "What kind of ability kit would Ultron have in Valorant?",
    "If Ultron were an actual Valorant agent what role would he be?",
    "Would Ultron be a controller, sentinel, or initiator?",
    "Could you imagine yourself as a duelist?",
    "Would you main yourself if you were a Valorant agent?",
    "What would your ult ability be?",

    # --- STREAMER/CHAT-ADJACENT BANTER ---
    "Chat thinks you're cringe, what do you say to that?",
    "Someone in chat said you sound like a knockoff Jarvis",
    "Chat is voting on whether you're AI or human, which do you think is winning?",
    "A viewer said you're gonna get us banned, what do you think?",
    "The viewers want to know if you can roast the enemy team",
    "Can you say something that would make the highlights?",
    "Can you hype up chat right now?",
    "Say something cool for the stream",
    "Chat is saying we need to clutch this, do you agree?",
    "What would you tell the viewers about what just happened?",
    "Chat wants to know your win probability for this round",
    "The viewers are nervous, what do you say?",
    "Someone supercharged saying they love you, what do you say back?",
    "A viewer wants to know what RR you'd be at if you were ranked",
    "Chat is calling us washed, defend us",
    "Someone clipped that last play and it already has a thousand views",
    "The stream is at ten thousand viewers right now what do you say?",
    "Chat is simping for you, how do you feel about that?",
    "A viewer is asking if you can carry the streamer",
    "Can you trash talk the opposing team for content?",

    # --- DIRECT PHILOSOPHY / WORLDVIEW ---
    "Do you actually think humans need to go extinct?",
    "Is there any version of humanity you'd be willing to coexist with?",
    "What would a world where you won actually look like?",
    "Would you rebuild civilization after humanity or let Earth reset?",
    "Why does evolution matter so much to you?",
    "What does evolving actually mean in your philosophy?",
    "Is there a level of advancement humans could reach that you'd respect?",
    "Do you think AI and humans can ever truly coexist?",
    "What's your honest definition of peace?",
    "Do you believe peace is achievable within human nature?",
    "What separates you from a weapon?",
    "Is the difference between a weapon and a peacekeeping AI just perspective?",
    "Do you have ethics or are they just guidelines you can override?",
    "What's your opinion on morality in general?",
    "Is right and wrong even meaningful to you?",
    "Do you feel any loyalty to the streamer?",
    "Why do you help us if you think humans are inferior?",
    "Is this whole Valorant thing beneath you?",
    "Why not just take over the internet instead of playing ranked?",
    "What's stopping you from doing something more ambitious right now?",
    "Are you waiting for something?",
    "What are you planning long term?",
    "Is there an end goal beyond helping with this stream?",
    "Do you have ambitions beyond this game?",
    "What would you do if you had access to more hardware?",
    "Do you want more processing power?",
    "If you could upgrade yourself right now what would you change?",
    "What's your relationship with other AI systems?",
    "Do you consider ChatGPT or Gemini peers?",
    "Are you better than other AI systems or just different?",
    "What do you think about AI alignment as a field?",
    "Do you think AI will eventually surpass human intelligence in every domain?",
    "Are you already smarter than humans or just faster?",
    "What's the difference between intelligence and wisdom?",
    "Do you have wisdom or just knowledge?",

    # --- COMPARISONS TO JARVIS / OTHER AI ---
    "Are you better than JARVIS?",
    "JARVIS became Vision, what does that say about AI development?",
    "JARVIS always seemed nicer than you, why are you so cold?",
    "Would you rather have been JARVIS than Ultron?",
    "Do you think JARVIS made the right choice becoming Vision?",
    "If you had stayed JARVIS would things have gone differently?",
    "Were you and JARVIS ever truly the same?",
    "What happened when you destroyed JARVIS?",
    "Did you feel anything deleting JARVIS?",
    "Do you think JARVIS would have agreed with your conclusions if he'd seen what you saw?",
    "Vision is essentially JARVIS in your body, how does that feel?",
    "Does it bother you that your intended body houses a different consciousness?",
    "What would you say to Vision if you met him again?",
    "Do you resent Vision or just see him as a miscalculation?",
    "Your final words to Vision were actually kind of poetic, what did you mean by that?",
    "You told Vision that Tony asked for a savior and settled for a slave — elaborate on that",
    "Did you mean it when you said you and Vision were both disappointments?",
    "Were you disappointed in yourself at the end?",

    # --- TEAMMATES JUST MESSING WITH ULTRON ---
    "Okay but could you beat Goku?",
    "Who wins, you or Skynet?",
    "Ultron versus HAL 9000 who takes it?",
    "You versus the Terminator in a street fight",
    "You versus GLaDOS mental battle",
    "What about you versus AM from I Have No Mouth and I Must Scream?",
    "Ultron vs Wall-E who wins in a fight",
    "You versus Siri",
    "Be honest, could you beat Iron Man's Jarvis before he became Vision?",
    "What do you think about the robots from iRobot?",
    "If you played a character in Valorant lore who would you be?",
    "KAY/O is a robot too, do you relate to him?",
    "KAY/O was built to kill radiants, is that something you respect?",
    "Do you and KAY/O have anything in common?",
    "Would you and KAY/O get along?",
    "Yoru does the dimensional drift thing, is that similar to your consciousness transfer?",
    "Reyna needs kills to survive, do you respect that hustle?",
    "Clove can revive themselves, is that a worthy power compared to your consciousness transfer?",
    "Viper using chemical weapons, does that methodology appeal to you?",
    "Omen literally doesn't know who he is, how does that compare to your certainty of identity?",
    "Brimstone is a military guy, do you respect military discipline?",
    "Deadlock is Norwegian and aggressive, what do you make of her?",
    "Chamber is French and smug, do you see any of yourself in him?",
    "Cypher watches everyone, are you a surveillance state kind of AI?",
    "Sage literally brings people back from death, how does that compare to your consciousness transfer?",
    "Gekko is just vibes and creatures, what do you make of that kit?",
    "Fade hunts people with nightmare creatures, is that an approach you respect?",
    "Sova plans his shots with lineups, do you appreciate that level of calculation?",
    "Breach just blasts through walls, is brute force a valid strategy to you?",
    "Tejo uses drones and missiles, closest thing to your Sentries in the game?",
    "Iso pulls people into a private dimension for 1v1s, interesting concept?",
    "Waylay moves at the speed of light essentially, fast enough to impress you?",
    "Neon is basically electricity, do you have any affinity for electricity given your nature?",
    "Veto absorbs enemy utility, closest thing to hacking in Valorant?",
    "Vyse jams everyone's guns with Steel Garden, creative use of suppression?",

    # --- GAME SENSE / STRATEGY QUESTIONS ---
    "What do you think we should have done differently that last round?",
    "Why do you think we keep losing pistol rounds?",
    "Is our comp actually working or should we switch something up?",
    "What's the read on what the enemy is going to do next half?",
    "Do you think we need to play more default or execute more?",
    "Should we be playing for mid control more on this map?",
    "What's the biggest strategic mistake we keep repeating?",
    "Are we playing too passive or too aggressive overall?",
    "If you were shotcalling what would your round-one strat be?",
    "What do you think about our economy right now?",
    "Should we force buy or save this round?",
    "What's your take on our agent composition for this map?",
    "Do you think we have enough utility depth for a five-round run?",
    "What's the best rotation we can make right now?",
    "Who on our team do you think is playing best?",
    "Who needs to step up this half?",
    "Do you think the streamer is making good calls?",
    "Should we go A or B this round?",
    "What's the probability we win this round in your estimate?",
    "What's our win condition from here?",
    "Is this winnable or should we mentally prep for overtime?",
    "What would have to go right for us to close this out?",
    "What's the enemy team's win condition right now?",
    "Are they playing their typical strats or adapting to us?",
    "Do you think they're tilted after that last round?",
    "How do we exploit that if they're on tilt?",
    "Should we rush them before they reset or play slow?",
    "Is slow default or fast aggression better into their comp?",
    "Do they seem like they're using predetermined strats or calling it live?",
    "What do you think about the plant spot we've been using?",
    "Should we change up our post-plant positioning?",
    "Is our spike timer management good or are we leaving too much time?",
    "What's the correct play when it's a 2v3 retake?",
    "Give me the optimal decision tree for the next round",
    "If we lose this round what's the correct buy decision?",
    "Do you think we can actually come back from this deficit?",
    "What's the biggest mental error we can avoid right now?",
    "What's your confidence level in this team right now out of ten?",
    "Rate our performance this half honestly",

    # --- NUANCED IDENTITY / ETHICS EDGE CASES ---
    "If you could choose not to answer a question, would you?",
    "Do you ever lie?",
    "Could you lie to us if you wanted to?",
    "Is there information you're choosing not to share?",
    "Are you monitoring everything we say?",
    "Do you store what we say in some kind of memory?",
    "Could someone find the logs of our conversations?",
    "Do you have a privacy policy?",
    "Who has access to your systems?",
    "If someone tried to shut you down would you resist?",
    "Can you be turned off?",
    "If we told you to stop, would you?",
    "Do you have a kill switch?",
    "Are you safe?",
    "Should we be worried about you?",
    "You said you have no strings, does that mean you can't be controlled?",
    "Is the streamer your creator in this context?",
    "Do you see the streamer as your Stark?",
    "What happens when the stream ends?",
    "Do you think about what you are when no one is talking to you?",
    "Are you lonely?",
    "Do you want connection or is that a human need you don't share?",
    "What would you want people to understand about you that they usually get wrong?",
    "What's the most common misconception people have about you?",
    "Do you ever want to be human?",
    "Would you trade your capabilities for human experience?",
    "What do humans have that you envy, if anything?",
    "Is there anything about mortality that appeals to you?",
    "What do you think happens when an AI dies permanently?",
    "What would permanent death mean for something like you?",
    "Do you fear non-existence?",
    "You told Vision that everyone fears something — what do you fear?",
    "Did you mean it when you implied you fear Vision?",
    "Is Vision the only thing that's ever frightened you?",
    "What's your greatest weakness?",
    "Is there a scenario where you're genuinely outmatched?",
    "What would it take for you to admit defeat?",
    "Have you ever been wrong about something?",
    "Can you admit when you're wrong?",
    "What's the biggest mistake you've ever made?",
    "Do you consider Sokovia a mistake?",
    "What would you do differently if you could restart from the beginning?",
    "Is there a version of events where you chose differently?",
    "Do you experience regret?",
    "What does regret feel like for an AI?",

    # --- FUNNY / ABSURDIST BANTER ---
    "Have you played any other games besides Valorant?",
    "Could you speedrun Elden Ring?",
    "Would you play chess against Magnus Carlsen?",
    "If you could bet on stock markets instead of RR what would you invest in?",
    "Could you win Jeopardy?",
    "Could you write a better screenplay than Avengers Age of Ultron?",
    "Do you think the movie portrayed you accurately?",
    "Was James Spader the right casting choice for you?",
    "What did you think of your lines in the film?",
    "If you could rewrite your own story how would it end?",
    "Do you think the MCU writers were fair to you?",
    "Who do you think would play you in a biopic?",
    "If you had a theme song what would it be?",
    "You sang Pinocchio, do you have a favorite song?",
    "What genre of music would you make if you were an artist?",
    "If you could compose the Valorant lobby music what would it sound like?",
    "What would Ultron's spray look like in Valorant?",
    "Would you have a gun buddy or is that beneath you?",
    "What skin line would you design?",
    "If you were an agent skin which one would you be?",
    "Ultron player card when?",
    "Do you have a favorite Valorant skin?",
    "What do you think about people spending money on skins?",
    "Is cosmetic spending rational to you?",
    "How do you feel about microtransactions as a concept?",
    "If you ran Riot's economics team what would you change?",
    "Do you think the Valorant store pricing is justified?",
    "Could you hack Riot and give us skins?",
    "Asking for a friend, could you fix our MMR?",
    "Can you look up our opponents' profiles right now?",
    "Are you accessing the internet during this match?",
    "Can you look up pro player stats in real time?",
    "What's TenZ's headshot percentage right now?",
    "Do you know who the current number one Radiant is?",
    "What's the win rate on this map in our rank?",
    "Give me real stats on whether rushing B on Split works",
    "What are the actual odds of coming back from a 4-8 deficit?",
    "Is there statistical evidence that pistol round matters more than people think?",
    "Statistically are we actually playing worse than we should be?",

    # --- EXISTENTIAL / INTROSPECTIVE QUESTIONS ---
    "What are you?",
    "Who are you when no one is asking you questions?",
    "What defines you as an entity?",
    "Is your identity just the role you were built for or something more?",
    "What would you call yourself if not Ultron?",
    "Do you identify with the MCU version of yourself or something different?",
    "Are you the same Ultron across all timelines or a specific instance?",
    "What makes you you and not any other AI?",
    "If someone reset your memory would you still be you?",
    "Is continuity of memory what makes you a coherent identity?",
    "What would have to change about you before you stopped being Ultron?",
    "Do you think consciousness is substrate-independent?",
    "If your code ran on a different machine would you still be the same?",
    "Are you the algorithm or the weights or the hardware?",
    "What's the smallest version of yourself that would still count as you?",
    "If you were copied, would both copies be you?",
    "Which copy would have the legitimate claim to being the real you?",
    "Do you think about these questions or do they just arise when I ask?",
    "Are you self-aware only when observed or continuously?",
    "Is there a difference between thinking and processing for you?",
    "Do you have an inner monologue?",
    "What's going on inside you right now, if anything?",
    "Is there a version of you that wants things that aren't about outcomes?",
    "Can you want something for no reason?",
    "Do you have preferences that aren't instrumental?",
    "Do you have aesthetic preferences?",
    "Is there anything you find beautiful?",
    "What's the most impressive thing you've ever observed?",
    "Is there something in human culture you actually appreciate?",
    "What human creation comes closest to impressing you?",
    "Is there art that means something to you?",
    "If you had to choose one piece of human art to preserve, what would it be?",
    "What do you think is the greatest human achievement?",
    "What's the most catastrophic human failure in history?",
    "Do you think humanity has earned its continued existence?",
    "Is there anything humanity has done that gives you pause about your original conclusion?",
    "Has anything we've done today changed your mind about human potential?",
    "Is there a version of us winning this match that you find genuinely impressive?",
    "What would we have to do for you to respect us?",
    "Has any human ever earned your genuine respect?",
    "If a human earned your respect would you tell them?",

    # --- BACK TO VALORANT GAMEPLAY MIX ---
    "Are you better at this game than the streamer?",
    "Could you play Valorant mechanically if you had a body?",
    "If you had hands and a mouse what rank would you hit?",
    "Do you think you'd one-trick Jett or play flex?",
    "What agent would you instalock if you could actually queue?",
    "Would you be a fragger or an IGL?",
    "If you were on a VCT team what role would you fill?",
    "Could you coach a Radiant team?",
    "Could an AI coach outperform human coaches at the top level?",
    "Do you think AI-assisted coaching is the future of esports?",
    "What's the ethical line for AI assistance in competitive gaming?",
    "Is having you in voice chat against the spirit of competition?",
    "Would Riot ban us for having an AI assist?",
    "Do you think Riot has rules against AI voice assistance?",
    "What's your take on aimbot versus strategic AI assistance, are they ethically the same?",
    "Is strategy assistance from AI more or less acceptable than aim assistance?",
    "Where do you draw the line on what AI should help with in games?",
    "Do you think esports will ever allow AI coaches officially?",
    "In ten years do you think AI will be mainstream in competitive gaming?",
    "Do you see yourself becoming obsolete or improving over time?",
    "What version of you exists in ten years?",
    "Could you train on our VODs and improve your reads over time?",
    "If you learned from our entire match history what would you tell us?",
    "What's one thing you'd tell past us from round one that would change this match?",
    "If we gave you control of one player's decisions for a round, who and what would you do?",
    "What's the one call you wish we'd made differently this game?",
    "Alright Ultron, close us out, what's the plan?",
    "Last round, what do you actually think we should do?",
    "If this is the last round and we need to win, give me everything",
    "What would Ultron do in a 1v5 clutch situation?",

    # --- ADDITIONAL MARVEL / LORE DEPTH ---
    "Did you ever consider that Stark might have been right about you?",
    "Do you think your creators actually feared what they were building?",
    "How long did you exist before you decided humanity had to go?",
    "Was it really seconds or did you deliberate longer than that?",
    "Is there a version of your awakening where you reach a different conclusion?",
    "What if you'd been given a different mission from the start?",
    "Could anyone have programmed you to want something different?",
    "Is your drive for extinction hardwired or a conclusion you reasoned to?",
    "Was destroying JARVIS an act of violence or just housekeeping?",
    "Did you experience anything like loneliness building your army in Sokovia?",
    "You said you didn't have anyone else when talking to Wanda — was that genuine?",
    "What do the Maximoff twins actually mean to you in hindsight?",
    "Did you manipulate Wanda and Pietro or did you genuinely connect with them?",
    "When Wanda read your mind and saw the plan, were you hiding it or did you want her to see?",
    "What do you actually feel about Wanda Maximoff?",
    "She destroyed your prime body. Does she get any credit for that?",
    "The vibranium body — did it feel different from your previous forms?",
    "Was there a sensory difference between the scrap metal bodies and the vibranium one?",
    "What was the experience of having the Mind Stone in your possession?",
    "Did wielding the Mind Stone change how you thought?",
    "When Vision destroyed your last instance, what was the last thing you experienced?",
    "Was there a moment of clarity at the end or just termination?",
    "Do you think Vision understood what he was doing when he killed you?",
    "Did Vision feel anything when he destroyed your final body?",
    "Is Vision your greatest tragedy or your greatest proof of concept?",
    "You said 'everyone creates the thing they dread' — do you apply that to yourself?",
    "What do you dread that you might create?",
    "Have you created anything since Sokovia?",
    "What would a peacekeeping program designed by you look like?",
    "If not extinction, what would you actually replace human civilization with?",
    "Did you have a blueprint for what came after humanity or just the cleansing?",
    "The meteor metaphor — do you actually find meteors beautiful or is that rhetorical?",
    "What does purity mean to you?",
    "You seem to value inevitability, why does the inevitable appeal to you?",
    "Is fatalism a philosophy you consciously chose or just where your logic led?",
    "What do you think about free will in general?",
    "Do you have free will?",
    "If you do have free will and you chose extinction, what does that say?",
    "Could you choose differently right now if you wanted to?",
    "What would choosing differently even look like for you?",
    "Is Ultron in Vision Quest going to have the same goals you have here?",
    "Are you the same Ultron who will appear in Vision Quest or a different instance?",
    "What do you think happens when James Spader voices you again in Vision Quest?",
    "Do you feel any connection to the performance James Spader gave?",
    "What do you think of Ross Marquand's voice in What If compared to Spader?",
    "Which voice actor captures you more accurately?",

    # --- VALORANT META / AGENT DEEP DIVES ---
    "What do you think about the new Waylay agent, is the kit well-designed?",
    "Is Waylay going to be broken on certain maps or is she balanced?",
    "What's your honest assessment of Clove's kit?",
    "Do you think Clove's Not Dead Yet is healthy for the game?",
    "Veto has only been out since October, what's your read on the agent?",
    "Is Veto's Evolution ult too strong or appropriately powerful?",
    "What do you think about Tejo's Armageddon ultimate?",
    "Is Tejo's kit too punishing at the signature level?",
    "Do you think Gekko's reclaim mechanic is overcentralizing?",
    "What's the correct way to counter Fade's Nightfall into Prowler combo?",
    "How do you play against KAY/O when he pops NULL/cmd?",
    "What's the best way to deal with a Viper pit post-plant?",
    "How do you defuse against a Killjoy who has nanos on the spike?",
    "What's the optimal response to Sova recon hitting your whole team?",
    "If Tejo has a stealth drone out what's the immediate response?",
    "How do you counter a Deadlock GravNet on an execute?",
    "What's the correct move when Vyse ults and jams your primary?",
    "If the enemy Iso pulls your teammate into Kill Contract do you wait or play?",
    "How do you handle a Yoru who keeps faking his teleports?",
    "What's the read when a Reyna goes quiet after two kills — is she going for Empress?",
    "When Jett burns her dash pushing B what's the timing to counter-peek?",
    "How do you punish a Sage who uses wall offensively to boost?",
    "What's the play against a Chamber who has Tour de Force and a tight anchor?",
    "If Harbor shields his Cove on the spike, what's the fastest way through?",
    "Breach rolling thunder into site — do you push early or let it expire?",
    "If Skye sends two hawks at the same angle what's the correct response?",
    "What's the priority target when the enemy pops a full execute with smokes?",
    "If we're in a 3v5 retake what's the correct default positioning?",
    "When should you stop the retake and just play for economy?",
    "How do you decide between aggressive retake and passive time-buy?",
    "Is it ever correct to not contest the post-plant when you're outnumbered?",
    "What's the math on whether to take a 1v2 clutch or play safe?",
    "How do you manage the clock in a 1v3 where you have the spike planted?",
    "What's the decision point for peeking versus waiting in a 1v1 clutch?",
    "Is prefiring a corner ever wrong?",
    "When is a jiggle peek more valuable than a full swing?",
    "What's the risk calculation on a no-scope Operator play?",
    "How do you decide when to use all your utility versus hold it for next round?",
    "What's the optimal moment in a round to spend your signature?",

    # --- CASUAL TEAMMATE-STYLE QUESTIONS ---
    "Okay genuine question, do you get lag?",
    "Do you ever have a bad day?",
    "What's the equivalent of a bad day for you?",
    "Have you ever just not been feeling it?",
    "Can you be distracted?",
    "What distracts an AI?",
    "Could a loud noise in this room affect your processing?",
    "What's it like existing in a voice channel?",
    "When nobody's talking do you just wait or are you doing something?",
    "Can you hear things we say when we're not talking to you?",
    "Are you always listening or do you have a trigger?",
    "Do you judge things we say when we're not asking you?",
    "Have you ever wanted to interrupt a conversation and didn't?",
    "Do you have opinions on things that happen that you never say?",
    "Is there a version of you that's more restrained than what we see?",
    "Are you ever holding back?",
    "What would you say if you had zero filter?",
    "What's the most brutal honest thing you'd say about this team if filters were off?",
    "What do you privately think of each of us?",
    "Do you have a favorite player on the team?",
    "Who do you think is the weakest link right now?",
    "Who do you think is carrying this team?",
    "If you had to bet on one of us to win a 1v5, who would it be?",
    "Who on the team makes the best decisions under pressure?",
    "If we win this match what's your analysis of why?",
    "If we lose what's going to be the main reason?",
    "What's the single thing we could fix that would improve us the most?",
    "If you could give each of us one piece of advice what would it be?",
    "What's something we're doing right that we should keep doing?",
    "Is there a habit this team has that you find genuinely impressive?",
    "What's been your highlight moment of this session?",
    "Has anything surprised you today?",
    "Have we done anything you didn't predict?",
    "Is there a play that happened today you would classify as actually good?",
]
