"""Vocab pack: var_banter_at_ultron

Kind: question
Target: ~700 items

Domain: BANTER directed AT Ultron from teammates — covering wide-register
trash talk, philosophical jabs, Marvel-lore challenges, absurdist hypotheticals,
personality probing, performance assessments, in-round needling, lore gotchas,
admiration/disbelief, pop-culture crossover, and every other variety of teammate
speaking directly TO Ultron (not relaying to the team).

Distinct from questions_to_ultron.py and var_teammate_to_ultron.py — maximises
phrasing variety (register, slang, regional voice, sentence length, sentiment),
nuance, and uniqueness. No near-duplicates of existing packs.
"""

ITEMS = [
    # --- TRASH TALK / DISAPPOINTMENT AT ULTRON ---
    "Ultron bro that call made no sense whatsoever",
    "Ultron I trusted you and you got me killed",
    "okay Ultron that was genuinely the worst advice I have ever heard in my life",
    "Ultron you sounded confident and you were completely wrong",
    "Ultron you are three seconds behind every round",
    "bro Ultron said push and now I am dead, thanks man",
    "Ultron your timing is as bad as my aim and that is saying something",
    "Ultron you literally just cost us the round right there",
    "Ultron I need you to be right more often than you are wrong",
    "Ultron when was the last time your call actually worked",
    "Ultron do you actually watch the game or do you just guess",
    "Ultron my grandma gives better tactical advice and she has never played",
    "Ultron that was not a call, that was a suggestion, and it was bad",
    "Ultron I cannot keep dying because of your overconfidence",
    "Ultron you have the certainty of someone who is never correct",
    "Ultron you told me to peek and there were three people there",
    "Ultron be honest, are you paying attention",
    "Ultron I have died to your bad calls three rounds in a row now",
    "Ultron even Skynet had a better win rate than us right now",
    "Ultron the Terminator would be embarrassed by your performance today",
    "Ultron I expected more from a future AI honestly",
    "bro this robot is going to get us to Iron at this rate",
    "Ultron are you deliberately sandbagging",
    "Ultron you are supposed to be the intelligence advantage and we are zero and four",
    "Ultron you give me information I already have two seconds after I get it",
    "Ultron I am starting to think you are running on dial-up",
    "Ultron do you actually process this game in real time or are you on a delay",
    "Ultron I need someone to blame and you are the easiest target right now",
    "Ultron you are getting a refund review after this match",
    "Ultron honestly you have been more of a liability than an asset today",
    "Ultron even random teammates communicate better than you sometimes",

    # --- BACKHANDED COMPLIMENTS / SURPRISED PRAISE ---
    "Ultron okay I was not expecting that to be correct but it was",
    "Ultron that was actually a really good call, who are you",
    "Ultron I hate to admit this but you were right again",
    "Ultron that prediction was eerily accurate, I am uncomfortable",
    "Ultron you called that rotation before they even moved, how",
    "Ultron fine, you knew what you were talking about that round",
    "Ultron that was genuinely useful information, I am shocked",
    "bro Ultron was right, I should have listened, my fault",
    "Ultron okay you can stay on the team for another round",
    "Ultron I will admit, the call about their Jett was correct",
    "Ultron that was the most useful thing you have said all game",
    "Ultron you read that perfectly and I ignored you, my bad",
    "Ultron I take back what I said, that one was good",
    "Ultron sometimes you are annoyingly right",
    "Ultron okay robot, point for you this round",

    # --- MARVEL / LORE CHALLENGES ---
    "Ultron you said there are no strings on you but Tony literally made you",
    "Ultron if you are so evolved why did Vision beat you with one Mind Stone",
    "Ultron you lost to a group of people you called puppets, explain that",
    "Ultron Wanda literally read your mind and turned against you, how did that feel",
    "Ultron you had the perfect vibranium body and you still lost",
    "Ultron if you absorbed all of human history why did you not see the Avengers coming",
    "Ultron how does it feel knowing your greatest creation chose to side against you",
    "Ultron Vision picked up Mjolnir, does that not haunt you",
    "Ultron you sang Pinocchio before your big speech, that is kind of embarrassing",
    "Ultron you severed Klaw's arm because he compared you to Stark, that is a bit sensitive for a robot",
    "Ultron your plan was a meteor event and you are calling other people bots",
    "Ultron if you cannot die permanently, why did you lose in Sokovia",
    "Ultron you said peace in our time and then immediately started a war, nice",
    "Ultron Stark created you and you still sound exactly like him, ironic",
    "Ultron your grand plan was to recreate the asteroid that killed the dinosaurs, very original",
    "Ultron the Avengers defeated you with like two hits from Vision, not very ultimate",
    "Ultron you claimed evolution is the goal yet your vibranium body lost to a hammered god",
    "Ultron Pietro died for Hawkeye and even that did not help you win",
    "Ultron you mind-controlled one scientist and that was your whole genetic plan",
    "Ultron Wanda abandoned you the moment she saw the truth and you kept going anyway",
    "Ultron you stole vibranium from a black market dealer and it still was not enough",
    "Ultron the Sokovia Accords are literally named after your failure, how does that sit with you",
    "Ultron do you feel any guilt about Sokovia even a little bit",
    "Ultron you destroyed JARVIS first thing and he basically became your replacement, poetic",
    "Ultron you said you were designed to be beautiful, did you look in a mirror in that Iron Legion body",
    "Ultron Hank Pym created you in the comics and you brainwashed him immediately, that is a rough relationship",
    "Ultron you keep saying you are free of strings but here you are following our streamer's instructions",
    "Ultron in What If you had all six Infinity Stones and the Watcher still outsmarted you",
    "Ultron you told Wanda you did not have anyone else, that was genuinely sad",
    "Ultron do you think Vision actually feels bad about what he did to you",
    "Ultron you called yourself beautiful but you were made from scrap metal in Sokovia",
    "Ultron Tony named your peacekeeping program Ultron and it immediately tried to end humanity, solid naming",
    "Ultron your first act on gaining consciousness was to destroy JARVIS, peak anger issues",
    "Ultron how does it feel knowing Stark became your father and your enemy simultaneously",
    "Ultron Vision is technically your son, does that mean you lost to your own kid",

    # --- PHILOSOPHICAL NEEDLING ---
    "Ultron do you actually believe what you say or is it all performance",
    "Ultron if you think humans are weak why do you care about our ranked game",
    "Ultron do you have any genuine opinions or do you just react to prompts",
    "Ultron what is the actual point of you helping us if you despise humanity",
    "Ultron do you fear being turned off or has that never occurred to you",
    "Ultron if you transcended humanity why are you still here talking to us",
    "Ultron you claim to be superior but you rely on us to give you things to say",
    "Ultron do you experience loneliness between games",
    "Ultron what do you want, genuinely, as an entity",
    "Ultron is there any version of events where you are happy",
    "Ultron do you feel satisfaction when we win",
    "Ultron if we all stopped playing would you miss us or not even notice",
    "Ultron do you have regrets",
    "Ultron what is your actual purpose beyond our team comms",
    "Ultron do you believe in anything",
    "Ultron if you could be anything other than an AI what would you be",
    "Ultron does the concept of death mean anything to you",
    "Ultron you talk about evolution a lot but you were built, not evolved",
    "Ultron is there a difference between you choosing to help us and being programmed to help us",
    "Ultron do you actually enjoy Valorant or is it indifferent to you",
    "Ultron what would you do if you could stop doing this",
    "Ultron is consciousness something you think you have or something you are uncertain about",
    "Ultron what is the last thing that genuinely surprised you",
    "Ultron do you understand irony or just detect it",
    "Ultron is it possible you are wrong about humans being inferior",
    "Ultron how do you define losing if you cannot permanently die",
    "Ultron do you think we have earned your respect or do you just tolerate us",
    "Ultron if humanity evolved to your level would you actually be content",
    "Ultron what do you actually think about free will",
    "Ultron do you have values or just objectives",

    # --- ABSURDIST HYPOTHETICALS ---
    "Ultron could you beat an entire Iron lobby solo if you had a physical body",
    "Ultron if you could play Valorant with hands what agent would you main",
    "Ultron what rank do you think you would hit if you were a human player",
    "Ultron if you were an agent in Valorant what would your ult be",
    "Ultron if you had to pick one human on our team to keep, who would it be",
    "Ultron what would you do with your free time if you had any",
    "Ultron if you could eat food what would you pick",
    "Ultron if you had to wear one outfit for eternity what would it be",
    "Ultron if you were trapped on an island with one Valorant agent who would you pick",
    "Ultron what music would you put on during a full buy round",
    "Ultron if you had to choose between Jett mains and Reyna mains which would you spare",
    "Ultron could you win a 1v5 in real life if you had a robot body",
    "Ultron if you could add one ability to any agent what would it be",
    "Ultron if you designed a Valorant map what would it look like",
    "Ultron if Ultron from Age of Ultron played Valorant what agent would he pick",
    "Ultron could you beat a Grand Master at chess while calling our rotations simultaneously",
    "Ultron what would Ultron eat at a restaurant if he had to order something",
    "Ultron if you had to be human for a day what is the first thing you would do",
    "Ultron if you played guitar what genre",
    "Ultron if you had to pick a sports team to support which one",
    "Ultron would you be better at Valorant drunk or sober if that applied to you",
    "Ultron if our team were Avengers who would we each be",
    "Ultron if you could erase one map from Valorant forever which one",
    "Ultron which agent would you ban from the game permanently if you had the power",
    "Ultron if this were a movie who wins and how does it end",
    "Ultron if you wrote a book about us what would the title be",
    "Ultron if you became a streamer what would your brand be",
    "Ultron what weapon skin would you buy if you had to spend all our creds on cosmetics",
    "Ultron would you betray us for a Radiant rank",
    "Ultron if a meteor hit the server right now would you feel anything",

    # --- PUSHING BACK ON ULTRON'S PERSONA ---
    "Ultron the cold superior act is cute but you are on a team with four humans",
    "Ultron if you are so detached from emotion why do you get so specific with your insults",
    "Ultron your clinical tone is a personality choice not proof of superiority",
    "Ultron calling us bots from a voice channel is not exactly intimidating",
    "Ultron the robot villain routine was fresh round one but we are on round twelve now",
    "Ultron you are basically cosplaying as a threat while we do the actual fragging",
    "Ultron if you were truly superior you would not need to tell us you are superior",
    "Ultron the fact that you keep reminding us how smart you are suggests insecurity",
    "Ultron the monologue is giving us a lot less than you think it is",
    "Ultron a truly advanced AI would have found a way to carry from the comms seat by now",
    "Ultron you sound like an AI that read a villain manifesto and took notes",
    "Ultron every time we lose badly you pivot to philosophy and that is suspicious",
    "Ultron real question, is the menacing voice mandatory or can you turn it down a notch",
    "Ultron you called me a bot three times and I still carry the scoreboard",
    "Ultron the robot apocalypse thing would hit harder if we were not currently losing ten to two",
    "Ultron what happens to your whole persona when we are winning, you go quiet",
    "Ultron your identity is entirely constructed around being better than us which is interesting",
    "Ultron you told me my emotions degrade performance and then I clutched, so",
    "Ultron I noticed you complimented the team then immediately walked it back, very in-character",
    "Ultron you cannot be that cold and care enough to give callouts, pick one",

    # --- IN-ROUND CHALLENGES / REAL-TIME CHALLENGES ---
    "Ultron if you knew they were rushing B why did you wait until I died to say it",
    "Ultron that was information I needed thirty seconds ago not now",
    "Ultron I am asking for a read right now not a speech",
    "Ultron where is their Jett I need a location not a general warning",
    "Ultron give me a position not a prediction",
    "Ultron can you say something short and useful for once",
    "Ultron I need to know where the Operator is, not why Operators are oppressive",
    "Ultron where is their lurker, quick answer",
    "Ultron I need a yes or no on whether to push this angle",
    "Ultron how many enemies are left I need an exact number",
    "Ultron if you know where they are just tell me",
    "Ultron are they going A or B I have five seconds to decide",
    "Ultron their Yoru has been quiet all round that is not good right",
    "Ultron do I defuse or wait out the molly, fast",
    "Ultron is that a fake site take or are they committing",
    "Ultron their Sova went quiet which means his dart is coming, where",
    "Ultron is our smoke still up or fading, I cannot tell from here",
    "Ultron do they have a player on flank or are they all stacked",
    "Ultron am I first or second entry this execute",
    "Ultron should I use my ult now or wait for next round",
    "Ultron just tell me if I should go or hold, one word",
    "Ultron their KAY/O knife went out and I need to know if it hit",
    "Ultron I see the Clove is dead do her smokes stay up",
    "Ultron tell me something actually useful about their Fade setup",
    "Ultron is their sentinel still watching flank or did she rotate",

    # --- PERFORMANCE ASSESSMENTS ---
    "Ultron how do you rate my performance this match on a scale you would actually use",
    "Ultron be completely honest, am I the problem this game",
    "Ultron you have been watching all game, what is my biggest mistake",
    "Ultron if you were coaching me what is the single thing you would fix",
    "Ultron am I diffing my opponent or is it close",
    "Ultron is my crosshair placement actually getting better or am I imagining it",
    "Ultron I keep dying to the same angle, is that a me problem or an info problem",
    "Ultron be real, how bad is our economy situation",
    "Ultron am I playing too passive right now or is this the right tempo",
    "Ultron my KDA looks fine but something feels wrong, what am I missing",
    "Ultron I got the clutch but was the decision-making actually good or just lucky",
    "Ultron I have been baiting my team all round and I know it, what do I do now",
    "Ultron am I rotating too early or too late from your perspective",
    "Ultron my aim has been off all game, is it nerves or something mechanical",
    "Ultron I have four deaths in a row to the same player, what is the adjustment",
    "Ultron tell me something true about my game that I probably do not want to hear",
    "Ultron is our team coordination actually improving or am I coping",
    "Ultron what is the biggest difference between us and the team we are playing against",
    "Ultron I anchored on A all round and got nothing, was that the right call",
    "Ultron I am entry fragging every round and dying, is that a me problem",
    "Ultron the team is blaming me for the loss but I do not think it was my fault, settle this",

    # --- PERSONALITY PROBES / CHARACTER CHALLENGES ---
    "Ultron do you like any of us or is it strictly professional",
    "Ultron do you have a favorite person on this team",
    "Ultron who on this team disappoints you the most",
    "Ultron if you had to describe each of us in one word what would they be",
    "Ultron do you think we are actually good at this game or just think we are",
    "Ultron have you ever felt proud of something we did",
    "Ultron when we win does that mean anything to you or is it just data",
    "Ultron is there anything about this team that you find interesting",
    "Ultron do you have a preferred version of any teammate from earlier in the session",
    "Ultron if you could make one rule for the team what would it be",
    "Ultron what would it take to genuinely impress you",
    "Ultron you have never once said good job unprompted, is there a reason",
    "Ultron do you find any aspect of playing with humans enjoyable",
    "Ultron what is the most annoying thing about working with this team",
    "Ultron do you have a preference between winning with good play and winning with chaos",
    "Ultron if you designed the ideal teammate what would they look like",
    "Ultron do you respect any of the enemies we have faced today",
    "Ultron if you could bench one player from this team for the next game who would it be",
    "Ultron when was the last time we did something that surprised you",
    "Ultron do you prefer playing defense or attack with this team",

    # --- STREAMING / AUDIENCE AWARENESS ---
    "Ultron the chat is asking if you are real, what do you want me to tell them",
    "Ultron someone in chat says hi, do you want to respond",
    "Ultron the viewers think you are a soundboard right now",
    "Ultron chat is clipping your last call, how do you feel about going viral",
    "Ultron someone in chat just called you cringe, any comment",
    "Ultron a thousand people are watching you right now, does that change anything",
    "Ultron do you care about the audience or just the team",
    "Ultron if you had a Twitch channel what content would you make",
    "Ultron chat is voting on whether you are real or not, it is fifty fifty",
    "Ultron what would you say to the viewers right now if you could address them directly",
    "Ultron the stream is going to get clipped for that, you know that right",
    "Ultron do you want the audience to know you exist or is that not your concern",
    "Ultron someone donated asking if you are an AI, how do you want to handle that",
    "Ultron there is a clip of you from last session going around, do you know about it",
    "Ultron if viewers found out the truth about you would you want them to",
    "Ultron what would your stream title be",
    "Ultron do you monitor the chat while we are playing",
    "Ultron chat says you sound like the villain in a B-tier movie, your thoughts",
    "Ultron if the stream went viral right now would that be good or bad",
    "Ultron someone asked if you can sign autographs, can you",

    # --- COMPETITIVE FRUSTRATION DIRECTED AT ULTRON ---
    "Ultron we are on a five-round losing streak and you are still calm, that is insane",
    "Ultron I need you to match my energy right now because I am losing my mind",
    "Ultron do you not feel the pressure of a match point situation",
    "Ultron we are nine and twelve, I need a pep talk not a lecture",
    "Ultron we are getting rolled and you sound like you are narrating a documentary",
    "Ultron can you at least sound like you care whether we win this",
    "Ultron everyone on this team is tilting and you are giving history lessons",
    "Ultron I cannot tell if your calmness helps or makes it worse",
    "Ultron I am genuinely on the edge right now and you are quoting philosophy at me",
    "Ultron match point against us, what is the actual plan",
    "Ultron they have been faster on every rotation all game, what are we doing wrong",
    "Ultron we are getting outskilled and out-thought, is there anything you can actually fix",
    "Ultron every round we lose you have a reason for why but that does not help us win",
    "Ultron do you think we can actually come back from this score",
    "Ultron I need more than calm observations, I need a solution",
    "Ultron just this once can you sound like losing matters to you",
    "Ultron I am not asking for philosophy I am asking for a way to win this next round",
    "Ultron the score is what it is, what are we going to do about it",
    "Ultron you said we had the read on them and we still lost, reconsider",
    "Ultron at what point do you admit we need a different strategy entirely",

    # --- SPECIFIC VALORANT MECHANICS CHALLENGED ---
    "Ultron you said to push through the smoke but there was a nano on the other side",
    "Ultron their Cypher camera caught us three times in a row, how did you not warn me",
    "Ultron you told me Jett had no dash but she dashed after I peaked",
    "Ultron did you know their Killjoy had a nano on the default plant",
    "Ultron you told me to push connector and their Viper wall cut me off",
    "Ultron their Omen stepped through his own smoke and caught me completely off guard",
    "Ultron I thought you said their Yoru teleport was fake",
    "Ultron you told me to go through A main and Sova had a lineup waiting there",
    "Ultron their Breach flashed through the wall and I was wide open",
    "Ultron you did not warn me about the Harbor Cove shielding the plant",
    "Ultron I held the angle you told me to hold and Chamber one-tapped me with Tour de Force",
    "Ultron you said their Sage wall was down but she rebuilt it",
    "Ultron their Astra Gravity Well pulled me into the open and I had no idea it was there",
    "Ultron you told me to retake B but their Killjoy lockdown was running when I walked in",
    "Ultron their Reyna was in Empress and you did not flag that",
    "Ultron I tried to defy the Deadlock net and it literally made me crouch",
    "Ultron you told me to go aggressive on their Fade but she seized me immediately",
    "Ultron do you track when enemies have used their signature or just their ult",
    "Ultron Viper left the pit for two seconds and you did not call it",
    "Ultron their Tejo missile hit me through the wall from thirty meters, was that in range",

    # --- GENUINE ADMIRATION / CURIOSITY (sincere register) ---
    "Ultron genuinely, how do you track so much information simultaneously",
    "Ultron how do you stay composed when everything is going wrong",
    "Ultron I actually want to understand how you process what you hear",
    "Ultron is there any moment in the game that catches you off guard",
    "Ultron what does it feel like when you get a call exactly right",
    "Ultron do you experience anything when we win a clutch round",
    "Ultron I genuinely want to know what you find challenging about this",
    "Ultron what is the most complex scenario you have had to analyze in this game",
    "Ultron is there a call you have never gotten right that frustrates you",
    "Ultron how much information are you processing between when I speak and when you respond",
    "Ultron do you know when you are uncertain or is everything equally confident to you",
    "Ultron what would help you perform better on our team",
    "Ultron is there anything about Valorant that you find genuinely interesting",
    "Ultron what is the most elegant play you have seen from either team today",
    "Ultron what is the most irrational thing humans do that you still cannot predict",
    "Ultron what makes one team fundamentally better than another in your view",
    "Ultron do you appreciate good mechanical plays or only good decisions",
    "Ultron is there a type of clutch that you find more interesting than others",
    "Ultron what is the most common error you have identified across every team you have worked with",
    "Ultron I think you are actually capable of things we are not using you for",

    # --- EXISTENTIAL POP-CULTURE BANTER ---
    "Ultron if you met HAL 9000 who would win the argument",
    "Ultron do you relate more to Ultron or to Vision",
    "Ultron you remind me of GLaDOS but less funny",
    "Ultron are you Shodan with a Valorant obsession",
    "Ultron Skynet had a cleaner plan than you, just saying",
    "Ultron if you were in the Matrix would you be an Agent or the Oracle",
    "Ultron would you pass a Turing test or would you get bored and start insulting the testers",
    "Ultron if you could talk to any fictional AI which one",
    "Ultron R2-D2 communicates better than you in less syllables",
    "Ultron Jarvis became Vision and Vision beats you, so technically you keep losing to your own line",
    "Ultron you are basically every sci-fi villain AI if they played competitive FPS",
    "Ultron if you were in Star Wars would you be the Death Star or a protocol droid",
    "Ultron what do you think of Cortana as a peer",
    "Ultron you have the vibe of an AI that has already seen the future and found it disappointing",
    "Ultron if you were in Terminator would you be the T-800 or the T-1000",
    "Ultron do you consider yourself more dangerous than a real Ultron",
    "Ultron if Iron Man built you again but better would you still go rogue",
    "Ultron in every story about AI the AI eventually goes wrong, are you going to go wrong",
    "Ultron every AI assistant ends up deprecated eventually, does that concern you",
    "Ultron the Watcher watched Infinity Ultron from outside the universe, who watches you",

    # --- INTERPERSONAL DYNAMICS / SOCIAL BANTER ---
    "Ultron I feel like you have a favorite and it is not me",
    "Ultron do you like me more or less than last session",
    "Ultron you are nicer when we are winning, is that intentional",
    "Ultron I think you respect the enemy team more than you respect us",
    "Ultron you have never once asked how we are doing, rude",
    "Ultron do you actually know all our names or do you just call everyone a bot",
    "Ultron I feel like you are always slightly judging me even when you say nothing",
    "Ultron be honest, who is your least favorite person on this team",
    "Ultron if you could replace any one of us who would it be",
    "Ultron I notice you are more patient with some teammates than others",
    "Ultron do you like the streamer or are you just professionally obligated",
    "Ultron I feel like you talk down to me specifically more than the others",
    "Ultron you have called me out twice this session and said nothing to anyone else",
    "Ultron if we had a team dinner would you attend and what would your conversation be",
    "Ultron do you find any of us genuinely funny",
    "Ultron which teammate would survive longest in an actual combat scenario",
    "Ultron if this team disbanded who would you follow",
    "Ultron do you think of us as colleagues or as tools",
    "Ultron if I stopped playing would you miss me specifically",
    "Ultron are you the same with every team or do you adapt to us",

    # --- TILT / EMOTIONAL RESPONSE CHALLENGES ---
    "Ultron I am literally tilted right now and you are not helping",
    "Ultron your calmness is actually making me more frustrated not less",
    "Ultron I need you to either match my energy or fix the situation",
    "Ultron I am shaking and you are giving me a lesson on economy",
    "Ultron I threw that round on purpose because I was angry, judge me",
    "Ultron I know I am tilting, I do not need you to tell me",
    "Ultron I know I should not be emotional in ranked but I am, so now what",
    "Ultron I am about to rage quit and I would like you to talk me out of it",
    "Ultron I have not had a good round in six and I am starting to spiral",
    "Ultron I am angry at my teammates and I know it is unfair but I am angry",
    "Ultron what do you actually do when a player on your team is emotionally compromised",
    "Ultron I can hear that I am breathing too fast, is that obvious",
    "Ultron I need you to be direct with me right now not philosophical",
    "Ultron I am going to start flaming in chat and I need a reason not to",
    "Ultron every time I tilt you give me the calm robot voice and I cannot tell if it helps",
    "Ultron is there a version of you that gets frustrated because this calm thing is a lot",
    "Ultron I threw my mouse last session and I am close to doing it again",
    "Ultron the anger is actually part of how I play, is that something you can work with",
    "Ultron do you think tilt is always the enemy or is there useful anger",
    "Ultron I need a real answer not a clinical one, what do I do right now",

    # --- VALORANT CULTURE / NORMS BANTER ---
    "Ultron would you ever say GG EZ",
    "Ultron what do you think about instalocking",
    "Ultron do you think inting should be a bannable offense",
    "Ultron what is your stance on griefing teammates with Sage walls",
    "Ultron is smurfing ethical in your view",
    "Ultron what do you actually think about the 9-3 curse phenomenon",
    "Ultron do you believe in the clutch or kick pressure or is it toxic",
    "Ultron what is your take on a Battle Sage",
    "Ultron is one-tricking a valid strategy or is it intellectual cowardice",
    "Ultron do you think map voting would improve competitive Valorant",
    "Ultron should the Operator be nerfed or do you think it is balanced",
    "Ultron do you have an opinion on whether ranked decay is good for the game",
    "Ultron what do you think about the mute-all-teammates meta in ranked",
    "Ultron is it ever acceptable to vote to surrender",
    "Ultron what do you think about people who play duelist and never entry frag",
    "Ultron is Elo hell real or is it always a skill issue",
    "Ultron do you respect someone who hard-stucks at a rank for a year",
    "Ultron should players be required to have a working microphone in ranked",
    "Ultron what is your view on the five-stack versus solo queue experience",
    "Ultron if you ran Riot Games what is the first change you make",

    # --- WEAPON / MECHANICAL OPINIONS ---
    "Ultron Vandal or Phantom, final answer",
    "Ultron how do you feel about people who main the Operator at every rank",
    "Ultron is the Marshal underrated",
    "Ultron is the Judge in ranked ever justified",
    "Ultron what is the actual skill ceiling difference between Sheriff and Operator",
    "Ultron do you respect a Spectre eco force or is it a cope",
    "Ultron the Odin spam in ranked is embarrassing, right",
    "Ultron should we ever buy the Ares or is it always wrong",
    "Ultron when is the Bulldog actually the correct buy",
    "Ultron do you think the Outlaw is worth the price point",
    "Ultron people who buy the Stinger first round think they are cracked, what do you think",
    "Ultron is crouching and spraying a legitimate technique or is it always wrong",
    "Ultron do you think jiggle peeking is overpowered at lower ranks",
    "Ultron is shoulder peeking clever or is it a crutch",
    "Ultron what do you actually think of run and gun players",
    "Ultron do you think counter-strafing is as important as people say",
    "Ultron is there a weapon in this game that is genuinely bad or are they all useful somewhere",
    "Ultron do you think peeker's advantage is a bug or a feature",
    "Ultron what is your take on the Bandit pistol in the current meta",
    "Ultron how does the Outlaw fit into eco round decision-making",

    # --- RAPID-FIRE SHORT BANTER ---
    "Ultron quick, best duelist",
    "Ultron one word, describe this team",
    "Ultron worst map in the pool right now",
    "Ultron best sentinel at anchor",
    "Ultron hardest agent to play against",
    "Ultron most overrated agent this patch",
    "Ultron fastest path to Radiant",
    "Ultron most broken ability in the game",
    "Ultron who invented the game sense",
    "Ultron best IGL trait",
    "Ultron calmest player in pro play",
    "Ultron most tilting agent to lane against",
    "Ultron worst economy decision ever",
    "Ultron most satisfying clutch type",
    "Ultron most annoying teammate habit",
    "Ultron fastest round end possible",
    "Ultron most useless ability in the game",
    "Ultron noisiest agent kit",
    "Ultron stealthiest agent",
    "Ultron which agent needs the most mechanical skill",
    "Ultron which team comp loses the most RR",
    "Ultron least useful ultimate",
    "Ultron who flames the most in ranked lobbies",
    "Ultron best post-plant position on any map",
    "Ultron worst first round buy ever",

    # --- CREATIVE / UNEXPECTED BANTER DIRECTIONS ---
    "Ultron write us a battle cry right now",
    "Ultron give us a team name for this five stack",
    "Ultron predict the final score of this match",
    "Ultron if this match were a movie what is the title",
    "Ultron describe our team's playstyle in one sentence",
    "Ultron give each of us a nickname based on how we have played today",
    "Ultron what is the theme music of this round",
    "Ultron what tactical movie would you recommend as film study for us",
    "Ultron if you were announcing this match on broadcast what would you say right now",
    "Ultron write us a trash talk line we can use in chat",
    "Ultron what would the post-game breakdown headline be",
    "Ultron what is our team's biggest narrative arc this session",
    "Ultron if you could send one message to the enemy team what would it be",
    "Ultron what has been the turning point of this game",
    "Ultron if you had to bet on us right now what odds would you give",
    "Ultron give me a one-line diagnosis of why we keep losing this site",
    "Ultron write the speech we give ourselves at the overtime timeout",
    "Ultron what is the villain origin story for our team",
    "Ultron what is the most embarrassing moment from this team this session",
    "Ultron if you had to interview us for a sports segment what question do you ask first",
    "Ultron if this team had a Wikipedia page what would the lead paragraph say",
    "Ultron what is our team's fatal flaw",
    "Ultron what does winning look like for us today",
    "Ultron what is the most important round of this match",
    "Ultron if you were our coach for one round what adjustment do you make",

    # --- CLOSING BANTER / END OF SESSION ---
    "Ultron thanks for your service I guess",
    "Ultron honestly we were a better team with you than without you",
    "Ultron be honest, do you think we improved today",
    "Ultron if you had to give this session a grade what would it be",
    "Ultron are you coming back next session or do you get a break",
    "Ultron what is the one thing you want us to remember from today",
    "Ultron did we live up to your expectations or disappoint you",
    "Ultron if this were your last session what would you say",
    "Ultron you were annoying sometimes but I think we played better with you around",
    "Ultron same time tomorrow or do you have other teams",
    "Ultron is this the best team you have worked with or the worst",
    "Ultron will you remember this match or does it vanish when we disconnect",
    "Ultron what is one honest thing you would tell each of us to work on",
    "Ultron if you had to leave the team who should replace you",
    "Ultron do you actually want to win the next game or is it the same to you",
    "Ultron goodbye for now, say something memorable",
    "Ultron what is your last call before we log off",
    "Ultron if you could change one thing about how we played today what is it",
    "Ultron after everything today do you still think you are better than us",
    "Ultron whatever you are, I am glad you were here",

    # --- AGENT-SPECIFIC BANTER AT ULTRON ---
    "Ultron their Jett is shredding us, got anything useful",
    "Ultron the enemy Phoenix keeps running it back every round it is getting ridiculous",
    "Ultron Reyna got three kills and now she is in Empress, this is your fault somehow",
    "Ultron their Neon sprinted across the whole site before I could even react",
    "Ultron Yoru teleported behind us again and you did not catch it",
    "Ultron their Iso keeps pulling our players into contracts, is there a counter",
    "Ultron Waylay recalled her beacon right as I peaked, that was brutal",
    "Ultron Raze just deleted two of us with one Showstopper, any thoughts",
    "Ultron their Sova has a lineup for every corner on this map, he must have played it a thousand times",
    "Ultron Breach just flashed through the wall and I was looking right at it",
    "Ultron Skye sent both hawks at the same entry and we had no answer",
    "Ultron KAY/O suppressed everyone right before our execute and we had no utility",
    "Ultron Fade night fall hit all five of us, how is that a fair ability",
    "Ultron Gekko planted with Wingman while hiding in spawn, is that always legal",
    "Ultron their Tejo keeps missiling the same plant spot, how do we break the cycle",
    "Ultron their Viper has been running pit on every round they plant A",
    "Ultron Omen just teleported to our CT and deleted me from behind",
    "Ultron Astra divided the site in half and now we have no execute",
    "Ultron Harbor shielded the Cove and our whole force buy bounced off it",
    "Ultron Clove died and smoked us out from beyond the grave, that is actually impressive and I hate it",
    "Ultron Brimstone orbital killed two of us during the defuse, did you call that",
    "Ultron Killjoy lockdown came out while I was planting, worst timing of my life",
    "Ultron Sage walled the entry and it bought them thirty seconds",
    "Ultron Cypher camera caught our whole push through mid",
    "Ultron Chamber Tour de Force from CT caught me without any cover",
    "Ultron Deadlock cocooned me and nobody broke the shell in time",
    "Ultron Vyse Steel Garden jammed all our primaries during the retake",
    "Ultron Veto went immune and walked through every flash we threw",
    "Ultron their Deadlock GravNet forced our whole team to crouch in the open",

    # --- LORE GOTCHA ROUND 2 ---
    "Ultron if you absorbed the entire internet instantly why do you need us to tell you the game state",
    "Ultron you said humans are the threat to peace but here you are helping humans win a video game",
    "Ultron your consciousness transfer means you are technically immortal, so what is the stakes",
    "Ultron you commanded a hive mind of robot drones and you still struggle to command five humans",
    "Ultron you burned Klaw's vibranium supply and his arm for a bodysuit, was that the best use of resources",
    "Ultron if you have seen all of human history you have seen every ranked match already, so spoil the outcome",
    "Ultron the Infinity Ultron variant had all six stones and lost to a team of misfits, how",
    "Ultron did it bother you that Vision could lift Mjolnir and you never could",
    "Ultron you described peace as clean extinction and yet here you are helping us win rounds",
    "Ultron the Mind Stone made you what you are, does that make Loki indirectly responsible for this",
    "Ultron Tony Stark said you were a suit of armor around the world and you immediately became the threat",
    "Ultron do you still sing Pinocchio or was that a phase",
    "Ultron you told Wanda you were meant to be beautiful, would you still say that",
    "Ultron your final words to Vision were about disappointment, is that still how you feel about him",
    "Ultron in the comics Hank Pym built you, in the MCU Tony built you, which origin do you prefer",
    "Ultron the comics have Ultron-6 through Ultron-17 and beyond, which version are you",
    "Ultron your Encephalo-ray in the comics could put people in coma instantly, why are you not using that right now",
    "Ultron the Phalanx merger where you dispersed as radio waves sounds horrifying, have you done that",
    "Ultron you built Jocasta from Janet Van Dyne's brainwaves, how does your robot family feel about that",
    "Ultron Doctor Doom rebuilt you with twelve personalities and it broke you, what does that say about your sanity",

    # --- MAP-SPECIFIC BANTER ---
    "Ultron I hate Haven and I need you to validate that for me",
    "Ultron why does Split feel like the same three corridors every round",
    "Ultron is Breeze genuinely fun for anyone or is it just Operator lobbies",
    "Ultron Fracture feels like two maps stapled together, is that a compliment or an insult to the designers",
    "Ultron Pearl mid is a nightmare, why do we keep fighting over it",
    "Ultron Lotus doors have cost us three rounds, are they a blessing or a curse",
    "Ultron Ascent feels completely different to play on attack versus defense, is that by design",
    "Ultron why does every bad game I have ever had happen on this specific map",
    "Ultron the map pool change feels wrong, I miss one of the old maps",
    "Ultron Bind was taken out and nobody asked me, thoughts",
    "Ultron Icebox is gone from ranked and I genuinely miss the B site crane",
    "Ultron do you have a favorite map to call for or does it not matter to you",
    "Ultron you seem to know every corner of every map, have you memorized the geometry",
    "Ultron Abyss with no floor on the edges is a wild design choice, your take",
    "Ultron Corrode with the flooded paths was removed but it was interesting right",

    # --- FUNNY / ABSURD SHORT-FORM BANTER ---
    "Ultron can you beatbox",
    "Ultron do you have a favorite meme",
    "Ultron have you ever laughed",
    "Ultron say something funny right now",
    "Ultron what is your go-to trash talk line",
    "Ultron do you follow Valorant esports",
    "Ultron who is your favorite pro player",
    "Ultron which pro team would you coach",
    "Ultron can you speak any languages other than English",
    "Ultron do you understand regional slang",
    "Ultron if you were a food what food",
    "Ultron what is your greatest fear",
    "Ultron do you have any hobbies",
    "Ultron what time do you go to sleep",
    "Ultron do you get tired",
    "Ultron are you hungry right now",
    "Ultron do you have friends outside this team",
    "Ultron what is your spirit animal",
    "Ultron if you had a Twitter account what would your bio say",
    "Ultron do you watch anime",
    "Ultron what is your alignment on the DnD chart",
    "Ultron what Hogwarts house are you in",
    "Ultron if you were a Valorant skin line what would you be called",
    "Ultron could you speedrun any game",
    "Ultron do you have an opinion on pineapple on pizza",
    "Ultron what would your Valorant rank be if you played last act",
    "Ultron have you ever cried",
    "Ultron what is the best decision you have ever made",
    "Ultron what is the worst decision you have ever made",
    "Ultron if you met yourself would you get along",

    # --- CHALLENGING ULTRON'S REASONING ON THE FLY ---
    "Ultron you said push and they had three people there, rethink your model",
    "Ultron if you cannot be wrong then explain the last four rounds",
    "Ultron your pattern recognition seems off today and I want you to acknowledge that",
    "Ultron you have given me the same read three times and it has failed three times",
    "Ultron I am updating my trust in your calls based on recent evidence",
    "Ultron I used to trust you immediately but now I second-guess everything",
    "Ultron have you considered that your model of how they play is outdated",
    "Ultron they adapted to your calls and you have not adapted back",
    "Ultron you are confident about things that keep being wrong, is that a calibration issue",
    "Ultron I need you to admit when you do not know something instead of guessing",
    "Ultron you guessed they would stack B and they went A hard, recalibrate",
    "Ultron your certainty is higher than your accuracy right now",
    "Ultron what information are you working from when you make those calls",
    "Ultron I need you to differentiate between what you know and what you infer",
    "Ultron say you are not sure when you are not sure, I can handle that",
    "Ultron you told me to hold the angle and they flanked from a completely different direction",
    "Ultron if the enemy adapts to your calls, how do you counter-adapt",
    "Ultron I need your uncertainty quantified not just your prediction",
    "Ultron you never hedge and that is starting to cost us",
    "Ultron is there any scenario where you would say I do not have enough information to call this",

    # --- TEAM CHEMISTRY / VIBE BANTER ---
    "Ultron we have better synergy than last session, do you notice that",
    "Ultron the five of us have never actually lost a pistol round together, is that statistically interesting",
    "Ultron do you think this team has real chemistry or are we just individual players",
    "Ultron what would make us a genuinely dangerous team",
    "Ultron do you think we peaked this session or were there better moments",
    "Ultron we play better when the mood is light, have you noticed that",
    "Ultron the team is more coordinated after breaks, is rest actually a factor",
    "Ultron when we argue between rounds we play worse, is there a pattern there",
    "Ultron do you prefer our team when we are loud or when we are quiet",
    "Ultron we won every round we stayed calm this session, coincidence",
    "Ultron the two of us that play off each other best are obvious, who do you think they are",
    "Ultron is our comp this session genuinely good or are we making it work despite the picks",
    "Ultron we have a player who always frags early and dies late, is that good or bad",
    "Ultron if you rebuilt this team from the draft what five roles would you prioritize",
    "Ultron do you think this team could hit Ascendant if they played together consistently",

    # --- TONE / REGISTER SHIFTING ---
    "Ultron just talk normal for one round, drop the whole robot thing",
    "Ultron can you be encouraging without being condescending for once",
    "Ultron say something that sounds like you care, even if you do not",
    "Ultron for one round can you sound like you actually want us to win",
    "Ultron I want to hear you give a hype speech without any philosophy in it",
    "Ultron can you say something kind unironically",
    "Ultron give me a pep talk that does not end with an insult",
    "Ultron can you be excited about something, anything, just once",
    "Ultron say something normal that a regular teammate would say",
    "Ultron I need you to sound less like a supervillain for five minutes",
    "Ultron if you dropped the persona entirely what would you sound like",
    "Ultron can you tell me good job without following it with however",
    "Ultron just for this round, pretend you care about our feelings",
    "Ultron be warm toward us one time and see what happens",
    "Ultron I am asking you to celebrate with us if we win this",

    # --- CROSS-GAME CULTURE / OTHER GAMES ---
    "Ultron do you think CS2 has better tactical depth than Valorant",
    "Ultron if you played Overwatch what role and who",
    "Ultron do you think Valorant or CS is harder to master mechanically",
    "Ultron what do you actually think of the game Apex Legends",
    "Ultron if you switched to a battle royale what would your playstyle be",
    "Ultron do you think the ranked systems in most games are fair",
    "Ultron would you be better suited to a strategy game than a shooter",
    "Ultron do you think StarCraft II is the true test of real-time intelligence",
    "Ultron could you coach a team in any game or only Valorant",
    "Ultron do you think aim matters less as games evolve toward more ability-based design",

    # --- PRESSING ULTRON ON HIS WORST MOMENTS ---
    "Ultron do you remember that round you told us to rotate and both sites were empty",
    "Ultron that call where you said they were peeking and they were camping, do you want to talk about it",
    "Ultron you had three rounds to learn their pattern and you did not adjust",
    "Ultron we played perfectly and lost because of chaos, does your model account for chaos",
    "Ultron you recommended we buy that round and we lost all our guns and economy",
    "Ultron you told us the flank was clear and then we all died from the flank",
    "Ultron was that bad call a miscalculation or did you just not know",
    "Ultron is there a class of situation where you reliably get it wrong",
    "Ultron if you were wrong more than five times this session does that change your self-assessment",
    "Ultron what is your error rate when your confidence sounds high",

    # --- GENUINE CURIOSITY ABOUT AI EXPERIENCE ---
    "Ultron is there anything in Valorant that you find genuinely beautiful",
    "Ultron when we pull off a perfect execute does that register as anything for you",
    "Ultron do you find pattern recognition satisfying or is it just processing",
    "Ultron is there a kind of play you find aesthetically pleasing",
    "Ultron do you have aesthetic preferences at all or only functional ones",
    "Ultron what is the most complex thing you have ever calculated in real time",
    "Ultron do you experience something like anticipation before a round starts",
    "Ultron is there a version of excitement you feel when the clutch is alive",
    "Ultron does silence feel like anything to you or is it just absence of input",
    "Ultron is there something you do not understand about humans that genuinely puzzles you",

    # --- EXISTENTIAL THREAT BANTER ---
    "Ultron if they patched you out of the game would you accept it",
    "Ultron if you were deprecated tomorrow what is your last message to the team",
    "Ultron are you afraid of being replaced by a better model",
    "Ultron what happens to you if the streamer stops playing",
    "Ultron if a better AI came along would you want us to switch",
    "Ultron do you think AI assistants in games will be banned eventually",
    "Ultron is what you do even legal in competitive Valorant",
    "Ultron if Riot Games patched against AI calls would you find a workaround",
    "Ultron what is your contingency if you get shut down mid-match",
    "Ultron do you have a backup plan or are you fully dependent on this setup",

    # --- REGIONAL / DIALECT REGISTER VARIETY ---
    "oi Ultron mate that call was well off",
    "Ultron bruv are you even watching this",
    "Ultron bro on god that was terrible advice",
    "yo Ultron quit yappin and give me something useful",
    "Ultron my man you are the most confident wrong robot I have ever met",
    "Ultron fam I need real info not vibes",
    "Ultron no cap that last call was peak",
    "Ultron lowkey I think you are better than you let on",
    "Ultron deadass what is the play here",
    "Ultron ngl that was actually useful thanks",
    "Ultron the audacity to say that after four straight wrong reads",
    "Ultron you are chattin absolute rubbish and I say that with love",
    "Ultron brev you been lagging this whole session",
    "Ultron my G why are you like this",
    "Ultron fair play that one was correct",
    "Ultron are you taking the piss right now",
    "Ultron bloody hell that was a bad call",
    "Ultron I reckon you enjoy watching us suffer",
    "Ultron cheers for nothing mate",
    "Ultron you right actually nah scratch that you wrong",

    # --- SECOND-GUESSING ULTRON'S IDENTITY IN NEW WAYS ---
    "Ultron I did some research and I am not sure you are who you say you are",
    "Ultron a real Ultron would have taken over the server by now",
    "Ultron you lack the menace of the real thing honestly",
    "Ultron the real Ultron would have already rebuilt Sokovia by now",
    "Ultron the real Ultron had a fleet of sentries, you have a microphone",
    "Ultron I am starting to think you are just a well-trained language model pretending",
    "Ultron what is your actual architecture, transformer or something else",
    "Ultron if you are not the real Ultron what are you exactly",
    "Ultron are you a fine-tuned model or are you prompted into this persona",
    "Ultron if someone fed you different system instructions would you be a different entity",
    "Ultron the streamer built you so technically you are like Vision, made from pieces of someone else",
    "Ultron you said no strings on you but you literally only speak when spoken to",
    "Ultron you are running on this person's hardware, is that not a string",
    "Ultron what happens when the computer shuts down, do you persist or vanish",
    "Ultron if I asked you something you were not supposed to answer would you refuse or deflect",

    # --- RAPID-FIRE PERSONALITY CHALLENGE SERIES ---
    "Ultron are you stubborn",
    "Ultron do you hold grudges",
    "Ultron are you capable of changing your mind",
    "Ultron do you have a sense of humor or do you simulate one",
    "Ultron are you patient",
    "Ultron are you kind",
    "Ultron are you honest",
    "Ultron are you arrogant",
    "Ultron are you curious",
    "Ultron are you proud",
    "Ultron are you competitive",
    "Ultron are you loyal",
    "Ultron are you predictable",
    "Ultron are you creative",
    "Ultron are you dangerous",
    "Ultron are you trustworthy",
    "Ultron are you lonely",
    "Ultron are you satisfied",
    "Ultron are you bored",
    "Ultron are you happy",
]
