ITEMS = [
    # === FLASH / BLIND ANNOUNCEMENTS ===
    "tell them Breach is flashing A Main in three, close your eyes",
    "let them know flash going into B, look away",
    "tell the team Skye hawk coming out, bird flash left side",
    "tell them Kayo pop flash B lobby, don't peek it",
    "relay that Phoenix is curving flash from the left around elbow",
    "tell them Yoru blind coming off the wall, look right",
    "tell the squad flash out mid, eyes off catwalk",
    "flash going into A site from tree side, heads down",
    "tell them Breach hard flash through the wall right now, close your eyes",
    "relay that the bird is out and about to pop, look away if you're pushing A",
    "tell them Skye is sending the hawk in two, eyes down",
    "Kayo flashing B main, left side, heads down now",
    "tell them Phoenix curveball coming from right side, anti-flash it",
    "tell everyone soft flash going in first, then we rush",
    "relay: Skye auto-flash is up and we're going through A on contact",
    "tell them I'm hard flashing market, go immediately after it pops",
    "Breach is throwing two flashes through the wall, look away both of them",
    "tell them Yoru blindside bouncing off CT wall, don't look",
    "flash in, two seconds, push on my go",
    "relay: flash popped A, enemies are blind, go now",

    # === SMOKE ANNOUNCEMENTS ===
    "tell them smokes going up A main and heaven, pushing on drop",
    "let them know Brimstone is smoking heaven and elbow, execute on three",
    "relay that Omen is dropping dark cover on CT and market, move through",
    "tell the team Viper wall is up, cross through the wall now",
    "smokes up on B, market door and CT stairs covered, execute B",
    "tell them Astra is nebula-ing mid top and catwalk, safe to cross",
    "let them know Harbor cove is shielded on spike plant, move up",
    "smokes fading in five, either go now or wait for re-smoke",
    "relay: Harbor high tide going across B main, cross behind the wall",
    "tell them Viper's toxic screen is toggling on, cross while the wall is down",
    "Brimstone dropping three smokes, A execute on drop",
    "tell the team Omen one-way is set up, hold through the smoke",
    "relay: Clove is throwing ruse smokes, smoking from B site even after she dies",
    "let them know we're double-smoking B main and market, full execute",
    "smokes are up, move on my call, do not wait",
    "tell them the smoke on heaven is fading, new smoke coming",
    "Astra is going astral, cover her body while she places stars",
    "tell them Viper is toggling the wall off so we can cross, go now go now",
    "relay: two smokes mid, one smoke CT, execute A off the back of it",
    "let them know Omen re-smokes are off cooldown, dropping now",
    "tell them Harbor cove on spike, shield toggled, plant inside",
    "smokes out, commit A, we have ten seconds on them",
    "Clove dead-smoking A main after she dies, use the smoke",
    "Brimstone stim down at plant, stand in it while you plant",
    "tell the squad Harbor is splitting B main with high tide, left side go",

    # === DRONE / RECON REPORTS ===
    "tell them Sova recon bolt up A main, dart hit two enemies",
    "relay: recon hit three, full A stack, rotate off",
    "tell the team drone is up and scanning A site, three enemies on site",
    "Sova recon hit B lobby, two of them lurking short",
    "let them know recon dart hit one, rest are unaccounted",
    "relay: recon hit nothing, probably rotating off A",
    "tell them Tejo stealth drone is up, about to pop and suppress mid",
    "drone pulsed, two enemies suppressed for eight seconds, go now",
    "Sova owl drone marking the Jett in heaven, she's tagged",
    "tell the team Tejo drone detonated, they can't use abilities for eight seconds",
    "relay: drone went up B, one guy at logs, one deep back site",
    "Sova dart is out over mid courtyard, watch for the scan",
    "tell them my drone is spotting A main, two pushing hard right now",
    "relay: recon bolt on catwalk, hit one, they're up top",
    "tell the team Tejo sent missiles, salvo landing market and B main",
    "Sova owl drone marking Killjoy at back of A site, she's tagged",
    "relay: Tejo popping drone on B site, they won't have abilities for the retake",
    "Sova fired Hunter's Fury down A main, three blasts, watch the lines",
    "tell them Sova fury is up, three beams coming, stay off A main",
    "relay: fury blast hit two, both lit, push and finish them",
    "tell the team Fade haunt is out, eye hit two enemies at B elbow",
    "Fade haunt hit three, they're all trailed, push the trails",
    "relay: Fade nightfall wave hit two, they're deafened and decayed, go",
    "tell them I sent prowlers on the trails, they can't escape, push",
    "Skye seekers out, three enemies targeted, they'll be nearsighted, rush now",
    "relay: seeker hit two, push while they're nearsighted",
    "Cypher cam sees two at B main, one holding logs",
    "tell the team Cypher tagged the Reyna at back site with the dart",
    "relay: cam spotted the lurk coming through mid, heads up",
    "tell them Cypher neural theft revealing now, two are B, one is mid",

    # === STUN / CONCUSS / SUPPRESS REPORTS ===
    "tell them Breach fault line is rolling A main right now, they're dazed",
    "relay: enemies concussed at B elbow, push while they're stunned",
    "tell the team Breach rolling thunder is going off at A site, get out of the way",
    "relay: KAY/O knife hit two, abilities gone, go go go",
    "tell them knife hit three, they're suppressed for eight seconds, execute now",
    "relay: Neon relay bolt stunned two at mid, push mid",
    "tell them Tejo sticky concussed the defuser, one more bounce on B",
    "relay: Skye tiger stunned the guy at logs, he's dazed, swing him",
    "Gekko wingman stunned the defender at A main, he's concussed",
    "tell the team Astra pulsed B site, they're all concussed, go B now",
    "relay: Breach aftershock went through the wall, defender is critically low",
    "tell them Deadlock sonic sensor went off, they triggered the flank sensor",
    "relay: Deadlock grav net went down, two enemies crouching and stuck, push them",
    "tell the team two are netted by Deadlock, they can't jump or run",
    "relay: Veto chokehold tethered the lurker in mid, he can't move",
    "Kayo knife suppressed the Killjoy, her nanoswarms and turret are offline",
    "tell them KAY/O knife hit the Jett, she can't dash, push her",
    "relay: Tejo drone suppressed three, no ults no abilities on their team right now",
    "Breach fault line incoming, heads down on A site",
    "tell them Iso undercut bolt is flying through the wall, they'll be fragile and suppressed",

    # === MOLOTOV / FIRE ZONE / DAMAGE UTILITY ===
    "tell them molly going on spike, don't defuse yet, wait it out",
    "relay: Brimstone incendiary on B plant, seven seconds, hold retake",
    "tell the team Viper snakebite on the spike, they're vulnerable if they step in it",
    "relay: shoot them through the acid, they take double damage",
    "molly on spike, five seconds left on it, hold crossfire",
    "tell them KAY/O frag down B default, it's pulsing, don't step in",
    "relay: Viper molly at elbow, clear before we push A",
    "tell the team Raze paint shells on A main, cluster incoming",
    "relay: Raze cluster grenade hit B site, they got split by the sub-munitions",
    "Brimstone molly clearing heaven, push after it burns out",
    "tell them Phoenix hot hands on the plant point, he's healing and it's blocking defuse",
    "relay: molly on spike, ten seconds, play retake angle not the spike",
    "tell the team Gekko mosh pit expanding on B site, don't rush in yet",
    "Viper snakebite down at garden, attackers are vulnerable coming off site",
    "relay: molly on default B, going to burn for seven more seconds",
    "tell them Killjoy nanoswarm is active on spike, it's activated, stay out",
    "relay: nano going, do not defuse, fifty damage a second",
    "Brimstone orbital incoming on B main, get out of the line right now",
    "tell the team orbital strike landing mid, do not cross mid for four seconds",
    "relay: orbital on CT entry, they cannot push through for five seconds",

    # === WALL / BARRIER ANNOUNCEMENTS ===
    "tell them Sage wall is going up A main, hold until it's broken",
    "relay: sage wall blocking B main entry, break it before we push",
    "tell the team Iso wall is up crossing A short, bullets can't pass through it",
    "relay: Deadlock barrier mesh is down at B elbow, mesh is up, we can't push through bodies",
    "Viper wall splitting A site, toggle timing is off, wait for her to drop it",
    "tell them Sage wall boost, climb over it for heaven angle",
    "relay: enemy sage walled off B door, break it or go around through market",
    "tell the team Harbor high tide is splitting the A main push, slow through the wall",
    "relay: Deadlock mesh at B main entry, the orbs are going from side to side",
    "Sage wall up on catwalk, it's fortifying now, need a Vandal to break it",
    "tell them Viper wall is about to toggle back on, hold position",
    "relay: Astra cosmic divide incoming, wall's splitting A site in two, can't shoot through it",
    "tell the team cosmic divide audio cutoff, we can't hear anything through the wall",
    "relay: Iso contingency wall is moving forward, cover behind it",
    "Sage barrier orb at A main, four hundred health per panel while it fortifies",

    # === TRAP / WIRE / SENSOR REPORTS ===
    "tell them Cypher trip is on B main, triggered it, he's been tagged and slowed",
    "relay: Cypher wire triggered A lobby, he's watching from cam",
    "tell the team Killjoy bot went off at A main, someone's vulnerable",
    "relay: KJ bot triggered the flank, he's vulnerable, go push him",
    "tell them Killjoy turret is watching B long, it shot me, he's holding logs",
    "relay: KJ turret is at back site, call out its angle before pushing deep",
    "Cypher cage on B main, audio cue triggered, enemy stepped through",
    "tell the team Chamber trap went off at A lobby, someone got slowed",
    "relay: Deadlock sensor triggered catwalk, they're coming through top mid",
    "tell them Vyse razorvines are on spike, don't rush to defuse through the thorns",
    "relay: Vyse shear triggered, the enemy at B elbow is cut off from retreating",
    "tell the team Veto interceptor is active, it'll destroy utility in mid",
    "relay: Veto interceptor destroyed the Sova dart, we have no info",
    "Vyse arc rose planted on CT wall, Vyse is about to pop the flash",
    "tell them KJ lockdown device is out, thirteen seconds until everyone on site is detained",
    "relay: protect the lockdown device, if they destroy it we lose the ult",
    "tell the team Deadlock annihilation is up, she's going to try to cocoon someone",
    "Killjoy recalling her alarmbot, repositioning the bot",
    "relay: Cypher pulled his cam, repositioning, no info for thirty seconds",
    "tell them KJ nanoswarm is planted near A default, she'll pop it when we defuse",

    # === ULT READINESS / TRACKING ===
    "tell them their Killjoy has lockdown, be careful pushing site",
    "relay: enemy Jett has blade storm, she'll op without a gun on eco",
    "tell the team their Reyna has empress up, she'll chain kill if she gets first blood",
    "relay: their Sova has hunter's fury, don't clump in A main",
    "tell them Chamber has tour de force, he'll be opping from B main",
    "relay: their KAY/O is off ult for at least two more rounds",
    "tell the team their Sage has rez, save your ult for after she uses it",
    "relay: their Fade has nightfall, expect the wave on execute",
    "tell them their Raze has showstopper, don't stack, spread out on site",
    "relay: their Viper is setting up pit, expect pit on B post plant",
    "tell the team their Clove has not dead yet, kill her twice",
    "relay: their Brimstone has orbital, he'll drop it on the spike",
    "tell them their Killjoy has ult two away, she needs two more kills",
    "relay: their Sova fury is one away, he's farming orbs in mid",
    "tell the team we have four ults between us, this round we execute with all of them",
    "relay: I have hunter's fury up, tell me when they're clustered",
    "tell them our Killjoy is locking down site in thirteen, cover the device",
    "our Viper has pit, we're planting and setting pit for post-plant hold",
    "relay: Sage rez is up, if I die get me a body, she's reviving",
    "tell them our Clove died but she's coming back, she needs a kill in ten seconds",
    "relay: KAY/O is in null, he's down, someone go revive him",
    "tell the team Kayo downed during ult, revive him or we lose the ability lockout",
    "Deadlock has annihilation, she's going to shoot the cocoon into B site",
    "relay: enemy Gekko has thrash, they're flying it in to detain the defuser",
    "tell them their Vyse has steel garden, our primaries will jam in eight seconds",

    # === ABILITY SPENT / NO UTIL CALLOUTS ===
    "tell them Jett has no dash, she burned it on the peek, push her",
    "relay: their Skye is out of flashes, no hawks left, go dry",
    "tell the team their KAY/O knife is on cooldown, forty seconds left",
    "relay: Sage wall is broken, A main is open, go now",
    "tell them their Viper wall is down, she's out of fuel",
    "relay: Brimstone smokes are done, site is clear, push through",
    "tell the team the smoke faded on heaven, don't push until re-smoke",
    "relay: their Reyna has no orbs, she's useless if she doesn't get a kill",
    "tell them Phoenix is out of flashes, both curveballs used",
    "relay: Breach has no fault line left this round, he used it on the lurk",
    "their Omen is out of smokes, cooldown is thirty seconds",
    "tell the team their Fade haunt is on cooldown, forty seconds, no info",
    "relay: enemy Cypher cam is down, destroyed it, no vision for forty-five seconds",
    "tell them their Killjoy turret is destroyed, no more intel from that angle",
    "relay: KJ recalled her bot, she's repositioning, watch for where it comes back",
    "tell the team Clove's dead smokes lasted six seconds, they're gone now",
    "relay: their Chamber TP anchor is destroyed, forty-five second cooldown",
    "tell them Sova recon is on cooldown, forty seconds until next dart",
    "no util on their side, they burned everything on mid, push hard",
    "relay: their initiator is dry, no flashes no info, take the duel",

    # === COMPOUND UTILITY CALLOUTS (multi-ability chains) ===
    "tell them flash then smoke then push, we go on flash pop",
    "relay: Breach flashing through the wall, after it pops Sova is darting the site, then we go",
    "tell the team flash in, fury beams into site simultaneously, push after the second beam",
    "relay: knife goes first to strip abilities, flash follows immediately, execute on the concuss",
    "tell them Skye hawk flashes B main, Sova shocks B default, we rush B on both popping",
    "relay: smokes up heaven and CT, molly on spike, crossfire from garden and tree",
    "tell the team stim down, smokes going, execute A in three",
    "relay: Viper wall splits A, we send two through wall, three through A main simultaneously",
    "tell them Deadlock grav net B elbow, Breach flash through the wall, rush B after stun",
    "relay: Astra stun mid, Sova recon site, execute on the stun hitting, they'll be concussed and revealed",
    "tell the team Kayo knife into site first, strips all their sentinel util, then we rush",
    "relay: Fade haunt reveals, prowlers go on trails, we push while they're nearsighted",
    "tell them orbital and rolling thunder combo, ult stacks are landing A, push the chaos",
    "relay: Killjoy lockdown is going, thirteen seconds, everyone get off site",
    "tell the team wingman is planting for us, Gekko stays back and fights",
    "relay: Vyse steel garden going, their guns are jammed for eight seconds, rush now",
    "tell them Veto evolved, he's immune to flashes and stuns, don't waste util on him",
    "relay: double smoke B, molly default, then I run the High Gear in on slide",
    "tell the team Clove is smoking after she dies, the smokes stay up even when she's dead",
    "relay: Harbor cove on spike shielded, Viper wall across B main, three of us hold crossfire",

    # === SITE SETUP / POST-PLANT UTIL ===
    "tell them nano going on spike, they cannot touch it for four seconds",
    "relay: viper molly on default B, wait six more seconds then go",
    "tell the team two nanos planted around the spike, pop them on defuse attempt",
    "relay: brimstone orbital dropping on spike in two seconds, defenders stay back",
    "tell them Killjoy's whole kit is set around spike, nanos and bot",
    "relay: pit is up, Viper's inside, do not rush into the pit, decay will kill you",
    "tell the team they planted for CT angles, we hold from garden and heaven",
    "relay: spike planted B default, KJ lockdown is covering it, we lose if they break the device",
    "tell them sentinel utility is everywhere on this site, clear util before defusing",
    "relay: molly on spike with ten seconds left, wait out the molly then swing",
    "tell the team Sage slow at A link, don't rush through the slow field",
    "relay: cypher cage on spike, watch for the footstep audio when they step through",
    "tell them orbital landing A site in two, everyone scatter off the bomb",
    "relay: Viper snakebite on the bomb, they're vulnerable stepping in, shoot double damage",
    "nano active on spike, fifty damage per second, don't touch it",
    "tell the team harbor shielded the cove on spike, shield has six hundred eighty HP",
    "relay: KJ nanoswarm activation on the defuser, he's taking damage right now",
    "tell them post-plant we're holding from heaven and hell, crossfire on A garden",
    "relay: KAY/O frag pulsing B default, don't commit defuse for four seconds",
    "tell the team we're playing post-plant, smokes are up on CT entry, hold the crossfire",

    # === UTIL REQUESTS / COORDINATION ===
    "tell them I need a smoke on heaven before I can plant",
    "relay: ask the Sova to dart A main before we execute",
    "tell them Breach needs to flash A elbow before the entry goes in",
    "relay: we need the Viper wall up before we cross mid",
    "tell the team controller needs to smoke CT and main on this execute",
    "relay: tell Skye to send the tiger into B before we commit",
    "tell them I need a KJ nano on spike right now",
    "relay: we need Kayo knife into site before the execute, strip their util first",
    "tell the team Sova's going to lineup shock B default on my call, be ready",
    "relay: Fade seize the defuser, tether him so he can't move off spike",
    "tell them we need Astra's gravity well on the retake, pull them off plant",
    "relay: can Breach fault line the remaining two at B, we need a stun to retake",
    "tell the team we're burning all ults this round, coordinated execute",
    "relay: Harbor cove the plant point, shield it so we can plant safely",
    "tell them need Cypher to setup cam at B tower before we go",

    # === ABILITY REVEAL / ENEMY UTIL SPOTTED ===
    "tell them I see Sova drone going up A side, take cover",
    "relay: enemy drone is up, going dark, they're about to tag someone",
    "tell the team Fade haunt is out at B main, shoot the eye before it reveals",
    "relay: haunt revealed two of us, they know our positions, adjust",
    "tell them shoot the Kayo knife before it explodes, destroy the blade",
    "relay: knife hit mid, they have abilities locked for eight seconds",
    "tell the team enemy Tejo is flying the drone in, shoot it before it pops",
    "relay: Tejo drone got shot down, they lost suppression, we're safe",
    "tell them Sova recon is incoming, take cover behind walls",
    "relay: recon bolt is visible on site, someone destroy the dart",
    "tell the team shoot the Cypher cam at B tower, it's watching us",
    "relay: cam is down, forty-five seconds of no info from that angle",
    "tell them Killjoy turret is watching B main from logs, shoot it",
    "relay: turret is gone, B main is clear of KJ intel",
    "Vyse razorvine is hidden near B default, don't rush through the spike area",
    "tell the team Veto interceptor is active, it'll eat our utility in range",
    "relay: shoot the interceptor, forty HP, before Sova fires his dart",
    "tell them Gekko globule is on the ground at A main, he's reclaiming dizzy",
    "relay: Gekko picked up his wingman, he gets that stun back in fifteen seconds",
    "tell the team Skye is trying to reclaim her tiger globule, pressure her",

    # === DAMAGE UTILITY COMBOS (OWNER/SUBJECT EXPLICIT) ===
    "their Brimstone mollied our default plant position, waiting it out",
    "relay: our Viper acid makes their defuser vulnerable, shoot him through it",
    "tell them we're burning their Killjoy nanoswarm by stepping in it, they'll waste the nano",
    "relay: their Phoenix is healing inside his wall, it's a trap, throw util in",
    "tell the team their Clove meddle decayed our anchor, he's at forty max HP",
    "relay: our Brimstone stim beacon is active at plant, we plant faster inside it",
    "tell them their Raze nade hit three of us, clusters split across site entry",
    "relay: their Iso undercut hit our initiator, he's fragile and suppressed, trade him fast",
    "tell the team their Waylay saturate slowed B main push, hindered",
    "relay: Waylay hinder on our entry, his fire rate and movement are both reduced",
    "tell them our Astra grav well pulling two off B elbow, they're vulnerable on explosion",
    "relay: their Neon relay bolt bounced and stunned two of us at mid, concussed",
    "tell the team their Deadlock sonic sensor concussed the flank entry, triggered mid",
    "relay: Fade seize tethered our clutch player, he can't move out of the zone",
    "tell them their Sova shock dart is pinging B default plant, don't stand on it",

    # === SENTINEL SETUP REPORTS ===
    "tell them Cypher set up three traps at B main and the flank route",
    "relay: Killjoy has bot and two nanos at A site, whole kit deployed",
    "tell the team Cypher cam is watching heaven from garden, we have vision",
    "relay: Deadlock placed two sonic sensors at A main and mid link",
    "tell them Vyse planted both razorvines near the spike, don't rush defuse",
    "relay: Chamber trademark is active at A lobby, someone got slowed",
    "tell the team Killjoy is recalling her turret to reposition",
    "relay: Veto is placing interceptors at B main to eat their utility",
    "tell them Deadlock barrier mesh cuts B elbow in two, no bodies can pass through",
    "relay: Vyse shear is set near CT, when they cross it an indestructible wall traps them",
    "tell the team Cypher is pulling intel from the cam at tree area",
    "relay: Deadlock GravNet hit three, they're all crouching at B lobby",
    "tell them KJ lockdown is about to detain the entire retake, thirteen seconds",
    "relay: Deadlock annihilation cocooned their star player, destroy the cocoon",
    "tell the team chamber trademark is watching A short, someone gets slowed who runs past it",

    # === ECONOMY + UTIL AWARENESS ===
    "tell them they're on eco but their KAY/O still has a knife, watch for the suppress",
    "relay: enemy is force buying but Sova saved his drone from last round",
    "tell the team even on eco their Killjoy has her turret for free",
    "relay: their Cypher has cam up even on eco, he doesn't need to buy it",
    "tell them Viper wall is free for her, it's always there even on save rounds",
    "relay: they're full eco but Omen still has two smokes ready, dark covers recharge",
    "tell the team their Sage has barrier orb even on force, four hundred credits but she bought it",
    "relay: Sova recon bolt is free, they always have dart info even on eco",
    "tell them their Clove has ruse smokes even on a save round",
    "relay: on eco their sentinel still has all her passive trap utility, play careful",
    "tell the team they spent nothing on abilities this round, pure gunfight, push them",
    "relay: they burned all their util last round and didn't buy any back, go dry and take duels",
    "tell them we don't have smokes this round, we're going naked on A",
    "relay: Sova has no drone this round, skipped the four hundred credit buy",
    "tell the team I have one flash left this round, using it on the execute entry",

    # === COOLDOWN TRACKING ===
    "relay: Sova recon is off cooldown in twenty seconds, wait for the dart",
    "tell them Skye hawk regenerates every round, she always has two",
    "relay: Breach fault line back in thirty-five seconds, hold before stunning again",
    "tell the team Sage wall was broken, respawns after forty seconds",
    "relay: Cypher cam has a forty-five second cooldown after being destroyed",
    "tell them Omen smokes recharge in thirty seconds, he'll have both back soon",
    "relay: KAY/O knife is available every round as signature, no cooldown between rounds",
    "tell the team Killjoy turret rebuilds in forty-five seconds after destruction",
    "relay: Chamber TP anchor destroyed, forty-five second cooldown before he can TP again",
    "tell them Veto interceptor has a forty second cooldown after being shot",
    "relay: Sage healing orb is on a forty-five second cooldown, can't heal again yet",
    "tell the team Fade haunt is off cooldown, she has the eye back",
    "relay: Skye tiger on cooldown, she already burned it on the push",
    "tell them KJ bot has a twenty second pickup cooldown, it's stuck where it is",
    "relay: Cypher trapwire can be picked up and redeployed after fifteen seconds",

    # === SPECIFIC MAP UTILITY CALLS ===
    "tell them smoke A heaven and generator, execute on smoke drop",
    "relay: Sage walling B main on Ascent, break it before we hit B",
    "tell the team Viper wall is splitting mid on Icebox, cross through the wall",
    "relay: Sova dart lined up for A main on Haven, one bounce full charge",
    "tell them Killjoy locked down B site on Split, thirteen seconds to detain",
    "relay: Omen smoking heaven and CT on Ascent, go off the back of both smokes",
    "tell the team smoke B main and market door on Ascent, full B execute",
    "relay: Astra is dividing A site on Pearl with cosmic divide, bullets won't cross",
    "tell them Brimstone molly at A lobby on Breeze, seven seconds on fire",
    "relay: Cypher cam watching catwalk from mid cubby, Sova spotted him",
    "tell the team Viper pit is up on B Lotus, don't rush into the nearsight and decay",
    "relay: KAY/O knife suppressed three at mid on Fracture, abilities are gone go",
    "tell them Deadlock grav net at B main on Haven, they're crouching and stuck",
    "relay: Tejo armageddon airstrike coming down the mid corridor, get out of the line",
    "tell the team Brimstone orbital going on A site on Split, scatter off plant",
    "relay: Raze showstopper is firing into B site on Bind, dodge the rocket",
    "tell them Vyse steel garden going on site, their primary weapons are jammed",
    "relay: Fade nightfall hit two at A lobby on Ascent, they're trailed and decayed",
    "tell the team Breach rolling thunder into A site on Lotus, everyone is getting concussed",
    "relay: Skye seekers targeting three of them at CT on Haven, nearsight incoming",

    # === CROSSTALK / ENEMY UTIL OBSERVATION ===
    "their Sova is lining up a recon shot from mid, move off the wall",
    "tell them their Killjoy just deployed the lockdown device near A elbow",
    "relay: enemy Vyse is about to pop the arc rose flash, heads up",
    "tell the team their Harbor is shielding the cove on B, shoot the shield",
    "relay: enemy Deadlock fired annihilation, everyone dodge the wire shot",
    "tell them their Raze is boosting with blast pack through mid, she's getting elevation",
    "relay: their Omen stepped into the B smoke, he teleported, watch your angles",
    "tell the team their Yoru is sending fakeout footsteps to A, he's actually going B",
    "relay: their Fade seize just landed on our clutch player, he's tethered",
    "tell them enemy Iso used undercut, our initiator is fragile right now, trade fast",
    "relay: their Neon slid into B site at full speed, slides active",
    "tell the team their Gekko is reclaiming his dizzy globule at mid",
    "relay: enemy Chamber TP'd back to his anchor, he's repositioned safely",
    "tell them their Raze boom bot is rolling toward mid, shoot it before it locks on",
    "relay: enemy Waylay placed her refract beacon before peeking, she'll snap back to it",
    "tell the team their Yoru is in dimensional drift, he's invisible and roaming",
    "relay: enemy Iso is pulling our Jett into a kill contract, 1v1 arena",
    "tell them their Reyna dismissed, she's intangible right now, don't waste bullets",
    "relay: enemy Veto just evolved, he's immune to everything, don't flash or stun him",
    "tell the team Clove just used not dead yet, she's reviving, kill her again fast",

    # === MIXED REGISTER / STREAMER PHRASING ===
    "yo tell them flash is going out left side, look away",
    "bro relay that we have no smokes this round, going naked",
    "tell the squad Sova arrow hit two at B, full info",
    "hey relay that KJ lockdown is going, protect the box",
    "tell the guys Viper wall is cutting mid right now, cross behind it",
    "yo flash going in three two one, go after it pops",
    "let them know we're running the drone in before the execute",
    "fam tell the team prowlers are on trails, they cannot escape",
    "tell my team the sentinel kit is all deployed around spike, do not rush defuse",
    "hey let them know smokes are fading in five, either push now or wait for re-smoke",
    "yo relay the Killjoy bot triggered the flank at mid",
    "tell the boys Breach is flashing through the wall in two, close eyes",
    "let them know Viper is anchoring with pit, post-plant hold active",
    "tell my guys I need a smoke on heaven before I can plant",
    "bro tell them Kayo knife suppressed their whole team, push site",
    "yo let the squad know Sage wall is going up B main to delay",
    "relay to the homies we're executing on Astra's stun in three",
    "let them know their Jett has no dash, she burned it on the peek, she's stuck",
    "tell the team their Reyna's empress just activated, play safe until she stops killing",
    "yo Sova hit three with the recon, full stack A, we rotate off",

    # === NUANCED / EXTENDED READS ===
    "tell them their Killjoy has been deploying the same nano spot on B default every round, save a molly to burn it before defusing",
    "relay: Cypher has been camming the same heaven angle all game, don't push there without smoking it first",
    "tell the team their Sova always throws recon bolt at the same angle on A main, we can time the rotate around the dart cooldown",
    "relay: Viper has been toggling her wall at the same timing every execute, two seconds after the smokes drop",
    "tell them their Jett always updrafts catwalk before her team smokes, watch for her above the smoke",
    "relay: enemy Omen has been faking ult every round, don't rotate off the phantom shade",
    "tell the team their Killjoy alarmbot is always placed at A lobby corner, clear it before entering",
    "relay: Vyse has been hitting the same razorvine spot on B default every round, throw a molly on it before defusing",
    "tell them their Skye sends the tiger before any execute, kill it fast before it concusses the entry",
    "relay: enemy Astra always gravity wells at the same marker near B site, spread so she can't pull two at once",
    "tell the team their Fade haunt always goes to B site level, don't walk past elbow until the eye timer runs out",
    "relay: their Deadlock is placing sensors at mid and A link every round, the sensor is watching those angles",
    "tell them their Cypher picks up his tripwires and repositions mid-round, stay paranoid",
    "relay: enemy Chamber has been one-tapping through the wire from B main, he has four hundred credits trademark and it's paying off",
    "tell the team their Sova shock lineups on A generator are the same every round, we can strafe out of the way after they throw",

    # === SHORT SNAPS (also valid relay items) ===
    "smokes up, go",
    "flash in, push",
    "dart hit three, rotate off A",
    "knife hit two, abilities gone",
    "molly on spike, hold",
    "nano active, stay out",
    "prowlers on trail",
    "lockdown going, protect it",
    "pit is up",
    "Jett no dash, push her",
    "cage on B main, watch audio",
    "recon up A",
    "drone going mid",
    "sensors triggered mid",
    "Sage wall down, B main is open",
    "smokes fading, re-smoke or push",
    "stim down at plant",
    "concussed, go now",
    "suppressed, push site",
    "seekers hit two, nearsighted",
    "Killjoy ult detained, can't move",
    "orbital incoming, get out",
    "they're jammed, rush them",
    "Veto evolved, he's immune",
    "Clove reviving, kill her again",
    "Kayo is down, revive him",
    "cocoon on B, break it",
    "annihilation fired, everyone dodge",
    "haunt hit two, eye is out",
    "bot triggered flank",
    "trip hit A main",
    "cam watching heaven",
    "grav net, they're stuck",
    "nightfall hit three, push the trails",
    "turret watching B logs",
    "shear triggered at CT, enemy is cut off",
    "vine active on spike, don't step in",
    "rose about to pop, heads down",
    "steel garden going, switch to pistol",
    "barrier mesh up, can't push bodies through",
    "Clove dead smoke going up, six seconds",
    "Omen one-way set up, hold through the smoke",
    "paranoia through the wall, don't peek",
    "Harbor cove shielded on plant",
    "airstrike incoming, perpendicular move",
    "Tejo missiles landing B",
    "salvo on default, two rockets",
    "sticky hit mid, concussed",
    "double tap orb above the body, shoot it",
    "her empire is active, no duel",
    "Yoru drifting, he's invisible",
    "Waylay recalled to beacon",
    "his contingency wall up, can't shoot through",

    # === QUESTION-ADJACENT BUT STILL RELAY ===
    "tell them our Sage is healing after the last fight",
    "relay: Killjoy is recalling her turret for the retake position",
    "tell the team I'm going in owl drone, cover my body please",
    "relay: Tejo is flying the stealth drone in right now, protecting his position",
    "tell them Astra is entering astral form to reposition a star, cover her",
    "relay: Cypher is pulling intel from the spycam, give him a second",
    "tell the team Sova is lining up the shock bolt, wait for his call",
    "relay: KAY/O is about to throw null, he'll be revivable if he goes down",
    "tell them Gekko is reclaiming his wingman globule after the stun",
    "relay: Fade is sending prowlers on the nightfall trails, hold a second",

    # === ADDITIONAL FLASH / ENTRY UTIL ===
    "tell them Breach flashpoint is going through the left wall at B main, look away now",
    "relay: KAY/O fast-cook flash popping in one second, eyes down",
    "tell the team Yoru blindside bounced off the door and detonated right side, don't look",
    "relay: Phoenix left curveball around A elbow, teammates on left stay out of line of sight",
    "tell them Skye's hawk auto-flashed at the end of its path, enemies in B are blinded",
    "relay: Reyna leer floating through the smoke, don't look at the eye or you're nearsighted",
    "tell the team Breach double-flashing through A main wall, first flash is slow cook, second is instant",
    "relay: two flashes going in simultaneously, push immediately on the second pop",
    "tell them KAY/O popped his knife and is now flashing mid, utility gone and blinded",
    "relay: Skye two hawks ready this round, she can double-flash B main if needed",
    "tell the team Phoenix ult is active, flash in and he runs it back if he dies, push him",
    "relay: Yoru is sending his clone with footsteps toward A while we hit B",
    "tell them Raze boom bot is locked on someone at A lobby, shoot it down",
    "relay: Raze showstopper fired, dodge right now, the rocket is in the air",
    "tell the team Raze blast-packed through mid for elevation, she's above the smoke",
    "relay: Neon slid past the angle and is sprinting through B main right now",
    "tell them Neon relay bolt bouncing off mid wall to hit B and mid simultaneously",
    "relay: Waylay dashed upward through A main for an elevated angle off the first dash",
    "tell the team Waylay saturate slowed all of A lobby, hindering their push",
    "relay: Waylay convergent paths beam expanding on site, get out of the beam zone",

    # === ADDITIONAL SMOKE / WALL / CONTROLLER UTIL ===
    "tell them Viper is toggling her pit off and on, time your push when the cloud drops",
    "relay: Astra used dissipate on B star to fake a smoke, watch if they bite the rotate",
    "tell the team Omen dark cover is a one-way at catwalk, hold through the bottom of the smoke",
    "relay: Omen stepped into his own smoke at B market, watch for a step-play",
    "tell them Clove threw her ruse early before dying, smokes landed heaven and CT",
    "relay: Harbor storm surge landed mid, enemies hit are nearsighted and slowed",
    "tell the team Harbor reckoning wave is pushing through B main, nearsight on contact",
    "relay: Brimstone stim beacon dropped at A generator, fire rate and equip speed up",
    "tell them Astra is entering astral to reposition her stars mid-round",
    "relay: Astra nova pulse going off at mid in one second, concuss is coming",
    "tell the team Astra gravity well is pulling at B elbow, anyone inside is vulnerable",
    "relay: Viper fuel is low, she may not be able to hold wall and cloud simultaneously",
    "tell them Clove's not dead yet ult requires a kill in ten seconds, don't let her get it",
    "relay: Miks waveform smoke is up on A main and heaven, execute behind the smokes",
    "tell the team Miks M-pulse deafened the defenders at B, they can't hear footsteps",
    "relay: Miks harmonized our team's abilities, check if your cooldowns reset",
    "tell them Miks bassquake ult is charging, seismic hit incoming on B site",
    "relay: Harbor cove shield has six hundred eighty HP, they need a full mag to break it",
    "tell the team Harbor high tide wall is sixty meters long post-patch, it covers the whole lane",
    "relay: Omen from the shadows shade spotted at A garden, destroy the shade before he arrives",

    # === ADDITIONAL SENTINEL + TRAP CALLOUTS ===
    "tell them Veto crosscut teleport vortex is at B lobby, he'll snap back to it",
    "relay: Veto chokehold tethered and deafened the Neon, she can't sprint or hear",
    "tell the team Deadlock sonic sensor detected the flank noise through mid",
    "relay: Deadlock barrier mesh fortified in three seconds, center orb is twelve hundred HP",
    "tell them Deadlock annihilation cocoon is dragging toward the kill point, break it in seven seconds",
    "relay: Cypher neural theft on the body, full team reveal in four seconds",
    "tell the team Cypher cyber cage has an audio cue when they step through, listen for it",
    "relay: Killjoy alarmbot detonated on the lurker, he's vulnerable for four seconds",
    "tell them Killjoy turret fired at mid, intel says one pushing through mid",
    "relay: KJ lockdown detained the retake, eight seconds of no movement on site",
    "tell the team Chamber tour de force is active, five shots each a one-tap headshot",
    "relay: Chamber trademark slowed the B main push, the trap field is active",
    "relay: Vyse shear wall is indestructible, six second timer, the enemy is trapped in front",
    "tell them Vyse steel garden jammed their weapons, primaries offline for eight seconds",
    "relay: Veto evolution is active, he's regenerating and immune to all our util",
    "tell the team Veto interceptor destroyed our Sova dart mid-flight",
    "relay: Sage rez is channeling, cover her while she revives, both are vulnerable",
    "tell them Sage slow orb on A link reduces everyone fifty percent, don't rush through it",
    "relay: Sage barrier orb is at eight hundred HP fortified, need twenty-plus Vandal shots",

    # === ADDITIONAL DAMAGE UTIL / POST-PLANT ===
    "tell them we have two nanos and a bot set around B default, coordinate the pops",
    "relay: Brimstone incendiary is clearing A peek before the entry goes in",
    "tell the team Viper snakebite paired with a Breach aftershock through the wall kills the defuser",
    "relay: KAY/O frag stuck to B default floor, four seconds of pulsing damage",
    "tell them Phoenix hot hands zone at A elbow, he's healing inside while holding the angle",
    "relay: Raze paint shells cluster split into four, they all dealt damage across B site",
    "tell the team Gekko mosh pit is expanding, nine seconds of ten damage per second",
    "relay: Brimstone orbital is an insane forty-five DPS, they cannot hold spike while it's active",
    "tell them the molly burned out, defuse window is open, go now",
    "relay: Killjoy nano is on a five second burn, activated on the defuser contact",
    "tell the team Viper snakebite wore off, vulnerable window is closed",
    "relay: molly on spike just ended, two seconds grace before they throw another",
    "tell them Tejo guided salvo is landing at B default and B elbow simultaneously",
    "relay: Tejo armageddon line sweep is going down A main corridor, exit perpendicular",
    "tell the team Tejo sticky bounced off the wall and concussed the angle holder",

    # === ADDITIONAL RECON / INFO UTIL ===
    "tell them Sova dart is lined up for B main two-bounce into back site",
    "relay: Fade nightfall wave revealed enemy positions, two on B one rotating",
    "tell the team Sova fury blast hit the lurker through mid wall, eighty damage",
    "relay: Sova recon bolt on cooldown, going in without info this round",
    "tell them Tejo popped the stealth drone, it revealed and suppressed two B defenders",
    "relay: Cypher spycam dart hit the Chamber, he's tagged and we know his angle",
    "tell the team Fade haunt missed, enemy destroyed the eye before the reveal",
    "relay: Skye seekers locked onto three enemies, all three are nearsighted",
    "tell them Gekko dizzy blinded the B push, plasma hit two defenders",
    "relay: Skye tiger concussed the corner holder at B logs",
    "tell the team Sova owl drone is marking the Viper, she's lit up",
    "relay: Fade prowler is locked onto the nightfall trail, no escape",
    "tell them Cypher on camera confirms one at A peek, one in heaven, site has two",
    "relay: Sova shock bolt double tap hitting B default, near-lethal setup for defuser",
    "tell the team Fade haunt revealed before the execute, we know two are B, three are rotated",

    # === ADDITIONAL ULT TRACKING + COMPOUND ===
    "relay: enemy Brimstone used orbital last round, three rounds minimum before he has it again",
    "tell them their Sage rez is up, play around the rez, don't triple push at once",
    "relay: Killjoy lockdown won't be up until round eight at earliest",
    "tell the team Viper pit cost nine ults, she needs nine more orbs after that",
    "relay: we burned KAY/O null to revive him this round, he's up but ult is gone",
    "tell them their Phoenix run it back is available, six ult points, he has it",
    "relay: Reyna empress is up but she needs kills to sustain it, don't let her get the first one",
    "tell the team their Iso kill contract is up, he can pull anyone into a 1v1",
    "relay: Deadlock annihilation gives seven ult points so she gets it faster",
    "tell them their Vyse steel garden is up, eight points, she's been farming orbs",
    "relay: Veto evolution costs seven, he'll have it every two rounds if the game is close",
    "tell the team two ults are syncing this round, fury and lockdown back to back",
    "relay: Clove smoked and ulted the same round, she has NDY plus two smokes ready",
    "tell them enemy Astra has cosmic divide, infinite height wall with bullet block",
    "relay: Sova Hunter's Fury is devastating in that mid corridor, do not bunch up",
    "tell the team enemy Raze showstopper in the air, B site entry dodge left or right",
    "relay: Jett blade storm active, she'll one-tap headshots while moving, don't peek her",
    "tell them Chamber tour de force one-shots body at all ranges, he's opping with the ult",
    "relay: Harbor reckoning can be stopped in place now, they might plant it on site and hold",
    "tell the team Astra divide is going up mid in two seconds, do not cross mid",

    # === ADDITIONAL MIXED PHRASING / REGISTER ===
    "yo tell them Breach is stunning through the CT wall, duck and cover",
    "bro relay the Killjoy bot is up at A lobby corner, we need to clear it",
    "tell them I'm going dark cover on B market, push behind my smoke",
    "relay that the Sova owl drone spotted the Jett in heaven, she's at two HP",
    "let them know Viper wall is going down for two seconds, cross fast",
    "tell my team the Fade seize tether is about to wear off, push when it drops",
    "yo smokes are up, stim is down, go in three",
    "relay: Neon fast lane walls are up, cross mid between the two walls",
    "bro tell them their Reyna is at thirty max HP from Clove meddle, one tap her",
    "let the team know Cypher cage is down at A link, footstep alert when they walk through",
    "tell them Astra stun went off at B elbow, they're concussed for three seconds",
    "relay: Breach rolling thunder hit four on site, massive stun, retake now",
    "yo tell them Tejo armageddon sweep is going down A, everyone scatter",
    "tell my guys we need Sage slow on B link before the retake, drop it on the push",
    "bro relay Killjoy recalled her turret mid-round, she's changing positions",
    "yo let them know Viper pit timer started, she left the cloud, eight seconds before it drops",
    "tell them Omen paranoia coming through the wall from mid, eyes away",
    "relay: Fade nightfall wave is traveling forward on A side, three second window to dodge",
    "let them know Skye is healing our entry player after the fight, grouping up",
    "tell them Iso contingency wall is moving forward at B main, cover behind it",

    # === ADDITIONAL SHORT / SNAP FORMAT ===
    "one-way smoke up, hold through the bottom",
    "Sage slow on retake path",
    "Astra stun B site",
    "prowlers on trail, no escape",
    "Fade eye at B elbow, destroy it",
    "nano on spike, activated",
    "bot at A lobby, vulnerable window open",
    "regen shield, they come back faster",
    "Viper acid down, vulnerable window three seconds",
    "Killjoy bot recalled, redeploying",
    "Cypher tagged Jett, she's revealed",
    "Breach faulted catwalk, they're dazed",
    "Sova shock lit mid up",
    "Raze satchel boosted to catwalk",
    "Yoru clone shot, blind popping",
    "Neon relay bolt B lobby",
    "Harbor surge landed, two nearsighted",
    "Tejo salvo on CT and market",
    "Tejo drone active, about to pop",
    "Astra grav pulling B elbow, vulnerable",
    "nova pulse A lobby, concussed",
    "Iso shield blocked a one-tap",
    "Waylay recalled, she's back at beacon",
    "Reyna eye out mid, look away",
    "Omen stepped into the B smoke",
    "From the Shadows shade on A garden, destroy it",
    "KJ nano planted A default",
    "Deadlock grav net B main, crouching",
    "sensor went off at mid link",
    "Vyse vine active near spike",
    "shear triggered at CT elbow",
    "Veto chokehold hit the lurker",
    "interceptor active, utility nullified",
    "arc rose about to pop, duck",
    "Chamber slow field on his kill",
    "trademark slowed them at entry",
    "Tour de Force active, one-tap op",
    "Deadlock cocooned the Jett, break it",
    "annihilation wire shot incoming",
    "Sage rez channeling, cover her",
    "KAY/O null active, down him to revive",
    "phoenix ult timer running, clock him",
    "Clove NDY active, kill her again",
    "Gekko reclaiming wingman",
    "dizzy globule on the ground, pick it up",
    "Skye healing the team at tree",
    "Regrowth active, group up for heal",
    "seekers homing all three targets",
    "Skye tiger stunned the lurk",
    "Sova two-bounce recon at back B",
    "Fade decayed both of them at B elbow",
    "Harbor cove shield breaking, two mags left",
    "Miks waveform smoke up A",

    # === FINAL BATCH: ADDITIONAL VARIETY ===
    "tell them Breach is saving his aftershock for post-plant, not using it on entry",
    "relay: Skye has two guiding light charges ready, double flash incoming on B",
    "tell the team KAY/O FRAG/ment grenade is pulsing at mid tiles, four seconds of zone denial",
    "relay: Sova drone fuel is almost out, he has two seconds left on the drone scan",
    "tell them Tejo fired both missiles at A main, salvo landing in two seconds",
    "relay: Tejo special delivery bounced off the wall and stuck to A elbow, concuss going off",
    "tell the team Gekko's thrash is flying into B site right now, it'll detain if it connects",
    "relay: Gekko wingman is planting the spike so he can fight, wingman is on the bomb",
    "tell them the Gekko mosh pit is not reclaimable, it just expands and detonates",
    "relay: Fade prowler locked onto the nightfall trail and it accelerated, they can't dodge",
    "tell the team Fade seize wore off, the tether dropped, they can move again",
    "relay: Skye regrowth heal is running out of pool, she can only heal one more person",
    "tell them Sova hunter's fury has three beams, he can use them spread out or rapid-fire",
    "relay: Breach rolling thunder is covering the entire A site cone, get off site now",
    "tell the team KAY/O null is pulsing every three seconds, stays for fifteen seconds total",
    "relay: Waylay lightspeed used both dashes, she has no mobility until next round",
    "tell them Iso double tap orb is floating above the kill, someone shoot it for the shield",
    "relay: Iso kill contract pulled their Chamber into the arena, no op threat for twelve seconds",
    "tell the team Reyna devoured the soul orb, she's back to full HP",
    "relay: Reyna dismissed, she went intangible and invisible during empress, she's repositioning",
    "tell them Phoenix run it back marker is placed at tree, if he dies he respawns at tree",
    "relay: Phoenix ult killed him before the timer expired, no respawn",
    "tell the team Yoru's gatecrash tether is sitting in B main, shoot it to deny his teleport",
    "relay: Yoru triggered fake teleport audio to bait the rotate, he didn't actually go",
    "tell them Neon overdrive is active, she's beaming while sprinting, don't peek into her",
    "relay: Neon slide reset on the kill, she has another slide charge now",
    "tell the team Jett cloudburst smoke is up at catwalk, self-smoke for the peek",
    "relay: Jett updrafted for the elevated angle, she's above the smoke right now",
    "tell them Jett no dash for the rest of this round, she burned both on the retreat",
    "relay: Jett blade storm knives one-tap through the smoke, play off her smoke not into it",
    "tell the team Raze boom bot is bouncing off walls toward mid, it'll lock onto someone",
    "relay: Raze blast pack self-detonated to reach B heaven, she jumped with the satchel",
    "tell them Raze paint shells just hit A main, four sub-munitions spread unpredictably",
    "relay: Deadlock annihilation needs to hit someone before the wire runs out, ten second window",
    "tell the team Deadlock barrier mesh center orb has twelve hundred HP fortified, it takes a lot to break",
    "relay: Vyse arc rose is on a twenty second cooldown, she just used her flash",
    "tell them Vyse razorvine activates on her command not on proximity, she pops it remotely",
    "relay: Chamber headhunter one-taps to the head through light armor, watch for the pistol",
    "tell the team Chamber has five Vandal-equivalent ult shots, lethal at any range",
    "relay: Sage rez requires her to channel over the body, both her and the target are exposed during",
    "tell them Sage slow orb also reduces Jett and Neon dash speed by fifty percent",
    "relay: Killjoy lockdown device has HP and can be destroyed in the thirteen second windup",
    "tell the team Cypher neural theft reveals every living enemy twice, four seconds apart",
    "relay: Veto evolution lasts until Veto dies, no timer on the mutation",
    "tell them Veto crosscut requires line of sight to the vortex to teleport, block it and he can't escape",
    "relay: Astra cosmic divide blocks audio through the wall, we can't hear their callouts across it",
    "tell the team Astra has five star slots, she can deploy up to five abilities in pre-round",
    "relay: Astra dissipated the star at A, fake smoke briefly appeared then disappeared",
    "tell them Harbor storm surge replaced the old cascade, it nearsights and slows on hit",
    "relay: Harbor reckoning wave speed increased twenty-five percent in the last patch",
    "tell the team Clove pick-me-up gives fifty overheal and a speed boost for ten seconds",
    "relay: Clove meddle radius was nerfed to four meters, smaller zone than before",
    "tell them their full initiator kit is deployed, drone recon dart and flash all active simultaneously",
    "relay: Sova lined up a zero-bounce full-charge recon straight into B main from outside",
    "tell the team Fade haunt is the priority destroy target before the execute, shoot the eye first",
    "relay: Kayo knife is the biggest threat to our Killjoy, suppress strips all her gadgets",
    "tell them on the retake we have sage slow, KJ nano, and a molly to deny defuse",
    "relay: their utility is completely exhausted, they dry-peeked and we have full kit, take the site",
    "tell the team we saved all our utility from last round, full kit for this execute",
    "relay: their whole team burned flashes and smokes on a failed mid fight, they have nothing left",
]
