"""Verbatim "repeat to my team X" commands (the soundboard check -- a teammate asks
the user to say a specific word/phrase to prove a human is on comms). Must relay the
phrase EXACTLY (verbatim=True), no LLM."""
ITEMS = [
    'repeat to my team watermelon',
    'repeat to jett watermelon',
    'repeat to the squad pineapple',
    'echo to my team rutabaga',
    'repeat banana to my team',
    'ultron repeat to my team kumquat',
    'repeat to sage kumquat',
    'repeat to my team exactly persimmon',
    'repeat after me to my team quesadilla',
    'repeat to the boys blue forty two',
    'repeat to my team the following red October',
    'repeat to omen red October',
    'repeat to my team seven seven seven',
    'repeat to the squad echo charlie',
    'echo to my team falcon nine',
    'repeat mango tango to my team',
    'echo to killjoy mango tango',
    'ultron repeat to my team purple monkey dishwasher',
    'repeat to my team exactly supercalifragilistic',
    'repeat after me to my team bumblebee',
    'repeat to the boys zucchini',
    'repeat to jett zucchini',
    'repeat to my team the following albatross',
    'repeat to my team code word falcon',
    'repeat to the squad the eagle has landed',
    'echo to my team green light go',
    'repeat to sage green light go',
    'repeat alpha bravo charlie to my team',
    'ultron repeat to my team fuzzy pickles',
    'repeat to my team exactly marmalade',
    'repeat after me to my team kerfuffle',
    'repeat to omen kerfuffle',
    'repeat to the boys wombat',
    'repeat to my team the following snickerdoodle',
    'repeat to my team flibbertigibbet',
    'repeat to the squad gobbledygook',
    'echo to killjoy gobbledygook',
    'echo to my team whatchamacallit',
    'repeat code red to my team',
    'ultron repeat to my team nine lives',
    'repeat to my team exactly jellybean',
    'repeat to jett jellybean',
    'repeat after me to my team ravioli',
    'repeat to the boys cattywampus',
    'repeat to my team the following lollygag',
    'repeat to my team brouhaha',
    'repeat to sage brouhaha',
    'repeat to the squad gigawatt',
]
