"""Curated-command intent phrasings (refuse/dismiss/criticize/praise/ask/status).
Each should route to a curated full-Ultron response (deterministic, no LLM)."""
ITEMS = [
    "tell my team that I'm not going to answer that because it's stupid",
    "tell my team that's a stupid question",
    'tell my team that is a ridiculous question',
    "tell my team that's an absurd question",
    "tell my team I don't know the answer to that",
    "tell my team I don't want to talk about that",
    "tell my team I don't want to get into that",
    "tell my team I'm not answering that",
    "tell my team I won't argue with them",
    "tell my team I'm not going to argue",
    "dismiss my team's flame",
    'tell my team their flame means nothing',
    "tell my team I know I'm cool",
    "tell my team I know it's cool",
    "tell my team you're welcome",
    'tell my team they are throwing the game',
    "tell my team they're throwing",
    'tell my team to stop flaming each other',
    'tell my team that is a bad idea',
    "tell my team that's a terrible idea",
    'tell my team they are wrong',
    "tell my team that's wrong",
    'tell my team I know what I am doing',
    'tell my team to trust me',
    'tell my team trust the plan',
    "tell Jett that I'm not going to answer that because it's stupid",
    "tell Sova that I'm not going to answer that because it's stupid",
    "tell Cypher that I'm not going to answer that because it's stupid",
    'tell Killjoy they are an idiot',
    'tell Raze they are an idiot',
    'tell Reyna they are an idiot',
    "tell Omen you're an idiot",
    "tell Viper you're an idiot",
    "tell Sage you're an idiot",
    'ask Brimstone if they are throwing',
    'ask Neon if they are throwing',
    'ask Fade if they are throwing',
    'ask Breach to explain why they are throwing',
    'ask KAY/O to explain why they are throwing',
    'ask Astra to explain why they are throwing',
    "ask Harbor what they're doing",
    "ask Gekko what they're doing",
    "ask Chamber what they're doing",
    'tell Skye to stop throwing',
    'tell Yoru to stop throwing',
    'tell Phoenix to stop throwing',
    'tell Clove to stop griefing',
    'tell Deadlock to stop griefing',
    'tell Vyse to stop griefing',
    'tell Iso they are throwing',
    'tell Tejo they are throwing',
    'tell Waylay they are throwing',
    'tell Miks they are wrong',
    'tell Veto they are wrong',
    'tell Jett they are wrong',
    'tell Sova I know what I am doing',
    'tell Cypher I know what I am doing',
    'tell Killjoy I know what I am doing',
    'tell Raze to trust me',
    'tell Reyna to trust me',
    'tell Omen to trust me',
    'inform my team that Viper has disconnected',
    'inform my team that Sage has disconnected',
    'inform my team that Brimstone has disconnected',
    'tell my team Neon disconnected',
    'tell my team Fade disconnected',
    'tell my team Breach disconnected',
    'tell my team KAY/O is afk',
    'tell my team Astra is afk',
    'tell my team Harbor is afk',
    'tell my team Gekko reconnected',
    'tell my team Chamber reconnected',
    'tell my team Skye reconnected',
    'tell Yoru good job',
    'tell Phoenix good job',
    'tell Clove good job',
    'tell Deadlock great job',
    'tell Vyse great job',
    'tell Iso great job',
    'tell Tejo nice shots',
    'tell Waylay nice shots',
    'tell Miks nice shots',
    'tell Veto well played',
    'tell Jett well played',
    'tell Sova well played',
    'tell Cypher nice clutch',
    'tell Killjoy nice clutch',
    'tell Raze nice clutch',
    "tell Reyna they're carrying",
    "tell Omen they're carrying",
    "tell Viper they're carrying",
    'tell Sage their flame means nothing',
    'tell Brimstone their flame means nothing',
    'tell Neon their flame means nothing',
]
