ITEMS = [
    # ── JETT OPINIONS ──────────────────────────────────────────────────────────
    "tell them our Jett needs to stop dry peeking the op",
    "let the team know their Jett has no dash left, she can't escape",
    "tell them Jett with an op is a problem on this map",
    "tell them to trade Jett immediately when she peeks, she has no dash",
    "tell them our Jett is the best fragger we have, give her space to work",
    "tell the team their Jett is one-tricking and it's working against us",
    "tell them Jett players at this rank think they're better than they are",
    "tell them the enemy Jett has been baiting her team all game",
    "tell them to shut down Jett's op angle before she gets a free pick",
    "tell them our Jett is playing too aggressively and burning her dash for nothing",
    "tell them the Jett diff is real this game, she's cracked",
    "tell them their Jett hasn't hit a single shot in three rounds, stop giving her the op",
    "tell them Jett without her dash is just a duelist with a knife, she's punishable now",
    "tell them if our Jett instalocked without asking I don't want to hear her call mid",
    "tell them this Jett is a smurf, her flicks are inhuman",
    "tell my team the enemy Jett is going aggressive every single round, she's predictable",
    "tell them Jett is the highest pick rate in the game and the worst-played agent in ranked",
    "tell them to shut down the Jett early and she falls apart, she needs the snowball",
    "tell them our Jett has five kills this half, she's the only reason we're alive",
    "tell them the enemy Jett is tilting, she's dry peeking everything now",

    # ── PHOENIX OPINIONS ───────────────────────────────────────────────────────
    "tell them Phoenix is self-sufficient but his team contribution is basically zero",
    "tell them their Phoenix hasn't used Run it Back once this half, he's playing scared",
    "tell them Phoenix's curveball around that corner is going to blind us, call it out",
    "tell them a Phoenix who heals himself mid-fight is genuinely hard to kill",
    "tell them the Phoenix is going to Run it Back into B, don't commit fully",
    "tell them our Phoenix is the only one trading, at least someone is doing their job",
    "tell them Phoenix's flash is the most underrated in the game because it curves",
    "tell them the enemy Phoenix is on a four-kill run in his ult, we have to kill him before it ends",
    "tell them Phoenix down bad this game, he's feeding every round",
    "tell them their Phoenix has been running his ult and just flaming into a wall every time",

    # ── RAZE OPINIONS ──────────────────────────────────────────────────────────
    "tell them Raze is the safest duelist pick in this meta, Showstopper alone wins rounds",
    "tell them their Raze is boosting into site every round with blast pack, catch her mid-air",
    "tell them our Raze should be using Paint Shells before she pushes, not after",
    "tell them the enemy Raze cleared our setup with one Showstopper rocket",
    "tell them Raze with blast pack mobility is the scariest thing in tight corridors",
    "tell them their Raze bot is going to clear the corner before she pushes, hold deep",
    "tell them Raze is one of the few duelists who provides real utility and frags",
    "tell them if their Raze gets another Showstopper off we need to spread out",
    "tell them our Raze is only using blast pack for kills and wasting the mobility",
    "tell them the Raze nade lineup on this site is going to land on the spike, watch it",
    "tell them Raze diff this half, she single-handed their whole execute",
    "tell them the enemy Raze has been baiting her team into site with Boom Bot every round",

    # ── REYNA OPINIONS ──────────────────────────────────────────────────────────
    "tell them Reyna is a stat-padder and her team will suffer for it",
    "tell them if Reyna doesn't get a kill she's completely useless to her team",
    "tell them their Reyna is in Empress, we need to kill her before she chains",
    "tell them Reyna no kills means no dismiss, she can't escape right now",
    "tell them Reyna players are the most selfish people in this game",
    "tell them shoot the Reyna eye or we're all getting nearsighted",
    "tell them their Reyna is snowballing, we have to shut her down this round",
    "tell them the enemy Reyna is on a seven-kill streak and we're handing her orbs",
    "tell them Reyna Empress is up, don't peek her one-on-one",
    "tell them our Reyna has zero assists this game which tells you everything",
    "tell them a Reyna who can't get a first blood in round one is dead weight",
    "tell them the enemy Reyna dismissed into that corner, she's still in the site",

    # ── YORU OPINIONS ──────────────────────────────────────────────────────────
    "tell them their Yoru is the best mind-game player we've faced all session",
    "tell them don't fall for the fake teleport audio, that's exactly what Yoru wants",
    "tell them their Yoru has been in Dimensional Drift for thirty seconds gathering intel",
    "tell them Yoru is the hardest duelist to master and this one clearly hasn't",
    "tell them the Yoru Fakeout is a distraction, real pressure is coming from B",
    "tell them their Yoru is legitimately scary because he knows exactly how to use the kit",
    "tell them shoot the Gatecrash tether on B main or he teleports in for free",
    "tell them Yoru is worthless when his team doesn't follow up on his fakes",
    "tell them the enemy Yoru is tilted and just running straight in now, no mind games",
    "tell them Yoru is a Pacific meta king and this player clearly watched the pro VODs",
    "tell them their Yoru Blindside is going to bounce off the wall before it pops, look away now",
    "tell them Yoru drift is active, he's roaming and we don't know where he'll exit",

    # ── NEON OPINIONS ──────────────────────────────────────────────────────────
    "tell them Neon at this speed is impossible to track if you pre-aim the wrong angle",
    "tell them the enemy Neon is running High Gear every round, she's never walking in",
    "tell them Neon post nerf is still faster than any other agent, don't underestimate her",
    "tell them our Neon needs to slide first before she pushes that corner",
    "tell them Neon Overdrive beam with perfect accuracy while sprinting is broken to play against",
    "tell them the enemy Neon has been winning every duel because nobody is counter-strafing against her speed",
    "tell them Neon walls create a corridor that she runs through, don't cross into it",
    "tell them Neon relay bolt stun is about to hit B main, move or get concussed",
    "tell them their Neon is on two slides right now, she got a kill in Overdrive",
    "tell them the air-sprint nerf hurt her but she's still the best speed entry in the game",
    "tell them Neon diff, she won every single duel she took this half",

    # ── ISO OPINIONS ──────────────────────────────────────────────────────────
    "tell them the enemy Iso pulled our player into a Kill Contract, we're four-on-five until it resolves",
    "tell them Iso Contingency wall blocks bullets completely, don't shoot through it",
    "tell them if Iso hits the Undercut we're all taking double damage for four seconds",
    "tell them Iso is Reyna but he dies because he has no escape, punish the aggression",
    "tell them their Iso is playing for the 1v1 contract every round, it's working",
    "tell them Iso below fifty percent win rate is a liability in ranked, this guy proves it",
    "tell them the Iso shield is from a Double Tap orb, one more hit and it breaks",
    "tell them if our Iso wins that Kill Contract we get a five-on-five with him at full health",
    "tell them Iso Undercut suppresses abilities for four seconds, don't use anything during it",
    "tell them the enemy Iso is cracked in duels but his team utility is nothing",

    # ── WAYLAY OPINIONS ──────────────────────────────────────────────────────────
    "tell them Waylay Refract beacon is down on CT, she'll snap back to it if she loses the duel",
    "tell them shoot the Waylay beacon or she gets a free escape every single peek",
    "tell them the Hinder from Saturate isn't just a slow, it also tanks her fire rate and reload",
    "tell them their Waylay is double dashing into site aerially, watch the first dash angle",
    "tell them Waylay Convergent Paths is going to zone the entire back of site, spread out",
    "tell them our Waylay has been using Refract to bait them beautifully this half",
    "tell them Waylay is still a developing meta pick and this player is figuring it out live",
    "tell them the Waylay beacon on that box means she's already committed to the peek",
    "tell them their Waylay and our Jett are playing the same role and one of these comps is wrong",
    "tell them Waylay Lightspeed double dash into an aerial angle is almost impossible to react to",

    # ── CLOVE OPINIONS ──────────────────────────────────────────────────────────
    "tell them Clove is the best agent in the game right now and I'll die on that hill",
    "tell them don't assume Clove smokes disappear when she dies, they stay up",
    "tell them the enemy Clove ulted and she needs a kill in ten seconds or she dies again",
    "tell them Clove post-death smoke is going to keep B smoked even though she's dead",
    "tell them their Clove is a hybrid controller-duelist and she's winning both roles",
    "tell them Clove Not Dead Yet is active, she's coming back with a kill requirement",
    "tell them killing Clove twice in one round is exhausting and that's the whole point of her kit",
    "tell them Clove Pick-Me-Up after a kill gives her an overheal and a speed boost, she's hard to chase",
    "tell them the dead smoke from Clove only lasts six seconds now, wait it out",
    "tell them this Clove is playing like a duelist because she can, the kit allows it",
    "tell them Clove Meddle decays max HP to ten, one bullet finishes them",
    "tell them their Clove was the carry all game and she's been dead the whole time",
    "tell them if we can force Clove out before she activates NDY we neutralize the whole kit",
    "tell them Clove's win rate is over fifty-three percent and it's not a coincidence",

    # ── KILLJOY OPINIONS ──────────────────────────────────────────────────────────
    "tell them Killjoy Lockdown is down on B site, get out or get detained",
    "tell them Killjoy is the best sentinel in Valorant and the stats back it up",
    "tell them the enemy Killjoy turret is feeding her intel on every push we make",
    "tell them Killjoy Nanoswarm on the spike post-plant is why we keep losing the round",
    "tell them their Killjoy alarmbot tagged our guy, he's vulnerable right now, push him",
    "tell them protect the Killjoy Lockdown device or they'll destroy it in thirteen seconds",
    "tell them Killjoy solo-holds a site better than any other sentinel in the game",
    "tell them a Killjoy who hides her nanos invisibly under the site is a post-plant nightmare",
    "tell them the Killjoy turret is watching B main, it has a hundred-degree cone",
    "tell them their Killjoy recalled her alarmbot, she knows we're coming B",
    "tell them Killjoy Lockdown detains for eight seconds and that's enough to win a retake",
    "tell them the passive info Killjoy generates just by existing on a site is insane",

    # ── SOVA OPINIONS ──────────────────────────────────────────────────────────
    "tell them Sova recon bolt hit two of them on B, push now",
    "tell them information wins games and Sova is the information king",
    "tell them destroy the Sova recon dart or they know exactly where we're holding",
    "tell them Hunter's Fury goes through walls on the entire map length, everyone get out of that line",
    "tell them their Sova has been running perfect lineups all game, he knows this map cold",
    "tell them Sova owl drone is active on A, he's going to dart-tag someone",
    "tell them Sova is near-mandatory on half the maps in the current pool and they're running him correctly",
    "tell them a Sova with memorized shock dart lineups wins post-plants without line of sight",
    "tell them their Sova hunter's fury is a three-beam wall-piercing ultimate, spread horizontally",
    "tell them if the Sova recon bolt scans and we're all clustered it's over, they know our positions",
    "tell them the Sova double shock on the spike is going to nearly kill anyone defusing",
    "tell them their Sova droned the site before they pushed, they have full information on us",

    # ── VIPER OPINIONS ──────────────────────────────────────────────────────────
    "tell them Viper wall splits the entire B side of this map, we can't rotate through it",
    "tell them Viper's Pit post-plant is why nobody can defuse, she can see every enemy inside it",
    "tell them their Viper is on low fuel, the toxic screen is about to drop",
    "tell them Viper snake bite makes us Vulnerable, if she throws it we take double damage",
    "tell them Viper on this map is near-mandatory and they ran her correctly all game",
    "tell them the enemy Viper in her pit can see our outlines while we're blind inside it",
    "tell them cross the Viper wall on the toggle, not when it's active or we take decay",
    "tell them Viper's pit is the strongest post-plant ultimate in the game by a wide margin",
    "tell them their Viper toggled the wall off to save fuel, cross now before she turns it back on",
    "tell them Viper poison cloud decay doesn't kill but it softens everyone up for a push",

    # ── OMEN OPINIONS ──────────────────────────────────────────────────────────
    "tell them the enemy Omen is setting up one-way smokes and they're working perfectly",
    "tell them Omen From the Shadows is active, his shade appeared at C, destroy it",
    "tell them Omen Paranoia goes through walls and it's going to hit us even in this hallway",
    "tell them Omen one-way smoke in heaven is the reason we can't swing it",
    "tell them their Omen is a very outdated pick at high elo but he's making it work",
    "tell them Omen is stepping into his own smoke to take that off-angle, don't pre-aim standard",
    "tell them the Omen shade is at A site, kill it now or he teleports in behind us",
    "tell them Omen smokes recharge over time, he's never out of them for long",
    "tell them Omen paranoia nearsight hits all of us at once through this corridor wall",
    "tell them their Omen is faking the ultimate to bait us into rotating, don't move",

    # ── ASTRA OPINIONS ──────────────────────────────────────────────────────────
    "tell them the Astra Gravity Well is going to pull everyone in B off the spike",
    "tell them Astra Cosmic Divide is splitting the site, bullets don't go through it",
    "tell them the Astra nova pulse is going to concuss the entire entry point, push after it goes off",
    "tell them their Astra is a two hundred IQ controller and I hate playing against her",
    "tell them Astra is Immortal-plus only and this one clearly has the hours",
    "tell them Astra stars glow on the ground, find them and shoot them before she activates",
    "tell them the fake Astra nebula is a dissipate to bait our rotation, hold position",
    "tell them Astra in astral form is physically vulnerable, find her body and kill it",
    "tell them Cosmic Divide blocks audio through the wall, we can't hear anything on that side",
    "tell them Astra gravity well and nova pulse on the same push is coordinated and deadly",

    # ── BRIMSTONE OPINIONS ──────────────────────────────────────────────────────
    "tell them Brimstone stim beacon is down at plant, anyone in the circle gets a fire rate boost",
    "tell them the Brimstone orbital strike is the only thing keeping us off the spike post-plant",
    "tell them Brimstone Sky Smokes are the longest-lasting smokes in the game and they're still active",
    "tell them Brimstone is C tier this patch but he's working on Fracture specifically",
    "tell them their Brimstone is vulnerable when he opens the tablet, find him and kill him",
    "tell them Brimstone incendiary on the spike is a classic post-plant molly, wait for it to burn",
    "tell them the Brimstone stim beacon is inside the enemy's smokes, don't walk in there",
    "tell them Brimstone can only smoke within his tablet range, he can't do cross-map smokes like Omen",

    # ── HARBOR OPINIONS ──────────────────────────────────────────────────────────
    "tell them Harbor Cove is shielded with six hundred and eighty HP, it's going to take a while to break",
    "tell them the Harbor High Tide wall slows anyone who crosses it, don't walk through it",
    "tell them their Harbor is the worst controller pick in ranked and it shows",
    "tell them Harbor Reckoning wave is coming, get out of the corridor now",
    "tell them Harbor Storm Surge nearsighted and slowed our whole push in one throw",
    "tell them Harbor players get flamed every game and this one is no exception",
    "tell them the Harbor cove shield blocks bullets, plant behind it and we're fine",
    "tell them Harbor is D tier and they're running him because they main him, not because it's correct",
    "tell them Harbor Reckoning can hold in place now, it's going to sit on B site for seven seconds",

    # ── BREACH OPINIONS ──────────────────────────────────────────────────────────
    "tell them Breach Rolling Thunder is one of the best site-clearing ultimates in the game when it lands",
    "tell them Breach flashpoint through that wall is going to blind us even though we can't see him",
    "tell them Breach fault line stun is four seconds of not being able to fight back, push during it",
    "tell them ranked Breach just stuns his own team because nobody talks",
    "tell them their Breach and their Killjoy lockdown is the most coordinated thing we've faced",
    "tell them Breach is D tier in ranked but this one is communicating perfectly and it's working",
    "tell them the Breach aftershock through that wall is post-plant utility to force us off spike",
    "tell them Breach hard flash from the right side is faster and harder to react to, close your eyes now",
    "tell them their Breach knows exactly where we're holding because they have our information",
    "tell them Breach Rolling Thunder knockup plus concuss is essentially a free site take if we're clustered",

    # ── SKYE OPINIONS ──────────────────────────────────────────────────────────
    "tell them Skye is the only initiator with healing and she's keeping her whole team alive",
    "tell them the Skye trailblazer is going to leap and concuss anyone in that corner",
    "tell them their Skye seekers hit all three of us and now we're all nearsighted",
    "tell them Skye two hawks per round means she can flash a site twice before they even push",
    "tell them shoot the Skye bird before she detonates it or we're all blind",
    "tell them the Skye dog is scouting the site right now, they have full information",
    "tell them Skye healing mid-round keeps their team topped up before the execute",
    "tell them Skye A-tier this patch and nobody is talking about it, she's consistent every game",
    "tell them their Skye has been guiding the hawk perfectly around every corner all game",
    "tell them the seeker hit our guy, he's nearsighted for three seconds, push him now",
    "tell them Skye and Fade together is a double-initiator nightmare because the info never stops",

    # ── KAYO OPINIONS ──────────────────────────────────────────────────────────
    "tell them Kayo zero-point knife is on B main, don't use any abilities in that zone",
    "tell them Kayo suppressed three people and now we have to fight without any abilities for eight seconds",
    "tell them Kayo is only good when the enemy team runs ability-heavy comps, and they do",
    "tell them Kayo null-cmd is active, he's suppressing the whole area and he can be revived if he goes down",
    "tell them Kayo is down during his ult, someone has to go revive him in one and a half seconds",
    "tell them their Kayo knife hit Killjoy and now her turret and nanos are gone for eight seconds, push",
    "tell them Kayo frag grenade on the spike is a multi-tick explosion, don't defuse through it",
    "tell them Kayo pop flash is the fast cook version, less warning than the other one",
    "tell them the knife suppression removed the Skye healing and Raze satchels all at once",
    "tell them Kayo B tier this patch but he counters exactly this team composition",

    # ── FADE OPINIONS ──────────────────────────────────────────────────────────
    "tell them Fade Nightfall trailed two of them, send the prowlers now and they can't escape",
    "tell them Fade haunt eye is going to reveal us the moment it lands, shoot it",
    "tell them the Fade seize tethered our guy to that corner, he can't move for four and a half seconds",
    "tell them their Fade is running the best initiator kit for coordinated sends in the meta",
    "tell them Fade A tier this patch, the haunt plus prowler combo gives deeper info than any other initiator",
    "tell them the Fade prowler is following the terror trail, it will lock on automatically",
    "tell them Nightfall decay and deafen together means they can't hear anything and they're dying slowly",
    "tell them Fade replacing Skye in double-init comps is the meta shift this act",
    "tell them their Fade terror trails on our whole team means every prowler they throw locks onto us",
    "tell them Fade seize and Killjoy lockdown in the same round is the most overkill CC setup I've ever seen",

    # ── GEKKO OPINIONS ──────────────────────────────────────────────────────────
    "tell them Gekko Wingman is going to plant the spike by himself while we cover him",
    "tell them the Gekko Dizzy blinded me but it's plasma, not a standard flash, it also blacks the minimap",
    "tell them their Gekko is reclaiming every globule, he's getting three to four uses per ability per round",
    "tell them Gekko is the lowest pick rate in the game right now and this player shows why",
    "tell them Gekko Thrash detained two people, go in right now they can't shoot for three seconds",
    "tell them Gekko Mosh Pit explodes after a delay and covers a large area, get out of it",
    "tell them their Gekko Wingman is defusing the spike, kill the Wingman first",
    "tell them Gekko requires constant pet management and most people don't have the game sense for it",
    "tell them the Gekko dizzy flew overhead and blinded the whole site before they pushed",
    "tell them if they reclaim Wingman after it concusses they'll use it again in fifteen seconds",

    # ── TEJO OPINIONS ──────────────────────────────────────────────────────────
    "tell them Tejo stealth drone is going to suppress anyone it detonates on for eight seconds",
    "tell them the Tejo guided salvo missiles are inbound on B, get off the site or take the damage",
    "tell them Tejo Armageddon is sweeping from A long to A site in a line, move perpendicular",
    "tell them Tejo special delivery concussed the whole entry, push after the two-and-a-half seconds",
    "tell them Tejo is a fifty percent win rate agent that everyone is still figuring out",
    "tell them their Tejo fired both guided salvo missiles at the same location, that's maximum pressure",
    "tell them Tejo stealth drone suppresses and reveals at the same time, everyone scatter",
    "tell them Tejo Armageddon from the attacker spawn is going to sweep the whole A corridor",
    "tell them Tejo guided salvo doesn't need line of sight, he sent missiles around the corner",
    "tell them the Tejo drone detonated on four of them, eight seconds of no abilities, push now",

    # ── CYPHER OPINIONS ──────────────────────────────────────────────────────────
    "tell them the Cypher cam is watching B link, move along the wall to stay out of its view",
    "tell them Cypher Neural Theft on that body is about to reveal every living enemy to us",
    "tell them their Cypher has been calling every single push before it even starts thanks to that cam",
    "tell them the Cypher tripwire on B entry triggered, one of them is slowed and revealed",
    "tell them shoot the Cypher cam before we push or they'll see us and call the rotate",
    "tell them Cypher is strong on Pearl specifically because of the B-link camera placement",
    "tell them their Cypher tapped that body and now they know exactly where all five of us are",
    "tell them Cypher cam dart tagged our guy, he's revealed until he removes the dart",
    "tell them the Cypher cage is up on main, they'll hear us if we walk through it",
    "tell them Cypher dropped from S tier after the tripwire rework but he's still dangerous on the right map",

    # ── SAGE OPINIONS ──────────────────────────────────────────────────────────
    "tell them the Sage wall is blocking A ramp completely, it needs to be broken before we push",
    "tell them Sage resurrection is going to bring back their star player at full health, focus her down first",
    "tell them their Sage is a Battle Sage who is fragging instead of healing and it's costing them",
    "tell them the Sage slow orb on the entry is going to halve our movement speed and make us an easy target",
    "tell them tell them Sage is B tier but Resurrection turns rounds that should be losses into wins",
    "tell them their Sage healed their whole team through every fight this half",
    "tell them the Sage wall boost is how they're getting to that height position, watch it next round",
    "tell them break the Sage wall before it fortifies at eight hundred HP or we'll never get through",
    "tell them don't rez me if it puts Sage in a bad position, the ult isn't worth her life",
    "tell them Sage Resurrection is a seven-point ultimate and it's worth every single one",

    # ── CHAMBER OPINIONS ──────────────────────────────────────────────────────────
    "tell them Chamber is the gentleman's Jett and he's been one-tapping everything with Tour de Force",
    "tell them the Chamber headhunter is a one-shot to the head at any range when scoped, respect it",
    "tell them their Chamber Trademark trap triggered on B entry, one of them is slowed and revealed",
    "tell them shoot the Chamber Rendezvous anchor or he can't teleport out when he gets peeked",
    "tell them Chamber Tour de Force on kill creates a slow field at the body, don't rush through it",
    "tell them Chamber is the high pick rate sentinel because op plus teleport escape is basically Jett with a sniper",
    "tell them their Chamber has been holding the same op angle every round, he's a creature of habit",
    "tell them Chamber Headhunter on eco is a full eco threat, he can one-tap with the pistol",
    "tell them the Chamber TP anchor was destroyed, he can't reposition safely this round",
    "tell them Chamber Tour de Force is the second best sniper platform after Jett in this meta",

    # ── DEADLOCK OPINIONS ──────────────────────────────────────────────────────────
    "tell them the Deadlock Annihilation cocooned our guy, he's being dragged to his death unless someone breaks it",
    "tell them Deadlock GravNet is going to force everyone into crouch-walking, we'll be sitting targets",
    "tell them their Deadlock Barrier Mesh blocks our body completely, we can't push through it",
    "tell them Deadlock is A tier this patch and she's been dominating the whole back half",
    "tell them the Deadlock sonic sensor heard our footsteps and concussed the entire flank",
    "tell them break the Annihilation cocoon or our guy dies in seven seconds",
    "tell them Deadlock GravNet on the spike entry is the most oppressive post-plant setup we've run",
    "tell them their Deadlock is building coffins and walls simultaneously and I respect it",
    "tell them the Deadlock barrier mesh fortifies at twelve hundred HP in the center, stop wasting bullets on it",
    "tell them Deadlock buffs this act brought her barrier HP up significantly, she's a real anchor now",

    # ── VYSE OPINIONS ──────────────────────────────────────────────────────────
    "tell them Vyse Steel Garden jammed all our primaries, switch to pistols and abilities only",
    "tell them the Vyse Arc Rose is hidden on that surface, it's going to flash the whole angle when she pops it",
    "tell them their Vyse Razorvine is active under the site, don't rush through it",
    "tell them Vyse Shear trapped our guy behind the wall, he can't retreat and he's going to die",
    "tell them Vyse Steel Garden doesn't affect Chamber's op or Jett's blades, just primary rifles",
    "tell them Vyse is B tier win rate but S tier on defense and this round proves it",
    "tell them their Vyse Razorvine placement under the smokes is invisible and it's going to cost us",
    "tell them the Vyse pop flash is going to blind us when she activates the Arc Rose, look away",
    "tell them Vyse Shear wall is indestructible for six seconds, we can't break through it",
    "tell them Vyse is the metal alchemist of this team and she's playing it perfectly on defense",

    # ── VETO OPINIONS ──────────────────────────────────────────────────────────
    "tell them the Veto Evolution ult makes him immune to every debuff including flashes and stuns",
    "tell them the Veto Interceptor is destroying our Raze bombs and Gekko utility before they land",
    "tell them Veto Chokehold tethered our guy and he's taking decay and can't hear anything",
    "tell them don't try to flash the Veto when he's evolved, he's completely immune to all of it",
    "tell them shoot the Veto Interceptor before he activates it or we lose all our utility",
    "tell them Veto Crosscut teleport requires line of sight to the vortex, cut the sightline and he can't escape",
    "tell them their Veto is a unique pick and he's using Evolution to push through every piece of utility we have",
    "tell them Veto C tier right now but Evolution immunity to everything is legitimately unfair when played right",
    "tell them the Veto Chokehold trap is on the flank and it's going to tether anyone who tries to rotate",
    "tell them Veto interceptor destroyed the Wingman and the Boom Bot in the same round, none of our utility landed",

    # ── MIKS OPINIONS ──────────────────────────────────────────────────────────
    "tell them nobody knows what to do with Miks yet and this game is proving it",
    "tell them the Miks M-Pulse can concuss or heal and nobody communicates which mode he's set it to",
    "tell them the enemy Miks Bassquake wave is incoming, it deafens and knocks back, brace for it",
    "tell them Miks Harmonize gives him and one teammate a kill-refreshing combat stim",
    "tell them Miks is D tier right now and the community is still figuring out how to break forty-five percent win rate",
    "tell them the Miks Waveform smokes are instant unlike Brimstone's overhead deploy",
    "tell them their Miks healed their whole team with M-Pulse in healing mode between rounds",

    # ── COMP / META OPINIONS ──────────────────────────────────────────────────
    "tell them the double-initiator setup with Fade and Sova is giving them perfect information every single round",
    "tell them running two duelists without an initiator is how teams lose executes at high elo",
    "tell them their Clove Jett Killjoy Neon Sova composition is the number one win rate comp this act",
    "tell them we have no initiator and that's why every site push feels like walking blind",
    "tell them the Chamber Clove Sova spine is the core of the ranked meta and they're running it correctly",
    "tell them their team composition has three duelists and a Sage, there's no controller and it shows",
    "tell them the Clove-centric meta means the controller never fully disappears even after death",
    "tell them double-initiator comps have higher information throughput than anything else and that's why they win",
    "tell them running Astra at this elo requires coordination we do not have",
    "tell them their composition punishes selfish play and ours rewards it, that's the skill gap",
    "tell them the Viper Jett Sova Killjoy KAY/O comp is optimal for this map's long sightlines",
    "tell them three sentinels is not a composition, it's a fortified cemetery",
    "tell them their Yoru Viper Omen triple-deception comp is a Pacific meta import and it's disorienting",
    "tell them the regional meta matters and they're running Pacific pro comps in a ranked queue and winning",
    "tell them we need a controller or this team is fighting through smoke every single round",

    # ── ABILITY/MECHANIC PHILOSOPHY OPINIONS ─────────────────────────────────
    "tell them a Jett player who doesn't save their dash for escapes is playing the agent wrong",
    "tell them Clove's ability to smoke from the grave fundamentally changes how controllers are valued",
    "tell them Reyna needs kills to function and if she's not killing she's a liability with a gun",
    "tell them Yoru's entire value is in deception and a team that doesn't follow up on fakes wastes him",
    "tell them one-way smokes change the mental game more than any other mechanic in this game",
    "tell them Killjoy Nanoswarm placed invisibly pre-round is the most underrated setup in the game",
    "tell them Sage Resurrection mid-round forces the enemy to play a completely different economy next round",
    "tell them Viper's Pit is the only post-plant ability that gives the user an information advantage inside it",
    "tell them Sova's recon bolt gives the whole team a minimap outline and no other initiator does that",
    "tell them Breach is a pro-play pick that falls apart without voice communication and this lobby has neither",
    "tell them KAY/O suppression is the hardest counter to Killjoy in the game and they timed it perfectly",
    "tell them Astra stars placed before round start lock in the entire strategy for that round",
    "tell them Tejo guided salvo is the only initiator signature that deals direct damage and they're abusing it",
    "tell them Gekko reclaim mechanic gives effectively more ability charges per round than any other agent",
    "tell them Deadlock Annihilation doesn't kill the target, it detains them while dragging them to death",
    "tell them Vyse Steel Garden is the only ability that physically prevents primary weapon fire",
    "tell them Iso Kill Contract removes two people from the round simultaneously, it's a coinflip tactic",
    "tell them Veto Evolution immunity means utility teams waste every resource they have on him",

    # ── PLAYER BEHAVIOR / PERSONAL OPINIONS ON AGENTS ──────────────────────
    "tell them the Jett player who instalocks without typing in chat is always the one who drops two kills and flames",
    "tell them Reyna players in ranked are the most selfish people in the entire game",
    "tell them a player who one-tricks Astra below Diamond is actively hurting their team",
    "tell them the Yoru player spent forty hours in deathmatch and it shows in every duel",
    "tell them a good Sova player wins the information war before the first shot is even fired",
    "tell them Battle Sage who never heals and never walls is the biggest waste of a sentinel slot",
    "tell them the enemy Clove is playing with absolute confidence knowing she comes back when she dies",
    "tell them their Chamber has been taking op duels all half and he hasn't missed once",
    "tell them Skye two-flashes per round played correctly is more flash coverage than any other agent",
    "tell them their Neon is mechanically cracked and I hate every round we play against her",
    "tell them the Viper is playing like a chemical weapons engineer, methodical and absolutely merciless",
    "tell them the Fade player has read every pro VOD and it's ruining us",
    "tell them that Gekko main has three hundred hours on the agent and reclaims perfectly every time",
    "tell them the Deadlock player is treating this site like a crime scene and nobody gets out",
    "tell them the Omen playing one-way smokes is a player who studied the game seriously",
    "tell them a Breach main in ranked is either a God or a curse and this one is both simultaneously",
    "tell them our Cypher has been feeding them information all half by leaving the camera in the same spot",
    "tell them that Iso is mechanically gifted but his team gets no utility from him at all",
    "tell them whoever decided to run Harbor this game made a decision and now we're living with it",
    "tell them the enemy Killjoy set up this site before round start and we walked directly into all of it",
    "tell them their Raze has been playing reactively to our pushes and she reads us every time",
    "tell them a Clove who knows how to smoke after death is worth two controllers in a single life",
    "tell them that Veto is abusing Evolution immunity to push through every utility stack we have",
    "tell them Sova in the right hands makes the information gap between the teams a chasm",
    "tell them their Jett is the highest pick rate in the game for a reason and she's showing you now",

    # ── TACTICAL AGENT ROLE OPINIONS ─────────────────────────────────────────
    "tell them Killjoy anchors B by herself better than two players holding it manually",
    "tell them their Viper wall cuts this map in half and without a counter-wall we fight a two-on-five",
    "tell them Sova recon bolt is mandatory on the execute or we're pushing blind into held angles",
    "tell them a Clove death on attack doesn't end the smokes, that's what separates her from every other controller",
    "tell them Skye healing before the execute gives the whole team topped HP and it changes the duel math",
    "tell them Cypher cam at B link is giving them free information on every B push, destroy it",
    "tell them Fade nightfall plus prowlers is a guaranteed nearsight chain if the trails are active",
    "tell them Tejo drone suppression on the defenders before the push makes the execute free",
    "tell them Deadlock GravNet on the spike is why we can't defuse quickly, they're forcing the crouch",
    "tell them Sage Resurrection is a seven-point ultimate that saves the team's economy for the next round",
    "tell them the Chamber Tour de Force slow field on kill makes post-plant defense much easier",
    "tell them Killjoy Lockdown covers the whole site and the thirteen-second wind-up is the only window to destroy it",
    "tell them Breach Rolling Thunder knockup plus Killjoy Lockdown detain is a perfect double-CC execute",
    "tell them Viper toxic screen on B and Brimstone Sky Smoke on A gives us both sites covered simultaneously",
    "tell them Kayo knife suppression right before the Sova recon bolt means they can't shoot the dart while suppressed",
    "tell them the Fade haunt plus Sova drone together is giving them eyes on every defender simultaneously",
    "tell them Astra Gravity Well plus Fade Seize on the same location is the most overkill CC in the game",

    # ── MAP-SPECIFIC AGENT OPINIONS ──────────────────────────────────────────
    "tell them Viper is near-mandatory on Breeze because her wall cuts B in half and nothing else does",
    "tell them Breach is uniquely effective on Fracture because both site entries have walls for flashpoints",
    "tell them Sova on Ascent gives you recon bolt coverage across the whole mid and it's dominant",
    "tell them Cypher on Pearl is an elite pick because the B-link camera placement is unmatched",
    "tell them Killjoy on Haven solo-holds a site and lets the other four play for the other two sites",
    "tell them Viper wall on Split at ramps blocks the entire A entry and that's why she's good here",
    "tell them Jett on Breeze with an Operator is a different competitive category of player",
    "tell them Sova has almost no walls to bounce off on Split, the map actively punishes his recon bolt",
    "tell them Harbor is outperformed by every other controller on every map in the current pool",
    "tell them Brimstone Sky Smokes aren't wide enough for Breeze's massive open sites",
    "tell them Raze mobility on Split B mid is the best site-entry mechanic on this map",
    "tell them Omen one-way smokes in Haven heaven create angles that don't exist for any other controller",
    "tell them Killjoy on Lotus can lock down a site with nanos and lockdown while the team plays the other two",
    "tell them Chamber Tour de Force holding the Pearl mid long sightline is the reason we can't contest mid",
    "tell them Fade Haunt on Fracture reveals defenders rotating between attack spawns before they arrive",
    "tell them Clove post-death smokes on Haven protect all three sites even after she dies on the push",

    # ── COMP-SPECIFIC OBSERVATIONS ────────────────────────────────────────────
    "tell them their Clove Jett Killjoy Neon Sova is the exact number one win rate composition and they know it",
    "tell them our composition has no sentinel and the flank watch is entirely manual",
    "tell them their double-initiator with Sova and Fade is generating more information than we can process",
    "tell them we're running a duelist-heavy comp and winning on individual skill, not coordination",
    "tell them their Viper Jett Sova Killjoy KAY/O composition is the exact counter to our utility stacking",
    "tell them Chamber Clove Sova is the spine of ranked meta right now and three of their five are running it",
    "tell them their three-duelist composition has no information gathering and they're winning on pure aim",
    "tell them their Yoru Viper Omen deception comp is built to confuse and it's working perfectly",
    "tell them the four-sentinel composition is a meme and this game is proving it",
    "tell them any composition without a controller is a composition that fights through smoke on every execute",

    # ── REGISTER-VARIED OPINIONS (casual/slang-heavy) ─────────────────────────
    "yo tell them their Jett is absolutely cracked, she's been one-tapping through everything",
    "bro tell the team Reyna is feeding her kills and she can't even dismiss anymore",
    "dude let them know the Sova drone is literally giving them eyes on everyone, it's cooked",
    "tell the guys their Neon is actually a smurf, that speed is not normal",
    "yo let them know Clove ain't staying dead, she's coming back every single time",
    "tell the squad that Killjoy turret is ratting out every push we try",
    "bro Viper pit post-plant is literally unwinnable if we don't bait her out first",
    "yo tell them Yoru's been in dimensional drift for ages, he knows where all of us are",
    "tell the team that Chamber's been one-tapping with Tour de Force all half and it ain't stopping",
    "bro let them know the Fade prowler is locked on to the trail, it's going to hit",
    "tell them the Breach stun through the wall is going in, close your eyes and swing after",
    "yo their Raze is literally boosting into site with blast pack every round, it's the same play every time",
    "tell the boys Deadlock GravNet made everyone crouch-walk, push them now they're sitting ducks",
    "bro that Skye has two hawks left this round and we haven't even started the execute",
    "yo tell the team Vyse just jammed all our primaries, pistols and abilities only",
    "tell them their Omen one-way in heaven is the most toxic smoke placement I've ever played against",
    "bro let them know the Gekko Thrash detained two guys, it's a five-on-three right now",
    "yo their Iso hit the Kill Contract on our best player, we're down a man for the next ten seconds",
    "tell them KAY/O knife hit four people and their entire ability kit is disabled for eight seconds, rush them",
    "bro that Waylay beacon is going to let her escape every single peek, destroy it",

    # ── REGISTER-VARIED OPINIONS (formal/analytical) ─────────────────────────
    "please advise the team that the opposing Jett has her Tailwind charged, her escape route is viable",
    "inform the team that Viper's Pit requires us to bait her out of the cloud before we push in",
    "advise the squad that the enemy Sova's Recon Bolt has two scans and the first one already hit",
    "let them know the Clove Not Dead Yet timer is active and she requires a kill within ten seconds",
    "please inform the team that the Killjoy Lockdown device has a thirteen-second windup and can be destroyed",
    "tell them the Breach Rolling Thunder covers a twenty-five meter wide cone and everyone in it is getting knocked",
    "advise them that Deadlock Annihilation cocoon has six hundred HP and requires immediate teammate assistance",
    "inform them that the Fade Nightfall hit three enemies and all three are trailing, prowlers will lock on",
    "let the team know the Astra Cosmic Divide blocks both bullets and audio communication through the wall",
    "please advise the team that the Chamber Trademark trap at the entry point will slow and reveal the first person through",

    # ── MIXED REGISTER (mid-game realistic crosstalk) ─────────────────────────
    "yo tell them their Clove is doing what no other controller does, she's smoking after she dies",
    "tell the team their Killjoy is anchoring B solo and she's doing a better job than two people would",
    "let them know the Raze rocket is out and she launched it from B main, everyone take separate angles",
    "tell them Jett with no dash is literally just a duelist with knives, punish her now",
    "inform the guys Skye's bird is about to pop, look away from mid",
    "tell the team Harbor Cove shield is at six hundred eighty HP now, it's stronger than it looks",
    "yo let them know Yoru is using fake footsteps on A, don't rotate",
    "tell them Neon Overdrive beam has perfect accuracy while she's sprinting, that's why she wins every duel",
    "let the squad know Viper fuel is low, the wall is about to toggle off, cross it now",
    "tell them the Iso Undercut passed through that wall and suppressed the whole entry",

    # ── OWNERSHIP INVERSION OPINIONS ─────────────────────────────────────────
    "tell them our Sova has been hitting perfect lineups all half and he deserves more credit",
    "tell them our Killjoy's turret has been giving us free information on every B push",
    "tell them our Clove smoked from the grave and that's the reason we survived the round",
    "tell them our Viper wall is what gives us control of this map, without it we're fighting everywhere",
    "tell them our Fade is the only initiator generating actual deep information this game",
    "tell them our Breach Rolling Thunder is going to clear the entire site, push the moment it lands",
    "tell them their Killjoy is doing more work than their entire team combined",
    "tell them their Viper is the only thing keeping them in this game",
    "tell them their Sova has been their IGL from behind a recon bolt all half",
    "tell them their Clove is the reason every round we think we won suddenly reverses",
    "tell them our Raze Showstopper is charged and she's pushing next round with it",
    "tell them our Chamber Tour de Force is holding that angle and it's not moving",

    # ── NUANCED STRATEGIC OPINIONS ───────────────────────────────────────────
    "tell them Jett is the highest pick rate in the game and the worst-played agent below Diamond, act accordingly",
    "tell them Reyna is the best agent for climbing solo because she rewards individual skill and punishes teams",
    "tell them Yoru only works when his team has the game sense to follow his deceptions",
    "tell them Astra requires pre-round star placement which means her entire strategy is visible before it starts",
    "tell them Clove post-death smokes fundamentally alter the value equation of a controller dying",
    "tell them a Killjoy with proper nanoswarm placement wins post-plants without firing a single bullet",
    "tell them Viper on the right map isn't just a controller choice, it's a map control multiplier",
    "tell them KAY/O suppression knife on a Killjoy disables nanos, turret, alarmbot all at once for eight seconds",
    "tell them Chamber Rendezvous anchor being destroyed doubles his cooldown and removes his escape route",
    "tell them Deadlock Barrier Mesh only blocks player movement, bullets pass right through it",
    "tell them Vyse Steel Garden doesn't affect agent weapons like Jett's blades or Neon's Overdrive beam",
    "tell them the Tejo guided salvo range cap at forty-five meters means he can't fire cross-map missiles",
    "tell them Skye seekers can be shot down but three simultaneous trackers at one hundred and twenty HP each is a lot to handle",
    "tell them Sage Resurrection is a seven-point ultimate that replaces the economy cost of that player dying",
    "tell them Omen fake ultimate bait into a cancel is a mind game that only works once per map",
    "tell them Raze Boom Bot reveals the enemy position through audio when they shoot it, don't shoot it",

    # ── ADDITIONAL VARIETY (to reach 700) ────────────────────────────────────
    "tell them the enemy Jett has been awping from catwalk every round, smoke that angle before she picks again",
    "tell them Reyna in Empress with full kills refresh is unkillable until the chain breaks",
    "tell them their Yoru decoys aren't fooling anyone but the real push is already on B",
    "tell them Neon's slide resets on kills during Overdrive and she's already gotten two this round",
    "tell them Iso Contingency wall is moving forward and it's blocking both bullets and vision simultaneously",
    "tell them Waylay Saturate doesn't blur vision, it just completely wrecks fire rate and movement",
    "tell them Phoenix has been healing himself to full in his fire wall between every duel",
    "tell them Raze Blast Pack into a site is faster than any other agent mobility in the game",
    "tell them the enemy Clove Meddle fragment is going to reduce their max HP to ten, burst them immediately after",
    "tell them Omen shrouded step into the smoke is the reposition play he runs every single round",
    "tell them Harbor Reckoning forward wave nearsights and slows on hit, it's a forced push tool",
    "tell them Astra dissipate creates a fake smoke briefly before the star returns, don't rotate for it",
    "tell them Brimstone stim beacon in the execution corridor makes the whole team shoot faster",
    "tell them Cypher neural theft on that body is going to reveal where every single one of them is right now",
    "tell them Sage slow orb on the entry makes Jett's dash fifty percent shorter range when she crosses it",
    "tell them Killjoy alarmbot is waiting in that corner and the moment someone walks by it they're Vulnerable",
    "tell them the Chamber trademark trap outside the site sees anyone trying to flank before they get here",
    "tell them Deadlock sonic sensor is going to hear our footsteps on the rope and concuss the whole platform",
    "tell them Vyse Shear wall behind our entry player is going to cut off her retreat, she has to commit now",
    "tell them Veto Evolution immunity means we cannot soften him with flashes or stuns before the duel",
    "tell them our Clove is the reason we win post-plants, she keeps smokes up after she dies for the defuse block",
    "tell them this Sova has been hitting perfect zero-bounce full-charge lineups for ten rounds straight",
    "tell them Fade prowler chasing a Nightfall terror trail is an unstoppable nearsight if the trail is active",
    "tell them Gekko Wingman is concussing the entry and then being reclaimed for the next round, he gets infinite value",
    "tell them Tejo Armageddon sweep path goes right down the middle of the site, spread to the edges immediately",
    "tell them the Skye dog concussed the corner before they pushed and that's why the entry was free",
    "tell them KAY/O null-cmd pulses suppression every three seconds, anyone who pushes in loses their abilities",
    "tell them Breach fault line followed by their own smoke execute is the simplest play in the game and it's free",
    "tell them their Viper manages fuel better than any player I've watched this session, she never runs out",
    "tell them Astra gravity well plus team shooting is double damage from Vulnerable, coordinate the burst",
    "tell them Deadlock Annihilation pulls the cocooned enemy along a predetermined path we can't intercept",
    "tell them Vyse razorvine damages and slows Jett's dash when she flies through it",
    "tell them the Miks Bassquake is coming in from the side, deafens everyone it hits",
    "tell them the enemy Neon is running the same sprint-slide entry every round and we keep dying to it",
    "tell them Waylay Convergent Paths speed boost plus the hinder beam expansion makes her impossible to fight in the open",
    "tell them the Reyna player has twelve kills and five assists is zero, she's a stat padder with a really good run",
    "tell them Phoenix curveball from the right side curves left into the angle and there's almost no time to react",
    "tell them Iso Double Tap shield absorbs one full hit, shoot twice before he can regenerate it",
    "tell them the Clove Not Dead Yet kill requirement means she has to push aggression immediately after reviving",
    "tell them Omen from the shadows shade cancel is a fake ult to make us rotate unnecessarily",
    "tell them Killjoy lockdown is the best round-winning ultimate in the sentinel class, nine points is worth it",
    "tell them their Raze and their Jett together is two duelists with no information tool, it's pure aggression",
    "tell them Sova Hunter's Fury wall-piercing beams on the entire map mean nobody is safe behind cover on a straight line",
    "tell them Skye three seekers homing to three separate enemies simultaneously is an information bomb",
    "tell them Fade Seize tethers the enemy and Fade Prowler nearsights them and together they cannot fight or run",
    "tell them their Viper on this map is the whole reason their defense is holding, she's a one-person control system",
    "tell them the Tejo stealth drone is harder to hear than Sova's owl drone, don't assume you'll hear it coming",
    "tell them the Deadlock barrier mesh only blocks bodies, so our utility still goes through it",
    "tell them their Jett dash timing is Radiant-level, she's baiting shots before the window opens",
    "tell them Yoru gatecrash fake teleport audio is about to play on A to pull our rotation off B",
    "tell them the Vyse Arc Rose hidden on that wall is why that angle is suicide to swing right now",
    "tell them Sage resurrection brings the dead player back at full health which is why we focus Sage first",
    "tell them Neon relay bolt bounces once before the stun and this one is aimed at the rope platform",
    "tell them Clove pick-me-up requires her to activate manually on the kill, she's choosing to stay in the fight",
    "tell them Iso Kill Contract pulls both players out of the round, it's never the right call when you're down a man",
    "tell them their composition revolves around Clove surviving long enough to set up smokes and she keeps dying for free",

    # ── ADDITIONAL JETT / DUELIST DEPTH ──────────────────────────────────────
    "tell them their Jett is the reason this team has a winning record, everyone else is deadweight",
    "tell them Jett Blade Storm knives reload on kill, she can keep one-tapping indefinitely if she doesn't stop",
    "tell them Jett Updraft into a rooftop is an angle nobody pre-aims, it's free value",
    "tell them our Jett burned both Cloudburst smokes just to cross mid and she still got picked",
    "tell them a Jett with zero dash activations this round is either afraid or saving it for the op peek",
    "tell them their Jett has a fifty-four percent pick rate in ranked and about a fifty-one percent win rate, make of that what you will",
    "tell them Jett Cloudburst is two smokes, if she crosses with both she has no personal concealment",
    "tell them their Jett is top fragging but her team is losing because she takes every duel solo",

    # ── ADDITIONAL PHOENIX ────────────────────────────────────────────────────
    "tell them Phoenix Run it Back resets kills from the ult window, don't count those as real deaths",
    "tell them a Phoenix who times his blaze heal between fights is genuinely hard to deplete",
    "tell them their Phoenix hasn't died once this half because he heals inside every piece of cover",
    "tell them Phoenix Curveball curves around corners and the timing window to look away is less than a second",

    # ── ADDITIONAL RAZE ───────────────────────────────────────────────────────
    "tell them the Raze Showstopper rocket has a massive blast radius, nobody should be grouped right now",
    "tell them their Raze is single-handedly winning every fight by Blast-Packing before anyone else can react",
    "tell them Raze Paint Shells in a tight corridor is devastating because the sub-munitions spread unpredictably",
    "tell them the Raze Boom Bot chasing in that hallway is forcing them to reveal their position to shoot it",

    # ── ADDITIONAL REYNA ──────────────────────────────────────────────────────
    "tell them Reyna with six kills this round is going to be impossible to kill in Empress",
    "tell them the enemy Reyna has been refusing to shoot the orbs after kills and it's confusing everyone including me",
    "tell them Reyna Dismiss makes her intangible for a second and a half, don't spray into her escape",

    # ── ADDITIONAL YORU ───────────────────────────────────────────────────────
    "tell them Yoru Dimensional Drift lets him scout the entire site without anyone being able to shoot him",
    "tell them their Yoru exits his ult with a flash, the moment the animation starts look away",
    "tell them Yoru fake teleport audio is designed to trigger rotations and we keep falling for it",
    "tell them a Yoru who knows his team is watching his deceptions is an entirely different threat level",

    # ── ADDITIONAL NEON ───────────────────────────────────────────────────────
    "tell them Neon High Gear sprint makes her the fastest agent in the game and that's after the nerf",
    "tell them their Neon hasn't slid once this half, she's conserving slide charges for the execute",
    "tell them Neon Fast Lane walls damage enemies who walk through them, don't cross if they throw it at your feet",
    "tell them Neon Overdrive at full speed is a weapon she fires while running, it defies every accuracy rule",

    # ── ADDITIONAL ISO ────────────────────────────────────────────────────────
    "tell them Iso wall is indestructible and bullet-blocking, which makes him the only duelist who can solo cross open ground",
    "tell them their Iso has been building his Double Tap shield after every duel and absorbing the first trade shot",

    # ── ADDITIONAL WAYLAY ─────────────────────────────────────────────────────
    "tell them Waylay Saturate hinder debuff reduces jump height which makes it terrible to fight her in the air",
    "tell them their Waylay has been placing Refract beacon before every peek and recalling the instant she takes damage",
    "tell them Waylay Convergent Paths zones a large area and the expanding beam is the most annoying ability to dodge in the open",

    # ── ADDITIONAL CLOVE ──────────────────────────────────────────────────────
    "tell them Clove is by far the best agent in this act and every tier list in the world agrees",
    "tell them Clove Meddle plus one bullet is a kill on a full-HP enemy, the decay reduces them that much",
    "tell them their Clove used Not Dead Yet and failed to get a kill in ten seconds so she died again, now she's really dead",
    "tell them Clove Ruse smokes last fourteen seconds alive and only six when placed post-death, time it accordingly",
    "tell them Clove Pick-Me-Up overheal decays after ten seconds so she has to use the momentum immediately",

    # ── ADDITIONAL VIPER ──────────────────────────────────────────────────────
    "tell them Viper Toxic Screen toggled off to regenerate fuel means it's coming back in thirty seconds",
    "tell them inside Viper Pit the decay can't kill but it brings everyone to one HP and then any bullet finishes it",
    "tell them their Viper manages the fuel system better than anyone I've seen, she never runs both abilities dry simultaneously",
    "tell them the Viper Snakebite Vulnerable window lasts two seconds after leaving the acid zone, shoot immediately",
    "tell them Viper Pit on post-plant requires baiting her out or the entire team will die to decay trying to defuse",

    # ── ADDITIONAL OMEN ───────────────────────────────────────────────────────
    "tell them Omen Dark Cover is a sphere not a cylinder which is how he creates one-ways from elevation",
    "tell them their Omen has been cancelling From the Shadows mid-travel to fake us into rotating",
    "tell them Omen Shrouded Step cancellation is the fake-out play, don't reposition based on the audio",
    "tell them Omen smoke recharges in thirty seconds, he can smoke multiple rounds without buying new charges",

    # ── ADDITIONAL ASTRA ──────────────────────────────────────────────────────
    "tell them Astra entering Astral Form in the middle of a round leaves her body vulnerable, find it and kill her",
    "tell them Astra Cosmic Divide for twenty-one seconds is the longest wall duration of any ability in the game",
    "tell them Astra Nova Pulse has a one-second charge delay before it goes off, you have a brief window to get out",
    "tell them Astra is the highest-skill-cap controller in the game and this one has clearly hit that ceiling",

    # ── ADDITIONAL BRIMSTONE ──────────────────────────────────────────────────
    "tell them Brimstone Sky Smokes have a visual streak trail when they're incoming from the sky",
    "tell them Brimstone Incendiary deals sixty HP per second which means two seconds in the fire is lethal",
    "tell them the Brimstone stim beacon buffs both teams, the enemy walked into our stim and got the fire rate boost",

    # ── ADDITIONAL HARBOR ─────────────────────────────────────────────────────
    "tell them Harbor High Tide wall slows anyone who crosses in either direction by thirty percent",
    "tell them their Harbor Storm Surge is a new ability, the old Cascade is gone since the rework",
    "tell them Harbor Cove shield now has six hundred eighty HP after the recent buff, it actually tanks shots",

    # ── ADDITIONAL BREACH ─────────────────────────────────────────────────────
    "tell them Breach Aftershock through the wall deals one hundred sixty damage total over two ticks",
    "tell them Breach fault line is a seismic wave that travels through all terrain, walls don't stop it",
    "tell them Breach Rolling Thunder knocks enemies airborne and concusses them for six seconds, use it to clear site not kill",
    "tell them Breach right-click Flashpoint is the fast cook with one second of warning, it's the pop flash version",

    # ── ADDITIONAL SKYE ───────────────────────────────────────────────────────
    "tell them Skye Regrowth healing pool is finite per purchase, she can't heal indefinitely",
    "tell them Skye Trailblazer tiger is eighty HP and one rifle shot kills it before it reaches the corner",
    "tell them Skye Seekers also slow Jett and Neon dashes now, they added that after the patch",
    "tell them their Skye has been detonating the hawk at the perfect range to maximize blind duration",

    # ── ADDITIONAL KAYO ───────────────────────────────────────────────────────
    "tell them Kayo ZERO point suppression sphere is thirty meters in diameter, it catches everyone in a chokepoint",
    "tell them Kayo null-cmd combat stim also boosts his movement speed while the ult is active",
    "tell them Kayo down during null-cmd has thirty HP when revived, he's fragile immediately after coming back",
    "tell them Kayo FLASH drive left-click has a longer fuse for over-the-shoulder flashes, right-click is the fast pop",

    # ── ADDITIONAL FADE ───────────────────────────────────────────────────────
    "tell them Fade Seize tether zone can be destroyed by shooting it before it fully detonates",
    "tell them Fade Haunt eye has one HP, any bullet destroys it before the reveal lands",
    "tell them Fade Prowler chasing a terror trail locks on automatically and accelerates, it cannot be outrun",
    "tell them Fade Nightfall passes through walls and gives Fade an audio callout of how many enemies it hit",

    # ── ADDITIONAL GEKKO ──────────────────────────────────────────────────────
    "tell them Gekko globule reclaim window is fifteen seconds before it vanishes, he has to move immediately",
    "tell them Gekko Thrash lunge is the detain activation, steering her alone does nothing to the enemy",
    "tell them Gekko Mosh Pit is the only Gekko ability that cannot be reclaimed, it's a one-way commitment",
    "tell them their Gekko Wingman planted the spike in a completely safe location while we were all focused on him",

    # ── ADDITIONAL TEJO ───────────────────────────────────────────────────────
    "tell them Tejo Special Delivery alt-fire is a single-bounce concuss grenade that comes from an unexpected angle",
    "tell them Tejo stealth drone is quieter than Sova owl drone and sixty percent of people don't hear it coming",
    "tell them Tejo guided salvo fires up to two missiles at two different locations simultaneously",
    "tell them Tejo Armageddon can target any straight path on the map within range and sweep it with explosions",

    # ── ADDITIONAL CYPHER ─────────────────────────────────────────────────────
    "tell them Cypher Trapwire can be picked up and redeployed, he moves it when the round starts going wrong",
    "tell them Cypher Spycam dart reveals the tagged enemy indefinitely until they remove it from themselves",
    "tell them the Cypher cam respawn cooldown is forty-five seconds, we have a window to push while it's down",
    "tell them Cypher Cyber Cage makes an audio alert when enemies walk through it, even if he's not watching",

    # ── ADDITIONAL SAGE ───────────────────────────────────────────────────────
    "tell them Sage Barrier Orb starts at four hundred HP per segment and fortifies to eight hundred after three seconds",
    "tell them Sage Slow Orb also reduces Jett and Neon dash speed by fifty percent",
    "tell them Sage Healing Orb cooldown starts after the heal finishes, not when she activates it",
    "tell them their Sage has been boosting players on the wall to reach positions that don't have a natural route",

    # ── ADDITIONAL KILLJOY ────────────────────────────────────────────────────
    "tell them Killjoy Nanoswarm goes invisible on landing and she activates it remotely when we're on the spike",
    "tell them Killjoy Alarmbot recall has a twenty-second pickup cooldown before she can redeploy it",
    "tell them Killjoy turret watches a hundred-degree cone and it's placed to watch the main entry point",
    "tell them Killjoy Lockdown detains for eight seconds, if they get in before we destroy it everyone is frozen",

    # ── ADDITIONAL CHAMBER ────────────────────────────────────────────────────
    "tell them Chamber Headhunter ADS is a one-tap at any range and he's buying four bullets to cover this round",
    "tell them Chamber Trademark slow field activates on any enemy in range, including through the entry smoke",
    "tell them Chamber Tour de Force slow field on kill means every body he drops creates a new slow zone",
    "tell them Chamber Rendezvous requires him to be on the ground and in range of the anchor, get between him and it",

    # ── ADDITIONAL DEADLOCK ───────────────────────────────────────────────────
    "tell them Deadlock Sonic Sensor detects significant noise like gunfire, not just footsteps",
    "tell them Deadlock GravNet forces enemies to crouch and moves at thirty percent speed, they're sitting targets for seven seconds",
    "tell them Deadlock Barrier Mesh only blocks player movement, bullets and utility pass right through",
    "tell them Deadlock Annihilation cocooned enemy needs six hundred HP of damage from teammates to be freed",

    # ── ADDITIONAL VYSE ───────────────────────────────────────────────────────
    "tell them Vyse Shear wall is indestructible and the enemy behind it has no choice but to push forward",
    "tell them Vyse Razorvine activates when she presses the ability key remotely, it's not automatic",
    "tell them Vyse Steel Garden has a brief windup before the jam effect lands, there's a window to start the push",
    "tell them Vyse is niche but on defense she has a fifty-two versus forty-eight percent win rate split",

    # ── ADDITIONAL VETO ───────────────────────────────────────────────────────
    "tell them Veto Crosscut requires facing the vortex to teleport, just block the sightline and he's stuck",
    "tell them Veto Chokehold deploys on landing and tethers anyone who walks into the zone afterward",
    "tell them Veto Interceptor destroys utility projectiles but only has twenty HP and one rifle shot takes it out",
    "tell them Veto Evolution until death means he doesn't have a timer, we have to kill him to end it",

    # ── CROSS-AGENT SYSTEM OPINIONS ───────────────────────────────────────────
    "tell them the information gap between the two teams this game is entirely because of their Sova and Fade pairing",
    "tell them a sentinel who gets destroyed in the buy phase setup wastes the whole team's strategy",
    "tell them the meta punishes teams without a controller because you fight through smoke on every single push",
    "tell them ability suppression from KAY/O knife on a Killjoy-anchored site is a complete shutdown combo",
    "tell them two initiators running simultaneously doubles the information coverage and that's the entire reason it's meta",
    "tell them Clove and Sage together on the same team is overkill on healing but the Rez plus NDY combo is unstoppable",
    "tell them the Breach and Killjoy Lockdown sequence is the most scripted team play in the ranked meta",
    "tell them any duelist without a flash or a smoke has to rely on teammates and ranked teammates never deliver",
    "tell them a controller who manages their utility cooldowns correctly never truly runs out of resources",
    "tell them Sova recon bolt plus Fade Nightfall terror trail plus prowlers is a three-layer information destroy",

    # ── PHRASING VARIETY BURST (short, declarative) ──────────────────────────
    "tell them Jett no dash, she's exposed",
    "tell them Reyna empress just ended, she needs a kill to restart it",
    "tell them Clove is back, she needed that kill for the ult",
    "tell them Sova recon hits two, push them",
    "tell them Killjoy lockdown going down on B, protect it or destroy it",
    "tell them Viper low fuel, wall drops soon",
    "tell them Kayo knife hit everyone, abilities are down for eight seconds, go",
    "tell them Breach ult incoming, spread wide or get knocked",
    "tell them Deadlock cocooned our guy, break him out",
    "tell them Vyse jammed the whole team, pistols only",
    "tell them Waylay recalled, she's back at the beacon",
    "tell them Iso Kill Contract is over, he won",
    "tell them Phoenix coming back in his ult, burn him before the timer",
    "tell them Neon Overdrive active, don't chase her",
    "tell them Yoru is drifting, he's invisible right now",
    "tell them Sage rez incoming, they're getting their guy back",
    "tell them Chamber pulled the trigger on Tour de Force, he has five shots",
    "tell them Skye seekers tracking all three of us right now",
    "tell them Omen shade on site, kill it before he arrives",
    "tell them Astra gravity well on spike, don't defuse until it's done",

    # ── LONG / ANALYTICAL OPINIONS ───────────────────────────────────────────
    "tell them the reason their execute works every round is Fade Haunt plus Sova Recon Bolt giving them advance knowledge of exactly where each of us is holding",
    "tell them Killjoy anchoring B with turret intel, alarmbot on the flank, and nanoswarm on the spike means three players are effectively controlling one site",
    "tell them Clove's value proposition is simple: the controller utility doesn't disappear when the controller dies, and that changes every economic calculation for the round",
    "tell them Viper on this specific map is not a preference, it is the mathematically correct agent choice because no other controller splits a map this size",
    "tell them the reason the Breach and Killjoy combo is devastating is that Rolling Thunder knockup into Lockdown detain creates eight seconds of total inability to respond",
    "tell them Yoru's Dimensional Drift is not an ultimate for killing, it's an ultimate for intelligence gathering, and this player is using it as intended",
    "tell them the Chamber Tour de Force slow field on every kill means the enemy is effectively leaving permanent slow traps at every body they drop in post-plant",
    "tell them Sage Barrier Orb as a boost wall for the Raze Blast Pack is a one-time height advantage that no defender pre-aims because nobody expects the combo",

    # ── FINAL TOP-UP ─────────────────────────────────────────────────────────
    "tell them Miks Harmonize kill-refresh combat stim means both him and his target get faster reload and fire rate for every kill they chain",
    "tell them the enemy Iso has a twelve-kill game and every single kill is in a one-on-one, he's a duel machine",
    "tell them Waylay Lightspeed double dash commits both dashes in sequence, she can't abort mid-motion",
    "tell them Phoenix is self-sufficient in the way that makes him useless to his team simultaneously",
    "tell them their Reyna hit eleven kills and zero utility this half and somehow that's considered a strong performance",
    "tell them the reason Neon wins every gunfight at close range is that nobody has crosshair placement for how low and fast she moves",
    "tell them Veto is a C-tier sentinel right now but Evolution immunity is genuinely the most oppressive ult in the sentinel class",
    "tell them Gekko is the only agent who can defuse the spike without a human player walking into the kill zone",
    "tell them Tejo is still being discovered and his guided salvo around corners without line of sight is the ability nobody is accounting for",
    "tell them Fade Seize tether plus Killjoy Alarmbot Vulnerable plus one bullet is a guaranteed one-shot kill sequence on any HP value",
    "tell them Harbor Cove shielded smoke at the plant point is the safest plant in the entire game because bullets don't reach the planter",
    "tell them Brimstone Orbital Strike requires open sky above the target location, he can't laser anyone inside a building",
    "tell them their Astra had all five stars placed before round one started and she's been playing off that setup for three rounds",
    "tell them the Cypher cam destroyed means we have a forty-five second window before it respawns, push during it",
    "tell them Deadlock Annihilation is the one ultimate that doesn't kill immediately but guarantees death unless teammates intervene",
    "tell them Vyse Arc Rose is redeployable after pickup, she's moving it to the angle we just discovered",
    "tell them Clove and Killjoy in the same composition means the site never truly clears even when both players are dead",
    "tell them Sova on this map has been running the same recon bolt lineup for ten rounds and we still haven't learned to shoot the dart",
    "tell them the enemy team's Jett and Neon together is two fast-entry duelists with no information tool and somehow they keep winning on raw mechanics",
]
