ITEMS = [
    # ---- ASCENT ----
    "tell them mid on Ascent is the whole map, whoever wins it wins the round",
    "tell the team we should fight for Catwalk early and hold it all half",
    "tell them to close the B door at round start every time",
    "let my team know the Generator plant on A is the safest default we have",
    "tell them A Main is a death trap without smokes on Heaven and Hell",
    "tell them the Sova recon into mid courtyard is mandatory every single round",
    "let them know Wine is where defenders hide on A Main, check it first",
    "tell the team Tree is the flank route, someone needs to watch it post-plant",
    "tell them the Market stairs give attackers a height angle into B site",
    "inform the team that a Jett Op on B Main controls the entire B lane",
    "tell them we should default and look for mid picks before committing",
    "let them know the Tiles panels can be broken to open new mid angles",
    "tell them B triple box is the safest plant spot we have on B",
    "let my team know that the Workshop is a must-clear before planting B",
    "tell them Killjoy turret in mid watches both Catwalk and Market at once",
    "tell the team Logs on B is always contested, clear it before stepping on site",
    "tell them if we lose A Heaven we basically lose A site for free",
    "let the team know we should play the A door mechanic to delay a push",
    "tell them Hell under Heaven on A is the hardest post-plant spot to clear",
    "let them know Catwalk split off mid while hitting A Main is our best A execute",
    "tell the team we keep getting traded through the B Main Op angle, play Subroza spot",
    "tell them an Omen TP to Tree puts a player behind the defender holding A",
    "tell the team Garden is how defenders rotate A-to-CT, watch it post-plant",
    "let them know Sova dart through the Market room reveals every B stack",
    "tell my team if mid is uncontested we should take it for free every round",
    "tell them the Ascent doors are 500 HP, break the B door and pressure through Market",
    "let the team know the Dice boxes on A are the best plant-for-Main position",
    "tell them A Main is the widest lane on the map, it rewards rifles not SMGs",
    "let the team know a Clove double-controller with Omen owns this map in 2026",
    "tell them the Mid Cubby near Catwalk is free cover on the approach, use it",

    # ---- HAVEN ----
    "tell them on Haven whoever controls Garage owns the whole C and B simultaneously",
    "tell the team mid on Haven is called Garage, we need to win it early or we lose map control",
    "let them know A Heaven on Haven is mandatory to hold or we get picked off through Long",
    "tell the team B site on Haven is the cleanest execute if we smoke A Link and C Link",
    "let them know C Long is Operator territory, we need a flash opener to push it safely",
    "tell them the Garage Nest position above Garage is where defenders perch, smoke it",
    "let the team know Hell under A Tower is the single hardest post-plant spot on Haven",
    "tell them A Short Sewer is a fast flank onto A that defenders never respect",
    "let them know the Double Doors in mid make a loud sound when broken, listen for it",
    "tell the team that C Platform is the highest angle on C site, clear it before planting",
    "let my team know that we should fake A Long and actually hit B or C through Garage",
    "tell them playing three on B is usually waste, it's the smallest site on Haven",
    "let them know A Heaven plus a Heaven Stairs player locks down all of A site",
    "tell the team the Gong back-wall on B is the hardest hiding spot to clear",
    "let them know C Logs give an angle that catches people rotating from C Link",
    "tell them if we take Garage control early we can pivot to B or C on information",
    "let the team know that on Haven defenders always have one player short somewhere",
    "tell them the C Long corner cubby is where defenders hide to catch the first entrant",
    "let my team know that A Tree is the connector between A and mid, watch for lurks",
    "tell them A Link connects A to mid, that's the rotation route on defense",
    "let the team know that Nest above Garage is a defender perch, pop flash it on entry",
    "tell them the mid window angles into B site and C approach simultaneously",
    "let them know rotating from A Heaven to C through CT is the longest rotation on the map",
    "tell the team that a Breach stun through C Long walls is the opener for a safe C push",
    "let my team know that stacking four on A Long and one on B is a viable stratagem here",

    # ---- SPLIT ----
    "tell the team that on Split mid control is A Tower access and B Link access combined",
    "tell them A Heaven on Split must die before we step onto A site or we get hit from above",
    "let them know the ropes on Split are slow and loud, you're vulnerable when ascending",
    "tell the team that B Tower controls the entire B site, we need it smoked before crossing Garage",
    "let them know the Mail room in mid is a common early defender hold for information",
    "tell them the mid Vent rope takes you up to A Tower, that's the mid-to-A flank",
    "tell the team B Hell rope goes up to B Tower and is the fastest defender way to B Heaven",
    "let my team know that Screens on A site gives angles into A Main and Ramps at once",
    "tell them a KAY/O knife in mid Vent suppresses defenders in A Tower and Screens simultaneously",
    "let them know the B Alley corridor is the defender rotation path to B site from CT",
    "tell the team the B site default plant behind the Double Box is the safest B plant",
    "let them know the A site Terminal holo box is the A default, plant behind it",
    "tell them split execution on A, Ramps plus A Main simultaneously, is how we break the defense",
    "let the team know Rafters above A site give sightlines on A Main entry and back site",
    "tell them mid bottom connected to Vents is the attacker path to A Tower from mid",
    "let my team know that Viper Toxic Screen along A Main blocks Heaven and Rafters entirely",
    "tell the team the B Rafters position gives angles on Garage entry and the whole B site",
    "let them know Ninja spots on A site can catch defenders rotating out of Screens",
    "tell them the Market area near B Link connects B approach to mid, watch for flanks",
    "let them know a Sage wall at B Garage denies the entire B push for a full round",
    "tell the team that KAY/O is statistically the highest win-rate agent on Split, run him",
    "let them know Raze satchels over A Ramps is one of the fastest site entries on the map",
    "tell them holding Top Mid as defenders prevents the Vent rope flank to A Tower",
    "tell the team we should slow-push B with a Gekko Wingman plant while we fight Garage",
    "let my team know the Orange room in mid corridor is a hidden lurk spot most people ignore",

    # ---- BIND ----
    "tell them on Bind the teleporter sound is global, always call when you hear it",
    "let them know A Bath is the hardest entry room on the map, dump utility before pushing",
    "tell the team B Hookah window is how B gets forced, smoke it before stepping on site",
    "let them know the A Short TP sends players into Hookah, and the B Long TP sends them to A Lobby",
    "tell them U-Hall Lamps area controls both A Short and the A TP entrance at once",
    "let the team know B Elbow between B site and B Hall is the hardest defender lurk to clear",
    "tell them Heaven on A site is a free information angle on both Bath and A Short exits",
    "let them know the Shiny radianite crates at B site can be wallbanged through",
    "tell the team that B Long into B Garden gives the B Short Hookah approach from the side",
    "let them know there is no traditional mid on Bind, the teleporters are the mid equivalent",
    "tell them a Sage wall in the Hookah window cuts off one entire B site entry",
    "let the team know Triple Box on A is where the spike goes and Heaven hold wins post-plant",
    "tell them the Tank vehicle on A site is secondary cover for post-plant holding toward Bath",
    "let them know a fake TP does NOT trigger the global audio, only completing the TP does",
    "tell the team Vyse has the highest win rate on Bind, Arc Rose in Hookah is devastating",
    "let them know Cypher tripwires on TP exits give free information on cross-map rotations",
    "tell them B Container at center site is the default plant and cover for post-plant on B",
    "let my team know Raze Showstopper through Hookah window clears every corner in one shot",
    "tell the team that Bath Cubby near A Showers is where defenders hide to catch entrants",
    "let them know B Fountain orb is open pickup on early rounds if nobody contests B Long",
    "tell them the Elbow corner at B site covers both Hookah window angle and back site simultaneously",
    "let the team know a Sova recon through B Garden reveals everyone staging in Hookah",
    "tell them B Hall corridor is the defender rotation path to B, it comes in from behind",
    "let my team know there is zero excuse to get caught by a TP sound and not rotate",
    "tell the team the Ninja spot on A site is a deep ambush that catches first-wave entrants",

    # ---- LOTUS ----
    "tell them on Lotus the rotating doors are the most important audio cue on the map, always call it",
    "let the team know the A Door rotation is loud and shows on the minimap, call it the second you hear it",
    "tell them the destructible B Wall in A Link is a one-time permanent commitment, call it when it breaks",
    "let my team know that B site on Lotus is the smallest and cleanest execute with B Pillars smoked",
    "tell them C Mound control on Lotus is like Garage on Haven, winning it controls C and B pressure",
    "let them know the silent drop from A Heaven can flank to the Waterfall area without footstep noise",
    "tell the team A Root and A Rubble are the two A approach lanes and we should split them",
    "let them know C Bend is the hardest corner to clear on C site, it catches every entrant",
    "tell them C Gravel produces loud footstep sounds that reveal enemy position before contact",
    "let the team know C Door rotating puts the door into utility placed there, destroying it instantly",
    "tell them A Hut in the center of A site splits sightlines and is the main plant reference",
    "let them know B Upper is the defender high ground on B site, it must be cleared before entry",
    "tell them A Top Heaven on Lotus is a rope ascender up from site, it overlooks everything",
    "let my team know that Deadlock Annihilation through B Pillars corridor clears the entire entry",
    "tell the team C Hall and C Link are the CT rotation paths to C site from defender spawn",
    "let them know Harbor wall along A Main cuts the entry into manageable chunks",
    "tell them a Fade Haunt into C Bend reveals anyone hiding there before we step on site",
    "let the team know that Lotus has three ult orbs, mid orb near B Upper is worth contesting",
    "tell them rotating both doors in the same round is a loud signal but can fake split pressure",
    "let them know Omen TP suits Lotus perfectly because the map rotation distances are enormous",
    "tell the team the A Cubby near A Stairs is called Squeaky by some players due to the audio",
    "let my team know we should play a B execute with the wall broken to create a third angle into B",
    "tell them the C Waterfall ambient sound can mask footsteps near the CT spawn side",
    "let the team know Killjoy Lockdown on B site post-plant basically wins the round",
    "tell them on Lotus three sites means there is always one defender short somewhere, exploit it",

    # ---- BREEZE ----
    "tell the team that Breeze rework in 2026 narrowed mid into corridors, it is no longer pure Operator",
    "let them know Mid Nest on Breeze now requires a mobility ability to reach, Jett or Omen only",
    "tell them the A Pyramids on Breeze are the primary plant cover and they are taller post-rework",
    "let my team know A Hall connects mid to A site and is the fastest mid-to-A rotation path",
    "tell the team B Cubby on Breeze was significantly expanded in the rework, check the new corners",
    "let them know the Metal Doors on A Hall are the mechanical choke, defenders close them to buy time",
    "tell them the Snake B side route was removed in the Breeze rework, only one non-mid B path remains",
    "let the team know Mid Pillar is now connected to a larger wall post-rework, not isolated",
    "tell them the A Shop off A Lobby has the first ult orb and is accessible through Cave safely",
    "let them know B Main has the second ult orb, smoke the Nest angle before picking it up",
    "tell the team the B Wall on B site was extended toward B Main to prevent multi-angle coverage",
    "let my team know that Viper wall is essentially mandatory on Breeze for every long corridor",
    "tell them Jett can still dash-peek into B Main with an Operator, that is the defining Jett play here",
    "let the team know Deadlock and Vyse are statistically the top agents on current reworked Breeze",
    "tell them B Elbow now has utility windows from the rework, walls are no longer climbable",
    "let them know Chamber Operator on A Main or B Main still dominates the long entry lanes",
    "tell the team the Right Pyramid plant on A site forces defenders to push through the site to defuse",
    "let them know B Back plant deep in site forces a very long retake with extreme time pressure",
    "tell them the Mid Wood Doors connecting Mid Top to A site corridor are a key chokepoint",
    "let the team know Mid Cannon area on B side is where mid connects to B Elbow and B Tunnel",
    "tell them Sova recon darts through the large open areas on Breeze are still extremely valuable",
    "let my team know the B Pillar in B site lets defenders pivot between watching B Main and B Tunnel",
    "tell the team the A Bridge is the defender rotation path above Hall from the CT spawn side",
    "let them know a Fade Haunt into the Mid Nest area reveals anyone hiding there from below",
    "tell the team that playing through B Tunnel from B Elbow adds a second angle into B site",

    # ---- PEARL ----
    "tell them on Pearl there are zero mechanics, no ropes no doors no teleporters, timing is everything",
    "let the team know Mid Doors on Pearl is the single most important fight every round",
    "tell them Mid Plaza control opens A Art flank or B Link, losing mid means single-entry only",
    "let my team know B Main on Pearl is one of the longest committed corridors in the game, use utility",
    "tell them Viper wall across B Main is the most impactful single ability on the entire map",
    "let the team know B Tower on Pearl overlooks the B Main entry and requires a smoke to push safely",
    "tell them a KAY/O Fragment through the B Hall wall is the standard B execute opener",
    "let them know B Ramp was reduced in size post-patch, the old flat attacker cubby is gone",
    "tell the team the A Restaurant corridor approach has defender pockets that can be wallbanged",
    "let them know A Dugout on A site is a mandatory clear before planting, defenders hide there",
    "tell them the Defender Water room is how defenders rotate A-to-B, it comes out in mid connector",
    "let the team know Defender Records leads directly to B Tower and B Tunnel from spawn",
    "tell them A Art connects mid to A Link and creates a two-angle execute when used with A Main push",
    "let my team know A Secret and A Flowers are the CT-side positions for A site defenders",
    "tell them the B Screen was widened post-patch with impenetrable blocks behind it",
    "let the team know B Hall is the second entry into B site and also the defender rotation path",
    "tell them Sova recon into A Main from A Restaurant reveals every pocket before entry",
    "let them know Killjoy Nanoswarm on B Ramp forces defenders off the ramp during a B execute",
    "tell the team a Deadlock Barrier Mesh on A Link corridor is statistically the top win-rate play",
    "let them know the B Tunnel under B Tower connects Defender Records to the site from behind",
    "tell them Breach Rolling Thunder through Pearl's walls is extremely effective for site clears",
    "let my team know that Pearl is slight defender-sided at around 52 to 53 CT win rate",
    "tell the team the mid orb in Plaza is heavily contested because mid control is already the key fight",
    "let them know Clove global smokes are especially strong here because the map is so spread out",
    "tell them B Hall attack post-plant crossfire from B Link and Ramp catches every retake attempt",

    # ---- FRACTURE ----
    "tell them on Fracture we can fake A and zip to hit B before defenders rotate",
    "let the team know B Tower is the single most contested position on Fracture, whoever holds it wins B",
    "tell them the ziplines are attacker-only and one-way, defenders cannot use them",
    "let my team know A Rope connects A Door in A Hall to A Link toward Defender Spawn",
    "tell the team that A Sand is the foothold you take through A Door before committing to site",
    "let them know B Canteen is where rotating defenders hide to hold B Long angles",
    "tell them B Generator near B Canteen gives retake angles into B Link and the site",
    "let the team know Fracture has four ult orbs across the map, Sova and KAY/O love this map",
    "tell them A Dish is the flanking route with the second A ult orb and access to A Gate",
    "let them know the attacker spawns are split, one on each wing, coordinate before ziping across",
    "tell them Top Site is the elevated A Heaven position that overwatches all of A site",
    "let my team know a smoke on A Link and B Link simultaneously is the rotation-cut execute",
    "tell the team B Arcade has three sub-lanes, Underpass left, center straight, right up to B Tower",
    "let them know Cypher trapwires on A Link and B Link give passive rotation information all half",
    "tell them we should double-zip fake to make defenders uncertain which site we actually hit",
    "let the team know B Bench is the defender lurk on B site watching all three Arcade entries",
    "tell them the A Drop onto A site comes from the top after using the zipline from B spawn",
    "let my team know A Heaven controls A Main, A Drop, A Link, and most of the site from above",
    "tell the team playing A Hell on bottom site covers the plant from the hardest angle to clear",
    "let them know Raze Blast Pack onto A Drop is one of the fastest A site entries in the game",
    "tell them Brimstone smokes cover A Link, A Door, B Canteen, and B Generator for key executes",
    "let the team know Fracture's dual-spawn means every round the enemy does not know which side gets zipped",
    "tell them B Tunnel Underpass lets us split B with some going B Main and some going through Tunnel",
    "let my team know the Defender Spawn in the center of Fracture is the fastest rotation point on any map",
    "tell the team that Jett Op on B Tower and a stun through Arcade is the standard B hold setup",

    # ---- SPLIT ----
    "tell the team on Split that the B Ninja spot catches every attacker stepping onto B site",
    "let them know the B site Pillar near back provides a crossfire hold against Garage entry",
    "tell them A site Flowerpot is a tight hiding spot that catches people coming through Screens",
    "let the team know the Mid Vent rope gives attackers a free flank to A Heaven from mid bottom",
    "tell them on Split if we control Bottom Mid and Vents we can open A Heaven from behind",

    # ---- ABYSS ----
    "tell them on Abyss there are no outer walls, falling off any edge is instant death",
    "let the team know the A Bridge on Abyss is a narrow walkway over a death drop, do not get knocked off",
    "tell them the A Vent doors are 120 HP and color-coded, shoot them blue to yellow to red",
    "let them know Mid Library connects mid to B Link and is the central staging area for B rotations",
    "tell the team Mid Catwalk elevated lane leads to A Vent, that is the mid-to-A Tower path",
    "let my team know Mid Bottom and Mid Catwalk are separated by a void death drop in the middle",
    "tell them A Secret is a defender-side outer ledge behind A site only accessible from spawn side",
    "tell the team B Danger is the outer ledge behind B site, jumping across is risky but faster",
    "let them know A Tower on Abyss is accessible via rope ascender from A site floor, contest it",
    "tell them the breakable vent doors connect Mid Catwalk to A Tower and give a mid-to-heaven flank",
    "let the team know B Nest near B site is a concealed post-plant position most people ignore",
    "tell them B Link connects B site to Mid Library, covering it prevents the mid-to-B flank",
    "let my team know Abyss is not currently in the competitive map pool so our rotations may be rusty",
    "tell the team A Security is the defender cut into A Main that allows early peeking",
    "tell them A Cobby is the community name for A Lobby on Abyss per Liquipedia callouts",

    # ---- CORRODE ----
    "tell them on Corrode the flooded walkways make noise when you run through them, walk slowly",
    "let the team know Mid Stairs is the elevation change that controls access to both sites from mid",
    "tell them A Crane on Corrode is the defender-side elevated entry to A site, smoke it for a safe push",
    "let my team know A Elbow is the second A site entry angle and losing it gives attackers a crossfire",
    "tell the team A Link on Corrode is a contested power position connecting mid and A Yard",
    "let them know A Pocket has tight corners requiring clearing before committing to A site from A Main",
    "tell them B Arch on Corrode is the primary defender entry to B site, a strong anchor hold",
    "let the team know B Tower near B site is the elevated rotation route for defenders watching B Main",
    "tell them B Link on Corrode is the most contested position on the B lane, it controls site tempo",
    "let my team know B site on Corrode is the smaller site and is heavily defender-favored",
    "tell the team that Mid Window in mid provides a cross-map sightline between Top and B approach",
    "tell them the water sections are distributed through lower corridors and transitional areas",
    "let them know Vyse is rated the top sentinel for Corrode according to current meta data",
    "tell the team Corrode has no teleporters, no ropes, no breakable elements, pure static map",
    "tell them Sova recon dart and Fade Haunt are especially powerful here because the walls are thin",

    # ---- LOTUS (additional) ----
    "tell them the A Door on Lotus takes ten seconds to fully rotate, you can shoot through the gap during rotation",
    "let the team know B Stairs on Lotus is the sunken pit in the center of B site, use it for low-angle duels",
    "tell them the C Door rotating destroys any utility placed in its sweep path, do not smoke the door gap",
    "let my team know A Top rope ascender from A site gives the defender elevation over the entire A plant zone",

    # ---- ICEBOX ----
    "tell them on Icebox Kitchen between mid and B site is the single most important room on the map",
    "let the team know losing Kitchen means losing B site rotation timing, it is that critical",
    "tell them A Nest on Icebox is an elevated room above A site and we can plant the spike inside it",
    "let my team know the horizontal Belt zipline on A site runs the length of the A lane at elevation",
    "tell the team B Snowman on B site gives a long angle that catches anyone crossing from Green to Yellow",
    "tell them A Belt at elevation controls Nest access and Pipes simultaneously on A site",
    "let them know the Boiler elevated position in mid gives defenders free vision across the entire mid zone",
    "tell the team B Cubby on Icebox is extremely forward and gives no escape, only use it aggressively",
    "let them know the 410 crate in front of A site is a community slang name for the numbered container",
    "tell them Viper wall is essentially mandatory on Icebox for blocking B Main or A Main sightlines",
    "let my team know Icebox is not in the current competitive map pool, it has been out since Patch 11.04",
    "tell the team that Icebox is attacker-sided historically, which is unusual in this game",
    "let them know two vertical ziplines ascend to A Nest and are audible when used",
    "tell them B Green and B Yellow are the two sub-lanes of B Main, split them on the push",
    "let the team know Under Tube is the lower faster path through mid but has the most angles to clear",

    # ---- OPINION / META / CROSS-MAP ----
    "tell the team we should default every round on this map and gather info before committing",
    "let them know our controller needs to be placing smokes before we step up, not after",
    "tell them we keep losing because we all push the same angle, we need to split every execute",
    "let my team know that whoever controls Heaven on this map controls the entire site, prioritize it",
    "tell the team we are giving up mid for free every round and it is costing us the game",
    "let them know we should be slower on this map, burn their utility before we commit",
    "tell them the lurker role on this map should go through mid and flank CT after the execute starts",
    "let the team know our IGL needs to call commits instead of letting us default every round",
    "tell them we need a Sova this map, recon darts are the best way to get information without dying",
    "let my team know the entry fragger needs flashes before stepping into the main, not dry peeks",
    "tell them if we keep stacking one site we are making it easier for them to defend, spread out",
    "let the team know post-plant we should be in two separate angles watching the defuse, not clumped",
    "tell them we have been rotating too early every round and getting caught off site",
    "let them know we need someone to actually anchor and give information instead of everyone rotating",
    "tell the team a fake execute into one site followed by a zip or TP to the other is our best play",
    "let my team know the attacker side on this map is rated around 48 percent win rate, defend patiently",
    "tell them this map heavily punishes uncoordinated pushes, we need to execute with utility",
    "let the team know we should be playing for picks mid before committing to a site every round",
    "tell them the sentinel utility needs to go on the rotation path, not on the site itself",
    "let my team know we should run a slow-push this round and make them burn all their smokes",
    "tell the team we need to run two controllers on this map, single smoke coverage is not enough",
    "let them know the agent composition we have is weak for this map, our controllers cannot reach the key chokes",
    "tell them after we plant we should be in crossfire positions, not lined up behind the same box",
    "let the team know we are relying too heavily on individual plays, structured executes beat raw aim on this map",
    "tell them we have been playing too passive as defenders, we should push into the map earlier",

    # ---- ECONOMY + MAP CONTEXT ----
    "tell the team on an eco round on this map we should rush B and force a fight before they set up",
    "let them know if they are eco we should not be fighting them in the open, play behind cover",
    "tell them a force buy on this map means we need to rush fast before they can smoke and set",
    "let my team know we should save this round and full buy next, we have the credits to reset properly",
    "tell the team a half buy works here only if we rush one lane without exposing to the long angle",
    "let them know if they have Operators on eco this map punishes running in the open severely",
    "tell the team we should stall the clock and make them push into us on defense this round",
    "let them know we should not force a fight for the orb this round, get the credits instead",

    # ---- STREAMER IDIOMS / VARIED REGISTER ----
    "yo tell them we have been inting into that angle for five rounds, play the other side for once",
    "tell my team bro they are stacking Heaven every round, we need to counter that",
    "let them know real quick that mid is literally open every round and no one is contesting it",
    "hey tell the team that B site is actually doable this round if we just smoke Tower first",
    "tell them to use the teleport timing on this map to their advantage for crying out loud",
    "let them know honestly the way we have been playing A Main is just handing them kills",
    "tell them straight up that if we do not smoke Heaven we are going to lose A site every time",
    "let the team know the way we play default on this map is too predictable, change it up",
    "tell them basically every round they are holding the same angle and we keep walking into it",
    "let them know at this point we should just full rush B one round and catch them off guard",
    "tell my team like genuinely the Viper wall across this lane would change everything",
    "hey let the team know if anyone has a KAY/O knife lineup for the main entry we should use it",
    "tell them the issue is we never have smokes up before we step into the site, fix the timing",
    "let them know we need someone to actually call the rotation, not everyone guessing at once",
    "tell the team honestly I think they are just anchoring one player on each site, split it",

    # ---- SPECIFIC AGENT-MAP COMBOS ----
    "tell them Killjoy Lockdown planted on the spike post-plant on this map stops every retake",
    "let my team know that a Reyna Leer into the main corridor before entry clears the close angle",
    "tell the team a Breach Rolling Thunder through the wall on this map hits every clustered defender",
    "let them know a Sage Slow Orb on the ramp or staircase entry wins the time game every round",
    "tell them Sova Hunter's Fury through the wall into the back of the site is a guaranteed kill",
    "let the team know Clove smokes from death means our controller stays useful even after dying",
    "tell them a Yoru clone walk through the main entry will bait every defender into shooting early",
    "let my team know Neon fast lane through B Main creates a split sightline that defenders hate",
    "tell the team a Cypher spycam above the entry angle gives free information for the whole round",
    "let them know a Tejo guided salvo into the entry corridor clears it without anyone entering",
    "tell them Skye Seekers after the plant locate every remaining defender in the entire map",
    "let the team know a Phoenix Curveball around the corner into the main is an effective flush",
    "tell them a Vyse Shear placed on the approach choke forces defenders to stop or get rooted",
    "let my team know a Gekko Wingman plant while we hold the entry angle is a massive time advantage",
    "tell the team an Astra Gravity Well on the default plant area pulls defenders out of cover",

    # ---- MAP-SPECIFIC STRATEGY OPINIONS ----
    "tell the team the right play on this map right now is to stack three on the easier site and run it",
    "let them know we should play the slower side of the map for information before forcing anything",
    "tell them we should smoke the long angle first before any short angle, the Op kills us at distance",
    "let the team know we are wasting our smokes on passive positions, use them for the execute",
    "tell them the key to attacking this map is making them rotate before we commit, fake first",
    "let my team know the defense setup we should run is two anchors with three rotators through mid",
    "tell them playing three on the smaller site and two on the larger site makes no sense here",
    "let the team know we should identify their anchor player and target the unanchored sites",
    "tell them this map is defender-sided but we keep playing like it is a rush map, slow down",
    "let them know we have to make them burn utility before we execute, slow the pace this half",
    "tell the team the worst thing we can do right now is keep splitting our utility across both sites",
    "let my team know we cannot keep hitting the same site every round, they have the read on us",
    "tell them we need one lurker to stay mid and cut the rotation every execute, it is free kills",
    "let the team know the pattern they have seen from us is too readable, change the timing",
    "tell them we should anchor the easier site and have four rotate to whatever they do not hit",
    "let them know if we win the pistol round the bonus round strategy on this map is full Spectre rush",
    "tell the team their Operator on that angle is not going away, we need a utility commitment to clear it",
    "let my team know a two-player split through two different entry points is always stronger than single file",
    "tell them we keep dying to the same off-angle every round because we aim at the default hold",
    "let the team know the off-angle in that corner is an intentional setup, stop walking into it blind",

    # ---- HAVEN (additional) ----
    "tell them on Haven that running two controllers to cover all three sites is not optional, it is required",
    "let the team know we should put someone in Garage every round for the map control it provides",
    "tell them we cannot afford to cede mid on Haven or we lose rotational advantage on every round",
    "let my team know that three defenders on B site is a waste when B is the safest site to retake",
    "tell the team C Long defenders need a flash opener before any push because Operators own that lane",

    # ---- PEARL (additional) ----
    "tell them on Pearl the B Main push is never free without utility, use Viper wall every time",
    "let the team know we should fight for mid first then decide A or B based on information",
    "tell them B Link from mid is the second angle into B site that defenders cannot cover from Screen alone",
    "let my team know that Pearl has no shortcuts, rotation timing here determines every round outcome",
    "tell the team that A Main curve box can be wallbanged if they are hiding behind it",

    # ---- BREEZE (additional) ----
    "tell them on Breeze mid Cannon is the junction point between mid and B Elbow, control it for B access",
    "let the team know playing through B Elbow from mid adds a second angle and splits the B defense",
    "tell them Sova recon through the large open mid area on Breeze reveals staging players every round",
    "let my team know we should play a crossfire on B site with one player in B Cubby and one at B Pillar",
    "tell the team the A Cave approach to A site bypasses the long Main angle and is underused",

    # ---- FRACTURE (additional) ----
    "tell them on Fracture the three-man A execute plus two-man zipline bluff to B is our signature play",
    "let the team know the B Bench position catches people coming through both Arcade and Underpass",
    "tell them A Gate near A Dish is where CT-side defenders try to catch flanking attackers",
    "let my team know the four ult orbs on Fracture mean everyone should have ult charged by mid-half",
    "tell the team A Heaven plus Generator on A site post-plant is nearly an unbeatable defensive hold",

    # ---- ASCENT (additional) ----
    "tell them on Ascent we should always push A Main and Catwalk simultaneously to force the defender to choose",
    "let the team know Heaven on A site gives free information on both A Main entry and Garden simultaneously",
    "tell them the Gen default plant behind the generator on A is covered from Tree and Garden for free",
    "let my team know that Hell under A Heaven is the hardest post-plant spot to clear on the entire map",
    "tell the team the B door in Market should be closed by a defender early to force B Main attack",

    # ---- SPLIT (additional) ----
    "tell them on Split the Ramen shop is the community callout for the area near B Link in mid",
    "let the team know A site Benches inside A Lobby are sub-callout positions for holding the approach",
    "tell them B site has a TV corner position that gives a strong angle on limited escape options",
    "let my team know B Long Plant on B site is further from Tower and exposes the post-plant team to retakes",
    "tell the team the Back CT hallway runs along the entire defender side connecting A back to B Tower stairs",

    # ---- BIND (additional) ----
    "tell them on Bind A Lobby is where the B Long TP exits, near A Bath, and it is free intel",
    "let the team know a Sova recon through B Garden reveals every attacker staging in Hookah",
    "tell them the B Roof position is an elevated overhang that gives angles down onto Hookah entrants",
    "let my team know the A Short TP sounds globally audible, it is the most important audio cue on Bind",
    "tell the team playing A Heaven plus Triple Box post-plant on A is the hardest possible defense to break",

    # ---- LOTUS (more specific) ----
    "tell them C Platform on Lotus is the elevated plant spot on C site and a strong defender retake angle",
    "let the team know C Bend on Lotus is the curved corner on the right side of C site from attacker view",
    "tell them A Double Box near the Hut on A site is the standard A default plant position on Lotus",
    "let my team know B Lower on Lotus is the pit section below B Stairs and an excellent post-plant spot",
    "tell the team the A Drop silent drop mechanic requires holding forward then tapping back before landing",

    # ---- ICEBOX (additional) ----
    "tell them on Icebox the A Maze is the winding corridor on site connecting Screens to Generator side",
    "let the team know Kitchen Window was added in the Episode 8 rework and gives defenders a new peek angle",
    "tell them the A Heaven walkway on Icebox overlooks Belt, Pipes, and Nest from above",
    "let my team know B Orange is the orange container on B site and marks the lower B area",
    "tell the team Jenny is community slang for a corner near Defender Spawn on Icebox",

    # ---- MIXED OPINIONS & STRATEGIC READS ----
    "tell them we need to respect the anchor and not push into a 1v1 they have set up for free",
    "let the team know our rotation timing is wrong, we are rotating after the plant not before",
    "tell them the clock is their enemy on attack if we keep playing slow past forty-five seconds",
    "let my team know that playing default and looking for picks is the right call with this composition",
    "tell the team if we catch the lurker we should not chase, collapse on the site instead",
    "let them know the way to beat their Operator is to deny the angle with a smoke first, then entry",
    "tell them staying out of the main after a teammate dies there and finding a second angle is free value",
    "let the team know stopping and shoulder peeking the corner before committing to entry saves lives",
    "tell them the issue is not aim, we keep entering in single file and trading one for one at best",
    "let my team know playing around the spike timer is an actual strategy, do not throw post-plant",
    "tell the team we cannot afford to let them farm ult orbs every round, contest the orb positions",
    "let them know a coordinated retake with two angles on the spike beats a lone clutch every time",
    "tell them calling the rotation before the execute is done is what gets the anchor killed on defense",
    "let the team know anchoring alone on a site while four rotate is a skill, not everyone can hold it",
    "tell them honestly we just need one good default round to identify their patterns before going aggressive",
    "let my team know we have been burning every smoke on poke and arriving at the execute with nothing left",
    "tell the team we should play for a pick in mid before any site commitment, it wins the numbers game",
    "let them know the timing of our execute needs to be tighter, staggered entry kills the whole team",
    "tell them on this side of the map we should play toward the closer site and rotate if it shows empty",
    "let the team know we are giving them free information by peeking angles that do nothing tactically",
    "tell them we need the lurker to time the flank to when the execute starts, not before",
    "let my team know that calling damage is half the game, we keep getting one-shot because nobody said he was lit",
    "tell the team our sentinel needs to watch the flank path because we keep getting stabbed in the back",
    "let them know we should stack the easier execute site and reset if it shows stacked",
    "tell them honestly the strategy is simple, smoke two, flash one, and entry with the info, execute cleaner",
    "let the team know we need communication in real time not post-round analysis while we are dying",
    "tell them on defense we should be getting information without taking contact, use drones and recon first",
    "let my team know this map rewards playing with information over raw aim, slow it down a tier",
    "tell the team we are walking into the same Operator angle repeatedly, learn from the first death",
    "let them know we should play for the timer advantage and make them run the clock down on us",

    # ---- ASCENT DEEP CUTS ----
    "tell them the Subroza spot under Mid Top near Catwalk is one of the hardest positions to check on Ascent",
    "let the team know an Omen TP into Workshop on B site completely repositions the lurker behind the plant",
    "tell them Sage wall on A Main forces the attacker team to commit a whole extra smoke just to push",
    "let my team know a Killjoy Turret placed in mid provides both A and B side information all round",
    "tell the team the A Peak Long Cubby inside A Main is where defenders get early picks, clear it",
    "let them know we should be smashing the B door early with Raze satchels if we want a free Market flank",
    "tell them the Garden to Window breakable glass on A site creates a new Heaven entry if we shoot it",
    "let the team know on Ascent the Subroza nook can hide a lurker watching mid Catwalk undetected",
    "tell them Sova recon into the mid courtyard every single round is the reason Sova is mandatory here",
    "let my team know a back-gen plant on A site is the deepest option and hardest retake for defenders",

    # ---- HAVEN DEEP CUTS ----
    "tell them on Haven one player in Nest above Garage gives information on both mid and C approaches",
    "let the team know the A Tunnel Sewer short route to A site is the fast flank option attackers ignore",
    "tell them playing A Hell under A Tower post-plant forces attackers to commit a molly before defusing",
    "let my team know Haven has the widest CT rotation network of any three-site map because of Garage",
    "tell the team B Gong wood wall at back of B site is the hardest post-plant position to clear",
    "let them know on Haven we should always count defender rotations by listening for Garage door breaks",
    "tell the team a Breach Rolling Thunder through A Long walls hits every defender stacked at A Tower stairs",
    "let them know the A Ramp on A Long leading up toward site is where rifles have the angle advantage",
    "tell them putting a Cypher cage on A Link cuts the A-to-mid rotation path for the whole round",
    "let my team know Haven is the only three-site map in the competitive pool right now besides Lotus",

    # ---- SPLIT DEEP CUTS ----
    "tell them on Split the Back CT hallway lets defenders run silently from B Tower stairs to A Rafters",
    "let the team know A Screens on Split has spam gaps that let you fire into A Main without full exposure",
    "tell them Mid Market near B Link is the community name for the storefront area connecting mid to B",
    "let my team know a Viper Toxic Screen along A Ramps cuts off A Heaven and A Rafters in one placement",
    "tell the team the Orange room in mid corridor is a community callout for a small hiding spot most ignore",
    "let them know climbing the B Hell rope is loud and you are completely exposed during the animation",
    "tell them Gekko Wingman can plant on B site while we hold B Heaven and the entry simultaneously",
    "let the team know B Heaven stairs on the defender side are the primary way to reach B Tower safely",
    "tell them the B Rafters elevated position above B site gives angles on both Garage entry and the site",
    "let my team know a double-flank through Sewer and mid Vent simultaneously puts pressure on both sites",

    # ---- BIND DEEP CUTS ----
    "tell them on Bind A Bath Boost spot near the shower exit lets a defender peek down into the bathroom",
    "let the team know B Short leads from B Garden through Hookah and is the faster B approach",
    "tell them the B Lobby fountain area is where the B ult orb spawns, it is exposed but worth grabbing",
    "let my team know Under Hookah at ground level beneath the window is where defenders lurk on B site",
    "tell the team Roof on B site is an elevated overhang that covers both the Hookah window and below",
    "let them know Neon speed ability synergizes well with TP flanks and the B Long approach timing",
    "tell them a Raze Showstopper through the Hookah window clears both the window and the room below",
    "let the team know an Astra Gravity Well at the TP exit catches everyone coming out the teleporter",
    "tell them the A Ninja spot on A site is a deep ambush angle that counters the first-wave entry entirely",
    "let my team know we should alternate between using the TP and not using it to keep them guessing",

    # ---- PEARL DEEP CUTS ----
    "tell them on Pearl B Hall is also called B Museum because of the museum interior aesthetic",
    "let the team know Defender Water room is a low crawl space that puts CT-side players at a height disadvantage",
    "tell them the B Tower Pillar was thickened in Patch 6.11 giving defenders more safe holding area",
    "let my team know we should use Mid Shops as the lower mid lane and Mid Top as the upper to split the angle",
    "tell the team the wallbang box on A Main curve is a known kill shot through wood crates",
    "let them know Tejo Stealth Drone is rated alongside Sova for Pearl because of the long corridor visibility",
    "tell them a Viper Pit on B site post-plant makes the defuse genuinely impossible without multiple utilities",
    "let the team know B Screen peek used to be a wallbang but impenetrable blocks were added behind it",
    "tell them the orb in mid Plaza means the mid fight already has economic value beyond map control",
    "let my team know we should place Killjoy Nanoswarm on B Ramp as the B execute opener every time",

    # ---- FRACTURE DEEP CUTS ----
    "tell them on Fracture A Heaven controls A Drop, A Main, A Link, and all of A site from above",
    "let the team know A Hell at bottom site is the lowest plant position and the hardest to clear on retake",
    "tell them the A Stairs vertical connector on A site links Bottom Site to Top Site in close combat",
    "let my team know a Cypher cage on B Link cuts the defender rotation to B every single round",
    "tell the team B Tree at the top B attacker spawn approach lets us pre-aim down B Main before entry",
    "let them know a KAY/O knife landing in Defender Spawn suppresses every ability from both sites at once",
    "tell them we should put two on A Dish for the flanking angle and three pushing A Main for a split execute",
    "let the team know that A Gate near A Dish is the CT-side opening where defenders catch flanking attackers",
    "tell them using both ziplines in the same round creates confusion about which site actually gets hit",
    "let my team know that B Double Box at B Main entrance gives cover for peeking into the site from outside",

    # ---- LOTUS DEEP CUTS ----
    "tell them on Lotus C Mound is the early control point that determines who controls the C Door timing",
    "let the team know A Root is the large tree root structure providing natural covered approach to A Main",
    "tell them the A Rubble debris area near A Door is a contested early-round duelling zone every half",
    "let my team know the Waterfall ambient sound at C Waterfall can mask defender footstep sounds completely",
    "tell the team C Close Right is the right-side close-range hold on C site that lurkers abuse post-plant",
    "let them know a Deadlock GravNet through B Pillars corridor traps every attacker in the choke",
    "tell them Harbor High Tide wall along C Main is as effective here as Viper wall on other maps",
    "let the team know A Hut in A site center is called Midsight by some players because it splits sightlines",
    "tell them contesting A Top early gives us the rope ascender control and elevation over the whole site",
    "let my team know that a three-site map with only five defenders means one site is always undermanned",

    # ---- BREEZE DEEP CUTS ----
    "tell them on Breeze the Orange container on A site cannot be wallbanged and is solid cover post-plant",
    "let the team know B Planks is the wooden area at the foot of B Main before stepping onto B site",
    "tell them B Lane is the straight-on path from B Main entry onto the B site floor level",
    "let my team know the A Cave route avoids the long A Main Operator angle and is underused by attackers",
    "tell the team the A Switch mechanism near A site end of A Hall controls the Metal Door mechanic",
    "let them know B Back Pillar behind B site gives a secondary cover structure for post-plant holds",
    "tell them the Mid Stack of boxes near Mid Pillar is secondary cover and height in mid bottom area",
    "let the team know Sova recon through the wide mid areas on Breeze still reveals staging positions",
    "tell them a Fade Haunt into the Nest area from below reveals any Operator player before they see us",
    "let my team know A Hall is also called A Tube by the community and connects mid to the A site corridor",

    # ---- ABYSS DEEP CUTS ----
    "tell them on Abyss a player falling off A Bridge is an instant death, the void has no floor",
    "let the team know A Cobby is the Liquipedia name for what most players just call A Lobby on Abyss",
    "tell them B Danger jump across the outer ledge behind B site is a risky shortcut but creates surprise angles",
    "let my team know Mid Library with the bookshelves is the central staging area in the mid section",
    "tell the team A Security is the defender cut-through that lets them peek into A Main from the flank",
    "let them know four rope ascenders are distributed across Abyss and are silent to others unless nearby",
    "tell them the A Vent breakable doors at both ends are blue to yellow to red as HP drops from bullets",
    "let the team know the Mid Bottom below the void connects toward B Main side and has the most open angles",
    "tell them B Nest near B site is a flanking concealed position used for post-plant holds on B",
    "let my team know a Killjoy Lockdown on B site is especially strong because the open layout forces defenders to move",

    # ---- CORRODE DEEP CUTS ----
    "tell them on Corrode B Elbow is essential for both defensive fallback and attacker post-plant crossfire on B",
    "let the team know A Yard is the intermediate open zone between A Main and A site, second major entry point",
    "tell them A Pocket off A Main has tight corners requiring a clear before stepping into A Yard",
    "let my team know Mid Bottom on Corrode has water sections, walk through them slowly or give away position",
    "tell the team A Crane is the high ground entry for defenders on A site, it is their natural perch",
    "let them know B Arch is the defensive entryway to B site from CT spawn and the primary defender anchor",
    "tell them Mid Window in mid on Corrode provides cross-map sightlines between Top mid and B approach",
    "let the team know B site on Corrode has layered elevation including Tower top, shed top, and boxes",
    "tell them Breach and Skye flashes are ideal here to force through B Tower and B Arch layered elevation",
    "let my team know Corrode is not in the current competitive map pool, it was rotated out with Act 2",

    # ---- ICEBOX DEEP CUTS ----
    "tell them on Icebox A Gate on A site is a doorway position that gives post-plant angles on site entry",
    "tell the team the A 410 community name comes from the visible number printed on the large crate on site",
    "let them know B Hut near the B approach side is a small structure providing early cover before B Main",
    "tell them B Black is community slang for a dark shadowed corner on B site that is hard to see in",
    "let the team know Kitchen Window added in the Episode 8 rework lets defenders peek incoming B Main attackers",
    "tell them the horizontal Belt zipline at elevation lets defenders or attackers rapidly reposition along A lane",
    "let my team know Under Tube in mid is faster but has significantly more angles to check than top route",
    "tell the team the Jenny community slang refers to a specific corner near Defender Spawn on Icebox",
    "let them know Sage Wall placed across the A Belt zipline denies vertical elevation access for a full round",
    "tell the team B Fence line on the B approach side is the outermost forward position for B Main staging",

    # ---- VARIED PHRASING / REGISTER ----
    "honestly tell my team that they are overthinking this map, just smoke Heaven and run A Main",
    "let them know bruh at this point we should just default every round and let them make mistakes",
    "tell the team for real this round we need to play slow and let the clock pressure them into pushing",
    "let my team know on the real we cannot keep hitting the same site, they have our pattern memorized",
    "yo tell them that mid control on this map is literally everything and we keep giving it away for free",
    "tell them respectfully our smokes have been going in the wrong place all game, fix the lineup",
    "let the team know honestly our biggest problem is not ability usage, it is our rotation timing",
    "tell them bro the way we have been playing A Main is straight up feeding, find a different approach",
    "let my team know with all due respect we need someone to step up and call the execute clearly",
    "tell the team if we just play one round of clean coordinated utility usage we will see how strong we are",
    "tell them look we are better individually but they are reading us like a book, change something",
    "let the team know listen I get that it is frustrating but one disciplined execute is all we need",
    "tell them honestly we need to stop arguing mid-round and just commit to the call that was made",
    "let my team know the difference between a win and a loss on this map is usually two seconds of timing",
    "tell the team we should not get tunnel-vision on one entry route, the map has three ways onto site",

    # ---- ECONOMY + MAP CROSS ----
    "tell them on this map a force buy with Spectres and a rush through the fastest lane is actually viable",
    "let the team know if they are full saving we should anti-eco and take the easy ground without risking rifles",
    "tell them an eco rush through the short path on this map can catch full-buy defenders completely off guard",
    "let my team know the pistol round on this map should be played toward the site with the shortest path",
    "tell the team we should buy light this round and play passive to learn their setup before the full buy round",
    "let them know dropping an extra rifle to a teammate on this map is worth more than individual grenades",
    "tell the team if we save now we can full buy next round and actually execute properly with all utilities",
    "let my team know a half-buy Guardian on the long angle of this map punches way above its price point",
    "tell them we should not force this round, we have the credits to reset properly and hit them next round",
    "let the team know their eco rush this round is likely, stack the short path and watch for the rush",

    # ---- POST-PLANT / RETAKE SPECIFICS ----
    "tell them post-plant on A we need two angles on the defuse, not everyone watching the same entry",
    "let the team know if they retake through two entries simultaneously they will trade favorably every time",
    "tell them plant for the CT side this round so we hold the angle they cannot reach under time pressure",
    "let my team know do not fight on the retake, let them run out of time if we have the spike angles covered",
    "tell the team a molly on the spike when we have the defuse angle already won is unnecessary, save it",
    "let them know if we have one watching the spike and one watching the entry they cannot defuse safely",
    "tell them the ninja defuse is a real option if we can get one player past their post-plant positions",
    "let the team know calling spike timer loudly at forty-five and at twenty seconds keeps everyone on track",
    "tell them on this map the default plant faces toward the main so we can peek from behind on defuse",
    "let my team know we should plant for the CT side this round so our post-plant angle faces their rotation",

    # ---- CLUTCH & LATE ROUND ----
    "tell them in a clutch situation on this map use the cover positions to deny full sightlines and move slow",
    "let the team know if the spike is down we do not need kills, just play around the timer",
    "tell them in a 2v3 the best play on this map is to split them around the site rather than face one at a time",
    "let my team know a fake defuse on this map buys the angle reveal and then the punish, use it",
    "tell the team a 1v1 clutch on this map is about forcing the enemy to make a move, do not push blind",
    "let them know the last player alive needs to know where the spike is before doing anything else",
    "tell the team if we are down to two players left we should stick together and play around one angle",
    "let my team know the tap spike fake defuse is one of the highest percentage plays in a 1v2",
    "tell them in a retake situation the person with the best weapon should enter first not the lowest HP",
    "let the team know we won that but the late-round comms fell apart, call the spike timer every time",

    # ---- REGISTRATION / VARIED SENTENCE STRUCTURES ----
    "tell the boys that mid on this map is contested every single round and nobody can afford to ignore it",
    "let the squad know our smoke placements have been wrong all game, the controller needs to fix the lineup",
    "tell the homies honestly if we just ran one textbook execute we would absolutely win this map",
    "let the crew know we should not be dry peeking that angle without at least a shoulder peek first",
    "tell the fellas that the map is telling us B site is open, let us actually take the information",
    "let everyone know straight up that we play the same strategy every round and they are anti-stratting us",
    "tell the guys that the problem is our utility is going in too early and fading before we actually push",
    "let them know that honestly this is just a map control problem, we give up space every single round",
    "tell the team no cap we are better at this game than we are showing, focus and run the execute",
    "let everyone know dead serious our anchor needs to communicate more or defenders cannot rotate on time",

    # ---- AGENT-SPECIFIC CALLS (map-contextual) ----
    "tell them if Jett is using the Op on this lane she needs dash ready as an escape, not used early",
    "let the team know our Killjoy should anchor the harder site because her kit enables a solo hold",
    "tell them KAY/O knife into the main suppresses every ability and forces raw gunfights",
    "let my team know Reyna is aggressive but gives us zero information, someone else needs to drone",
    "tell the team that Viper needs to decide the wall placement before the round starts, not mid-round",
    "let them know Sova needs to call what the recon dart reveals immediately, not after the info expires",
    "tell them Omen Shrouded Step onto an unexpected angle behind their Operator is free RR",
    "let the team know that Fade Haunt into the default plant position reveals every post-plant camper",
    "tell them Sage Barrier on the ramp or staircase entry gives defenders an extra twenty seconds minimum",
    "let my team know Chamber Trademark on the rotation path gives early warning before they commit to site",
    "tell the team Breach Fault Line through the wall stuns the entire main entry if they are stacked",
    "let them know a Cypher Neural Theft gives full information on every living player position at death",
    "tell them Skye Seekers after the plant track every remaining defender and expose their post-plant",
    "let the team know Deadlock Annihilation through the long entry corridor is an unstoppable clear",
    "tell them our Raze Showstopper needs to be used for the execute, not after the site is already taken",

    # ---- MORALE / TACTICAL OPINION READS ----
    "tell the team we are not getting outaimed, we are getting out-positioned, change the approach",
    "let them know we have the better composition on this map but we are not playing to its strengths",
    "tell them we are one coordinated execute away from turning this around, stay disciplined",
    "let my team know that losing mid does not mean losing the round, reset and play for picks",
    "tell the team our timing is off by about two seconds every execute and it is costing the entry",
    "let them know we are winning individual duels but losing the map because we do not trade fast enough",
    "tell them the enemy team is running the same strategy every round because it is working, adapt",
    "let the team know we need to stop second-guessing the call mid-execute and just commit",
    "tell them we have better utility but worse timing, the answer is to execute later in the round",
    "let my team know the problem is not the map or the composition, we are rotating at the wrong times",
    "tell the team we should force them to play at uncomfortable angles by changing our approach lane",
    "let them know on defense we keep giving up space without trading, make every poke cost them something",
    "tell them our anchor is getting overwhelmed because we are not giving rotation call-outs fast enough",
    "let the team know playing the easier site does not mean playing the wrong site, it is good map sense",
    "tell them we need one round of pure information to understand their default tendencies before adapting",

    # ---- FINAL BATCH: REGISTER VARIETY + MAP-SPECIFIC NUANCE ----
    "tell them the Ascent catwalk angle rewards a Jett updraft to an unexpected height that defenders never check",
    "let the team know Omen teleport to Garden or Tree on Ascent creates a free behind-their-Operator position",
    "tell them the Garden window on Ascent can be broken to create a new Heaven entry route mid-round",
    "let my team know a KAY/O NULL cmd ultimate on Ascent site walk wins the retake by removing all utility",
    "tell them on Haven the B site execute requires smoking A Link and C Link before anyone steps inside",
    "let the team know Skye dog through Haven Garage clears both Nest and the lower Garage in one use",
    "tell them on Haven A Hell post-plant forces a molly spend before any defuse is even possible",
    "let my team know on Split the A Ramps plus A Main simultaneous push is what breaks the A Heaven hold",
    "tell them on Split B Rafters gives angles on both Garage entry and the B default plant at once",
    "let the team know a Cypher cage in Split Sewer blocks the mid rotation between A and B for a full round",
    "tell them on Bind smelling the TP sound means rotating preemptively, before they exit the other end",
    "let my team know on Bind the B Long TP to A Lobby is a one-player split tool that does not need a team",
    "tell them on Lotus breaking the B Wall makes permanent noise that tells every defender exactly where we are",
    "let the team know on Lotus the C Mound high ground gives angle down onto C Main entry before the door",
    "tell them on Lotus three ult orbs means everyone should have their ultimate by mid-round of each half",
    "let my team know on Pearl B Main without a Viper wall is a round forfeit, do not push it dry",
    "tell them on Pearl A Art from mid creates a two-angle execute that the defense cannot cover with one player",
    "let the team know on Pearl losing Mid Doors means every attack becomes a single-entry corridor fight",
    "tell them on Fracture a three-man A execute with two staying at B tree is not a split, it is a bait",
    "let my team know on Fracture B Canteen and B Generator are the two places defenders retake from",
    "tell them on Breeze the Nest jump-up is ability-gated post-rework, so only Jett Omen or Raze can reach it",
    "let the team know on Breeze the B Cubby expanded significantly in the rework and needs a full corner check",
    "tell them on Abyss the rope ascenders are silent unless you are standing right next to someone using one",
    "let my team know on Abyss Mid Library connects both mid lanes and is the central information choke point",
    "tell them on Corrode walking through the flooded sections is the most important movement discipline on this map",
    "let the team know on Corrode B site layered elevation with Tower and Arch requires two separate smoke placements",
    "tell them on Icebox the Kitchen room controls both the Tube rotation and the B site drop simultaneously",
    "let my team know on Icebox the B site Yellow container post-plant forces defenders to have width to retake",
    "tell them on Icebox A Nest plant puts the spike inside the elevated room for a brutal post-plant hold",
    "let the team know on Icebox a Viper wall along A Main to Belt blocks every Heaven and Rafters angle at once",
    "tell them this round we need to play slower and respect the clock, they will push into us eventually",
    "let my team know playing aggressive on defense early drains utility and leaves us empty at mid-round",
    "tell them every time we execute without a smoke on the obvious Operator position we lose a player for free",
    "let the team know we should call what we see in the drone before it gets destroyed, not after",
    "tell them the lurker timing needs to coincide with when the execute starts, not after we are already dead",
    "let my team know a coordinated three-man execute is stronger than a chaotic five-man rush on every map",
    "tell the team post-plant discipline means not swinging the same angle twice if the first player died there",
    "let them know the reason they keep winning the retake is that we are all watching the same angle",
    "tell them spreading out on site after planting is the entire concept of a post-plant position",
    "let my team know watching the defuse from one angle while someone else watches entry covers both threats",
    "tell them if the spike is down and we are full health, time is on our side, do not force unnecessary fights",
    "let the team know the entry should announce contact before dying, not go silent when the duel starts",
    "tell them the IGL should be counting enemy abilities out loud so we know when to push without a flash",
    "let my team know we need to win one anti-eco round cleanly or we will fall behind economically this half",
    "tell the team a thrifty win on an eco round swings the economy in our favor for two full rounds",
    "let them know if we die with our rifles on a round we know we are going to lose we just sabotaged the next",
    "tell them on that map layout running two lurkers creates confusion but leaves the site execute short-handed",
    "let my team know the way to play against a stacked site is to fake it and hit the other one with utility",
    "tell the team a default opener where we spread and gather information before committing wins information maps",
    "let them know our opponent's anchor is playing a very aggressive off-angle, check deeper before stepping in",
    "tell them we have the utility to win this execute if everyone uses their ability at the correct moment",
    "let the team know we are winning the map control fights but losing the execute timing, tighten it up",
    "tell them honestly we just need one round where we trust the smoke and push on the controller cue",
    "let my team know calling the rotation two seconds earlier changes whether the anchor survives or dies alone",
    "tell the team the gun fight we keep losing at the main entry is a crosshair placement problem not an aim one",
    "let them know stopping movement before shooting in that corridor means our shots actually land accurately",
    "tell the team the mistake is pre-aiming the default hold angle when they are clearly playing an off-angle",
    "let my team know an early peek from a distance lets us identify the off-angle before committing",
    "tell them the reason we keep losing the first fight is we are not counter-strafing before we shoot",
    "let the team know peeking slowly and wide gives us more time to react than a fast swing into an angle",
    "tell them a shoulder peek at that corner before committing is completely free information, use it",
    "let my team know a jiggle peek is the correct opener for any corner where we are not sure they are waiting",
    "tell the team if we can pre-fire the corner with information from a drone we win that duel before it starts",
    "let them know our aim is fine, our positioning before the aim duel is what needs to improve this game",
    "tell them we keep losing because we are standing in the middle of the lane and not using the cover geometry",
    "let my team know the side walls in that corridor can be used to break line of sight during a push",
    "tell them we should be playing the geometry of the map, not just gunfighting in the open every round",
    "let the team know the advantage of this map is the number of angles, use them instead of head-to-head duels",
    "tell them this is a map that rewards reading the enemy pattern, we have had enough rounds to know their default",
    "let my team know at this point in the half we should know which site they favor and hit the other one",
    "tell the team recognizing their pattern and going opposite is the highest-percentage play we have right now",
    "let them know the information we have from the last eight rounds tells us exactly what they will do, adapt",
    "tell them we have been reactive all game, this round we should be proactive and force them to respond to us",
    "let my team know a proactive mid fight early round takes control away from the defenders who are waiting",
    "tell the team we should not wait for them to come to us on attack, we need to force the issue on a site",
    "let them know playing too safe on attack means they just set up utilities and wait, we need to create pressure",
    "tell them a fast execute within the first thirty seconds of the round before they rotate is statistically strong",
    "let the team know a slow round where we clear every angle before committing is the alternative when rushed fails",
    "tell them each approach has merit depending on information, the key is choosing the right one at the right time",
    "let my team know that our composition this round favors a fast execute because our initiators have flashes",
    "tell them we should never run an execute without the initiator going in first with a flash or drone",
    "let the team know our initiators need to flash and the duelists need to follow within one second of the flash",
    "tell them the entry duelist should not be leading without a flash in front of them, that is the support role",
    "let my team know that the controller smokes need to be in before the entry fragger steps up, not simultaneously",
    "tell the team we have been executing with smokes going in at the same time as entry and it is too slow",
    "let them know smoke first, one beat, then entry gives the smoke time to actually blind the angle",
    "tell them coordinating the smoke timing with the flash timing and the push timing is what pro teams do",
    "let my team know we have the individual skill to win this, we just need to execute like a team for one round",
]
