"""Bare agent/count + action callouts with no explicit enemy -- Ultron should
infer the enemy contextually and frame cleanly (deterministic)."""
ITEMS = [
    'tell my team jett is flank',
    'tell my team jett flank',
    'tell my team jett and sova are flank',
    'tell my team cypher is flanking',
    'tell my team cypher flanking',
    'tell my team cypher and killjoy are flanking',
    'tell my team raze is pushing',
    'tell my team raze pushing',
    'tell my team raze and reyna are pushing',
    'tell my team omen is push',
    'tell my team omen push',
    'tell my team omen and viper are push',
    'tell my team sage is rotating',
    'tell my team sage rotating',
    'tell my team sage and brimstone are rotating',
    'tell my team neon is rushing',
    'tell my team neon rushing',
    'tell my team neon and fade are rushing',
    'tell my team breach is lurking',
    'tell my team breach lurking',
    'tell my team breach and kay/o are lurking',
    'tell my team astra is peeking',
    'tell my team astra peeking',
    'tell my team astra and harbor are peeking',
    'tell my team gekko is holding',
    'tell my team gekko holding',
    'tell my team gekko and chamber are holding',
    'tell my team skye is baiting',
    'tell my team skye baiting',
    'tell my team skye and yoru are baiting',
    'tell my team phoenix is swinging',
    'tell my team phoenix swinging',
    'tell my team phoenix and clove are swinging',
    'tell my team deadlock is defaulting',
    'tell my team deadlock defaulting',
    'tell my team deadlock and vyse are defaulting',
    'tell my team 1 is flank',
    'tell my team 1 is flanking',
    'tell my team 1 is pushing',
    'tell my team 1 is push',
    'tell my team 1 is rotating',
    'tell my team 1 is rushing',
    'tell my team 2 are flank',
    'tell my team 2 are flanking',
    'tell my team 2 are pushing',
    'tell my team 2 are push',
    'tell my team 2 are rotating',
    'tell my team 2 are rushing',
    'tell my team 3 are flank',
    'tell my team 3 are flanking',
    'tell my team 3 are pushing',
    'tell my team 3 are push',
    'tell my team 3 are rotating',
    'tell my team 3 are rushing',
    'tell my team one is flank',
    'tell my team one is flanking',
    'tell my team one is pushing',
    'tell my team one is push',
    'tell my team one is rotating',
    'tell my team one is rushing',
    'tell my team two are flank',
    'tell my team two are flanking',
    'tell my team two are pushing',
    'tell my team two are push',
    'tell my team two are rotating',
    'tell my team two are rushing',
    'tell my team three are flank',
    'tell my team three are flanking',
    'tell my team three are pushing',
    'tell my team three are push',
    'tell my team three are rotating',
    'tell my team three are rushing',
]
