"""Curated-command batch-2 phrasings (illogical-play questions, requests, self-status,
strategy with {site}/{agent} slots, yes/no/agree). Should route to curated responses."""
ITEMS = [
    'tell my team what are they doing',
    'ask my team what they think they are doing',
    'tell my team why would they do that',
    'tell my team why nobody is carrying the spike',
    'tell my team the enemy is force buying every round',
    'tell my team the enemy has lots of ults so play picks',
    'tell my team to default because we are on eco',
    'tell my team I am lurking',
    'tell my team to bait me because I am low',
    'tell my team I am saving for op but I believe in them',
    'tell my team I can drop them a gun',
    'tell my team I agree',
    'tell my team I disagree',
    'tell my team yes',
    'tell my team no',
    'ask if someone can drop us a gun',
    'ask Jett what they are doing',
    'ask Sova what they are doing',
    'ask Cypher why they would do that',
    'ask Killjoy why they would do that',
    'ask Sage why they arent doing their job',
    'ask Brimstone why they arent doing their job',
    'ask Omen why they arent carrying the spike',
    'ask Viper why they arent carrying the spike',
    'ask Astra where our smokes are',
    'ask Harbor where our smokes are',
    'ask Neon why they arent smoking',
    'ask Fade why they arent smoking',
    'tell Breach their smokes are terrible',
    'tell KAYO their smokes are terrible',
    'ask Raze for a heal',
    'ask Reyna for a heal',
    'ask Jett to drop us a gun',
    'ask Sova to drop us a gun',
    'tell Cypher I can drop them a gun',
    'tell Killjoy I can drop them a gun',
    'tell Sage to wait for me',
    'tell Brimstone to wait for me',
    'tell my team the easiest site to take is A',
    'tell my team the easiest site to take is B',
    'tell my team they are not holding C',
    'tell my team they are not holding A site',
    'tell my team we need to hold B site better',
    'tell my team we need to hold heaven better',
    'tell my team the enemy is taking mid for free',
    'tell my team the enemy is taking A main for free',
    'tell my team to go B main because the enemy is on eco take longer angles',
    'tell my team to go long because the enemy is on eco take longer angles',
    'tell my team to go short because we are on eco take shorter angles',
    'tell my team to go A long because we are on eco take shorter angles',
    'tell my team I am lurking B short',
    'tell my team I am lurking market',
    'tell Omen to play showers',
    'tell Viper to play garage',
    'tell Astra to play hookah',
    'tell Harbor to play A',
    'tell my team to play off site because Neon has ult',
    'tell my team to play off site because Fade has ult',
    'tell my team to play off site because Breach has ult',
    'tell my team to play off site because KAYO has ult',
    'tell my team Raze is one point off ult and going for orb',
    'tell my team Reyna is one point off ult and going for orb',
    'tell my team Jett is one point off ult and going for orb',
    'tell my team Sova is one point off ult and going for orb',
    'tell my team Cypher is one off ult and will orb in B',
    'tell my team Killjoy is one off ult and will orb in C',
    'tell my team Sage is one off ult and will orb in A site',
]
