ITEMS = [
    # === HEALTH / HP STATE ===
    "tell them I'm on 10 HP, don't push until I reset",
    "let my team know I'm low, need a second",
    "tell them I'm at 30 HP and have no armor",
    "tell my team I'm one shot, don't make a move yet",
    "let them know I got tagged 80, sitting at 20",
    "tell the boys I'm at half health and still pushing",
    "inform the team I'm full HP and ready to entry",
    "tell them I'm 100 HP no armor, I'll be aggressive",
    "let my team know I drank the heal, I'm back to 75",
    "tell them I'm critically low, I need backup before I peek",
    "tell my team I'm at 50, playing off-angle until I rez",
    "let the squad know I tanked a Vandal hit, sitting at 25",
    "tell them I'm fine, just grazed, still at 85",
    "inform the team I got hit in the face, I'm at 7 HP",
    "tell them I'm not low, pushing with confidence",
    "let them know I'm sitting at 40 with armor, I'll hold this",
    "tell my team I'm regenning the regen shield, give me 3 seconds",
    "tell them I took a bad trade, I'm at 15, don't rely on me",
    "inform the team I'm healthy, full HP, full armor, buying all util",
    "tell them I got smacked by the operator, somehow still alive at 20",
    "let them know my regen shield kicked in, back to 50",
    "tell my team I got one-tapped in the shoulder, barely survived at 3",
    "tell them I'm peaking at 100 HP and full shields, let's execute",
    "let the squad know I'm dinking on 20 HP, I'm going for the exit frag",
    "tell them my HP is mid, I'm at 60 but got heavy armor still",

    # === ARMOR / SHIELD STATE ===
    "tell them I have no armor this round, just a rifle",
    "let my team know I'm on light armor, don't throw me into the first fight",
    "tell my team I'm shield-less, I'll play behind them",
    "inform the team I'm rocking heavy armor today, feel free to use me as bait",
    "tell them my shield is gone, took two body shots",
    "let the boys know I have regen shield, I'll hold the corner until it procs",
    "tell them I'm glasscannon this round, Vandal no armor",
    "let my team know I bought heavy shield, I'll go first",
    "tell them I have 25 shield left, not full but enough",
    "inform the team I'm running light armor on purpose, saving for next",
    "tell my team my armor is gone, I burned it crossing mid",

    # === ULTIMATE STATUS ===
    "tell them my ult is ready",
    "let my team know I have ult this round",
    "tell the team I'm one kill away from ult",
    "let them know I need two more orbs for ult",
    "tell them I have no ult, lost it last round",
    "inform the team my ult is up, use me",
    "tell them I burned my ult on the retake, don't count on it this round",
    "let my team know I used ult already, it's down",
    "tell them I'm saving ult for the execute, don't ask me to pop it now",
    "let the squad know ult is charged and I'm ready to go",
    "tell them my ult is three kills away, I need frags",
    "inform the team I have ult but I'm holding it for post-plant",
    "tell my team ult ready, pop it on your call",
    "let them know I'm at 6 out of 8 ult points, almost there",
    "tell the team I just charged ult off that kill",
    "inform them ult is fresh, I'll use it to open the round",
    "tell my team my ult expired without a kill, it's gone",
    "let them know I'm holding ult for the clutch, don't give it away",
    "tell them I need one more orb on CT side for ult",
    "inform the team my ult is ready but I want to coordinate before I pop it",
    "tell them I have ult and I'm going aggressive, play off me",
    "tell the squad I charged ult from the plant bonus, it's ready",
    "let them know I have ult stacked from two rounds ago, let's use it this execute",
    "tell my team I'm at 7 ult points, one kill or orb and I pop",
    "tell them I don't have ult yet, don't think I'll get it this half",
    "let my team know my ult is going to waste if I don't use it in the next two rounds",

    # === ECONOMY / CREDITS ===
    "tell them I'm at 4200 credits, full buy this round",
    "let the team know I have 1800 and I'm saving",
    "tell them I need a rifle, I'm at 2600 but short",
    "inform the team I'm going eco, only got 900 credits",
    "tell my squad I'll drop someone a gun, I have credits to spare",
    "let them know I'm at 5000, I can drop two rifles if needed",
    "tell them I'm forcing this round, spending everything I have",
    "inform the team I'm on full eco, just Classic",
    "tell them I'm going half buy, Spectre plus light armor",
    "let the boys know I bought a Marshal this round, no rifle",
    "tell my team I burned credits last round on utilities, I'm light this round",
    "inform the team I'm at 3000 but I need to save so we can all buy next round",
    "tell them I have credits but I can't afford OP and armor",
    "let my team know I'm carrying spike this round, can someone drop me a Vandal",
    "tell them I bought the Sheriff on eco, going for headshots",
    "inform the team I'm at 4700, Operator round for me",
    "tell them I have enough for rifle and full armor, no util though",
    "let the squad know I went full utility, light armor only",
    "tell them I'm gonna need a drop this round or I'm going Classic",
    "inform the team I'll full buy next round after this eco",
    "tell them I have 2,900 loss bonus this round, I can finally afford a buy",
    "let my team know I'm buying Bulldog on this half buy, don't judge me",
    "tell them I bought extra flashes this round, no rifle, all in on info",
    "inform the team I bought the Odin this round, going Odin-lord mode",
    "tell them I'm at 4200 but I'm gonna take the Operator this round, covering long",

    # === ABILITY / UTILITY STATUS ===
    "tell them my flashes are gone, used both this round",
    "let my team know I have one flash left, saving it for entry",
    "tell them I have no smokes left this round",
    "inform the team my signature is back up, free smoke available",
    "tell them I burned my molly already on mid, nothing for post-plant",
    "let the squad know I have my dash back, I got two kills",
    "tell my team my drone is up, I'll scout with it",
    "inform them my recon bolt is on cooldown, 10 seconds",
    "tell them I deployed the turret already, it's watching B main",
    "let my team know I activated the pit, we're post-plant safe",
    "tell them I have both Blast Packs ready, I'll boost up",
    "inform the team I have no blast pack, I burned them getting here",
    "tell them my stim beacon is down at default plant",
    "let them know my wall is up across mid already",
    "tell the team I set up two nanos on the spike, they shouldn't defuse",
    "inform them I dropped the cam on B main, we have eyes",
    "tell my team both hawks are fresh, two flashes available",
    "let them know I have no hawk left, I used both getting through main",
    "tell the team my knife is out, their abilities are gone for 8 seconds",
    "inform them my seekers are charged, I'll send them on the retake",
    "tell them my wingman is ready, I can plant through smoke",
    "let the squad know I don't have my dog anymore, used it on entry",
    "tell the team my salvo missiles are loaded, two charges, where do you want them",
    "inform them my Viper pit is set up, I'm anchoring site",
    "tell them my cosmic divide is ready, I'll cut the site in half on execute",
    "let my team know I have no util bought this round, full save on abilities",
    "tell them I have aftershock but both flashes are gone",
    "inform the team I have my paranoia, I'll throw it before we push",
    "tell them I have two shock bolts and a drone, lots of info available",
    "let them know I have my Overdrive charged, I'm ready to run it",
    "tell the team I have no Gatecrash left, I used the fake to bait their rotation",
    "inform them my arc rose is planted at elbow, I'll pop it on your call",
    "tell my team my gravity well is ready, I have a star at default",
    "let them know I have a nova pulse pre-placed at the entrance, just say go",
    "tell them I have both pieces of Nanoswarm down already, defending spike",
    "inform the team I have one razorvine left, saving it for their retake",
    "tell them I have my Steel Garden charged, if they rush I'll jam their primaries",
    "let my team know I have my Evolution ult, nothing can stop me",
    "tell them my Annihilation is ready, I'll cocoon someone on retake",
    "inform the team I have the Lockdown placed, 13 seconds on the windup",
    "tell them my Chokehold is down in the hallway, they can't run through it",
    "let my team know I have regrowth still available, group up for heals",
    "tell them I have my slow orbs, both of them, saving for the push",
    "inform them I have my Cove ready, I'll shield the plant",
    "tell the team I have my Nightfall ult charged, sending it on execute",

    # === WEAPON STATE ===
    "tell them I have the Op, I'm holding long",
    "let my team know I picked up a Vandal from the kill",
    "tell them I'm on a Phantom this round",
    "inform the team I found a dropped rifle, I'm not on eco anymore",
    "tell them I'm running Sheriff only, watch my back",
    "let the squad know I have the Op, save the plant for me to cover",
    "tell my team I dropped my gun in the smoke, I'm on Classic",
    "inform them I'm using Jett's knives, blades out, I have the Op replacement",
    "tell them I bought an Outlaw, I'll play like a budget Op",
    "let them know I have a Judge this round, don't send me to long angles",
    "tell my team I have the Marshal, cheap op strats are in play",
    "inform the team I'm running the Spectre on this force buy",
    "tell them I have the Ares, I'll spray through smokes",
    "let the boys know I have a Guardian, going for one-taps at range",
    "tell my team I have full utility but I'm on a Bulldog, buy round was a stretch",
    "inform them I found the Op on the ground, do you want me to hold this or find a rifle",
    "tell the team I'm on a Frenzy this round, staying close range",
    "let my team know I grabbed their dropped Vandal, I'm re-armed",
    "tell them I have my headhunter pistol, no rifle but I one-tap heads",

    # === POSITION / LOCATION STATUS ===
    "tell them I'm on A main, holding",
    "let my team know I'm at heaven, watching site from up top",
    "tell the team I'm crossing mid right now, cover me",
    "inform them I'm rotating to B, one minute",
    "tell them I'm anchoring A, take your time rotating",
    "let the squad know I'm deep in B back site",
    "tell my team I'm at elbow, ready to swing",
    "inform the team I'm posted at CT, nobody is coming through here",
    "tell them I'm holding garage, nobody gets through",
    "let my team know I'm out of position, give me 5 seconds to reset",
    "tell them I'm taking mid control right now",
    "inform the team I'm already in the smoke, push when ready",
    "tell them I'm on the box, playing elevated",
    "let the boys know I'm at the corner, waiting for a peek",
    "tell my team I'm off-angle by the crates, don't call my position",
    "inform them I'm pushing B main right now",
    "tell them I'm holding down the link, nobody rotates",
    "let my team know I'm at the lobby, going for an early pick",
    "tell the team I'm at the cubby left, peeking on your flash",
    "inform them I'm at bottom mid, taking space",
    "tell them I'm crossing through the smoke they put up",
    "let my team know I took the rope ascender, I'm elevated now",
    "tell the team I'm in Viper's wall crossing safely",
    "inform them I'm planting right now, cover the angles",
    "tell them I've taken the off-angle at short, don't shoot my position",
    "let the squad know I'm clearing the cubby, almost done",
    "tell my team I'm back-siting, playing for retake if they push",
    "inform the team I'm at B danger, holding the outer edge",
    "tell them I'm at the catwalk, watching mid from up here",
    "let them know I'm flanking through mid right now",
    "tell the team I just took library, rotating from here",
    "inform them I'm somewhere deep, don't rotate to me, I'll make plays",
    "tell them I'm at A security, popping over to hold main",
    "let my team know I'm at A bridge, careful about calling my spot",
    "tell the team I'm in the corner they never check at B nest",

    # === ALIVE / DEAD STATUS ===
    "tell them I'm still alive in the clutch",
    "let my team know I'm the last one up, don't talk",
    "tell them I died, I'm spectating",
    "inform the team I got killed, traded though",
    "tell them I died to a wallbang, I have no idea where it came from",
    "let the squad know I'm down but I made it hurt",
    "tell my team I'm dead but not dead, I'm coming back with Not Dead Yet",
    "inform them I died in the smoke, I went for it",
    "tell the team I survived somehow, still in it",
    "let them know I'm not tradeable this round, I'm on flank",
    "tell my team I'm going to die in three seconds but I'm marking his position",
    "inform them I traded and died, the site is 4v4 now",
    "tell them I died holding the angle, I never saw him",
    "let the boys know I'm still standing after that 1v2",
    "tell them I killed two and I'm alive with 18 HP",
    "inform the team I just wiped two entries and I'm at 40, let's execute",
    "tell them I'm the clutch player this round, go silent please",

    # === ROLE / ASSIGNMENT ===
    "tell them I'll entry this round",
    "let my team know I'm going in first, use me",
    "tell the team I'm playing lurk this round",
    "inform them I'm the anchor on A, don't call a rotate unless you're sure",
    "tell them I'm playing support this round, I'll flash everyone in",
    "let the squad know I'm going IGL this round, follow my calls",
    "tell my team I'm playing for picks, spread out",
    "inform the team I'm doing a ninja defuse, go silent",
    "tell them I'm tapping the spike to bait, don't give it away",
    "let them know I'm going for the fake defuse, I need someone to trade",
    "tell the team I'm planting and anchoring, hold CT",
    "inform them I'm the information agent this round, my job is eyes not frags",
    "tell them I'll be the second entry, I'm playing off the entry fragger",
    "let my team know I'm on flank watch, something coming from spawn",
    "tell the team I'm going to initiate the execute, coordinate with me",
    "inform them I'm going aggro opener, play off my contact",
    "tell them I'm playing slow this round, drawing their utility before we commit",
    "let my team know I'm running the lurk through mid, watch for my flank",
    "tell the team I'm saving this round, keeping the rifle alive",
    "inform them I'm decoy-ing toward A so you can hit B",

    # === ABILITY USAGE ANNOUNCEMENTS ===
    "tell them I'm dashing in, play off the smoke",
    "let my team know I'm flashing in three seconds, look away",
    "tell the team I'm throwing the recon now, wait for the scan",
    "inform them I'm dropping the wall, cross in the next two seconds",
    "tell them I'm smoking the two chokes, execute on three",
    "let the boys know I'm launching the missiles at their default, 3 seconds",
    "tell my team I'm activating the Lockdown, protect the device",
    "inform the team I'm launching the orbital, nobody push until it's done",
    "tell them I'm going in my ult, I'm invisible and scouting",
    "let them know I'm activating Not Dead Yet, I need one kill to stay",
    "tell the team I'm ulting Phoenix, play crossfire if I respawn",
    "inform them I'm running Empress, I'm getting chain kills right now",
    "tell them I'm using Run It Back, kill me fast or I'm back at full HP",
    "let my team know I'm setting up Viper's Pit, plant in the cloud",
    "tell the team I'm sending Thrash in, I need someone to follow up when they're detained",
    "inform them I'm launching the Showstopper, nobody push mid yet",
    "tell them I'm sending the Seekers, their positions are getting marked",
    "let the boys know I'm ulting with Kill Contract, I'm pulling their Jett into the arena",
    "tell my team I'm throwing Nightfall, 3 enemies tagged",
    "inform the team I'm throwing the Nova Pulse at their main entrance, push after the stun",
    "tell them my Convergent Paths is expanding, I have the speed boost, playing off it",
    "let them know I just used Armageddon down B site, clear it out",
    "tell the team I'm activating the Null/cmd, revive me if I go down",
    "inform them I'm setting up the Rolling Thunder, move out of the cone",
    "tell them I'm sending Reckoning through the choke, push behind the wave",
    "let my team know I'm throwing the seize at their plant position",
    "tell the team I'm dragging the tiger in, follow when it concusses",
    "inform them I'm droning mid right now, protect my body",
    "tell them I'm using my From the Shadows ult to teleport behind them",
    "let the squad know I'm dropping my orbital on spike right now",

    # === HEALTH RECOVERY / HEALING ===
    "tell them I'm healing up, give me two seconds",
    "let my team know I took Sage's heal, I'm back at 75",
    "tell the team I'm standing in my Blaze wall healing, don't push yet",
    "inform them I absorbed the life force off that kill, I'm at 150 HP with overheal",
    "tell them I used Pick-Me-Up, I'm overhealed, pushing now",
    "let my team know I need a heal from Sage before we entry",
    "tell them I'm healing myself in the Hot Hands, stall a second",
    "inform the team I picked up an orb and healed, back to 100",
    "tell them I self-healed with the healing orb, I'm at 60 now",
    "let the squad know I need Skye to Regrowth me before I push",

    # === CAPABILITY ANNOUNCEMENTS ===
    "tell them I can plant through smoke, send Wingman",
    "let my team know I can solo this B hold",
    "tell the team I'm good for an aggro push through mid",
    "inform them I can fake the teleport to bait their rotate",
    "tell them I can't rush, I'm too low",
    "let my team know I'm capable of winning this 1v1, just stay back",
    "tell the team I can hold A alone, go take B",
    "inform them I can't take a duel right now, no armor",
    "tell them I'm in a position to trade but not entry",
    "let the boys know I can ninja defuse if they're all holding the smoke",
    "tell my team I'm good to entry if we have flashes",
    "inform the team I can't go to long right now, they have the Op",
    "tell them I can bait the rotation with my footsteps, do it on my call",
    "let them know I'm ready to entry on your smoke, just say when",
    "tell the team I'm good for a jiggle peek to bait info",

    # === EQUIPMENT / GEAR COMBINATIONS ===
    "tell them I went full buy this round, rifle heavy armor all util",
    "let my team know I'm on a half buy, Spectre and light armor",
    "tell the team I bought an Operator but skipped heavy armor, glass cannon",
    "inform them I forced this round, everything I had went into a rifle and light shield",
    "tell them I have the Vandal but no armor, I'll play passive",
    "let the squad know I went ghost and armor on this eco, playing pistol",
    "tell my team I have the Guardian and heavy armor, hunting long angles",
    "inform the team I have the Outlaw as a budget sniper this round",
    "tell them I bought an Ares for spray through smoke, full send",
    "let them know I'm all in on abilities this round, barely any gun money left",
    "tell the team I have the Frenzy and a Judge, close-range chaos this round",
    "inform them I have the Phantom, heavy armor, all abilities, clean buy",
    "tell them I'm going Vandal this round even if we eco together",
    "let my team know I bought the Stinger on this bonus round",
    "tell the team I grabbed the Bucky for the corridor on eco, expect close range",

    # === POSITIONING INTENT ===
    "tell them I'm going to take mid control this round",
    "let my team know I'll be holding heaven today",
    "tell the team I'm playing the off-angle by the box, don't call me",
    "inform them I'm going to lurk through B and wait for the flank opportunity",
    "tell them I'm anchoring this site while you fake the other",
    "let the squad know I'm going to play passive at CT this round",
    "tell my team I want to contest the early peek at top of mid",
    "inform the team I'm dropping down short for an aggressive pick",
    "tell them I'm playing back site this round so I can info the rotation",
    "let them know I'll hold link while they push through A",
    "tell the team I'm going to fast peek mid window and get out",
    "inform them I'm staying at lobby, I'll be the lurk today",
    "tell them I'm camping the off-angle by the cubby, they never check there",
    "let my team know I'm taking the ramp for elevation",
    "tell the team I'm setting up at the corner they always rush through",

    # === ROUND PHASE AWARENESS ===
    "tell them I'm planting now, hold spike for 40 seconds",
    "let my team know I tapped the spike, fake defuse in progress",
    "tell the team I'm defusing, cover all angles",
    "inform them I'm going ninja on the spike, keep them busy",
    "tell them I have 10 seconds to defuse and two enemies left, I'm going for it",
    "let the squad know I'm going to let the spike blow, not worth dying for",
    "tell my team the spike is at 20 seconds, I can't make it in time",
    "inform the team I planted at default, no time for the safe position",
    "tell them the round timer is at 15, they have to push now",
    "let them know I'm stalling time here, spike ticks down in 8",
    "tell the team I'm playing for time, don't fight them",
    "inform them I got the spike down on A, come defend it",

    # === FIRST-PERSON CAPABILITY / SKILL READS ===
    "tell them I can handle this 1v2, I've done it before",
    "let my team know I'm cracked right now, hot streak, let me entry",
    "tell the team I'm in a bad spot mechanically tonight, play around me",
    "inform them I'm not feeling the duels this round, let someone else entry",
    "tell them I'm tilting from that last round, I need a moment to reset",
    "let the squad know my aim is locked in today, give me first contact",
    "tell my team I whiffed that shot, I know, please don't say anything",
    "inform the team I'm playing off their patterns, I know their default",
    "tell them I know where he camps every round, let me call it",
    "let them know I've been burned by that corner three times, I'm not dry peeking it",

    # === SELF-DEPRECATING / ADMISSIONS ===
    "tell them I threw that round, my bad",
    "let my team know I baited the entry, I'll do better",
    "tell the team I missed a free kill at close range, I deserve the roast",
    "inform them I got tilted last round, I'm calming down now",
    "tell them I panicked and used ult way too early",
    "let the squad know I ran the wrong way on the rotation, completely my fault",
    "tell my team I should have traded but I hesitated",
    "inform the team I died to a prefire I should have expected, I'll prefire it back",
    "tell them I don't know how I survived that, pure luck",
    "let them know I'm playing like I'm Bronze right now but I'll course correct",

    # === INTENT TO ACT / NEXT ACTION ===
    "tell them I'm going to peek long in five seconds",
    "let my team know I'll be taking the first fight at elbow",
    "tell the team I'm about to entry on your flash",
    "inform them I'm going in the next time they poke out",
    "tell them I'm going to bait the corner and swing back on their shot",
    "let the squad know I'm going to run the aggro push to waste their utility",
    "tell my team I'll shoulder peek to get his position and then pass to someone else",
    "inform the team I'm going to hard swing the door, cover me",
    "tell them I'm taking a jiggle peek at B main to bait the Op shot",
    "let them know I'm going to crossfire with whoever pushes left",
    "tell the team I'm going deep to flank while you push through smokes",
    "inform them I'll rotate to B after I confirm there's nothing on A",
    "tell them I'm going to double-tap the spike before I commit to the defuse",
    "let my team know I'm about to open the round with an aggro mid peek",
    "tell the team I'm setting my angle before the smoke fades",
    "inform them I'm going to cut through mid and come to site from link",
    "tell them I'm going to Gatecrash teleport to the off-angle they don't expect",
    "let the squad know I'll snap flash the corner before I push through",

    # === COMPOUND SELF STATUS (MULTIPLE FACTORS) ===
    "tell them I'm at 40 HP no armor but I have ult, let me use it",
    "let my team know I'm full health full armor but no util bought",
    "tell the team I'm one shot, no armor, no ult, and lost the rifle, I'm useless this round",
    "inform them I'm 100 HP, heavy shield, all abilities loaded, Op in hand, prime",
    "tell them I have the Op and no armor on a half buy, gambling",
    "let the squad know I'm low health with ult up, let me bait one more kill",
    "tell my team I'm full buy but no ult this round, playing smart",
    "inform the team I'm on eco but the Empress is ready, I just need one kill",
    "tell them I'm at 60 HP with ult, I can go in if someone flashes for me",
    "let them know I have the rifle, light armor, two flashes, and ult, ready to entry",
    "tell the team I'm clutch player, 1v3, 30 HP, no ult, but I know their positions",
    "inform them I have full util but I'm at 10 HP, I'll play for info not frags",
    "tell them I'm on the Vandal with 100 HP, heavy armor, no ult, I'm just a rifle",
    "let my team know I'm an Op player with full armor but no util, playing passive",
    "tell the team I just got Sage rez'd so I'm at full HP and my ult is preserved",

    # === COOL REGISTER VARIANTS (REGIONAL SLANG, CASUAL, CLIPPED) ===
    "yo tell them I'm low-key one shot right now",
    "let the boys know I'm cracked out on a killing spree, feed me",
    "yo tell the squad my ult is popped and ready to go",
    "tell them straight up I have no gun this round, eco fragger mode",
    "let my team know I'm vibing at 100 HP, ready to throw hands",
    "tell them I'm lowkey just spectating from this corner angle, I'll info",
    "yo let my team know I have the blade storm charged, op replacement incoming",
    "tell the boys I'm all in this round, full send no fear",
    "let them know I have 0 ult and 0 util, I am literally just a gun this round",
    "tell my team ngl I'm tilting but ult is ready so let me cook",
    "tell them fr I got this clutch, just everyone chill",
    "let them know deadass I have no armor but I have all my flashes, so it evens out",
    "yo tell the team I smoked myself by accident and now I'm at 30 from decay",
    "let the boys know I'm on a full eco Frenzy rush, just vibes",
    "tell my team bro I stepped in the razorvine, I'm at 20, not going aggressive",

    # === SITUATIONAL SELF REPORTS ===
    "tell them I got seize'd and they walked on me, I'm dead",
    "let my team know I got suppressed by Kayo's knife, no util for 8 seconds",
    "tell the team I got nearsighted by their Skye, totally blind right now",
    "inform them I'm concussed from Breach, can't aim straight, wait for me",
    "tell them I got Netted by Deadlock, I'm crouched and trapped",
    "let the squad know I walked into decay and I'm at 10, do not push off me",
    "tell my team I got dinked in the head but I'm alive, he's at 150 HP minimum",
    "inform the team I hit him for 80, he's one shot at B main",
    "tell them I tagged the Jett 55, she has no armor anymore",
    "let them know I traded the entry, I'm 3v3 now with 60 HP",
    "tell the team I took a Boom Bot hit, 40 HP and moving carefully",
    "inform them I got hit by the Guided Salvo, took a tick, at 50 now",
    "tell them I got blind-sided by Yoru, missed all my shots, he's still full",
    "let the squad know I ate the Orbital Strike and somehow lived, I'm at 5",
    "tell my team I'm detained by Killjoy Lockdown, I can't move or shoot",
    "inform the team I got tethered by Fade, I can't leave this spot",
    "tell them I got hit with the Undercut, I'm fragile, double damage window right now",
    "let my team know I stepped on their alarmbot, I'm Vulnerable",
    "tell the team I walked into the nanoswarm, took heavy damage, I'm at 15",
    "inform them I pulled the Spike from the wingman, I'm planting manually now",
    "tell them I got hit by the Reckoning wave, I'm nearsighted and slowed",
    "let them know I got hit by a prowler, I can barely see anything",
    "tell the team I stepped through Viper's wall to cross, at 80 from decay tick",
    "inform them I'm being tracked by the terror trail, they know where I am",
    "tell them I fell off the edge in Abyss, I'm dead, that was embarrassing",
    "let the squad know I walked through the flooded section on Corrode running, they heard me",

    # === TEMPO / URGENCY VARIANTS ===
    "tell my team I'm ready right now, let's go",
    "let them know I need 3 more seconds and I'll be in position",
    "tell the team I'm close, hold the execute one second",
    "inform them I'm sprinting there now, 10 seconds out",
    "tell them I'm late, start without me if you have to",
    "let the squad know I'm out of position, wait for me to reset before the execute",
    "tell my team I have time to ult before the timer expires",
    "inform the team I can make it to the defuse in time, give me 5 seconds",
    "tell them I'm rushing, I'll be there before the smokes fade",
    "let them know I'm close to spawn, I won't make the rotation in time this round",
    "tell the team I need to take the rope ascender, it's faster, wait 4 seconds",
    "inform them I'm shifting walk through the water, slower but silent",
    "tell them I'm burning time on purpose to drain the clock",
    "let my team know I have enough time for a safe plant and a defuse wait",
    "tell the team I won't make it to B in time, anchor A and I'll join after the pick",

    # === EXPRESSING SELF-ASSESSMENT / OPINIONS ===
    "tell my team I think I can solo hold this site for another 20 seconds",
    "let them know I believe there's someone lurking the flank, I'm watching it",
    "tell the team I'm confident he's in the cubby, let me peek first",
    "inform them I'm not sure about pushing that angle without a flash",
    "tell them I think I can win this 1v1 if someone doesn't interfere",
    "let the squad know I know his spot, let me handle it",
    "tell my team I'm not dying for nothing here, I'll save the rifle",
    "inform the team I think we should reset and go next, I'm not feeling this push",
    "tell them I believe the retake is winnable if we coordinate right now",
    "let them know I don't want to take that fight without utility",
    "tell the team I feel like they're stacking A every round, let's hit B",
    "inform them I'm pretty sure their Jett has her dash back, be careful",
    "tell them I don't think I can win a 1v3 here, I'll info and exit",
    "let my team know I think their Killjoy set up nanos on the spike",
    "tell the team I feel good about this clutch, trust me",

    # === EXTENDED HEALTH / HP NUANCES ===
    "tell them I got tagged by the recon dart, they can see me through the wall",
    "let my team know I took 12 from their snakebite crossing, at 88 now",
    "tell the team I took the full Aftershock through the wall, I'm at 20 HP, don't push off me",
    "inform them I burned my Devour already, no more self-heal this round",
    "tell them I'm overhealed at 150 from Empress, I'm going in",
    "let my team know I picked up the orb, back at a hundred",
    "tell the team I stood in Phoenix's wall to heal, I'm at 65 now",
    "inform them I managed to Devour off that kill, I'm back at 90",
    "tell them I took the Mosh Pit direct hit, at 25, don't entry on me yet",
    "let the squad know I stepped in their Viper acid, one foot out and I was at 30",
    "tell my team I barely dodged the Hunter's Fury beams, at 40, still moving",
    "inform the team I ate a full Showstopper blast radius, I'm dead but that was impressive",
    "tell them I'm 100 HP and haven't taken a single bullet this round yet",
    "let them know I took the Shock Bolt to the knee, at 45",
    "tell the team I sat in the KAY/O frag too long, taking heavy tick damage, at 10",
    "inform them I absorbed that Orbital Strike and survived somehow, at 5 HP",
    "tell them I tanked the Gravity Well explosion, Vulnerable right now, double damage window",
    "let my team know I got hit by a Prowler, I'm nearsighted and at 60",
    "tell the team I'm regenerating regen shield right now, give me 4 seconds",
    "inform them I took the Seize decay to 1 HP and barely survived, don't touch me",

    # === EXTENDED ULTIMATE VARIANTS ===
    "tell them my blades are out, Blade Storm activated, I have perfect accuracy",
    "let my team know I activated Empress, I'm chain-killing, feed me enemies",
    "tell the team I have Run It Back active, kill me fast or I respawn at 100",
    "inform them Dimensional Drift is up, I'm invisible and scouting ahead",
    "tell them I'm about to pop Kill Contract on their best player",
    "let my team know my Overdrive is charged, I'm going to beam everyone",
    "tell the team I have Convergent Paths up, I'll zone them with the hinder beam",
    "inform them my Hunter's Fury is ready, three beams, stay out of the line",
    "tell them I have Rolling Thunder ready, 9 point ult, I'll earthquake the site",
    "let the squad know I can use Nightfall to tag all three of them before the push",
    "tell my team my NULL/cmd is charged, if I go down revive me",
    "inform the team I have Thrash ready, I'll pilot her into the site and detain",
    "tell them I have Armageddon up, 9 point ult, give me a target line",
    "let them know I have Seekers charged, three trackers on their positions",
    "tell the team Lockdown is set, 13 second windup, someone protect the device",
    "inform them Steel Garden is ready, when they rush I jam their primaries",
    "tell them Evolution is active, I'm immune to everything, going in",
    "let my team know I have Annihilation up, I'll cocoon someone on retake",
    "tell the team I have Cosmic Divide ready, I'll cut the site on execute",
    "inform them From the Shadows is charged, I'll teleport to their flank",
    "tell them I have Viper's Pit up, I'll anchor the bomb site in the toxic cloud",
    "let the squad know I have Neural Theft charged, use it on any body they leave behind",
    "tell my team Resurrection is ready, call who you want rezzed",
    "inform the team Not Dead Yet is charged, if I die I'm coming back on one condition",
    "tell them I have tour de force ready, custom sniper out, slow fields on kills",
    "let them know I'm using the Reckoning wave into the chokepoint, push behind it",
    "tell the team my Bassquake ult is charged, on the call",
    "inform them I have the Orbital Strike queued, just need a good position",

    # === EXTENDED ECONOMY DEPTH ===
    "tell them I have exactly 3,900 credits, bare minimum full buy",
    "let my team know I have 5,700 credits, buying Op and full armor and everything",
    "tell the team I'm at 2,400 credits after the force, barely a light buy",
    "inform them I have the loss bonus stacking, second consecutive loss means 2,400 for me",
    "tell them I'm at the third consecutive loss tier, 2,900 loss bonus this round",
    "let the squad know I capped at 9,000 credits, I need to spend this round",
    "tell my team I picked up the enemy's Operator after the kill, I'm not buying a gun",
    "inform the team I got a thrifty round win, we spent way less than them",
    "tell them I spent nothing this round, full eco, zero credits spent",
    "let them know the spike plant bonus gave me an extra 300, I can afford the Op now",
    "tell the team the kill credit from last round pushed me to 4,200, I'm buying",
    "inform them I can drop you the Guardian, I have enough for a rifle myself",
    "tell them I'm on a pistol round budget, only 800 to start",
    "let my team know the bonus round is here, I'm buying Spectre and light armor",
    "tell the team I'm buying the Bandit pistol this eco round, the 600 credit one-tapper",
    "inform them I have Outlaw money, 2,400 credits, going for the budget sniper",
    "tell them I'm at 800 and buying the Frenzy for run-and-gun on this eco",
    "let the squad know I have exactly one rifle worth of credits, nothing extra",
    "tell my team I'm going Shorty shotgun on this full save, pure aggression at close range",
    "inform the team I'll take the ghost and armor on this pistol round, most versatile option",

    # === WEAPON NUANCES ===
    "tell them I have the Vandal, AK mode, no damage drop at range",
    "let my team know I'm on the Phantom this round, silenced, no tracers",
    "tell the team I went Guardian for this half-buy, one-tap machine",
    "inform them I bought the Judge shotgun, eco chaos at close range",
    "tell them I grabbed an Odin, I'm going to spray through the smokes",
    "let the squad know I picked up a dropped Phantom from the enemy kill",
    "tell my team I have the Outlaw, semi-auto dual-barrel, body shots chunk hard",
    "inform the team I'm going knife-run to site for speed, equipping right before the peek",
    "tell them I bought three extra headhunter bullets, I have 8 rounds in the pistol",
    "let them know I'm on the Stinger on this bonus, close-range burst fire",
    "tell the team I have the Bucky for the bathroom corner, gonna one-tap close",
    "inform them I'm running the Marshal as a budget sniper, 950 credits",
    "tell them I have the classic and I'm going to run-and-gun these eco players",
    "let my team know I bought 6 headhunter bullets total, conserving ammo",
    "tell the team I picked up the Sheriff from that kill, back in business",

    # === GRANULAR ABILITY TRACKING ===
    "tell them both my Cloudburst smokes are gone, I have one Updraft left",
    "let my team know I burned both Curveballs flashing through main",
    "tell the team I used one Blast Pack to get here, one satchel remaining",
    "inform them I used my Regrowth on the team heal, pool is almost empty",
    "tell them I have both Slow Orbs intact, didn't buy them until now",
    "let the squad know I used my second Trapwire, I'm down to the camera only",
    "tell my team I have both Cyber Cages up, I'll drop one for the fake",
    "inform the team I burned my Haunt but got the reveal, two prowlers left",
    "tell them I have both FLASH/drive grenades, two flashes for the execute",
    "let them know I used one ZERO/point already, suppression is on cooldown 40 seconds",
    "tell the team I have both Mosh Pit charges but I'm saving both for post-plant",
    "inform them I used my first Relay Bolt on mid, one stun left",
    "tell them I have two Shock Bolt charges and a full-charged Recon Bolt ready",
    "let my team know I've already placed both Nanoswarms, they're covert at default",
    "tell the team both Alarmbot and turret are up, two layers of defense on flank",
    "inform them I used both Fakeout echoes already, no more fake footsteps",
    "tell them I have both Blindside flashes and the Gatecrash tether up",
    "let the squad know I burned one High Tide wall already, one more available",
    "tell my team the Storm Surge is on cooldown, 12 seconds remaining",
    "inform the team I have the second Guided Salvo missile ready, 150 credits well spent",
    "tell them I set up both Razorvines at the retake entry, they're covert",
    "let them know I placed one Shear already, it's waiting for them to trigger",
    "tell the team both Crosscut vortexes are down, I can TP to either",
    "inform them I burned my Chokehold trap already, no tether utility left this round",
    "tell them I have my Interceptor active, their utility is getting blocked",
    "let my team know the Stim Beacon is at default plant, stand in it when we push",
    "tell the team both Incendiary shots are ready, molly on spike and another for entry",
    "inform them I'm out of Sky Smoke charges, smokes are empty",
    "tell them I have two extra Sky Smoke charges I bought, total three smokes available",
    "let the squad know my Paranoia is up and I'll throw it through the wall before we go",
    "tell my team I have two Shrouded Step teleports, I'll step into the smoke from two angles",
    "inform the team the Spycam dart is loaded and the cam is watching B main",
    "tell them I have zero Trapwires left, Cypher is running naked this round",

    # === FLANKING AND MOVEMENT PLAYS ===
    "tell them I'm flanking through their side, don't rotate away from me",
    "let my team know I got a pick on the flank, I'm coming back through mid",
    "tell the team I need to cut back to spawn, I'm out of position",
    "inform them I'm boost-jumping using Blast Packs to get to the elevated position",
    "tell them I Updrafted to the high ground, I have the angle advantage",
    "let the squad know I'm using the Refract beacon to pull back after the peek",
    "tell my team I dashed into the smoke and took the off-angle",
    "inform the team I teleported to the position they never check",
    "tell them I fake-teleported to bait their rotation, I'm still here",
    "let them know I'm running at sprint speed toward mid, I'll beat them there",
    "tell the team I slid into the site entry, caught them off guard",
    "inform them I'm using a rope ascender to get elevation, give me 3 seconds",
    "tell them I walked through the water section slow, they didn't hear me",
    "let my team know I fell off the bridge, you didn't see that",
    "tell the team I jumped the gap to the outer ledge, holding the unusual angle now",

    # === PLAYING OFF TEAM EVENTS ===
    "tell them I'm pushing when the KAY/O knife lands, be ready",
    "let my team know I'll entry the second the smoke goes up",
    "tell the team I'm going in right after the Rolling Thunder",
    "inform them I'll swing the corner as soon as they're concussed from Breach",
    "tell them I'm timing my dash with the flash, play off my entry",
    "let the squad know I'm pushing into the Lockdown detain window",
    "tell my team I'll Gatecrash in when the Nightfall hits",
    "inform the team I'll use my kill contract when their best duelist shows",
    "tell them I'll activate the pit the second the spike is planted",
    "let them know I'll use the orbital when the defuse starts",
    "tell the team I'll pop the Nova Pulse the second you enter the lobby",
    "inform them I'm ulting when you commit, coordinate the push with my Hunters Fury",
    "tell them I'm going to use the Steel Garden the second they start the retake",
    "let my team know I'll stim the team at plant before the defuse window",
    "tell the team I'm activating Cosmic Divide the moment you say go",

    # === SELF-STATUS WITH AGENT-SPECIFIC CONTEXT ===
    "tell them I'm Jett with no dash, I'm a sitting duck right now",
    "let my team know I'm Reyna with no soul orbs, I can't heal or dismiss",
    "tell the team I'm Reyna in Empress right now, feeding me more enemies",
    "inform them I'm Phoenix and my Run It Back just expired, I didn't get the kill",
    "tell them I'm Neon and I can't slide anymore, used it on the entry",
    "let the squad know I'm Yoru and my tether is down B main, I can TP or fake",
    "tell my team I'm Waylay with my beacon placed, I'll recall if the peek goes bad",
    "inform the team I'm Iso with Double Tap shield active, I can absorb one hit",
    "tell them I'm Raze with both satchels and a fresh grenade, fully loaded",
    "let them know I'm Viper outside my own pit, 8 second countdown before it dissolves",
    "tell the team I'm Omen and both smokes are on cooldown, 30 seconds until they recharge",
    "inform them I'm Clove and I died but I'm smoking the site from the grave",
    "tell them I'm Clove and Not Dead Yet triggered, I need one kill in 10 seconds",
    "let my team know I'm Killjoy and Lockdown is out, don't let them break it",
    "tell the team I'm Sage with no wall this round, I bought slow orbs instead",
    "inform them I'm Chamber and my Rendezvous anchor is placed, I'll TP to it if I need to",
    "tell them I'm Cypher and the cam was destroyed, respawning in 45 seconds",
    "let the squad know I'm Veto with Evolution active, I'm immune to everything",
    "tell my team I'm Gekko and I reclaimed my Dizzy, second flash available after cooldown",
    "inform the team I'm Sova with all three Fury beams loaded, where do you want them",
    "tell them I'm Skye with both hawks recharged, two flashes ready for the execute",
    "let them know I'm KAY/O and I went down during Null, someone revive me",
    "tell the team I'm Fade and all three enemies got trailed, sending prowlers",
    "inform them I'm Breach with Rolling Thunder charged, point me at the site",
    "tell them I'm Tejo and my Armageddon is primed, give me the strike coordinates",
    "let my team know I'm Brimstone with all three smokes loaded, ready to execute",
    "tell the team I'm Astra with stars placed at all three positions, ready to activate anything",
    "inform them I'm Harbor and my Cove shield is at 680 HP, plant behind it",
    "tell them I'm Deadlock and the Annihilation cocoon is 600 HP, shoot it to free him",
    "let the squad know I'm Vyse and Steel Garden jammed their primaries, push now",

    # === NEGATIVE SELF-REPORTS (must NOT relay) - no wait, this pack is relay only ===
    # (intentionally omitted - all above are genuine relay commands)

    # === LATE-ROUND CLUTCH SPECIFIC ===
    "tell them I'm in a 1v2 clutch and I know where both are",
    "let the team know I'm 1v1 last round last pistol round, let me cook",
    "tell them I'm the clutch player, absolutely no comms please",
    "inform them I planted the spike, 1v3, playing for detonation now",
    "tell them I'm holding two angles at once and I need someone to be quiet",
    "let the squad know I defused with 0.1 seconds left, I know",
    "tell my team I tapped the spike twice to bait one out",
    "inform the team I faked the defuse and got the peek, now 1v1",
    "tell them I won the clutch, moving to buy phase",
    "let them know I dropped the clutch, I let the spike explode by mistake",
    "tell the team I'm playing for time in the 1v3, just need the spike to go off",
    "inform them I'm going for the ninja, if they don't find me we win",
    "tell them I'm behind them in the 1v3, about to start the domino",
    "let my team know I'm in a 1v1 with the entry fragger and I have ult",
    "tell the team the 1v2 is on me, I have 20 HP and both their positions",

    # === SELF-STATUS IN DIFFERENT REGISTERS (stream / casual / pro) ===
    "mate tell them I'm absolutely cooked, 5 HP and no armor",
    "bruv let my team know I barely made it to the corner, at 12",
    "yo let the squad know I'm GOATED right now, top fragging and ult is up",
    "tell them bro I have the Op and I'm holding B long forever",
    "let them know gang I am fully built, rifle shield util ult, we're going",
    "fam tell my team I got flanked and I'm dead, their lurker is at CT",
    "tell them literally nobody can stop me right now, Empress chain-kill in progress",
    "let the boys know I have the eco rifle and I'm fighting like I have a Vandal",
    "tell them nah I'm good, I recovered, back at 75 and playing aggressive",
    "let my team know I'm done tilting, resetting, ready to go",
    "tell them I got wrecked on that peek but I tagged him 60 at least",
    "let my squad know honestly I don't know how I survived that, but I'm here",
    "tell them real talk I have no ult and no util, I'm just a gun today",
    "let them know I promise I know his spot, let me handle this 1v1",
    "tell my team I need healing or I'm not going anywhere near that fight",
    "inform them straight up my aim is off today, let someone else entry for a bit",
    "tell them frfr I have the Vandal and heavy armor and I'm ready to top frag",
    "let the squad know on god I will not peek that angle dry again",
    "tell my team swear to god I had him, the game just decided otherwise",
    "inform them for real I have both flashes and I'll entry if you need me to",

    # === REMAINING VARIETY: MIXED MULTI-FACTOR SCENARIOS ===
    "tell them I have ult, full HP, and the Op, someone put a smoke at CT so I can peek",
    "let my team know I died but I hit him for 90, he's one shot at B site right now",
    "tell the team I got the entry kill and I'm alive at 30, trade if they push",
    "inform them I'm pushing off the Breach stun, someone follow behind me",
    "tell them I dashed to the off-angle, play when I call contact",
    "let the squad know I'm sitting in the cage listening for footsteps",
    "tell my team I have no armor but two Op shots, playing carefully",
    "inform the team I bought a Regen Shield instead of heavy, it'll kick in after I take a hit",
    "tell them I activated the Gravity Well, they're all pulled in and Vulnerable",
    "let them know I've been baiting this angle for 20 seconds, nobody's coming, giving up the spot",
    "tell the team I'm going to sacrifice myself to burn their utility before the execute",
    "inform them I hit his legs twice, he's limping at 26 HP near A main",
    "tell them I'm pre-firing the corner every time they peek, locking down mid short",
    "let my team know I have both shock darts and will lineup post-plant from here",
    "tell the team I placed the stim at the plant point, stand in the blue circle when you arrive",
    "inform them my paranoia goes through the wall on their right side, close your eyes on the left",
    "tell them I crouch-sprayed the entire corner and missed, I deserve the clip",
    "let the squad know I'm going to wallbang through this surface, tell me if he's still there",
    "tell my team I just prefire'd that corner and got a free kill, pushing off the kill",
    "inform the team I'm going to shoulder peek B main once and then call what I see",
    "tell them I used the jiggle peek to bait his Op shot, he missed, now I'm peeking for real",
    "let them know I exit-fragged their lurker on the way out, taking the rifle",
    "tell the team I hit him for a dink, he's so low he has to play passive",
    "inform them I have a collateral angle lined up through this wall, two of them are stacked",
    "tell them I have the knife out running to rotate faster, equipping rifle in 3",
    "let my team know I'm going to let them plant and then come from behind",
    "tell the team I'm holding the angle from deep back-site, they don't know I'm this far back",
    "inform them I took the high box position on A site, I have the angle advantage",
    "tell them I'm playing the long peek from CT, Operator in hand",
    "let the squad know I shifted my position left so the off-angle is covered",
    "tell my team I'm going to rotate but walking through the water part on Corrode, give me 5",
    "inform the team I got knocked off the rope ascender by gunfire, back on the ground",
    "tell them I'm at A Secret on Abyss, outer ledge, weird angle they won't expect",
    "let them know I'm playing B Nest on Abyss, post-plant hold from the flanking spot",
    "tell the team I crossed A Bridge on Abyss, barely didn't fall off the edge",
    "inform them I took the death drop line to B Danger on Abyss, high risk angle",
    "tell them I'm at A Tower on Abyss, accessed via the rope ascender from site",
    "let my team know I went through the vent door into A Tower, door's broken now",
    "tell the team I'm at A Crane on Corrode, I have the high ground on site",
    "inform them I'm at B Arch on Corrode, primary defender entryway, holding tight",
    "tell them I'm at B Tower on Corrode, elevated position watching their B main approach",
    "let the squad know I have the mid window angle on Corrode, long line of sight",
    "tell my team I'm at the Mid Stairs on Corrode, top of the elevation, I can pivot either site",
    "inform the team I have Mid Library on Abyss, I control the B rotation from here",
    "tell them I'm at Mid Catwalk on Abyss looking at the A Vent door, watching for a push",
    "let them know I took the Mid Bend position after the rope ascender, in their flank path",
    "tell the team I'm pushing through A Yard on Corrode, taking space before the execute",
    "inform them I'm holding A Pocket on Corrode, off-angle they forget about",
    "tell them I'm at A Link on Corrode, the contested power position between mid and site",
    "let my team know I'm pushing from B Lobby on Corrode to B Elbow fast",
    "tell the team I'm at B Link on Corrode, power position locked down",
    "inform them I have the Cobby angle on Abyss, watching anyone pushing A Main",
    "tell them I cleared A Security on Abyss and I'm pushing into A Main from their side",
    "let the squad know I'm at the Mid Bottom on Abyss, lower lane, void gap to my right",
    "tell my team I'm holding Mid Top on Abyss and I have eyes on anyone taking Catwalk",
]


