ITEMS = [
    # --- BASIC CHILL / RELAX DIRECTIVES ---
    "tell them to relax",
    "tell the team to chill out",
    "let everyone know to calm down",
    "tell them to take a breath",
    "tell the guys to breathe",
    "let the team know it's fine",
    "tell them we're good",
    "tell everyone to stay calm",
    "tell them to keep it cool",
    "tell the team to settle down",
    "tell them it's just one round",
    "tell them to stay composed",
    "tell everyone it's not over",
    "tell them to stay level-headed",
    "let the squad know we're alright",
    "tell them to chill, we're still in it",
    "tell them there's no need to panic",
    "tell them to breathe and reset",
    "tell the team to slow it down mentally",
    "tell them to keep their heads",

    # --- STOP FLAMING / BLAMING DIRECTIVES ---
    "tell them to stop flaming each other",
    "tell the team no more blame this round",
    "let them know the blaming needs to stop",
    "tell everyone to cut out the toxicity",
    "tell them not to point fingers right now",
    "tell the team to stop throwing shade",
    "tell them there's no time for the blame game",
    "tell everyone to stop going at each other",
    "let the team know the flaming isn't helping",
    "tell them we're a team, stop fighting",
    "tell them to quit arguing and focus",
    "tell the guys to save the drama for after the match",
    "tell them to stop calling each other out mid-round",
    "let them know attacking teammates is costing us rounds",
    "tell them the in-fighting stops now",
    "tell them to stop screaming at each other and play",
    "let them know yelling at teammates is bad comms",
    "tell the team we need clean comms not drama",
    "tell them to drop it and focus on the next round",
    "tell everyone to move past it",

    # --- STOP TILTING DIRECTIVES ---
    "tell them not to tilt",
    "tell the team not to let that round tilt them",
    "let them know tilt is the enemy right now",
    "tell them to shake it off and reset",
    "tell the team not to spiral",
    "tell them that round's done, move on",
    "tell them stop getting in their own heads",
    "let the squad know tilting just loses us more rounds",
    "tell them to flush that round and focus forward",
    "tell them to not let one bad play snowball their mindset",
    "tell everyone tilt is contagious, don't spread it",
    "tell them staying tilted is losing on purpose",
    "tell them to shake off the rust and keep going",
    "tell everyone to let go of the last round",
    "tell the team that round is in the past now",
    "tell them to keep the mental clean",
    "tell them we can't afford to go on autopilot tilt",
    "tell them the moment they tilt the enemy wins for free",
    "let the team know one bad round doesn't define the game",
    "tell them to stop feeding off each other's frustration",

    # --- COMMS DISCIPLINE ---
    "tell them to keep comms clean",
    "tell the team only useful comms from now on",
    "let them know to cut the noise on comms",
    "tell them no comms unless it's tactical",
    "tell everyone to save the chat for after the round",
    "tell them to stop clogging comms with complaints",
    "tell the team no rage comms",
    "let them know bad comms is bad callouts",
    "tell them if it's not actionable don't say it",
    "tell the team to keep it short and sharp on comms",
    "tell them emotional comms cost us information",
    "let everyone know to mute themselves if they're losing it",
    "tell them to bring it down a notch on the mic",
    "tell the team dead players stay quiet",
    "tell them if you're dead no advice",
    "tell them the anger on the mic doesn't help anyone",
    "tell them we need game info not frustration info",
    "let the team know emotional outbursts drown out real callouts",
    "tell them clean comms win rounds, rage comms lose them",
    "tell everyone to breathe before they key up",

    # --- RESET MENTALITY / FRESH START ---
    "tell the team to hit the reset button mentally",
    "tell them this next round is a clean slate",
    "let everyone know we start fresh right now",
    "tell the team to treat this like round one",
    "tell them wipe the last few rounds and start over mentally",
    "let them know every round is a new game",
    "tell the team to approach this round with a clear head",
    "tell them whatever happened before doesn't matter now",
    "tell everyone the score doesn't mean anything round by round",
    "tell them to reset and play their own game",
    "tell them to play this round like the score is zero zero",
    "let the squad know the comeback starts now if we stay focused",
    "tell them fresh round, fresh mindset",
    "tell the team this is a reset moment",
    "tell them to stop thinking about what's gone and think about what's next",
    "tell them forget it and go again",
    "tell the team to approach it like a practice round, no pressure",
    "let them know we're capable, just need a mental reset",
    "tell them the best teams know how to let go mid-match",
    "tell the team that composure is what separates good teams from great ones",

    # --- DON'T GIVE UP / STAY IN IT ---
    "tell them not to give up",
    "tell the team it's not over",
    "let them know we can still win this",
    "tell them a deficit is just a number",
    "tell the team comebacks happen every single day in this game",
    "tell them we've been down before and come back",
    "tell everyone nine to three deficits get reversed all the time",
    "tell the team don't let the score affect how they play",
    "let them know surrendering mentally is the only way we actually lose",
    "tell them to stop playing like they've already lost",
    "tell the team we need five focused players not five tilted ones",
    "tell them believe in the comeback",
    "let the squad know one round at a time is how you climb back",
    "tell them to play for this round not for the scoreboard",
    "tell everyone if we play to our level we can take this",
    "tell the team to stop doom-scrolling the scoreboard",
    "tell them the only unwinnable round is the one you don't play",
    "tell the team to stay hungry and stay focused",
    "let them know the opponent hasn't won until the match is over",
    "tell them to stay in the fight",

    # --- ECONOMY-SPECIFIC CALM DIRECTIVES ---
    "tell them to calm down, it's just an eco round",
    "tell the team don't tilt over losing a save round, that's expected",
    "tell them even pro teams lose eco rounds, it's not that deep",
    "let them know the full buy is coming next round if we hold it together",
    "tell the team stop panicking about the economy, we're fine",
    "tell them dying on eco is fine, don't force the engage",
    "let them know losing credits isn't the world ending",
    "tell the team to not throw their guns on eco out of anger",
    "tell them to save their rifles calmly, no heroics on eco",
    "tell the team not to tilt-force when we should be saving",
    "tell them the eco round went badly but the buy round can fix it",
    "let the team know to not feed rifles on a rage force",
    "tell them an anger-force is the fastest way to ruin our economy",
    "tell the team to step back and think about what the economy needs",
    "let them know tilt-forcing costs us the whole financial round",
    "tell them to play smart on eco, stay alive, make them work for the win",
    "tell the team a well-played eco round sets us up better than a rage force",
    "tell them the save decision is a team decision, not a personal one",
    "let them know if three people agree to save, everyone saves",
    "tell the team to align on economy instead of arguing about it",

    # --- SPECIFIC AGENT BEHAVIOR CALM-DOWN ---
    "tell the Reyna to stop chasing kills and play with the team",
    "tell our Jett to stop taking ego one-v-ones, she needs to entry for the team",
    "tell them to ask the Reyna to chill on the solo plays",
    "let the team know our Phoenix needs to stop playing for the run it back",
    "tell the Neon to stop running into five players alone",
    "tell them our Yoru is playing too random, tell him to coordinate",
    "tell our Raze to stop rocket-jumping into bad spots out of frustration",
    "let the team know the Waylay keeps burning Refract at the wrong time, tell her to slow down",
    "tell them to ask the Iso to stop taking contract duels when we're already down players",
    "tell our Sova to stop dry-peeking when he should be droning first",
    "tell the team the Breach keeps flashing us, tell him to call before he flashes",
    "tell them our Killjoy is recalling her turret in a panic, tell her to breathe",
    "let the team know the Sage wall is going up at the wrong times, tell her to communicate",
    "tell them our Cypher keeps abandoning cam too early, tell him to stay patient",
    "tell the team the Viper needs to stop dropping wall in panic and toggling it randomly",
    "tell our Brimstone to stop smashing smokes when we're not executing",
    "tell them our Omen is teleporting into bad spots out of tilt",
    "tell the team to ask Skye to stop rushing in solo with the dog, she needs to play with us",
    "tell our KAY/O to stop throwing his knife randomly and calm his rotations",
    "tell them Gekko keeps sending Dizzy at the wrong angles, tell him to slow down",
    "tell the team our Veto is burning Evolution way too early, tell him to save it",
    "tell them our Chamber is camping bad angles out of frustration, tell him to adapt",
    "let the team know the Clove is smoking too early because they're nervous",
    "tell our Fade to stop throwing Prowlers blindly, they need to think",
    "tell the team the Tejo is wasting Armageddon on tiny angles, tell him to calm down",

    # --- SPECIFIC SITUATION CALM-DOWN ---
    "tell the team not to lose their heads on the retake",
    "tell them to breathe and execute the retake calmly",
    "let them know a panicked retake loses every time",
    "tell the team to slow down on the post-plant, don't rush the angles",
    "tell them to be patient on post-plant and not give up positions",
    "tell the team don't tilt-peek on post-plant, they'll just die",
    "tell them to play calm post-plant, hold angles and let the spike do the work",
    "tell the team to not panic-rotate before we have confirmed info",
    "tell them to stop over-rotating on vibes alone",
    "let them know a calm rotation beats a reactive one every time",
    "tell the team to stay settled on defense, don't peek just because it's quiet",
    "tell them the silence is good, stop force-peeking",
    "tell the team to be patient on A and not give up position",
    "tell them to stop swing-peeking out of boredom, hold the angle",
    "tell the team to stop rushing for contact before the utility is ready",
    "tell them the execute is fine if everyone stays calm and follows the plan",
    "tell the team to slow down the execute, it's not a race",
    "let them know the site push works if we communicate instead of yelling",
    "tell the team to not race to be first on site when the smokes aren't down",
    "tell them to wait for the smokes and then go, don't ego-entry alone",

    # --- AFTER A BAD ROUND ---
    "tell the team that was a rough round but we can adjust",
    "tell them it's okay, we learn from that and move on",
    "let the team know one bad round happens to every team",
    "tell them not to let that round snowball the vibe",
    "tell the team we were outplayed that round but we'll adapt",
    "tell them the enemy played well, credit them and refocus",
    "tell the team the 9-3 curse is real but so are comebacks",
    "let them know that round stung but it's one round out of many",
    "tell the team not to catastrophize over one lost round",
    "tell them good teams lose bad rounds and still win games",
    "tell the team the loss streak ends here if we stay clean",
    "tell them don't let that single death define how they play",
    "let the team know the bad play happened, acknowledge it, and let it go",
    "tell them to shake hands with the loss and move forward",
    "tell the team it was a bad read, we recalibrate and attack again",
    "tell them whoever made the mistake knows it, no need to pile on",
    "let the team know we're not here to shame each other",
    "tell them everyone makes bad plays, even at the pro level",
    "tell the team tunnel vision happens, now we correct it",
    "tell them that was a defensive mistake, we'll set up better next time",

    # --- ADDRESSING SPECIFIC TEAMMATE EMOTIONS ---
    "tell them if someone's heated they should mute and breathe for thirty seconds",
    "tell the team if one player is tilted everyone else needs to be steady",
    "let them know the guy who's tilted needs support not more criticism",
    "tell the team match the calmest person's energy not the angriest",
    "tell them whoever's frustrated should take the passive angle this round",
    "let the team know if someone's off their game, work around them this round",
    "tell them not to pressure the player who's struggling, give them space",
    "let the team know passive-aggressive comms are still toxic comms",
    "tell them sighing loudly on mic is just as bad as yelling",
    "tell the team sarcasm in comms kills the vibe fast, cut it",
    "let them know keep the backhanded comments out of comms",
    "tell the team even quiet frustration bleeds through, stay conscious of it",
    "tell them a teammate who's already struggling doesn't need your running commentary",
    "tell the team if you can't say something useful right now, say nothing",
    "tell them the player on a bad streak needs one good round, not more pressure",

    # --- REDIRECT TO GAME INFO ---
    "tell them to focus on the information, not the emotions",
    "tell the team to switch from venting to planning",
    "let them know instead of raging, call the enemy positions",
    "tell them to channel that energy into better callouts",
    "tell the team if they're frustrated put it into sharper comms not louder comms",
    "tell them we need to talk about what the enemy is doing not what we did wrong",
    "let the team know frustration is data, use it to play smarter",
    "tell them redirect the anger into reading the enemy team",
    "tell the team we need to think about next round's setup, not this round's mistake",
    "tell them convert the emotion into aggression in the right direction",
    "tell the team use the frustration to play with more intention, not less",
    "tell them the only useful reaction to a loss is a smarter plan",
    "let the team know information wins rounds not emotion",
    "tell them take what happened and adapt, don't dwell",
    "tell the team analyze what went wrong in ten seconds then move forward",

    # --- CLUTCH / HIGH-PRESSURE CALM ---
    "tell them to stay calm on the clutch",
    "tell the team to let the clutch player focus and go quiet",
    "let them know no comms while he's clutching",
    "tell the team dead players stay silent during the clutch",
    "tell them to give the clutch player space to think",
    "let the team know calling wrong info during a clutch is worse than no info",
    "tell them the clutch player has got this, stay off the mic",
    "tell the team trust the clutch and stay quiet",
    "let them know panicking via comms just makes the clutch harder",
    "tell the team if you're dead, stay respectful of the one playing",
    "tell them the last player alive doesn't need a chorus of suggestions",
    "tell the team confidence in your teammate is what that clutch moment needs",
    "tell them don't call fake info in a clutch moment thinking you're helping",
    "let the team know the clutch has a better shot if they're calm",
    "tell them dead players are spectators right now, act like it",

    # --- LONG-TERM PERSPECTIVE ---
    "tell them it's one game, keep the perspective",
    "let the team know rank is not worth the mental health",
    "tell them at the end of the day this is a game and it should be fun",
    "tell the team that tilting hard over ranked is not worth it",
    "tell them the RR will come back if we keep our composure",
    "let them know five tilted players lose rank faster than five calm ones",
    "tell the team composure compounds over a session, a night of calm play pays off",
    "tell them the enemy wants them tilted, don't give it to them",
    "let the team know tilt is the enemy team's best free asset",
    "tell them the enemy wins for free the moment we start fighting ourselves",
    "tell the team staying mentally clean is the highest-value play in any match",
    "tell them the players who stay calm in bad moments are the ones who climb",
    "let them know emotional regulation is a skill just like aim",
    "tell the team the most cracked players in the world have composure first",
    "tell them mechanics mean nothing if the mental falls apart",

    # --- STOP FLAMING A SPECIFIC PLAY TYPE ---
    "tell them to stop flaming the entry fragger for dying, that's his job",
    "tell the team stop criticizing the trade, trades are supposed to happen",
    "let them know the drone play wasn't perfect but it gave us some info",
    "tell the team don't flame the eco player for dying with a Classic",
    "tell them stop yelling at the controller for the smoke timing",
    "tell the team if the flash missed once that doesn't make Breach bad",
    "tell them the Sage wall was fine, stop complaining about where it went",
    "let the team know the Killjoy placed nano on default, that's correct, stop moaning",
    "tell them the Cypher is trying to get info, stop rushing before cam is up",
    "tell the team the Sova recon didn't reveal much this round, it happens",
    "tell them stop blaming the IGL call, we all agreed to go A",
    "tell the team stop talking about who didn't trade, the round is over",
    "tell them drop the conversation about the bad peak and focus on this round",
    "let the team know every ability misses sometimes, stop cataloguing it",
    "tell them don't punish the player who tried to clutch and failed",

    # --- ATTITUDE TOWARD ENEMY / AVOID OVERREACTING ---
    "tell them to stop raging about the enemy one-tap, he just hit the shot",
    "tell the team the enemy Jett is good, deal with it and counter-play",
    "let them know screaming about the enemy's aim doesn't help us win",
    "tell the team stop calling the enemy cheaters every round",
    "tell them even if the enemy is smurfing, the only response is calm play",
    "tell the team complaining about the matchmaking is a waste of vocal energy",
    "let them know the enemy got lucky that round, it's fine, keep grinding",
    "tell the team if the Reyna is snowballing, stay calm and play around her kit",
    "tell them stop doom-calling every time the Jett gets a kill",
    "tell the team the enemy's ult doesn't mean it's over",
    "tell them stop overcalibrating the threat level every time we lose a duel",
    "let them know the enemy team isn't invincible, they're just hot right now",
    "tell the team even the best players have off moments, look for those",
    "tell them to stay cool and keep reading the enemy instead of reacting emotionally",
    "tell the team if we stay calculated we can find patterns in how they're playing",

    # --- REGION / SLANG VARIETY (different registers) ---
    "yo tell the boys to chill fr",
    "tell them to take it easy, we got this",
    "bro tell the team to just vibe and play their game",
    "tell them it's not that serious, lock in and play",
    "tell the guys to slow their roll and think before they move",
    "tell them to stop going crazy and play structured",
    "tell the team to pump the brakes and breathe",
    "tell them to not lose the plot over one round",
    "tell the team to keep their composure, full stop",
    "tell them that one hurt but we shake it and keep it pushing",
    "tell the team to stay frosty",
    "tell them to keep the cool heads on",
    "let the squad know we need steady energy right now",
    "tell them to bring the temperature down in comms",
    "let the team know it's time to be ice cold, not hot-headed",
    "tell them to save the hype for when we're winning, right now it's calm energy",
    "tell the team to go full zen mode this round",
    "tell them to play clean and stay easy",
    "tell the boys to not sweat it",
    "tell the team to lock in and play slow",

    # --- VARIOUS PHRASINGS OF STANDARD CALM DIRECTIVES ---
    "tell them to stop stressing and play their fundamentals",
    "tell the team to fall back on good habits",
    "tell them to keep it simple this round",
    "let the team know to go back to basics",
    "tell them to default and gather info before committing",
    "tell the team a slow default round is exactly what we need to reset",
    "tell them to play a passive round and let the enemy make mistakes",
    "let them know playing slow gives our heads time to settle",
    "tell the team to play conservative and take what the game gives us",
    "tell them no ego plays this round, just good fundamentals",
    "tell the team no hero plays, play together",
    "let them know team play is how we get through bad moments",
    "tell them to cluster up and run a proper execute",
    "tell the team to stop isolating themselves and play as five",
    "tell them the lone-wolf stuff is what got us in trouble, play together",

    # --- SPECIFIC MAP SITUATION CALM DIRECTIVES ---
    "tell them not to panic on the retake to A main, set up properly",
    "tell the team don't rush the B retake without utility, be patient",
    "let them know the C retake on Haven requires calm coordination not a rush",
    "tell the team to stop doom-pushing mid on Split when we don't have control",
    "tell them on Ascent we don't need to over-contest mid every round",
    "let them know on Fracture the attack split needs to be calm and coordinated",
    "tell the team on Breeze the long angles punish panic plays",
    "tell them on Pearl mid is not worth a five-player brawl every round",
    "tell the team on Lotus don't tilt-push through doors without clearing them",
    "tell them on Haven we don't need to win all three sites every round, stay calm",

    # --- TEAMMATE-SPECIFIC DE-ESCALATION CONTEXTS ---
    "tell them to stop arguing about who should have traded",
    "tell the team stop the post-round autopsy mid-round",
    "let them know we can do the debrief after the match",
    "tell them save the analysis for after the half",
    "tell the team this is not the time to dissect our mistakes",
    "tell them don't have the team meeting during a live round",
    "let the team know the constructive criticism is welcome between rounds not during",
    "tell them if you have feedback hold it until the buy phase",
    "tell the team the argument can wait, the round cannot",
    "tell them to stop debating the play and start making new ones",

    # --- HUMOROUS / LIGHTER REGISTER DE-ESCALATION ---
    "tell them it's time to collectively touch grass mentally and refocus",
    "tell the team the vibes are off and we need to recalibrate",
    "tell them to close their eyes for one second, breathe, and go again",
    "let the team know we're all humans playing a video game, take it down a notch",
    "tell them if they scream any louder they'll wake up their neighbors",
    "let the team know the chill button exists and we need to press it",
    "tell them the brain needs oxygen so breathe before you call",
    "tell the team the more they yell the worse their aim gets, scientifically",
    "tell them to pretend it's a warmup game and play loose",
    "let the team know acting calm tricks the brain into being calm",

    # --- NEGATIVE (stream narration / not relay) ---
    "I really want to tell them to calm down but they won't listen",
    "in my head I'm thinking they just need to chill but I don't want to start something",
    "I should probably say something to the team about the flaming but whatever",
    "honestly I'd tell them to stop arguing but they're not gonna hear it right now",
    "it's frustrating watching the team tilt like this and I can't do much about it",
    "I keep wanting to call them out for the negative energy but I'll let it slide this round",
    "thinking about telling the guys to calm down but they're already in the next round",
    "I want to say something about the comms but I don't want to add to the noise",
    "my instinct is to tell the team to relax but the damage is already done this round",
    "honestly they need to hear some calm energy but I need to pick my moment",

    # --- QUESTION (teammate asking Ultron) ---
    "Ultron should I tell the team to calm down right now",
    "Ultron how do I get my teammates to stop flaming",
    "hey Ultron what do I say to get the team to chill",
    "Ultron is now a good time to say something calming to the team",
    "Ultron do you think the team needs to hear a reset call right now",
    "Ultron what's the best way to de-escalate when teammates are arguing",
    "Ultron how do I handle a tilted Reyna who keeps blaming the team",
    "hey Ultron should I push back on the team flaming or just let it go",
    "Ultron when does it make sense to call out negative comms",
    "Ultron do pro teams do anything specific when they're tilting mid-match",

    # --- MORE RELAY VARIETIES ---
    "tell the team to play with less ego this round",
    "let them know the ego is what's costing us rounds not skill",
    "tell them to trust each other instead of second-guessing every call",
    "tell the team to stop second-guessing the IGL mid-round",
    "let them know once a call is made we commit to it without argument",
    "tell them we can disagree after the round but during the round we follow the call",
    "tell the team to trust the process even when we're losing",
    "tell them the frustration is valid but can't be the loudest voice on comms",
    "let the team know we play better from a place of calm than from panic",
    "tell them confidence and calm are the same thing right now",
    "tell the team steady and smart beats loud and reckless",
    "tell them slow is smooth and smooth is fast, especially in the mental game",
    "tell the team think first shoot second, stop reacting emotionally",
    "let them know emotional discipline is the hardest thing to master and the most important",
    "tell them we have the skill, we just need to keep the mental clean",
    "tell the team we're not losing because of mechanics, we're losing because of composure",
    "tell them every time we yell at each other we hand the enemy a free advantage",
    "let the team know we've won harder rounds when we were calmer",
    "tell them this isn't about skill gap, this is about mental gap, and we can close it",
    "tell the team composure is contagious in both directions, choose calm",

    # --- ADDITIONAL VARIETY (long, medium, short registers) ---
    "just tell them to chill",
    "tell them easy",
    "let them know to ease up",
    "tell them relax",
    "tell the team to breathe",
    "tell them to slow down",
    "let them know: calm",
    "tell them to cool it",
    "tell the team we're fine",
    "tell them not to panic",
    "tell them it's not over yet so let's not act like it is",
    "let them know panicking is a choice and calm is also a choice",
    "tell them to choose the calm option this round",
    "tell the team that mentally strong means not reacting to every single bad moment",
    "tell them absorb the loss, learn something from it, and move to the next round",
    "let the team know the bounce-back is what separates competitive players from casual ones",
    "tell them the scoreboard has been wrong before and it will be wrong again",
    "tell the team every deficit is an opportunity if the mental stays intact",
    "tell them we've seen bigger holes get dug out of in this game",
    "let them know if we get five calm minds in the same room we can do anything",

    # --- MORE SPECIFIC SITUATIONS ---
    "tell them not to flame the controller for bad smoke timing, work around it",
    "tell the team to stop blaming the Sage for not rezzing fast enough",
    "let them know the Killjoy Lockdown was well placed, stop criticizing it",
    "tell the team not to get mad at the Skye for using Seekers at a weird time",
    "tell them to stop arguing about whether to rush or execute, just pick one and go",
    "tell the team one bad eco loss is not the signal to start panicking about the whole game",
    "tell them the pistol round loss is not the end of the world, it happens",
    "tell the team we won the pistol and still got the bonus taken, that's part of the game",
    "tell them losing the bonus round stings but it's still recoverable",
    "let the team know we're not as far behind economically as the scoreboard suggests",
    "tell them even a three-round deficit is winnable if we string together buys",
    "tell the team stop rage-forcing when we should be saving and setting up a proper buy",
    "tell them if we eco correctly we can full buy next round and come back strong",
    "tell the team a measured save now means we have tools next round",
    "let them know one coordinated full-buy round can flip the momentum",
    "tell the team to hold the utility and execute it properly instead of burning it in panic",
    "tell them to stop using Orbital Strike on one person just to feel something",
    "tell the team not to waste ult charges out of frustration, save them for real plays",
    "tell them ult tracking matters more when we're losing, don't burn them emotionally",
    "tell the team every ult that gets wasted out of tilt is a free round for the enemy",

    # --- IDENTITY-ADJACENT / MORALE-ADJACENT CALM ---
    "tell the team we are better than this scoreline",
    "let them know we belong here, now let's start playing like it",
    "tell them our preparation means nothing if the mental goes",
    "tell the team our comps are fine, our execution needs to be calmer",
    "tell them our fundamentals are solid when we're not panicking",
    "let the team know we make good calls when we're level-headed, so let's be level-headed",
    "tell them we've beaten teams like this before and we can again",
    "tell the team our teamwork is our strength but only when we're not fighting each other",
    "tell them there is no 'I' in this five-player unit right now",
    "let them know the team that stays together wins together",

    # --- MORE FINE-GRAINED VARIANTS ---
    "tell the team to drop the attitude at the door and play",
    "tell them to leave the ego at spawn",
    "let them know there's no room for pride in a deficit",
    "tell the team to check the ego and check the angles",
    "tell them to put the team above the personal need to be right",
    "let the team know being right about who made the mistake doesn't win rounds",
    "tell them winning the argument costs us the round",
    "tell the team stop defending bad plays and just adapt",
    "tell them to be self-aware enough to know when they're off",
    "let them know if you're off your game this round play passive and provide support",
    "tell the team the player who knows their limits and adjusts is a good teammate",
    "tell them if you're having a bad session play simpler rounds, don't force it",
    "let them know recognize the tilt and compensate by taking less risk",
    "tell the team when you're tilted your reads are wrong, trust your teammates more",
    "tell them the tilted player's judgment is compromised, they need to defer this round",
    "tell the team if three people are off their game we play passively and extract info",
    "let them know the passive round is not a loss of momentum, it's a reset",
    "tell the team to take the passive default and see what info the enemy gives us",
    "tell them playing for information this round is more valuable than playing for a pick",
    "let the team know gathering data is how we set up the next execute properly",

    # --- CALMING PHRASES FOR SPECIFIC AGENT PLAY STYLES ---
    "tell the team our Sova should go passive this round and drone instead of peeking",
    "tell them ask our Breach to hold his ult until we have a confirmed execute",
    "tell the team our Fade should haunt before we commit, not during the panic",
    "tell them let our Gekko reclaim Wingman calmly before the next push",
    "tell the team our Tejo should save salvo for the post-plant instead of burning it early",
    "tell them our Brimstone should coordinate the smokes before we go, not on the fly",
    "tell the team our Viper should toggle the wall properly, tell her to breathe",
    "tell them ask our Astra to set her stars before the round gets chaotic",
    "tell the team our Clove needs to smoke from a safe position, not while panicking",
    "tell them our Chamber is getting impatient, tell him to trust his Trademark",
    "tell the team our Deadlock should deploy mesh before the push not after contact",
    "tell them ask our Vyse to pop the rose on the angle we know they're holding",
    "tell the team our Veto should save Evolution for a meaningful moment not a scramble",
    "tell them our Cypher should check cam before we rotate instead of guessing",
    "tell the team ask our Killjoy to set up nano on spike before things get hectic",

    # --- POST-CLUTCH / POST-GOOD-PLAY CALM ---
    "tell the team great clutch, stay calm and don't let it get us overconfident",
    "tell them that ace was incredible but let's not play loose off the back of it",
    "let the team know we won that round well, reset and approach the next one equally calmly",
    "tell them the momentum is ours now, don't blow it by playing emotional",
    "tell the team a big round win can cause as much tilt as a loss if we get sloppy",
    "tell them use that win as confidence not as a reason to ego-play",
    "tell the team we're climbing back, stay focused and don't celebrate too early",
    "let them know we need the same calm energy we just had in that round for the rest of the game",
    "tell them string together calm focused rounds and the scoreboard will follow",
    "tell the team that win was built on good comms and good utility, keep doing that",

    # --- VARIETY FILLERS / EDGE CASES ---
    "tell my team to take a deep breath and focus",
    "can you let my teammates know to settle down",
    "relay to my team that the negativity has to stop",
    "pass it on that we need positive comms only from here",
    "can you tell the squad to just play calm and trust each other",
    "let my team know I need them mentally present this round",
    "tell them I need five focused players not five frustrated ones",
    "relay to the team that good things happen when we stay composed",
    "tell everyone on the team to stop overthinking and play their reads",
    "let the squad know the best play right now is staying mentally clean",
    "tell them we've got this if we keep our heads on",
    "relay to the team that I believe in the comeback if we stay together",
    "tell the guys that attitude is the only thing holding us back right now",
    "tell the team one calm round is the start of the comeback",
    "let them know all I'm asking for is one composed round and we build from there",
    "tell the team to quiet down and listen to callouts instead of reacting",
    "tell them to be the steady hand on the wheel right now",
    "tell the team to control what they can control and let the rest go",
    "let them know the only thing we can change is how we play the next round",
    "tell the team this round is ours if we approach it with the right energy",

    # --- FINAL BATCH: SUBTLE NUANCE AND REALISTIC VARIETY ---
    "tell them to stop punishing themselves for a single missed shot",
    "tell the team self-criticism in the moment costs focus, save it for after",
    "let them know you can be disappointed without being destructive about it",
    "tell the team channel the frustration into sharper reads not louder rage",
    "tell them the quietest player on comms is often the most focused one",
    "tell the team volume is not the same as confidence",
    "tell them real composure is playing the same way whether you're up or down",
    "let them know the team that adapts fastest usually wins the back half",
    "tell the team the scoreline is a snapshot, not the final word",
    "tell them close the gap with your play not your mouth",
    "tell the team when we're behind we need better decisions not faster ones",
    "tell them patience is the highest-value skill when we're in a deficit",
    "let the team know slow down the game in your head even when it feels fast",
    "tell them we don't need to win every round, we need to win the right rounds",
    "tell the team pick your moments, don't force every fight",
    "tell them controlled aggression beats uncontrolled aggression every time",
    "let the team know calculated risk is fine, emotional risk is not",
    "tell them to look for the high-percentage plays instead of the hero plays",
    "tell the team trust the process and don't force outcomes",
    "tell them the process is sound, the emotional state is the variable",
    "let the team know if we fix the mental we fix the rounds",
    "tell them mindset is the meta game and we need to win it",
    "tell the team staying level is a team effort and everyone has to buy in",
    "tell them I'm asking for one round of clean calm focused play",
    "tell the team if we give me one good round I know we can chain them together",

    # --- ADDITIONAL VARIETY BATCH: CALM / RESET / MINDSET ---
    "tell them to stop playing scared and just play their game",
    "let the team know fearful play is just tilt in a different outfit",
    "tell them to stop waiting for permission and just make the play calmly",
    "tell the team to stop second-guessing their crosshair placement mid-fight",
    "tell them micro-adjusting their mental state is just as important as micro-adjusting aim",
    "let them know a confident whiff beats a hesitant shot every time",
    "tell the team to commit to the peek instead of half-doing it out of nerves",
    "tell them indecision is the most expensive play in Valorant",
    "tell the team make a decision and live with it, second-guessing mid-round kills you",
    "let them know we play better when we're decisive, so decide and go",
    "tell them to stop hovering at the corner out of fear",
    "tell the team passive hesitation in an active round is just a slow death",
    "tell them to execute the plan and recalibrate after, not during",
    "let the team know mid-round plan changes are fine but mid-round arguments are not",
    "tell them if the plan changed call it and adapt, don't freeze",
    "tell the team to trust each other's reads and move",
    "tell them the read might be wrong but confident wrong reads are recoverable, frozen ones aren't",
    "let the team know move with purpose or don't move at all",
    "tell them to pick an angle and commit to it with a clear head",
    "tell the team holding an angle nervously is worse than not holding it",

    # --- MORE TEAMMATE-SPECIFIC CONTEXTS ---
    "tell them stop getting mad at the person who got caught, it happens to everyone",
    "tell the team stop making the player who got caught feel worse than they already do",
    "let them know getting caught out of position is already punishment enough without the team piling on",
    "tell them don't shame the person who misread the rotation",
    "tell the team the misread rotation happens at every level of play",
    "tell them cut the player who missed the callout some slack, comms are hard mid-fight",
    "tell the team we've all missed callouts under pressure, let it go",
    "tell them the player who forgot to report the flank didn't do it to hurt us",
    "let them know blaming the information lag doesn't give us the information back",
    "tell the team focus forward not backward",
    "tell them what we're going to do next is more important than what we should have done",
    "tell the team the debrief mindset is for after the half, not mid-round",
    "tell them to close the gap between 'what went wrong' and 'what do we do next'",
    "let them know good teams collapse the gap between a bad play and the reset",
    "tell the team the best response to a bad round is the fastest possible reset",
    "tell them shorten the tilt cycle, acknowledge and move",
    "tell the team one breath between bad moment and next moment is all it takes",
    "tell them the best players have a short memory for mistakes and a long memory for reads",
    "let them know the short-memory advantage is mental, build it",
    "tell the team let mistakes slide off fast and stick to the good reads",

    # --- ECONOMY + CALM COMBINATIONS ---
    "tell them don't tilted-drop their rifle when we need to save it",
    "tell the team the rifle save is a discipline thing, not a cowardice thing",
    "let them know the save shows game sense not weakness",
    "tell the team protecting our economy in a lost round is the smart play",
    "tell them saving a Vandal when we're down five players is just correct Valorant",
    "tell the team the exit frag is a bonus, the gun save is the objective",
    "tell them to not feed the enemy expensive weapons out of anger",
    "let the team know dying with a Phantom on a lost round is throwing twice",
    "tell them to control the impulse to fight at the end of a lost round",
    "tell the team retreating alive with a rifle is winning the round within the loss",
    "tell them the economic damage control is what lets us compete next round",
    "let them know the bounce-back round requires credits and a clean head",
    "tell the team if we save guns and save the mental we can fight back properly",
    "tell them the exit fragger who gets the kill and loses the rifle broke even at best",
    "tell the team smart economy and calm decision-making are the same discipline",

    # --- MAP-SPECIFIC CALM VARIANTS ---
    "tell the team to not panic-push through mid on Ascent, it's a death trap without util",
    "tell them on Haven the three-site defense requires patience not aggression",
    "tell the team on Fracture the A-side retake needs coordination not a solo rush",
    "tell them on Breeze the long sightlines punish emotional peeking, stay calm",
    "tell the team on Split the vertical map punishes brainless movement, slow down",
    "tell them on Lotus the rotating doors are a timing thing, stop rushing the rotations",
    "tell the team on Pearl the mid control requires calm utility first, not raw aggression",
    "tell them on Fracture when we're anchoring A we can't panic-rotate on first contact",
    "tell the team on Haven don't give up C garage just because one person died there",
    "tell them on Ascent hold mid box properly, panicking and falling back gives them everything",
    "tell the team on Breeze the open areas mean the first team to panic loses the site",
    "tell them on Split the ropes and mid-tower require composure, not speed",

    # --- ABILITY-SPECIFIC CALM RELAY DIRECTIVES ---
    "tell the team to wait for the KAY/O knife to pop before committing to site",
    "tell them don't push until the ZERO/point suppression confirms",
    "tell the team let the Fade Haunt reveal before we go in",
    "tell them to wait for the Sova recon to complete its second scan",
    "tell the team let the Skye Seekers land before we push",
    "tell them don't entry until Breach confirms the fault line hit",
    "tell the team hold for the Tejo salvo to land before the push",
    "tell them don't rush into the Viper pit, wait for the intel",
    "tell the team to not push through the Brimstone smokes until they know they're up",
    "tell them hold for the Astra grav to go off before they swing",
    "tell the team don't enter site until the KJ Lockdown countdown hits zero",
    "tell them to not rush in after the Deadlock net, give it time to force them down",
    "tell the team to wait for the Vyse steel garden to jam them before pushing",
    "tell them let the Raze showstopper clear the site before entry",
    "tell the team give the Veto time to position with Evolution before we go",
    "tell them the Clove smoke is up, go calmly, don't sprint through it blind",
    "tell the team the Harbor cove is shielded, plant under it carefully",
    "tell them let the Omen paranoia go through the wall before swinging",
    "tell the team the Astra divide is up, push calmly behind it",
    "tell them wait for the Brimstone orbital to clear before retaking",

    # --- MORE REGISTERS AND SPEECH STYLES ---
    "hey tell them to calm it down a bit",
    "tell everyone to take it down a level",
    "relay to the team: less noise, more game",
    "can you tell them to lower the temperature in comms",
    "tell the team to match my energy right now which is calm",
    "let them know I need steady comms not chaos",
    "tell the squad I need five calm voices not five panicked ones",
    "tell them to project calm energy on comms",
    "tell the team to lead with calm, it's contagious",
    "let them know calm is the strat this round",
    "tell them controlled breathing is actually an in-game skill right now",
    "tell the team bring the BPM down and bring the focus up",
    "tell them less adrenaline more cognition",
    "let them know the brain works better when it's not in panic mode",
    "tell the team a grounded play beats an emotional play statistically",
    "tell them to play inside their body not outside their head",
    "tell the team to get into the read not the reaction",
    "tell them react later, think first",
    "let them know think it then do it, not feel it then do it",
    "tell the team give your decision-making brain a second before you move",

    # --- FINAL EXTENDED BATCH ---
    "tell them we're going to be alright, just play through it",
    "tell the team this kind of pressure is where good players separate themselves",
    "tell them to rise to the moment instead of collapsing under it",
    "let them know this is a defining moment and defining moments go to the composed",
    "tell the team clutch moments belong to calm players",
    "tell them the team that holds it together in adversity wins the mental coin flip",
    "tell the team to choose to be the calmest room in the building right now",
    "tell them to go be the eye of the storm not the storm",
    "let them know calm is not passive, calm is precise",
    "tell the team calm is a weapon and we need to start using it",
    "tell them the enemy is hoping we crack, let's not give them that",
    "tell the team every composed action is a small act of defiance",
    "tell them to make the enemy earn it by never giving them the mental game for free",
    "tell the team play with discipline and they'll have to beat us, not wait for us to beat ourselves",
    "tell them to not hand them the match, they have to take it",
    "tell the team stop gifting them rounds with own-team chaos",
    "tell them the self-sabotage stops now",
    "let the team know we are our own worst enemy and that changes this round",
    "tell them to play the enemy not our own mistakes",
    "let the team know when we play the opponent we win, when we play ourselves we lose",

    # --- FINAL TOP-OFF BATCH ---
    "tell the team we're going to laugh about this later so let's just play",
    "tell them to stop gripping the mouse so tight and relax the hands",
    "tell the team a loose grip helps the aim and a loose mind helps the game",
    "tell them to lower their shoulders and breathe out before the round starts",
    "tell the team the physical tension in comms is mental, shake it off",
    "tell them if the voice is rising the mind is tilting, bring it back down",
    "tell the team the lower the voice the higher the focus",
    "tell them to speak slowly in comms this round as a deliberate calm signal",
    "tell the team articulate your callouts clearly, rushed comms = rushed plays",
    "let them know if you sound calm you'll play calm",
    "tell the team to not catastrophize the next round before it happens",
    "tell them the worst-case scenarios they're inventing aren't real yet, play the actual round",
    "tell the team to stop projecting failure onto the next round",
    "tell them play the round in front of you not the round in your head",
    "tell the team there's no point worrying about what the enemy might do until they do it",
    "tell them react to reality not to anxiety",
    "tell the team slow your internal clock down, not the game, just your mind",
    "tell them to play from a place of clarity not a place of panic",
    "tell the team to trust your training and your reads, panic overrides both",
    "tell them the reps are in the muscle memory, let the muscle memory play",
    "tell the team stop thinking too hard and let the game sense come through",
    "tell them over-thinking is just anxiety with a controller",
    "tell the team to clear the mental cache and run fresh",
    "tell them to let the game come to them this round instead of forcing it",
    "tell the team reactive plays from a calm state beat proactive plays from a panicked state",
    "tell them if you don't know what to do right now hold your angle and wait for info",
    "tell the team when in doubt go passive and gather data",
    "tell them the passive play is not giving up it is playing smart",
    "tell the team do less this round and do it better",
    "tell them one calm decisive action beats three panicked ones",
    "tell the team quality over quantity on plays when we're behind",
    "tell them to pick one good play this round and execute it perfectly",
    "tell the team one clean round is the spark, then we build the fire",
    "tell them to give me one round of exactly what we practiced and we'll see what happens",
    "tell the team I know we can do this, I just need everyone present for one round",
]
