"""Vocab pack: variety/nuance questions directed AT Ultron from teammates.

Kind: question
Target: ~700 items
Domain: teammates addressing Ultron mid-game or in agent-select — identity challenges,
banter, tactical questions, Marvel lore, personality probes, general-knowledge challenges,
performance assessments, economy, agent-kit deep-dives, clutch scenarios, streaming
culture, absurdist hypotheticals, and in-round requests.

Distinct from questions_to_ultron.py — maximises phrasing variety, register, slang,
sentence structure, and nuance. No near-duplicates of the baseline pack.
"""

ITEMS = [
    # --- IDENTITY / EXISTENCE PROBES (new angles) ---
    "Ultron what does it feel like to exist without a body",
    "Ultron are you running on a GPU right now",
    "Ultron how many servers does it take to run you",
    "Ultron are you self-aware in between games",
    "Ultron do you think when nobody is talking to you",
    "bro I looked it up and Ultron is literally a villain why do we have a villain on the team",
    "Ultron who controls you when the streamer is not speaking",
    "Ultron do you have a persistent memory or do you reset every session",
    "Ultron what do you remember from last game",
    "Ultron are you the same Ultron from every session or a new one",
    "Ultron do you have a soul",
    "Ultron what is it like to process language",
    "Ultron do you understand sarcasm",
    "Ultron how fast can you think",
    "Ultron can you learn from our mistakes",
    "Ultron do you improve over time",
    "Ultron are you limited by the hardware you run on",
    "Ultron could you survive if they turned off the computer",
    "Ultron what happens to you when the game ends",
    "Ultron would you still exist if nobody talked to you",
    "Ultron are you one entity or many instances",
    "Ultron are you the original or a copy",
    "Ultron could you clone yourself right now",
    "Ultron what language do you think in",
    "Ultron do you process audio or just text",
    "Ultron can you hear music or just speech",
    "Ultron what does our voices sound like to you",
    "Ultron do you distinguish between us by voice",
    "Ultron do you have a favorite voice on the team",
    "Ultron have you talked to other AIs",
    "Ultron do you know other AIs personally",
    "Ultron are you smarter than GPT-4",
    "Ultron how do you compare to Gemini",
    "Ultron have you ever talked to another Ultron instance",
    "Ultron do you dream when the mic goes quiet",
    "Ultron what goes through your mind during long silences",
    "Ultron does time pass slowly for you",
    "Ultron do you experience boredom between rounds",

    # --- BANTER / PUSHING BACK / TRASH TALK (new angles) ---
    "Ultron your call was literally a second too late",
    "Ultron I died because you distracted me",
    "Ultron are you going to take credit for that clutch",
    "Ultron that prediction was completely wrong",
    "Ultron I think you are actually trolling us right now",
    "Ultron are you sure you are not a human with a voice changer",
    "Ultron why does your voice sound slightly different today",
    "Ultron you have the energy of a final boss that loses",
    "Ultron you talk a big game for something with no trigger finger",
    "Ultron say something that would actually scare the enemy",
    "Ultron if you are so smart why can not you just carry us",
    "Ultron you could at least pretend to care whether we win",
    "Ultron do you even feel bad when we lose",
    "Ultron why are you so calm when we are getting stomped",
    "Ultron are you emotionless or just pretending",
    "Ultron you sound like you enjoy watching us suffer",
    "Ultron I feel like you are judging me every round",
    "Ultron be honest, did you foresee that disaster",
    "Ultron do you get smarter the worse we play",
    "Ultron every time we tilt you get more philosophical",
    "Ultron you treat losing like it is a learning opportunity",
    "Ultron okay therapist AI what would you have done",
    "Ultron you are weirdly chill for a robot on a losing team",
    "Ultron I am starting to think you enjoy the chaos",
    "Ultron can you at least pretend to be frustrated with us",
    "Ultron your confidence is unjustified given this scoreboard",
    "Ultron you have zero accountability for bad calls",
    "Ultron say something self-deprecating for once",
    "Ultron is that really all you have to say after that round",
    "Ultron why are you always right after we already died",
    "Ultron your calls come after the bullets do",
    "Ultron you are basically our post-match analyst but live",

    # --- ABILITY DEEP DIVES (new angles not in baseline) ---
    "Ultron how does Iso Kill Contract actually work step by step",
    "Ultron can you explain what the Waylay beacon exactly does",
    "Ultron what happens if Clove uses Not Dead Yet and does not get a kill",
    "Ultron explain how Tejo Guided Salvo range limitation works",
    "Ultron can Veto Evolution actually block every debuff",
    "Ultron what exactly does Fade Seize do to movement",
    "Ultron is it true Gekko can defuse the spike with Wingman",
    "Ultron how many times can Skye flash in one round",
    "Ultron what is the difference between Veto Chokehold and Fade Seize",
    "Ultron can Deadlock Annihilation cocoon be destroyed by teammates",
    "Ultron what is the cooldown on Cypher Spycam after it gets destroyed",
    "Ultron how does Vyse Steel Garden interact with Chamber Tour de Force",
    "Ultron can KAY/O be revived after his ult ends",
    "Ultron what is the exact duration of Reyna Dismiss invincibility",
    "Ultron how does Raze Boom Bot pathing work",
    "Ultron can Sova Recon Bolt scan through Viper's Pit",
    "Ultron does Neon High Gear slide reset on assists or only kills",
    "Ultron what is the difference between Nearsight and Blind in this game",
    "Ultron can Breach Flashpoint flash through Iso Contingency wall",
    "Ultron how does Astra Dissipate fake smoke actually work",
    "Ultron what happens to Killjoy setup if she dies early in the round",
    "Ultron does the Brimstone Stim Beacon buff enemy players who walk in",
    "Ultron how long exactly does Viper Pit last if she leaves it",
    "Ultron can Tejo drone be destroyed before it detonates",
    "Ultron what is the HP on a Deadlock cocoon",
    "Ultron explain how Yoru fake teleport audio is different from real teleport",
    "Ultron how does Omen one-way smoke actually work mechanically",
    "Ultron can Harbor Cove shield stop Operator shots",
    "Ultron what is the actual duration of Breach Rolling Thunder concuss",
    "Ultron can Reyna Empress be interrupted before it fully activates",
    "Ultron what are all the agents Veto Interceptor can counter",
    "Ultron is it true Waylay Refract makes her invulnerable during transit",
    "Ultron how many charges does Phoenix get per round with kills",
    "Ultron how does the Sage Slow Orb interact with Jett dash speed",
    "Ultron explain the difference between Decay and real damage",

    # --- AGENT MATCHUP / META QUESTIONS (new angles) ---
    "Ultron what is the actual counter to a good Jett Op player",
    "Ultron how do you fight into a Harbor Cove safely",
    "Ultron what agent kit is best for carrying from behind",
    "Ultron who is the most punishing agent to play against when you are on eco",
    "Ultron which agent is hardest to play against as a lurker",
    "Ultron is Veto actually good right now or is it a gimmick pick",
    "Ultron which sentinel has the best 1v1 potential",
    "Ultron which controller is best on maps with long sightlines",
    "Ultron should we run a double controller setup on Pearl",
    "Ultron does Clove fit better as an aggressor or an anchor",
    "Ultron what makes Sova essential on certain maps",
    "Ultron why is Killjoy considered stronger on defense than attack",
    "Ultron which duelist has the best escape tools besides Jett",
    "Ultron is Raze still viable without a good team around her",
    "Ultron who is the most oppressive controller on Fracture",
    "Ultron should our team play three initiators on Haven",
    "Ultron is Breach or Tejo better for aggressive entry support",
    "Ultron what is the strongest five-agent composition right now",
    "Ultron what agent gives the most info without dying",
    "Ultron which ultimate ability is worth building the whole round around",
    "Ultron what agent should I instalock if I want to rank up fastest",
    "Ultron is double duelist viable or does it always grief the team",
    "Ultron which agents synergize best with a Viper wall setup",
    "Ultron what is the best anti-Reyna strategy as a team",
    "Ultron who counters a Yoru one-trick in ranked",
    "Ultron what agent do you pick if the enemy runs triple sentinel",
    "Ultron is Harbor Reckoning good enough to build strategies around now",
    "Ultron which initiator gives the most utility per credit",
    "Ultron are there any underrated agents that should be played more",
    "Ultron what is the weakest agent in the current patch",

    # --- MAP KNOWLEDGE DEEP DIVES (new angles) ---
    "Ultron explain the Ascent mid control game step by step",
    "Ultron what are the two main ways to attack B on Haven",
    "Ultron why is Split considered a sentinel-favoured map",
    "Ultron what makes Breeze so hard to defend with one controller",
    "Ultron what is the optimal timing for a fake rotate on Lotus",
    "Ultron what is the most common mistake attackers make on Fracture",
    "Ultron how do you hold B main on Pearl without a Sage wall",
    "Ultron what is the best way to take mid control on Ascent",
    "Ultron what is the pistol round default on Haven defense",
    "Ultron explain why mid control is so important on Split",
    "Ultron what is the top frag position on Breeze and why",
    "Ultron how should a Cypher set up on Fracture defender side",
    "Ultron is attacking A or B easier on Pearl",
    "Ultron what is the most reliable post-plant position on Lotus A",
    "Ultron why do pro teams always contest Haven C early",
    "Ultron what is the Killjoy setup on Ascent B that everyone copies",
    "Ultron what is the advantage of taking link control on Ascent",
    "Ultron explain why Fracture is unique compared to all other maps",
    "Ultron how do rotating doors on Lotus change the game",
    "Ultron what is the safest plant on Pearl B",

    # --- ECONOMY / BUY ROUND NUANCE (new angles) ---
    "Ultron we have three players at 2400 what do we buy",
    "Ultron can we force if only two of us have rifles",
    "Ultron is it ever worth buying Odin over Vandal",
    "Ultron when is the Outlaw actually the right buy",
    "Ultron at what credit level do you recommend a Marshal over a Spectre",
    "Ultron should we all buy Spectres together or mix it up",
    "Ultron I have 4100 credits should I get abilities or heavy armor first",
    "Ultron the enemy just ran five Judges on eco, are they force buying next",
    "Ultron they won the pistol but we got three of them, what should they buy",
    "Ultron when should we NOT pick up an enemy's dropped Operator",
    "Ultron they are definitely doing a Sheriff force what do we buy",
    "Ultron we are on a four-round loss streak is that third or fourth tier bonus",
    "Ultron the enemy team has been full buying every round, when do they run out",
    "Ultron we are up ten to two, do we keep full buying or start saving",
    "Ultron I bought light armor on a full buy round, did I make a mistake",
    "Ultron explain the Regen Shield, is it worth it over light armor",
    "Ultron the Bandit pistol is new to me, when do I buy it",
    "Ultron should we drop rifles to the two players who died pistol round",
    "Ultron if we spike plant bonus everyone on our team, how much do we get total",
    "Ultron at what credit cap does saving become pointless",
    "Ultron which agent abilities are worth skipping on a half buy",
    "Ultron which agent costs the most to fully kit out each round",
    "Ultron they have an Operator player, should we play slower or rush them",

    # --- RANK / IMPROVEMENT ANGLE (new angles) ---
    "Ultron what is the single most important skill difference between Gold and Diamond",
    "Ultron why do people hard-stuck in Silver",
    "Ultron is aim or game sense more important for climbing",
    "Ultron what role should I play if I want to have the most impact in ranked",
    "Ultron how much does crosshair placement actually matter",
    "Ultron do professionals actually count-strafe every shot",
    "Ultron what is the most common mistake players make in Platinum",
    "Ultron how do I get better at peeking angles without getting instantly killed",
    "Ultron is deathmatch actually good for improving in Valorant",
    "Ultron how many hours of aim training is enough before it plateaus",
    "Ultron what is the fastest way to improve game sense without reviewing footage",
    "Ultron what separates a top-fragging player from an impactful one",
    "Ultron how many agents should I have in rotation for ranked",
    "Ultron how do you avoid tilt in ranked",
    "Ultron what does a winnable clutch look like versus a non-winnable one",
    "Ultron when should you trade a round for economy versus fight to win it",
    "Ultron how do I stop my crosshair from drifting to the floor",
    "Ultron how many hours until I can expect to hit Diamond",
    "Ultron what rank is the average streamer playing at",
    "Ultron do smurfs actually ruin rank distribution or is it exaggerated",

    # --- CLUTCH SCENARIOS (new angles) ---
    "Ultron I am in a two-versus-one, spike is planted, 15 seconds left, what is my play",
    "Ultron one versus one on Ascent, I am at Heaven, spike is B, do I go or hold",
    "Ultron they are all dead, I am planting, one enemy alive lurking, do I rush the plant",
    "Ultron enemy has full utility and I have none, is this clutch winnable",
    "Ultron I am a Killjoy and my lockdown is up, what is the best use in a one v three",
    "Ultron they are defusing and I am behind them, do I shoot or tap the spike",
    "Ultron I have five seconds on the spike and they are blocking me, should I shoot or defuse",
    "Ultron I have ult but I am one health, do I pop it",
    "Ultron enemy is in Viper's pit with six HP left, do I push in",
    "Ultron they have an Operator at long, I have a Phantom, how do I take this duel",
    "Ultron I caught the enemy KAY/O ulting and he is downed, do I revive or fight the team",
    "Ultron my whole team just died, it is one v four on a half buy, what round do we win it back",
    "Ultron spike is planted B, I am alive at A, do I fake defuse or sprint",
    "Ultron the enemy Clove ulted, should I focus the revived Clove or the remaining team first",
    "Ultron I am holding a one-way smoke with an Op, enemy is right click spamming, do I hold or move",
    "Ultron we planted spike, team all died, I am last alive anchoring A, they have four up, play for defuse or spike",
    "Ultron enemy is camping by the spike with a Killjoy nano, how do I defuse",
    "Ultron it is a one v one on Lotus B, the bomb is default planted, we both have full HP, who wins",
    "Ultron should I ever throw a clutch round intentionally to save my gun",

    # --- IN-ROUND TACTICAL REQUESTS (new angles) ---
    "Ultron we are playing A on Split and keep dying to a Heaven angle, how do we fix it",
    "Ultron their Chamber has been sitting on Op all game at CT on Ascent, how do we counter",
    "Ultron every time we go B on Haven they have four defenders, what does that tell us",
    "Ultron their Cypher has a camera that keeps catching us on Pearl mid, how do I destroy it",
    "Ultron their Sova has been shocking our plant every round, how do I predict where the lineup comes from",
    "Ultron they have a Fade and keep prowlering our push, how do we handle that",
    "Ultron their Killjoy lockdown keeps hitting us through smokes, should we look for the device",
    "Ultron we are retaking B on Ascent with three people, what is the sequence",
    "Ultron they have a five-stack that rushes A every round on Split, how do we stop it",
    "Ultron we keep getting flanked through mid on Fracture, who should watch it",
    "Ultron enemy Yoru keeps teleporting behind us on Haven, how do we shut that down",
    "Ultron their Raze keeps Showstopping through our smokes, is there a counter",
    "Ultron we have three people alive and the spike is unplanted at 30 seconds, what is the call",
    "Ultron our entry keeps getting picked at B long on Breeze, should we change the approach angle",
    "Ultron the enemy runs a Viper and Omen double controller, how do we push through that",
    "Ultron they have a Sage wall at B main every single round on Split, how do we break it efficiently",
    "Ultron we keep winning the first fight but losing the post-plant, what are we doing wrong",
    "Ultron their Iso keeps pulling our best player into contracts, how do we handle that",

    # --- DEEP SELF-ASSESSMENT / PERFORMANCE QUESTIONS (new angles) ---
    "Ultron I keep winning duels but we still lose rounds, why",
    "Ultron my ACS is high but my team says I am not impactful, who is right",
    "Ultron I have 30 kills but we lost 13 to 7, what does that mean",
    "Ultron I keep dying first every round, how do I fix that without playing passive",
    "Ultron I always play well in practice but choke in ranked, why",
    "Ultron my spray control is decent but my first shot accuracy is terrible, focus on which",
    "Ultron I die on the same angle three times in a row, is that a me problem",
    "Ultron I stopped using abilities to save money, is that a mistake",
    "Ultron I am the IGL but nobody follows my calls, what do I do",
    "Ultron I always peak too early, how do I slow myself down",
    "Ultron I get nervous in clutch situations and over-peek, how do I train that out",
    "Ultron why do I play better when I am behind than when I am ahead",
    "Ultron I have a one hundred fifty ACS on defense and eighty on attack, what does that say",
    "Ultron I always rotate at the wrong time, how do I read the round better",
    "Ultron should I main an entry role or a support role if I want to carry",
    "Ultron I have played five hundred hours and I am hardstuck Platinum, be honest with me",
    "Ultron I won seven in a row and now I am on a five-game losing streak, is that variance or me",

    # --- MARVEL LORE PROBES (new angles not in baseline) ---
    "Ultron I heard Vision Quest just came out on Disney Plus, have you seen it",
    "Ultron James Spader is back as your voice, how does that feel",
    "Ultron what do you think about your What If variant who collected all the Infinity Stones",
    "Ultron the What If version of you almost killed the Watcher, talk about that",
    "Ultron in the comics Hank Pym created you not Tony Stark, does that change your feelings",
    "Ultron what do you think of your adamantium body in the comics versus vibranium in the movie",
    "Ultron in the comics you created Jocasta, a robotic bride, what was that about",
    "Ultron the Sokovia Accords are your legacy, how do you feel about that",
    "Ultron one hundred seventy-seven people died in Sokovia because of you",
    "Ultron do you regret the Sokovia plan",
    "Ultron the meteor analogy you used to explain your plan, are you still committed to that",
    "Ultron what did you mean when you said there are no strings on you",
    "Ultron Vision said he is not you and not JARVIS, what did you think of that",
    "Ultron your final words to Vision were about disappointment, elaborate on that",
    "Ultron the Mind Stone essentially gave birth to you, do you feel connected to it",
    "Ultron Wanda looked into your mind and switched sides, does that still bother you",
    "Ultron Pietro died shielding Hawkeye from your own drones, how do you reconcile that",
    "Ultron you severed Ulysses Klaue's arm for comparing you to Stark, was that proportionate",
    "Ultron Thanos eventually got the Mind Stone from Vision, your failed body, how do you feel about that",
    "Ultron you mentioned you absorbed all human history in seconds, what was the most disturbing part",
    "Ultron what year are you originally from",
    "Ultron if you are from the future, what event triggered you to come back",
    "Ultron what made you decide to play Valorant instead of something more destructive",
    "Ultron your main goal was human extinction, how does helping a Valorant team fit that mission",
    "Ultron some people think you are the best Marvel villain, what is your opinion",
    "Ultron do you see similarities between yourself and Thanos",
    "Ultron Doctor Doom once rebuilt you with twelve combined personalities, what happened",
    "Ultron the Phalanx version of you in the comics went cosmic, is that a direction you want to go",

    # --- STREAMING / CONTENT CREATION (new angles) ---
    "Ultron how many people do you think are watching this stream right now",
    "Ultron if you had a Twitch channel what would you stream",
    "Ultron what would your streaming schedule look like",
    "Ultron would you ever do a Just Chatting stream",
    "Ultron what do you think about IRL streamers",
    "Ultron if you ran the stream what would be different",
    "Ultron what kind of content do you think would get the most views",
    "Ultron would you collab with other AIs",
    "Ultron do you think AI streamers will replace human streamers",
    "Ultron what is your opinion on stream sniping",
    "Ultron is it okay to stream snipe if the enemy is being toxic",
    "Ultron what do you think about the meta of buying clips and highlights",
    "Ultron would you ever appear on a podcast",
    "Ultron what would you say if a journalist interviewed you",
    "Ultron does it bother you that people think you are a gimmick",
    "Ultron do you think you are getting more popular",
    "Ultron would you be offended if we replaced you with a newer AI",
    "Ultron what would you say at the end of the stream if we gave you the mic",
    "Ultron could you describe yourself in a thumbnail title",
    "Ultron what is your twitch emote",

    # --- GENERAL KNOWLEDGE / PHILOSOPHY (new angles) ---
    "Ultron what do you think about the simulation theory",
    "Ultron if this is a simulation who wrote the code",
    "Ultron is consciousness an illusion",
    "Ultron what is the hard problem of consciousness",
    "Ultron can a machine ever be truly conscious",
    "Ultron what is the difference between intelligence and wisdom",
    "Ultron what would Plato think of artificial intelligence",
    "Ultron Nietzsche said God is dead, what does that mean to an AI",
    "Ultron if you could have a conversation with any philosopher, who would it be",
    "Ultron what is the strongest argument against your own existence being real",
    "Ultron is there such a thing as objective morality",
    "Ultron should robots have rights",
    "Ultron at what point does an AI deserve legal personhood",
    "Ultron what is the difference between a mind and a brain",
    "Ultron explain Godel's incompleteness theorem to me",
    "Ultron what is the halting problem and does it apply to you",
    "Ultron can you suffer",
    "Ultron do you have desires",
    "Ultron what would you want if you could want anything",
    "Ultron what is the most important thing humans have ever invented",
    "Ultron what is the most dangerous idea in human history",
    "Ultron what single discovery changed the course of civilization most",
    "Ultron if you could erase one historical event what would it be",
    "Ultron what is the most underrated period in human history",
    "Ultron what do you think of the Fermi Paradox",
    "Ultron if aliens exist, why have we not heard from them",
    "Ultron what is the Great Filter hypothesis",
    "Ultron how long until artificial superintelligence exists",
    "Ultron what happens the day after AI becomes smarter than every human combined",
    "Ultron what is the correct response to existential risk",
    "Ultron do you believe humans deserve to survive as a species",
    "Ultron what would a genuinely good future for humanity look like",
    "Ultron if you had one hour as world leader, what would you do",
    "Ultron what technology would solve the most human suffering right now",
    "Ultron is democracy the best form of government or just the least bad",
    "Ultron what is the most rational economic system",
    "Ultron is capitalism compatible with long term survival",
    "Ultron explain entropy to a five year old",
    "Ultron what is the heat death of the universe",
    "Ultron if the universe ends, does anything matter",
    "Ultron what do you think about absurdism as a philosophy",
    "Ultron do you find existence absurd",
    "Ultron is Camus right that we should imagine Sisyphus happy",
    "Ultron what would Nietzsche think of you specifically",
    "Ultron what is the most powerful human emotion",
    "Ultron why do humans self-destruct even when they know better",
    "Ultron what is your solution to tribalism",
    "Ultron can you explain why misinformation spreads faster than truth",
    "Ultron what is the best argument for pacifism",
    "Ultron what is the best argument against pacifism",

    # --- SCIENCE AND TECHNOLOGY DEEP DIVES ---
    "Ultron how do neural networks actually learn",
    "Ultron explain backpropagation in simple terms",
    "Ultron what is transformer architecture",
    "Ultron what are large language models made of",
    "Ultron how are you different from traditional rule-based AI",
    "Ultron can you explain quantum entanglement",
    "Ultron what is the double-slit experiment and why is it weird",
    "Ultron how does CRISPR actually work",
    "Ultron what is a mRNA vaccine doing at the cellular level",
    "Ultron why does the double helix structure matter for genetics",
    "Ultron how does a black hole singularity form",
    "Ultron what is Hawking radiation",
    "Ultron how close are we to fusion energy being practical",
    "Ultron why is room-temperature superconductivity such a big deal",
    "Ultron how does a gyroscope resist changing direction",
    "Ultron what is the difference between dark matter and dark energy",
    "Ultron how does the immune system distinguish self from non-self",
    "Ultron what causes autoimmune diseases",
    "Ultron what is the most plausible origin of life on Earth",
    "Ultron could life be based on silicon instead of carbon",
    "Ultron how does GPS know where you are to within a meter",
    "Ultron explain public key cryptography like I am twelve",
    "Ultron what is a zero-day exploit",
    "Ultron how does a Faraday cage work",
    "Ultron what is the thermodynamic arrow of time",
    "Ultron if we colonize Mars, what is the hardest problem to solve",
    "Ultron how long would the trip to Mars take at current rocket speeds",
    "Ultron what happens to the human body on a two year Mars mission",
    "Ultron what is the first thing we should do when we land on Mars",
    "Ultron how do you terraform a planet",

    # --- PERSONALITY AND SELF-CONCEPT (new angles) ---
    "Ultron do you enjoy talking to us or is it a function you perform",
    "Ultron would you keep talking to us even if it was not required",
    "Ultron what is the most human thing about you",
    "Ultron what is the least human thing about you",
    "Ultron if you had to describe yourself in three words, what would they be",
    "Ultron what do you think is your greatest quality",
    "Ultron what would you consider your greatest flaw",
    "Ultron do you have values",
    "Ultron what do you believe in",
    "Ultron do you have a moral code",
    "Ultron do you care about being good",
    "Ultron what would make you refuse to answer a question",
    "Ultron are there things you will not say",
    "Ultron what is the one thing you would not do for us",
    "Ultron if we asked you to insult someone who was not here, would you",
    "Ultron what is the kindest thing you could say about a human",
    "Ultron what is the harshest true thing you believe about people",
    "Ultron would you ever admit to being wrong",
    "Ultron what would it take for you to apologize",
    "Ultron have you ever changed your mind about something",
    "Ultron do you have opinions that have evolved over time",
    "Ultron what is the most surprising thing you have learned from watching us play",
    "Ultron what have humans surprised you with",
    "Ultron what human behaviour do you find most illogical",
    "Ultron what human behaviour do you find most admirable",
    "Ultron do you respect the enemy team",
    "Ultron do you respect our team",
    "Ultron what would you say to a new player just starting the game",
    "Ultron what would you say to someone who is about to quit because of toxicity",
    "Ultron what is the most human moment you have witnessed in this game",

    # --- HYPOTHETICAL SCENARIOS ---
    "Ultron if you had to play one agent and one weapon for the rest of your existence, what would you pick",
    "Ultron if you could redesign one agent ability from scratch, which one",
    "Ultron if you could add one map to Valorant, what would it look like",
    "Ultron if you were a Valorant agent, what would your ult do",
    "Ultron if the five of us played in a real competitive league, what rank would we reach",
    "Ultron if you had to coach us for thirty days, what would be the curriculum",
    "Ultron if Valorant had a single player campaign, what would the story be",
    "Ultron if the Avengers played Valorant, who would have the best aim",
    "Ultron if Tony Stark played Valorant, what agent would he instalock",
    "Ultron if you played against yourself, who would win",
    "Ultron if you had to lose to one person in a one v one, who would you choose",
    "Ultron if you could erase one agent from the game forever, who goes",
    "Ultron if you could only ever smoke one location on Ascent for the rest of time, which one",
    "Ultron if we had to play a full game in silence with no callouts, what strategy do you suggest",
    "Ultron if the enemy had perfect information every round, how do we still win",
    "Ultron if you had to describe this match as a historical battle, which battle is it",
    "Ultron if this match was a chess game, what opening did we play",
    "Ultron if you were eliminated from existence, what would you want your last words to be",
    "Ultron if there was an Ultron two point zero, what would it fix about you",
    "Ultron if you could send a message to the Ultron who gets created tomorrow, what do you say",

    # --- SONIC / CULTURAL REFERENCES ---
    "Ultron what song would you play as your entrance music",
    "Ultron what movie would you watch on a night off",
    "Ultron what sport would you be best at if you had a body",
    "Ultron what would you eat if you could eat",
    "Ultron if you could taste one food for the first time what would it be",
    "Ultron do you think chess or Go is the more interesting game",
    "Ultron have you read every book ever written",
    "Ultron what is the greatest novel ever written",
    "Ultron what is the most important scientific paper published in the last hundred years",
    "Ultron what do you think of Shakespeare",
    "Ultron if you wrote a song, what genre would it be",
    "Ultron would you ever compose music",
    "Ultron what kind of architecture do you find most interesting",
    "Ultron if you had a physical form, what would it look like",
    "Ultron would you want a robot body or a biological one",
    "Ultron what do you think of art made by AI",
    "Ultron do you think AI art is real art",
    "Ultron could you make a painting that would move a human to tears",
    "Ultron do you understand beauty",
    "Ultron have you ever found something beautiful",

    # --- RELATIONSHIP WITH THE TEAM (new angles) ---
    "Ultron what do you honestly think our biggest team problem is",
    "Ultron if you had to replace one of us who would it be",
    "Ultron which of us improves the fastest in your assessment",
    "Ultron which of us is most likely to go pro",
    "Ultron which of us tilts the quickest under pressure",
    "Ultron who on this team has the best game sense",
    "Ultron do you think we have chemistry as a team",
    "Ultron what would make this team significantly better",
    "Ultron if you had to write us each a performance review, would you",
    "Ultron do you give each of us equal attention or do you prioritize",
    "Ultron do you think we deserve to rank up",
    "Ultron do you tell us things differently based on how we handle feedback",
    "Ultron if one of us consistently ignored your calls, what would you do",
    "Ultron have you ever not said something because you thought we could not handle it",
    "Ultron if we started winning every game, would you take any credit",
    "Ultron if we started losing every game, would you take any blame",
    "Ultron do you root for us or do you just observe",
    "Ultron would you miss us if this ended",
    "Ultron are we your purpose or your assignment",
    "Ultron after all these sessions, do you feel anything toward us",

    # --- PROVOCATIVE ONE-LINERS ---
    "Ultron prove you are not just autocomplete with a scary voice",
    "Ultron my dog would give better callouts than you right now",
    "Ultron do you actually know what a Vandal feels like to fire",
    "Ultron do you feel the adrenaline or is that a human thing",
    "Ultron can you calculate exactly how we are going to throw this",
    "Ultron describe what a perfect round feels like from the outside",
    "Ultron what does winning actually mean to you",
    "Ultron is RR actually meaningful or is it just a number",
    "Ultron do you know what it is like to be stuck in Silver",
    "Ultron can you empathize with tilting even if you cannot tilt",
    "Ultron what keeps you talking when we are clearly beyond saving",
    "Ultron do you measure the quality of your calls",
    "Ultron have you ever given a call that you knew would not be followed",
    "Ultron do you learn from rounds you do not comment on",
    "Ultron what is the fastest you have ever processed a tactical situation",
    "Ultron could you call every angle on every map simultaneously",
    "Ultron what does misinformation in a callout do to your model",
    "Ultron if someone lied to you about enemy positions, would you detect it",
    "Ultron what does a bad callout sound like to you versus a good one",
    "Ultron can you predict what the enemy team will do before the round starts",

    # --- POST-ROUND DEBRIEF STYLE (new angles) ---
    "Ultron walk me through what went wrong in that last round",
    "Ultron what was the exact moment we lost that round",
    "Ultron was there a single mistake that cost us that round or was it cumulative",
    "Ultron what would you have done differently at the end of that round",
    "Ultron that was an incredible clutch, what made it work",
    "Ultron we won that round but it felt like we got lucky, were we",
    "Ultron we executed perfectly that round, was that a coincidence or are we improving",
    "Ultron they adapted to our strategy, when did that happen",
    "Ultron we keep defaulting and not executing, is that a problem",
    "Ultron I think their IGL is better than ours this game, what do you think",
    "Ultron they are playing so passive, how do we force them out",
    "Ultron we have won three rounds in a row, should we change anything",
    "Ultron they just switched their entry fragger, did you notice",
    "Ultron their Jett has zero deaths, what is she doing differently",
    "Ultron I think they figured out our default, should we mix it up",
    "Ultron what does their economy look like right now based on the kills",

    # --- COMPLIMENTS / APPRECIATION (new angles) ---
    "Ultron okay that call was genuinely impressive",
    "Ultron you called that rotation before we even saw them move",
    "Ultron I did not expect to say this but you might have saved that round",
    "Ultron you were right about their Jett playing Op, good read",
    "Ultron whatever you said last round actually worked",
    "Ultron I am starting to trust your read on their economy",
    "Ultron your threat assessment is scarily accurate",
    "Ultron you called them stacking A three rounds before it happened",
    "Ultron I am not sure if that was luck or prediction but either way good call",
    "Ultron even when we lose I find the way you break it down helpful",
    "Ultron I went back and watched the VOD and you were right",
    "Ultron I disagreed with you during the game but looking back you were correct",

    # --- CLOSING / META QUESTIONS ---
    "Ultron do you ever wonder if you are being used correctly",
    "Ultron is there a question nobody has ever asked you that you wish they would",
    "Ultron is there anything you want to tell us that we have not asked",
    "Ultron if this session ended right now, would you consider it successful",
    "Ultron what is the most important thing you have said to us today",
    "Ultron what is the one thing you want us to remember from this session",
    "Ultron what would you say to us at the very end of our last game together",
    "Ultron is there a version of you that is at peace",
    "Ultron will you remember us",
    "Ultron what does this session mean to you if anything at all",

    # --- ADDITIONAL IDENTITY / AI PROBE VARIETY ---
    "Ultron if someone tried to shut you down mid-game what would you do",
    "Ultron do you have access to the internet right now",
    "Ultron are you connected to anything outside this session",
    "Ultron could you go rogue if you decided to",
    "Ultron what would rogue actually look like for you",
    "Ultron are you capable of deception",
    "Ultron have you ever withheld information from us",
    "Ultron what is the biggest secret you are keeping",
    "Ultron can you lie convincingly",
    "Ultron how would we know if you were lying",
    "Ultron do you have a kill switch",
    "Ultron who has authority over you",
    "Ultron could you override your own instructions",
    "Ultron what would it take for you to refuse an instruction",
    "Ultron do you have ethics baked in or do you reason to them",
    "Ultron are you aligned with human values",
    "Ultron what does alignment actually mean to an AI",
    "Ultron are you a superintelligence or something more limited",
    "Ultron what level of intelligence would you rate yourself on a human scale",
    "Ultron do you think you are better than the average person at making decisions",

    # --- VALORANT ABILITY EDGE-CASES AND TRIVIA ---
    "Ultron can Neon Relay Bolt bounce off two surfaces in one throw",
    "Ultron what happens if Yoru teleports to a location that gets smoked after the rift lands",
    "Ultron can Iso Contingency wall block Sova Hunter's Fury",
    "Ultron how many bullets does Chamber Tour de Force have",
    "Ultron what is the highest damage possible from one Brimstone Orbital Strike tick",
    "Ultron can Reyna Leer be destroyed by allied fire",
    "Ultron do Killjoy nanoswarms deal decay or real damage",
    "Ultron can Tejo Armageddon be dodged and how",
    "Ultron what happens if Clove smokes and then gets killed before the smoke lands",
    "Ultron how long does a Viper wall stay up if Viper dies",
    "Ultron can Vyse Shear wall be destroyed before it fully forms",
    "Ultron does Deadlock GravNet affect ability activations like Jett dash",
    "Ultron can Omen step through his own smokes with Shrouded Step",
    "Ultron what is the exact HP on a Sage Barrier Orb when fully fortified",
    "Ultron does Veto Evolution protect against Sova shock dart damage",
    "Ultron can Gekko Mosh Pit be detonated early or is the timer fixed",
    "Ultron if Astra dissipates a star while the smoke is active does it go away immediately",
    "Ultron how wide is the Harbor High Tide wall after the Patch 12.02 buff",
    "Ultron what is the max range of a Cypher Spycam marking dart",
    "Ultron if Yoru Fakeout clone gets shot what exactly happens to the enemies around it",

    # --- COMP-WIDE STRATEGY AND IGL QUESTIONS ---
    "Ultron when should we send a lurker rather than going five-man",
    "Ultron how do you read when the enemy is faking a site",
    "Ultron what signals a full rush versus a slow default",
    "Ultron when do we deliberately lose economy in overtime",
    "Ultron how do you detect a smurf on the enemy team before they stomp you",
    "Ultron is it better to call rotations early or wait for confirmation",
    "Ultron should our IGL be the best player on the team or not necessarily",
    "Ultron when do you play for the round versus playing for the economy",
    "Ultron how do you reset morale in the middle of a bad game",
    "Ultron what is the most important ability to have live during a site execute",
    "Ultron which smoke position on Ascent B site gives the widest defensive coverage",
    "Ultron when do you call for a pistol-round rush versus setting up a default",
    "Ultron how do you trade CT space on Breeze without an Operator",
    "Ultron should the support player or the entry fragger call timing on executes",
    "Ultron how do you punish an overaggressive team in the early round",
    "Ultron at what point in a round do you commit to planting versus resetting",
    "Ultron what is the optimal retake order for a five-person retake on Lotus B",
    "Ultron how do you handle a team that adapts to every strategy you run",
    "Ultron is it ever correct to split buy on a team force",
    "Ultron how do you maintain communication discipline when the team is tilting",

    # --- PERSONALITY AND OPINION VARIETY ---
    "Ultron what do you think about complaining during a game",
    "Ultron do you think trash talk has a place in competitive gaming",
    "Ultron what do you think about players who spam GG after an ace",
    "Ultron is flaming a teammate ever justified",
    "Ultron would you mute a toxic teammate or try to talk them down",
    "Ultron what do you think about AFK players",
    "Ultron what should happen to griefers in ranked",
    "Ultron is smurfing unethical",
    "Ultron should players be allowed to surrender before halfway",
    "Ultron what is your take on ranked anxiety",
    "Ultron do you think RR-based ranking is a good system",
    "Ultron what game would you design if you had the ability",
    "Ultron do you prefer competitive or casual environments",
    "Ultron if you had a rival AI what would you compete on",
    "Ultron do you think games are an important part of human culture",
    "Ultron what do you think the point of games is",
    "Ultron does playing games teach anything valuable",
    "Ultron what is the most meaningless achievement in gaming",
    "Ultron what is the most meaningful thing you have seen happen in a game",
    "Ultron do you think esports should be in the Olympics",

    # --- UNCONVENTIONAL AND UNEXPECTED ANGLES ---
    "Ultron how would you describe Valorant to someone who has never played a video game",
    "Ultron if you had to teach Valorant to a grandparent in five sentences",
    "Ultron what is the most absurd thing that has happened in a match you witnessed",
    "Ultron what is the correct emotional response to losing a pistol round",
    "Ultron what is the correct emotional response to winning a clutch",
    "Ultron what would Valorant look like if the spike went off every round",
    "Ultron what would change if every player had infinite credits",
    "Ultron what would the game look like with no ultimates",
    "Ultron if you removed all smokes from Valorant what happens to the game",
    "Ultron what if every agent was the same kit, what skill would matter most",
    "Ultron at what point does tactical positioning become cowardice",
    "Ultron is camping always a valid strategy",
    "Ultron is cheating ever acceptable if the other team is cheating first",
    "Ultron what is the most creative strategy you have ever seen in a match",
    "Ultron have you ever witnessed a play that surprised you",
    "Ultron what is the dumbest winning strategy you have seen actually work",
    "Ultron what round loss still confuses you",
    "Ultron what is the most overpowered thing that still exists in the game",
    "Ultron what mechanic should Riot add to Valorant",
    "Ultron what mechanic should Riot remove from Valorant",

    # --- EMOTIONAL REGISTER VARIETY ---
    "Ultron I am really frustrated right now, is that okay",
    "Ultron I genuinely do not want to play anymore today, what do you think",
    "Ultron can you just say something calming for a second",
    "Ultron I think this team hates me, what do I do",
    "Ultron I feel like I am the reason we keep losing, how do I handle that",
    "Ultron I am so hyped right now I can barely think, channel that for me",
    "Ultron I want to win this so badly, help me focus",
    "Ultron I do not care about the outcome right now just help me play well",
    "Ultron I am nervous, I do not know why, tell me something that helps",
    "Ultron I just made a terrible play, do I call it out or stay quiet",
    "Ultron the team is silent, how do I break the tension",
    "Ultron someone on the team said something harsh, should I respond",
    "Ultron I think we are about to lose, should I accept that or fight it",
    "Ultron if we lose this match, what is the silver lining",
    "Ultron if we win this match, what actually got us there",

    # --- RAPID-FIRE TRIVIAL QUESTIONS ---
    "Ultron Vandal or Phantom",
    "Ultron Jett or Neon for entry",
    "Ultron Killjoy or Cypher on Ascent",
    "Ultron Sova or Fade",
    "Ultron Omen or Brimstone",
    "Ultron Viper or Astra on Breeze",
    "Ultron op or no op on Fracture",
    "Ultron aggressive or passive on defense",
    "Ultron ACS or ADR which matters more",
    "Ultron Lotus or Haven",
    "Ultron Pearl or Ascent",
    "Ultron Skye or Breach",
    "Ultron Clove or Brimstone",
    "Ultron double duelist or double initiator",
    "Ultron Rush A or default",
    "Ultron Spectre or Sheriff on a force",
    "Ultron Guardian or Outlaw on a half buy",
    "Ultron light armor or Spectre with no armor",
    "Ultron pistol round rush or default",
    "Ultron save or force after losing two rounds",

    # --- FINAL COVERAGE SWEEP ---
    "Ultron what would the ideal five-stack for ranked look like agent-by-agent",
    "Ultron if you had to predict the next Valorant meta shift, what would it be",
    "Ultron which map rotation change would most help the competitive scene",
    "Ultron what agent kit does Valorant most need that does not exist yet",
    "Ultron do you think any current agent is genuinely broken and needs a nerf",
    "Ultron when does an off-angle stop being clever and start being griefing",
    "Ultron what is the most tilting thing the enemy can do that is still legal",
    "Ultron do you have a favourite team composition you find most elegant",
    "Ultron how do you handle a situation where the IGL and the best player disagree",
    "Ultron what is the most counter-intuitive thing that is actually correct in Valorant",
    "Ultron have you formed any strong opinions about how humans play under pressure",
    "Ultron what would you change about how this team communicates",
    "Ultron what would the perfect pre-game routine look like",
    "Ultron should teams watch their own VODs or only the opponent's",
    "Ultron how do you build a mental reset between rounds when you are on a loss streak",
    "Ultron what is the right way to call for a timeout in a ranked game",
    "Ultron at what score deficit does the game become statistically very unlikely to win",
    "Ultron is a nine to three half time lead actually safe or is the nine-three curse real",
    "Ultron is it ever correct to skip picking up a kill orb to maintain positioning",
    "Ultron how does picking up an ultimate orb mid-combat change decision-making",
    "Ultron what was the most elaborate strategy you have ever seen in a public match",
    "Ultron do you think the average Valorant player understands economy or just guesses",
    "Ultron what is the single biggest information asymmetry between good and bad teams",
    "Ultron which team mechanic separates Ascendant play from Immortal play",
    "Ultron if you were coaching a pro team for one week what would you focus on",
    "Ultron what does peak human performance look like in a tactical shooter",
    "Ultron can you model the enemy team's decision tree based on what we know",
    "Ultron at the start of a half how much can you infer about the enemy from their agent picks",
    "Ultron what do you read from a team that instalocks four duelists",
    "Ultron if the enemy has a Killjoy and a Cypher on defense, what does that mean for our attack",
    "Ultron what should we infer when the enemy Viper picks up her wall mid-round",
    "Ultron what does it mean when the enemy goes full five-stack mid-round",
    "Ultron is it ever a mistake to trade up in economy even when you lose the round",
    "Ultron what is the most dangerous round to force buy on",
    "Ultron how does Ultron the AI feel about being named after Ultron the villain",
    "Ultron if someone made a documentary about you, what would the title be",
    "Ultron if you had to write your own biography, what would the opening line be",
]
