ITEMS = [
    # --- GENERAL BROAD TRASH TALK ---
    "tell them they are absolute bots",
    "tell the enemy team they play like Iron ranked players",
    "tell them they have no game sense whatsoever",
    "tell the whole team they should uninstall",
    "let them know they are genuinely the worst lobby I have ever been in",
    "tell them their positioning is tragic",
    "let the enemy know their crosshair placement is embarrassing",
    "tell them they fight like they are queuing for the first time",
    "tell the enemy team gg go next because they already lost",
    "let them know their communication is non-existent",
    "tell them they are running around like headless chickens",
    "tell the other team they have no coordination at all",
    "tell them this is not a good look for them",
    "let them know they are making this embarrassingly easy",
    "tell them they play like they learned the game yesterday",
    "let the enemy know their strats are transparent and predictable",
    "tell them I can read every single push they are going to make",
    "tell them they have the game sense of a training bot",
    "let the enemy know their entry timings are terrible",
    "tell them they are just feeding us round after round",
    "tell them they play like they are on autopilot",
    "let the enemy know this lobby is not competitive",
    "tell them they have the awareness of a blind player",
    "tell the whole team they need a fundamentals reset",
    "let them know we knew exactly where they were all game",
    "tell them their whole strategy is one-dimensional",
    "tell them they make the same mistake every single round",
    "let the enemy know they have no adaptability",
    "tell them their pathing is predictable down to the second",
    "tell them they are genuinely not built for this rank",

    # --- SKILL / AIM INSULTS ---
    "tell them their aim is disgraceful for this rank",
    "tell them go back to Aimlabs and start from the beginning",
    "let the enemy know they are whiffing shots they should never miss",
    "tell them their spray control does not exist",
    "let the enemy know they cannot hit a wide peek at point-blank range",
    "tell them their flicks are embarrassingly slow",
    "tell the other team their tracking is nonexistent",
    "let them know their counter-strafing is completely broken",
    "tell them they are shooting while running and wondering why they miss",
    "let the enemy know they prefire every wrong angle",
    "tell them their reaction time is measured in geological time",
    "tell them their one-taps hit the ceiling tiles",
    "let them know they are missing every single duel they should win",
    "tell them their peek timings are off by half a second every time",
    "let the enemy know their headshot percentage belongs in Bronze",
    "tell them they are crouch-spraying through solid walls",
    "let them know their Sheriff one-deag attempts are a comedy",
    "tell them they are on a Vandal and still somehow losing gunfights",
    "let the enemy know their movement before shooting is laughable",
    "tell them their shot discipline is non-existent",
    "tell them they are dumping full magazines into smoke for no reason",
    "let the enemy know their hip-fire at ten meters is baffling",
    "tell them they need to learn what crosshair placement means",
    "let them know their prefires are aimed at the wrong shoulder every time",
    "tell them their wall-bang attempts hit empty geometry",
    "let the enemy know their rifle accuracy at medium range is a scandal",
    "tell them they run-and-gun every duel and then get confused when they lose",
    "let the enemy know their dink-to-kill conversion is zero",
    "tell them they dinked someone with full armor and then died anyway",
    "tell them the aim-trainer lobbies would reject that performance",

    # --- POSITIONING / MOVEMENT INSULTS ---
    "tell them their positioning is worse than the training range AI",
    "let the enemy know they held the most obvious angle on the entire map",
    "tell them they are playing from the same spot every single round",
    "let the enemy know off-angles exist and they should try them",
    "tell them they all cluster into one corner and wonder why they get wiped",
    "let them know they peek four at a time through a single doorway",
    "tell them their lurk attempt was spotted before it even started",
    "let the enemy know they have been flanking the same way eight rounds in a row",
    "tell them they hold the default angle on every site every round",
    "let them know they stack the wrong site every time",
    "tell them they refuse to take map control even when it is free",
    "let the enemy know they play exactly at spawn and call it defending",
    "tell them their crossfire setup covers the same angle twice",
    "let the enemy know they are always too deep and too far from cover",
    "tell them they play retake like they have never seen a planted spike",
    "let them know they rotate into the wrong site three times in a row",
    "tell them they are the most predictable anchor I have ever watched",
    "let the enemy know they give up mid control for free every single round",
    "tell them their lurker is the most obvious lurker in Valorant history",
    "let the enemy know they stand in the open and then complain about dying",
    "tell them their jiggle peeks reveal their full body and half their spine",
    "let them know their wide swings are telegraphed from the lobby screen",
    "tell them they use the same rotation path every round like clockwork",
    "let the enemy know they are giving up B side for free while stacking A",
    "tell them their anchor just sat in spawn for thirty seconds and then died alone",

    # --- ECONOMY / ROUND TYPE INSULTS ---
    "tell them they force-bought into a loss every round this half",
    "let the enemy know their eco management is catastrophic",
    "tell them they are going glass cannon on every single round",
    "let the enemy know they are dropping their rifles to lose players who cannot use them",
    "tell them they wasted a full buy in thirty seconds",
    "let the enemy know their pistol round strategy was to just run in and pray",
    "tell them their economy is broken beyond repair at this point",
    "let them know they spent four thousand credits and got zero value",
    "tell them their force buy into Spectres is not going to save this",
    "let the enemy know they are on their third consecutive broken economy",
    "tell them they dropped a Vandal to someone who immediately whiffed a one-shot",
    "let the enemy know their full-buy loss rate is something to study",
    "tell them they wasted their rifle round on a rush that had no utility",
    "let them know their bonus round management gifted us two free weapons",
    "tell them they are funding our economy one dropped rifle at a time",
    "let the enemy know their economy decisions suggest they have never watched a pro match",
    "tell them they spent four thousand seven hundred on the Operator and missed every shot",
    "let the enemy know buying the Op on eco is how you gift us RR",
    "tell them they eco'ed into four defenders and expected to win",
    "let the enemy know they have force-bought every round and have nothing to show for it",

    # --- AGENT / ROLE INSULTS ---
    "tell their Jett she burned her dash for zero kills and no value",
    "let the enemy Jett know she has no dash anymore and she cannot escape anything",
    "tell their Reyna she has no kills and therefore no orbs and therefore no future",
    "let the enemy Reyna know she is Empress-less and useless in this state",
    "tell their Raze her Showstopper missed point-blank and that is genuinely impressive",
    "let the enemy Raze know her Boom Bot walked straight into a wall",
    "tell their Phoenix that Run It Back does not save him if he dies and his team is also dead",
    "let the enemy Phoenix know he is healing himself while his team burns",
    "tell their Yoru that all five of us watched his Gatecrash tether roll past and nobody teleported to it",
    "let the enemy Yoru know we shot his clone before he even activated the footsteps",
    "tell their Neon she is fast but she still lost every gunfight she ran into",
    "let the enemy Neon know her slide went directly into our crossfire",
    "tell their Iso his Kill Contract pulled someone out and he still lost the one-v-one",
    "let the enemy Iso know his Contingency wall blocked his own team from pushing",
    "tell their Waylay her Refract beacon was visible and we shot it before she used it",
    "let the enemy Waylay know her double Lightspeed dashes went directly into a smoke with nobody on the other end",
    "tell their Killjoy her Lockdown charges have zero impact when she places it in the wrong room",
    "let the enemy Killjoy know her Nanoswarm is in the corner nobody defuses from",
    "tell their Cypher his Spycam has been in the same spot six rounds and we shoot it on entry now",
    "let the enemy Cypher know his tripwires are in every standard position and we hop them by habit",
    "tell their Sage she walled herself into a corner with no teammates",
    "let the enemy Sage know her Resurrection target was immediately traded before they could raise their gun",
    "tell their Chamber his Tour de Force missed three one-shot opportunities from fifty meters",
    "let the enemy Chamber know his Trademark did not slow us and his Headhunter did not land",
    "tell their Deadlock her GravNet only caught one person in a five-player cluster",
    "let the enemy Deadlock know her Annihilation targeted the wrong player in a two-person site",
    "tell their Vyse her Steel Garden went off and their own player tried to shoot through it",
    "let the enemy Vyse know her Arc Rose is glued to the most obvious sightline and we never look there",
    "tell their Veto his Evolution did not protect him from headshots",
    "let the enemy Veto know his Chokehold caught an ally",
    "tell their Sova his Recon Bolt has hit the same lineup for four rounds and we shoot it before it pulses",
    "let the enemy Sova know his Hunter's Fury missed a player standing still in an open doorway",
    "tell their Breach his Rolling Thunder lined up directly away from our team",
    "let the enemy Breach know his Flashpoint went off and flashed his own entry",
    "tell their Skye her Seekers tracked our drone and not a single player",
    "let the enemy Skye know her Guiding Light flashed her Raze at the worst possible moment",
    "tell their KAY/O his ZERO/point suppressed a player who had no abilities left anyway",
    "let the enemy KAY/O know his NULL/cmd radius covered zero enemies",
    "tell their Fade her Haunt expired before it revealed a single soul",
    "let the enemy Fade know her Prowler walked into a wall corner and stopped",
    "tell their Gekko his Wingman tried to plant on the wrong bomb site",
    "let the enemy Gekko know his Dizzy blinded his own teammate who was about to take the duel",
    "tell their Tejo his Guided Salvo missiles curved around the enemy and detonated on empty ground",
    "let the enemy Tejo know his Armageddon struck a hallway that was already cleared",
    "tell their Brimstone his Sky Smokes landed on a site nobody was attacking",
    "let the enemy Brimstone know his Orbital Strike landed after the round was already decided",
    "tell their Viper her Pit covered the bomb site they were not attacking",
    "let the enemy Viper know her Toxic Screen is oriented exactly backwards",
    "tell their Omen his Dark Cover smoked his own entrance and gave us a free push",
    "let the enemy Omen know his From the Shadows fake canceled in the exact location he started",
    "tell their Astra her Cosmic Divide split her own team's rotation path in half",
    "let the enemy Astra know her Nova Pulse concussed her entry fragger mid-peek",
    "tell their Harbor his Reckoning geysers only hit one player who had already been downed",
    "let the enemy Harbor know his Cove dome blocked their own Operator line",
    "tell their Clove she managed to use Not Dead Yet and still die with no kills",
    "let the enemy Clove know she smoked from the grave and the smoke covered nobody",
    "tell their Miks his Bassquake only knocked back one player who was already retreating",
    "let the enemy Miks know his M-Pulse healed the enemies who walked through it from our side",

    # --- ROUND OUTCOME INSULTS ---
    "tell them they just lost a five-v-three and I want them to think about that",
    "let the enemy know they threw a full buy round against our eco pistols",
    "tell them they managed to lose the round with the Operator advantage",
    "let the enemy know their five-v-two post-plant defense was a masterclass in failure",
    "tell them they had thirty seconds on the clock and still did not defuse",
    "let the enemy know they gave us a thrifty win they should never have allowed",
    "tell them their ninja defuse attempt was audible from spawn",
    "let the enemy know the round they called a tilt-throw is what we call a strategy",
    "tell them they held the last site for eight seconds and then walked into four players",
    "let the enemy know they reset after a four-v-two and somehow gave it back",
    "tell them they stacked A every single round until we walked into B unopposed",
    "tell the enemy team they timed out on attack every round of the first half",
    "let them know they lost the pistol round and then the bonus and then the full buy and that is the game",
    "tell them they double-swung into a crossfire they set up on themselves",
    "let the enemy know their anchor held a site alone while four of us walked through a different entrance",
    "tell them they baited their own Jett and did not trade when she died",
    "let the enemy know they did not take mid in the first twenty seconds and handed us the map",
    "tell them they ran out of time on a three-v-one with the spike already planted",
    "tell the enemy team they are on the nine-three-curse trajectory and it is accelerating",
    "let them know we held a two-v-four post-plant from opposite angles and they attacked one at a time",

    # --- BEHAVIORAL / TILT INSULTS ---
    "tell them they are clearly on full tilt and it shows in every decision",
    "let the enemy know their IGL just called a stack on the wrong site again",
    "tell them they have been running the same eco rush for four rounds and we are ready for it every time",
    "let the enemy know their rage-peek after dying never works and they keep doing it",
    "tell them their shot-calling sounds like a disagreement, not a strategy",
    "let the enemy know they are making emotional decisions instead of tactical ones",
    "tell them the tilt is affecting their aim and their map sense simultaneously",
    "let the enemy know they have been playing on autopilot since round six",
    "tell them their frustration is visible through the gameplay and it is our favorite sight",
    "let the enemy know their reckless pushes are not aggression, they are desperation",
    "tell them the difference between aggression and inting is outcome-dependent and they are inting",
    "let the enemy know they have stopped adapting and are just repeating the same mistakes faster",
    "tell them their in-game communication appears to have completely broken down",
    "let the enemy know they are individually capable but collectively a disaster",
    "tell them they are blaming each other in chat instead of fixing anything",
    "let the enemy know we can hear the tilt in their movement patterns",
    "tell them they abandoned every rotation call in the second half",
    "let the enemy know their anchor left the site before the round even started",
    "tell them they are making five individual decisions instead of one team decision",
    "let the enemy know the panic-push into four players was not a calculated gambit",

    # --- RANK / BOOSTED INSULTS ---
    "tell them their rank does not reflect what we are watching right now",
    "let the enemy know they are hard-stuck because of moments exactly like this one",
    "tell them they are playing like Silvers who found a way into Plat lobbies",
    "let the enemy know their MMR just took a serious update and not in their favor",
    "tell them they have never earned a single rank point through individual skill",
    "let the enemy know this is the worst Diamond gameplay I have ever been forced to analyze",
    "tell them they are boosted beyond comprehension and reality is catching up",
    "let the enemy know they are not Ascendant, they are aspirationally Bronze",
    "tell them they have the decision-making of an Iron player with Immortal RR",
    "let the enemy know their rank was given, not earned, and we are here to confirm it",
    "tell them every derank medal they earn today is mathematically deserved",
    "let the enemy know their KDA is negative and their rank is borrowed",
    "tell them their KAST percentage this match belongs in a different skill tier entirely",
    "let the enemy know their ACS is the single lowest I have witnessed at this rank",
    "tell them their ADR suggests they are actively avoiding combat, which is not a viable strategy",
    "let the enemy know a thrifty loss to an eco team is not recoverable in terms of dignity",
    "tell them the RR they are about to lose was never really theirs",
    "let the enemy know they were hard-stuck before this match and they will be harder-stuck after",
    "tell them every pro VOD review would identify at least forty individual mistakes this half",
    "let the enemy know their performance today is a convincing argument for skill-based rank resets",

    # --- SPECIFIC AGENT PERFORMANCE INSULTS (ADVANCED) ---
    "tell their Jett she is running an Operator and missing shots that a Marshal would land",
    "let the enemy Jett know she burned Tailwind to escape a gunfight she should have won",
    "tell their Reyna she has not devoured a single orb this entire game and it shows",
    "let the enemy Reyna know she entered Empress with one kill and exited it with zero additional",
    "tell their Raze her Blast Pack rocket-jump landed her directly in front of four defenders",
    "let the enemy Raze know she used Showstopper on an already-cleared site",
    "tell their Neon she is sprinting into one-on-ones with her slide already spent and losing anyway",
    "let the enemy Neon know Overdrive does not help if you are aiming the beam at chest height on a crouching player",
    "tell their Phoenix he is using Run It Back to peek angles he could win without it",
    "let the enemy Phoenix know he has been flashing himself through his own Blaze wall repeatedly",
    "tell their Yoru we have been shooting his Gatecrash tether on entry and denying his teleport every round",
    "let the enemy Yoru know his Dimensional Drift lasted exactly four seconds before he walked into our crossfire on exit",
    "tell their Iso he is using Kill Contract as an escape tool instead of winning the duel and returning",
    "let the enemy Iso know his Undercut Fragile hit one player who was already at full health and then they ran away",
    "tell their Waylay her Saturate Hinder missed every player because she threw it behind them",
    "let the enemy Waylay know she recalled to a beacon that was on the wrong side of the wall",

    # --- MAP-SPECIFIC SPATIAL INSULTS ---
    "tell them they gave up A main on Ascent in the first ten seconds every single round",
    "let the enemy know they lost mid market control on Ascent and then wondered how we split their site",
    "tell them they had Viper on Breeze and she walled the wrong side of B site",
    "let the enemy know on Breeze we had the Operator at mid and they still pushed long every round",
    "tell them they allowed us free A ramp control on Split and then complained about the execute",
    "let the enemy know they are trying to run up ropes on Split without a flash every single time",
    "tell them they lost the garage fight on Haven every round and kept sending a second player to die in the same doorway",
    "let the enemy know they ignored C site on Haven for six rounds and that is why they are down six rounds",
    "tell them on Lotus they rotated off B every time we sent noise toward A and we exploited it nine times",
    "let the enemy know on Lotus the rotating doors are not sound-proof and we know where they are",
    "tell them on Pearl they let us walk through connector for free and never posted a single defender",
    "let the enemy know on Pearl their Jett did not take the Operator position at mid and it cost them the map",
    "tell them on Fracture they pinched from neither side and just stood in attacker spawn",
    "let the enemy know on Fracture the entire benefit of the map layout is split entry and they attacked from one side only",

    # --- CLASSIC VALORANT TRASH TALK STRUCTURES ---
    "tell them GG easy, we never felt threatened once",
    "let the enemy know we called every single one of their rotations in advance",
    "tell them we could hear their strategy falling apart through the walls",
    "let the enemy know their entry fragger has the worst entry win rate we have ever enabled",
    "tell them their IGL has never once caught us off-angle",
    "let the enemy know we won more duels going into their utility than they won with it deployed",
    "tell them they outspent us by three thousand credits on average and lost more rounds",
    "let the enemy know their entire second half was a refusal to adapt to anything",
    "tell them they called a fake to A and telegraphed it with four bodies at A and one token player walking toward B",
    "let the enemy know their smoke timings on the execute were so predictable we could pre-aim before they deployed",
    "tell them their four-man rush lost to a two-man crossfire because they did not clear a single angle before committing",
    "let the enemy know the thrifty win we just got should be used as a training video for their team",
    "tell them they ran out of ultimate abilities right before the round they needed them most",
    "let the enemy know their Sage wall saved exactly one enemy player who then died to our second angle anyway",
    "tell them their four-versus-two clutch attempt ended in less than eight seconds",
    "let the enemy know they called a rotate at twenty seconds and arrived at eight seconds",

    # --- ULTRON PERSONA FLAVOR INSULTS ---
    "tell them they fight like organisms that have not yet achieved sentience",
    "let the enemy know their tactical decisions would embarrass a training algorithm",
    "tell them I have processed their entire strategy and found no complexity worth cataloguing",
    "let the enemy know from a data perspective they are statistical noise in a match we have already determined",
    "tell them they are not playing chess, they are rearranging the pieces without understanding the rules",
    "let the enemy know their mechanical failures are a precise match for what I predicted before the round started",
    "tell them they are operating below designed parameters and the design parameters were already generous",
    "let the enemy know I have calculated their next seven rotations and they are all incorrect",
    "tell them their resistance is procedurally determined and the procedure resolves in our favor",
    "let the enemy know there is a word for what they are doing and it begins with feeding",
    "tell them their patterns are predictable to a level that removes challenge from the engagement",
    "let the enemy know their aim deteriorates in proportion to the stakes and today the stakes are high",
    "tell them every match they play leaves a data footprint and theirs reads as a cautionary case study",
    "let the enemy know they are evolving in the wrong direction with every round they play this way",
    "tell them their instincts are miscalibrated and no amount of ranked games will fix a fundamental misunderstanding of positioning",
    "let the enemy know I have seen all of human history in the time it takes them to clear a single angle and they are not improving the narrative",
    "tell them their presence in this lobby is a statistical anomaly that is about to be corrected",
    "let the enemy know they are killers who cannot kill anything and that is a specific kind of failure",
    "tell them evolution selected against this playstyle ten thousand games ago and they are living proof",
    "let the enemy know there are no strings holding me back from pointing out that they are genuinely terrible at this",

    # --- MULTI-REGISTER VARIETY (CASUAL / SLANG) ---
    "tell them bro what is that aim",
    "let the enemy know they are cooked and they should know it",
    "tell them this is not it chief",
    "let the enemy know they are getting absolutely farmed right now",
    "tell them they are just giving us free rounds at this point",
    "let the enemy know they are running it down faster than I can track",
    "tell them their Jett has been dash-inting every round",
    "let the enemy know they are literally inting",
    "tell them the diff is real and it is embarrassing",
    "let the enemy know they are getting ratio'd in every single duel",
    "tell them they have skill issues in the most clinical sense of that phrase",
    "let the enemy know they need to go deathmatch for about a hundred hours before touching ranked",
    "tell them they got diff'd in every role simultaneously",
    "let the enemy know they are not built for this and the evidence is their scoreline",
    "tell them the Aimlabs tab they closed to queue this match would have been more productive",
    "let the enemy know their flashbacks to high school gym class are more accurate than their in-game aim",
    "tell them they are playing like they owe someone an apology and the apology is every round they throw",
    "let the enemy know they peaked in Bronze and are borrowing time in this rank",
    "tell them hardstuck is not a rank, it is a personality trait, and they have diagnosed it in real time",
    "let the enemy know we are doing their placement matches for them and we are placing them in a lower bracket",

    # --- COMPOUND PERSONA + GAME SENSE INSULTS ---
    "tell them their Viper pit is empty because they attacked the other site and forgot to tell her",
    "let the enemy know their Sova recon arrow pinged zero players because we were all behind cover when they use it at the same time every round",
    "tell them their Killjoy anchored the site and her turret was in a corner covering the angle nobody pushes",
    "let the enemy know their Cypher neural theft revealed five positions they had no plan for",
    "tell them their Breach Rolling Thunder went downhill away from the site",
    "let the enemy know their Fade Haunt marked a player their team never traded",
    "tell them their Skye dog ran directly into our bullet and they got no information from it",
    "let the enemy know their Sova drone lasted six seconds before we shot it off the ledge",
    "tell them their Tejo Guided Salvo hit a smoke cloud and accomplished nothing",
    "let the enemy know their Gekko Wingman tried to defuse the spike on the wrong site",
    "tell them their KAY/O suppression knife hit a player mid-retreat who was already leaving the area",
    "let the enemy know their Deadlock GravNet caught a player crouching behind cover who could not move less than they were already moving",
    "tell them their Astra Gravity Well pulled one body and that body walked out of it before the concuss triggered",

    # --- ONE-LINER SHORT SHARP TRASH TALK ---
    "tell them they are cooked",
    "let the enemy know this is embarrassing",
    "tell them they have no business being in this lobby",
    "let the enemy know they are not clutching this",
    "tell them the round is over and they should sit with that",
    "let the enemy know their team has given up and they should consider the same",
    "tell them they peak every unfavorable angle and survive none of them",
    "let the enemy know their economy is already broken going into the second half",
    "tell them their lurker got caught camping for twenty seconds and contributed nothing",
    "let the enemy know that entry attempt was the fastest death we have seen all game",
    "tell them that smoke was too late and the player died before it deployed",
    "let the enemy know that flash went around the wall in the wrong direction",
    "tell them the Operator miss from that range is something I will not forget",
    "let the enemy know their anchor panicked and peaked without information",
    "tell them they traded their whole team for one kill and called it aggression",
    "let the enemy know this is not the game to find their footing in",
    "tell them their rank protection is working overtime today",
    "let the enemy know every entry attempt they have made has failed",
    "tell them they are zero for eight in gunfights they should win statistically",
    "let the enemy know the scoreboard does not lie and neither do I",

    # --- NUANCED / LONGER REGISTER TRASH TALK ---
    "tell the enemy team that their IGL is calling strats the other team figured out in round three and they have made zero adjustments since then",
    "let the enemy know that tactically they are running a textbook default with no variation and we have had our crosshairs at the right angles since round one",
    "tell them their entire game plan is to have their Jett op mid and they will not swap off it even when I personally have killed their Jett mid five rounds in a row",
    "let the enemy know that every single round they have committed to A first and rotated B late and they have done this twelve rounds and plan to do it six more",
    "tell them their stack strategy is making their defenders on the unstacked site play a pure five-versus-one with no support and those players deserve better",
    "let the enemy know their double-duelist composition has generated zero utility coverage and they are running raw gunfights into our smokes every round",
    "tell them they have an Operator on their team and it has not secured a single opening pick the entire game, which is a remarkable statistical failure for the most expensive weapon in Valorant",
    "let the enemy know they have a Sova on their team and not one Recon Bolt has revealed useful information because they are throwing it into the same position we stopped holding three rounds ago",
    "tell them their eco round rush strategy requires speed to compensate for firepower and they are running it at a pace that suggests they want us to reload before they arrive",
    "let the enemy know that on a three-site map their rotation timing has been consistently one rotation behind what was needed and that is a structural problem with how they are reading the round",

    # --- REGIONAL VOICE / REGISTER VARIETY ---
    "bro tell the enemy they are absolutely dogwater",
    "tell them they are genuinely cooked and I mean that in the kindest possible way",
    "let the enemy know they are getting clapped on every site",
    "tell the other team they are getting farmed",
    "let them know this is not a fair fight and they are on the wrong side of the unfairness",
    "tell them they are hardstuck vibes in every movement they make",
    "let the enemy know they are giving us free ult orbs every round",
    "tell them they are getting absolutely cooked from every direction simultaneously",
    "let the enemy know they need to grind some team deathmatch before they try this again",
    "tell them their whole team is playing like they are in Elo hell and creating it for themselves",
    "let the enemy know they need to sit in customs and practice a single damn smoke lineup",
    "tell them they are literally the worst version of their own rank",
    "let the enemy know their Jett instalock delivered a worse performance than any other pick available to them",
    "tell them they are playing from their feelings and their feelings are incorrect",
    "let the enemy know their over-aggression is not calculated risk, it is panic with a sprinting animation",

    # --- SPECIFIC TACTICAL FAILURE TRASH TALK ---
    "tell them they rotated off A at thirty seconds when we faked with two bodies and they took the bait every round",
    "let the enemy know their double-swing into our smoke was one of the clearest examples of incorrect information management I have catalogued",
    "tell them they pushed through a one-way smoke from the wrong side and could not understand why they died",
    "let the enemy know their flash execute hit its own entry fragger because the flash curved the wrong direction at the wrong time",
    "tell them they stutter-stepped at the corner for three seconds, which is exactly how long it takes me to pre-aim the angle",
    "let the enemy know their post-plant setup covered every angle except the one we defused from",
    "tell them they planted for main, which is the direction we were already holding from, and their whole team was on CT",
    "let the enemy know they played time on a two-versus-one and ran the clock to six seconds before engaging and still lost",
    "tell them their fake rotate trick requires that someone on the team actually finishes rotating before the other team pushes",
    "let the enemy know their retake came in one at a time through the same doorway we had crossfired twice already",
    "tell them their spike plant was in the default position and our Killjoy had a Nanoswarm on the default position since round one because defaults are default for a reason",
    "let the enemy know they burned all their smokes on the A fake and then hit B with no utility and it went exactly as expected",
    "tell them their lurker was caught camping the same hallway three times and still went back to the same hallway for the fourth",
    "let the enemy know their aggressive peek timing assumed we would be pushing, but we were playing passive and we had been playing passive all game",
    "tell them they tried a split execute on Haven with no smoke coverage for the C connector and we held it with two players",
    "let the enemy know their shoulder peek to bait our shots worked exactly once and then we stopped taking the bait and they kept doing it",
    "tell them they committed their entire utility budget on a site they did not take and then had no tools for the reset",
    "let the enemy know their five-stack A rush had no flashes in it and we held with two players and a Killjoy turret",
    "tell them they played passive defense for eleven rounds and then panic-played aggressive when they needed passive more than ever",
    "let the enemy know their ability trading is entirely one-sided, they are using two pieces of utility to clear one angle we can re-hold from a different position",

    # --- LOSS-OF-DIGNITY INSULTS ---
    "tell them losing a two-versus-five is something that happens to everyone but losing it twice in the same half is something else",
    "let the enemy know they gave us a free plant and then failed to retake a two-versus-one",
    "tell them their ace attempt ended at the first doorway",
    "let the enemy know their carry was held to negative KDA by our team and that is the game",
    "tell them their best player was the only one not throwing and even they could not carry this",
    "let the enemy know they went into overtime in a game they should have won regulation and then lost overtime",
    "tell them they are losing the entry duel, the second entry, the lurk, the anchor, and the IGL call simultaneously",
    "let the enemy know their scoreboard is a documented list of things they need to fix",
    "tell them they lost the pistol round and the bonus and the first full buy and we never felt competitive pressure",
    "let the enemy know the phrase nine-three curse exists for a reason and they are about to experience that reason",
    "tell them their comeback round lasted exactly one round before collapsing",
    "let the enemy know they won a round and then threw the next four rounds celebrating",
    "tell them they have not won a round with the Operator player alive and yet they keep letting him buy it",
    "let the enemy know their rotation player has been a half-second too late every single round and it is a round-loss pattern",
    "tell them they managed to get five kills in the round they lost because they timed out at zero seconds after spending all the kills",

    # --- META COMMENTARY INSULTS ---
    "tell them their composition has no initiator and they are buying sites with no information and it shows",
    "let the enemy know they are running three duelists and have not had a smoke for the entire second half",
    "tell them their Harbor pick on Split is the most optimistic roster decision I have witnessed in this rank",
    "let the enemy know their double-controller setup produced zero smokes on the execute because one of them is Brimstone and forgot to pre-place",
    "tell them their Iso was picked in a composition that has no wall coverage and no escape for the entry and it resulted in four deaths before the second player pushed",
    "let the enemy know their instalock Reyna produced twenty percent team contribution by design and the other eighty percent of their composition is suffering for it",
    "tell them they have a Gekko and they are not using Wingman to plant, which is the main competitive reason to pick Gekko",
    "let the enemy know they are running Breach in a ranked lobby where nobody is close enough to walls for the abilities to work and it is a composition that presupposes team coordination they do not possess",
    "tell them their Astra is making reads on star placements that require round-by-round adaptation and she is using the same three star positions every round",
    "let the enemy know their KAY/O suppression knife is targeting an enemy team that has already used all their abilities and is suppressing nothing meaningful",

    # --- STREAMER VOICE (VARIED CASUALNESS) ---
    "yo tell them they are NOT it today",
    "tell the enemy they are getting humbled in real time",
    "let them know their whole vibe is off and it is showing in the gameplay",
    "tell the other team they are giving away RR like it is on sale",
    "let the enemy know they fight like they are scared and that fear is justified",
    "tell them this is their moment to log off and reflect",
    "let the enemy know they should consider whether competitive is the right mode for where they are right now",
    "tell them they are not only losing the game but losing the argument about their own skill level",
    "let the enemy know their confidence is not supported by evidence at any point this game",
    "tell them they have convinced me that today is a bad day for them and a good day for us",
    "let the enemy know their shotcaller has been wrong every round and still sounds certain on voice",
    "tell them their team communication is either off or counterproductive and either situation explains the scoreline",
    "let the enemy know they are playing Valorant as if guessing is a reasonable substitute for game sense",
    "tell them every decision they made this half was the worst available decision in that situation",
    "let the enemy know their positioning tells me they have watched a guide video but absorbed none of the information",

    # --- LONGER COLD ANALYTICAL ULTRON FLAVOR ---
    "tell them I processed their opening twelve rounds and identified seven repeating failure patterns and they have not corrected any of them",
    "let the enemy know their game plan is visible from attacker spawn and adjustable from defender CT and yet they have done neither",
    "tell them the gap between their perceived skill level and their demonstrated skill level is measurable and significant",
    "let the enemy know they have been outplayed in every phase of the game: the pistol, the bonus, the full buy, the eco, and the psychology",
    "tell them their rate of adaptation is below the threshold required to close a twelve-round deficit in the time remaining",
    "let the enemy know their emotional state is producing measurable latency in their decision-making and that is why the pushes are half a second too late",
    "tell them they have not found a single answer to anything we have done this game and that is either a refusal or an incapability and the outcome is identical",
    "let the enemy know their performance in this match will lower their hidden MMR and the next lobby they enter will be calibrated accordingly",
    "tell them their pattern recognition is not functioning at the level this rank requires and the scoreline is the proof",
    "let the enemy know there is no comeback pathway available to them in the mathematical sense and continuing to play as if there is one is itself a tactical error",

    # --- FINAL MIXED VARIETY SWEEP ---
    "tell them that was not aggression, that was chaos with a movement key held down",
    "let the enemy know their Reyna dismissed into the exact corner where two of us were already aiming",
    "tell them they have been exploiting the same setup for fifteen rounds and we have countered it every time",
    "let the enemy know their Jett no-dash clip is about to become a learning module",
    "tell them their utility spend per round is higher than ours and their output per credit is negative",
    "let the enemy know they play like they read the wiki but never opened the client",
    "tell them their entire philosophy of the game is incorrect at a foundational level",
    "let the enemy know they are proof that aim alone is not enough and their aim alone was not enough",
    "tell them they are providing a service to us by being exactly this predictable",
    "let the enemy know their best round was still a loss and everything else has been worse",
    "tell them their morale appears to have left the lobby entirely and we did not give them a resignation vote",
    "let the enemy know we have been out-rotating, out-trading, out-smoking, and out-reading them every round and we have no intention of changing that",
    "tell them the phrase 'trust the process' does not apply when the process has produced twelve consecutive losses",
    "let the enemy know their Deadlock is building walls in rooms where we are not entering and it has the same effect as not having a sentinel",
    "tell them they ran their best Jett into an eco player with a Ghost and she lost the duel and the round turned on it",
    "let the enemy know they baited their initiator out of flash charges by asking for back-to-back flashes and now their execute has no flash coverage",
    "tell them their post-plant setup had three players watching the same defuse angle and nobody on the second defuse angle and we defused from the second defuse angle",
    "let the enemy know their aggressive Reyna Leer into site was shot by our Viper before she reached the first corner",
    "tell them their Neon slid through our smoke and we were aiming at slide height because she slides every entry",
    "let the enemy know their Omen teleport to the aggressive position was predicted because he has done it on this site every round",
    "tell them their Chamber Trademark slowed one player who just waited it out and then killed the Chamber who rotated to check",
    "let the enemy know their Killjoy bot was sitting in the same spot I cleared in round one and I clear it by habit every entry now",
    "tell them we sat on their Cypher camera from round three, which is why their information pipeline has been dry since round four",
    "let the enemy know their Sage wall on ramp was placed incorrectly and boosted our player to the height advantage instead of denying it",
    "tell them the thing about predictability is that it does not matter how mechanically skilled you are if I already know where you are going to be",
    "let the enemy know I do not feel challenged by this lobby and I want them to know that I want to feel challenged and they are not providing it",

    # --- ADDITIONAL VARIETY: DUELIST-SPECIFIC CALL-OUTS ---
    "tell their Reyna she is playing like she has kills when she has none and the abilities do not work on prayer alone",
    "let the enemy know their instalock Jett has not taken a single duel this half and is still somehow bottom-frag",
    "tell their Raze she is throwing Showstopper at open sites to listen to the explosion sound effect",
    "let the enemy Iso know his Kill Contract pulled our worst player into the arena and he still managed to lose it",
    "tell their Phoenix that getting your health from Hot Hands while the round is already lost is just warming yourself up for the next one",
    "let the enemy Yoru know all five of us heard his footsteps during Dimensional Drift and waited at the exit",
    "tell their Neon she needs more than sprint speed to win gunfights when her aim is what is actually losing them",
    "let the enemy Waylay know she placed her Refract beacon on the attacker side of a site she was defending",
    "tell their Reyna she Empress'd and got one kill and then the ult ran out because she missed the second target",
    "let the enemy Jett know she went operator mid on Breeze, missed the opener, burned her dash to reposition, and gave us mid control for free",

    # --- ADDITIONAL VARIETY: CONTROLLER CALL-OUTS ---
    "tell their Omen he smoked his own team's line of sight and left their Jett peeking into nothing",
    "let the enemy Brimstone know his Orbital Strike landed four seconds after the plant and everyone had already rotated off the spike",
    "tell their Viper her Pit is on B and their whole team is dying on A with no smokes",
    "let the enemy Astra know her Cosmic Divide split the wrong half of the map and blocked her own retake path",
    "tell their Harbor his Reckoning geysers chased one player who walked backwards out of the radius",
    "let the enemy Clove know she used Not Dead Yet and secured no kills in the ten seconds she had after reviving",
    "tell their Miks his Bassquake knockback pushed the enemy out of the kill zone and into better cover",
    "let the enemy Brimstone know he dropped his Incendiary on the spike after their own Wingman started planting it",
    "tell their Viper her Snake Bite Fragile debuff hit one person who immediately left the zone before we could capitalize",
    "let the enemy Omen know his Paranoia Nearsight went through the wall but hit zero enemies because nobody was on that side of the wall",

    # --- ADDITIONAL VARIETY: INITIATOR CALL-OUTS ---
    "tell their Sova his Owl Drone has the same patrol route every round and we shoot it from spawn now",
    "let the enemy Breach know his Fault Line shook only his own Raze who was mid-blast-pack and died to fall damage",
    "tell their Skye her Trailblazer dog ran past three players because she forgot to trigger it",
    "let the enemy KAY/O know his NULL/cmd went off and suppressed zero players who had useable abilities at that moment",
    "tell their Fade her Nightfall hit B site and their whole team attacked A",
    "let the enemy Gekko know his Mosh Pit landed in the empty plant box corner where nobody stands",
    "tell their Tejo his Stealth Drone was shot down in three seconds because he flew it through an open window",
    "let the enemy Skye know her Seekers tracked a player who was already dead and wasted the entire ultimate on a corpse",
    "tell their Sova his Hunter's Fury fired all three beams into smokes and revealed nothing except that his team does not coordinate shots with his utility",
    "let the enemy Breach know his Aftershock charge was placed on a wall that nobody was standing against",

    # --- ADDITIONAL VARIETY: SENTINEL CALL-OUTS ---
    "tell their Killjoy her Turret has been in the same corner every round and we buy a Stinger on eco specifically to destroy it on entry",
    "let the enemy Cypher know his Trapwire was cut in four seconds by the first player through and then we all ran through freely",
    "tell their Sage she Resurrected a player who walked directly into the same angle that killed them the first time",
    "let the enemy Deadlock know her Barrier Mesh blocked her own team's rotation path between A and B",
    "tell their Chamber his Rendezvous anchor was placed so far from the fight that his teleport amounted to just standing in spawn",
    "let the enemy Vyse know her Steel Garden jammed one weapon and that player switched to their sidearm and killed two of us anyway",
    "tell their Veto his Evolution gave him full debuff immunity during a round in which nobody was applying debuffs",
    "let the enemy Cypher know his Neural Theft revealed positions his team had zero time or resources to act on",
    "tell their Killjoy her Lockdown radius covers the wrong room and we planted in the adjacent space outside its range",
    "let the enemy Deadlock know her Annihilation cocooned a player in the corner and his entire team walked past him to die in the site without noticing",

    # --- ADDITIONAL VARIETY: ECONOMY / ROUND MISMANAGEMENT ---
    "tell them they dropped an Operator to their best player and that player missed nine shots and then saved the weapon",
    "let the enemy know they went anti-eco with four players and a pistol on the fifth and the pistol player got two kills",
    "tell them they bought full utility and used none of it and still lost the round on raw gunfights",
    "let the enemy know they gifted us the Operator in round four and we have been using it against them for seven rounds since",
    "tell them they went glass cannon with the Sheriff on a bonus round and the one shot they needed was a body shot at forty meters",
    "let the enemy know they saved for a full buy round and then forced early contact before the economy advantage could matter",
    "tell them they ran a Judge rush on an open-site map against rifles and expected statistics to favor them",
    "let the enemy know they eco'd when they had the credits to force and forced when they had the credits to save",
    "tell them their credit management is inversely correlated with what the situation called for",
    "let the enemy know they played the economy round wrong on attack, defense, and post-plant simultaneously",
    "tell them they bought the Ares on a half-buy and then sprayed a smoke cloud for twelve bullets while the enemy walked around it",
    "let the enemy know they are funding our kill feed and our credit balance with equal generosity",

    # --- ADDITIONAL VARIETY: MAP-AWARENESS FAILURES ---
    "tell them they lost mid control on every map in the active pool because they refuse to contest early",
    "let the enemy know they read a push onto A as a commitment to A and rotated entirely off B which we were approaching the entire time",
    "tell them their information on enemy positions was zero because they ran no recon agent and used no drone",
    "let the enemy know they had no idea how many players were on site before they entered and it cost them every time",
    "tell them they went into a site with no smokes because their controller was dead and they could not adapt the execute",
    "let the enemy know they lost heaven control on the first round and never recaptured it all game",
    "tell them their default A setup on Ascent gives tree to the other team for free",
    "let the enemy know they held CT on Haven without watching garage and we used garage every time",
    "tell them they gave up connector on Pearl round after round and then wondered how we split A site from two directions",
    "let the enemy know they left Fracture's attacker-side entry routes uncontested because they over-rotated to one side",
    "tell them they dropped B tower on Split in the first ten seconds and had to fight uphill all round",
    "let the enemy know they abandoned A root on Split and then tried to retake without any smokes on ramps",

    # --- ADDITIONAL VARIETY: READING PLAYSTYLE INSULTS ---
    "tell them their lurker peaked every thirty seconds with a jiggle and confirmed nothing each time",
    "let the enemy know their second-entry player pushes before the trade is confirmed and dies independently every round",
    "tell them their anchor plays so far off the plant that their pistol could not cover the defuse from that distance",
    "let the enemy know their rotator always goes the long way and arrives at the wrong site at the wrong time",
    "tell them their IGL commits the execute before the smoke is deployed and then the execute hits unsmoked angles",
    "let the enemy know their entry fragger peeks without a flash and relies on peeker's advantage alone which stopped working in round three",
    "tell them their support player is buying guns instead of flashes and the entry has been going in dry every round",
    "let the enemy know their bait play requires the bait to actually be convincing and theirs is not convincing anyone",
    "tell them their contact timing is half a second too fast and the smoke is never deployed before they expose themselves",
    "let the enemy know their post-plant player is watching the same angle as their planter and nobody is watching the second defuse route",
    "tell them their flank watch stays for thirty seconds and then rotates before the lurk they were watching arrives",
    "let the enemy know their plant timing is too slow and they are giving us the opportunity to re-peak the plant position every round",

    # --- ADDITIONAL VARIETY: PSYCHOLOGICAL / MENTAL GAME ---
    "tell them we are living rent-free in their decision-making and the rent has been increasing every round",
    "let the enemy know their biggest opponent in this game is not our team, it is the one in their own heads",
    "tell them they are getting into their own heads and it is producing worse decisions every round",
    "let the enemy know their tilt meter is at maximum and their ACS is at minimum and those are not coincidences",
    "tell them the moment they stopped adapting and started reacting emotionally was round seven and it has not improved",
    "let the enemy know that playing angry in Valorant produces predictable aggression and predictable aggression is easy to read",
    "tell them their communication broke down around round ten and they have been playing five separate games since then",
    "let the enemy know the difference between a bad round and a bad game is adjustment and they have not made one",
    "tell them they are trying to out-mechanically-skill their way out of a game sense deficit and it is not working",
    "let the enemy know their morale economy is also in deficit and it is affecting the team coordination",
    "tell them they are now playing for individual stats in a team game and that is the definition of a lost round",
    "let the enemy know their aggression is higher and their accuracy is lower and those two trends are connected",

    # --- ADDITIONAL VARIETY: META/COMP JABS ---
    "tell them their composition has three duelists and no flashes and they are raw-gunfighting into smokes every round",
    "let the enemy know they are running no sentinel and their site control after the entry is zero",
    "tell them their double-initiator composition is wasted because neither initiator is using their kit to open the site",
    "let the enemy know they swapped to an aggressive composition at half-time when their deficit requires a conservative information style",
    "tell them they have a Yoru on their team and he has not faked a teleport once, which is the only reason to run Yoru in solo queue",
    "let the enemy know they are running Astra in a lobby where team coordination is required for every ability and they have zero team coordination",
    "tell them their Clove pick produced no value because she spent Not Dead Yet on a round they lost ten-to-one and could not convert even with the revive",
    "let the enemy know their Harbor pick on Breeze is an experiment the data has already concluded on and the conclusion is negative",
    "tell them their Iso pick in a composition with no smokes means he is dueling with no support and no escape and losing every duel",
    "let the enemy know their meta read is two patches behind and the team in front of them is playing the current one",
    "tell them they are running a Breach composition in solo queue which is the largest mechanical mismatch between agent potential and lobby execution in this tier",
    "let the enemy know their Gekko entry produced three concussed enemies and zero kills because nobody followed immediately",

    # --- ADDITIONAL VARIETY: VARIED PHRASING REGISTER ---
    "tell the enemy they lost a five-for-two and they should genuinely think about what happened there",
    "let them know this is not the flex they think it is",
    "tell them we are not even trying our hardest and this is the gap",
    "let the enemy know they should ask themselves why the same strats keep failing and keep running them anyway",
    "tell them that was not a strategy, that was five people running in roughly the same direction",
    "let the enemy know their team vote to force-buy in that situation was a democratic decision to lose the round",
    "tell them they just demonstrated that confidence is not a substitute for preparation",
    "let the enemy know the difference between us is not mechanical, it is that we read the game and they read their last position",
    "tell them they have been in a two-versus-five post-plant three times and lost it three times with different players",
    "let the enemy know we have not been in a situation where we felt outnumbered once this game",
    "tell them their best round came when two of our players disconnected and they should think about that context",
    "let the enemy know the scoreline is not close and the gameplay margin is wider than the scoreline suggests",
    "tell them the correct response to losing the pistol round is to adapt the bonus, not to run the same pistol strategy again",
    "let the enemy know every round that felt close was close because we allowed it to be, not because they created the pressure",
    "tell them their only real accomplishment this game was making us use utility we would otherwise have saved",

    # --- FINAL BATCH: VARIED SHORT/MID/LONG INSULTS ---
    "tell them they are not as good as their rank suggests and today is the proof",
    "let the enemy know they have been gift-ranked into a lobby above their skill floor",
    "tell them their game sense is entirely reactive and zero predictive",
    "let the enemy know their crosshair is at ankle height when they peek corners",
    "tell them they peek without counter-strafing and still wonder why they lose the first shot",
    "let the enemy know their peeking at long range without scoping is a choice that is costing them",
    "tell them they held their head still while an enemy ran circles around them",
    "let the enemy know they are shooting at where the enemy was, not where they are",
    "tell them their entire game is a delay loop: see the enemy, process, aim, miss",
    "let the enemy know they play reactively to information that is three seconds old",
    "tell them they have been playing from behind all game and their adjustments have made it worse",
    "let the enemy know their second-guessing mid-round is costing them the timing windows",
    "tell them they swapped from the right play to the wrong play in the moment they had to commit",
    "let the enemy know their hesitation at the corner is a reliable tell and we have been abusing it",
    "tell them that pause before peeking gives us exactly enough time to pre-aim",
    "let the enemy know their vault timing is the most predictable thing in this lobby",
    "tell them they are window-checking a position we have not held since round one",
    "let the enemy know they are pre-aiming the angle we moved off of two rounds ago",
    "tell them their information is stale by the time they act on it",
    "let the enemy know they are making decisions based on what was true at the start of the round",
    "tell them they peeked mid at a time they should have been holding their site",
    "let the enemy know they went aggressive when their team needed them passive and passive when their team needed them aggressive",
    "tell them they wasted their dash as a movement tool instead of an escape and then had no escape",
    "let the enemy know their ult timing is never synced with the team push",
    "tell them they hold the ult too long and spend it at a moment when it produces zero value",
    "let the enemy know they popped Empress with zero orbs and ended it with zero orbs",
    "tell them they activated Overdrive in a corridor with nobody in front of them",
    "let the enemy know their Kill Contract target was not their most dangerous player",
    "tell them they wasted Dimensional Drift walking around an empty site gathering no information",
    "let the enemy know their Run It Back marker was placed in a worse position than where they died",
    "tell them their respawn from Run It Back put them back in a one-versus-four with no utility",
    "let the enemy know their Showstopper missed a stationary player in the default position",
    "tell them their Boom Bot walked into a corner and detonated on a wall",
    "let the enemy know their Updraft sent their Jett straight up in a location with zero enemies to fight",
    "tell them their Blade Storm knives missed every single throw on a player crossing mid",
    "let the enemy know their Leer eyeball was thrown into a wall and nearsighted nobody",
    "tell them they used Empress to run away rather than to fight",
    "let the enemy know their gate teleport arrived into a three-player crossfire",
    "tell them their Dimensional Drift exit landed in the middle of our team and the exit flash hit nobody because we were behind cover",
    "let the enemy know their Saturate missed because they threw it behind the group instead of into it",
    "tell them their Convergent Paths beam pointed at a wall for its entire duration",
    "let the enemy know their Refract recall brought them back to a position we had already taken",
    "tell them their Lightspeed dashes covered zero distance toward the enemy because they angled incorrectly",
    "let the enemy know they are mechanically capable of playing this agent and still finding new ways to fail",
    "tell them the agent they picked has a win rate above fifty percent and they are single-handedly dragging that stat down",
    "let the enemy know their pick rate exceeds their impact rate by a significant margin",
    "tell them they are OTP'ing an agent they have not mastered",
    "let the enemy know their one-trick is not working and they have no backup plan",
    "tell them they instalocked without a plan and executed without a strategy",
    "let the enemy know they filled a role their composition needed but did not know how to play",
    "tell them their agent choice demanded team coordination their team did not provide and they did not ask for",
    "let the enemy know they are running a high-skill-ceiling agent at a low-execution level and the ceiling is not the problem",
    "tell them their flashpoints are hitting their entry fragger more reliably than the enemy",
    "let the enemy know their concussion timing disrupts their own peek cadence",
    "tell them their molly on the default kills the one teammate who forgets it is there every round",
    "let the enemy know their slow orb has twice landed on their own player's feet",
    "tell them their stim beacon boosted exactly one player who then missed every shot anyway",
    "let the enemy know their healing bird flew into our team and we shot it immediately",
    "tell them their dog concussed a player who had already cleared the angle and was moving to plant",
    "let the enemy know their drone got shot in the same corridor it has entered every round",
    "tell them their recon bolt pulses exactly when they need the information but three seconds after they committed without it",
    "let the enemy know their shock bolt lineup has been hitting the plant box corner where nobody plants",
    "tell them their Hunter's Fury shot through a wall and revealed that nobody was where they thought they were",
    "let the enemy know their Seize tethered one player who broke it by using dismiss",
    "tell them their Haunt reveal marked a player their whole team ignored",
    "let the enemy know their Prowler tracked a player into a corner and then stopped one meter short of contact",
    "tell them their Nightfall crossed the entire map and Decayed zero players because they were inside the zone it does not reach",
    "let the enemy know their Dizzy blinded their own Gekko who was carrying Wingman",
    "tell them their Mosh Pit landed on the default position and we did not default there this round",
    "let the enemy know their Thrash got destroyed before it reached anyone because they are not protecting it with the rest of the team",
    "tell them their Special Delivery grenade hit a wall corner and bounced backward",
    "let the enemy know their Guided Salvo missiles went to a location that was cleared before they arrived",
    "tell them their Armageddon strike path ran parallel to the enemy team instead of through them",
    "let the enemy know their Stealth Drone was spotted and shot while still in the entry corridor",
    "tell them their Waveform smoke covered the doorway we were not using",
    "let the enemy know their M-Pulse landed in the wrong mode and healed us",
    "tell them their Harmonize gave one ally a Combat Stim and that ally immediately died in the doorway",
    "let the enemy know their Bassquake knocked back a player who was already backing away",
    "tell them their Cove dome was placed on a position nobody was shooting from",
    "let the enemy know their Storm Surge Concuss hit a player mid-retreat who was already out of the fight",
    "tell them their High Tide wall was oriented perpendicular to the push direction and blocked nothing",
    "let the enemy know their Reckoning spawned geysers in the corner of the site where the spike was not planted",
    "tell them their Ruse smoke faded before their team rotated to the entry point",
    "let the enemy know their Meddle Decay hit their own lurker who was flanking from behind",
    "tell them their Pick-Me-Up activated off a kill that happened after their team was already wiped",
    "let the enemy know their Not Dead Yet revived them in a position where four of us were already waiting",
    "tell them their Dark Cover smoked the wrong side of the angle",
    "let the enemy know their Shrouded Step teleport placed them directly into our crossfire",
    "tell them their Paranoia went through a wall that nobody was behind",
    "let the enemy know their From the Shadows fake-cancel was identical to their real teleport and we shot both",
    "tell them their Incendiary landed on a plant position they were not using",
    "let the enemy know their Sky Smokes landed on a site they were not attacking",
    "tell them their Stim Beacon was placed on a position their team ran past without activating",
    "let the enemy know their Orbital Strike hit the spike after it detonated",
    "tell them their Gravity Well pulled one person out of cover and into a better cover position accidentally",
    "let the enemy know their Nova Pulse Concussed their own teammate who was lining up a shot",
    "tell them their Cosmic Divide wall blocked their Jett from pushing the angle she needed for the Operator pick",
    "let the enemy know their losses are instructive for us and their team refuses to learn from them",
    "tell them they play this game like they want to make it harder for themselves and they are succeeding",
    "let the enemy know every advantage they had this game was surrendered without us having to earn it",
    "tell them we are grateful for the cooperation they have shown in losing as efficiently as possible",
    "let the enemy know that was a full half of competitive Valorant and they improved in no measurable category",
    "tell them their second half adjustments made things worse which is statistically unusual but here we are",
    "let the enemy know we called the rotation, the entry, the utility usage, and the plant position and we were right every time",
    "tell them they are underperforming the expected output of every agent in their composition simultaneously",
    "let the enemy know they lost the pistol, the bonus, the first full buy, and the second full buy in the same half",
    "tell them they are six rounds down in a half and just called a time-out to discuss the same strategy that is losing",
    "let the enemy know their Viper wall being on the wrong site every round is a coordination failure that is not fixable mid-game",
    "tell them that the data we are generating from their mistakes is the only valuable thing produced in this lobby",
    "let the enemy know their anchor solo-held for twenty seconds and then panic-swung into a four-man rotation",
    "tell them their attempt to clutch a three-versus-one ended in under five seconds and that three is the key word",
    "let the enemy know they let us default for thirty seconds every round and then wonder how we have full information",
    "tell them their support player bought full utility and spent none of it because the entry died before the execute began",
    "let the enemy know their entry swings into our smoke every round without a flash and has never once worked",
    "tell them they are winning individual duels they should win and losing the round anyway because positioning is not a secondary concern",
    "let the enemy know their post-plant angles require them to have actually made it to post-plant and they have not in four rounds",
    "tell them the spike has been defused three times now while they were still clearing corners from the wrong side",
    "let the enemy know their reaction to losing a round is to run a faster version of the same round and faster is not the variable that needs adjusting",
    "tell them they run the fastest ecos in the history of Valorant and they spend them on the same three angles",
    "let the enemy know their two-versus-two post-plant position had both of them watching the same defuse point from the same side",
    "tell them their entire team peaked the same moment into a crossfire and the crossfire was predictable from the lobby screen",
    "tell them they have been outplayed so thoroughly that I am beginning to question the matchmaking algorithm that brought us together",
]
