"""Vocab pack: var_economy_buys  (kind=relay, ~700 cases)

Domain: All facets of Valorant in-game economy and buy-phase decision-making.
Covers: full buy / eco / save / force buy / half buy / bonus round / pistol round /
anti-eco / drop system / credit checks / loss-bonus awareness / weapon choices /
armor choices / ability spend / enemy econ reads / glass-cannon plays / thrifty /
team econ sync / save exits / econ-informed round-plan pivots.

Phrasing distribution: raw streamer callouts (short), explicit relay directives
("tell my team..."), indirect asks ("let them know..."), slang-heavy, regional
voice, long-form reasoning, terse one-liners, question-tagged asks, British/Aus
inflection, frustrated tilt-voice, confident IGL voice, humble support voice.

Every item is a relay (kind=relay): the streamer speaks; Ultron relays it.
"""

ITEMS = [
    # ── FULL BUY ──────────────────────────────────────────────────────────────
    "tell my team full buy this round",
    "tell them we're buying, everyone get a rifle",
    "let my teammates know we can full buy",
    "tell my squad everyone buy rifles and heavy armor",
    "tell them Vandal and armor, we have the creds",
    "tell my team buy up, we're full buying",
    "let my team know buy round, rifles and all utility",
    "tell them we're rich this round, buy everything",
    "tell my teammates get a Phantom and heavy, full loadout",
    "tell my squad full buy, no excuses, we have credits",
    "tell them don't save, full buy now",
    "tell my team buy rifles, buy armor, buy all util",
    "let my teammates know we go full send this round economically",
    "tell them Vandals and Phantoms across the board",
    "tell my team we can afford full utility too, buy it all",
    "tell my squad full buy this round, we earned it",
    "tell them all buy, we have 5k each",
    "tell my team rifle and heavy, that's the standard",
    "let my team know buy phase is free, spend it",
    "tell them we full buy this round, no holding back",
    "tell my teammates all buy, skip nothing",
    "tell them heavy armor, rifle, full util - the works",
    "tell my team we're at full buy threshold, everyone spend",
    "let my squad know we full buy, play for the win",
    "tell them rifle up, we can take this fight head-on",

    # ── ECO / SAVE ────────────────────────────────────────────────────────────
    "tell my team save this round",
    "tell them we eco this round",
    "let my teammates know we're saving",
    "tell my squad eco round, don't buy",
    "tell them save your credits, don't spend",
    "tell my team full save, buy nothing",
    "let my team know we're banking this round",
    "tell them eco and play smart, don't give away guns",
    "tell my teammates save round, pistols only",
    "tell them we save because we need the full buy next round",
    "let my squad know this is a sacrifice round, just save",
    "tell them Classic only this round",
    "tell my team buy nothing and live if you can",
    "tell my teammates full save, Classic or Shorty max",
    "tell them don't spend a single credit, hard save",
    "tell my team we eco and farm some kills if we can",
    "let my team know this is an eco round, play angles",
    "tell them save, try to get a trade at least",
    "tell my squad eco but contest the plant if possible",
    "tell them economy reset, we save now and buy next",
    "tell my teammates we need two saves to get back to full buy",
    "tell them one more eco and we're full buying",
    "let my team know this save sets up next round's full buy",
    "tell them we have a plan: eco now, buy rifles next",
    "tell my squad don't risk the gun, just save and rotate",
    "tell my teammates it's a save round, don't throw the rifle",
    "tell them save exit, don't die trying to win this",
    "tell my team save your weapon, round is lost",
    "let my team know round's gone, save your guns",
    "tell them the round is over, just save",
    "tell my squad save exit now, don't feed them kills",
    "tell them keep the rifle, back out safe",
    "tell my team the round is cooked, just don't die",
    "let my teammates know cut your losses and save",
    "tell them back off and save, no heroics",
    "tell my team save the gun and don't feed them ult charge",
    "tell them save round, play passive, survive",
    "let my squad know this round's over, preserve your loadout",
    "tell them save mode, no unnecessary duels",
    "tell my team we can't win this, just save",

    # ── FORCE BUY ─────────────────────────────────────────────────────────────
    "tell my team we're forcing this round",
    "tell them force buy, spend everything you have",
    "let my teammates know we force this round, no saving",
    "tell my squad forcing here, buy whatever you can afford",
    "tell them forced round, yolo buy",
    "tell my team force it, we have to take a shot",
    "let my team know we force because we can't eco into a 3-0",
    "tell them spend everything, this is a force round",
    "tell my teammates force buy round, all in",
    "tell them we force because the loss bonus is maxed anyway",
    "let my squad know this is a force, don't hold anything back",
    "tell them force buy, enemy is probably weak too",
    "tell my team go force, Sheriff and light armor at minimum",
    "let my teammates know it's a force round so play aggressive",
    "tell them coordinate the force, same weapon everyone",
    "tell my team Spectres for everyone, coordinated force",
    "tell my squad all Spectre force this round",
    "tell them we force with Spectres and light armor",
    "tell my team we can't save our way out of this, force",
    "let my team know we need to force, can't keep ecoing",
    "tell them buy what you have and we force together",
    "tell my teammates pistol force this round, Sheriffs if you can",
    "tell them force because they might be on eco too",
    "tell my squad eco force this one, spend it all",
    "tell them we all force, maybe land a Thrifty",
    "tell my teammates Bulldog force if you have 2k",
    "tell them Guardian force, it's a cheaper rifle than Vandal",
    "let my team know forcing here because momentum matters more than eco",
    "tell them buy everything even if it's just a Frenzy and armor",
    "tell my squad force and rush, don't play passive on a force",

    # ── HALF BUY / LIGHT BUY ─────────────────────────────────────────────────
    "tell my team half buy this round",
    "tell them light buy, Spectre and light armor",
    "let my teammates know we half buy",
    "tell my squad SMGs and light shields, half buy",
    "tell them half buy round, no rifles",
    "tell my team we half buy to stay competitive but protect economy",
    "let my team know half eco this round",
    "tell them Spectre and light shield if you have it",
    "tell my teammates half buy, save the rest for next round's rifles",
    "tell them Marshal if you can, otherwise Spectre",
    "let my squad know half buy: Spectre or Ghost, light armor",
    "tell them buy what keeps you safe but don't spend rifle money",
    "tell my team half buy, we're in the 2-3k range",
    "tell my teammates it's a partial buy, not a full one",
    "let my team know half buy round, Spectre is the play",
    "tell them affordable rifles only, Bulldog or Guardian",
    "tell my squad Guardian force if you have 2.2k, Spectre otherwise",
    "tell them buy light this round, we're not at full buy threshold",
    "let my teammates know we half buy to preserve our next round",
    "tell them SMG round, play accordingly",
    "tell my team we half buy, don't play like you have a Vandal",
    "tell them half buy, play tight angles, don't peek",
    "let my squad know half buy so play smart not aggressive",
    "tell them light buy round, be economical with your peeking",
    "tell my team half buy and maybe we get a Thrifty",

    # ── PISTOL ROUND ──────────────────────────────────────────────────────────
    "tell my team Ghost this round",
    "tell them pistol round, decide Ghost or Frenzy",
    "let my teammates know get a Ghost for the pistol round",
    "tell my squad everyone buy Ghost and an ability",
    "tell them buy a Ghost and light armor if possible",
    "tell my team Frenzy rush for pistol round",
    "let my team know Sheriff pistol if you're confident with headshots",
    "tell them pistol round, don't waste credits, buy smart",
    "tell my teammates buy one ability each minimum for pistol",
    "tell them pistol round strat: Ghost plus one ability",
    "let my squad know pistol round plan: Ghost mid, nobody stack",
    "tell them it's an 800-credit round, prioritise the pistol",
    "tell my team buy armor if you can afford pistol plus armor",
    "let my teammates know pistol round, standard buy, nothing greedy",
    "tell them Frenzy if you want run-and-gun, Ghost for aiming",
    "tell my squad Classic plus an ability if credits are tight",
    "tell them pistol round, play it safe, we need the W",
    "tell my team play solid pistol round fundamentals",
    "let my team know pistol round, don't buy a Shorty unless you're entry",
    "tell them it's the second half pistol, reset and play clean",

    # ── BONUS ROUND ───────────────────────────────────────────────────────────
    "tell my team bonus round, Spectres",
    "tell them bonus round, buy a Spectre and keep your pistol",
    "let my teammates know it's bonus round, SMG plus keep our guns",
    "tell my squad Spectre and light armor for the bonus round",
    "tell them bonus round, don't buy a rifle, save for round 3",
    "let my team know it's the bonus round, Spectre and light shield",
    "tell them we won pistol, now bonus round standard: Spectre",
    "tell my teammates second round bonus, don't over-spend",
    "tell them keep the Ghost from pistol and buy a Spectre",
    "let my squad know buy Spectre and hold credits for next round",
    "tell them bonus round strategy: SMG, light armor, save the rest",
    "tell my team bonus round, don't upgrade to rifles yet",
    "let my teammates know it's a bonus round so play conservatively with it",
    "tell them Spectre round, play for picks not execute",
    "tell my team bonus round and don't throw it, maintain the advantage",

    # ── ANTI-ECO ──────────────────────────────────────────────────────────────
    "tell my team they're on eco, play anti-eco",
    "tell them enemy is saving, buy light this round",
    "let my teammates know they're on eco, don't over-invest",
    "tell my squad anti-eco round, Spectre and light shield",
    "tell them they're saving so don't buy Operators, just rifles",
    "tell my team enemy eco round, don't give away full-buy guns",
    "let my team know they're saving, we play anti-eco",
    "tell them they're on pistols, we go anti-eco with SMGs",
    "tell my teammates enemy eco, buy light and don't feed them guns",
    "tell them anti-eco: Spectre and light armor, keep your rifle for next round",
    "let my squad know it's their eco round, we play conservative",
    "tell them they're saving hard, don't over-invest this round",
    "tell my team anti-eco, don't let them turn this into a gun round",
    "let my teammates know they're on Classic, we don't need Operators",
    "tell them enemy on eco, play passive and don't die with rifles",
    "tell my team they're saving, easy round if we don't throw it",
    "tell my squad enemy eco, play for safe kills not risky pushes",
    "tell them they're weak this round, play smart anti-eco",
    "let my team know enemy is in full save, play for picks",
    "tell them anti-eco round, they might rush so be ready",
    "tell my teammates watch for eco rush, they're saving and might go all-in",
    "tell them on eco rounds they often rush, play with that in mind",
    "let my squad know watch for the eco rush, play tight",
    "tell them they're saving and will probably rush or go aggressive",
    "tell my team they're on eco, expect chaos and an aggressive push",

    # ── DROP SYSTEM ───────────────────────────────────────────────────────────
    "tell my team drop someone a rifle",
    "tell them someone drop a Vandal for the entry",
    "let my teammates know who needs a drop",
    "tell my squad check who needs a rifle and drop them one",
    "tell them drop a Phantom to whoever is short",
    "tell my team the short players need drops, sort it out",
    "let my team know someone buy and drop a Vandal to the fragger",
    "tell them request a rifle if you can't afford one",
    "tell my teammates drop each other rifles if you have the credits",
    "tell them if you're at 5k drop a rifle to whoever's short",
    "let my squad know check the requests and fill the drops",
    "tell them buy the requested weapon if you have credits to spare",
    "tell my team who's got enough to drop someone?",
    "let my teammates know one of you drop a rifle to the short guy",
    "tell them drop the Vandal, I'll buy my own armor",
    "tell my team drop weapons before buy phase ends",
    "tell my squad fill the drops or we're uneven",
    "tell them someone with 5k drop a rifle to whoever requested",
    "let my team know be generous with drops, we need even buys",
    "tell them if you're capped, drop a rifle to help the team",
    "tell my teammates I'll drop you a Spectre if you're broke",
    "tell them can anyone drop me a rifle?",
    "let my squad know drop your spare credits into weapons for teammates",
    "tell them the drop system exists, use it so we're all even",
    "tell my team buy for your teammate, they requested a Phantom",

    # ── CREDIT CHECK / ECON CHECK ─────────────────────────────────────────────
    "tell my team econ check",
    "tell them do a quick econ check",
    "let my teammates know call out your credits",
    "tell my squad what's everyone's econ?",
    "tell them everyone call their credits",
    "tell my team report your creds so we can decide",
    "let my team know econ check: can everyone full buy?",
    "tell them call out how much you have",
    "tell my teammates econ check before we decide to force or save",
    "tell them who can full buy and who can't?",
    "let my squad know quick credits check before buy phase ends",
    "tell them I need to know if we can all full buy or if we drop",
    "tell my team what's the lowest credits on our side?",
    "let my teammates know check your credits and tell the team",
    "tell them call econ so the IGL can make the call",
    "tell my squad run an econ check, we need to know if we force or save",
    "tell them everyone just shout out their credits real fast",
    "tell my team we need to coordinate buys, call your creds",
    "let my team know econ transparency now: what's everyone working with?",
    "tell them quick econ audit before buy phase closes",

    # ── LOSS BONUS AWARENESS ──────────────────────────────────────────────────
    "tell my team we're on a loss streak so we have extra credits",
    "tell them loss bonus kicks in, we have more credits than usual",
    "let my teammates know we're getting a good loss bonus this round",
    "tell my squad we've lost two in a row, the bonus rounds up our credits",
    "tell them three losses means maximum loss bonus, we're nearly at full buy",
    "tell my team the loss bonus means we can force with better guns",
    "let my team know we've accumulated enough loss bonus to full buy",
    "tell them don't panic about the losses, the loss bonus evens it out",
    "tell my teammates loss bonus is helping us, check your credits",
    "tell them after two straight losses we should all have enough to force",
    "let my squad know the catch-up money means we're not as broke as we feel",
    "tell them the loss bonus stacks up to like 2900 per person after three",
    "tell my team we have the max loss bonus now, eco gets us to full buy",
    "let my teammates know one good save and we'll have full buy credits",
    "tell them the loss streak is actually working in our economy's favor",
    "tell my team we save this round and the loss bonus plus carry-over gets us full buy next",
    "tell them the catch-up mechanic means eco one more and we buy rifles",
    "let my squad know the loss bonus stacks so one eco round sets us up",
    "tell them we're at loss streak two, bonus is 2400, one save and we full buy",
    "tell my teammates don't tilt about the round losses, the credits are recovering",

    # ── WEAPON-SPECIFIC ECONOMY CALLS ────────────────────────────────────────
    "tell my team buy Vandals not Phantoms this round",
    "tell them Phantom is fine, don't stress about Vandal vs Phantom",
    "let my teammates know go Vandal if you have one-tap confidence",
    "tell my squad Guardian if you're low on credits but want a rifle feel",
    "tell them Bulldog is fine this round, save the extra 800",
    "tell my team go Spectre if that's all you can afford",
    "let my team know Spectre is actually good if they're on eco",
    "tell them SMG round means Spectre and play aggressive angles",
    "tell my teammates if you can't afford a rifle, get a Sheriff at least",
    "tell them Sheriff plus heavy armor is a legit half-buy for duelists",
    "let my squad know don't buy the Op unless you're the designated Op player",
    "tell them Op is 4700, only buy it if you specifically play it",
    "tell my team if you have an Operator, don't force into close range",
    "let my teammates know Odin only if we're post-planting passively",
    "tell them Marshal is 950 and can work on eco rounds, consider it",
    "tell my team Outlaw is a budget Op alternative, 2400, worth considering",
    "let my squad know Guardian for long-range eco, it's 2250 and one-taps",
    "tell them Bucky or Judge on eco if you wanna contest close range",
    "tell my teammates Judge rush is a thing on eco rounds, it can work",
    "tell them Stinger is only 1100 and works up close if you're tight on credits",
    "let my team know the Ares isn't bad in post-plant situations if you're rich",
    "tell them if you have 900 on eco buy a Marshal, it's worth it for one-taps",
    "tell my squad Bandit is the 600-credit pistol, new option between Ghost and Sheriff",
    "tell them Frenzy for run-and-gun eco if you're playing aggressive",
    "tell my team Ghost is the standard pistol buy, 500 and silenced",

    # ── ARMOR ECONOMY CALLS ───────────────────────────────────────────────────
    "tell my team buy heavy armor if you're going full buy",
    "tell them heavy armor is a thousand credits, it's worth it",
    "let my teammates know get light armor at minimum",
    "tell my squad light shield is only 400, always buy it if you can",
    "tell them light armor on a force, heavy only if you're full buying",
    "tell my team skip armor on eco rounds, save those credits",
    "let my team know Regen Shield is a thing, 650 and it repairs itself",
    "tell them Regen Shield is between light and heavy, consider it on half buys",
    "tell my teammates light armor first, then save for rifle next round",
    "tell them if you're on Sheriff half-buy, get heavy armor with it",
    "let my squad know on full buy it's always heavy armor, don't skimp",
    "tell them glass cannon is valid only if you're Op-ing from distance",
    "tell my team skip armor if you're playing back-site and going Op",
    "let my teammates know heavy armor on a force even if it means a worse gun",
    "tell them armor absorbs damage, always try to have at least light",

    # ── ABILITY SPEND ECONOMY ─────────────────────────────────────────────────
    "tell my team buy your utility this round",
    "tell them full buy means full utility too",
    "let my teammates know buy your abilities, we need the util",
    "tell my squad don't skip abilities on a full buy",
    "tell them ability skip on eco, save the credits",
    "tell my team save your util money on eco rounds",
    "let my team know if you're on force, maybe skip one ability to afford armor",
    "tell them prioritize armor over abilities on a force round",
    "tell my teammates Jett, buy your cloudbursts and updrafts",
    "tell them Sage buy your wall and slow orbs please",
    "let my squad know Killjoy, get your Nanoswarms this round",
    "tell them Sova, buy the Owl Drone if you're full buying",
    "tell my team Brimstone, get the Incendiary plus extra smokes",
    "let my teammates know Reyna, your Leers are cheap, buy them all",
    "tell them Cypher, get your Trapwires for info",
    "tell my squad controller buy your smokes at minimum even on a force",
    "tell them sentinel, at least buy one trap this round",
    "tell my team if you can only afford abilities OR armor, go armor",
    "let my team know on eco just skip everything, save it all",
    "tell them full utility is the standard, we're buying round so buy it",

    # ── ENEMY ECONOMY INTEL ───────────────────────────────────────────────────
    "tell my team they're on eco",
    "tell them enemy is saving this round",
    "let my teammates know they're on a save round",
    "tell my squad enemy economy is weak right now",
    "tell them they're probably on pistols or Classics",
    "tell my team enemy can't buy rifles this round",
    "let my team know they lost two in a row so they might force",
    "tell them enemy might be forcing with Sheriffs and light armor",
    "tell my teammates enemy is on eco so play a bit looser",
    "tell them if they're on eco this is a free round, don't throw it",
    "let my squad know their economy is hurting, they lost three straight",
    "tell them the enemy saved so next round they'll full buy",
    "tell my team enemy is saving now and will full buy next round",
    "let my teammates know they eco'd so expect rifles from them next round",
    "tell them they're setting up a full buy next, watch out",
    "tell my squad they have rifles, don't underestimate them this round",
    "tell them enemy full buy this round, play tight",
    "let my team know they all have Vandals, respect the rifles",
    "tell them enemy has Op on B, be careful swinging",
    "tell my teammates someone on their side has the Operator, call it out",
    "tell them enemy bought Op so don't take long angles carelessly",
    "let my squad know their Jett is Op-ing, play accordingly",
    "tell them they might have mismatched buys, some rifles some pistols",
    "tell my team enemy is on a mixed buy, some full some eco",
    "let my teammates know their economy is inconsistent, some bought some didn't",

    # ── SITUATIONAL ECONOMY CALLS ─────────────────────────────────────────────
    "tell my team we full buy because we're up on the scoreboard",
    "tell them we can buy freely, we're up 8-3",
    "let my teammates know we save because we're already winning",
    "tell my squad we're behind on rounds so we force this one",
    "tell them if we win this round we go full buy next",
    "tell my team win this and we full buy the next three",
    "let my team know we need to stretch our economy over these next rounds",
    "tell them plant the spike even on eco for the 300 credits each",
    "tell my teammates spike plant bonus is 300 each, try to get it on eco",
    "tell them plant the spike for the creds even if you think you'll lose",
    "let my squad know planting earns us 300 each, worth going for",
    "tell them every kill on eco is 200 credits, plays matter",
    "tell my team eco kills earn us creds, don't play scared",
    "let my teammates know try to get one or two kills on eco, it adds up",
    "tell them kill credits and plant credits can save an eco round",
    "tell my team after this save we should hit the full buy threshold",
    "tell them we're one round of saving away from full buy",
    "let my squad know one more save and we buy properly",
    "tell them this eco sets up everything next round",
    "tell my team sacrifice this round and win the next two buying full",

    # ── NUANCED ECONOMY STRATEGY ──────────────────────────────────────────────
    "tell my team we don't force because we'd lose the rifles and reset our economy",
    "tell them don't force when the loss bonus is still building",
    "let my teammates know forcing now kills the next round's economy too",
    "tell my squad if we force and lose we can't buy next round either",
    "tell them the risk of forcing isn't worth it right now",
    "tell my team we could force but I'd rather save and guarantee full buy",
    "let my team know we're right on the edge, it's a judgment call",
    "tell them if three of us are at 3900 and two aren't, we drop and buy",
    "tell my teammates if four can full buy, drop the fifth a rifle",
    "tell them four of us can full buy so we drop whoever is short",
    "let my squad know don't leave a teammate on a bad loadout if you can drop",
    "tell them team economy is more important than individual credits",
    "tell my team we buy as a unit, not individually",
    "let my teammates know the whole team needs to be on the same buy tier",
    "tell them uneven buys hurt us more than a coordinated eco",
    "tell my squad don't half-buy while everyone else full buys",
    "tell them buy at the same level as your teammates",
    "let my team know we decide together what to buy before buy phase ends",
    "tell them don't do anything crazy without agreeing on a buy first",
    "tell my teammates we need everyone on the same page with economy",
    "tell them our economy is healthy, let's not screw it up",
    "let my squad know protect the economy lead, don't get greedy",
    "tell them we're in a good economy position, let's maintain it",
    "tell my team play to protect the economy advantage",
    "let my teammates know don't break the bank if we're already ahead",

    # ── SAVE EXIT / GUN PRESERVATION ─────────────────────────────────────────
    "tell my team save the guns, round is lost",
    "tell them round's over, everyone save their rifles",
    "let my teammates know save exit, don't die for nothing",
    "tell my squad save your weapons, we need them next round",
    "tell them the round is done, preserve your loadout",
    "tell my team don't fight it, just save your gun",
    "let my team know save mode, live to buy next round",
    "tell them get out alive with your rifle, that's the priority",
    "tell my teammates save exit priority: keep the rifle alive",
    "tell them don't be a hero, just save the gun",
    "let my squad know we lost, now protect the economy",
    "tell them save your weapon and don't feed them kills or ult charge",
    "tell my team saving the rifle is worth more than one last trade",
    "let my teammates know exit with the rifle, don't trade it away",
    "tell them saving your gun saves your next round's economy",
    "tell my team if the round is definitely lost, save exit now",
    "tell them the spike is planted and we're down numbers, save",
    "let my squad know we can't retake this, just save weapons",
    "tell them lost round, save priority, don't chase kills",
    "tell my teammates run away, keep the rifle alive for next round",

    # ── THRIFTY / ECO FRAG SITUATIONS ────────────────────────────────────────
    "tell my team if we win this on eco that's a Thrifty",
    "tell them let's see if we can pull a Thrifty this eco round",
    "let my teammates know we can upset them on eco if we play right",
    "tell my squad eco kill equals free rifle, go for the pick",
    "tell them if we kill their full-buy players we get free guns",
    "tell my team eco frags mean free weapons, play for the pick-up",
    "let my team know grab their dropped guns if we get a kill on eco",
    "tell them pick up their weapons if you kill someone on eco",
    "tell my teammates free rifle if you kill a full-buy enemy on eco",
    "tell them eco round doesn't mean passive, look for the gun pick-up",
    "let my squad know go for the eco frag, their guns are worth taking",
    "tell them if you pick up an enemy rifle on eco you're fine next round",
    "tell my team coordinate the eco rush for the Thrifty",
    "let my teammates know this eco can win us the round if we coordinate",
    "tell them eco doesn't mean defeated, play smart and take your shots",
    "tell my squad even on eco we can beat them if we angle well",
    "tell them get the eco kill, grab the drop, play their gun",
    "let my team know eco rush coordination: agree on a site and commit",
    "tell them rushed eco on B, everyone commit at thirty seconds",
    "tell my teammates eco rush is on, we all go A, no splits",

    # ── GLASS CANNON / SPECIAL BUILDS ────────────────────────────────────────
    "tell my team don't buy armor if you're going Op on a glass cannon build",
    "tell them glass cannon Op: skip armor, get the Operator",
    "let my teammates know Op no armor is a glass cannon, tell them to respect it",
    "tell my squad if you Op without armor make sure you play it safe",
    "tell them pocket Guardian this round: Guardian and light armor",
    "tell my team Guardian on a half-buy is a legitimate play",
    "let my team know tell them someone's going pocket Guardian this round",
    "tell them Outlaw as the budget Op option, 2400 and hits hard",
    "tell my teammates Outlaw for the semi-auto sniper play on a half-buy",
    "tell them Judge rush is viable on eco, make noise about it",

    # ── VARIED REGISTER / SLANG HEAVY ────────────────────────────────────────
    "tell my team we're broke, eco it up",
    "tell them we ain't buying this round, creds are low",
    "let my teammates know the team's wallets are empty, save round",
    "tell my squad we're poverty this round, don't even try to buy",
    "tell them credit situation is grim, eco or die",
    "tell my team the bank is busted, full eco",
    "let my team know we ball out next round, save for now",
    "tell them eco this round so we can go hard next",
    "tell my teammates save up and nuke them next round",
    "tell them we're destitute, Classic only",
    "let my squad know creds are cooked, we pistol round it",
    "tell them one more save and we're cashed up",
    "tell my team we're flush with credits this round, full send it",
    "let my teammates know creds are looking good, don't waste them",
    "tell them economy is healthy, buy confidently",
    "tell my squad we're sitting on five ks each, go ham",
    "tell them loaded up this round, don't play like we're poor",
    "let my team know we're economically in a great spot",
    "tell them the credits are there, buy what you need",
    "tell my teammates don't sleep on the credits we have, spend them well",

    # ── REGIONAL / VARIED VOICE ───────────────────────────────────────────────
    "tell my mates to save this round",
    "let the boys know we eco this one",
    "tell my crew we're saving, yeah?",
    "tell them we're doing a save round, cheers",
    "let my guys know to full buy, we've got heaps of creds",
    "tell my squad we buying, got proper credits this time",
    "tell my team we save aye, next round we buy",
    "let my teammates know go light buy, not enough for rifles",
    "tell the lads force buy this round",
    "tell my boys half buy, Spectres and light shields",
    "let the squad know we're saving up bruv",
    "tell my team yeah we eco, no question",
    "tell them save round init, just don't buy",
    "let my teammates know honestly just save the round",
    "tell them proper eco this one, not even a pistol if possible",
    "tell my squad we're absolutely skint, full save",
    "let my team know we're on a budget this round",
    "tell them this is a credits-preservation round",
    "tell my teammates we're in fiscal austerity mode",
    "tell them economic conservation round, save everything",

    # ── TILT-VOICE / FRUSTRATED ───────────────────────────────────────────────
    "tell my team to save because we keep throwing our rifles",
    "tell them save the gun this round, stop dying with rifles",
    "let my teammates know we can't keep wasting full-buy guns",
    "tell my squad stop force buying when our economy is wrecked",
    "tell them we wouldn't be broke if people saved their rifles last round",
    "tell my team stop dying with the Op, that's why we can't buy",
    "let my team know we lost economy because we didn't save exit properly",
    "tell them the economy is bad because someone kept their rifle and died",
    "tell my teammates this is why I say save exit, look at our credits now",
    "tell them we wouldn't need to eco if you saved last round",
    "let my squad know just save the rifle, it's not hard",
    "tell them one person's greed for the last kill cost us a round of economy",
    "tell my team please don't give away free guns on eco rounds",
    "let my teammates know dying with rifles on a lost round hurts everyone's econ",
    "tell them this eco is self-inflicted, could have saved last round",

    # ── IGL VOICE / CONFIDENT CALLS ──────────────────────────────────────────
    "tell my team the call is full buy, trust the economy",
    "tell them I'm calling full buy, everyone commit",
    "let my teammates know the economy call is force, we need this round",
    "tell my squad the play is eco, I'm making the call",
    "tell them we half buy and here's why: we can't all full buy anyway",
    "tell my team listen to the econ call: we save",
    "let my team know economy decision is made: we force",
    "tell them the econ call: half buy and play for picks",
    "tell my teammates I'm calling anti-eco, they're saving",
    "tell them alright team, the call is bonus round: Spectres",
    "let my squad know the economy is fine, buy confidently this round",
    "tell them coordinated eco, all five of us pistols and one ability",
    "tell my team unified buy decision: Guardian force if you have 2.2k, Spectre otherwise",
    "let my teammates know the budget for this round is 2000 per person maximum",
    "tell them alright, nobody spending more than 2500 this round",

    # ── COMPLEX COMPOUND ECONOMY READS ────────────────────────────────────────
    "tell my team save this round because they full bought and we can't win the gun fight",
    "tell them we eco this round because we're already up and economy is fine",
    "let my teammates know force this one because we can't keep letting them breathe",
    "tell my squad we half buy because three of us aren't at full buy threshold",
    "tell them full buy this round because the loss streak maxed our loss bonus",
    "let my team know we force because one more save and we might lose the round count",
    "tell them eco this round because we can't afford to fight their full buy",
    "tell my teammates save because even a Thrifty win doesn't help our economy long-term",
    "tell them force this one because we're up round count and can absorb the risk",
    "let my squad know full buy because we just won three and have stacked credits",
    "tell them half buy because we need to balance economy with staying in the match",
    "tell my team eco because after this save the loss bonus rounds us all up",
    "let my teammates know force round because at this point we have nothing to lose",
    "tell them we anti-eco because their buy was terrible and we don't want to waste Operators",
    "tell my squad full buy because they're likely on eco and we need to capitalize",

    # ── ROUND-FLOW ECONOMY SEQUENCING ────────────────────────────────────────
    "tell my team save now and full buy next round",
    "tell them eco this round and buy next",
    "let my teammates know we save, then force, then full buy",
    "tell my squad this is our sacrifice round so next round we buy",
    "tell them we eco for two rounds then buy",
    "tell my team after this eco we should all hit full buy threshold",
    "let my team know next round is our buy round if we save this",
    "tell them just get through this eco and we reset properly",
    "tell my teammates this eco sets up everything downstream",
    "tell them we play the long game: eco now, buy round, dominate",
    "let my squad know round 8 is our designated buy round, build toward it",
    "tell them the econ plan is: this round save, next round force, round after full buy",
    "tell my team if we eco here we guarantee full buy for at least two rounds",
    "let my teammates know the economy schedule: save, buy, buy, reassess",
    "tell them think of this eco round as an investment",

    # ── SHORT TERSE RELAY-STYLE ───────────────────────────────────────────────
    "tell them save",
    "tell them eco",
    "tell them force buy",
    "tell them half buy",
    "tell them full buy",
    "tell them buy round",
    "tell them save round",
    "tell them drop rifles",
    "tell them buy armor",
    "tell them skip armor",
    "tell them econ check",
    "tell them call credits",
    "tell them they're saving",
    "tell them they're buying",
    "tell them anti-eco",
    "tell them buy Spectres",
    "tell them Vandals this round",
    "tell them bonus round buys",
    "tell them pistol round plan",
    "tell them save the rifle",

    # ── CONVERSATIONAL / NATURAL RELAY ───────────────────────────────────────
    "tell them I think we should save this round honestly",
    "let my team know I feel like we should just eco here",
    "tell them not sure if we should force or save, but I say save",
    "tell my teammates my gut says full buy but check the credits first",
    "let my squad know probably a half buy this round based on what I can see",
    "tell them I reckon we force this one, what do you think",
    "tell my team I'm leaning toward eco, let me know if you disagree",
    "let my teammates know my call is force buy but I'm open to the team's read",
    "tell them I might be wrong but I think we should eco and reset",
    "let my squad know the credits look tight, probably a half buy situation",
    "tell them heads up: we might be looking at a force this round",
    "tell my team just giving a heads up: I think it's a save round",
    "let my teammates know check your credits, I think we might be on a half buy",
    "tell them not entirely sure on the econ call but I'm thinking force",
    "let my squad know I'm making the eco call, let's see how it goes",

    # ── AGENT-LINKED ECONOMY CALLS ───────────────────────────────────────────
    "tell them Jett needs 900 credits for full util, factor that in",
    "tell my team Sage is expensive to fully kit, she needs like 800 for abilities",
    "let my teammates know Raze full util is around 700, make sure she can afford it",
    "tell them Sova buy the Owl Drone if we're full buying, it's 400 but worth it",
    "tell my squad Killjoy's full util is only 600, she should always buy on full buy rounds",
    "tell them Astra is the cheapest controller to kit out, only 450 for full stars",
    "let my team know Clove has cheap util, no reason not to buy abilities",
    "tell them if we're half buying, Omen can still buy his Paranoia",
    "tell my teammates on a force, Brimstone can afford smokes plus the incendiary",
    "tell them Viper's abilities are 600 total, manageable even on a force",
    "let my squad know Chamber's Headhunter costs per bullet, factor that into buys",
    "tell them Tejo's Stealth Drone costs 400 for the extra, skip it on a force",
    "tell my team KAY/O's knife is free, he's cheap to buy util for",
    "let my teammates know Gekko is only 550 for full util, very economy friendly",
    "tell them on a half-buy round sentinels should still afford at least one trap",

    # ── ROUND-TYPE EDGE CASES ────────────────────────────────────────────────
    "tell my team even if we're winning, eco one round to build a credit buffer",
    "tell them don't spend your credit cap, max hold is 9000",
    "let my teammates know if you're near the credit cap, spend before next round",
    "tell my squad you can't hold more than 9000 credits, spend if you're near the cap",
    "tell them near the credit cap means you should buy something or drop it",
    "tell my team buy something or you'll lose credits to the cap",
    "let my team know capping credits is money lost, spend if you're close",
    "tell them even on eco, if you're about to cap, buy light armor",
    "tell my teammates if you have 8500 credits, buy something before round start",
    "tell them the credit ceiling is real, don't sit at the cap",
    "let my squad know win bonus is 3000 per person, that sets up the next buy",
    "tell them after a win we each get 3k, plan accordingly",
    "tell my team win bonus plus carry-over means we buy next round for sure",
    "let my teammates know the kill credit is 200 each, multi-kills add up",
    "tell them every kill earns 200, grind those creds on eco",
    "tell my team the spike plant earns 300 each, always worth going for",
    "tell my squad plant even on a loss for the bonus creds",
    "let my team know defuse bonus also exists, 300 per person on defense",
    "tell them if we defuse we all get 300 extra, worth playing for the defuse",
    "tell my teammates coordinated economy is the meta, let's play it right",

    # ── MISC ECONOMY SCENARIOS ────────────────────────────────────────────────
    "tell my team we're doing an all-Spectre force this round",
    "tell them we coordinate the force: Spectres for everyone",
    "let my teammates know coordinated force: pick one weapon and all buy it",
    "tell my squad all-Judge rush on eco, just send it",
    "tell them if we're forcing let's at least be consistent with what we buy",
    "tell my team Bulldog is viable on a force if you have 2050",
    "let my team know Guardian force for the one-tap potential on a cheap rifle",
    "tell them if half the team can buy rifles, drop the other half",
    "tell my teammates the strong half drops the short half and we play even",
    "tell them drop economy: rich players buy for the poorer ones",
    "let my squad know economy pooling through drops is the competitive way to play",
    "tell them don't refuse a drop, it helps the whole team",
    "tell my team accept the drop graciously and play the weapon well",
    "let my teammates know offer drops if you have extra, it's team investment",
    "tell them being selfish with credits hurts the whole team's economy",
    "tell my squad the goal is 5 even loadouts, not 2 great ones and 3 terrible ones",
    "tell them coordination in the buy phase is as important as coordination in the round",
    "let my team know we buy together or we die separately on a force",
    "tell them we're on the same team economically, pool knowledge and drops",
    "tell my teammates economy is a team stat, not a personal one",

    # ── HALF-SAVE / HYBRID CALLS ──────────────────────────────────────────────
    "tell my team half-eco this round, keep 2k for next",
    "tell them spend 1500 max and bank the rest",
    "let my teammates know half-eco: buy light and save the rifle money",
    "tell my squad light buy but keep credits above 3k for next round",
    "tell them we play a middle ground: Sheriff and light armor",
    "tell my team Sheriff plus heavy is a valid half-buy if you're a duelist",
    "let my team know half buy and we should still have full buy after this round",
    "tell them partial buy: grab armor and one ability minimum",
    "tell my teammates buy something that keeps you competitive without wrecking economy",
    "tell them don't throw all your credits away but don't go naked either",

    # ── CREDIT-SPECIFIC NUMERIC CALLS ────────────────────────────────────────
    "tell my team if you have 3900 or more you can full buy",
    "tell them 3900 is the minimum for rifle and heavy armor, check your credits",
    "let my teammates know 4500 is the comfortable full buy threshold with utility",
    "tell my squad 5000 credits is the full buy ceiling for most agents",
    "tell them if you have less than 3900 you can't full buy, adjust accordingly",
    "tell my team 2900 is rifle price: Vandal or Phantom, that's your check",
    "let my team know heavy armor is 1000 credits, add that to your rifle cost",
    "tell them Spectre is 1600 and light armor is 400, that's a 2000 credit half buy",
    "tell my teammates Ghost is 500 and light armor is 400, that's a pistol half buy for 900",
    "tell them Sheriff and heavy armor is 1800 total, a real option on a short round",
    "let my squad know Bulldog at 2050 plus light armor at 400 is 2450, a solid force option",
    "tell them Guardian at 2250 plus heavy armor at 1000 is 3250 minimum for sniper play",
    "tell my team Op is 4700 alone, factor in whether that leaves room for armor",
    "let my teammates know Marshal at 950 is the eco sniper play",
    "tell them Outlaw at 2400 is between Guardian and Op for the sniper economy option",

    # ── TIMING AND ROUND-STATE ECONOMY ───────────────────────────────────────
    "tell my team buy phase closes in ten seconds, decide now",
    "tell them make your buy decision, clock is running",
    "let my teammates know buy phase is ending, commit to a buy",
    "tell my squad we're at round six, economy should be stable if we've been consistent",
    "tell them mid-game economy check: are we in a sustainable buy pattern?",
    "tell my team we're past the pistol rounds, economy should be set by now",
    "let my team know if our economy is still rocky at round eight, someone messed up",
    "tell them track the economy from round to round, it matters",
    "tell my teammates every forced buy with a loss sets us back two rounds",
    "tell them think ahead: does this buy decision cost us the next round too?",
    "let my squad know think about the economy three rounds ahead, not just this one",
    "tell them winning this round on a full buy gives us the buy round advantage",
    "tell my team if we win this buy round we stay in good economy shape",
    "let my teammates know maintaining buy parity with the enemy team is the goal",
    "tell them we break their economy by winning gun rounds, so buy right",

    # ── ENEMY BUY READS ───────────────────────────────────────────────────────
    "tell my team check the scoreboard for their loadouts",
    "tell them look at what guns they dropped, that tells us their economy",
    "let my teammates know watch for their buy patterns each round",
    "tell my squad if they keep forcing they'll burn out economically",
    "tell them enemy has been forcing three rounds straight, their economy should crack",
    "tell my team they can't sustain this force-buy pattern much longer",
    "let my team know if we win this round their economy collapses",
    "tell them break their economy by winning this gun round",
    "tell my teammates forcing against a full-buy team is their mistake",
    "tell them if they're forced into a force, we win the gun fight",
    "let my squad know their economy is fragile right now, press the advantage",
    "tell them the enemy economy is in trouble after three lost force rounds",
    "tell my team they're forced to force buy because they can't eco into a deficit",
    "let my teammates know recognize when the enemy is economically vulnerable",
    "tell them their economy tilt is an opportunity for us",

    # ── SCENARIO-SPECIFIC ECONOMY ─────────────────────────────────────────────
    "tell my team overtime economy: everyone starts at 5000 credits",
    "tell them in overtime we all have equal credits, it resets",
    "let my teammates know OT means even economy, no carry-over advantage",
    "tell my squad overtime round: 5000 each, full buy is on for everyone",
    "tell them pistol round of the second half, reset and buy fresh",
    "tell my team second half pistol round, we start clean at 800 credits",
    "let my team know second half pistol is the same as first half: 800 credits each",
    "tell them second half pistol round, we need to win this one for the bonus",
    "tell my teammates winning second half pistol sets up the bonus round advantage again",
    "tell them second half bonus round: same rules, Spectre and light armor",
    "let my squad know we swap sides and reset the momentum, economy included",
    "tell them we're on defense now, buy smarter for passive play",
    "tell my team attacking side economy: buy aggressively for executes",
    "let my teammates know defender economy: play for information and picks, not just gunfights",
    "tell them defense doesn't need to out-frag, just play economy-conscious",

    # ── PASSIVE ECONOMY VOICE ────────────────────────────────────────────────
    "let my team know the economy is fine, don't stress",
    "tell them we're in a good spot economically, just play",
    "tell my teammates the credits are healthy, no panic buys needed",
    "let my squad know we're economically stable, make good buy decisions",
    "tell them the econ is good, trust it and buy accordingly",
    "tell my team we're not in a crisis, standard buy this round",
    "let my teammates know economy is positive, no need to force or save",
    "tell them the credits are where they should be, buy normally",
    "tell my squad economic health is strong, go full buy without worry",
    "let my team know no economy pressure this round, buy freely",

    # ── BUY-PHASE COMMUNICATION ETIQUETTE ────────────────────────────────────
    "tell my team communicate in buy phase, not mid-round",
    "tell them sort out the economy before the round starts",
    "let my teammates know agree on the buy type before buy phase ends",
    "tell my squad the buy decision should be unanimous, not individual",
    "tell them don't go rogue with a buy nobody agreed on",
    "tell my team don't force when the team agreed to save",
    "let my team know if someone saves when everyone else bought, that's a problem",
    "tell them we all agree on the buy type first, then everyone commits",
    "tell my teammates don't full buy while your teammates eco, that breaks the team",
    "tell them unity in the buy phase is as important as unity in the round",
]
