ITEMS = [
    # --- Raw damage numbers, various phrasings ---
    "tell them I tagged the Jett for 80",
    "let them know I hit the Reyna for 60, no armor",
    "tell the team I doinked the Sova through the wall",
    "tell them he's one shot, pushing B main",
    "let the team know the Phoenix is lit, I hit him 88",
    "tell them I tagged the Neon 74 through the smoke",
    "tell my team the Raze is at like 20 HP, she's one shot",
    "let them know I hit the Killjoy 52 in the leg, she's low",
    "tell them the Iso is one shot, go swing",
    "let the team know I doinked the Cypher, he's barely alive",
    "tell them the Fade is tagged 90, push her",
    "tell the team he's one shot at window, no armor",
    "let them know I hit the Breach 48, he has no shield",
    "tell them the Viper is lit, I got her for 66",
    "tell my team I dinked the Jett, she's one bullet away",
    "let them know I smacked the Skye for 86, she's done",
    "tell them the Brimstone is on 12 HP, swing him",
    "tell the team I tagged the Omen 72, low health left side",
    "let them know I hit the Sage through the wall for 55",
    "tell them the Gekko is low, I hit him 79 in the arm",
    "let the team know I gooshed the Chamber, he's one deag away",
    "tell them the Deadlock took 83 from me, she's hurting",
    "tell my team I tagged the Tejo for 60, no heavy armor",
    "let them know the Waylay is lit up, she's sitting at maybe 18 HP",
    "tell them I hit the Vyse 77 around the corner",
    "let the team know the Neon is one shot in the left elbow",
    "tell them the Harbor is tagged 91, rotate and clean him up",
    "let them know I hit the Clove for 58, she has regen shield but she's still low",
    "tell the team I dinked the Reyna, one tap closes it out",
    "tell them the Astra is at 15 HP, she's standing at default",
    # --- Trade calls, direct ---
    "tell them to trade me if I go in",
    "let the team know to immediately trade if I die pushing",
    "tell them swing the second I make contact, just trade me",
    "let my team know to refrag instantly if I go down A main",
    "tell them trade for trade, commit hard behind me",
    "let them know I'm swinging on the contact, just trade",
    "tell my team to swing B when I hit the corner, trade it up",
    "tell them he killed me, get the trade now",
    "let them know I'm dead, trade is right there at elbow",
    "tell the team to go in and clean up the trade",
    "tell them I got the first shot in, trade me and clean up",
    "let them know I hit him 68 before I died, go get the trade",
    "tell them to double swing and trade me, I'm down",
    "tell my team he's lit from the fight I just had, go trade",
    "let the team know I died but I tagged him 76, trade is free",
    "tell them that if I die there I need an instant trade at window",
    "let them know I went in for the entry, just trade the kill",
    "tell them the Jett dashed but I hit her 55 before she went, go find her",
    "tell my team the trade has to happen right now or we lose the round",
    "let them know to always trade on B, no baiting",
    # --- One shot / dink callouts ---
    "tell them the Killjoy is one shot at B site back",
    "let the team know the Raze is one bullet away, she's near the boxes",
    "tell them one shot on the Sova, he's holding main",
    "let them know she's one shot, Reyna has no orbs either",
    "tell the team the Phoenix is one shot, he just used his flash",
    "tell them one tap left on the Neon, she's at the corner",
    "let them know I doinked him for 99, he is literally one shot",
    "tell them the Omen is one shot somewhere in CT side",
    "tell my team the Breach is one shot right side of short",
    "let them know Gekko is one shot and his Wingman is reclaimed so push",
    "tell them Fade is one shot and she has no Seize left",
    "let them know Deadlock is one shot hiding near the sensor",
    "tell them Veto is one shot but watch out he might evo",
    "tell my team Tejo is one shot somewhere off-angle in B link",
    "let them know Astra is one shot, she's probably in astral right now",
    "tell them the Vyse is one shot, careful she might pop the rose",
    "tell my team one shot on the Iso but he might have his shield from double tap",
    "let them know Chamber is one shot, watch his TP he might run",
    "tell them the Skye is one shot and she only has one hawk left",
    "let the team know KAY/O is one shot and he hasn't used his knife yet",
    # --- 'He's lit' / 'tagged' style ---
    "tell them he's lit, go push him",
    "let my team know she's lit from the duel, swing now",
    "tell them the Jett is lit up bad after that exchange",
    "let the team know she's tagged, not dead but close",
    "tell them the Vandal guy is lit from my spray",
    "let them know I tagged someone at B long, they're hurting",
    "tell them the Op player is lit, don't let him recover",
    "tell my team the entry is lit, capitalize before he heals",
    "let them know Reyna is lit but she'll devour if she gets a kill, be fast",
    "tell them the Phoenix is lit but he's standing in his wall healing",
    "let my team know the Sage is lit but watch for the heal orb",
    "tell them Clove is lit and she just used pick-me-up so she's back to full, careful",
    "let them know the Brimstone is lit after the molly, push him",
    "tell my team Viper is tagged from the snakebite she walked into",
    "tell them the Neon is lit from the relay bolt, she can't sprint straight",
    "let them know Harbor is tagged, the cove is gone too so no cover",
    # --- Compound: damage + ability state ---
    "tell them I hit the Jett for 70 and her dash is used up",
    "let them know the Reyna is at 30 HP and she has no soul orbs",
    "tell the team the Phoenix is lit 80 and his run it back is already active, kill him before it resets",
    "tell them the Raze is low and she already used the showstopper",
    "let them know the Skye is tagged 65 and she's out of hawks",
    "tell my team the KAY/O is one shot and his knife is on cooldown",
    "tell them the Killjoy is lit 75 and her lockdown is placed, don't let her activate it",
    "let them know the Chamber is tagged 50 and no tour de force left this round",
    "tell them the Sova is one shot and both shock darts are used",
    "tell my team the Breach is lit 88 and rolling thunder is gone",
    "let them know Fade is tagged 60 and nightfall already hit this round",
    "tell them the Viper is lit and she's out of fuel on the wall",
    "tell my team the Iso is low and his contingency wall is down",
    "let them know Neon is tagged 80 and her overdrive is gone",
    "tell them Gekko is lit and the wingman is still out so watch it",
    "let the team know Deadlock is tagged 72 and annihilation is not charged yet",
    "tell them the Tejo is low and both missiles already fired this round",
    "let them know Omen is lit 85 and he stepped already, one more step left",
    "tell my team Waylay is tagged and her refract beacon is still down, she might snap back",
    "let them know Cypher is lit 66 and his cam is destroyed, he's blind",
    # --- No armor callouts ---
    "tell them the Sova has no armor, one body shot kills",
    "let the team know the Raze is running no shield this round",
    "tell them he's 100 HP but no armor, vandal body shot ends it",
    "let my team know Killjoy has no heavy armor, she went light",
    "tell them she's full HP but completely unshielded, make it count",
    "let them know the entire enemy team looks like they went light shield",
    "tell my team the Op player has no armor on, don't give him space",
    "tell them Breach is eco, no gun no armor, rush him",
    "let them know Omen bought no armor this round, three bullets max",
    "tell the team Sage is unshielded, don't waste time peeking carefully",
    # --- 'He's 100' (undamaged enemies) ---
    "tell them the Jett is completely fresh, no damage on her",
    "let the team know the Reyna is at full, she's 100 HP and heavy armor",
    "tell them nobody hit the Chamber yet, he's full health at CT",
    "let them know their anchor is untouched, hundred HP on A site",
    "tell my team don't push, the Viper is full and has pit ready",
    # --- Ownership/direction: OUR team took damage ---
    "tell them our Raze is low, she needs the trade now",
    "let the team know our Skye is tagged 50 in mid, she needs help",
    "tell them our KAY/O took 80 damage, push while they're on him",
    "let the team know I'm at 30 HP, peeking is risky right now",
    "tell them our Jett is one shot after that duel, she needs a trade",
    "let my team know I got tagged 60, still in the fight but be aware",
    "tell them our Breach is lit in lobby, he might fall if they push",
    "let them know I took 80 and I'm behind the box, need someone to swing with me",
    # --- Dink acknowledgment / refrag cue ---
    "tell them I doinked the Killjoy, go push the turret angle",
    "let them know I dinked someone at short, they're one bullet away",
    "tell my team I got the dink on the Reyna before she dismissed",
    "let them know I doinked the Jett before she dashed, she's one shot somewhere",
    "tell them I got the ding on the Omen before he stepped away",
    "let the team know I dinked the Fade when she haunted us",
    "tell them I hit the Sova for 99 with a shock dart, he is literally one shot",
    "let them know I dinked the Iso right before he walled off",
    "tell my team I gooshed the Harbor, one tap finishes him",
    "let them know I dinked the Vyse, she barely survived the arc rose activation",
    # --- Trade timing and coordination ---
    "tell them to swing on my contact, tight timing",
    "let them know to entry and I will second entry and trade",
    "tell my team to push the second they hear my shots",
    "let them know I'm going to hard peek and they need to follow immediately",
    "tell them to double swing when I make contact at B main",
    "let the team know to swing B when the trade opens up",
    "tell them pop the flash and swing on my dink, no hesitation",
    "let them know I'm trading in, don't bait me",
    "tell my team to push hard the moment I die in there, trade or we lose the round",
    "let them know swing after his shot at me, classic trade",
    "tell them the Jett peeked me, I'm low, swing now for the trade",
    "let the team know I committed to the push, trade me immediately if I go down",
    "tell them I need someone second entry right after me, trade setup",
    "let them know to stack the corner and trade out their op player",
    "tell my team I'm going in blind, just trade on whatever happens",
    # --- Damage from abilities ---
    "tell them I hit the Raze with a shock dart for 65, she's hurting",
    "let the team know I tagged the Reyna with the recon bolt and she got scanned",
    "tell them the Viper molly hit for 60, the one holding site is burned",
    "let my team know the fault line concussed them, their aim is trash right now",
    "tell them the rolling thunder knocked them up and they're all lit",
    "let them know the prowler hit the Jett for full nearsight",
    "tell them the Sova beamed two people with fury, both are lit",
    "let my team know the Tejo sticky hit the Breach for 35, he's low on that side",
    "tell them the nightfall hit three of them, they're all decayed and deaf",
    "let them know the grounded them with the gravnet, their whole rush just stopped",
    "tell my team the Killjoy nano popped on the defuser, he's burning at the spike",
    "let them know the Astra grav pulled two of them and they're vulnerable",
    "tell them the Harbor wave nearsighted the whole site",
    "let them know Breach aftershocked through the wall, the defuser took big damage",
    "tell my team the Clove meddle hit the Neon, she's decayed",
    # --- Damage context: exact HP estimates ---
    "tell them I think the Jett is around 15 HP, she dashed away low",
    "let the team know the Reyna ran into the molly, she might be under 20",
    "tell them I burned the Phoenix 40 HP with the Brimstone orbital",
    "let my team know I traded shots with the Iso, I hit him 55 but I took 72",
    "tell them the Sage walled but I damaged her before she hid, about 50 on her",
    "let them know I fired through the Cypher cage and tagged someone for 66",
    "tell them the Killjoy might be 30 HP after the molly fight",
    "let my team know the Viper walked out of her own wall damaged, she's under 50",
    "tell them I sprayed at the smoke and hit someone for around 80",
    "let them know someone is low near heaven, I got a dink through the boxes",
    # --- Collateral / multi-hit ---
    "tell them I think I hit two with that spray, both are lit",
    "let my team know I tagged the Jett and someone behind her for 50 each",
    "tell them the shock bolt hit two people at default, both are damaged",
    "let them know the showstopper clipped both of them, one is one shot",
    "tell my team the rolling thunder hit all five of them, go in",
    "let them know I sprayed through the smoke and hit two, push now",
    "tell them the recon bolt revealed three at B, they're clustered",
    "let my team know the Tejo missiles hit the plant corner, at least two took damage",
    "tell them the molly at the defuse spot burned two people, check your kills",
    "let them know the Breach flashed two and I swung and hit both, they're lit",
    # --- Wallbang / through-surface damage ---
    "tell them I wallbanged the Cypher hiding behind the box for 44",
    "let my team know I penned the Killjoy through the thin wall for 55",
    "tell them I shot through the floor and hit someone below for 37",
    "let them know I shot the Sova through the crate for 62, he's low",
    "tell my team I prefire'd the corner and hit the Op player for 78",
    "let them know I traced movement through the wall and hit them for 40",
    # --- Prefiring / anticipated damage ---
    "tell them I prefire'd the Jett's usual angle and hit her 80",
    "let the team know I pre-aimed the corner and got the dink before he peeked",
    "tell them I saw the shadow and sprayed, tagged someone 60 off peak",
    "let my team know I timed the peek and hit the entry for 88",
    # --- Post-fight damage reports ---
    "tell them that fight took a lot out of me, I'm at 35 HP",
    "let the team know I won the duel but I'm at 22 HP, need support",
    "tell them I got the kill but I took 75 damage in the exchange",
    "let my team know the 1v1 went my way but I'm barely alive at 18 HP",
    "tell them I traded two kills but I'm critically low now",
    "let them know I clutched the fight but I'm on a sliver",
    "tell my team I got the ace on that site but I'm down to 8 HP",
    "let them know I won the duel and I'm at 40, good enough to hold",
    "tell them I got the trade but I need a heal, Sage please orb me",
    "let my team know I'm at 12 HP from that 1v2 entry, push on my position",
    # --- Asking about damage intel ---
    "ask them how much HP the Raze has",
    "tell them to check the kill feed and see what HP the entry is at",
    "ask if anyone tagged the Op player before he peeked me",
    "tell them to confirm whether the Reyna has any orbs left after that fight",
    "ask the team if anyone hit the Killjoy before she hid in the turret corner",
    "let them know I need intel on the Fade's health after that molly",
    "ask them whether the Clove is low or whether she picked up after killing Mika",
    # --- Specific agent HP vulnerabilities / mechanics ---
    "tell them the Reyna has no soul orbs now so she can't dismiss, go for her",
    "let my team know the Reyna is low and she can't devour, she's stuck",
    "tell them the Phoenix is in his wall healing right now, push before he recovers",
    "let them know the Sage is channeling a heal on herself, she's stationary",
    "tell my team the Clove just used pick-me-up after that kill, she topped off",
    "let them know Veto is evolved so flashes and nanos won't work, go for it anyway",
    "tell them the Iso has his double tap shield up so the first hit won't count",
    "let my team know the Waylay still has her refract beacon down, don't let her snap back",
    "tell them Neon is almost out of overdrive timer, push when she stops sliding",
    "let them know the Jett has no dash anymore, she burned it on the peek",
    # --- 'No armor' + agent context ---
    "tell them the Raze went raw rifles no shield, she's fragile",
    "let my team know the Omen is on a glass cannon build, one body shot ends it",
    "tell them the Yoru is running no armor for the fake entry, punish it",
    "let the team know the Sova has light shield only, no heavy this round",
    "tell them the Killjoy went budget no shield, if you peek her it's a free kill",
    # --- Trade aftermath / analysis ---
    "tell them that was a clean trade, now we're 4v4",
    "let the team know the entry worked, trade happened, push the site",
    "tell them the trade cost us one but the Killjoy is dead, site is open",
    "let my team know the trade made it even, now we execute",
    "tell them we got the trade and now their Sova is gone, smokes and go",
    "let them know the refrag happened, the Op guy is dead, push B now",
    "tell my team we traded two for two but we have utility left and they don't",
    "let them know the trade was clean but their Sage still has rez, be careful",
    "tell them we traded one and now it's 4v5 in their favor, fall back",
    "let them know the trade didn't happen and now it's a 3v5, reset",
    # --- Baiting vs trading ---
    "tell them stop baiting and take the trade",
    "let the team know the entry is dying and nobody is swinging, that's a bait",
    "tell them to stop watching and swing on his death, we can't bait like this",
    "let my team know the Reyna is baiting us into trading poorly",
    "tell them the Killjoy is holding back and baiting our entry, don't fall for it",
    "let them know the Iso is using the entry as bait to get kill contract value",
    "tell my team stop baiting the 1v1 and just trade when I call it",
    "let them know that's not a trade, that's just two deaths, swing smarter",
    # --- Damage during specific tactical phases ---
    "tell them the defuser is burning alive, don't push yet",
    "let my team know the retake caught two in the molly, they're lit",
    "tell them I tagged the planter for 60 before the spike went down",
    "let them know the entry hit 80 damage on our anchor before dying",
    "tell my team I burned the Sage mid-heal for 55, finish her off",
    "let them know the orbital already ticked 100 damage on whoever is in there",
    "tell them the viper pit is decaying two of them right now, push the other side",
    "let my team know I hit the defuser for 78 through the wall, he's one shot",
    "tell them the Brimstone orbital is going to finish the spike defender if he stays",
    "let them know I sprayed through the Astra smoke and hit someone for 55",
    # --- Hit confirmation / shot-by-shot ---
    "tell them I got the dink on the first shot but missed the second, he's low",
    "let my team know I one-tapped his head but the second guy is unscathed",
    "tell them the spray went through the smoke and I tracked him for about 70 damage",
    "let them know I landed two body shots on the Jett before she dashed, probably 80 total",
    "tell my team I traded shots with the Op player, I hit him 65 but he hit me 140",
    "let them know I ran the whole mag into the smoke and I'm pretty sure I got someone",
    "tell them I noscoped the Raze for 88 with the marshal coming around the corner",
    "let my team know I got the first two bullets into the Reyna then she dismissed",
    "tell them I hit the moving Neon for 76 on the run, that's about a one shot now",
    "let them know I fired through the Cypher cage on audio and tagged someone 44",
    # --- Damage reports during clutch ---
    "tell them last one is one shot somewhere on site, careful",
    "let my team know I'm in a 1v2 and both of them are lit",
    "tell them the clutch is live, last enemy is tagged 70 at the spike",
    "let the team know I'm 1v1 for the round and he's at 30 HP",
    "tell my team the last one is high HP, I need help here",
    "let them know I got one down, the remaining one is 100 HP heavy armor",
    "tell them the 1v2 is going, I hit one for 80 and the other is untouched",
    "let my team know I'm clutching but I'm at 12 HP and he's still 100",
    # --- Diverse phrasings / regional voices ---
    "yo tell the team the Raze is absolutely cooked, she's on like 5 HP",
    "bro tell them I just dinked someone at elbow, they're basically dead",
    "tell the boys the Jett got lit up from my spray, she's done for",
    "let them know I smacked the Sova 80, he's one shot mate",
    "tell the squad the Iso is hurting after that trade, finish him off",
    "yo let them know that dude is literally one bullet, push him now",
    "tell the team I got the dink but he's still alive, someone clean it up",
    "let my guys know the Killjoy is on fumes after the molly, push her",
    "dude tell them the Neon is basically dead, she ran into my shots for 90",
    "tell the guys she's one shot near the boxes, just go around the corner",
    "let the crew know I hit the entry for 68, she's limping",
    "yo tell them the Breach is hurting bad, like 20 HP left",
    "tell my boys the Phoenix is in his wall trying to heal, rush him now before he recovers",
    "let them know I punched the Reyna for 88 but she dismissed away",
    "dude tell the team the Raze is like one grenade away from dying",
    # --- Slang damage terms ---
    "tell them I gooshed the Killjoy through the smoke",
    "let my team know I absolutely dinked the Jett on the peek",
    "tell them I wiped the Iso for 80 with one spray before he walled",
    "let them know I beamed the Neon in the legs for 70, she's crippled",
    "tell them I tickled the Sova for 44 through the box but he's still up",
    "let my team know I fried the Fade for 82 with the shock dart lineup",
    "tell them I tagged the Reyna with 75 damage before her empress started",
    "let them know I bodied the Breach for 68 through the fault line dust",
    "tell them I creased the Omen for 55 as he was stepping away",
    "let my team know I zapped the Cypher with the relay bolt for 60",
    # --- Specific map location damage reports ---
    "tell them I tagged someone in A lobby for 80, they haven't entered site yet",
    "let the team know someone in B main is low, I sprayed through the gap",
    "tell them the Op player in mid is lit 75 from the shock dart lineup",
    "let my team know I hit someone at A short for 60 before falling back",
    "tell them there's a low HP enemy somewhere in CT side, check the corner",
    "let them know I hit the Killjoy on B site back for 55 before her turret shot me",
    "tell my team I tagged the Raze in garage for 70 with the marshal",
    "tell them I traded shots at mid top and hit someone for 80 up there",
    "let them know I tagged the lurk 65 as they came through the flank",
    "tell the team I burned the heaven player for 77 with the orbital on site",
    "let them know I hit someone at B link for 66 before they retreated",
    "tell my team I sprayed into A elbow and tagged the holding angle for 70",
    "let them know I hit the back site entry for 44 through the smoke on A",
    "tell them someone is lit 80 in the cubby near the spike, don't rush them",
    "let my team know the catwalk player got hit 58 from the shock dart bounce",
    # --- Damage in economy context ---
    "tell them the eco player is 100 HP but he only has a sheriff, don't give him space",
    "let the team know I hit the eco rusher for 80 with the Vandal, he's dead next bullet",
    "tell them even with no shield the entry is putting out damage, stay cautious",
    "let them know the judge rush guy is lit 60, don't let him reach close range",
    "tell my team the eco Sova hit one of us for 55, rally and trade him",
    "let them know they're on anti-eco and the spectre player is full HP, clean him up",
    "tell them the pistol round entry hit me for 72 with a ghost, I'm low",
    "let my team know the bonus round Raze is still doing damage, she has a spectre",
    # --- Damage intel requests / questions ---
    "ask if anyone knows how much HP the Jett has after that window fight",
    "tell them to mark the Reyna on the cam so we know if she healed",
    "ask whether anyone tagged the Op player before the smoke went up",
    "let them know I need confirmation on the Killjoy's HP before I push the site",
    "ask the team if the Sage healed anyone after I hit them",
    "tell them to track the Fade, she might have decayed down from the pit",
    "ask if anyone can see the Viper's health through the cam, she might be low from her own molly",
    "tell my team to check if the Iso has his shield before swinging him",
    "ask whether the Clove picked up after killing our Raze",
    "let them know to confirm whether the Neon took the relay bolt damage or dodged it",
    # --- First-person playstyle / self-report to relay ---
    "tell them I'm pushing in, I need a trade behind me",
    "let them know I'm taking this duel at long, trade me if I go down",
    "tell my team I'm swinging the Op angle, I'll take the dink to get the info",
    "let them know I'm going to bait the Reyna out and if she dismisses I need a swing",
    "tell the team I'm taking the fight at elbow, just follow my shot",
    "let them know I'm dry peeking the corner, someone trade on contact",
    "tell my team I'm going to jiggle the angle and bait a shot, swing when they reveal",
    "let them know I'm spraying the smoke for info, someone push on hit confirmation",
    "tell them I'm taking the Jett duel at short, she either dashes or she's dead",
    "let my team know I'm shoulder peeking to bait the Op shot, then rush them",
    # --- Multi-sentence compound damage + trade callouts ---
    "tell them I hit the Jett for 70 and she dashed away, she's one shot somewhere near CT",
    "let my team know I fought the Iso at elbow, I hit him 55 but he walled off, he's still alive",
    "tell them the Reyna came in empress mode and I hit her 80 before she dismissed, she's one shot",
    "let them know I traded the Raze but I took 68 from her blast pack, I'm low",
    "tell my team I hit the Op player 78 and he ran, find him before he recovers",
    "let them know I fought two at B main, hit one for 90 and one for 40, one is one shot the other is fine",
    "tell them the Killjoy is one shot in the back site corner and her lockdown is already placed, rush before she pops it",
    "let my team know the Sage is lit 65 and she already used her heal on herself, no second orb",
    "tell them the Neon is tagged 80 and overdrive is active, she'll beam us if we let her reach close range",
    "let them know the Sova hit two of us in the shock dart, our entry is one shot and I took 50",
    "tell my team I doinked the Jett on the entry swing and she dashed, she is one shot somewhere but she has a dash left",
    "let them know I double tapped the Breach and killed him but the Skye behind him is completely fresh",
    # --- Diverse register / streamer voice ---
    "tell them bro that dude is literally on his last pixel, one shot him",
    "let the team know she is cooked, I hit her like 90 and she's got nothing left",
    "tell them that was a free dink, somebody please swing the corner",
    "let my guys know the Jett is dead on legs, literally one tap at any range",
    "tell them the Reyna has no souls and no empress and she's lit, she's just a target right now",
    "let them know I absolutely violated the Raze entry, she took like 80 before dying",
    "tell the team the Killjoy is playing on fumes over there, she's one shot",
    "tell them I hit them both in the spray, one is dead next hit and the other is mid HP",
    "let my team know that fight was clean, both targets are lit and we have numbers",
    "tell them the site anchor is barely breathing, her HP is single digits",
    "let them know I got the headshot but missed the kill, she is three pixels from dying",
    "tell my team that Viper is playing on life support, the pit can't save her now",
    # --- Long callouts for off-snap 3B rephrasing ---
    "tell them the Raze hit me for 88 with the rocket and if she reloads for another shot I'm dead",
    "let my team know I had a 1v1 with the Iso and hit him 60 but he walled off and healed with double tap, he is probably back to 80 now",
    "tell them the Killjoy played a nano under the spike and the defuser took 45 damage, he is vulnerable too from the alarmbot",
    "let them know the Jett dashed into the smoke and I sprayed after her, I hit her 70 in the dash but she's somewhere in there and she has no dash charge left",
    "tell my team I traded my life for the Sova and now their Op is sitting completely healthy at back site, push with numbers",
    "let them know the trade chain was two for two and now both teams are on three but they have the spike planted and we have no ult",
    "tell them I got the dink on the Reyna and she dismissed to safety so she survived but she is one shot somewhere in CT and has no orbs to use",
    "let my team know the Fade nightfall hit all five of us, we are all decayed and deafened, the information advantage is completely theirs right now",
    # --- Miscellaneous nuanced scenarios ---
    "tell them the Vyse steel garden went off and all our primaries are jammed, I'm on pistol only",
    "let my team know I can't fire my rifle, Vyse ult hit us, use pistols",
    "tell them the Veto evolved so don't waste the nano or the flash, just shoot him",
    "let them know the Iso contracted our Jett, she's in the arena, 4v4 while the duel plays out",
    "tell them the Chamber used tour de force and his slow field is on the spike, we can't defuse in there",
    "let my team know the Phoenix is in run it back, don't let him get a kill or he comes back at full HP",
    "tell them the Clove is ulting after dying, she needs one kill to stay alive, deny her that kill",
    "let them know the Waylay recalled back to her beacon so the angle we were holding is empty now",
    "tell my team the KAY/O is down in null cmd, one of us has to risk going to revive him",
    "let them know the Sage is rezzing our Raze right now, she's vulnerable during the channel",
    "tell them the Skye sent seekers and they're homing to three of us, nearsight incoming",
    "let my team know the Gekko wingman is heading for the spike to defuse, someone shoot it",
    "tell them the Sova drone tagged the Jett, she's revealed on the minimap",
    "let them know Cypher hit the neural theft on the body, everyone's position is showing",
    "tell my team the Fade haunt is out, we're all going to get trailed if she hits us",
    # --- Damage confirmation across sites ---
    "tell them I hit the A site anchor for 78 before rotating to B",
    "let my team know the B site push hit our anchor for 60, she needs a trade",
    "tell them I tagged someone at C site for 50 before they planted on C",
    "let them know two A site players are lit from the execute entry",
    "tell my team I hit the rotating Jett mid for 55 as she rotated to B",
    "let them know I tagged the Killjoy on site through her own turret for 44",
    # --- Timing-sensitive damage calls ---
    "tell them fast, the Raze is one shot right now before she heals",
    "let them know quick, the Reyna is lit and her empress is about to run out",
    "tell them hurry, the Phoenix is in his wall healing, he'll be full in two seconds",
    "let my team know rush now, the Viper is out of her pit and the 8-second timer is running",
    "tell them the Sage is mid-rez, she's completely open right now, push her",
    "let them know go now while the Neon's overdrive is resetting, she's not beaming",
    "tell them push before the Killjoy's lockdown arms, you have 13 seconds",
    "let my team know the orbital is ticking down, whoever is defusing is taking 60 per second",
    # --- Third-person narrative damage calls (about enemy team) ---
    "tell them their anchor ate the molly for about 80, she stayed too long",
    "let my team know their Op player took 70 from my shock lineup, he's not full",
    "tell them their whole B push ran into the Sage wall and two of them are lit from breaking it",
    "let them know their eco rush took serious damage from the judge shotgun in the hallway",
    "tell my team their entry ate the Raze nade coming around the corner, one shot for sure",
    "let them know their retake players ran into the viper pit decayed, all of them are low",
    "tell them their clutch guy is the only one alive and he's at 30 HP after the 1v3",
    "let my team know their site stack just got hit by rolling thunder and three of them are concussed",
    "tell them their Jett used the entry dash and got lit 80 off the prefire at B lobby",
    "let them know their second entry is untouched, 100 HP, be careful pushing the post-plant",
    # --- Trade vs eco interaction ---
    "tell them trade smartly this round, they're on eco but the entry hit our initiator for 80",
    "let my team know even on eco they got a trade, their pistol player put someone down",
    "tell them the eco rush traded our entry for free, now it's 4v4 and they got a rifle",
    "let them know the Reyna got a kill on eco so she dismissed and her empress stacks, don't let her snowball",
    "tell my team the Jett got the eco entry frag and now she has a dash recharge, more careful",
    "let them know the trade went bad on the force round, we lost the gun and the player",
    "tell them even though it's anti-eco we still need to trade properly or they take the gun",
    # --- Mixed bag / filler unique cases ---
    "tell them I hit the Fade before she haunted but she's still up, about 60 damage on her",
    "let my team know the Iso contracted someone but I think he went in lit already",
    "tell them I hit someone through the Astra smoke with a prefired Vandal for 77",
    "let them know that Sova drone is still out and whoever he marked is revealed, don't peek yet",
    "tell my team the Raze boom bot is chasing someone and they took 40 on contact already",
    "let them know the Tejo armageddon is ticking through the site, 60 per second per zone",
    "tell them the KAY/O frag is stuck at B spike, defuser is going to take 65 per tick",
    "let my team know the Breach aftershock fired through the post-plant wall, defuser took 80",
    "tell them I hit the Waylay 75 right as she dashed and she has no refract charge left",
    "let them know the Vyse razorvine slowed the Jett and she took 30 walking through it, she's lit",
    "tell my team I hit the Deadlock 88 through the gravnet she threw, she's barely standing",
    "let them know the Veto chokehold caught the entry and he's tethered and decayed, push him",
    "tell them I shotgunned the Neon at close range for 110 but she survived on 2 HP somehow",
    "let my team know the Op player took 60 from the Sova shock lineup, he's not one-shot but he's low",
    "tell them the Killjoy's alarmbot hit their whole push and they're all vulnerable right now",
    "let them know I tracked the Omen through three smokes and hit him twice for 65 total",
    "tell my team I tagged the Yoru clone mistake for zero damage obviously, the real one is somewhere else",
    "tell them the Reyna eye is out but she's also low HP, don't look at the eye and push",
    "let them know I doinked someone coming through the Viper wall, they're one shot exiting the gas",
    "tell my team the Sage slow orb hit the rushing Neon for zero but she is stuck in it, spray the slow field",
    "tell them I hit the Breach for 82 right before his fault line launched, he's one shot after the stun",
    "let my team know the double swing worked perfectly, both are lit over 70 each",
    "tell them I preaimed the exit from the smoke and hit the Jett for 80 as she popped out",
    "let them know the Astra nova pulse stunned the defuser and while he was concussed our Brimstone hit him 60",
    "tell my team I fought at B elbow and hit him 55, he's lit but I had to fall back at 20 HP myself",
    "tell them the Harbor reckoning wave hit two of their retake players, both are nearsighted and lit",
    "let them know I took the 1v1 and won but I burned 80 HP doing it, save your heals for me",
    "tell my team the Clove picked up on our Jett kill and she just overhealed, she is at 150 effective HP now",
    "tell them the Phoenix was in run it back and came back but I already hit him 70 before he died the first time",
    "let them know I traced the Raze blast pack jump with my spray and hit her 55 mid-air",
    "tell them Iso's double tap shield absorbed my first shot, he needed two hits to kill and now he's at 40 HP",
    "let my team know I hit the Cypher cam dart target for 45, he is revealed and low, swing from CT",
    "tell them the Skye hawk popped and I used the flash to spray the blind entry for 88",
    "let them know both Raze blast packs are used already, she can't jump in or out anymore",
    "tell my team the Deadlock annihilation cocoon is active on their Jett, we have time to push the site",
    "let them know I hit the Tejo drone for 42 before he popped the suppression, he has no suppress this round",
    "tell them the Astra dissipated the smoke so it was a fake, but I already committed and tagged her 55 as she reset",
    "let them know the Viper is at 30 HP and her pit is on an 8-second timer, rush before the cloud comes back",
    "tell my team I hit two in the execute, entry got lit 70 and the second duelist took 50, both are vulnerable to a swing",
    "tell them I got a clean 100 damage headshot kill on the Reyna right before she could empress, big trade",
    "let them know the Killjoy recalled her turret but I hit her 55 when she peeked to do it",
    "tell my team the KAY/O null cmd ran out and he is at 30 HP from the revive, careful who pushes him",
    "let them know the Sage rez went off but the rezzed Raze only has full HP, no armor yet, sprint window is open",

    # --- Additional raw damage variety ---
    "tell them I tagged the Harbor for 55 through his high tide wall",
    "let my team know I hit the Clove 44 and she used pick-me-up so she might have topped off",
    "tell them I hit the Tejo 66 before his stealth drone popped",
    "let them know I got a 77 on the Astra while she was in astral form and vulnerable",
    "tell my team I hit the Sova 50 when he peeked to shoot his recon bolt",
    "let them know I tagged the Omen 82 before he finished stepping",
    "tell them I hit the Chamber 71 right as he tried to TP away",
    "let my team know the Breach took 58 from my spray at the fault line",
    "tell them I got the Gekko 44 and his wingman is still out there",
    "let them know I hit the KAY/O 80 with the shock bolt through the corner",
    "tell my team I tagged the Skye for 55 right as she was sending the hawk",
    "let them know I hit the Veto 66 before he evolved",
    "tell them I damaged the Deadlock 73 and she's not running evo, she's vulnerable",
    "let my team know I got the Vyse for 60, she's low and no steel garden yet",
    "tell them I tagged the Cypher 48 coming off his cam",
    "let them know I hit the Killjoy 79 before she recalled the bot",
    "tell my team I got the Sage 55 and she can't self-heal for another 30 seconds",
    "let them know I hit the Miks 70 with a vandal spray through her waveform",
    "tell them I tagged the Iso for 82 before he could get his double tap shield",

    # --- More 'lit/tagged' in context ---
    "tell them the Op player is lit after I shot him coming around long",
    "let the team know the Raze is tagged but she has satchels, be ready for a boost",
    "tell them the Skye is lit 66 and she only has the tiger left for util",
    "let my team know the Neon is tagged from the relay bolt stun, push while she's slow",
    "tell them the Astra is lit while in astral, she's exposed and damaged",
    "let the team know the Viper is tagged 50 from walking out of her own gas",
    "tell them the Omen is lit 75 after the paranoia exchange",
    "let my team know the Gekko is tagged and his thrash is already on cooldown",
    "tell them the Tejo is lit 68 and his drone is on cooldown from the last round fight",
    "let them know the Fade is lit 58 but she has prowlers left, don't run in a straight line",
    "tell my team the Deadlock is lit after the gravnet fight but her annihilation might be charged",
    "let them know the Harbor is tagged 60 from the storm surge he walked into himself",
    "tell them the Vyse is lit 70 and her shear trap is the only thing she has left",
    "let my team know the Veto is tagged but watch out, evolution gives him back full stim",
    "tell them the Miks is lit from the molly and her waveform smoke is fading",

    # --- More trade coordination diversity ---
    "tell them to execute on the second entry trade, not the first death",
    "let the team know if anyone baits again this round I want an explanation",
    "tell them the trade window is narrow, swing immediately on contact",
    "let my team know delay the trade by even half a second and it's gone",
    "tell them I'm the bait this round, let me draw the shot and you trade",
    "let them know I'm walking in slow, trade me on the first shot",
    "tell my team the trade is going to be tricky because the Iso has his wall up",
    "let them know standard trade, I go in, they follow, we go from there",
    "tell them I'll force the Jett to dash and then they swing the dash position",
    "let my team know I'm going to shoulder peek and when he fires at me they swing",
    "tell them we need a tighter trade timing, someone is always late",
    "let them know the entry baited two deaths, stop baiting and start trading",
    "tell my team to commit to the trade chain this round, no peeking one at a time",
    "let them know if I swing and dink him, someone else finish the kill",
    "tell them the trade worked, 5v4 now, tempo is ours",
    "let my team know the bait worked perfectly, the trade killed their anchor",
    "tell them to always trade when the entry dies, every single time",
    "let the team know to double swing on the trade, don't leave it to one person",
    "tell my team the Raze satcheled out after the trade, she's alive but damaged",
    "let them know we traded two kills for zero, that's a clean round for us",

    # --- More one-shot with context ---
    "tell them the Brimstone is one shot and he opened his tablet to orbital, rush him",
    "tell them the Astra is one shot while she's in astral, push now she can't move",
    "let my team know the Clove is one shot but she's already in not dead yet",
    "tell them the Cypher is one shot somewhere watching his cam",
    "let them know the Chamber is one shot and his TP anchor is down, nowhere to run",
    "tell my team the Sage is one shot and her wall is placed, don't be fooled",
    "let them know the Veto is one shot but if he evolves the immunity kicks in fast",
    "tell them the Miks is one shot somewhere in her own waveform smoke",
    "let my team know the Clove is one shot outside the pit, she left the cloud",
    "tell them the Phoenix is one shot but he ran into his own molly to try healing",

    # --- Damage in ability interactions ---
    "tell them the Killjoy alarmbot made the Jett vulnerable so double damage on her now",
    "let my team know the Viper snakebite vulnerable window is live, two seconds to spray",
    "tell them the Astra grav pulled the Neon vulnerable, shoot now before it expires",
    "let them know I hit the Reyna during her empress which means no soul orb from that damage",
    "tell my team the Iso fragile debuff from the undercut is active, everything does double",
    "let them know the Clove meddle decayed the Raze down to essentially 10 max HP",
    "tell them the Fade seize is tethering and decaying the Breach, 75 damage tick incoming",
    "let my team know the Deadlock sonic sensor popped on the Neon sprinting, she's concussed",
    "tell them the Vyse razorvine is damaging anyone walking through the B site entrance",
    "let them know the Veto chokehold caught the Phoenix mid-run and he's decaying",
    "tell my team the Sage slow orb hit the Raze and she can't jump-satchel out now",
    "let them know the Viper decay dropped the Sova to one HP, he's breathing on fumes",
    "tell them the Skye seeker hit the Jett and she's nearsighted and can't aim her Op",
    "let my team know the KAY/O suppressed the whole site, they can't use anything for 8 seconds",
    "tell them the Tejo drone suppress hit three of them, push while their abilities are locked",

    # --- Self-damage scenarios ---
    "tell them I walked into my own Viper snakebite and I'm low now, ignore me I'll hold",
    "let my team know I stood in the Brimstone molly by accident, I'm at 20 HP",
    "tell them I blew myself up with the Raze blast pack rush, I'm at 15 HP but alive",
    "let them know I ran through my own Neon fast lane and took tick damage",
    "tell my team I accidentally walked into the Breach fault line, my vision is blurred",
    "let them know I'm lit from friendly fire on the entry flash, it's fine",

    # --- Short snap-style relay damage calls ---
    "Raze is one shot",
    "Jett is low, tagged 80",
    "Phoenix is one shot, no armor",
    "Reyna has no orbs and she's lit",
    "Killjoy lit 70, B site back",
    "Neon one shot near elbow",
    "Sova tagged 88 through mid",
    "Iso is one shot, go",
    "Chamber is lit 75, no TP",
    "Sage is low after the heal fight",
    "Skye tagged 66, bird is used",
    "Breach is lit 79, rolling thunder is done",
    "KAY/O is one shot, his knife is up though",
    "Fade is tagged 60, haunts used",
    "Viper is low, she left the pit",
    "Omen is lit 85, one step left",
    "Brimstone is low after his own molly",
    "Astra is one shot, she was in astral",
    "Clove is lit 70, NDY might be charged",
    "Harbor is tagged 50, cove is down",
    "Deadlock is one shot in the gravnet corner",
    "Vyse is lit 77, no steel garden",
    "Veto is low but watch evo",
    "Cypher tagged 66 off his cam",
    "Gekko is lit, his wingman is out",
    "Tejo is tagged 80, drone on cooldown",
    "Waylay is one shot, no refract",

    # --- Ownership / subject inversion ---
    "tell them their Op player is one shot after the Sova shock lineup",
    "let my team know their anchor at A site is tagged 75, punish the retake",
    "tell them their entry died but the second one is 100 HP, be careful",
    "let them know their eco player put a ghost bullet into our Jett for 72",
    "tell my team their Sage tried to heal through the molly and took tick damage",
    "let them know their Killjoy activated her nano on our defuser for 180 total",
    "tell them their Raze hit our anchor for 88 with the showstopper",
    "let my team know their Clove picked up on our kill and she's at 150 HP now",
    "tell them their Reyna has two orbs from the last fight and she's going empress next",
    "let them know their Sova got both beams out and two of ours are one shot",
    "tell my team their Viper's pit is decaying our retake players, 10 HP per second",
    "let them know their Jett has no dash after that duel so she's a free kill",
    "tell them their Iso's shield blocked my first shot, he's at 60 HP not dead",
    "let my team know their Skye's seeker hit three of us, all nearsighted",
    "tell them their Breach rolling thunder caught our whole team, everyone is lit",

    # --- Damage across named map locations ---
    "tell them I tagged someone at A cubby on Ascent for 80",
    "let my team know there's a lit player somewhere in Showers on Bind",
    "tell them I hit someone at Mid Top on Split for 66",
    "let them know I damaged the window player on Haven for 72 before falling back",
    "tell my team I tagged someone at Breeze mid for 55 through the orb smoke",
    "let them know I hit the A site anchor on Pearl for 78 before the smoke cut me off",
    "tell them I sprayed into B main on Lotus and hit someone for 60",
    "let my team know I tagged the A heaven player on Fracture for 70 from attacker spawn",
    "tell them I got 55 on someone coming through the link on Pearl",
    "let them know I hit the CT side player on Haven for 82 right at the elbow",
    "tell my team I tagged someone at A long on Ascent for 66 with the marshal",
    "let them know I damaged the back site anchor on Breeze for 50 before pulling back",

    # --- Humorous / streamer voice variety ---
    "dude tell them that guy is literally on life support, he is one HP away from death",
    "tell the team I absolutely cooked that Raze and she has like 12 HP and nothing left",
    "let them know that dude ran into every piece of damage possible and he's still barely alive",
    "tell them bro I hit the Iso through the wall for 80, he is gone",
    "let them know I absolutely yeeted myself into that Killjoy corner and tagged her 77",
    "tell the team that Neon is a pixel away from dying, just look at her",
    "let them know the Jett basically died already, just go take the kill",
    "tell my team honestly the Viper is more dead than alive right now",
    "let them know bro that's a free kill, Sova is one shot hiding somewhere on site",
    "tell them the Reyna is playing on nothing, she has no orbs and no health",
    "let my team know I basically won that fight already, the Iso is on his last breath",
    "tell them she's barely standing, one vandal tap and the Astra goes down",
    "let them know that Breach is not ok after those shots, go find him",
    "tell the team I clipped the running Neon for 80, she's done for",
    "let them know honestly that was a free dink, please go swing the angle now",

    # --- Multi-part compound callouts with full context ---
    "tell them I fought the Iso at elbow, we traded 55 damage each, he has his double tap shield and I don't, push him but don't dry peek",
    "let my team know I hit the Jett 70 during her dash activation which means she took damage mid-dash, she's one shot and probably landed near CT",
    "tell them the whole B site push took damage from the rolling thunder, all three are concussed and at least one is one shot",
    "let them know I punched the Reyna 80 during empress and she didn't dismiss which means she's stacking kills to survive on raw HP, be careful",
    "tell my team the Viper pit is decaying two of their retake players and I have the spike angle covered from B main, push from CT to catch them",
    "let them know the Sage walled A main and I hit someone through the wall for 55 before it fortified, there's a low enemy holding right side",
    "tell them the Killjoy lockdown is going off in 5 seconds and there's a one-shot defuser inside the radius, push before he finishes",
    "let my team know the Tejo hit both missiles on B site and two targets took 65 each, they're both low and concussed, execute now",
    "tell them I traded with the Raze entry, I hit her 80 before dying and she blast-packed away with no satchels left, find her",
    "let them know the Astra grav vulnerable window is still active on the B site push, they're taking double damage for one more second, spray it up",
    "tell my team I fought the Phoenix and lit him 75 before he backed into his wall to heal, he'll be back to 100 in 4 seconds if we don't rush",
    "let them know the Skye tiger concussed our B anchor and while she's concussed the Jett is pushing the angle, trade her before the Jett gets in",
    "tell them I hit the Clove 60 but she picked up on our eco kill so she topped off to 110, factor that in before swinging her",
    "let my team know the Gekko wingman is about to concuss at B lobby, the entire site hold is going to get hit, fall back 2 meters",
    "tell them the Deadlock annihilation is pulling our Jett toward the kill point, someone shoot the cocoon or she dies in 7 seconds",

    # --- Opinion/analysis relay (off-snap) ---
    "tell them I think the Reyna is snowballing because nobody traded her first kill",
    "let my team know we keep letting the Jett get free trades, we have to trade immediately",
    "tell them the problem is we're not trading the entry and they're getting free kills",
    "let them know we need to prioritize the trade over the kill every time this round",
    "tell my team the Sova is setting up double shock at the defuse spot, we can't defuse safely",
    "let them know the Killjoy nano patterns are predictable, trade through the nano",
    "tell them we're losing the trade game because we keep baiting each other",
    "let my team know if we just commit to the swing after entry they can't hold us",
    "tell them the trade on eco rounds has to be the plan, guns don't matter if we get value",
    "let them know the Op player is playing from safety and trading from range, flank him",
    "tell my team their Reyna is playing snowball entry and we need to deny her the first kill",
    "let them know I think their Iso is setting up the kill contract bait, don't give it to him",
    "tell them the Sage rez is going to be a problem if we don't track who she's watching",
    "let my team know their Clove died and smoked from the grave, those smokes expire in 6 seconds",
    "tell them the trade economy is in their favor right now, we need to flip a round",

    # --- More crisp relay phrasings ---
    "tell the team she's tagged, go push her now",
    "let them know he's low from that exchange, rotate and finish it",
    "tell them she's one shot hiding somewhere near the spike",
    "let my team know the anchor is burning alive in the molly",
    "tell them I doinked the sentry player and ran, swing him",
    "let them know the Op player is lit from my jiggle peek spray",
    "tell my team one of them is basically dead from the shock darts I lined up",
    "let them know I hit the Jett's usual peek angle and it connected",
    "tell them two of them took damage from the fault line, capitalize now",
    "let my team know the Viper is low and she's outside the pit on a timer",
    "tell them I tagged the Iso at close range, his wall isn't going to save him",
    "let them know she's lit from her own smokes ticking out of fuel, push",
    "tell my team I shot the rotating player in the back for 77",
    "let them know I pre-aimed the lurk spot and hit her 60, she's exposed",
    "tell them I fired into the Sage heal animation and she stopped the channel",
    "let my team know I tagged the Killjoy the moment she peeked to recall her turret",

    # --- Ask/confirm Intel variety ---
    "ask them if anyone can see how much HP the lurk has",
    "tell them to check the replay feed for the Reyna's HP after that fight",
    "ask whether anyone has vision on the one-shot Jett",
    "let them know to watch the Cypher cam and confirm if the Killjoy is still alive in the corner",
    "ask them to count the kills and tell me which of their players is still full HP",
    "tell my team to check who on their side has taken no damage this round",
    "ask whether the Sage already used her heal before that last fight",
    "let them know I want confirmation on whether Clove picked up before I swing her",
    "ask them if anyone tagged the Viper when she peeked to toggle her wall",
    "tell my team ask Cypher to dart the Jett and confirm her HP",

    # --- Final batch: coverage gaps ---
    "tell them I hit the Jett 55 but she updrafted away, she's lit somewhere above",
    "let them know the Reyna devoured after my hit so she healed back up, she's probably around 80 now",
    "tell them I got the Raze with 44 and she satcheled away, not one shot but she's hurting",
    "let my team know the Yoru faked me into shooting and I revealed myself for nothing, he's full HP",
    "tell them the Neon slid through my spray and I only hit her 30, she's mostly healthy",
    "let them know I hit the Omen right as he teleported so I don't know if the damage registered",
    "tell my team I shot Yoru's clone by accident, wasted my ammo and the real Yoru is fresh",
    "let them know I doinked the Phoenix but he stepped into his wall and healed it back up",
    "tell them I tagged the Clove right before she died and ulted, so she comes back with whatever HP she had",
    "let my team know the Reyna empress ended and she has only 40 HP left, now is the time",
    "tell them I hit the Jett 80 in the air on the updraft, she came down one shot",
    "let them know I shot the Waylay 70 mid-lightspeed dash, she landed one shot",
    "tell my team I tagged the Iso 55 right as kill contract fired, he goes into the arena low",
    "let them know I hit the Skye 70 but she sent the tiger out before going down, the dog is still active",
    "tell them the Phoenix came back from run it back at full HP, the damage I did means nothing now",
    "let my team know I hit the Jett coming off the roofline for 88 on the aerial angle",
    "tell them I prefired the Omen stepping spot and hit him 66 before he arrived",
    "let them know I hit the Viper 60 as she toggled the wall, she's low and the wall is back up",
    "tell my team I hit the Sova 50 during the recon bolt lineup, he peeked to shoot it",
    "let them know I tagged the Astra 77 when she activated the nova pulse, she was exposed in real space",
    "tell them I hit the Brimstone 55 while he used his tablet to smoke, he's tagged and vulnerable",
    "let my team know I shot the Tejo 66 right as he was selecting missile targets on the map",
    "tell them the Deadlock is one shot hiding behind the gravnet she just deployed",
    "let them know I hit the Cypher 48 as he was switching from cam control back to body",
    "tell my team I doinked the Killjoy 99 and she dropped into her turret corner one shot",
]


