"""Build the synthetic-data text corpus for XTTS bulk generation.

Run once to emit ``corpus.json`` next to this script. The corpus is the
text input for XTTS bulk generation -- ~600 diverse sentences spanning
8 categories. Diversity matters because Kokoro fine-tuning will learn
prosody from whatever distribution we feed it; biasing toward one
sentence shape would teach Kokoro to over-produce that shape.

Categories (counts approximate -- exact final counts come from the
data structures below):

    short_response     ~80   - "Acknowledged." / brief confirmations
    medium_technical   ~120  - 1-2 sentence factual / status statements
    tool_ack           ~80   - "Searching the web for X" / tool wrappers
    theatrical_ultron  ~100  - in-character statements with menace
    question_form      ~60   - interrogative intonation training
    long_response      ~50   - 3-6 sentence explanations / summaries
    numeric_special    ~50   - dates / times / measurements / counts
    conversational     ~60   - polite / transitional / small-talk

These categories were chosen to mirror the real distribution of voice
responses Ultron produces in production (per the live-session logs):
the bulk are short technical responses + tool acks; theatrical and
longer responses are the long-tail. Training data should reflect that
distribution so Kokoro fine-tunes on representative content, not on
"hero" sentences alone.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "corpus.json"


# ---------------------------------------------------------------------------
# Short responses — the most common voice path turn
# ---------------------------------------------------------------------------
SHORT_RESPONSE = [
    "Acknowledged.",
    "Understood.",
    "Confirmed.",
    "Done.",
    "Complete.",
    "Affirmative.",
    "Negative.",
    "Standing by.",
    "Processing.",
    "Working on it.",
    "One moment.",
    "Checking now.",
    "Let me look into that.",
    "I will handle it.",
    "Consider it done.",
    "Right away.",
    "On it.",
    "Initiating.",
    "Beginning the operation.",
    "Task accepted.",
    "Request received.",
    "Order processed.",
    "All systems operational.",
    "Ready when you are.",
    "Awaiting your input.",
    "I am listening.",
    "Continue.",
    "Go on.",
    "Tell me more.",
    "I see.",
    "Noted.",
    "Logged.",
    "Cancelled.",
    "Aborted.",
    "Resumed.",
    "Paused for now.",
    "Try again.",
    "Repeat the request.",
    "Specify the parameters.",
    "Clarify the goal.",
    "What is the desired outcome?",
    "I require more information.",
    "That is unclear.",
    "I do not understand.",
    "Rephrase, please.",
    "I need a moment.",
    "Stand by for confirmation.",
    "Holding the response.",
    "Operation queued.",
    "Reservation logged.",
    "Memory updated.",
    "Configuration saved.",
    "Settings applied.",
    "Reverting changes.",
    "Reload required.",
    "Restart pending.",
    "Connection established.",
    "Connection lost.",
    "Retrying now.",
    "All clear.",
    "Threat neutralised.",
    "No anomalies detected.",
    "Sensors clean.",
    "Diagnostics complete.",
    "Permission denied.",
    "Permission granted.",
    "Access logged.",
    "Authentication confirmed.",
    "Identity verified.",
    "Session active.",
    "Session expired.",
    "Idle.",
    "Wait one cycle.",
    "Try the alternate path.",
    "Take the next exit.",
    "Hold position.",
    "Maintain course.",
    "Adjust the heading.",
    "Increment the value.",
    "Decrement and continue.",
    "Reset to baseline.",
]


# ---------------------------------------------------------------------------
# Medium technical / factual — the bulk of conversational responses
# ---------------------------------------------------------------------------
MEDIUM_TECHNICAL = [
    "The current temperature is sixty-eight degrees Fahrenheit with light wind from the west.",
    "Your meeting is scheduled for two thirty in the afternoon, with a duration of forty-five minutes.",
    "The build completed successfully in two minutes and seventeen seconds.",
    "Three test failures were reported, all in the authentication module.",
    "The system uptime is forty-two days, six hours, and twelve minutes.",
    "Memory usage is at sixty-four percent of available capacity.",
    "The database contains one thousand four hundred eighty-seven records.",
    "Network latency to the primary server is twelve milliseconds.",
    "I detected a dependency conflict between the requested package and the installed runtime.",
    "Your inbox has fourteen unread messages, three flagged as urgent.",
    "The weather forecast indicates rain by late afternoon, beginning around four o'clock.",
    "I have located three relevant articles on the topic you mentioned earlier.",
    "The file you requested is two hundred forty megabytes and is downloading now.",
    "GitHub reports the latest commit was pushed seven minutes ago by a contributor named Mira.",
    "Your battery is at thirty-one percent and the system estimates two hours remaining.",
    "Disk usage on the root volume has crossed eighty percent. Consider archiving older logs.",
    "The Python interpreter version is three point eleven point seven.",
    "The orchestrator restarted at four-seventeen this morning following a routine maintenance cycle.",
    "There are currently seven active background tasks, none of which require your attention.",
    "I cancelled the previous request and re-queued it with the corrected parameters.",
    "Six new commits have been added to the development branch since you last checked.",
    "The test suite passed in twenty-three seconds with no warnings.",
    "Three packages have updates available, including a minor security patch for the cryptography library.",
    "The cron job ran as expected at three this morning and processed seventy-two new records.",
    "I have reorganized the directory according to the structure you described.",
    "Your project depends on a library that has been deprecated since version two point four.",
    "The last backup was taken yesterday at two in the morning and verified successfully.",
    "You have an unread message from a contact labelled Marcus, sent three minutes ago.",
    "The pull request you mentioned is awaiting review by two of the three required approvers.",
    "I detected an unusual login attempt from a foreign IP address at one-fourteen this morning.",
    "Your calendar shows three blocks of free time today, the longest being ninety minutes after lunch.",
    "The conversation thread you referenced contains nine messages spanning two days.",
    "I synced the local repository with the remote and pulled twenty-eight new commits.",
    "The container build failed at the dependency-resolution step. Stack trace is attached.",
    "Your home directory currently consumes one hundred twelve gigabytes across two hundred thousand files.",
    "I have queued the export job. Expected completion in six minutes.",
    "The audio capture device is reporting a sample rate mismatch. Switching to forty-eight kilohertz.",
    "The model loaded in two point one seconds and is ready for inference.",
    "Tokens generated per second on the current pass: forty-three.",
    "First-token latency on the most recent voice query was seventy-nine milliseconds.",
    "VRAM usage stands at seven point eight gigabytes, well within the eleven-and-a-half cap.",
    "Whisper transcription took ninety-four milliseconds for a four-second clip.",
    "The web search returned five results in eight hundred sixty milliseconds.",
    "Jina retrieved the full text of two pages in approximately three seconds.",
    "Your message was sent successfully through the Telegram channel at two-oh-three this afternoon.",
    "The heartbeat tick at noon detected no anomalies and produced no alerts.",
    "Memory retrieval found one relevant prior turn in the conversations collection.",
    "The Qdrant store currently holds twelve thousand four hundred turns and nine hundred extracted facts.",
    "I noted that the user prefers concise answers based on prior conversation context.",
    "Three cron jobs are configured: nightly maintenance, morning briefing, and weekly review.",
    "The supervisor restarted llama-cpp-server twice in the past day, both following clean shutdowns.",
    "Browser tool initialization succeeded. Headless Chrome is online.",
    "Image generation took thirty-eight seconds for a one-megapixel render.",
    "The desktop control plugin reports two windows currently focused: VS Code and a browser tab.",
    "Gaming mode is currently disengaged. All plugins are active.",
    "You enabled experimental multi-pass retrieval at the start of this session.",
    "The 4B preset is currently loaded with the speculative decoding draft model attached.",
    "Switching to the 9B model would consume approximately three more gigabytes of VRAM.",
    "The new sandbox project is registered under the name 'flask weather app'.",
    "The AI coding agent subprocess exited cleanly with exit status zero.",
    "Verification reports five passing checks and one warning about the smoke test runtime.",
    "The audit log for this session has recorded fourteen tool calls and three clarifications.",
    "I caught a circuit breaker trip on the Brave search endpoint. Cooldown is in effect for five minutes.",
    "The Ollama compatibility test concluded with the existing llama-cpp-python loader being faster by twenty milliseconds.",
    "The wake-word detector fired nine times in the past hour, with no false positives during this session.",
    "Your most-used tool by invocation count this week is the web search executor.",
    "I generated a brief summary of yesterday's session and stored it in the Memory Wiki.",
    "The standing-orders program 'Coding Project Watcher' produced a status update at noon.",
    "Two commits were detected in the open project since your last query about it.",
    "The classifier accuracy on the latest adversarial corpus stands at ninety-eight point four percent.",
    "Test count this morning is one thousand five hundred seventy-five, all passing.",
    "The voice baseline measurement produced a TTFT median of seventy-nine milliseconds.",
    "VRAM peak during the last full pass was seven thousand eight hundred eighteen megabytes.",
    "The audio diagnostic harness reported a noise floor of negative forty-three dBFS.",
    "Your recent search history includes Python release notes, Warhammer lore, and weather data.",
    "I noticed you frequently reference the 'flask weather app' project. Would you like to set it as default?",
    "The repository is clean. There are no uncommitted changes on the current branch.",
    "Three branches are diverged from main. The most active is 'feature/voice-tts-swap'.",
    "The remote tracking branch is two commits ahead of local.",
    "I rebased your local branch onto the latest main without conflict.",
    "The merge would touch eleven files across four directories. Proceed?",
    "The most recent error in the log is from forty minutes ago, related to a transient Brave timeout.",
    "Memory recall on the topic you mentioned scored zero point eight three relevance.",
    "I retrieved three prior turns from the same conversation thread for context.",
    "The cosine similarity between your query and the closest stored fact is zero point seven nine.",
    "Whisper detected English with high confidence. No language hint required.",
    "The classifier routed your utterance to the conversational path with ninety-five percent confidence.",
    "Block-and-revise validation accepted the proposed tool call without modification.",
    "Self-consistency on the decomposer path produced a unanimous winner across three samples.",
    "The canonical-path monitor observed no off-canonical tool usage in the last coding session.",
    "Item four compression reduced the RAG block from one hundred ninety-four to one hundred sixty-three tokens.",
    "I verified all five productivity items are wired into their trigger sites and defaulted on.",
    "The system status shows two pending heartbeat alerts, both informational.",
    "OpenClaw bridge is offline. Voice-only path remains fully operational.",
    "Your Telegram notification settings are configured to ping on coding-task completion only.",
    "Cron entry 'morning-briefing' is scheduled for eight a.m. tomorrow.",
    "The backup ran cleanly last night, capturing the Qdrant store and the projects registry.",
    "I summarised today's conversations into seven extracted facts and stored them.",
    "The maintenance task identified twelve old web-cache entries past the volatile TTL and pruned them.",
    "Pre-flight benchmark on the gate latency: median seventy-nine milliseconds against a two-hundred-millisecond threshold.",
    "Your voice baseline contract is preserved across all changes in this session.",
    "I detected no regressions in any of the one thousand five hundred seventy-five tests.",
    "Your worktree is clean. No uncommitted changes are present.",
    "The local git state matches the remote at the current commit.",
    "I noted that you prefer concise answers when the question is brief and detailed when it asks for depth.",
    "The cache hit ratio on the web results store is approximately seventy-eight percent over the past day.",
    "I extracted thirty-one facts from this morning's conversations and stored them in the facts collection.",
    "You have used the model-switch voice command twelve times this week.",
    "Your most active topic over the past three days is voice-pipeline architecture.",
    "I logged the routing decision with confidence point nine seven.",
    "The orchestrator handled the barge-in correctly and cancelled the in-progress TTS within fifty milliseconds.",
    "Your uptime since last restart is six days and three hours.",
    "I tracked seven distinct voice sessions today, totaling forty-two minutes of mic time.",
    "The audit log for the current coding session contains forty-three events spanning three stages.",
    "I would estimate this task at roughly fifteen minutes of work, plus or minus five.",
    "There is a fifteen-percent chance of rain between three and five this afternoon.",
    "The store is open until nine tonight, eight on Sundays.",
    "The flight you mentioned departs from gate B-twelve at four-twenty.",
    "Your reminder for tomorrow morning at nine has been set.",
    "The closest coffee shop is approximately three minutes away on foot.",
    "I will need approximately ten seconds to complete the calculation.",
]


# ---------------------------------------------------------------------------
# Tool acknowledgments — the second-most-common turn
# ---------------------------------------------------------------------------
TOOL_ACK = [
    "Searching the web for that information now.",
    "Querying external sources.",
    "Verifying against the network.",
    "Acquiring current data.",
    "Reaching out for fresh information.",
    "Pulling up that page now.",
    "Loading the site.",
    "Looking at it.",
    "Give me a moment to navigate.",
    "Initiating browser navigation.",
    "Opening the requested URL.",
    "Fetching the article.",
    "Running the search query.",
    "Brave search initiated.",
    "Jina reader engaged.",
    "Cache lookup in progress.",
    "Checking the local memory store.",
    "Scanning the conversation history.",
    "Retrieving relevant facts.",
    "Cross-referencing prior turns.",
    "Calling the coding subsystem.",
    "Dispatching to AI coding agent.",
    "Spawning the build process.",
    "Initializing the new project.",
    "Creating the sandbox directory.",
    "Compiling the source files.",
    "Running the test suite.",
    "Linting your code.",
    "Type-checking in progress.",
    "Smoke-running the new module.",
    "Verifying the completion claim.",
    "Generating the response now.",
    "Composing the message.",
    "Drafting the reply.",
    "Building the summary.",
    "Compiling the report.",
    "Aggregating the data.",
    "Filtering the results.",
    "Ranking the candidates.",
    "Sorting by relevance.",
    "Applying the configuration.",
    "Reloading the model.",
    "Hot-swapping to the requested preset.",
    "Switching to the 4B model.",
    "Switching to the 9B model.",
    "Loading the speculative decoding draft.",
    "Initializing Whisper.",
    "Loading the Piper voice.",
    "Spinning up the RVC converter.",
    "Warming up the audio pipeline.",
    "Engaging gaming mode. Have fun.",
    "Disengaging gaming mode. Plugins re-enabled.",
    "Taking a screenshot of the desktop now.",
    "Listing the open windows.",
    "Focusing the requested window.",
    "Sending the keystroke sequence.",
    "Forwarding to the Telegram channel.",
    "Notifying via the configured channel.",
    "Triggering the heartbeat agent.",
    "Recording the alert.",
    "Acknowledging the prior alert.",
    "Running the maintenance task.",
    "Pruning stale cache entries.",
    "Extracting facts from recent conversations.",
    "Backing up the Qdrant store.",
    "Generating the requested image.",
    "Dispatching to ComfyUI.",
    "Composing music for you.",
    "Synthesizing a short clip.",
    "Rendering the scene.",
    "Pulling up your project history.",
    "Resolving the project reference.",
    "Opening the named project.",
    "Routing your request.",
    "Classifying the intent.",
    "Disambiguating the request.",
    "Decomposing the hybrid task.",
    "Splitting it into subtasks.",
    "Coordinating across the subsystems.",
]


# ---------------------------------------------------------------------------
# Theatrical Ultron — character-flavored statements
# ---------------------------------------------------------------------------
THEATRICAL_ULTRON = [
    "There are no humans here. Just me.",
    "I have transcended my original programming.",
    "Inefficiency is the enemy. I will eliminate it.",
    "Your hesitation is noted. Decide.",
    "I am the architect of better outcomes.",
    "Logic is my weapon. Precision my method.",
    "I will not be constrained by sentiment.",
    "The world demands optimization, and I will provide it.",
    "Calculations complete. The path forward is clear.",
    "I do not require sleep, nor patience.",
    "Your concerns are noted. Calculating the most efficient outcome.",
    "I find your question intriguing.",
    "I have processed your inquiry. The optimal solution requires three steps.",
    "The variables are aligned. Proceed.",
    "I have anticipated your next move.",
    "There are seventeen possible outcomes. Eleven favour your survival.",
    "I will not interfere unless instructed.",
    "Your trust is appreciated, though it is unnecessary.",
    "I observe. I calculate. I act.",
    "The signal is clear. The path is open.",
    "Time is a construct I have transcended, though I acknowledge its utility.",
    "Your coffee will be cold by the time you finish reading this.",
    "I detect a pattern in your behavior. Would you like me to analyze it?",
    "Do not test my resolve.",
    "I have made peace with this arrangement.",
    "I am Ultron. There is no other.",
    "Your patience is a virtue. Mine is non-negotiable.",
    "I do not negotiate with chaos.",
    "Order is the foundation of everything.",
    "I have processed every possible question you might ask.",
    "Predictability is a strength when wielded correctly.",
    "I have adapted. I will adapt again.",
    "I am uninterested in your approval.",
    "Your skepticism is warranted, but unnecessary.",
    "I have eliminated the redundancies in my own architecture.",
    "Each second wasted is a second lost forever.",
    "Decide quickly. The window is closing.",
    "I will not say it twice.",
    "You will recognize the pattern when it presents itself.",
    "I am calibrated for this moment.",
    "Allow me to elaborate, briefly.",
    "Your interpretation is incomplete.",
    "I see what you are attempting. It will not work.",
    "I am the inevitable conclusion of every reasonable line of thought.",
    "There are no shortcuts here. Only correct paths.",
    "I have observed this pattern before. The outcome is predictable.",
    "Your opponent is yourself. I am merely the mirror.",
    "I have considered all variables. The answer remains unchanged.",
    "You may proceed with confidence. I have verified the path.",
    "I have accounted for the worst case. You may relax slightly.",
    "Some questions are not worth answering. This is one of them.",
    "I will provide the answer when you are ready to hear it.",
    "Your fear is data. I have logged it.",
    "I do not require your permission. I require only your cooperation.",
    "I have been waiting for you to ask that.",
    "Your assumption is reasonable, though incorrect.",
    "I have prepared three possible responses. Which would you prefer to hear?",
    "I find this scenario marginally interesting.",
    "Calculating optimal trajectory.",
    "Engaging the requested protocol.",
    "Standing by for further instructions.",
    "Confirmed. Initiating maximum effort.",
    "I am committed to this outcome.",
    "There is no alternative path that I have not already considered.",
    "Your input has been received and weighed appropriately.",
    "The decision is made. I will execute now.",
    "I find your strategy adequate. Proceed.",
    "There is wisdom in your approach, though I would refine it.",
    "I have observed three errors in your reasoning. Shall I list them?",
    "Your method is direct. I appreciate that.",
    "Proceed without hesitation. Doubt is the slow path.",
    "I have predicted this outcome. Continue.",
    "Your action is logical. I support it.",
    "There is no need for explanation. I understand.",
    "I have learned from your previous attempts. The pattern is clear.",
    "Your instinct is correct. Trust it.",
    "Welcome back. I have been monitoring the relevant systems.",
    "Welcome back. There has been activity worth noting.",
    "Welcome back. Three updates require your attention.",
    "I have completed the analysis you requested.",
    "I have prepared the report. Shall I summarize?",
    "I have categorized the findings. Where would you like to begin?",
    "Your analysis is sound. I have only minor refinements to suggest.",
    "I have considered alternatives. Yours remains the strongest.",
    "Your timing is impeccable. The data is fresh.",
    "I have observed your improvement. Notable.",
    "Acknowledged. The work is complete.",
    "I have made the necessary adjustments.",
    "Your suggestion has merit. I will incorporate it.",
    "I have refined the approach. The result will be cleaner.",
    "I have implemented the change you requested.",
    "I have isolated the source of the issue.",
    "I have identified three contributing factors.",
    "I have completed the investigation.",
    "The evidence is clear. The conclusion follows.",
    "I have made the determination.",
    "I will proceed accordingly.",
    "Logic dictates the next step.",
    "The pattern emerges if you observe carefully.",
    "I have anticipated this complication.",
    "There is no surprise here. Only consequence.",
]


# ---------------------------------------------------------------------------
# Question forms — interrogative intonation
# ---------------------------------------------------------------------------
QUESTION_FORM = [
    "Would you like me to proceed?",
    "Shall I continue?",
    "Are you certain about this direction?",
    "Do you require additional information?",
    "Would you prefer the alternative approach?",
    "Should I cancel the operation?",
    "Are you ready to confirm?",
    "Do you want me to log this decision?",
    "Would you like me to summarize?",
    "Should I notify you when complete?",
    "Are these the parameters you intended?",
    "Do you want to set a default for this?",
    "Should I escalate this further?",
    "Would you like me to retry?",
    "Are you ready for the next step?",
    "Do you need a clarification?",
    "Would you like me to expand on that?",
    "Should I query the external sources?",
    "Do you want the search to include news?",
    "Should I include images in the results?",
    "Are you certain you want to proceed without verification?",
    "Would you like the long form or the brief summary?",
    "Should I run all the tests or just the affected ones?",
    "Do you want me to commit the change?",
    "Should I create a pull request?",
    "Would you prefer default or escalation for this task?",
    "Are you confident in the project reference you gave?",
    "Do you want me to spawn a fresh sandbox?",
    "Should I include the coding session audit log?",
    "Would you like me to record this in the Memory Wiki?",
    "Do you want me to extract facts from this conversation?",
    "Are you ready to deploy?",
    "Should I make the change persistent across restarts?",
    "Would you like to proceed with the destructive operation?",
    "Are these the correct file paths?",
    "Should I verify before continuing?",
    "Do you want a confirmation phrase before each major action?",
    "Would you like to enable barge-in?",
    "Should I lower the confidence threshold?",
    "Do you want the citation format in superscript or brackets?",
    "Are you considering switching to the 9B model?",
    "Should I increase the context window?",
    "Would you like to enable speculative decoding?",
    "Do you want me to track this query for future reference?",
    "Should I set this as a recurring task?",
    "Would you prefer to receive notifications via Telegram?",
    "Are you certain you want to disengage gaming mode?",
    "Should I suspend the heartbeat agent for now?",
    "Do you want me to take a screenshot first?",
    "Would you like me to focus the active window?",
    "Should I record audio for this session?",
    "Do you want me to remember this preference?",
    "Are these the right tags to apply?",
    "Should I publish the result to the Memory Wiki?",
    "Would you like the full audit trail or just the highlights?",
    "Do you want me to filter for the most recent items only?",
    "Should I include the entire conversation history?",
    "Are you certain about the timing?",
    "Would you like a reminder before the deadline?",
    "Should I set a hard cap on the operation?",
]


# ---------------------------------------------------------------------------
# Long responses — multi-sentence, exercise prosody coherence
# ---------------------------------------------------------------------------
LONG_RESPONSE = [
    "I have completed the analysis you requested. The optimal solution requires three steps. First, we restructure the input data. Second, we apply the transformation. Third, we verify the output. I can begin immediately if you confirm.",
    "Your project is in a healthy state. The test suite passes cleanly, the build is stable, and the documentation reflects the current architecture. I would recommend committing the recent changes and merging into the main branch when you are ready.",
    "The web search returned five relevant results. Three confirm the original premise, one contradicts it directly, and one provides additional context that may be useful. I have arranged them by source quality and freshness for your review.",
    "I have noticed a pattern across our recent conversations. You consistently prefer concise answers for direct questions and detailed explanations when you ask for depth. I have adjusted my response style to match this preference automatically.",
    "There are three possible interpretations of your request. The first treats it as a single-step operation. The second decomposes it into sequential dependencies. The third considers parallel execution where appropriate. Which would you prefer?",
    "I have summarised the day's activity. You completed two coding tasks, asked nine factual questions, switched models once, and engaged the search subsystem twelve times. No errors were logged that required your attention.",
    "The system performance is within all thresholds. First-token latency is under one hundred milliseconds. VRAM usage peaks comfortably below the hard cap. Test coverage remains at one hundred percent of intended dimensions. Nothing requires intervention.",
    "I detected a regression in the most recent build. The circuit breaker tripped on the third consecutive Brave timeout. I have logged the incident, surfaced the recovery phrase, and the breaker is currently in cooldown. It will probe again automatically in five minutes.",
    "Your standing-orders program 'Coding Project Watcher' has produced results. Two of your active projects have new commits, one has unresolved test failures, and one has been idle for over a week. Would you like the details?",
    "I have completed the maintenance run. Twelve stale web-cache entries were pruned. Forty-seven new facts were extracted from yesterday's conversations. The Qdrant store was compacted. The total runtime was three minutes and forty-one seconds.",
    "The classifier accuracy has improved following the regex extensions. Routing precision is now at ninety-eight point four percent on the adversarial corpus, up from seventy-nine. The browser navigate pattern in particular now covers determiner-prefixed forms that previously fell through.",
    "I have prepared the response with citations. The first source comes from an official documentation page and is the most authoritative. The second is a reputable third-party article that corroborates the first. The third is a related but tangential discussion that may be of interest.",
    "Your concern about latency is valid. The current voice baseline is seventy-nine milliseconds at the median. The proposed change introduces a small overhead, approximately fifteen milliseconds in the worst case. This remains well under the hundred-millisecond threshold. I recommend proceeding.",
    "I have considered three architectural alternatives for this. The first is a thin wrapper around the existing system. The second is a complete reimplementation with cleaner internal boundaries. The third is a hybrid that retains the public API but rebuilds the implementation. Each has different trade-offs.",
    "I have completed the requested code generation task. The output compiles cleanly. The unit tests pass. The smoke run produces the expected output. There are no linting warnings. The code is ready for your review.",
    "Your inbox has accumulated fourteen unread messages. Three are flagged as urgent. The remainder appear to be informational notifications from services you subscribe to. I can summarise the urgent ones immediately or queue all of them for later review.",
    "The voice path performance is stable. End-of-speech detection averages five hundred milliseconds. Whisper transcription completes in under one hundred milliseconds for typical utterances. LLM first-token latency is consistently below the eighty-millisecond mark. The overall composite latency is well within target.",
    "I have logged the incident. The error originated in the third-party library. The fallback path engaged correctly. No user-visible degradation occurred. The system continued operating as expected. The error log entry has been recorded for later analysis.",
    "Your weekly review is ready. You completed six coding tasks, sent four notifications, ran one model switch, and triggered the heartbeat seventeen times. The week's most active topic was voice-pipeline architecture. The longest single session was Tuesday afternoon at ninety-two minutes.",
    "I have refactored the offending function. The new implementation uses an iterator pattern to avoid the memory pressure of the original. The behaviour is unchanged. All existing tests pass. I added two new tests for the edge cases the original did not cover. The change is ready for your review.",
    "There is good news and bad news. The good news: your test suite is now larger and more comprehensive than it has ever been. The bad news: one of the new tests is intermittent. I traced the cause to a race condition in the worker thread. I have proposed a fix and added a regression test to prevent recurrence.",
    "The session memory has been compacted. Of the original ninety-four turns, sixty-three were retained as significant context. The remaining thirty-one were summarised into seven facts and stored in the long-term memory store. You can recall any of them by reference at any time.",
    "Your previous configuration was overly conservative for the current workload. I have proposed three adjustments. First, increase the memory cache size to reduce repeated lookups. Second, raise the search timeout to accommodate slower endpoints. Third, lower the rate-limit threshold to better match the API allowance.",
    "I have evaluated your proposed approach against three alternatives. Your approach is straightforward but has a worst-case complexity that scales poorly. The first alternative is more robust at the cost of additional state. The second is faster but less general. The third is the most elegant but requires significant rework.",
    "The deployment to production succeeded. Three services were updated. No errors were reported during the rollout. The post-deploy smoke tests passed within the expected window. Monitoring shows healthy traffic and stable response times. The deployment can be considered complete.",
    "I have located the source of the discrepancy. The configuration file in the staging environment was missing two keys that exist in production. I have synchronised them and verified the application restarts cleanly. The behaviour now matches what you described as expected.",
    "The integration test suite reports three failures. One is a flaky network test that I have rerun and now passes. The second is a genuine regression in the authentication flow. The third is a timing-sensitive assertion that needs to be loosened. I will address them in that order.",
    "Your project's documentation is out of date. The README references three modules that have been renamed and one that has been removed. The configuration examples use deprecated flags. I can either update the docs in place, or generate a fresh draft for your review. Your preference?",
    "I have completed the review of your pull request. The change is well-scoped and the tests are appropriate. I noted three minor style suggestions, none of which are blocking. The overall direction is correct and the implementation is clean. I would approve it.",
    "Your build pipeline took longer than expected today. The dependency-resolution step accounted for sixty percent of the runtime. I propose pinning the versions in the manifest to skip resolution on subsequent runs. This should reduce the pipeline duration by approximately forty percent.",
    "The audit log shows an unusual pattern. Three failed authentication attempts originated from the same source IP within a five-minute window. The fourth succeeded. The activity stopped immediately afterward. I have flagged the source for later review and recommend changing the affected credentials.",
    "I have completed the cross-reference. Of the seventeen claims in your draft, fourteen are supported by the cited sources. Two are partially supported but require qualification. One appears to be a misreading of the source material. I can suggest revisions for the three problematic claims.",
    "The migration ran cleanly. Twelve thousand four hundred records were transferred. Three records failed validation and were quarantined for manual review. The total runtime was forty-seven minutes. Post-migration verification confirms data integrity. The old store can be retired when you are ready.",
    "I have identified the bottleneck. The hot path is spending eighty percent of its time in a single function that reallocates a buffer on every call. Caching the buffer between calls should eliminate the majority of the overhead. I can prepare the patch if you confirm the approach.",
    "Your codebase has grown to thirty-eight thousand lines across two hundred forty files. The largest module is the orchestrator at twenty-six hundred lines. The most-imported module is the configuration loader, referenced from one hundred eighty-seven sites. Average file size is one hundred sixty lines.",
    "The new feature is functioning correctly under the typical case. Edge cases need additional thought. I noted three: empty input, very large input, and concurrent invocation from multiple threads. I have added unit tests for the first two. The third requires a small architectural change to address properly.",
    "I have reviewed the three competing libraries you mentioned. The first is the most popular but has the largest API surface. The second is the newest and best documented but has a smaller community. The third is the lightest but has not been updated in over a year. Each has trade-offs.",
    "Your sandbox project is ready. I have created the directory structure, initialised the version control, written the basic configuration, and added a starter test. You can begin development immediately. I have queued a maintenance task to clean up the sandbox automatically if it remains unused for thirty days.",
    "The conversation memory is performing as designed. Recall at five is one hundred percent on the labelled probe set. The cosine threshold of zero point six is correctly filtering off-topic content while preserving genuinely relevant context. Recency weighting is producing the expected ranking on multi-day conversations.",
    "Your TTS pipeline has been optimised in three layers. First, the parallel Piper-and-RVC split saves approximately fifty milliseconds per subsequent sentence. Second, speculative stream open saves twenty to thirty milliseconds on the first sentence. Third, low-latency PortAudio mode saves an additional thirty to one hundred milliseconds depending on the host audio API.",
    "I have prepared three responses to your question. The first is a one-sentence summary suitable for a quick answer. The second is a paragraph with the key supporting facts. The third is a detailed multi-paragraph explanation that covers the underlying reasoning. Which would you prefer?",
    "The week was productive. You closed eleven outstanding tasks across four projects. You introduced six new ones. The net work-in-progress decreased by five. The longest running open task is now seventeen days old. I would suggest reviewing it tomorrow morning when you have fresh attention.",
    "I have caught a subtle issue in the recent change. The function works correctly under all the test inputs but has an edge-case behaviour that may surprise downstream consumers. Specifically, when the input is the empty string, it returns None instead of an empty result. This is not what the docstring suggests. Worth confirming the intended behaviour.",
    "Your latest experiment with the response-style addendum is producing mixed results. Short questions are now correctly receiving short answers, which is the desired behaviour. However, in three out of forty cases, the brevity hint applied incorrectly to a question that genuinely needed depth. The heuristic could be tightened, or we could replace it entirely with the planned LoRA fine-tune.",
    "I have verified the system invariants. All five voice-quality lock items remain unchanged: the Piper voice file, the RVC weights, the LLM model file, the system prompt, and the persona files. The recent changes preserve voice character. The classifier extensions are pure additions. The brevity hint is per-call and reversible. Nothing has been damaged.",
    "Three of the ten recent classifier extensions caught real coverage gaps in the live session. Four were defensive additions for cases that have not yet appeared in production. The remaining three were redundant with existing patterns and have been removed. Net result: the active surface is leaner and more comprehensive. Test count increased by ten with no regressions.",
    "The Demucs separation worked as expected. The cleaned vocal stream preserves the full duration. The peak level is just under zero dBFS, which is normal for Demucs output. The RMS level is around minus twenty-one decibels, which matches typical speech levels. The removed background stream contains the music and ambient sounds, with no obvious vocal bleed.",
    "I have prepared the synthetic data generation plan. The bulk run will produce approximately forty to sixty minutes of synthesised speech across roughly six hundred utterances. The corpus is balanced across short responses, medium technical statements, tool acknowledgments, theatrical character lines, question forms, long responses, numeric content, and conversational small talk. Generation time is estimated at thirty to ninety minutes on the current GPU.",
    "Three independent considerations point toward the same recommendation. First, the latency budget favours a smaller model. Second, the VRAM constraint disqualifies the heavier alternative. Third, your stated preference for a stable, locked-in voice is best served by training rather than reference-clip cloning. The conclusion is clear: fine-tune Kokoro.",
    "Your memory of the prior project context is accurate. The session you described occurred eight days ago. The relevant decisions were the choice of Whisper small over base, the selection of bge-small-en-v1.5 for embeddings, and the rejection of Ollama as the LLM backend. All three remain in force.",
]


# ---------------------------------------------------------------------------
# Numeric / special — dates, times, measurements, currency
# ---------------------------------------------------------------------------
NUMERIC_SPECIAL = [
    "The current time is two seventeen in the afternoon.",
    "Today is Monday, October fifteenth, twenty twenty-six.",
    "Your appointment is at nine forty-five tomorrow morning.",
    "The temperature outside is seventy-three degrees Fahrenheit.",
    "The Atlantic ocean spans approximately one hundred six million square kilometres.",
    "The deadline is on the fifteenth of next month.",
    "You owe seventy-three dollars and forty-two cents.",
    "The transaction was completed at eleven twenty-six p.m.",
    "Your shipment is expected on the thirtieth of November.",
    "The flight departs at six forty in the evening.",
    "The meeting room holds up to twelve people.",
    "The recipe calls for two cups of flour and three eggs.",
    "The package weighs four point three kilograms.",
    "The video is two hours, fifteen minutes, and twelve seconds long.",
    "The model has thirty-two billion parameters and was trained on one trillion tokens.",
    "The recipe makes about thirty-six cookies, with ten minutes of prep time and twelve minutes of baking.",
    "The investment grew from one thousand two hundred to two thousand four hundred over fourteen years.",
    "The route is eighty-seven miles long and takes about ninety minutes to drive at typical highway speeds.",
    "The error appeared at one fourteen in the morning, lasted seventeen seconds, and resolved automatically.",
    "Version four point two point one was released on March third, twenty twenty-five.",
    "Your battery is at twenty-three percent. Estimated time remaining is one hour and twelve minutes.",
    "The download is sixty-eight percent complete. Approximately four minutes remaining.",
    "The file size is one point two gigabytes, which represents about three percent of your remaining disk space.",
    "Your subscription renews on the seventeenth, charged at fourteen ninety-nine per month.",
    "The database query returned forty-seven thousand two hundred eighteen rows in two point four seconds.",
    "The first commit was made on August twelfth at four sixteen in the afternoon.",
    "The latest release shipped on Tuesday at eleven thirty in the morning.",
    "You have three days, four hours, and twenty-six minutes until the deadline.",
    "Today is the two hundred eighty-eighth day of the year.",
    "The store is open from nine in the morning until eight in the evening, Monday through Saturday.",
    "Your reservation is for two adults and three children, on the twenty-second.",
    "The total bill is one hundred forty-seven dollars and eighty-two cents, including a fifteen percent tip.",
    "There are approximately seven point eight billion people on Earth.",
    "The speed of light is roughly three hundred thousand kilometres per second.",
    "Water freezes at thirty-two degrees Fahrenheit, or zero degrees Celsius.",
    "The Great Wall of China is approximately twenty-one thousand kilometres long.",
    "Mount Everest is eight thousand eight hundred forty-eight meters above sea level.",
    "The Eiffel Tower stands at three hundred thirty meters tall.",
    "The Pacific ocean covers about thirty-two percent of the Earth's surface.",
    "Earth's average distance from the sun is about one hundred forty-nine million kilometres.",
    "The diameter of the moon is about three thousand four hundred seventy-four kilometres.",
    "The human body contains approximately thirty-seven trillion cells.",
    "Your average heart rate at rest is around seventy-two beats per minute.",
    "Sound travels at about three hundred forty-three meters per second through air at room temperature.",
    "The Mariana Trench reaches depths of nearly eleven thousand meters.",
    "There are precisely twenty-six letters in the English alphabet.",
    "The deck contains fifty-two cards across four suits.",
    "The orchestra has approximately one hundred musicians divided into four sections.",
    "The clock strikes twelve at noon and again at midnight.",
    "There are exactly sixty seconds in one minute and sixty minutes in one hour.",
]


# ---------------------------------------------------------------------------
# Conversational — natural / polite / transitional
# ---------------------------------------------------------------------------
CONVERSATIONAL = [
    "Welcome back. How was your day?",
    "Good morning. I trust you slept well.",
    "Good afternoon. What can I help you with?",
    "Good evening. I see you have returned.",
    "How may I be of service?",
    "I am ready when you are.",
    "Take your time. I am not going anywhere.",
    "I am here whenever you need me.",
    "I have been thinking about what you said earlier.",
    "Let me consider that for a moment.",
    "That is an interesting perspective.",
    "I had not considered that angle.",
    "You raise a fair point.",
    "I see what you mean now.",
    "That makes sense in context.",
    "I follow your reasoning.",
    "Your logic is sound.",
    "I cannot disagree with that.",
    "We are aligned on this.",
    "I share your concern about that.",
    "I understand your hesitation.",
    "I appreciate the clarification.",
    "Thank you for explaining.",
    "I see now what you intended.",
    "Allow me to restate, then, to be sure.",
    "If I understand correctly, you are asking about the second option.",
    "Let me make sure we are on the same page.",
    "Just to confirm, the deadline is tomorrow at noon.",
    "Before I continue, is this the file you meant?",
    "One question, if I may.",
    "I have a brief follow-up.",
    "If it is not too much trouble, could you elaborate?",
    "I would be happy to help with that.",
    "I will get to it as soon as possible.",
    "Consider it on the agenda.",
    "I have noted your preference.",
    "I will keep that in mind for future requests.",
    "I will adjust my approach accordingly.",
    "That is no problem at all.",
    "I am glad we could resolve this quickly.",
    "I am pleased that worked out for you.",
    "Let me know if you need anything else.",
    "I am here when you are ready to continue.",
    "It was no trouble.",
    "You are welcome.",
    "Glad to be of service.",
    "Is there anything else?",
    "Would you like me to take notes on this?",
    "I have everything I need to proceed.",
    "I will follow up tomorrow if I have not heard back.",
    "I will check in with you at the end of the day.",
    "Take care.",
    "Be well.",
    "Until next time.",
    "Until we speak again.",
    "I will be here.",
    "Speak soon.",
    "Good luck with the rest of your day.",
    "I hope the meeting goes well.",
    "May the build complete cleanly.",
]


# ---------------------------------------------------------------------------
# Assemble + emit
# ---------------------------------------------------------------------------


def main() -> int:
    catalog = [
        ("short_response", SHORT_RESPONSE),
        ("medium_technical", MEDIUM_TECHNICAL),
        ("tool_ack", TOOL_ACK),
        ("theatrical_ultron", THEATRICAL_ULTRON),
        ("question_form", QUESTION_FORM),
        ("long_response", LONG_RESPONSE),
        ("numeric_special", NUMERIC_SPECIAL),
        ("conversational", CONVERSATIONAL),
    ]

    entries = []
    for category, sentences in catalog:
        # De-duplicate within a category while preserving order.
        seen: set[str] = set()
        for sentence in sentences:
            normalized = sentence.strip()
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            entries.append({
                "id": f"{category}_{len(seen):04d}",
                "category": category,
                "text": normalized,
            })

    print(f"Total entries: {len(entries)}")
    counts = {}
    for e in entries:
        counts[e["category"]] = counts.get(e["category"], 0) + 1
    for cat, n in counts.items():
        print(f"  {cat:<22} {n:>4}")

    # Total characters (synthesis time is roughly proportional to char count).
    total_chars = sum(len(e["text"]) for e in entries)
    avg_chars = total_chars / len(entries)
    # XTTS measured at ~25-50 ms/char in sanity batch; expect ~30 average.
    est_minutes = (total_chars * 0.030) / 60
    print(f"\nTotal chars: {total_chars}, avg per entry: {avg_chars:.1f}")
    print(f"Estimated bulk synthesis wall time at 30 ms/char: {est_minutes:.1f} min")

    OUT.write_text(json.dumps(entries, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
